### ISSUE TITLE
help for enabling multi session with 10.0.183262.267 at different winver

### ISSUE THREAD

**Issue by gifur** [stascorp/rdpwrap#965] opened 2020-01-19 12:56 UTC
it seems windows uses the same version termsrv.dll displayed 10.0.18362.267 at different version windows platform such as 10.0.18362.329 or 10.0.18363.592, and what more seriously is that it cannot work with already  section in rdpwrap.ini. when i login with another account, it occured with " the connections is limited .... "

the [10.0.18362.267] section at rdpwrap.ini :

[10.0.18362.267]
LocalOnlyPatch.x86=1
LocalOnlyOffset.x86=B7D06
LocalOnlyCode.x86=jmpshort
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=82FB5
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x86=1
SingleUserOffset.x86=50535
SingleUserCode.x86=nop
SingleUserPatch.x64=1
SingleUserOffset.x64=0DBFC
SingleUserCode.x64=Zero
DefPolicyPatch.x86=1
DefPolicyOffset.x86=50269
DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1FE15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x86=1
SLInitOffset.x86=5A77A
SLInitFunc.x86=New_CSLQuery_Initialize
SLInitHook.x64=1
SLInitOffset.x64=22DDC
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.18362.267-SLInit]
bInitialized.x86      =D577C
bServerSku.x86        =D5780
lMaxUserSessions.x86  =D5784
bAppServerAllowed.x86 =D578C
bRemoteConnAllowed.x86=D5790
bMultimonAllowed.x86  =D5794
ulMaxDebugSessions.x86=D5798
bFUSEnabled.x86       =D579C

bInitialized.x64      =F6A8C
bServerSku.x64        =F6A90
lMaxUserSessions.x64  =F6A94
bAppServerAllowed.x64 =F6A9C
bRemoteConnAllowed.x64=F6AA0
bMultimonAllowed.x64  =F6AA4
ulMaxDebugSessions.x64=F6AA8
bFUSEnabled.x64       =F6AAC

please help !!! my computer is win10 pro x64

**Comment by ghost** [comment] 2020-01-22 05:25
I have the same issue - 10.0.183262.267

**Comment by Crakki** [comment] 2020-01-25 13:02
I have the same problem  - 10.0.183262.267

**Comment by MrKroo** [comment] 2020-02-06 16:01
I'm having the same issue. - 10.0.183262.267

**Comment by ericlecoutre** [comment] 2020-02-07 18:20
Same issue. Anyone has found a solution?

**Comment by sebaxakerhtc** [comment] 2022-06-20 10:22
Duplicate of https://github.com/stascorp/rdpwrap/issues/871

**Closed as completed by sebaxakerhtc** 2022-06-20 10:22 UTC
