### ISSUE TITLE
Windows 11 22000.778, 10.0.19041.1348

### ISSUE THREAD

**Issue by zlaazlaa** [stascorp/rdpwrap#1929] opened 2022-07-13 11:17 UTC
![image](https://user-images.githubusercontent.com/72907523/178721092-798fb697-8317-48ca-ba09-2820fb06a9dd.png)
![image](https://user-images.githubusercontent.com/72907523/178721127-3491f9fb-db8d-4e79-8355-fe3b8263071e.png)
22000.778 or 10.0.19041.1348, which is my version?
I use [this](https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini) as my ini file , fully supported but not listening.

**Comment by zlaazlaa** [comment] 2022-07-13 11:26
install.bat has an error.
![image](https://user-images.githubusercontent.com/72907523/178722892-dddb14c7-dc41-41ad-9a53-3526b16070b8.png)

**Comment by zlaazlaa** [comment] 2022-07-13 11:30
I made the install follow by the [step](https://github.com/stascorp/rdpwrap/issues/1474#issuecomment-903411164)

**Comment by binarymaster** [comment] 2022-07-13 11:30
Your first screenshot (10.0.19041.1348, tracked in #1595) contradicts the second one (10.0.22000.708, tracked in #1868).

Resolving as duplicate of either anyway.

**Closed as completed by binarymaster** 2022-07-13 11:30 UTC
Labels: duplicate
