### ISSUE TITLE
Windows 11 home 10.0.22631.3447 Not listening

### ISSUE THREAD

**Issue by dkyu1109** [stascorp/rdpwrap#2564] opened 2024-04-12 23:07 UTC
<img width="305" alt="111" src="https://github.com/stascorp/rdpwrap/assets/166878578/72aa6832-8be6-4f47-bfee-74ee4ffea342">

After update windows, RDP Wrapper don't work

**Comment by dkyu1109** [comment] 2024-04-12 23:08
please help

**Comment by sashaqwert** [comment] 2024-04-13 09:29
Duplicate of https://github.com/stascorp/rdpwrap/issues/2469

**Comment by sashaqwert** [comment] 2024-04-13 09:30
Try:
1. Download RDP Wrapper 1.6.2 and extract this to any directory.
2. Place `rdpwrap.ini` in the same directory.
3. Open CMD as administrator
4. Execute this commands
```
cd C:\path\to\directory\
rdpwinst -u -k
rdpwinst -i
```
5. Enjoy!

Original message: https://t.me/rdpwrap/49131

**Closed as not planned by sashaqwert** 2024-04-13 09:29 UTC
