### ISSUE TITLE
Please add support for Windows 10 1809 - 10.0.17763.1

### ISSUE THREAD

**Issue by aliqalavi** [stascorp/rdpwrap#580] opened 2018-10-03 17:16 UTC
Please add support for Windows 10 1809 - 10.0.17763.1

**Comment by binarymaster** [comment] 2018-10-03 17:17
Duplicate of #578.

**Closed by binarymaster** 2018-10-03 17:17 UTC

**Comment by Julien-nl** [comment] 2018-10-04 12:52
i am using only the cracked termsrv.dll
does anyone have a working one?
