### ISSUE TITLE
10.0.26100.2454 [not supported] Windows 11 Pro

### ISSUE THREAD

**Issue by 4Hillz** [stascorp/rdpwrap#3403] opened 2024-12-27 15:50 UTC
It says not supported even though I added the following to my .ini file in programs, which is what was said in the last open issue about this version. 

[10.0.26100.2454]
SingleUserPatch.x64=1
SingleUserOffset.x64=9B55B
SingleUserCode.x64=mov_eax_1_nop_2
DefPolicyPatch.x64=1
DefPolicyOffset.x64=9897F
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx_jmp
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=8EB71
LocalOnlyCode.x64=jmpshort
SLInitHook.x64=1
SLInitOffset.x64=AF200
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.26100.2454-SLInit]
bServerSku.x64=11EE5C
bRemoteConnAllowed.x64=11EE70
bFUSEnabled.x64=11EE80
bAppServerAllowed.x64=11EE68
bMultimonAllowed.x64=11EE74
lMaxUserSessions.x64=11EE60
ulMaxDebugSessions.x64=11EE7C
bInitialized.x64=11EE58

Dunno what I am doing wrong and how I can fix this. Did I insert the wrong code? I added an extra blank line at the end and tried it without it as it said in the previous post.

**Comment by 4Hillz** [comment] 2024-12-27 15:56
Update: yeah so I clicked on the link that you sent in the previous thread regarding this version made from the developer and copied the .ini file text over and now it [fully supported] but [Service state: stopped] and [Listener state: Not listening]

**Comment by 4Hillz** [comment] 2024-12-27 16:02
Nevermind I just had to restart my PC I am so sorry you can close this...

**Comment by binarymaster** [comment] 2024-12-27 16:24
Duplicate of https://github.com/stascorp/rdpwrap/issues/3353.

**Closed as not planned by binarymaster** 2024-12-27 16:24 UTC
Labels: duplicate
