### ISSUE TITLE
Please add support for termsrv.dll 10.0.17763.771

### ISSUE THREAD

**Issue by nick7inc** [stascorp/rdpwrap#1109] opened 2020-06-30 16:00 UTC
Operating System Properties	
OS Name	Microsoft Windows 10 Pro
OS Language	Русский (Россия)
OS Installer Language	Русский (Россия)
OS Kernel Type	Multiprocessor Free (64-bit)
OS Version	10.0.17763.1282 (Win10 RS5 [1809] October 2018 Update)
[termsrv.dll](https://yadi.sk/d/1AvL_eqs4cTtlA) 10.0.17763.771 (MD5:600bb6c97f076582995a6db93fc46b34)

**Comment by affinityv** [comment] 2020-07-01 07:00
That termsrv.dll version is covered by this [ini](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini) file

**Comment by nick7inc** [comment] 2020-07-01 17:40
Thank you, it is looks like it's working. Can you answer one more question (for my experience). This is a second unofficial version of config (the url you posted is not official, I suppose the official is [this one](https://github.com/stascorp/rdpwrap/blob/master/res/rdpwrap.ini)). The [previous unofficial one](https://github.com/JD10NN3/rdpwrap-1/blob/patch-2/res/rdpwrap.ini) I found recently. So my question: are both of them beta-version (the official file will be upgraded soon)?  Or next time I need special url for fresh one because of "conspiracy" reasons?

**Comment by affinityv** [comment] 2020-07-02 10:56
@nick7inc 

The community here is providing updates to add new sections to the INI file; the official project doesn't seem to be interested in updating the project's INI file for some reason (perhaps lack of time, perhaps some other reason(s), I don't know why; I would only be guessing as to why).

There are a number of INI files floating around, my concern that there are the odd sections for particular versions that have different entries and I'm never quite sure which one is correct.  I, myself, will endeavour to collect any new sections that I see as they become available.  I have not, to date, tried to work through the processes required to build INI sections myself.

Of all the INI files that I've seen, I've collected and analyzed them against what I have and end up with what could be considered a monolithic version of all known INI sections in one INI file; this includes sections for versions of Windows that are EOL and should not be used by anyone at all, but having extra sections doesn't cause any issues, so there isn't a good enough reason to cull them down.

A great number of INI sections in my file have undergone some "normalizing", I've got a reasonable technique to discover if another INI file has something extra to add in to my file; that can be time consuming because of the varying formatting of INI sections -- I am preferring to keep x86 in a section and x64 below x86 entries separated by a blank line.  I also line up the "=" with each section.  If either x86 or x64 is missing, I have a comment in the INI section as appropriate, if I later find that missing section, I incorporate it.

My "help" here is about all I can do at this time, one day I might try to build INI sections myself, but so long as others are able to do this, then my goal is to include the INI sections as soon as I become aware of them and make sure that my INI file remains as useful to as many people as possible.

My processes include breaking down entire INI files into sections into small files, this helps with comparisons.  Then I rebuild the INI file form those sections to end up with a very consistent form and, hopefully, without any errors.

**Comment by nick7inc** [comment] 2020-07-04 10:07
I see, thanks for your answer and, of course, your work.

**Comment by Epoxa1989** [comment] 2020-12-23 14:47
windows server 2019 Standart
Версия 1809
Сборка 17763.1637
[https://we.tl/t-Z6P0SWNRzE](url)

можно для server 2019 попросить Вас модифицировать?

**Comment by Popadopus** [comment] 2021-03-24 11:34
Microsoft Windows 10 Pro 10.0.19042.662
Версия ОС 10.0.19042.662
termsrv.dll ver:10.0.19041.662
CRC32:8FBA9DCE
MD5:23E8094AA46CC88F89817D6E9E10225E
SHA-1:D37BC21ECCCE58DA2DAA818099A4EDCCB1574E08
[https://disk.yandex.com/d/XLi2o7fbgDmUMg](url)
Пожалуйста, добавьте модификацию для этой версии. Поскольку текущая версия "RDP Wrapper" её не поддерживает.

**Comment by affinityv** [comment] 2021-05-03 17:41
> termsrv.dll ver:10.0.19041.662

This is supported with my [INI](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini) file.

**Comment by binarymaster** [comment] 2024-10-31 17:39
Duplicate of https://github.com/stascorp/rdpwrap/issues/886.

**Closed as not planned by binarymaster** 2024-10-31 17:39 UTC
Labels: duplicate
