### ISSUE TITLE
10.0.18362.53

### ISSUE THREAD

**Issue by 1660787987** [stascorp/rdpwrap#1744] opened 2022-02-23 14:08 UTC
10.0.18362.53
X64
![image](https://user-images.githubusercontent.com/100292879/155335471-faa630b1-d26f-4b85-88fc-d70e3f777fdc.png)

**Comment by sebaxakerhtc** [comment] 2022-02-24 08:20
Duplicate of https://github.com/stascorp/rdpwrap/issues/766

**Closed as completed by sebaxakerhtc** 2022-02-24 08:20 UTC
