### ISSUE TITLE
Version 10.0.22631.3374 is not available in rdpwrap.ini

### ISSUE THREAD

**Issue by angusgajurel** [stascorp/rdpwrap#2533] opened 2024-03-29 00:59 UTC
Version 10.0.22631.3374 is not available in rdpwrap.ini

**Comment by dn2182** [comment] 2024-03-29 08:11
Tried with new .ini file after adding new info and still does not work... Please help! 
![scs](https://github.com/stascorp/rdpwrap/assets/69160014/3604020a-8adc-42de-8fa8-7b5ae851a443)

**Comment by welkin1001** [comment] 2024-03-29 08:18
> Tried with new .ini file after adding new info and still does not work... Please help! ![scs](https://private-user-images.githubusercontent.com/69160014/317992914-3604020a-8adc-42de-8fa8-7b5ae851a443.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MDA0NjEsIm5iZiI6MTcxMTcwMDE2MSwicGF0aCI6Ii82OTE2MDAxNC8zMTc5OTI5MTQtMzYwNDAyMGEtOGFkYy00MmRlLThmYTgtN2I1YWU4NTFhNDQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA4MTYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3YTE3ZDkwNGY0MThjNWUwODYwZTRjMzFkZjA5YTA5MGM4OGY0ZWUyMmNlMDA2Yjc2ODM4ZmEwZjAxNzQ5NzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yZkNBBbDskpXfk-ZgVMPPPJ50LCGN81GxA9XKjrB9cs)

Same invalid, requires 10.0.22631.3374

**Comment by dn2182** [comment] 2024-03-29 08:34
termsrv.dll here

[termsrv.dll.zip](https://github.com/stascorp/rdpwrap/files/14801608/termsrv.dll.zip)

**Comment by asmtron** [comment] 2024-03-29 09:43
add support to 10.0.22631.3374
https://github.com/stascorp/rdpwrap/pull/1160

**Comment by loyejaotdiqr47123** [comment] 2024-03-29 11:20
Duplicate of #[https://github.com/loyejaotdiqr47123/rdpwrap/issues/4](https://github.com/loyejaotdiqr47123/rdpwrap/issues/4)

**Comment by angusgajurel** [comment] 2024-03-29 21:28
> Tried with new .ini file after adding new info and still does not work... Please help! ![scs](https://private-user-images.githubusercontent.com/69160014/317992914-3604020a-8adc-42de-8fa8-7b5ae851a443.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NDc4ODUsIm5iZiI6MTcxMTc0NzU4NSwicGF0aCI6Ii82OTE2MDAxNC8zMTc5OTI5MTQtMzYwNDAyMGEtOGFkYy00MmRlLThmYTgtN2I1YWU4NTFhNDQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDIxMjYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0NTdiZWFjNTZkODAwMjkyMDY4YjA1MDM4YWQyNGIzNWNkMmI5ZGI4ZTU0ZDc5ZTNjMGU4MjcyNmNhNWIxMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A0z7sLp_Bl48rPlcmR4OkXm3NFaD7rIJxaXY_jXLNvU)

I dont see that version on the new Ini file, Where are you looking at??

**Comment by dn2182** [comment] 2024-03-30 08:27
Here is how to fix it:

https://github.com/stascorp/rdpwrap/issues/2535#issuecomment-2027969145

**Comment by sashaqwert** [comment] 2024-03-31 16:31
Duplicate of https://github.com/stascorp/rdpwrap/issues/2528

**Closed as not planned by sashaqwert** 2024-03-31 16:31 UTC
Labels: duplicate

**Comment by sashaqwert** [comment] 2024-03-31 16:34
Duplicate, because `22631` uses versions of `termsrv.dll` from `22621`. You can check this in the properties of this file.

**Comment by xianchengyue** [comment] 2024-10-10 11:31
Same invalid, requires 10.0.22631.4317
