### ISSUE TITLE
Windows 11 Home 22H2 10.0.22621.2861 not listening / not supported 

### ISSUE THREAD

**Issue by watrworld** [stascorp/rdpwrap#2444] opened 2023-12-13 19:35 UTC
![image](https://github.com/stascorp/rdpwrap/assets/16058918/0dd934ac-b69a-4a3c-8e06-fa0663d0533c)

Windows today just did an update and suddenly my RDPWrap no longer works.

Tried re-installing, no luck.

`[*] Installing...
[*] Terminal Services version: 10.0.22621.2861
[-] This version of Terminal Services is not supported`

Any help appreciated. Thanks

**Comment by lucky1luc** [comment] 2023-12-13 21:16
I have the same problem windows 11 23H2. I got the latest rdpwin.ini and I have 
![image](https://github.com/stascorp/rdpwrap/assets/33922423/91fd28c4-337a-4656-8890-0664e6c17886)

**Comment by sashaqwert** [comment] 2023-12-14 06:39
Duplicate of https://github.com/stascorp/rdpwrap/issues/2443

**Closed as not planned by sashaqwert** 2023-12-14 06:39 UTC
Labels: duplicate

**Comment by lucky1luc** [comment] 2023-12-14 10:32
Installed the latest rdpwrap.ini from https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini and restarted services.
![image](https://github.com/stascorp/rdpwrap/assets/33922423/fe24fa8b-edbb-401f-94ed-b359bfa50ddf)
It works again

**Comment by watrworld** [comment] 2023-12-14 14:43
I did download the linked rdpwrap.ini, still not working.

I am attaching the termsrv.dll, interesting in the system32, there is a termsrv.dll_backup, I did not do that. Windows? or install of RDP does that? Should I try it?

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/13674676/termsrv.zip)
