### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by booler007** [stascorp/rdpwrap#2527] opened 2024-03-26 14:35 UTC
![Screenshot_1](https://github.com/stascorp/rdpwrap/assets/114855520/a7d9d13c-dbec-4b3f-a018-db8d26289f4f)
Does not work on windows build 19045.4170

**Comment by sashaqwert** [comment] 2024-03-26 16:39
> Doesn't work

The title screams: “Help me figure out how to use the search here!”

> Screenshot

All the information by which you can find the answer is here, namely, version `termsrv.dll` = 10.0.19041.3636

> windows build 19045.4170

Many people try to search by Windows version instead, which is incorrect. The version of termsrv.dll and the system architecture (x86, x64, arm, arm64) are enough.

**Comment by sashaqwert** [comment] 2024-03-26 16:40
Duplicate of https://github.com/stascorp/rdpwrap/issues/2381

**Closed as not planned by sashaqwert** 2024-03-26 16:40 UTC
Labels: duplicate

**Comment by booler007** [comment] 2024-03-26 19:49
thanks!
