### ISSUE TITLE
Do not working windows 10 19045.4046

### ISSUE THREAD

**Issue by sashaulanov** [stascorp/rdpwrap#2523] opened 2024-03-19 19:24 UTC
Do not working windows 10 19045.4046
Please help
Thank you

**Comment by loyejaotdiqr47123** [comment] 2024-03-20 11:56
Please upload the termsrv.dll file and a screenshot of rdpconf

**Comment by Horetz** [comment] 2024-03-22 10:22
![image](https://github.com/stascorp/rdpwrap/assets/95444558/e31e18c1-0e22-4fbc-ab48-fba6c985828c)
Got the same issue. Same version 
Termsrv file:
https://dropmefiles.com/7CqyG

**Comment by loyejaotdiqr47123** [comment] 2024-03-22 10:36
> ![image](https://private-user-images.githubusercontent.com/95444558/315973816-e31e18c1-0e22-4fbc-ab48-fba6c985828c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDQwNjIsIm5iZiI6MTcxMTEwMzc2MiwicGF0aCI6Ii85NTQ0NDU1OC8zMTU5NzM4MTYtZTMxZTE4YzEtMGUyMi00ZmJjLWFiNDgtZmJhNmM5ODU4MjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDEwMzYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlZDdmOWIwMWZmZmRhYzdhMjA0ZjVlNDNmYjcxMDA5ZmNhYmU3OTExYWY0MGIyYTgwMDY1ZGE0NzkzNjBlMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3dYX9IREUte1lTtDlgG2nh9k7CF61Xp0FwdwLLOmZ54) Got the same issue. Same version Termsrv file: https://dropmefiles.com/7CqyG

#2381

**Comment by sashaqwert** [comment] 2024-03-23 14:20
Duplicate of https://github.com/stascorp/rdpwrap/issues/2381

**Closed as not planned by sashaqwert** 2024-03-23 14:20 UTC
Labels: duplicate
