### ISSUE TITLE
10.0.17763.168 workable solution for x32 and x64

### ISSUE THREAD

**Issue by explorerhk** [stascorp/rdpwrap#617] opened 2018-12-19 17:04 UTC
I have tried number of ways from other threads, finally I came up a simple and workable solution for both x32 and x64 edition.

1. First, install rdpwrap v1.62
https://github.com/stascorp/rdpwrap/releases/download/v1.6.2/RDPWrap-v1.6.2.zip
2. Go to Administrative command prompt, then run "net stop termservice"
3. Replace rdpwrap.ini attached (It supports both x32 and x64)
4. Go to Administrative command prompt, then run "net start termservice"
5. Finally, go to C:\Program Files\RDP Wrapper folder, run RDPConf to check the states
6. Make sure All states are green
7. Congrats! You should now be able to RDP to your desktop.

If Listener state is not green, please do the following:-

1. Go to Administrative command prompt, then run "net stop termservice"
2. Replace termsrv.dll and rfxvmt.dll in c:\windows\system32 (Please download the correct OS version)
3. Repeat Step 4 to 6 above.

Hope this helps.

[rfxvmt_32bit.zip](https://github.com/stascorp/rdpwrap/files/2695811/rfxvmt_32bit.zip)
[rfxvmt_64bit.zip](https://github.com/stascorp/rdpwrap/files/2696045/rfxvmt_64bit.zip)
[termsrv_x32.zip](https://github.com/stascorp/rdpwrap/files/2695818/termsrv_x32.zip)
[termsrv_x64.zip](https://github.com/stascorp/rdpwrap/files/2696043/termsrv_x64.zip)
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/2695824/rdpwrap.zip)

![image](https://user-images.githubusercontent.com/31785847/50235889-f68eca00-03f3-11e9-82e2-841350e0ebab.png)

**Comment by binarymaster** [comment] 2018-12-19 21:59
Duplicate of #606.

No need to open duplicate issues.

**Closed by binarymaster** 2018-12-19 21:59 UTC
