### ISSUE TITLE
Windows 11 PRO 23H2 22631.3593 - not supported

### ISSUE THREAD

**Issue by dayspring-dev** [stascorp/rdpwrap#3086] opened 2024-06-02 03:34 UTC
I have attached a zip file with all the files including termsrv.dll
![Version_23H2_OS_Build_22631 3593](https://github.com/stascorp/rdpwrap/assets/26641244/d21f644d-9fc8-4111-800a-cc7e4f4cafa4)
![RDPConf_Window11Pro_23H2_22631 3593](https://github.com/stascorp/rdpwrap/assets/26641244/6b94f5c8-226f-4883-85d0-7ee8acce9e2e)

[Windows11_22631.3593.zip](https://github.com/user-attachments/files/15524050/Windows11_22631.3593.zip)

**Comment by badr258** [comment] 2024-06-02 15:11
+1 have like this proplem after last update win 11

**Comment by binarymaster** [comment] 2024-06-03 17:14
Issue title is misleading, your termsrv build is 10.0.22621.3085 (as shown by RDPConf)

Duplicate of #2469.

**Closed as not planned by binarymaster** 2024-06-03 17:14 UTC
Labels: duplicate
