### ISSUE TITLE
Terminal Services version: 10.0.22000.1042 not supported

### ISSUE THREAD

**Issue by ronlbrink** [stascorp/rdpwrap#2045] opened 2022-11-11 22:40 UTC
[*] Installing...
[*] Terminal Services version: 10.0.22000.1042
[-] This version of Terminal Services is not supported.
Try running "update.bat" or "RDPWInst -w" to download latest INI file.

The options to try did not change anything. I have been unable to find anything for ...1042

**Comment by sashaqwert** [comment] 2022-11-12 08:38
Duplicate of https://github.com/stascorp/rdpwrap/issues/1993

**Closed as not planned by sashaqwert** 2022-11-12 08:38 UTC
Labels: duplicate

**Comment by ronlbrink** [comment] 2022-11-12 14:49
Thank you I will check it out
