### ISSUE TITLE
Supposed Virus infection in repository

### ISSUE THREAD

**Issue by 3dWrecker** [stascorp/rdpwrap#414] opened 2018-02-24 01:12 UTC
Bitdefender reports RDPWrap-v1.6.2.zip and link to msi download infected with Trojan.GenericKD.40145889
Please fix.
![infection](https://user-images.githubusercontent.com/34898242/36623780-b3192ba2-196c-11e8-9db2-09ad68c28129.png)

**Comment by 3dWrecker** [comment] 2018-02-25 00:59
Sorry. I hadn't seen the previous threads on this issue. I will try to get Bitdefender to add rdpwrap components to their whitelist (or remove them from their malware list). I will update you if I have any success.

**Comment by binarymaster** [comment] 2018-02-28 16:04
Duplicate of #277 < any further discussion here.

**Closed by binarymaster** 2018-02-28 16:04 UTC
