### ISSUE TITLE
rdpwrap.ini for Win10 x64 Ver.10.0.19041.1202 Build 19042.1237

### ISSUE THREAD

**Issue by Paul-dd-h** [stascorp/rdpwrap#1542] opened 2021-09-27 05:43 UTC

**Comment by Paul-dd-h** [comment] 2021-09-27 05:48
[rdpwrap.ini.txt](https://github.com/stascorp/rdpwrap/files/7233682/rdpwrap.ini.txt)
![Win10](https://user-images.githubusercontent.com/43093768/134851584-4037919a-54b6-45bd-976d-dde5741c25e3.png)
![RDP](https://user-images.githubusercontent.com/43093768/134851616-97c1c70f-1340-48c8-bba1-0b0a81ea73c1.png)

**Comment by 77348953** [comment] 2021-09-27 08:51
![image](https://user-images.githubusercontent.com/34222926/134875411-76ebdfa4-029f-49bb-926c-eeaf22f24e7c.png)
![image](https://user-images.githubusercontent.com/34222926/134875523-a8021028-626b-4b0e-9ff7-7cdc718b418a.png)
升级后，我的也有相同的问题。希望能得到大神指引。谢谢！
After update, I have the same problem, below the _rdpwrap.ini_ I am using. But seems not working. Hope can get help. Thanks!
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/7234746/rdpwrap.zip)

**Comment by ouchangjian** [comment] 2021-09-27 09:35
> ![image](https://user-images.githubusercontent.com/34222926/134875411-76ebdfa4-029f-49bb-926c-eeaf22f24e7c.png)
> ![image](https://user-images.githubusercontent.com/34222926/134875523-a8021028-626b-4b0e-9ff7-7cdc718b418a.png)
> 升级后，我的也有相同的问题。希望能得到大神指引。谢谢！
> After update, I have the same problem, below the _rdpwrap.ini_ I am using. But seems not working. Hope can get help. Thanks!
> [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/7234746/rdpwrap.zip)

你这个已经安装完成了，重启电脑或者在服务里面重启远程桌面服务就可以了

**Comment by Paul-dd-h** [comment] 2021-09-27 11:21
> ![image](https://user-images.githubusercontent.com/34222926/134875411-76ebdfa4-029f-49bb-926c-eeaf22f24e7c.png)
> ![image](https://user-images.githubusercontent.com/34222926/134875523-a8021028-626b-4b0e-9ff7-7cdc718b418a.png)
> 升级后，我的也有相同的问题。希望能得到大神指引。谢谢！
> After update, I have the same problem, below the _rdpwrap.ini_ I am using. But seems not working. Hope can get help. Thanks!
> [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/7234746/rdpwrap.zip)

**Comment by Paul-dd-h** [comment] 2021-09-27 11:25
> ![image](https://user-images.githubusercontent.com/34222926/134875411-76ebdfa4-029f-49bb-926c-eeaf22f24e7c.png)
> ![image](https://user-images.githubusercontent.com/34222926/134875523-a8021028-626b-4b0e-9ff7-7cdc718b418a.png)
> 升级后，我的也有相同的问题。希望能得到大神指引。谢谢！
> After update, I have the same problem, below the _rdpwrap.ini_ I am using. But seems not working. Hope can get help. Thanks!
> [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/7234746/rdpwrap.zip)

端口号：3389
不是6868
设置完，点击OK，系统重启应该就好使了。

**Comment by xme** [comment] 2021-09-27 14:40
Same problem here... 10.0.1904.1202... It says "[not supported"]

**Comment by zekecarter** [comment] 2021-09-28 05:07
hello, before replacing the rdpwrap.ini file, you need to stop the remote desktop service, then replace the rdpwrap.ini file with the one you will use and finally start the remote desktop service again.

every time you are going to replace the rdpwrap.ini file to upgrade, you must stop the remote desktop service otherwise the termsvr.dll file will be in conflict.

here you have a [video](https://www.youtube.com/watch?v=hH4iaRAFALE) example only in spanish

**Comment by sebaxakerhtc** [comment] 2021-10-25 15:48
duplicate of https://github.com/stascorp/rdpwrap/issues/1509

**Closed as completed by sebaxakerhtc** 2021-10-25 15:48 UTC
