### ISSUE TITLE
Not supported Winver 22H2 19045.2251

### ISSUE THREAD

**Issue by Kousti666** [stascorp/rdpwrap#2048] opened 2022-11-19 20:11 UTC
Hey, I was search for this build in the issues, can't seem to find it. Did I miss something or someone could attach the right .ini here ? Thank you!!

**Comment by sashaqwert** [comment] 2022-11-20 07:18
Duplicate of https://github.com/stascorp/rdpwrap/issues/2043

**Comment by sashaqwert** [comment] 2022-11-20 07:19
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992

**Closed as not planned by sashaqwert** 2022-11-20 07:18 UTC
Labels: duplicate
