### ISSUE TITLE
Windows 10 Pro x 64 21H2 19044.1889 Fully supported but not working

### ISSUE THREAD

**Issue by jamaimac** [stascorp/rdpwrap#1981] opened 2022-09-12 17:59 UTC
![rdp](https://user-images.githubusercontent.com/113380478/189723337-e1d0b5a1-c971-40a3-a479-764bc8c85f45.jpg)

when I want to log in another user appears:

![error2](https://user-images.githubusercontent.com/113380478/189723753-401898f1-d9f4-4801-888e-d95849598686.jpg)

I already tried modifying the maximum number of simultaneous connections to 999999 in GPEDIT, but the error continues, I appreciate any help

**Comment by sashaqwert** [comment] 2022-09-12 18:04
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881

**Closed as not planned by sashaqwert** 2022-09-12 18:04 UTC
Labels: duplicate

**Comment by sashaqwert** [comment] 2022-09-12 18:06
The connection problem described in this issue is resolved by restarting the service or rebooting.

**Comment by jamaimac** [comment] 2022-09-12 18:46
> The connection problem described in this issue is resolved by restarting the service or rebooting.

I already restarted the computer and the service and still with the same problem.

I also tried reinstalling the RDP Wrapper, but that didn't work either.

Thank you

**Comment by wangchong33333** [comment] 2022-10-13 10:32
you may install rdpwrap from https://github.com/sebaxakerhtc/rdpwrap/releases, not this repo

**Comment by eymenbilisim** [comment] 2022-11-05 12:50
Windows 10 Pro x 64 21H2 19044.1889 oky.....
