### ISSUE TITLE
10.0.19045.1889 [not supported]

### ISSUE THREAD

**Issue by q465414859** [stascorp/rdpwrap#2399] opened 2023-11-12 10:53 UTC
10.0.19045.1889 [not supported]

**Comment by sashaqwert** [comment] 2023-11-12 16:56
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881

**Comment by sashaqwert** [comment] 2023-11-12 16:57
`termsrv.dll` version != Windows version!

**Closed as not planned by sashaqwert** 2023-11-12 16:56 UTC
Labels: duplicate
