### ISSUE TITLE
Issue after update in ver. 10.0.19041.1348

### ISSUE THREAD

**Issue by mhtkumar0025** [stascorp/rdpwrap#1622] opened 2021-11-16 09:29 UTC
I have even changed the termser.dll file in C Drive but it's still the same. Please help me.
Below is the screenshot

![RDP](https://user-images.githubusercontent.com/74907458/141959111-73045f04-ab5f-4900-98ee-ac30bcc9a7f4.PNG)

**Comment by BrianDent** [comment] 2021-11-16 15:56
Append this to your rdpwrap.ini file and restart:
[10.0.19041.1348]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=89AC1
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0D1E2
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=190D5
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=1E6AC
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.19041.1348-SLInit]
bInitialized.x64      =107108
bServerSku.x64        =10710C
lMaxUserSessions.x64  =107110
bAppServerAllowed.x64 =107118
bRemoteConnAllowed.x64=107120
bMultimonAllowed.x64  =107124
ulMaxDebugSessions.x64=107128
bFUSEnabled.x64       =10712C

**Comment by sebaxakerhtc** [comment] 2021-11-16 19:11
Duplicate of https://github.com/stascorp/rdpwrap/issues/1595

**Closed as completed by sebaxakerhtc** 2021-11-16 19:11 UTC
Labels: duplicate
