### ISSUE TITLE
Please support for 17763.195

### ISSUE THREAD

**Issue by AndrewCoWork** [stascorp/rdpwrap#624] opened 2018-12-21 20:14 UTC
Hello, could anyone tell me how to fix termsrv.dll for this version? An instruction for manually replacing it with an older version would help a lot because users are not able to connect simultaneously since the CU.

**Comment by binarymaster** [comment] 2018-12-21 21:16
Duplicate of #606.

**Closed as completed by binarymaster** 2018-12-21 21:16 UTC
Labels: duplicate
