### ISSUE TITLE
OS Build# 18363.778  ver: 1909  RDP Issues

### ISSUE THREAD

**Issue by Hagrid78** [stascorp/rdpwrap#1060] opened 2020-04-22 05:15 UTC
i really don't know what to say at this point the program works and i thank you guys for what you do but the main issue im having it keeps getting me protocol issue disconnects sometimes i cant even sign in most of the time i have to go to the psychical machine to sign me out for me to sign in to remote this is starting to happen every day just for me i share this machine with 5 other people i haven't heard anything from them yet.   if i need to some how send a log and i can i just have to get signed in first.

**Comment by s0nic9** [comment] 2020-04-22 07:02
try https://github.com/stascorp/rdpwrap/issues/858#issuecomment-523192537

**Comment by Hagrid78** [comment] 2020-04-22 07:57
![image](https://user-images.githubusercontent.com/26916567/79955863-5e707d00-844d-11ea-8809-1353a521d5ab.png)
this is what i get

**Comment by Hagrid78** [comment] 2020-04-23 06:14
that fix didn't work my friend @s0nic9 
![image](https://user-images.githubusercontent.com/26916567/80065406-106c7f80-8508-11ea-84f3-cce9fd6f310b.png)
![image](https://user-images.githubusercontent.com/26916567/80065434-19f5e780-8508-11ea-84d7-27733a2771c3.png)

I still have to go to the machine and sign my self out it never did this before.

**Comment by Hagrid78** [comment] 2020-04-23 09:59
I'm Trying this right now:
https://github.com/DrDrrae/rdpwrap/blob/72e6b9ec967d50c9e213fce65422099edceecc6e/res/rdpwrap.ini

i will give you a update

**Comment by Hagrid78** [comment] 2020-04-23 10:00
it still shows the older build number but if you look at the code it shows build 2004 from 1903 but there is no 1909 very odd.
![image](https://user-images.githubusercontent.com/26916567/80086413-a95ec300-8527-11ea-9b23-e90c0d4845b3.png)

**Comment by Hagrid78** [comment] 2020-04-23 10:00
i will give a update on how its working in a day or two maybe sooner.

**Comment by affinityv** [comment] 2020-04-23 19:34
Windows version does not co-relate with RDPConf version.... give it up; RDPConf reports the version of termsrv.dll .. that is different to the Windows version, every time!

**Comment by Hagrid78** [comment] 2020-04-24 03:34
@affinityv  no need to be a ass my friend i didnt now. everytime i have a issue an when its fixed its with the version i have so ya.

**Comment by sebaxakerhtc** [comment] 2022-04-27 16:06
Duplicate of https://github.com/stascorp/rdpwrap/issues/1059

**Closed as completed by sebaxakerhtc** 2022-04-27 16:06 UTC
