### ISSUE TITLE
不支持win11 10.0.22000.1

### ISSUE THREAD

**Issue by yanhx1993** [stascorp/rdpwrap#1804] opened 2022-04-11 08:23 UTC
不支持win11   10.0.22000.1
![111](https://user-images.githubusercontent.com/49421432/162695087-cfedacea-b838-4c02-a035-d63372cac772.jpg)

**Comment by sebaxakerhtc** [comment] 2022-04-11 10:19
Duplicate of https://github.com/stascorp/rdpwrap/issues/1455

**Closed as completed by sebaxakerhtc** 2022-04-11 10:19 UTC
