### ISSUE TITLE
win 10 19044.1387 update .ini file 

### ISSUE THREAD

**Issue by keerthir99** [stascorp/rdpwrap#1648] opened 2021-12-06 10:03 UTC
![Screenshot (5)](https://user-images.githubusercontent.com/94477131/144826802-8d75c095-54d4-4cfc-b877-30f056955d80.png)

**Comment by sebaxakerhtc** [comment] 2021-12-06 10:12
Duplicate of https://github.com/stascorp/rdpwrap/issues/1630

**Closed as completed by sebaxakerhtc** 2021-12-06 10:12 UTC
