### ISSUE TITLE
RDPWinst-v1.6.2.msi marked as "Dangerous"

### ISSUE THREAD

**Issue by peakpeak-github** [stascorp/rdpwrap#2417] opened 2023-11-20 13:06 UTC
RDPWinst-v1.6.2.msi marked as "Dangerous" with Chrome and Firefox browsers.
Is this for real?
![Window-2023-11-20 14_04_24](https://github.com/stascorp/rdpwrap/assets/10742803/66e9c183-9258-453e-8e31-c6c77f25360d)

**Comment by sashaqwert** [comment] 2023-11-23 07:53
> RDPWinst-v1.6.2.msi marked as "Dangerous" with Chrome and Firefox browsers.
> Is this for real?

Duplicate of https://github.com/stascorp/rdpwrap/issues/277

**Closed as not planned by sashaqwert** 2023-11-23 07:53 UTC
Labels: duplicate
