### ISSUE TITLE
win10 - 18362.900 Not supported

### ISSUE THREAD

**Issue by dkunin9** [stascorp/rdpwrap#1097] opened 2020-06-16 13:37 UTC
already tried diff .ini from other builds
still not working
help please for peace 👍

**Comment by Flukester69** [comment] 2020-06-16 22:01
Same, hope this can be updated!

**Comment by Mearman** [comment] 2020-06-18 23:32
I've found an appropriate ini file but get the error when I try and connect.
![image](https://user-images.githubusercontent.com/1331872/85081566-36d73000-b1c4-11ea-9ad9-238b6cc89c97.png)
![image](https://user-images.githubusercontent.com/1331872/85081619-5a9a7600-b1c4-11ea-819b-359e37719c3f.png)

**Comment by ipatch** [comment] 2020-06-20 21:45
@Mearman 

more than likely your issue can be resolved following the steps outlined in [this article](http://woshub.com/how-to-allow-multiple-rdp-sessions-in-windows-10/).

do a search for

```
The number of connections
```

on that page and you should see the fix for your issue.

**Comment by Mearman** [comment] 2020-06-20 23:17
I followed that exact guide with no success @ipatch

**Comment by d-and** [comment] 2020-06-26 21:13
Agree with @Mearman, connections set to 999999 and still not working.

**Comment by djmcfar** [comment] 2020-07-13 19:40
I have a recent model HP all-in-one, Windows firewall disabled, anti-malware turned off, VPN turned off. Windows build x.900 (see output from winver command below) . RDPconf says it's not supported, RDPcheck produces a windows warning box (see screen cuts below).

![winver](https://user-images.githubusercontent.com/41165983/87345916-6dc80980-c516-11ea-8b8e-c5b27cb89a81.PNG)
![RDPconf](https://user-images.githubusercontent.com/41165983/87345934-76204480-c516-11ea-9f25-82d73fc1c29d.PNG)
![RDPcheck](https://user-images.githubusercontent.com/41165983/87346065-ac5dc400-c516-11ea-8042-ddc7e6f41877.PNG)

**Comment by affinityv** [comment] 2020-07-13 20:41
[Have you updated the INI file to this one](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini)

**Comment by strarsis** [comment] 2020-12-10 16:39
Was able to fix it using some INI from another user - but `RDPConf.exe` incorrectly indicates an unsupported version, see https://github.com/stascorp/rdpwrap/issues/1054#issuecomment-742637185.

**Comment by sebaxakerhtc** [comment] 2022-06-20 11:03
Duplicate of https://github.com/stascorp/rdpwrap/issues/1083

**Closed as completed by sebaxakerhtc** 2022-06-20 11:03 UTC
