### ISSUE TITLE
rdp

### ISSUE THREAD

**Issue by zzzzzzzzzda** [stascorp/rdpwrap#2108] opened 2023-02-09 23:53 UTC
help 
![image](https://user-images.githubusercontent.com/124941507/217964858-68981e29-01b9-4aad-8a28-118cb235dc8b.png)

**Comment by sashaqwert** [comment] 2023-02-10 06:51
Duplicate of https://github.com/stascorp/rdpwrap/issues/1883

**Closed as not planned by sashaqwert** 2023-02-10 06:51 UTC
Labels: duplicate

**Comment by sashaqwert** [comment] 2023-02-10 06:52
Discussion about your version: https://github.com/stascorp/rdpwrap/issues/1992
