### ISSUE TITLE
19042.746 is out

### ISSUE THREAD

**Issue by Melnick704** [stascorp/rdpwrap#1282] opened 2021-01-14 08:42 UTC

**Comment by philipejapa** [comment] 2021-01-14 12:18
I have the same problem and I updated the rdpwrap.ini appears supported but I still can't make more than one simultaneous connection

**Comment by SGS2021** [comment] 2021-01-14 13:01
A quick workaround is to replace the new termsrv.dll (located in Windows\System32 folder) with an older one which worked with RDP Wrapper. Which version Windows did you have before update?

**Comment by philipejapa** [comment] 2021-01-14 13:18
> Uma solução rápida é substituir o novo termsrv.dll (localizado na pasta Windows\System32) por um mais antigo que funcionou com o RDP Wrapper. Qual versão o Windows tinha antes da atualização?

I tried to update the dll but not possible and I'm as a local administrator

**Comment by SGS2021** [comment] 2021-01-14 13:46
Right click over new Termsrv.dll, then left click Properties, go to Security, click Advanced and then change owner to yourself. Come out completely of Properties and then repeat only this time change the permissions to allow you to rename the file to say Termsrv.dll.new. Then copy over old one that worked and restart system - will work - I've done it on dozens of systems the last 2 days. Once someone comes up with the offsets and produces and updated ini file then you can use the new Termsrv.dll - although I doubt it is much different just and updated version number which the ini does not have listed.

**Comment by philipejapa** [comment] 2021-01-14 14:28
> Clique com o botão direito do mouse sobre o novo Termsrv.dll e, em seguida, clique em Propriedades, vá para Segurança, clique em Avançado e, em seguida, altere o proprietário para si mesmo. Saia completamente de Propriedades e, em seguida, repita somente desta vez altere as permissões para permitir que você renomeie o arquivo para dizer Termsrv.dll.novo. Então copie o antigo que funcionou e reinicie o sistema - vai funcionar - eu fiz isso em dezenas de sistemas nos últimos 2 dias. Uma vez que alguém venha com os deslocamentos e produtos e atualize o arquivo ini, então você pode usar o novo Termsrv.dll - embora eu duvido que seja muito diferente apenas e atualizado número de versão que o ini não tem listado.

I will try to restart to see what happens because so far, only one remote connection at a time tks

**Comment by philipejapa** [comment] 2021-01-14 16:11
after restarting the simultaneous connections they returned to work normally with the update of rdpwrap.ini described by the friend at the beginning of this topic

**Comment by nekkkoz-al** [comment] 2021-01-16 20:40
> Быстрый обходной путь - заменить новый termsrv.dll (расположенный в папке Windows \ System32) на более старый, который работал с RDP Wrapper. Какая версия Windows была у вас до обновления?

Where i can take old Termsrv.dll?

**Comment by SGS2021** [comment] 2021-01-16 21:24
[Files.zip](https://github.com/stascorp/rdpwrap/files/5825154/Files.zip)
Extract attached and place in right folders and restart.

**Comment by mikemtz-slt** [comment] 2021-01-19 21:24
It work perfect!! tks amigo @SGS2021 
saludos

**Comment by mikemtz-slt** [comment] 2021-01-19 21:26
> [Files.zip](https://github.com/stascorp/rdpwrap/files/5825154/Files.zip)
> Extract attached and place in right folders and restart.



> [Files.zip](https://github.com/stascorp/rdpwrap/files/5825154/Files.zip)
> Extract attached and place in right folders and restart.

tks

**Comment by SGS2021** [comment] 2021-01-20 16:56
Updated rdpwrap.ini and current Termsrv.dll both 32 and 64 bit - tested fully working
[Files.zip](https://github.com/stascorp/rdpwrap/files/5843953/Files.zip)

**Comment by yanggs07** [comment] 2021-01-21 02:46
> Updated rdpwrap.ini and current Termsrv.dll both 32 and 64 bit - tested fully working
> [Files.zip](https://github.com/stascorp/rdpwrap/files/5843953/Files.zip)

is there a way that rdp wrap could work without replacing termsrv.dll? just update the ini file only without the dll file.

i downloaded your zip and found no section in the ini file replated to 19042.746
so i guess this method is using the old version of termsrv.dll file and old patch.

this does not solve the issue fundamentally.

thanks.

**Comment by SGS2021** [comment] 2021-01-21 10:24
yanggs07 - you are confusing Windows version with Termsrv.dll version. RDP Wrapper works by acting as a  layer between Service Control Manager and Terminal Services so the Termsrv.dll does not need modifying as in previous workarounds. When KB4598242 is installed the Windows version changes to 19042.746, however this has no bearing on RDP Wrapper. The Termsrv.dll version changes to 19041.746 and that is the important part - hence the rdpwrap.ini entries referencing 19041.746 at the bottom of the file. I can assure you it works if installed correctly.

**Comment by yanggs07** [comment] 2021-01-22 03:34
> yanggs07 - you are confusing Windows version with Termsrv.dll version. RDP Wrapper works by acting as a layer between Service Control Manager and Terminal Services so the Termsrv.dll does not need modifying as in previous workarounds. When KB4598242 is installed the Windows version changes to 19042.746, however this has no bearing on RDP Wrapper. The Termsrv.dll version changes to 19041.746 and that is the important part - hence the rdpwrap.ini entries referencing 19041.746 at the bottom of the file. I can assure you it works if installed correctly.

Thanks for your very nice explaination.
I must appologize for my ignorance of the 19041.747 info in the ini file you gave in your reply as the version info existing there clearly.

But I'm still wondering why we must replace the dll file given in your file.zip.

i opened the zip and found that the dll version is 19041.746

update: these two are the same files.

so i understood, 
if someone met the 19041.746 issue, your solution of ini would work, no need to replace the dll file -- they are the same;
if someone's dll version is not 19041.746, neither would he or she should use your ini, nor replace the dll file.

thanks!

**Comment by SGS2021** [comment] 2021-01-22 14:34
yanggs07 - Glad it's sorted - you do not need the Termsrv.dll if you have updated but I include it for completeness. I also keep a copy of these handy so that when the next update comes out I rename the new Termsrv.dll temporarily and use the one attached so that the Wrapper continues to work until the updated ini file comes out.

**Comment by skyrocketZ** [comment] 2021-01-29 13:59
> [Files.zip](https://github.com/stascorp/rdpwrap/files/5825154/Files.zip)
> Extract attached and place in right folders and restart.

Perfect! THANKS!

**Comment by hrpuae** [comment] 2021-02-17 04:37
Perfect Working!!!Thanks

**Comment by sebaxakerhtc** [comment] 2022-06-20 12:42
Duplicate of https://github.com/stascorp/rdpwrap/issues/1270

**Closed as completed by sebaxakerhtc** 2022-06-20 12:42 UTC
