### ISSUE TITLE
【Problem solve】when rdpwrapper.dll is missing, rdp termsrv service report unkonwn error

### ISSUE THREAD

**Issue by snail1126** [stascorp/rdpwrap#2457] opened 2023-12-21 07:49 UTC
When rdpwrapper.dll is missing (usually killed by anti-virus), RDPWrap install or unintall will not be worked,
and rdp service will report unkonwn error.
Here is problem solving step
1. run regedit, recover \HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TermService\Parameters\ServiceDll to %SystemRoot%\System32\termsrv.dll
2. reinstall RDPWrap (close anti-virus recommended)
Problem solved.
This works with windows 11 22H

**Comment by sashaqwert** [comment] 2023-12-22 08:33
https://github.com/stascorp/rdpwrap/issues/1883 --> Problem 3

**Comment by sashaqwert** [comment] 2023-12-22 08:34
Duplicate of https://github.com/stascorp/rdpwrap/issues/1883

**Closed as not planned by sashaqwert** 2023-12-22 08:34 UTC

**Comment by jhairtelloar** [comment] 2024-08-09 00:05
> When rdpwrapper.dll is missing (usually killed by anti-virus), RDPWrap install or unintall will not be worked, and rdp service will report unkonwn error. Here is problem solving step
> 
> 1. run regedit, recover \HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TermService\Parameters\ServiceDll to %SystemRoot%\System32\termsrv.dll
> 2. reinstall RDPWrap (close anti-virus recommended)
>    Problem solved.
>    This works with windows 11 22H

> It Works with Windows 10 22 H 08/08/24

**Comment by boraleclerc** [comment] 2025-06-08 10:39
i dont get the 1. part what do i do
