### ISSUE TITLE
Stopped and Not Listening

### ISSUE THREAD

**Issue by iranadavi** [stascorp/rdpwrap#446] opened 2018-04-12 21:52 UTC
I've been using RDPWrap for some time now. Then some Windows updates stopped working.

OS: windows 10 Pro (x64)
Version: 1709
Build: 16299.371
termsrv.dll - Version 10.0.16299.15

after installing:
![after installing](https://user-images.githubusercontent.com/14761695/38706123-7c484668-3e82-11e8-9333-da2b4490573a.png)

install:
![install](https://user-images.githubusercontent.com/14761695/38705733-edc6fbce-3e80-11e8-8bcf-cae15fbd1665.png)

before installing:
![before installing](https://user-images.githubusercontent.com/14761695/38705738-f4d4d2ba-3e80-11e8-96cd-4a8627e82823.png)

**Comment by iranadavi** [comment] 2018-04-18 23:41
I checked all the services and they are running. Disabling anti-virus nevertheless continues with the same situation.

It did not solve!

Thank you for your help.
![conect](https://user-images.githubusercontent.com/14761695/38963535-d75c225c-4348-11e8-87f4-c52e6c88c7c5.PNG)
![host](https://user-images.githubusercontent.com/14761695/38963536-d77dff3a-4348-11e8-9ad4-6d3bc4ae023a.PNG)
![host2](https://user-images.githubusercontent.com/14761695/38963537-d79cb042-4348-11e8-9350-c284606233c5.PNG)
![host3](https://user-images.githubusercontent.com/14761695/38963538-d7bd8f9c-4348-11e8-9751-ebafbf06d200.PNG)

**Comment by binarymaster** [comment] 2018-04-21 21:26
This looks like a duplicate of #215.

**Comment by iranadavi** [comment] 2018-04-24 23:26
thank you!

Revolved!  <a class="issue-link js-issue-link tooltipped tooltipped-ne" data-error-text="Failed to load issue title" data-id="213468957" data-permission-text="Issue title is private" href="https://github.com/stascorp/rdpwrap/issues/215" aria-label="#215, Service state Stopped &amp; Listener State Not Listening">#215</a>

ok disabled smartscreen, disabled win defender,
disabled firewall
checked permissions on folder C:\Program Files\RDP Wapper\

Now ITs running

**Closed** 2018-04-25 00:03 UTC
