### ISSUE TITLE
NOT SUPPORTED

### ISSUE THREAD

**Issue by gotti1977** [stascorp/rdpwrap#437] opened 2018-03-28 11:56 UTC
hi
i,m running this on win8.1 enterprice. After upgrade windows i have this (pic)
![rdp](https://user-images.githubusercontent.com/37869964/38027353-a90131f0-328f-11e8-894a-94264570eaf6.jpg)
can anyone help??  

THANKS

**Comment by binarymaster** [comment] 2018-03-28 11:57
Duplicate of #418.

**Closed by binarymaster** 2018-03-28 11:57 UTC

**Comment by gotti1977** [comment] 2018-03-28 11:59
THANKS !!!
