### ISSUE TITLE
Failure　Install/Uninstall RDPWrapper with MSI installer

### ISSUE THREAD

**Issue by mtnmso1** [stascorp/rdpwrap#409] opened 2018-02-08 01:41 UTC
I can't install/uninstall RDPWrapper with msi installer.
First,i tried to install,but can't complete.
this is log for install.
`Error 1721. There is a problem with this Windows Installer package. A program required for this install to complete could not be run. Contact your support personnel or package vendor. Action: InstallAction, location: C:\ProgramData\Package Cache\{37ea5771-3352-4a52-9fac-9297331daebd}\RDPWInst.exe, command: -i -o 
=== Logging stopped: 2018/02/08  10:32:33 ===
`
But RDPWrapper appeared at Installed program list on windows config.
So,I tried to uninstall it, But can't complete too.
this is log for uninstall.
`Error 1721. There is a problem with this Windows Installer package. A program required for this install to complete could not be run. Contact your support personnel or package vendor. Action: UninstallAction, location: C:\ProgramData\Package Cache\{37ea5771-3352-4a52-9fac-9297331daebd}\RDPWInst.exe, command: -u 
=== Logging stopped: 2018/02/08  10:33:25 ===
`
System Information
Microsoft Windows [Version 10.0.16299.192]
Windows 10 Home 1709(Build 16299.192)

**Comment by binarymaster** [comment] 2018-02-08 10:49
Duplicate of #377.

**Closed by binarymaster** 2018-02-08 10:49 UTC
