### ISSUE TITLE
need help 10.0.17134.706

### ISSUE THREAD

**Issue by x-manosrs** [stascorp/rdpwrap#797] opened 2019-05-25 06:46 UTC
everything looks good and all, when i try RDPCheck it works perfectly but when I try use windows 10 RDC it says your computer could not connect to another console session on the remote computer because you already have a console session in progress. anyone know how to fix this? as stated when opening RDPCheck i can log on to another user and use it there

**Comment by alexsupra** [comment] 2019-05-25 10:54
I have got the same issue on Windows 10 Pro x64, possibly the reason is system update because it worked before.

**Comment by ghost** [comment] 2019-05-27 10:45
https://www.infopackets.com/news/10552/how-update-rdpwrapini-rdp-wrapper

Updating the rdpwrap.ini with that one provided in there worked for me with a charm. Theres even a tutorial on how to get it fixed.

**Comment by christian-elias** [comment] 2019-05-27 15:18
did you try this https://github.com/stascorp/rdpwrap/issues/763#issuecomment-487466729

**Comment by ChristopheCuddlup** [comment] 2019-05-29 08:40
Hi, it worked for me. Add this to the end of your file C:\Program Files\RDP Wrapper\rdwrap.ini 
Then restart the Remote Desktop services (run services.msc as Admin):

[10.0.17134.706]
LocalOnlyPatch.x86=1
LocalOnlyOffset.x86=ADAB8
LocalOnlyCode.x86=jmpshort
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=92521
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x86=1
SingleUserOffset.x86=36B1C
SingleUserCode.x86=nop
SingleUserPatch.x64=1
SingleUserOffset.x64=1511C
SingleUserCode.x64=Zero
DefPolicyPatch.x86=1
DefPolicyOffset.x86=33579
DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
DefPolicyPatch.x64=1
DefPolicyOffset.x64=10E78
DefPolicyCode.x64=CDefPolicy_Query_edi_rcx
SLInitHook.x86=1
SLInitOffset.x86=475DD
SLInitFunc.x86=New_CSLQuery_Initialize
SLInitHook.x64=1
SLInitOffset.x64=22F5C
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.17134.706-SLInit]
bInitialized.x86      =CBF38
bServerSku.x86        =CBF3C
lMaxUserSessions.x86  =CBF40
bAppServerAllowed.x86 =CBF44
bRemoteConnAllowed.x86=CBF48
bMultimonAllowed.x86  =CBF4C
ulMaxDebugSessions.x86=CBF50
bFUSEnabled.x86       =CBF54

bServerSku.x64        =F1378
lMaxUserSessions.x64  =F137C
bAppServerAllowed.x64 =F1380
bInitialized.x64      =F2430
bRemoteConnAllowed.x64=F2434
bMultimonAllowed.x64  =F2438
ulMaxDebugSessions.x64=F243C
bFUSEnabled.x64       =F2440

**Comment by ishwlitay** [comment] 2019-09-04 12:39
only listener state:not listening
why?how?

**Comment by sebaxakerhtc** [comment] 2022-01-04 10:50
Duplicate of https://github.com/stascorp/rdpwrap/issues/721

**Closed as completed by sebaxakerhtc** 2022-01-04 10:50 UTC
