### ISSUE TITLE
19042.1586 - please help

### ISSUE THREAD

**Issue by apokox** [stascorp/rdpwrap#1782] opened 2022-03-21 06:46 UTC
Help guys, windows version is 19042.1586 , RDP Wrapper is not working, thanks in advance. 

Windows 10 19042.1586

**Comment by apokox** [comment] 2022-03-21 06:50
20H2 (19042.1586) OC

**Comment by sebaxakerhtc** [comment] 2022-03-21 08:58
Duplicate of https://github.com/stascorp/rdpwrap/issues/1725

**Closed as completed by sebaxakerhtc** 2022-03-21 08:58 UTC
