### ISSUE TITLE
Add support for 10.0.17763.194

### ISSUE THREAD

**Issue by mbowers3** [stascorp/rdpwrap#611] opened 2018-12-12 04:32 UTC
new updates broke it I tried my old termserv.dll but then remote desktop services will not start anymore.

**Comment by artemmen** [comment] 2018-12-12 08:17
Yes, rdpwrapper is blow up after update yesterday. Any things?

**Comment by aliqalavi** [comment] 2018-12-12 11:45
> @ @mbowers, @artemmen , @binarymaster
> 10.0.17763.194 - CU KB4471332 - keeps/lifts the termsrv.dll to its file version 10.0.17763.168.
> Therefore since .165, .167, .168 use the data-offset, which are the same, we have to add to the rdpwrap.ini dated 2018-10-10 ( last.ini in the repository - code: res\rdpwrap,ini).
> Ensure you have the correct ini file with two ini-sections [10.0.17763.1] , [10.0.17763.1-SLInit]
> and add then the two sections [10.0.17763.168], [17763.168-SLInit]
> Keep an eye on Acces Rigths and at least use "stop net termservice" before you exchange the
> rdpwrap.ini (2018-10-10) with your newly edited ini file.
> After the successful replacing you have to start the termservice again ("start net termservice")
> Just a short remark there are more stumbling stones with system privileges if plan to change termsrv.dll on your own. ! ( see also #606 -hajubu posts)
> .Good Luck with this task
> ( You also may wait till we get an updated rdpwrap.ini from binarymaster in the repository )
> ;---------SNIP part1-----goes just behind the section of 10.0.17763.1 ---
> [10.0.17763.168]
> LocalOnlyPatch.x86=1
> LocalOnlyOffset.x86=AFC74
> LocalOnlyCode.x86=jmpshort
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=77AF1
> LocalOnlyCode.x64=jmpshort
> SingleUserPatch.x86=1
> SingleUserOffset.x86=4D665
> SingleUserCode.x86=nop
> SingleUserPatch.x64=1
> SingleUserOffset.x64=1322C
> SingleUserCode.x64=Zero
> DefPolicyPatch.x86=1
> DefPolicyOffset.x86=4BE69
> DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=17F45
> DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> SLInitHook.x86=1
> SLInitOffset.x86=5B18A
> SLInitFunc.x86=New_CSLQuery_Initialize
> SLInitHook.x64=1
> SLInitOffset.x64=1ABFC
> SLInitFunc.x64=New_CSLQuery_Initialize
> ;--------------end snip part1-----------
> ;
> ;-----------snip part2 --------goes just at the bottom of the file behind 10.0.17763-SLInit Section------
> ;.
> [10.0.17763.168-SLInit]
> bInitialized.x86 =CD798
> bServerSku.x86 =CD79C
> lMaxUserSessions.x86 =CD7A0
> bAppServerAllowed.x86 =CD7A8
> bRemoteConnAllowed.x86=CD7AC
> bMultimonAllowed.x86 =CD7B0
> ulMaxDebugSessions.x86=CD7B4
> bFUSEnabled.x86 =CD7B8
> 
> bInitialized.x64 =ECAB0
> bServerSku.x64 =ECAB4
> lMaxUserSessions.x64 =ECAB8
> bAppServerAllowed.x64 =ECAC0
> bRemoteConnAllowed.x64=ECAC4
> bMultimonAllowed.x64 =ECAC8
> ulMaxDebugSessions.x64=ECACC
> bFUSEnabled.x64 =ECAD0
> ;---------end snip part2 --------------

thank you very much hajubu it's working for me on build 17763.194
but i havent [10.0.17763.1] section i only have [10.0.17763.1-SLInit] section but its works!
anyone need help just follow these steps from above from hajubu

**Comment by waltw1207** [comment] 2018-12-12 13:08
Thank you Aliqalavi!    I finally got this working on Windows 10 (1809).     😊

**Comment by StarfighterJ** [comment] 2018-12-12 19:18
hajubu ?( You also may wait till we get an updated rdpwrap.ini from binarymaster in the repository ) is this going to be done around 18 December 2018 you think.

**Comment by hajubu** [comment] 2018-12-12 19:33
>>> @starfighter asked for „official“ update release date

…..  I just have a „Feeling“,  when the OS win10 1809 update Story is calming down ,
       we will be lucky getting an update.
     
        Probably @Binarymaster knows more & better.

…. Meanwhile we may live with this intermediate solution.
a) Os update CU 1809-17763-194 (KB4471332) using 
b) the suitable data for 10.0.17763.168 (termsrv.dll file version)



Von: StarfighterJ
Gesendet: Mittwoch, 12. Dezember 2018 20:18
hajubu ?( You also may wait till we get an updated rdpwrap.ini from binarymaster in the repository ) is this going to be done around 18 December 2018 you think.

**Comment by xianjianbo** [comment] 2018-12-13 13:01
Thank you very much !  @hajubu and @RobertSpir ( #601 )
Just adding [10.0.17763.168] and [17763.168-SLInit] to rdpwrap.ini ( 2018-10-10 ) seems does't work for me( Windows 10 build 17763.194 ).
When I add  [10.0.17763.168] , [17763.168-SLInit] and [10.0.17763.165] , [10.0.17763.165-SLInit] ( from @RobertSpir #601 ) , it works!
Anyone need help can try it.

**Comment by pchelpers** [comment] 2018-12-13 14:49
Hello.
After updating Windows, the RDP stopped working. I did everything according to the instructions of hajubu / @RobertSpir.
RDPWrap-v1.6.2 writes that everything works fine, but when you try to connect, the window opens for a second and automatically closes. What is the problem ? Help me please. Thanks.
Video https://cloud.mail.ru/public/837K/WcJ3b4E6t

**Comment by KasimAhmic** [comment] 2018-12-13 17:51
The latest Windows update seems to have an issue with the INI provided by @hajubu. Following all the above tips and tricks, I am still unable to get it working.

System Info:
OS: Windows 10 Home
Version: 1809
OS Build: 17763.194
RDP Version: 10.0.17763.168

Here are my findings after about an hour of testing:
- Adding the 165 support from @RobertSpir #601 (suggested by @xianjianbo) seems to make no difference whatsoever for me.
- Adding **ONLY** the **[10.0.17763.168]** section **OR** the **[10.0.17763.168-SLInit]** section allows TermService to launch with no errors and stay open, however it does not let me connect via RDP.
- Adding **BOTH** the **[10.0.17763.168]** and the **[10.0.17763.168-SLInit]** sections prevents TermService from launching properly. Looking at Task Manager, TermService seems to attempt to launch twice (cycling through two PID values) before crashing with an error code of 1067.

I'm at a complete loss here so any help would be much appreciated.

**Comment by fragtion** [comment] 2018-12-13 17:55
It works on 10.0.17763.168. I also struggled but if you follow the steps above you'll see it can work

**Comment by hajubu** [comment] 2018-12-13 18:18
[17763-templates.zip](https://github.com/stascorp/rdpwrap/files/2677160/17763-templates.zip)
Sorry Team - But here my cooking recipee and all the detail incl. the ini for 
Win10 OS 1809-17763.194 ( termsrv.dll Version .168) as it was done with the last update by KB44713322.
I also verified all snipping data in #601 and #611.
The Difference between the data @RobertSpier(x64-only in the first post) to mine in the middle
for .165 (x64 and x86) is the fact that Robert find a small deviation in one location for the SingleUserOffset.x64 ( for which I found no reason, stay with the logical location as we had since 17763.1
- checking done with IDA and several testbeds. ( see also #606 my post with the multiconnection test)
The main difference from termsrv.dll.001 ( OS 1809-17763.1/.55/107/134) was to the termsrv.dll.165.

	This method is straight forward without manually touching a system file  (like Rfxvmt.dll, termsrv.dll ) ( RDP Wrapper 1.6.2 does it for adding the missing rfxvmt.dll (syswow64) - OK!)
	
c)  Install rdpwrap.ini - ensure to have the latest    
	(actual 2018-10-10 in Code: res\rdpwrap.ini) by installing (save your own edits before)

d)  Edit rdpwrap.ini to add the relevant section
	for 10.0.17763.168 (acc.to termsrv.dll.168)
	(I do higly recommend to have in the end at least the section for
	[10.0.0.17763.1] , and [10.0.17763.1-SLinit]  
	and
	[10.0.0.17763.168] , and [10.0.17763.168-SLinit]
	
    Do not stumble over System access privileges and/or elevation (admin) if you edit or exchange
    rdpwrap.ini directly in the "%program files%\RDP Wrapper" folder.
	
	I do recommend to do the edit-task with a copy of the rdpwrap.ini from c) in "a-folder-of-y.choice" ,
	insert the both data section ([10.0.17763.168], and [10.0.7763.168-SLInit])
	in the template shown.
	
e)  To replace the data 
	in "%program files%\RDP Wrapper" 
	I do recommend to us a small batch file
    to  "stop net termservice" ,'PAUSE', do the replacing of "%program files%\RDP Wrapper\rdpwrap.ini" and the 	'CONTINUE' to "start net termservice" again.
	
    I also do recommend if you not sure enough that the service has stoppen and restarted witout errors
    Restart your "magic-machine"	

	Do not use the "update.bat" of RDP Wrapper as it might overwrite your own Rdpwrap.ini just implemented "new" version as the rpwrap.ini
	contains in the [Main] section
	an "updated=yyy.mm.dd" Date to control the 
	Update function. (!!)
---- and more details in my zip file -

**Comment by edwingf** [comment] 2018-12-13 19:54
hola, gracias @hajubu seguí sus instrucciones y funciono con la versión  w10 10.0.17763.168

**Comment by KasimAhmic** [comment] 2018-12-13 20:19
I've followed all the instructions given including those from the 17763-templates.zip file given by @hajubu but I am still unable to get it working. I have gone as far as uninstalling and reinstalling RDP Wrapper and have even replaced the termsrv.dll file in System32 with an older one (10.0.17763.1) to no avail. Curiously enough, now instead of TermService crashing on launch, it is just in a perpetual state of "Starting."

Seeing other having success makes me think that this is an isolated issue with my computer alone. Are there any other services, programs, permissions, etc that affect the usage of RDP Wrapper? Besides the standard installation and modification of the INI file, is there anything else I should take a look at?

**Comment by hajubu** [comment] 2018-12-13 21:44
Hello Kasim Ahmic – 
there is normally no need to tackle manually with the termsrv.dll.

Did you go straight forward  first with the KB4471332 (10.0.17763.194) 
which does an update from termsrv.dll.001  or dll.165 or dll.167  to dll.168
( …but keeps in case you had been already updated to  .168
 ( e.g. done  with the  windows10.0-kb4469342-x64_7290815610ac4c3d657eb5ed6e4e92421fa8c29a.msu 
, "Package_for_RollupFix" version="17763.168.1.10") which leads also to an Termsrv.dll.168  )

The same happens when you update the OS from .168 to .194 (KB4471332) {keeps the termsrv.dll.168)

I do assume you are on win 10x64-1809-17763-194 at this time 
and you had seen the termsrv.dll.168 and validated the  Version
  ( see my crc-listing 3-17763_rdpRule.CRC.txt in the Zip-file)
and for now are on termsrv.dll.001 ( manually)
As you did so – 
I assume you solved the  elevated privileges ( manually or either by a „Tool“).
To circumvent the stumbling Stones of the „System“ Access Rights.

Did you also Keep an eye on your „Virusscanner“ as some of these “good Boys“ are sensitive and reluctant for exchanging/touching System Files and also registry data. (win-defender is not reluctant).

Now It is time  Change the termsrv.dll.001  back to „Normal .168“ 

Ensure the correctness with following elevated cmd:

„Certutil -hashfile C:Windows\system32\termsrv.dll  -md5“
(-md5 , -sha1 – doesn’t matter in the „3-17763_rdpRule.CRC.txt“  are known crc-data in)

You may also verify the property data of  
C:Windows\system32\termsrv.dll  :: Props:: 10.10.17763.168  - size: 1019392 - date:2018-12-04
 
Another file(s)  of interest is/are
C:Windows\system32\rfxvmt.dll    :: Props:: 10.10.17763.1       - size: 40960     - date:2018-09-15
C:Windows\syswow64\rfxvmt.dll    :: Props:: 10.10.17763.1       - size: 32768    - date:2018-09-15

Remark:
BUT the syswow64\rfxvmt.dll may be added by your RDP Wrapper V.1.62 with an older date
(Up till now this was not conflicting with the RDP wrapper Function,
 „one“ rfxvmt.dll (32-bit) should be in this folder.  It must exist only !

If you like you can now take my Template 
1-17763_rdpwrap.168.194.txt renaming it to  „%program files%\RDP Wrapper\rdpwrap.ini“ 
( this folder is the „Default“ for the first Install.)
Follow my short instruction :
To replace the data in "%program files%\RDP Wrapper" 
I  recommend to use a batch file    with „Pause“:

 1::  "stop net termservice" ,                'PAUSE', 
 2::  delete old "%program files%\RDP Wrapper\rdpwrap.ini"  
 3::  and copy the „new-ini-168“ to  "%program files%\RDP Wrapper\rdpwrap.ini"
 4:: and then    'CONTINUE' ,  "start net termservice" ,     'PAUSE'  again.

Keep an eye on the Messages  in the ‚PAUSE‘-Phases !
This should help to ensure that the service has stopped  and restarted without errors
Also you may     Restart your "magic-machine"	
before you test the RDP Wrapper with RDPconf.exe  
and (or)  with  RDPcheck.exe to see the settings and function.

This concludes to easy teststeps.
It should work in General.

If there are other termservices products installed , it has Always worked fine.

b.r. Hajubu


Von: Kasim Ahmic
Gesendet: Donnerstag, 13. Dezember 2018 21:19
I've followed all the instructions given including those from the 17763-templates.zip file given by @hajubu but I am still unable to get it working. I have gone as far as uninstalling and reinstalling RDP Wrapper and have even replaced the termsrv.dll file in System32 with an older one (10.0.17763.1) to no avail. Curiously enough, now instead of TermService crashing on launch, it is just in a perpetual state of "Starting."
Seeing other having success makes me think that this is an isolated issue with my computer alone. Are there any other services, programs, permissions, etc that affect the usage of RDP Wrapper? Besides the standard installation and modification of the INI file, is there anything else I should take a look at?

**Comment by systracer** [comment] 2018-12-14 09:48
https://github.com/stascorp/rdpwrap/issues/611#issuecomment-447068372 - working.
https://github.com/warezio/rdpwrap/commit/2ded34c2399e3210f2929942e9cf1395b90daa5d - not working.

**Comment by ventsislav-georgiev** [comment] 2018-12-14 13:35
Hey guys, I had the same issue as @KasimAhmic. Adding both snippets breaks TermService start.
What solved it for me is using the full ini file @hajubu provided in its templates zip. 

My ini was just the last update from 2018.10.10, but I guess there must have been some differences. 
I also tested using the full ini from https://github.com/warezio/rdpwrap/commit/2ded34c2399e3210f2929942e9cf1395b90daa5d and can confirm that it does not work.
Thank you @hajubu !

**Comment by pchelpers** [comment] 2018-12-14 13:36
> [#611 (comment)](https://github.com/stascorp/rdpwrap/issues/611#issuecomment-447068372) - working.

I confirm. Works
https://i.imgur.com/bWJxsfd.png

**Comment by KasimAhmic** [comment] 2018-12-14 22:07
Thank you @ventsislav-georgiev, that worked for me as well! Also, big thanks to @hajubu and everyone else for the help! I greatly appreciate it! :)

**Comment by binarymaster** [comment] 2018-12-16 14:44
> 10.0.17763.194 - CU KB4471332 - keeps/lifts the termsrv.dll to its file version 10.0.17763.168.

So this is a duplicate of #606 too.

**Closed by binarymaster** 2018-12-16 14:44 UTC

**Comment by hajubu** [comment] 2018-12-16 15:07
1809-17763.1 -.55  -.107  -.134 has Always had the termsrv.dll.001 version

Termsrv.dll with Version  -.165 -.167  -.168 (CU_KB4469342_v5.10)  have different CRC
 but same Offset Values – see my template.zip in ^# 611.

Therefore Data Sections 10.10.17763  for .1 and  .168  ought to be sufficient in most cases.


Cu 4471332 does not touch termsrv.dll.168  only  in cases  less then  .168 !

OK?

^# 606 611 refer to These Facts !



10.0.17763.194 - CU KB4471332 - keeps/lifts the termsrv.dll to its file version 10.0.17763.168.

So this is a duplicate of #606 too.

**Comment by andrePKI** [comment] 2018-12-17 20:10
@hajubu Please refrain from mentioning all kinds of codes, details, KB article numbers, as this confuses most people more than it clarifies things. I as a technician find it hard to understand your posts...

To be clear to everybody:
All actions need to be done as administrator. (stop/start the service, edit ini file).

First find the version of your termserv.dll file.
Just look at termserv.dll. Open Explorer, go to C:\Windows\System32, find the file termsrv.dll, rightclick this file and look at the details. This will give you the version number (10.0.17763.xxx)
Now add the correct fragments for your version xxx in the rdpwrap.ini and restart the service.

BTW a big thank you goes to @hajubu and @robertspir for providing the details which need to go into the ini files. This is the real hard work.

The correct command to stop the service is
**net stop termservice** (not stop net termservice as is repeated in many posts)
the correct command to start the service is
**net start termservice**
If you are uncertain about this, use **services.msc**, then you have a graphical interface. Look for the Remote Desktop Services to stop/start. You can then immediately see if the service is running or not.
The order of actions is: stop the service, edit the ini file, start the service.

NB it would be most welcome to have the rdpwrap.ini file updated at the source more frequently with  validated contents for each new build of termsrv.dll, that would help a lot of people... @binarymaster please??

**Comment by hajubu** [comment] 2018-12-17 22:46
@ andrePKI wrote: 
Please refrain from mentioning all kinds of codes, details, KB article numbers, as this confuses most people more than it clarifies things. I as a technician find it hard to understand your posts...
➢  „as a technician it is …“ : what ever your full background might be, I have also one. 
We should stop here and stay cool.

**Comment by tblog1234** [comment] 2018-12-18 03:09
Thank you all !!! works fine with the attached rdpwrap.ini

**Comment by vibaaa** [comment] 2018-12-18 11:52
Windows 10 Pro x86 17763.194 not work with section from .ini for 10.0.17763.168
Windows 10 Pro x64 17763.194 worked.

**Comment by hajubu** [comment] 2018-12-18 13:04
@vibaaa wrote
X64 :: Windows 10 Pro x64 17763.194 worked. 
… OK 
X86:: Windows 10 Pro x86 17763.194 not work with section from .ini for 10.0.17763.168
… works in my Testbed: VM/Vbox  
??  which data sections did you implement ?? 
17763.1 , 17763-SLinit and also 17763.168, 17763.168-SLInit
?? Which file Version do you see in the properties for the termsrv.dll ??

**Comment by vibaaa** [comment] 2018-12-18 14:07
![image](https://user-images.githubusercontent.com/45967082/50159060-c9a0c100-02e6-11e9-9a3d-52f404e2bba9.png)
I copy section  [10.0.17763.1] -> [10.0.17763.168] and [10.0.17763.1-SLInit] -> [10.0.17763.168-SLInit]

**Comment by hajubu** [comment] 2018-12-18 14:59
@vibaaa wrote: 
1) property Info: Termsrv.dll .168
2) I copy section [10.0.17763.1] -> [10.0.17763.168] and [10.0.17763.1-SLInit] -> [10.0.17763.168-SLInit]


… Be Aware [10.0.17763.1] is not equal to [10.0.17763.168]
Therefore you need both sections, each with seprarate data  Content .

… The SLinit Data for [10.0.17763.1-SLInit]  is equal to [10.0.17763.168]  
Therefore copying is fine


… If you wants to have  os(x64 and x86) in one rdpwrap.ini , Combine them in one Header.

I add  a small sample to help you to clarify the data sections.

rdpwrap-light_for_viaba.txt in rdpwrap-light_for_viaba.zip

**Comment by jaxjexjox** [comment] 2018-12-19 01:06
Which ini file is the right one to grab?  It seems Microsoft have been messing with the file a lot lately?

**Comment by vibaaa** [comment] 2018-12-19 08:11
All works. Thanks.
Has attached a file rdpwrap.ini which works on x86 and x64 Windows Pro 10.0.17763.194 version termsrv.dll 10.0.17763.168.
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/2693839/rdpwrap.zip)

**Comment by jaxjexjox** [comment] 2018-12-19 10:13
Ok THAT zip file works - thank you!

**Comment by vibaaa** [comment] 2018-12-19 11:33
One more problem: in approximately 20 minutes the session of a remote desktop is disconnected, how it is possible to correct? It will be connected it is possible right after switching-off, in gpedit.msc switching-off time is not set.

**Comment by hajubu** [comment] 2018-12-19 11:46
@vibaa wrote: 
One more problem: in approximately 20 minutes the session of a remote desktop is disconnected, how it is possible to correct? It will be connected it is possible right after switching-off, in gpedit.msc switching-off time is not set.
… this seems MS Windows behaviour depending on your „Remote Desktop Session Host“ , which features no given timeout by Default.

… found some Infos – BUT Think of RISKs , with Time-Out settings
• OPEN A COMMAND-PROMPT AND TYPE GPEDIT.MSC  TO LAUNCH THE LOCAL GROUP POLICY EDITOR SNAP-IN.
• IN THE LEFT PANEL, EXPAND THE COMPUTER CONFIGURATION NODE OR THE USER CONFIGURATION NODE, DEPENDING IF YOU WANT TO CHANGE THE RDS BEHAVIOUR ON SYSTEM-SCOPE (RECOMMENDED FOR THIS SCENARIO) OR ON USERS-SCOPE (SEE BELOW FOR THE DIFFERENCES).
• NAVIGATE TO ADMINISTRATIVE TEMPLATES > WINDOWS COMPONENTS > REMOTE DESKTOP SERVICES > REMOTE DESKTOP SESSION HOST > SESSION TIME LIMITS.
• IN THE RIGHT PANEL, DOUBLE-CLICK THE SET TIME LIMIT FOR ACTIVE BUT IDLE REMOTE DESKTOP SERVICES SESSIONS POLICY: IN THE MODAL WINDOW THAT WILL APPEAR, ACTIVATE IT BY SWITCHING THE RADIO BUTTON FROM NOT CONFIGURED TO ENABLED, THEN SET THE DESIRED AMOUNT OF TIME IN THE DROP-DOWN LIST RIGHT BELOW.

**Comment by gustavoechavarria** [comment] 2018-12-28 08:27
Hi Everyone, I have tried with this .ini file and it worked for me, it's for 10.0.17763.167 version x64
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/2714373/rdpwrap.zip)
![image](https://user-images.githubusercontent.com/46215774/50508317-6681fd80-0a4f-11e9-9a4b-57872d4141f2.png)

First, stop the service running CMD as administrator, then run net stop termservice
Replace rdpwrap.ini in C:\Program Files\RDP Wrapper
then run net start termservice
Very important Reboot your PC
then when your pc rebooted, run RDPConf to check the states, make sure All states are green
