### ISSUE TITLE
Windows 10 20H2 Update  2021 -- New termsrv.dll version 10.0.19041.1387

### ISSUE THREAD

**Issue by JhonRen** [stascorp/rdpwrap#1661] opened 2021-12-16 01:58 UTC
ini
[10.0.19041.1387]

**Comment by Errorbot1122** [comment] 2021-12-16 02:27
???

**Comment by hiralalshah** [comment] 2021-12-16 06:53
Need rdp wrapper ini for 10.0.19041.1387
if any body has please post

**Comment by bazik5** [comment] 2021-12-16 07:42
+++

**Comment by sashaqwert** [comment] 2021-12-16 16:52
Duplicate of https://github.com/stascorp/rdpwrap/issues/1630

**Comment by DonoDayZ** [comment] 2021-12-16 17:34
![image](https://user-images.githubusercontent.com/37817874/146420810-ba912b15-9c2a-4f93-9f77-9ff9200da0fe.png)
not work for me

**Comment by yorchwa** [comment] 2021-12-16 18:11
> ![image](https://user-images.githubusercontent.com/37817874/146420810-ba912b15-9c2a-4f93-9f77-9ff9200da0fe.png) not work for me
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/7729554/rdpwrap.zip)
![image](https://user-images.githubusercontent.com/59339954/146425975-b494ce29-b709-403d-9910-b2e69833674d.png)
This ini file worked for me

**Comment by sebaxakerhtc** [comment] 2021-12-17 15:43
Duplicate of https://github.com/stascorp/rdpwrap/issues/1630

**Closed as completed by sebaxakerhtc** 2021-12-17 15:43 UTC

**Comment by simonchen** [comment] 2022-02-16 02:28
There is full solution:

https://github.com/simonchen/RDPWrapper_Win10_20H2_termsrv_dll_10.0.19041.1387
