### ISSUE TITLE
win10 64bit 19044.1526

### ISSUE THREAD

**Issue by Maaen93** [stascorp/rdpwrap#1719] opened 2022-02-14 14:03 UTC
win10 64bit 19044.1526 not supported

**Comment by Maaen93** [comment] 2022-02-14 14:04
if any one can help me

**Comment by sebaxakerhtc** [comment] 2022-02-14 14:08
Duplicate of https://github.com/stascorp/rdpwrap/issues/1697

**Closed as completed by sebaxakerhtc** 2022-02-14 14:08 UTC

**Comment by Maaen93** [comment] 2022-02-14 14:29
> Duplicate of #1697

its work thank you bro
