### ISSUE TITLE
RDPWrap

### ISSUE THREAD

**Issue by FrankenPahpii** [stascorp/rdpwrap#104] opened 2016-04-03 21:59 UTC
v1.6 has stopped working on latest Redstone Win10 version.  Any suggestions on how to fix?  Thank you.  Specifically, the listening state says "not listening [not supported]".

**Comment by neuralx** [comment] 2016-04-04 22:06
Have you tried running update.bat as Administrator?

**Comment by FrankenPahpii** [comment] 2016-04-04 23:38
Yes, still does not work.

**Comment by binarymaster** [comment] 2016-04-06 10:01
Probably a duplicate of https://github.com/stascorp/rdpwrap/issues/79

**Closed by binarymaster** 2016-04-06 10:01 UTC
Labels: duplicate
