### ISSUE TITLE
Terminal Services version: 6.3.9600.18928 is not supported

### ISSUE THREAD

**Issue by yottabyte1972** [stascorp/rdpwrap#432] opened 2018-03-18 10:40 UTC
Please add support for 

RDP Wrapper Library v1.6.2
Installer v2.5
Copyright (C) Stas'M Corp. 2017

[*] Notice to user:
  - By using all or any portion of this software, you are agreeing
  to be bound by all the terms and conditions of the license agreement.
  - To read the license agreement, run the installer with -l parameter.
  - If you do not agree to any terms of the license agreement,
  do not use the software.
[*] Installing...
[*] Terminal Services version: 6.3.9600.18928
[-] This version of Terminal Services is not supported.

THX!!

**Comment by yottabyte1972** [comment] 2018-03-18 11:00
Confirmed: is Fixed with:
[6.3.9600.18928]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=8B25D
LocalOnlyCode.x64=nopjmp
SingleUserPatch.x64=1
SingleUserOffset.x64=36C09
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=45495
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=5D830
SLInitFunc.x64=New_CSLQuery_Initialize

[6.3.9600.18928-SLInit]
bFUSEnabled.x64 =FA054
lMaxUserSessions.x64 =FA058
bAppServerAllowed.x64 =FA05C
bInitialized.x64 =FA060
bMultimonAllowed.x64 =FA064
bServerSku.x64 =FA068
ulMaxDebugSessions.x64=FA06C
bRemoteConnAllowed.x64=FA070

Please add to INI
THX

**Comment by binarymaster** [comment] 2018-03-18 11:38
Duplicate of #418.

**Closed by binarymaster** 2018-03-18 11:38 UTC

**Comment by ivanmara555** [comment] 2018-04-13 07:58
Confirm ... win8.1x64 ... after add this sections to ini everything is working! Please add to INI

**Comment by TLBM** [comment] 2018-05-01 23:29
Hi!

Tried the modified ini-file on a german Windows 8.1 Pro x64 [Version 6.3.9600] with all updates, but it is not working though it reads "[fully supported]". Also tried the one from #418 and the 1nd1g0 commit.
![20180502](https://user-images.githubusercontent.com/11824134/39498196-2c4526d6-4d96-11e8-8fb8-5febbc759bc7.png)

The second user get's a message that a user is already logged-in and that he will be disconnected.
![capture_05022018_011709](https://user-images.githubusercontent.com/11824134/39498202-33e52d28-4d96-11e8-9171-b4c41ddde4ed.png)

**Comment by ramjiyaniprajal** [comment] 2018-05-14 13:49
Can you please let me know which ini file needs to update and where it is. I am not much aware about all discussing but having same issue.
