### ISSUE TITLE
19043.1348

### ISSUE THREAD

**Issue by peterhman** [stascorp/rdpwrap#1607] opened 2021-11-11 02:40 UTC
Rdpwrap stopped working after OS update to 19043.1348 yesterday. Will the updated .ini for 19041.1348 work on this version of OS?

**Comment by VanderDT** [comment] 2021-11-11 04:35
Yes. Very necessary. The work is worth it.

**Comment by VanderDT** [comment] 2021-11-11 04:48
[10.0.19041.1348-SLInit]
bServerSku.x86        =D1A08
bRemoteConnAllowed.x86=D1A1C
bFUSEnabled.x86       =D1A28
bAppServerAllowed.x86 =D1A14
bMultimonAllowed.x86  =D1A20
lMaxUserSessions.x86  =D1A0C
ulMaxDebugSessions.x86=D1A24
bInitialized.x86      =D1A04

bServerSku.x64        =10710C
bRemoteConnAllowed.x64=107120
bFUSEnabled.x64       =10712C
bAppServerAllowed.x64 =107118
bMultimonAllowed.x64  =107124
lMaxUserSessions.x64  =107110
ulMaxDebugSessions.x64=107128
bInitialized.x64      =107108

[10.0.19041.1348]
LocalOnlyPatch.x86    =1
LocalOnlyOffset.x86   =B64A9
LocalOnlyCode.x86     =jmpshort
SingleUserPatch.x86   =1
SingleUserOffset.x86  =3BDE7
SingleUserCode.x86    =Zero
DefPolicyPatch.x86    =1
DefPolicyOffset.x86   =3E899
DefPolicyCode.x86     =CDefPolicy_Query_eax_ecx
SLInitHook.x86        =1
SLInitOffset.x86      =68578
SLInitFunc.x86        =New_CSLQuery_Initialize

LocalOnlyPatch.x64    =1
LocalOnlyOffset.x64   =89AC1
LocalOnlyCode.x64     =jmpshort
SingleUserPatch.x64   =1
SingleUserOffset.x64  =0D1E2
SingleUserCode.x64    =Zero
DefPolicyPatch.x64    =1
DefPolicyOffset.x64   =190D5
DefPolicyCode.x64     =CDefPolicy_Query_eax_rcx
SLInitHook.x64        =1
SLInitOffset.x64      =1E6AC
SLInitFunc.x64        =New_CSLQuery_Initialize

**Comment by sebaxakerhtc** [comment] 2021-11-11 08:28
Duplicate of https://github.com/stascorp/rdpwrap/issues/1595#issuecomment-964643800

**Closed as completed by sebaxakerhtc** 2021-11-11 08:28 UTC

**Comment by LeeWiu** [comment] 2021-11-11 10:37
I'm on 1904**3**.1348 and config seams ok but I always get: Another user is signed in, if you continue, they'll be disconnected...
I restarted pc multiple times.
![w](https://user-images.githubusercontent.com/1405188/141283653-fbe1d971-84d6-4a58-b5da-4a2524720fa8.png)
![r](https://user-images.githubusercontent.com/1405188/141283654-36937716-99b3-4329-854c-f16b503b3bb8.png)

**Comment by longingzhu** [comment] 2021-12-01 08:38
It works, thank you.
