### ISSUE TITLE
RDPWrapper  not available after updating Windows system

### ISSUE THREAD

**Issue by beautifulnight** [stascorp/rdpwrap#3355] opened 2024-11-22 02:20 UTC
I encountered the following problems after updating the Windows system:
- In RDPWrapper, it shows support, but the displayed Windows version is inconsistent with the system version. 
- Multiple people can connect to the remote server, but sometimes they will be frequently kicked off or unable to connect. 

Is that a problem and how can i solve it?

![image](https://github.com/user-attachments/assets/cf174a40-58b5-4d43-a3bc-1155b71ffc68)

![image](https://github.com/user-attachments/assets/638005b6-2132-49bf-bcce-e9ac18c27126)

**Comment by binarymaster** [comment] 2024-11-22 11:47
This is a won't fix, because RDP Wrapper shows the version of termsrv.dll file and not the system version, it's expected and by design.

**Closed as not planned by binarymaster** 2024-11-22 11:47 UTC
