### ISSUE TITLE
Termsrv 10.0.19041.1741 [Not Supported]

### ISSUE THREAD

**Issue by ACLS11** [stascorp/rdpwrap#1976] opened 2022-09-02 14:17 UTC
Hello!
My version is not supported.
Can you help me pls?
![CLI_error](https://user-images.githubusercontent.com/75848193/188168842-1a4d341c-129b-44a7-a2b5-e4d0a6f0c3a6.PNG)
![GUI_error](https://user-images.githubusercontent.com/75848193/188168851-6fc0cfa7-3dc8-4bd5-9e58-ed7fd37c34cd.PNG)
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/9478579/termsrv.zip)

**Comment by sashaqwert** [comment] 2022-09-02 15:01
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881

**Closed as not planned by sashaqwert** 2022-09-02 15:01 UTC
Labels: duplicate
