### ISSUE TITLE
Windows 11 10.0.22000.318 not supported 

### ISSUE THREAD

**Issue by coding-lover** [stascorp/rdpwrap#2267] opened 2023-07-06 04:11 UTC

**Comment by sashaqwert** [comment] 2023-07-06 08:12
Duplicate of https://github.com/stascorp/rdpwrap/issues/1599

**Comment by coding-lover** [comment] 2023-07-06 08:13
您好，您发的邮件我已收到，谢谢。

**Closed as not planned by sashaqwert** 2023-07-06 08:12 UTC
Labels: duplicate
