### ISSUE TITLE
10.0.22621.608 Keyboard 

### ISSUE THREAD

**Issue by Overnox** [stascorp/rdpwrap#2069] opened 2022-12-19 11:44 UTC
![Screenshot_1](https://user-images.githubusercontent.com/121029484/208417875-ee36974e-c94a-4d05-8c55-7d020c12f536.png)

Helllo friends,

unfortunately I have the problem as someone in another post.

As soon as two users work on the machine, one of them writes completely different letters or numbers than those that are pressed.

Does anyone have any advice?

https://github.com/stascorp/rdpwrap/issues/532

**Comment by sashaqwert** [comment] 2022-12-19 12:30
Not a RDP Wrapper issue.

Please, read answer by Stas'M in original issue.

And try check your antivirus keyboard settings (input protection, etc)

**Comment by Overnox** [comment] 2022-12-19 12:37
Thanks for answer, can u send me the link from Stas'M original issue?

**Comment by sashaqwert** [comment] 2022-12-19 12:58
> link from Stas'M original issue?

https://github.com/stascorp/rdpwrap/issues/532#issuecomment-447648032

**Comment by sashaqwert** [comment] 2022-12-19 14:08
Duplicate of https://github.com/stascorp/rdpwrap/issues/532

**Closed as not planned by sashaqwert** 2022-12-19 14:08 UTC
Labels: duplicate

**Comment by JackFrisco** [comment] 2023-01-04 16:45
I have read the original thread saying this is not an RDP wrapper issue, but I've installed this on 2 diffrent computers last week and both started having the keyboard issue after the RDP Wrapper install. I hope anyone has an explanation.

**Comment by zqlprovider** [comment] 2023-01-18 12:58
> I have read the original thread saying this is not an RDP wrapper issue, but I've installed this on 2 diffrent computers last week and both started having the keyboard issue after the RDP Wrapper install. I hope anyone has an explanation.

I have the same issue, did you find the solution? Thanks!

**Comment by zqlprovider** [comment] 2023-01-18 12:59
> Thanks for answer, can u send me the link from Stas'M original issue?

Hi, I have the same issue with the keyboard, did you find the solution? Thanks

**Comment by JackFrisco** [comment] 2023-01-18 15:57
I have tried everything, I'm desperate. Clean Windows install with latest driver/Windows updates. No antivirus and no other software installed. As soon as I install the RDP wrapper the keyboard gets messed up after like 2 minutes when 2nd user logs in. I disabled the firewall and whitelisted the RDP wrapper task in the firewall aswell. RPD Wrapper states are Installed, Running, Listening and fully supported. When I uninstall the keyboard is back to normal.

**Comment by zqlprovider** [comment] 2023-01-18 16:36
Yes, it's frustrating. I understand you perfectly. I also tried to set each user as administrator. If you close and reopen Remote Desktop, it seems to be solved but as more users connect the keyboard goes crazy.

**Comment by JackFrisco** [comment] 2023-01-19 13:02
First of all I have to apologise because apparantly I haven't been giving the right information in my prevous post, but I did manage to solve the problem. When I said 'no antivirus' I actually meant I disabled the antivirus software and firewall. Also after further investigation I found out that the chipset driver and BIOS were still not up-to-date. So what I did was completely uninstalled the antivirus software and then manually downloaded and updated both the chipset and BIOS. Everything is working fine now. I can't exactly tell which of the steps resolved the issue but my guess would be the ESET antivirus software, which is really wierd since the other 2 machines are running fine with exactly the same antivirus software. Good luck!

**Comment by Overnox** [comment] 2023-01-19 15:38
@JackFrisco Thank you for the message. I also found out in the meantime that the new feature of ESET under the Security Tools, Secure Online Banking and Payments brings a setting for the keyboard protection "Keylogger". I deactivated the complete function in mid-December and then had no problems for now. Now, unfortunately, the problems come again. My question times to you. Did you after you uninstalled ESET and installed BIOS and chipset driver updates. ESET also installed again? I can not imagine that ESET is the problem for the thing but this keyboard protection "Keylooger" function should be disabled I think. Kind regards from Germany :)

**Comment by zqlprovider** [comment] 2023-01-19 19:11
Well, it looks like ESET is the problem, because I have the same protection.  I did try to disable temporary the antivirus and the issue still occours.  Do you thinks that updating each computer will solve the issue? Thanks and regards from Argentina

**Comment by Overnox** [comment] 2023-01-19 19:30
So guys, I have Eset running on a very strong PC in a law firm. They had the same problem in mid-December last year. On the PC, one was working right before in his user profile. The other user was in the home office and was also working. The problem really only occurred when in the Eset Internet Security version under the settings in the security tools, the function "Secure Online Banking and Payment" was activated. Thereby, the keyboard protection is activated, and it comes to problems with the keyboard input. Since then, they have now had no more problems with double access with two simultaneously logged-on users.
Today, I had the problem with another customer who uses a Windows 11 PC in the cloud with three users at the same time. There, the problem came back. But they had also deactivated the function at Eset. Now, I just updated the BIOS as well as the drivers at all PCs. To update the drivers, I can only recommend Driver Booster Pro Portable. I hope I could help you. Greetings from Germany again.

**Comment by SeyedAbdollahi** [comment] 2024-10-24 13:09
> Not a RDP Wrapper issue.
> 
> Please, read answer by Stas'M in original issue.
> 
> And try check your antivirus keyboard settings (input protection, etc)

I had the same problem, and I realized it was due to a feature in Norton 32 antivirus. I disabled the 'secure all browsers' feature, and the issue was resolved.

![Screenshot (73)](https://github.com/user-attachments/assets/9831a192-d7f4-4939-97d1-e8dfd43417ad)
