### ISSUE TITLE
10.0.17134.1 need help

### ISSUE THREAD

**Issue by justblues** [stascorp/rdpwrap#2201] opened 2023-05-15 01:51 UTC
require windows 10 10.0.1734.1 rdpwrap.ini,please help me,thank you

**Comment by justblues** [comment] 2023-05-15 01:54
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/11473557/termsrv.zip)
![Uploading 372acc2beefdb4f0863289b42951fa8.jpg…]()

**Comment by sashaqwert** [comment] 2023-05-15 07:04
Please, rename your issue to `10.0.17134.1 need help` and fix RDPConf screenshot.

**Comment by sashaqwert** [comment] 2023-05-15 07:07
Offsets here: https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

**Comment by justblues** [comment] 2023-05-15 07:47
![RDPConf](https://github.com/stascorp/rdpwrap/assets/8804041/25b5cd59-96c0-452d-8e14-47148d053a69)

**Comment by justblues** [comment] 2023-05-15 07:58
Thanks a lot !!!

**Comment by justblues** [comment] 2023-05-19 09:55
PLEASE help me , Remote access to my computer from another computer, display other accounts, log in with account password and report password error .   that account belongs to administrator 
![rdpcheck_failed](https://github.com/stascorp/rdpwrap/assets/8804041/56c1e442-f307-444c-b71e-1aa34d59fe85)
![rdfconf_success](https://github.com/stascorp/rdpwrap/assets/8804041/c04c8ebe-9d4a-4c59-b4a6-1b8652b41a0e)
![mstsc_failed](https://github.com/stascorp/rdpwrap/assets/8804041/e26f5668-e74d-4f72-8b16-f7e680f9d746)
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/11515663/termsrv.zip)
![7](https://github.com/stascorp/rdpwrap/assets/8804041/30f1f0fb-2cf3-46b9-ac22-6d02444dead3)

**Comment by sashaqwert** [comment] 2023-05-19 16:22
> PLEASE help me , Remote access to my computer from another computer, display other accounts, log in with account password and report password error . that account belongs to administrator

@sebaxakerhtc Is this offsets correct?

https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

**Comment by sashaqwert** [comment] 2023-05-19 16:23
Duplicate of https://github.com/stascorp/rdpwrap/issues/690

**Closed as not planned by sashaqwert** 2023-05-19 16:23 UTC
Labels: duplicate

**Comment by sebaxakerhtc** [comment] 2023-05-19 17:09
> Is this offsets correct?

Yes, i think so.
It's an old build. If the offsets are wrong - we should have an information
