### ISSUE TITLE
RDP WRAPPER NOT SUPPORTED FOR BUILD 19044.2130

### ISSUE THREAD

**Issue by Sharma73012** [stascorp/rdpwrap#2022] opened 2022-10-17 09:06 UTC
![image](https://user-images.githubusercontent.com/115984143/196137020-f040b6d5-8e36-4e77-ba8c-593ba34b81a2.png)

[
![image](https://user-images.githubusercontent.com/115984143/196137101-f985e3b7-06fe-4f1e-80ba-3e0723fea6a4.png)
](url)

**Comment by sashaqwert** [comment] 2022-10-17 10:42
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992

**Closed as not planned by sashaqwert** 2022-10-17 10:42 UTC
Labels: duplicate
