### ISSUE TITLE
10.0.26100.1882 Not Supported 

### ISSUE THREAD

**Issue by xpinx2pin** [stascorp/rdpwrap#3358] opened 2024-11-22 14:22 UTC
![image](https://github.com/user-attachments/assets/ed604f04-eb90-41c7-85b5-1df35d931d3c)

[termsrv.zip](https://github.com/user-attachments/files/17871381/termsrv.zip)

**Comment by binarymaster** [comment] 2024-11-22 14:32
Duplicate of https://github.com/stascorp/rdpwrap/issues/3285.

**Closed as not planned by binarymaster** 2024-11-22 14:32 UTC
Labels: duplicate
