### ISSUE TITLE
W10 Update 17763.475

### ISSUE THREAD

**Issue by wanglulei** [stascorp/rdpwrap#789] opened 2019-05-20 04:00 UTC
W10 Update 17763.503
![微信截图_20190520115939](https://user-images.githubusercontent.com/50451150/57995852-d4aa8800-7af6-11e9-9645-3a01bee1484f.png)
![微信截图_20190520115950](https://user-images.githubusercontent.com/50451150/57995855-d96f3c00-7af6-11e9-9161-c3e82444c6e2.png)

**Comment by sezercoban** [comment] 2019-05-20 05:44
see #784 comments, ini file working with 17763.503 is attached.

**Comment by wanglulei** [comment] 2019-05-21 12:03
> see #784 comments, ini file working with 17763.503 is attached.

So how do we do this , I don't quite understand

**Comment by wanglulei** [comment] 2019-05-21 12:08
I don't understand

**Comment by fanssite** [comment] 2019-05-22 07:07
By changing .ini file,my Listener state is supported now,but still Not listening.what should i do.

**Comment by estivalinp** [comment] 2019-06-08 12:11
> > see #784 comments, ini file working with 17763.503 is attached.
> 
> So how do we do this , I don't quite understand

go to **issues  [#784](https://github.com/stascorp/rdpwrap/issues/784)**, download **[rdpwrap_JONH.zip](https://github.com/stascorp/rdpwrap/files/3192476/rdpwrap_JONH.zip)** which provided by **jonathan19091**. Copy the downloaded **'rdpwrap.ini'** in to **‘C:\Program Files\RDP Wrapper’** to overwrite the original file. Run **RDPWInst.exe** or use command **`'RDPWInst -r'`** in cmd. Finally, after run **’RDPConf.exe‘** you will find the lisening state is lisenling and supported in your 17763.503 version.
去上面的链接下载rdpwrap_JONH.zip，解压出来然后将rdpwrap.ini放入C:\Program Files\RDP Wrapper覆盖原始文件，运行RDPWInst.exe或者在控制台中运行 **`'RDPWInst -r'`**，最后打开RDPConf.exe查看状态为支持。我自己是测试成功的了。

**Comment by sebaxakerhtc** [comment] 2022-01-04 10:47
Duplicate of https://github.com/stascorp/rdpwrap/issues/720

**Closed as completed by sebaxakerhtc** 2022-01-04 10:47 UTC
