### ISSUE TITLE
Virus detected

### ISSUE THREAD

**Issue by bkolodny** [stascorp/rdpwrap#1151] opened 2020-08-25 13:00 UTC
When trying to download the installer and zip, my browser is saying that a virus is detected.

**Comment by robbak** [comment] 2020-08-25 13:03
Yes lots of antivirus packages are broken and report false positives on
RDPWrap. You'll have to disable your antivirus to retrieve it. You can try
to report the false positive, but AV providers are rather useless at fixing
these things.

**Comment by XiaoFaye** [comment] 2020-09-04 03:20
@bkolodny If you download from Github, you can ignore this, but if you download from other places, be careful.

**Comment by sebaxakerhtc** [comment] 2022-06-20 11:42
Duplicate of https://github.com/stascorp/rdpwrap/issues/277

**Closed as completed by sebaxakerhtc** 2022-06-20 11:42 UTC
