### ISSUE TITLE
windows11 pro 22h2(OS build 22631.4317)  rdpwrap.ini does not support version 10.0.22621.4249

### ISSUE THREAD

**Issue by ajaykakadia123** [stascorp/rdpwrap#3308] opened 2024-10-15 03:03 UTC
![rdpwrapper_screenshot](https://github.com/user-attachments/assets/e48810fe-bb33-4b91-8019-f69d818f55c5)

**Comment by ajaykakadia123** [comment] 2024-10-15 10:21
here is the copy of termserv.dll located in c:\windows\system32 folder
[termsrv.zip](https://github.com/user-attachments/files/17376576/termsrv.zip)

**Comment by binarymaster** [comment] 2024-10-15 12:58
Duplicate of https://github.com/stascorp/rdpwrap/issues/3280.

**Closed as not planned by binarymaster** 2024-10-15 12:58 UTC
Labels: duplicate

**Comment by ajaykakadia123** [comment] 2024-10-16 11:15
after adding the piece of code on #3280, It Worked !
Thank you very much. good luck and best wishes to you guys. pls let me know how to, if i want to make a small contribution to the repository
