### ISSUE TITLE
virustotal finds these as trojan/malware/virus

### ISSUE THREAD

**Issue by awahab01** [stascorp/rdpwrap#412] opened 2018-02-20 03:10 UTC
when scanned with virustotal many scan engines report this is a trojan

**Comment by YisroelAdler** [comment] 2018-02-20 03:15
Was already discussed a lot here, see one discussion here for all relevant information  #about it:
#277

**Comment by binarymaster** [comment] 2018-02-28 16:02
Duplicate of #277.

**Closed by binarymaster** 2018-02-28 16:02 UTC
Labels: duplicate
