### ISSUE TITLE
Windows 10 Home 1903 Build 18362.1082

### ISSUE THREAD

**Issue by ghost** [stascorp/rdpwrap#1173] opened 2020-10-01 05:16 UTC
Is this RDPWrap_ini_Updater a fix for my version OS and RDPWrapper?

Wrapper State: Installed
Service State: Running
Listener State: **_Not Listening_ Not Supported**

Version: 1.5.0.0
Ver: 10.0.18362.836

![RDP Wrapper Conf](https://user-images.githubusercontent.com/72182870/94770850-87852a00-036a-11eb-97ab-dc7afbd217e1.jpg)

**Comment by Iskandare** [comment] 2020-10-06 11:51
I am also waiting for a patch for version 18363 1082
thank you !

**Comment by ryryonline** [comment] 2020-10-09 17:05
This worked for me: https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini

**Comment by Freddd13** [comment] 2020-10-11 01:41
> This worked for me: https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini
@ryryonline
Thanks! It really works.

**Comment by Freddd13** [comment] 2020-10-11 01:42
> This worked for me: https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini

@ryryonline 
It really works. Thanks a lot!

**Comment by Kurisu1129** [comment] 2020-10-23 17:20
> This worked for me: https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini

thanks a lot ! It works on my pc.

**Comment by sebaxakerhtc** [comment] 2022-06-20 11:47
Duplicate of https://github.com/stascorp/rdpwrap/issues/1083

**Closed as completed by sebaxakerhtc** 2022-06-20 11:47 UTC
