### ISSUE TITLE
Windows 21H2 Not Supported

### ISSUE THREAD

**Issue by brkyozell** [stascorp/rdpwrap#1423] opened 2021-06-04 13:31 UTC
![image](https://user-images.githubusercontent.com/40227966/120808688-f9dd8800-c551-11eb-9d61-57ddb8a89e78.png)

I replaced rdpwrap.ini again and again.
I restarted pc again and again.

But it's not working :/
Please help me.

**Comment by brkyozell** [comment] 2021-06-04 13:31
Note: My Windows version: Windows 10 Pro 21H2

**Comment by ChristopherVilla** [comment] 2021-06-04 20:24
Same problem here, anyone has a solution ?

**Comment by saurav-biswas** [comment] 2021-06-06 03:50
[10.0.19041.964]
LocalOnlyPatch.x86=1
LocalOnlyOffset.x86=B65C9
LocalOnlyCode.x86=jmpshort
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=89F31
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x86=1
SingleUserOffset.x86=3BD35
SingleUserCode.x86=nop
SingleUserPatch.x64=1
SingleUserOffset.x64=0CA4C
SingleUserCode.x64=Zero
DefPolicyPatch.x86=1
DefPolicyOffset.x86=3E8A9
DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
DefPolicyPatch.x64=1
DefPolicyOffset.x64=18A15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x86=1
SLInitOffset.x86=687F8
SLInitFunc.x86=New_CSLQuery_Initialize
SLInitHook.x64=1
SLInitOffset.x64=1E29C
SLInitFunc.x64=New_CSLQuery_Initialize
[10.0.19041.964-SLInit]
bInitialized.x86=D1A04
bServerSku.x86=D1A08
lMaxUserSessions.x86=D1A0C
bAppServerAllowed.x86=D1A14
bRemoteConnAllowed.x86=D1A1C
bMultimonAllowed.x86=D1A20
ulMaxDebugSessions.x86=D1A24
bFUSEnabled.x86=D1A28
bInitialized.x64=107108
bServerSku.x64=10710C
lMaxUserSessions.x64=107110
bAppServerAllowed.x64=107118
bRemoteConnAllowed.x64=107120
bMultimonAllowed.x64=107124
ulMaxDebugSessions.x64=107128
bFUSEnabled.x64=10712C

**Comment by orionnelson** [comment] 2021-06-06 13:20
> [10.0.19041.964]
> LocalOnlyPatch.x86=1
> LocalOnlyOffset.x86=B65C9
> LocalOnlyCode.x86=jmpshort
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=89F31
> LocalOnlyCode.x64=jmpshort
> SingleUserPatch.x86=1
> SingleUserOffset.x86=3BD35
> SingleUserCode.x86=nop
> SingleUserPatch.x64=1
> SingleUserOffset.x64=0CA4C
> SingleUserCode.x64=Zero
> DefPolicyPatch.x86=1
> DefPolicyOffset.x86=3E8A9
> DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=18A15
> DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> SLInitHook.x86=1
> SLInitOffset.x86=687F8
> SLInitFunc.x86=New_CSLQuery_Initialize
> SLInitHook.x64=1
> SLInitOffset.x64=1E29C
> SLInitFunc.x64=New_CSLQuery_Initialize
> [10.0.19041.964-SLInit]
> bInitialized.x86=D1A04
> bServerSku.x86=D1A08
> lMaxUserSessions.x86=D1A0C
> bAppServerAllowed.x86=D1A14
> bRemoteConnAllowed.x86=D1A1C
> bMultimonAllowed.x86=D1A20
> ulMaxDebugSessions.x86=D1A24
> bFUSEnabled.x86=D1A28
> bInitialized.x64=107108
> bServerSku.x64=10710C
> lMaxUserSessions.x64=107110
> bAppServerAllowed.x64=107118
> bRemoteConnAllowed.x64=107120
> bMultimonAllowed.x64=107124
> ulMaxDebugSessions.x64=107128
> bFUSEnabled.x64=10712C

[10.0.19041.964-SLInit]
bInitialized.x86      =D0954
bServerSku.x86        =D0958
lMaxUserSessions.x86  =D095C
bAppServerAllowed.x86 =D0964
bRemoteConnAllowed.x86=D096C
bMultimonAllowed.x86  =D0970
ulMaxDebugSessions.x86=D0974
bFUSEnabled.x86       =D0978

bInitialized.x64      =106028
bServerSku.x64        =10602C
lMaxUserSessions.x64  =106030
bAppServerAllowed.x64 =106038
bRemoteConnAllowed.x64=106040
bMultimonAllowed.x64  =106044
ulMaxDebugSessions.x64=106048
bFUSEnabled.x64       =10604C

Is this SLInit still correct?

**Comment by saurav-biswas** [comment] 2021-06-08 13:47
> > [10.0.19041.964]
> > LocalOnlyPatch.x86=1
> > LocalOnlyOffset.x86=B65C9
> > LocalOnlyCode.x86=jmpshort
> > LocalOnlyPatch.x64=1
> > LocalOnlyOffset.x64=89F31
> > LocalOnlyCode.x64=jmpshort
> > SingleUserPatch.x86=1
> > SingleUserOffset.x86=3BD35
> > SingleUserCode.x86=nop
> > SingleUserPatch.x64=1
> > SingleUserOffset.x64=0CA4C
> > SingleUserCode.x64=Zero
> > DefPolicyPatch.x86=1
> > DefPolicyOffset.x86=3E8A9
> > DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
> > DefPolicyPatch.x64=1
> > DefPolicyOffset.x64=18A15
> > DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> > SLInitHook.x86=1
> > SLInitOffset.x86=687F8
> > SLInitFunc.x86=New_CSLQuery_Initialize
> > SLInitHook.x64=1
> > SLInitOffset.x64=1E29C
> > SLInitFunc.x64=New_CSLQuery_Initialize
> > [10.0.19041.964-SLInit]
> > bInitialized.x86=D1A04
> > bServerSku.x86=D1A08
> > lMaxUserSessions.x86=D1A0C
> > bAppServerAllowed.x86=D1A14
> > bRemoteConnAllowed.x86=D1A1C
> > bMultimonAllowed.x86=D1A20
> > ulMaxDebugSessions.x86=D1A24
> > bFUSEnabled.x86=D1A28
> > bInitialized.x64=107108
> > bServerSku.x64=10710C
> > lMaxUserSessions.x64=107110
> > bAppServerAllowed.x64=107118
> > bRemoteConnAllowed.x64=107120
> > bMultimonAllowed.x64=107124
> > ulMaxDebugSessions.x64=107128
> > bFUSEnabled.x64=10712C
> 
> [10.0.19041.964-SLInit]
> bInitialized.x86 =D0954
> bServerSku.x86 =D0958
> lMaxUserSessions.x86 =D095C
> bAppServerAllowed.x86 =D0964
> bRemoteConnAllowed.x86=D096C
> bMultimonAllowed.x86 =D0970
> ulMaxDebugSessions.x86=D0974
> bFUSEnabled.x86 =D0978
> 
> bInitialized.x64 =106028
> bServerSku.x64 =10602C
> lMaxUserSessions.x64 =106030
> bAppServerAllowed.x64 =106038
> bRemoteConnAllowed.x64=106040
> bMultimonAllowed.x64 =106044
> ulMaxDebugSessions.x64=106048
> bFUSEnabled.x64 =10604C
> 
> Is this SLInit still correct?

Works for me

**Comment by brkyozell** [comment] 2021-06-11 09:01
Not working :(
Because probably my Windows version Pro not Server

**Comment by sebaxakerhtc** [comment] 2022-06-20 13:24
Duplicate of https://github.com/stascorp/rdpwrap/issues/1384

**Closed as completed by sebaxakerhtc** 2022-06-20 13:24 UTC
