### ISSUE TITLE
Windows 10 22H2 10.0.19045.3570

### ISSUE THREAD

**Issue by reb00tz** [stascorp/rdpwrap#2382] opened 2023-10-27 09:35 UTC
Although `termsrv.dll` shows version 10.0.1904**1**.3570, Windows shows 10.0.1904**5**.3570, and RDPwrap is not working.
![image](https://github.com/stascorp/rdpwrap/assets/20411812/ffe0e7d3-e60d-447c-88da-0fb63fbefe61)
![image](https://github.com/stascorp/rdpwrap/assets/20411812/f2968b60-580c-4d3e-a36c-e0f5ba1fdcf3)
![image](https://github.com/stascorp/rdpwrap/assets/20411812/3cda29c5-5786-4ac4-82a0-75ed5ecec4ec)

Have already tried uninstalling and reinstalling.

Seems to be fault of Windows Update KB5031816:
![image](https://github.com/stascorp/rdpwrap/assets/20411812/7ac9a94e-49ac-4608-8892-ff9db1bf5e13)

**Comment by reb00tz** [comment] 2023-10-27 09:37
`rdpwrap.ini` Snippet:

```
[10.0.19041.3570-SLInit]
bServerSku.x86        =E4990
bRemoteConnAllowed.x86=E49A4
bFUSEnabled.x86       =E49B0
bAppServerAllowed.x86 =E499C
bMultimonAllowed.x86  =E49A8
lMaxUserSessions.x86  =E4994
ulMaxDebugSessions.x86=E49AC
bInitialized.x86      =E498C

bServerSku.x64        =125078
bRemoteConnAllowed.x64=12508C
bFUSEnabled.x64       =125098
bAppServerAllowed.x64 =125084
bMultimonAllowed.x64  =125090
lMaxUserSessions.x64  =12507C
ulMaxDebugSessions.x64=125094
bInitialized.x64      =125074

[10.0.19041.3570]
LocalOnlyPatch.x86    =1
LocalOnlyOffset.x86   =C3299
LocalOnlyCode.x86     =jmpshort
SingleUserPatch.x86   =1
SingleUserOffset.x86  =3FDC7
SingleUserCode.x86    =Zero
DefPolicyPatch.x86    =1
DefPolicyOffset.x86   =41999
DefPolicyCode.x86     =CDefPolicy_Query_eax_ecx
SLInitHook.x86        =1
SLInitOffset.x86      =70E18
SLInitFunc.x86        =New_CSLQuery_Initialize

LocalOnlyPatch.x64    =1
LocalOnlyOffset.x64   =92AF1
LocalOnlyCode.x64     =jmpshort
SingleUserPatch.x64   =1
SingleUserOffset.x64  =11E12
SingleUserCode.x64    =Zero
DefPolicyPatch.x64    =1
DefPolicyOffset.x64   =1F315
DefPolicyCode.x64     =CDefPolicy_Query_eax_rcx
SLInitHook.x64        =1
SLInitOffset.x64      =2866C
SLInitFunc.x64        =New_CSLQuery_Initialize
```

**Comment by reb00tz** [comment] 2023-10-27 09:40
Here is the `termsrv.dll` file:
[termsrv_dll.zip](https://github.com/stascorp/rdpwrap/files/13187428/termsrv_dll.zip)

**Comment by sashaqwert** [comment] 2023-10-27 10:40
> Although `termsrv.dll` shows version 10.0.1904**1**.3570

OK closing as duplicate. Please, wait :)

**Comment by sashaqwert** [comment] 2023-10-27 10:41
Duplicate of https://github.com/stascorp/rdpwrap/issues/2359

**Closed as not planned by sashaqwert** 2023-10-27 10:41 UTC
Labels: duplicate

**Comment by Chloe1703** [comment] 2025-09-10 08:54
Support for 10.0.19041.4522 (Win10 Home 22H2, 19045.5965)

Hello! Here is my termsrv.dll for version 10.0.19041.4522 (Win10 22H2, build 19045.5965).
Could you please add offsets to rdpwrap.ini?

[termsrv.zip](https://github.com/user-attachments/files/22251328/termsrv.zip)

![Image](https://github.com/user-attachments/assets/7de1f814-6abd-4d8d-a709-61478f6bdb49)
![Image](https://github.com/user-attachments/assets/9feb8c7b-c8b1-4863-8807-1a491f4b483c)
