### ISSUE TITLE
Windows 10 version 10.0.18363.657

### ISSUE THREAD

**Issue by PavloGor** [stascorp/rdpwrap#986] opened 2020-02-12 13:03 UTC
After update to Windows 10 to version 10.0.18363.657
Have error: The number of connections to this computer is limited and all connections are in use right now. Try connecting later or contact your system administrator. 
All menus are green. 
termsrv.dll x64 [https://fex.net/uk/s/esc36yf](url)

**Comment by luky92** [comment] 2020-02-14 15:36
use this #860  like this
put it in C:/Program files/RDP Wraper <-- you should have that folder with all the original files (RDPWInst etc)
uninstall 
disable firewall <--- this is important if it blocks anything while updating it will not work 
run autoupdate.bat it should update and install everything

**Comment by dlh2** [comment] 2021-12-20 10:09
Duplicate of #988

**Comment by sebaxakerhtc** [comment] 2022-04-27 15:51
Duplicate of https://github.com/stascorp/rdpwrap/issues/983

**Closed as completed by sebaxakerhtc** 2022-04-27 15:51 UTC
