### ISSUE TITLE
21H1,19043.1348

### ISSUE THREAD

**Issue by molamolaheng** [stascorp/rdpwrap#1613] opened 2021-11-12 03:27 UTC
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/7524667/termsrv.zip)

**Comment by mispl-2021** [comment] 2021-11-12 05:30
after replace this term file but its not working

**Comment by mispl-2021** [comment] 2021-11-12 05:31
if there any changes in .ini file

**Comment by ohforest** [comment] 2021-11-12 06:43
> after replace this term file but its not working

me too

**Comment by LeeWiu** [comment] 2021-11-12 06:58
Same here https://github.com/stascorp/rdpwrap/issues/1607#issuecomment-966192500

**Comment by sebaxakerhtc** [comment] 2021-11-12 08:26
Duplicate of https://github.com/stascorp/rdpwrap/issues/1595

**Closed as completed by sebaxakerhtc** 2021-11-12 08:26 UTC
