### ISSUE TITLE
RDP NOT SUPORTED -N10.0.19041.3636

### ISSUE THREAD

**Issue by Kgmondal** [stascorp/rdpwrap#2510] opened 2024-03-06 05:05 UTC
You can check RDP functionality with RDPCheck program.
Also you can configure advanced settings with RDPConf program.
![Screenshot (3)](https://github.com/stascorp/rdpwrap/assets/162407306/679c4a76-efa1-4aea-962e-6f82a554629f)

**Comment by sashaqwert** [comment] 2024-03-08 09:19
Duplicate of https://github.com/stascorp/rdpwrap/issues/2381

**Closed as not planned by sashaqwert** 2024-03-08 09:19 UTC
Labels: duplicate
