### ISSUE TITLE
10.0.22621.3958 not working

### ISSUE THREAD

**Issue by hackthedev** [stascorp/rdpwrap#3266] opened 2024-09-05 22:16 UTC
Hi its not working and running the update isnt working as well and idk where the ini file should be its not in the folder:
![image](https://github.com/user-attachments/assets/2853111d-60be-4595-ad97-62c7e0990647)

**Comment by binarymaster** [comment] 2024-09-05 22:25
Duplicate of https://github.com/stascorp/rdpwrap/issues/3238.

**Closed as not planned by binarymaster** 2024-09-05 22:25 UTC
Labels: duplicate
