### ISSUE TITLE
not supported. win 11 23H2 build 22631

### ISSUE THREAD

**Issue by LLIILLEEDD** [stascorp/rdpwrap#3281] opened 2024-09-27 09:14 UTC
after optional cumulative update KB5043145 windows build 22631 rdp wrapper does not work. helped to remove the update
![image](https://github.com/user-attachments/assets/a7827b25-c4b8-486f-8ece-9acbd5e316ba)

**Comment by binarymaster** [comment] 2024-09-27 10:30
Duplicate of https://github.com/stascorp/rdpwrap/issues/3280.

**Closed as not planned by binarymaster** 2024-09-27 10:30 UTC
Labels: duplicate
