### ISSUE TITLE
10.0.22621.4391 not supported pls help asap

### ISSUE THREAD

**Issue by kaereikaerei** [stascorp/rdpwrap#3337] opened 2024-11-11 07:23 UTC
![Screenshot 2024-11-11 152306](https://github.com/user-attachments/assets/722e0f27-737a-4b6e-a2f1-32231e19d18a)

**Comment by binarymaster** [comment] 2024-11-11 16:40
Duplicate of https://github.com/stascorp/rdpwrap/issues/3316.

**Closed as not planned by binarymaster** 2024-11-11 16:40 UTC
Labels: duplicate
