### ISSUE TITLE
WINDOWS 10 19042.330 / Need rdpwrap.ini offset for this version of windows please!

### ISSUE THREAD

**Issue by tjddnjs124** [stascorp/rdpwrap#1130] opened 2020-07-23 00:01 UTC
I use this code copy and paste to ini,but it ins't work. 

Need rdpwrap.ini code for this version of windows please

[10.0.19041.84]
LocalOnlyPatch.x86    =1
LocalOnlyOffset.x86   =B46B9
LocalOnlyCode.x86     =jmpshort
LocalOnlyPatch.x64    =1
LocalOnlyOffset.x64   =87611
LocalOnlyCode.x64     =jmpshort
SingleUserPatch.x86   =1
SingleUserOffset.x86  =3AD27
SingleUserCode.x86    =Zero
SingleUserPatch.x64   =1
SingleUserOffset.x64  =0BF0C
SingleUserCode.x64    =Zero
DefPolicyPatch.x86    =1
DefPolicyOffset.x86   =3D7D9
DefPolicyCode.x86     =CDefPolicy_Query_eax_ecx
DefPolicyPatch.x64    =1
DefPolicyOffset.x64   =17ED5
DefPolicyCode.x64     =CDefPolicy_Query_eax_rcx
SLInitHook.x86        =1
SLInitOffset.x86      =66658
SLInitFunc.x86        =New_CSLQuery_Initialize
SLInitHook.x64        =1
SLInitOffset.x64      =1BDFC
SLInitFunc.x64        =New_CSLQuery_Initialize

[10.0.19041.84-SLInit]
bInitialized.x86      =CF920
bServerSku.x86        =CF924
lMaxUserSessions.x86  =CF928
bAppServerAllowed.x86 =CF930
bRemoteConnAllowed.x86=CF938
bMultimonAllowed.x86  =CF93C
ulMaxDebugSessions.x86=CF940
bFUSEnabled.x86       =CF944

![image](https://user-images.githubusercontent.com/26290547/88240737-0010a000-ccc3-11ea-9d8a-53de40c8e523.png)
![image](https://user-images.githubusercontent.com/26290547/88240741-0272fa00-ccc3-11ea-803a-2a1166be03fe.png)

**Comment by tjddnjs124** [comment] 2020-07-23 00:02
Thanks in advance, developers around the world!

**Comment by princepsycho** [comment] 2020-07-25 08:30
Same, its been weeks im looking for this no one is answering....

**Comment by robbak** [comment] 2020-07-25 08:36
Your rdpwrap version, from your screencap, is 10.0.19041.84 . It is
supported by pretty much all the .ini files being made.

I use asmtron's one.
https://github.com/asmtron/rdpwrap/blob/master/res/rdpwrap.ini

**Comment by sebaxakerhtc** [comment] 2022-06-20 11:14
Duplicate of https://github.com/stascorp/rdpwrap/issues/1004

**Closed as completed by sebaxakerhtc** 2022-06-20 11:14 UTC
