### ISSUE TITLE
win10ent ltsc 10.0.17631.2300

### ISSUE THREAD

**Issue by Raad1n** [stascorp/rdpwrap#1610] opened 2021-11-11 08:27 UTC
Updated rdpwrap.ini with autoupdate
In the status everything is ok
But when connected, it gives a message that "The number of connections to the computer is limited" and throws out a local session
in gpedit, the "Limit the number of connections" parameter is enabled = 999999

![13](https://user-images.githubusercontent.com/94105268/141263936-0fd31e7a-b6b1-4c17-b265-f92c1d903a2a.png)
![11](https://user-images.githubusercontent.com/94105268/141263940-3385d997-eda5-4f90-a96a-916e706bcd7b.png)
![12](https://user-images.githubusercontent.com/94105268/141263942-dbd8f38c-e716-4fd7-b626-84e76100465f.png)
9

**Comment by sebaxakerhtc** [comment] 2021-11-11 08:30
Duplicate of https://github.com/stascorp/rdpwrap/issues/1596

**Closed as completed by sebaxakerhtc** 2021-11-11 08:30 UTC

**Comment by Raad1n** [comment] 2021-11-11 08:41
Thank you, it helped
1. rdpwinst.exe - u
2. rdpwinst.exe - i
3. autoupdate
