### ISSUE TITLE
rdp wrapper not suppoert my pc. plz solve it.

### ISSUE THREAD

**Issue by aniket950840** [stascorp/rdpwrap#2341] opened 2023-09-24 10:51 UTC
[
![Capture](https://github.com/stascorp/rdpwrap/assets/145317098/773f7f18-29fb-44b6-bc27-03b67e273681)
](url)

**Comment by sashaqwert** [comment] 2023-09-24 15:22
Duplicate of https://github.com/stascorp/rdpwrap/issues/2303

**Closed as not planned by sashaqwert** 2023-09-24 15:22 UTC
Labels: duplicate
