### ISSUE TITLE
10.0.17763.1971 not supported

### ISSUE THREAD

**Issue by girubhai** [stascorp/rdpwrap#1673] opened 2021-12-28 09:29 UTC
![WhatsApp Image 2021-12-28 at 2 58 53 PM](https://user-images.githubusercontent.com/3602562/147551567-065cbab6-e6df-4cba-82ea-8a1ef6ab3b62.jpeg)

**Comment by sebaxakerhtc** [comment] 2021-12-29 08:55
Duplicate of https://github.com/stascorp/rdpwrap/issues/1415

**Closed as completed by sebaxakerhtc** 2021-12-29 08:55 UTC
