### ISSUE TITLE
is this normal? (attached screenshot)

### ISSUE THREAD

**Issue by bhatna** [stascorp/rdpwrap#2472] opened 2024-01-27 18:19 UTC
![Screenshot (126)](https://github.com/stascorp/rdpwrap/assets/82880517/68952dcb-d0d7-4050-8c5b-7989842b8f17)

**Comment by binarymaster** [comment] 2024-01-27 20:42
Duplicate of #277.

**Closed as not planned by binarymaster** 2024-01-27 20:42 UTC
Labels: duplicate
