### ISSUE TITLE
Not working, TermServ.DLL 10.0.17763.168, 1,019,392 bytes, Win10 x64 Pro

### ISSUE THREAD

**Issue by jaxjexjox** [stascorp/rdpwrap#616] opened 2018-12-19 02:22 UTC
I've tried adding some text to my INI file and rebooting, still not working.  Am I doing something wrong here?

The update method, does not appear to be pulling down the correct INI file unfortunately?

**Comment by jaxjexjox** [comment] 2018-12-19 02:45
Further to my post, I have replaced, in full my .INI file as located here.
(Yes, I clicked RAW and grabbed the whole file, just removed all the text from the old file and pasted it in??)

https://github.com/warezio/rdpwrap/blob/2ded34c2399e3210f2929942e9cf1395b90daa5d/res/rdpwrap.ini

This has resulted in me being entirely unable to connect to my machine at all, so I guess I'll be fiddling when I get home.
A shame!

**Comment by hajubu** [comment] 2018-12-19 09:54
Hello @jaxjexjox 
That file (warezio ... rdpwrap.ini)  has an error .
It contains a superfluous DATA section  1rst)    [10.0.17763.165] 
and missed 2nd) the [10.0.17763.165-SLInit]
---------------
Meanwhile  you can use a manually Job:  
see last post of vibaaa in #611 he had managed it too 
He added also his tested rdpwrap.ini – using the official data from the repo and added the necessary data section.
@ andrePKI also had given a very short „cooking recipee“ how doing the Exchange of the rdpwrap.ini.
BTW – I’m just an user like you ! 
refer also to your post in #606 and my answer-------------------------------------------------
Good Luck !

**Comment by hajubu** [comment] 2018-12-19 10:17
@warezio
- Please have check on your personal branch for the rdpwrap.ini data.
It contains a superfluous DATA section 1rst) [10.0.17763.165] and missed 2nd) the [10.0.17763.165-SLInit]

But if you do not have the termsrv.dll version 165 - There is no need for this two data areas.
Normally you should implement 17763.1 and 17763.168 , latter works in Winver 10x 17763.194 , too) 
b.r. hajubu

**Comment by binarymaster** [comment] 2018-12-19 22:00
Duplicate of #606.

No need to open duplicated issues and post messages in them.

**Closed by binarymaster** 2018-12-19 22:00 UTC
