### ISSUE TITLE
10.0.19043.1706 NOT SUPPORTED

### ISSUE THREAD

**Issue by snow-to-earth** [stascorp/rdpwrap#1853] opened 2022-05-16 14:06 UTC

**Comment by snow-to-earth** [comment] 2022-05-16 14:31
termsrv

**Comment by snow-to-earth** [comment] 2022-05-16 15:00
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/8701159/termsrv.zip)

**Comment by mateuscdor** [comment] 2022-05-16 16:27
@sebaxakerhtc

**Comment by sebaxakerhtc** [comment] 2022-05-16 19:52
Duplicate of https://github.com/stascorp/rdpwrap/issues/1823

**Closed as completed by sebaxakerhtc** 2022-05-16 19:52 UTC
