### ISSUE TITLE
Windows 11 10.0.22621.608 not supported

### ISSUE THREAD

**Issue by lingchenma** [stascorp/rdpwrap#2179] opened 2023-04-23 12:35 UTC
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/11303730/termsrv.zip)
![image](https://user-images.githubusercontent.com/48959004/233840136-1d902ffb-609b-4245-b786-970fb7631b2c.png)

**Comment by sashaqwert** [comment] 2023-04-23 14:36
Duplicate of https://github.com/stascorp/rdpwrap/issues/2006

**Closed as not planned by sashaqwert** 2023-04-23 14:36 UTC
Labels: duplicate
