### ISSUE TITLE
Windows 10 - 10.0.15063.1155

### ISSUE THREAD

**Issue by cra3yk** [stascorp/rdpwrap#570] opened 2018-09-26 07:58 UTC
Hi

Please add support to this version - some of my machines stuck on this version and I can't update to newest 1709 to move to 16299 without that.

It seems that the newest rdpwrap.ini doesn't have this section (below), please include it into newest build too:

[10.0.15063.1155]
; no x86 version
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=8CB01
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=15EA4
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=FAE5
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=234DC
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.15063.1155-SLInit]
; no x86 version
bInitialized.x64 =E9468
bRemoteConnAllowed.x64=E946C
bMultimonAllowed.x64 =E9470
ulMaxDebugSessions.x64=E9474
bFUSEnabled.x64 =E9478
bServerSku.x64 =E9484
lMaxUserSessions.x64 =E9488
bAppServerAllowed.x64 =E948C

**Comment by binarymaster** [comment] 2018-09-26 11:06
Duplicate of #506.

**Closed by binarymaster** 2018-09-26 11:06 UTC
