### ISSUE TITLE
ver 10.0.19041.2913 not suported

### ISSUE THREAD

**Issue by 0xDoubleJump** [stascorp/rdpwrap#2240] opened 2023-06-03 17:44 UTC

**Comment by 0xDoubleJump** [comment] 2023-06-03 17:48
Hi! Can help me? thanks
![image](https://github.com/stascorp/rdpwrap/assets/135455808/3ad296a8-8c41-455c-8f74-8c94457f5ce5)
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/11643347/termsrv.zip)´
Not sure if this is the why im getting a error message when im trying to log in.
The message is: "The number of connections with this computer is limited and all the versions are used in the moment. Try to connect later."

**Comment by sashaqwert** [comment] 2023-06-04 09:42
Duplicate of https://github.com/stascorp/rdpwrap/issues/2180

**Closed as not planned by sashaqwert** 2023-06-04 09:42 UTC
Labels: duplicate
