### ISSUE TITLE
Windows 10 10.0.19044.3448 not supported

### ISSUE THREAD

**Issue by networkoper** [stascorp/rdpwrap#2333] opened 2023-09-13 19:54 UTC
Does anyone have rdpwrap ini file?

![rd](https://github.com/stascorp/rdpwrap/assets/143348479/9f2652c5-08b2-4309-8a77-ba18e2e92bdf)

**Comment by sashaqwert** [comment] 2023-09-14 07:50
Duplicate of https://github.com/stascorp/rdpwrap/issues/2289

**Closed as not planned by sashaqwert** 2023-09-14 07:50 UTC
Labels: duplicate
