### ISSUE TITLE
Windows 10 64-bit version 10.0.19041.1387 

### ISSUE THREAD

**Issue by ridern8** [stascorp/rdpwrap#1663] opened 2021-12-16 07:15 UTC
i cant use multiple person at a time in same user in Windows 10 64-bit version 10.0.19041.1387

**Comment by LightmanHub** [comment] 2021-12-16 08:28
Use sections [10.0.19041.1387-SLInit] and [10.0.19041.1387] from here 
https://github.com/stascorp/rdpwrap/issues/1662

**Comment by JorgaWetzel** [comment] 2021-12-16 11:48
after replacing the rdpwrap.ini from post #1662 the issue is not fixed. can you please show this again

**Comment by simonpatap0n** [comment] 2021-12-16 15:49
same here after replacing the INI file, RDP works but not multi-user
![Capture](https://user-images.githubusercontent.com/22940564/146403597-7a1eb9c0-d84c-4c21-84db-db7d3adb3065.PNG)

**Comment by DonoDayZ** [comment] 2021-12-16 17:34
![image](https://user-images.githubusercontent.com/37817874/146420756-6fc4de85-b67f-4267-8f62-c56bcaae6112.png)
not work for me

**Comment by sinisa-colic** [comment] 2021-12-16 21:49
As a temporary fix, open Windows Update settings, click View update history, click Uninstall updates, select the latest security update and uninstall it.

**Comment by sebaxakerhtc** [comment] 2021-12-17 15:43
Duplicate of https://github.com/stascorp/rdpwrap/issues/1630

**Closed as completed by sebaxakerhtc** 2021-12-17 15:43 UTC
