### ISSUE TITLE
10.0.19045.3324

### ISSUE THREAD

**Issue by zhaojing629** [stascorp/rdpwrap#2320] opened 2023-08-25 11:32 UTC
My windows was updated today, and it seems to be version 10.0.19045.3324. I searched the Internet for a long time but did not find the dll version 19045
I saw a post saying that 19045 can use version 19041, but my current dll is 10.0.19041.3271, and I still can't use remote desktop.

**Comment by zhaojing629** [comment] 2023-08-25 11:37
I saw the previous question, it seems that the termsrv.dll in my current computer is needed, I don't know if the one I uploaded is correct.

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/12438709/termsrv.zip)

**Comment by sashaqwert** [comment] 2023-08-26 09:45
> but my current dll is 10.0.19041.3271

The `rdpwrap.ini` file using only `termsrv.dll` versions (not Windows)

**Comment by sashaqwert** [comment] 2023-08-26 09:45
Duplicate of https://github.com/stascorp/rdpwrap/issues/2289

**Closed as not planned by sashaqwert** 2023-08-26 09:45 UTC
Labels: duplicate

**Comment by sashaqwert** [comment] 2023-08-26 09:47
> I still can't use remote desktop.

You need update your `rdpwrap.ini` file.

**Comment by zhaojing629** [comment] 2023-09-04 13:31
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/12514165/rdpwrap.zip)
Thank you very much!!
Sorry for uploading the wrong file earlier.
