### ISSUE TITLE
Termsrv.dll Patch 10.0.17763.437

### ISSUE THREAD

**Issue by yesidtaz** [stascorp/rdpwrap#750] opened 2019-04-16 04:08 UTC
![image](https://user-images.githubusercontent.com/48970086/56181489-53317880-5fd3-11e9-9436-53a89dd47fb8.png)

Hello friends for those who wish to just use the termsrv and activate the remote desktop manually here I bring the Termsrv Patch 10.0.17763.437, it was tested in windows 10 pro x64, I hope it helps.

Thank you does not count anything if it worked.

Download [Termsrv Patch 10.0.17763.437](https://github.com/stascorp/rdpwrap/files/3082981/Termsrv.Patch.10.0.17763.437.zip)

**Comment by armando1385** [comment] 2019-04-16 23:57
hello, I have this same version and today I was not supported, download your patch but it keeps saying the same thing, you would tell me the steps to execute it from scratch. I surely made a bad step. thank you

**Comment by Slonar** [comment] 2019-04-17 12:04
Hello, tried the patch for 10.0.17763.437, script ran correctly but still get "version not supported"

**Comment by Slonar** [comment] 2019-04-17 15:12
Well, after installing it would seem that Remote desktop cannot restart, after running the script in console message in console that it could not restart...  

If I read the script correctly, the termsrv.dll.bak would be a backup of my original dll, so should I replace the new dll with the backup, or find a termsrv.dll on the internets?

**Comment by Slonar** [comment] 2019-04-17 15:12
Well, after installing it would seem that Remote desktop cannot restart, after running the script in console message in console that it could not restart...  

If I read the script correctly, the termsrv.dll.bak would be a backup of my original dll, so should I replace the new dll with the backup, or find a termsrv.dll on the internets?

**Comment by yesidtaz** [comment] 2019-04-17 16:35
This patch is for use without the rdpwrap, the use of rdpwrap is a software that intermediates between the termsrv.dll and makes it work without needing to have modified the termsrv.dll, knowing this when using the modified termsrv.dll does not need to use the rdpwrap.

Use the termsrv.dll of my windows 10 pro x64 and modify and rehearse it and the multiuser works correctly, I have no where else to try it so I do not know if it works on other machines.

**Comment by yesidtaz** [comment] 2019-04-17 16:42
> Bueno, después de la instalación parecería que el escritorio remoto no se puede reiniciar, después de ejecutar el script en el mensaje de la consola en la consola que no se pudo reiniciar ...
> 
> Si leo la secuencia de comandos correctamente, termsrv.dll.bak sería una copia de seguridad de mi dll original, ¿debería reemplazar la nueva dll con la copia de seguridad, o encontrar un termsrv.dll en las redes internas?

Correct this command makes a copy of your termsrv.dll to restore it you must execute the following command with administrator rights

del c:\windows\system32\termsrv.dll
ren c:\windows\system32\termsrv.dll.bak termsrv.dll

**Comment by Slonar** [comment] 2019-04-17 17:37
Thank you

**Comment by vtjballeng** [comment] 2019-04-23 21:58
Seems there are some permissions issues:
![image](https://user-images.githubusercontent.com/12535732/56618639-3c051300-65f1-11e9-9636-f6877f83f80a.png)

**Comment by yesidtaz** [comment] 2019-04-24 00:15
> Seems there are some permissions issues:
> ![image](https://user-images.githubusercontent.com/12535732/56618639-3c051300-65f1-11e9-9636-f6877f83f80a.png)

Good day friend, it goes out that denied since there is some program that is blocking the modification, it can be the antivirus or any other program that you use to block modifications of the system, you must deactivate this software before making the change.

**Comment by vtjballeng** [comment] 2019-04-24 02:58
Thanks. I ended up heading to this thread and moving the rdpwrap.ini with my original termsrv.dll file which worked. I was able to change the termsrv.dll manually by taking permission but it did not resolve the issue in my case.

https://github.com/stascorp/rdpwrap/issues/729
Specifically FZappatta & https://github.com/stascorp/rdpwrap/files/3062713/rdpwrap.zip

I also had the wrong user for one service.
https://github.com/stascorp/rdpwrap/issues/391

**Comment by xrabbut** [comment] 2019-11-06 16:46
Hi, thanks for the work, try this.
[Termsrv.Patch.10.0.17763.437_V2.zip](https://github.com/stascorp/rdpwrap/files/3815714/Termsrv.Patch.10.0.17763.437.zip)

**Comment by slywall** [comment] 2020-04-06 21:16
i have problems, the past version only acept 16 users, i need more, this version can helpme?, the error that i can see is error in Remote Display Driver

**Comment by yomgui66330** [comment] 2020-12-27 20:13
Hi Bro. I verify on Windows Server 2019 Datacenter and it work great :-) thanks a lot

**Comment by abstatic** [comment] 2021-04-11 08:58
Thank you! Worked like a charm on windows server 2019 17763 build 
All I had to do the give ownership of termsrv.dll to the Administrator user

**Comment by NgaoDaCoPho** [comment] 2021-12-10 08:33
Thank you, but now new windows server 2019 update fixxed it, can you help me:((

**Comment by sebaxakerhtc** [comment] 2022-01-04 10:25
Duplicate of https://github.com/stascorp/rdpwrap/issues/720

**Closed as completed by sebaxakerhtc** 2022-01-04 10:25 UTC

**Comment by Avlasov18** [comment] 2022-02-02 08:39
> Спасибо, но теперь новое обновление Windows Server 2019 исправило это, вы можете мне помочь 
Did you fix it?

**Comment by sebaxakerhtc** [comment] 2022-02-02 08:53
> > Спасибо, но теперь новое обновление Windows Server 2019 исправило это, вы можете мне помочь
> > Did you fix it?

It is fixed already. Just update ini or use my modded version of rdpwrapper

**Comment by andersongmont** [comment] 2022-09-19 12:51
Good Morning,

How many users can I use simultaneously?

**Comment by andersongmont** [comment] 2022-09-19 12:59
@yesidtaz 
Good Morning,

How many users can I use simultaneously?
