### ISSUE TITLE
18362.295 Windows 10 

### ISSUE THREAD

**Issue by moonjutsu** [stascorp/rdpwrap#892] opened 2019-10-02 11:18 UTC
Hello to all.
In general, rpdwrapper supports my version, I updated the ini file from 09.07, but the problem is that the user restrictions still remain.
I don’t know how to solve it, I tried to set it again, but to no avail.
A space after the last line is.
![Screenshot_1](https://user-images.githubusercontent.com/56073813/66040201-8c2cbd80-e51f-11e9-923c-009e737da813.png)
![Screenshot_2](https://user-images.githubusercontent.com/56073813/66040202-8c2cbd80-e51f-11e9-8902-5fe932d32e0b.png)

**Comment by brgcosta** [comment] 2019-10-03 17:42
The solution bellow solved my problem on Windows 10 1903 18362.387

https://github.com/stascorp/rdpwrap/issues/889#issue-499827283

**Comment by sebaxakerhtc** [comment] 2022-06-20 10:13
Duplicate of https://github.com/stascorp/rdpwrap/issues/871

**Closed as completed by sebaxakerhtc** 2022-06-20 10:13 UTC
