### ISSUE TITLE
19045.4291 is not support

### ISSUE THREAD

**Issue by yabaoer** [stascorp/rdpwrap#2557] opened 2024-04-11 04:09 UTC
![image](https://github.com/stascorp/rdpwrap/assets/9652060/2a81e805-db59-482b-9abb-325126a907af)

**Comment by yabaoer** [comment] 2024-04-11 04:13
[Uploading rdpwrap.dll.zip…]()

**Comment by warning0810** [comment] 2024-04-11 06:31
Same problem...

**Comment by warning0810** [comment] 2024-04-11 07:22
This worked for me:
[autoupdate_v1.2.zip](https://github.com/stascorp/rdpwrap/files/14942739/autoupdate_v1.2.zip)
 Place in rdpwrap folder and open as administrator,after finish restart the pc

**Comment by loyejaotdiqr47123** [comment] 2024-04-11 12:44
> ![image](https://private-user-images.githubusercontent.com/9652060/321500405-2a81e805-db59-482b-9abb-325126a907af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4Mzk3MjgsIm5iZiI6MTcxMjgzOTQyOCwicGF0aCI6Ii85NjUyMDYwLzMyMTUwMDQwNS0yYTgxZTgwNS1kYjU5LTQ4MmItOWFiYi0zMjUxMjZhOTA3YWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTFUMTI0MzQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGQ3NjBmZTE4NDRlMTQ5NWUwZWJkNDg2Yzk5N2JkY2JiZWE3NjgyOGIyMjY0YmEzZDI1ZjdlMjBhNDNmZDA2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tg_ZmF8pCVlrJMwK363H0xCqaSA9CunhnWndnKgxCBc)

没有上传termsrv.dll文件和rdpconf的截图。

**Comment by ikikenshin** [comment] 2024-04-11 19:01
**Alguna solution...** 
Es una nueva actualizacion

**Comment by ikikenshin** [comment] 2024-04-11 19:01
> This worked for me: [autoupdate_v1.2.zip](https://github.com/stascorp/rdpwrap/files/14942739/autoupdate_v1.2.zip) Place in rdpwrap folder and open as administrator,after finish restart the pc

lo probe pero no tiene ningun cambio... el problema persiste

**Comment by ultrakanji** [comment] 2024-04-12 05:26
>Use RDPConf.exe to see the actual required version. You will likely find it as 10.0.18362.657 at this time.... you need 3rd party INI file as the update of the project will not give you an INI file that will work with many current day setups.
You can likely use [my ini](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini) file, then do RDPWInst -r in an elevated cmd session to restart RDP WRapper related service.

Above #1022 INI file works for me!
Windows 10 Home
Version 22H2 Build 19045.4291

**Comment by a115599663322** [comment] 2024-04-12 06:36
添加到rdpwrap.ini


[10.0.19041.4239]
LocalOnlyPatch.x86    =1
LocalOnlyOffset.x86   =C1B19
LocalOnlyCode.x86     =jmpshort
SingleUserPatch.x86   =1
SingleUserOffset.x86  =45675
SingleUserCode.x86    =Zero
DefPolicyPatch.x86    =1
DefPolicyOffset.x86   =41629
DefPolicyCode.x86     =CDefPolicy_Query_eax_ecx
SLInitHook.x86        =1
SLInitOffset.x86      =6FCD8
SLInitFunc.x86        =New_CSLQuery_Initialize

LocalOnlyPatch.x64    =1
LocalOnlyOffset.x64   =91191
LocalOnlyCode.x64     =jmpshort
SingleUserPatch.x64   =1
SingleUserOffset.x64  =182BB
SingleUserCode.x64    =Zero
DefPolicyPatch.x64    =1
DefPolicyOffset.x64   =1F2D5
DefPolicyCode.x64     =CDefPolicy_Query_eax_rcx
SLInitHook.x64        =1
SLInitOffset.x64      =27FFC
SLInitFunc.x64        =New_CSLQuery_Initialize

[10.0.19041.4239-SLInit]
bServerSku.x86        =E398C
bRemoteConnAllowed.x86=E39A0
bFUSEnabled.x86       =E39AC
bAppServerAllowed.x86 =E3998
bMultimonAllowed.x86  =E39A4
lMaxUserSessions.x86  =E3990
ulMaxDebugSessions.x86=E39A8
bInitialized.x86      =E3988

bServerSku.x64        =123078
bRemoteConnAllowed.x64=12308C
bFUSEnabled.x64       =123098
bAppServerAllowed.x64 =123084
bMultimonAllowed.x64  =123090
lMaxUserSessions.x64  =12307C
ulMaxDebugSessions.x64=123094
bInitialized.x64      =123074

**Comment by YUI556** [comment] 2024-04-12 11:57
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/14958355/rdpwrap.zip)
this works for me

**Comment by sashaqwert** [comment] 2024-04-12 14:56
Duplicate of https://github.com/stascorp/rdpwrap/issues/2529

**Closed as not planned by sashaqwert** 2024-04-12 14:56 UTC
Labels: duplicate

**Comment by seleusan** [comment] 2024-04-16 17:38
Como ejecutas el archivo .ini?

**Comment by navalito** [comment] 2024-04-26 14:12
No hay solución aun para la nueva actualización que ha tenido Windows 10 y su nueva compilación 19045.4291 he modificado todas las lineas posibles en el rdp wrapper  en un intento de levantar el error y no permite la conexión con múltiples escritorios, si alguna persona ya obtuvo resultados favorables, por favor puede hacer el post. No crear falsas expectativas y no inducir al error, con esta supuesta actualización del autoupdate.bat.
