### ISSUE TITLE
WIN11 10.0.22621.3235

### ISSUE THREAD

**Issue by WANGKUOWEI** [stascorp/rdpwrap#2507] opened 2024-03-01 09:06 UTC
![20240301-10](https://github.com/stascorp/rdpwrap/assets/42328451/00439689-dd2b-4d17-9d37-3c2d08a97e8b)

**Comment by asmtron** [comment] 2024-03-01 10:59
add support x64

https://github.com/asmtron/rdpwrap/blob/master/res/rdpwrap.ini

RDP Wrapper & Autoupdate
https://github.com/asmtron/rdpwrap/tree/master

**Comment by sashaqwert** [comment] 2024-03-02 12:47
Duplicate of https://github.com/stascorp/rdpwrap/issues/2504

**Closed as not planned by sashaqwert** 2024-03-02 12:47 UTC
Labels: duplicate
