### ISSUE TITLE
RDP Wrapper 

### ISSUE THREAD

**Issue by Tamil-selv** [stascorp/rdpwrap#2021] opened 2022-10-17 08:17 UTC
![image](https://user-images.githubusercontent.com/115980721/196125040-921e0935-aa55-4048-bd03-fde7a5a0ad47.png)

**Comment by sashaqwert** [comment] 2022-10-17 08:51
Duplicate of https://github.com/stascorp/rdpwrap/issues/1595

**Closed as not planned by sashaqwert** 2022-10-17 08:51 UTC
Labels: duplicate
