### ISSUE TITLE
rpdwarp   termservice error 5 build 10.0.17763.292

### ISSUE THREAD

**Issue by gumipedro** [stascorp/rdpwrap#696] opened 2019-03-12 16:43 UTC
when i install RPD wraptter  termservice stops and it cant be start again. until you uninstalled . I try with a new .ini  and restart the pc but it doesn't work. 
![error](https://user-images.githubusercontent.com/48487829/54218672-a0419c80-44b3-11e9-80ec-9fe6be02afd1.png)
![error2](https://user-images.githubusercontent.com/48487829/54218674-a33c8d00-44b3-11e9-8dc0-1abb03f67cb2.png)

**Comment by bellenic** [comment] 2019-03-13 19:14
check solution §697 it is working fine for 17763;292 too

**Comment by sashaqwert** [comment] 2024-01-28 12:21
Issues cleanup...

One `termsrv.dll` version for one architecture = ONE opened issue!

**Comment by sashaqwert** [comment] 2024-01-28 12:22
Duplicate of https://github.com/stascorp/rdpwrap/issues/645

**Closed as not planned by sashaqwert** 2024-01-28 12:22 UTC
Labels: duplicate
