### ISSUE TITLE
Add support for version 10.0.14393.2457

### ISSUE THREAD

**Issue by logiu** [stascorp/rdpwrap#562] opened 2018-09-18 13:45 UTC
Windows Server 2016 
Version: 1607
Build: 14393.2485

termsrv.dll
[termsrv.dll.zip](https://github.com/stascorp/rdpwrap/files/2392909/termsrv.dll.zip)

**Comment by binarymaster** [comment] 2018-09-18 13:46
Duplicate of #542.

**Closed by binarymaster** 2018-09-18 13:46 UTC
