### ISSUE TITLE
win10 pro winver 1709 16299.19

### ISSUE THREAD

**Issue by Lautren** [stascorp/rdpwrap#335] opened 2017-10-25 09:56 UTC
What do I need to do to RDP Wrapper  will work with winver 1709? This yt link cannot help me with this problem (https://www.youtube.com/watch?v=W9BpbEt1yJw)
I can repeat myself or someone, maybe someone wrote something like that, but I did not see any

**Comment by Lautren** [comment] 2017-10-25 10:55
![2017-10-25_16-41-43](https://user-images.githubusercontent.com/22935575/31995201-a9c0d484-b9ad-11e7-8ef8-51f5e5dcad48.png)

**Comment by binarymaster** [comment] 2017-10-25 12:39
Duplicate of #323.

**Closed by binarymaster** 2017-10-25 12:39 UTC
Labels: duplicate
