### ISSUE TITLE
termsrv.dll not supported on Windows 10 1903 Build 18362.657

### ISSUE THREAD

**Issue by TheMargarineMan** [stascorp/rdpwrap#997] opened 2020-02-15 17:49 UTC
The Installer said that the dll I have is not supported by RDP and it told me to run the update batch file. I did and it did nothing so here I am. Here's the file as a txt file
[termsrv.txt](https://github.com/stascorp/rdpwrap/files/4208831/termsrv.txt)

**Comment by sawwd** [comment] 2020-02-16 21:40
@TheMargarineMan check here https://github.com/stascorp/rdpwrap/issues/999

**Comment by sebaxakerhtc** [comment] 2022-04-27 15:50
Duplicate of https://github.com/stascorp/rdpwrap/issues/983

**Closed as completed by sebaxakerhtc** 2022-04-27 15:50 UTC
