### ISSUE TITLE
10.0.22000.2777 Not Listening [not supported]

### ISSUE THREAD

**Issue by josephny** [stascorp/rdpwrap#2490] opened 2024-02-16 11:40 UTC
I have .2777 in use and the latest .ini but still can't get past the "Not Listening" problem.

Any advice?

Thanks.

**Comment by sebaxakerhtc** [comment] 2024-02-16 18:58
Duplicate of https://github.com/stascorp/rdpwrap/issues/2486

**Closed as completed by sebaxakerhtc** 2024-02-16 18:58 UTC
Labels: duplicate
