### ISSUE TITLE
New version "19044.1766"

### ISSUE THREAD

**Issue by reisier** [stascorp/rdpwrap#1899] opened 2022-06-15 10:18 UTC

**Comment by ForwardUntoDawn** [comment] 2022-06-15 14:21
The latest INI from @sebaxakerhtc sorted this out for 19044.1766 on this end.
https://github.com/sebaxakerhtc/rdpwrap.ini/commit/7175c06c1779c5aa6e34b14478ddcb96070cc3f2
https://github.com/stascorp/rdpwrap/issues/1881#issuecomment-114563562

![Screenshot 2022-06-15 102033](https://user-images.githubusercontent.com/23408644/173850603-9297edc8-6c3e-47e5-8ea7-3a7544db0a7a.png)
1

**Comment by sebaxakerhtc** [comment] 2022-06-15 15:33
Please attach your termsrv.dll

**Comment by reisier** [comment] 2022-06-15 15:42
![termsrv](https://user-images.githubusercontent.com/5859481/173869192-3078ef3f-0270-4e43-854d-9ed1903da043.gif)

Please rename to dll. Thanks

**Comment by sebaxakerhtc** [comment] 2022-06-15 15:43
> Please rename to dll. Thanks

There's no file. Use ZIP

**Comment by reisier** [comment] 2022-06-15 15:43
![termsrv](https://user-images.githubusercontent.com/5859481/173869313-131ed389-652f-4833-b3b2-0032d563b83e.gif)

https://user-images.githubusercontent.com/5859481/173869518-25b4d127-f9e9-4b05-9f22-63dd2f11f43e.mov

**Comment by reisier** [comment] 2022-06-15 15:44
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/8910986/termsrv.zip)

Please rename!

**Comment by sebaxakerhtc** [comment] 2022-06-15 15:46
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881
Windows version doesn't matter - always look at termsrv.dll version

**Closed as completed by sebaxakerhtc** 2022-06-15 15:46 UTC
