### ISSUE TITLE
windows home 10.0.18362.418 NOT Listening

### ISSUE THREAD

**Issue by daleSys** [stascorp/rdpwrap#1257] opened 2020-12-23 03:13 UTC
![image](https://user-images.githubusercontent.com/20851920/102954973-ce209580-450f-11eb-9804-f980683d40cc.png)

**Comment by JD-aus** [comment] 2021-01-01 02:21
why are you using such an old version ?

**Comment by sebaxakerhtc** [comment] 2022-06-20 12:13
Duplicate of https://github.com/stascorp/rdpwrap/issues/871

**Closed as completed by sebaxakerhtc** 2022-06-20 12:13 UTC
