### ISSUE TITLE
Not supported 

### ISSUE THREAD

**Issue by send415** [stascorp/rdpwrap#1069] opened 2020-04-28 19:09 UTC
Hello . I'm trying this for first time. Please help me fix this one?
i can downgrade windows or reinstall if i have to 
I tried updating RDPwrapper same not supported
![image](https://user-images.githubusercontent.com/35176653/80527402-28e5fb00-8949-11ea-9d60-39db9db7d5be.png)

**Comment by affinityv** [comment] 2020-04-29 01:35
https://github.com/stascorp/rdpwrap/issues/1022#issuecomment-596437997

**Comment by send415** [comment] 2020-04-29 16:25
> [#1022 (comment)](https://github.com/stascorp/rdpwrap/issues/1022#issuecomment-596437997)

getting access denied now. everything is green.

**Comment by send415** [comment] 2020-04-29 16:28
![image](https://user-images.githubusercontent.com/35176653/80621163-c4d03f00-89fb-11ea-88b2-d1feeda30747.png)

**Comment by send415** [comment] 2020-04-29 16:28
![image](https://user-images.githubusercontent.com/35176653/80621219-d87ba580-89fb-11ea-99ba-b64d7dbc4d63.png)

**Comment by robbak** [comment] 2020-04-29 22:56
Great - that means everything is working.

You just need to work out what the username and password on that computer is. You need to have set a password, and the username might not be the name displayed when you log in. Run 'control userpasswords2' to check what the username really is.

**Comment by send415** [comment] 2020-04-30 01:56
> Great - that means everything is working.
> 
> You just need to work out what the username and password on that computer is. You need to have set a password, and the username might not be the name displayed when you log in. Run 'control userpasswords2' to check what the username really is.

When i rdp to this pc it is still logging the user out

**Comment by robbak** [comment] 2020-04-30 02:08
Yes, it is meant to do that. Especially with 'Single Session per User" selected.

There is a group working on ways to let it create a new session instead of logging the user out at #1064 . They are not having much success.

There is also session shadowing, but it seems that requires a network that logs everyone in using a domain server.

But the problem you opened this issue on is fixed, as rdpwarpper is running on your system. I suggest you close this off and do your research on any other issues you are having.

**Comment by send415** [comment] 2020-04-30 02:21
> Yes, it is meant to do that. Especially with 'Single Session per User" selected.
> 
> There is a group working on ways to let it create a new session instead of logging the user out at #1064 . They are not having much success.
> 
> There is also session shadowing, but it seems that requires a network that logs everyone in using a domain server.
> 
> But the problem you opened this issue on is fixed, as rdpwarpper is running on your system. I suggest you close this off and do your research on any other issues you are having.

ok fixed that now new problem , its not mirroring , seems like rdpwrapper created new user?  i can connect but its not the same screen , same pc . wth when i check there is only one user

**Comment by sebaxakerhtc** [comment] 2022-04-27 16:08
Duplicate of https://github.com/stascorp/rdpwrap/issues/983

**Closed as completed by sebaxakerhtc** 2022-04-27 16:08 UTC
