### ISSUE TITLE
10.0.19041.964 not supported

### ISSUE THREAD

**Issue by TukangM** [stascorp/rdpwrap#1964] opened 2022-08-21 15:18 UTC
![image](https://user-images.githubusercontent.com/91467886/185798165-4550db68-38d0-45fb-8767-0f6e205295ba.png)

windows 10 ghost spectre

**Comment by TukangM** [comment] 2022-08-21 15:27
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/9389439/termsrv.zip)

**Comment by sashaqwert** [comment] 2022-08-21 16:15
Duplicate of https://github.com/stascorp/rdpwrap/issues/1384

**Closed as not planned by sashaqwert** 2022-08-21 16:15 UTC
Labels: duplicate

**Comment by TukangM** [comment] 2022-08-24 11:18
> Duplicate of #1384

thanks
![image](https://user-images.githubusercontent.com/91467886/186406234-65a9dd0f-a435-4af2-a40a-c8a4d03beda2.png)
