### ISSUE TITLE
RDP Config does not open Correctly

### ISSUE THREAD

**Issue by mohday** [stascorp/rdpwrap#2166] opened 2023-04-08 09:11 UTC
the rdp Config and rdp Check opened but not visible, its goes to task bar but just a grey window showed when i hover mouse on its icon in task bar.
i terid blows:
Allow apps for rdp config and rdp check
turn off firewall
change port to 3390
change windows
but still problem not solved

**Comment by sashaqwert** [comment] 2023-04-08 10:23
Duplicate of https://github.com/stascorp/rdpwrap/issues/2103

**Closed as not planned by sashaqwert** 2023-04-08 10:23 UTC
Labels: duplicate
