### ISSUE TITLE
remote procedure call error with  Kb-5018410 update

### ISSUE THREAD

**Issue by joscu** [stascorp/rdpwrap#2016] opened 2022-10-13 07:10 UTC
Hi, first of all sorry about my bad english, if u need i can change my explanation

Normally, when windows 10 is updated i change the termsrv.dll, uninstall rdp wrapper, install and update and it works.

Now, with the Kb-5018410 windows version when i change the .dll i get this error: remote procedure call error with

I use the  11/06/2021 dll version. Is there a more current version

Thanks!!

**Comment by sashaqwert** [comment] 2022-10-13 09:35
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992

**Closed as not planned by sashaqwert** 2022-10-13 09:35 UTC
Labels: duplicate

**Comment by sashaqwert** [comment] 2022-10-13 09:37
`termsrv.dll` version is detected by previous duplicate https://github.com/stascorp/rdpwrap/issues/2015#issue-1406080478
