### ISSUE TITLE
Multiple connection to a session

### ISSUE THREAD

**Issue by alexblly** [stascorp/rdpwrap#1670] opened 2021-12-21 14:55 UTC
HI,

With RDP Wrapper on my Windows 10 I could connect with different devices on the same session simultaneously without interfering with the use of others
For the past few days, I can only connect once per session

I reinstalled RDP Wrapper with a new INI file. I also modified the termsrv.dll. I have also enabled “Limit number of connections” under Computer Configuration -> Administrative Templates -> Windows Components -> Remote Desktop Services -> Remote Desktop Session Host -> Connections section. Set value to 999999.

Does somebody have an idea ?

ver. 10.0.19041.1202
Windows: 19042.1266

**Comment by sashaqwert** [comment] 2021-12-21 17:55
> I also modified the termsrv.dll

RDP Wrapper ONLY supports original termsrv.dll.

**Comment by alexblly** [comment] 2021-12-22 07:30
it did not work before modifying it, this is the last modification I made, I saved the old termsrv.dll, I will put it back

**Comment by sashaqwert** [comment] 2021-12-22 07:35
> it did not work before modifying it

Please, attach your RDPConf screenshot and **original** termsrv.dll

**Comment by alexblly** [comment] 2021-12-22 08:07
This is the 2 files
[rdpwrap.ini.txt](https://github.com/stascorp/rdpwrap/files/7761024/rdpwrap.ini.txt)
[termsrv.dll.backup.txt](https://github.com/stascorp/rdpwrap/files/7761025/termsrv.dll.backup.txt)

**Comment by sashaqwert** [comment] 2021-12-22 08:45
> ver. 10.0.19041.1202

Your issue is https://github.com/stascorp/rdpwrap/issues/1509

> For the past few days, I can only connect once per session

Please, uncheck "Single session per user" and reboot.
If not work - replace INI from https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

**Comment by alexblly** [comment] 2021-12-22 08:56
> Your issue is #1509

I've already did it, but i've remade it for the issue

> Please, uncheck "Single session per user" and reboot. If not work - replace INI from https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

It's already uncheck too
I have reboot Windows and the problem is the same.

**Comment by sashaqwert** [comment] 2021-12-22 09:26
> I have reboot Windows and the problem is the same.

If both sessions under the user are remote, then there should be no problem.
If one of them is a console one, this is a common bug.

<details>
<summary>Offtopic</summary>

If you need a stable multisession operation:
1. Uninstall RDP Wrapper
2. Open CMD as Administrator
3. Enter magic command `slmgr.vbs /ipk CPWHC-NT2C7-VYW78-DHDB2-PG3GK`
4. Activate Windows
5. Reboot
6. Enjoy!

</details>

**Comment by alexblly** [comment] 2021-12-22 09:38
The connections are graphic remote desktops, either by Microsoft Remote Desktop on MacOS, xfreerdp for linux and the remote desktop for windows.
My windows is a Pro version without product key for the moment

**Comment by sashaqwert** [comment] 2021-12-22 09:52
> The connections are graphic remote desktops, either by Microsoft Remote Desktop on MacOS, xfreerdp for linux and the remote desktop for windows.

In that case, I recommend asking the offsets developer on Discord: https://discord.gg/N27yFftWP3

**Comment by cheops1551** [comment] 2021-12-22 23:41
I started using RDPWrap about 6 month ago.  Great stuff and it has been working well until the latest Win10 update.

About once a month, there's a Win update and then RDPWrap stops working. But after updating the latest INI, all is good again.

This time, even after updating to the latest rdpwrap.ini, and with RDPConf.exe reporting all in green, I still can't have multiple session allowed (one local, one remote).       It used to work before the latest Win10 update.

Is this a known problem?   My Windows is currently at 19043.1415.

Thanks!

**Comment by sebaxakerhtc** [comment] 2021-12-23 13:16
> Is this a known problem? My Windows is currently at 19043.1415.

There is no problems with this version. Tested now
Look [here](https://github.com/stascorp/rdpwrap/issues/1630#issuecomment-1000283183)

**Comment by cheops1551** [comment] 2021-12-24 19:55
> I started using RDPWrap about 6 month ago. Great stuff and it has been working well until the latest Win10 update.
> 
> About once a month, there's a Win update and then RDPWrap stops working. But after updating the latest INI, all is good again.
> 
> This time, even after updating to the latest rdpwrap.ini, and with RDPConf.exe reporting all in green, I still can't have multiple session allowed (one local, one remote). It used to work before the latest Win10 update.
> 
> Is this a known problem? My Windows is currently at 19043.1415.
> 
> Thanks!

Okay, I think I got it fixed.

Before, I was simply updating the INI.

This time, I completely removed the old installation, and used the latest v1.8.6 with the latest INI.  Now everything seems working well.

Many thanks!

**Comment by sebaxakerhtc** [comment] 2022-01-20 12:37
Duplicate of https://github.com/stascorp/rdpwrap/issues/1581

**Closed as completed by sebaxakerhtc** 2022-01-20 12:37 UTC

**Comment by louxinbo** [comment] 2022-09-10 02:42
> > I have reboot Windows and the problem is the same.
> 
> If both sessions under the user are remote, then there should be no problem. If one of them is a console one, this is a common bug.
> 
> Offtopic

How did you activate? Thanks.

**Comment by sashaqwert** [comment] 2022-09-10 05:18
@louxinbo 

> How did you activate? Thanks.

Offtopic. You can use any online KMS, KMS emulator or any other method. You can find links on Google.

**Comment by louxinbo** [comment] 2022-09-11 01:35
> @louxinbo
> 
> > How did you activate? Thanks.
> 
> Offtopic. You can use any online KMS, KMS emulator or any other method. You can find links on Google.

Off topic: actually I tried various activation methods and found that windows multi session  (server rdsh edition) does not support activation on non-Azure platforms. Do you have any workaround to bypass that? Thanks. Otherwise I will change it back and use rdp-wrap.

**Comment by sashaqwert** [comment] 2022-09-11 08:23
@louxinbo 

> Off topic: actually I tried various activation methods and found that windows multi session (server rdsh edition) does not support activation on non-Azure platforms. Do you have any workaround to bypass that?

I have a solution, but Stas'M asked me not to give said content and links to it.
Therefore, I can advise you to read the last (added today) post in the ServerRdsh topic on the "My Digital Life" forum.

**Comment by louxinbo** [comment] 2022-09-11 12:58
> @louxinbo
> 
> > Off topic: actually I tried various activation methods and found that windows multi session (server rdsh edition) does not support activation on non-Azure platforms. Do you have any workaround to bypass that?
> 
> I have a solution, but Stas'M asked me not to give said content and links to it. Therefore, I can advise you to read the last (added today) post in the ServerRdsh topic on the "My Digital Life" forum.

That worked! Thanks again, really appreciate it.
