### ISSUE TITLE
Add support for build 10.0.17763.168 in Windows 10 single language

### ISSUE THREAD

**Issue by texNICKru** [stascorp/rdpwrap#675] opened 2019-02-19 14:14 UTC
Need help)
rdpwrap.ini from previous topic don't help
![screenshot_1](https://user-images.githubusercontent.com/11171453/53021058-64de2000-3469-11e9-8de4-88f664dcd0a6.png)
![screenshot_2](https://user-images.githubusercontent.com/11171453/53021068-690a3d80-3469-11e9-9ec6-38eef3f1cc89.png)
[termsrv2019.zip](https://github.com/stascorp/rdpwrap/files/2880319/termsrv2019.zip)

**Comment by binarymaster** [comment] 2019-02-19 14:15
Duplicate of #606.

**Closed as completed by binarymaster** 2019-02-19 14:15 UTC
Labels: duplicate
