### ISSUE TITLE
version 10.0.19041.2075 not supported

### ISSUE THREAD

**Issue by JESUSGUTI1971** [stascorp/rdpwrap#2111] opened 2023-02-13 11:56 UTC
Hi
I have this problem. After update from 7 to Windows 10 it doesnt work.
![Anotación 2023-02-13 124837](https://user-images.githubusercontent.com/125270240/218451039-0cac8f16-4e98-4ae7-979b-b4d7b3186e34.png)
I look for this version but i didnt found nothing.
Thank you

**Comment by wangpengxing1996** [comment] 2023-02-13 16:20
you can have a try
https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

**Comment by sashaqwert** [comment] 2023-02-13 17:42
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992

**Closed as not planned by sashaqwert** 2023-02-13 17:42 UTC
Labels: duplicate

**Comment by sashaqwert** [comment] 2023-02-13 17:46
Please, use search before openning issue.

<details>


![Screenshot_2023-02-13-20-41-08-68_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/24974508/218533078-6afba53f-9fa4-4e38-a26e-90d464ef912b.jpg)

![Screenshot_2023-02-13-20-40-51-00_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/24974508/218533079-f49c2831-872d-4171-8207-d59bdf209f58.jpg)


</details>

**Comment by JESUSGUTI1971** [comment] 2023-02-13 19:55
Sorry, i think i don´t write properly the search. I sware I looked for it!
Thanks a lot
