### ISSUE TITLE
win11 26100.2152

### ISSUE THREAD

**Issue by Blakinas** [stascorp/rdpwrap#3341] opened 2024-11-12 21:54 UTC
![image](https://github.com/user-attachments/assets/848c8dff-21a2-42a2-8e82-fddd53287814)
[rdpwrap.zip](https://github.com/user-attachments/files/17723195/rdpwrap.zip)
[termsrv.zip](https://github.com/user-attachments/files/17723196/termsrv.zip)

please help make working.

**Comment by binarymaster** [comment] 2024-11-12 22:27
Duplicate of https://github.com/stascorp/rdpwrap/issues/3302.

**Closed as not planned by binarymaster** 2024-11-12 22:27 UTC
Labels: duplicate

**Comment by Blakinas** [comment] 2024-11-13 05:30
Dear Stanislav, but I put 1882. Or 2152 still not working. This is not
duplicate.

2024-11-13, tr 00:27, Stanislav Motylkov ***@***.***> rašė:

**Comment by binarymaster** [comment] 2024-11-13 12:24
One issue per termsrv version. Any user problems should be solved in the Telegram support chat.
