### ISSUE TITLE
Problem with version 10.0.19041.4239

### ISSUE THREAD

**Issue by FerdinandoPH** [stascorp/rdpwrap#2605] opened 2024-05-07 10:03 UTC
I'm trying to set up rdpwrap on my Windows 10.0.19041.4239 laptop. After installing it, I realized that this version of windows is "not supported" out of the box, and although I could still use rdp, I couldn't use the extra rdpwrap features.
![image](https://github.com/stascorp/rdpwrap/assets/29411787/13065883-feb1-491e-93dd-0447a443369a)

Looking into this repository's issues, i found https://github.com/stascorp/rdpwrap/issues/2529, and this comment https://github.com/stascorp/rdpwrap/issues/2529#issuecomment-2022141357 said that I needed to use RDPWrapOffsetFinder and copy the output to my ini file.. After a reboot, I got the fully supported message, but the rdp service was not running, and trying to start it from powershell resulted in an error. 
![image](https://github.com/stascorp/rdpwrap/assets/29411787/7f0eddb3-514d-478b-8ed2-c273652e58b7)
I deleted the ini entry I had added, and, after a reboot, rdp was back, but I got the "not supported" message again, so I'm back at the starting point.

What should I do?

**Comment by sashaqwert** [comment] 2024-05-08 09:56
Duplicate of https://github.com/stascorp/rdpwrap/issues/2529

**Closed as not planned by sashaqwert** 2024-05-08 09:56 UTC
Labels: duplicate

**Comment by FerdinandoPH** [comment] 2024-05-09 19:15
It's not just a duplicate. I opened this issue because the solution offered in #2529 is not working for me
