### ISSUE TITLE
2h22 win10 pro 2H22 

### ISSUE THREAD

**Issue by Rooney0317** [stascorp/rdpwrap#2402] opened 2023-11-14 07:16 UTC
I would like to ask about the current computer using the 2H22 version of Windows 10 pro but it has been unable to connect multiple people. I would like to ask what the problem is?
![image](https://github.com/stascorp/rdpwrap/assets/150777645/6d411c1a-0370-4221-8cef-9f124306662a)

![image](https://github.com/stascorp/rdpwrap/assets/150777645/11b79e84-cd9f-4a0b-9d45-29833d8c1b0a)

**Comment by sashaqwert** [comment] 2023-11-15 07:26
Duplicate of https://github.com/stascorp/rdpwrap/issues/2359

**Closed as not planned by sashaqwert** 2023-11-15 07:26 UTC
Labels: duplicate
