### ISSUE TITLE
win11 home 10.0.22621.2361 with 2023-10-22 version of rdpwrap.ini still can not work

### ISSUE THREAD

**Issue by ypingfeng** [stascorp/rdpwrap#2379] opened 2023-10-25 17:29 UTC
![10 0 22621 2361 fail](https://github.com/stascorp/rdpwrap/assets/5362330/20e9cce3-a2f7-4477-9569-f28a6ba21a93)
![image](https://github.com/stascorp/rdpwrap/assets/5362330/4138493e-27ef-42c5-adf7-e6fe40556ed1)
![image](https://github.com/stascorp/rdpwrap/assets/5362330/f5a0a3fb-84cc-4858-b027-244522c3a2cd)
![image](https://github.com/stascorp/rdpwrap/assets/5362330/32e34bd4-f8f5-48f7-94a5-554549b61df6)

**Comment by ypingfeng** [comment] 2023-10-25 19:32
I found a solution (but I don't know why)
1. Go to "Remote Desktop Services" -> "log in"
2. Log in using this account: "Network Service" (with win11 login password)
Then I can use rdpwrap

![image](https://github.com/stascorp/rdpwrap/assets/5362330/8c695728-b71a-46e0-97fc-a5f234f7d5a0)

**Comment by sashaqwert** [comment] 2023-10-27 10:43
One `termsrv.dll` version = ONE opened issue!

**Comment by sashaqwert** [comment] 2023-10-27 10:44
Duplicate of https://github.com/stascorp/rdpwrap/issues/2345

**Comment by sashaqwert** [comment] 2023-10-27 10:44
Try:
1. Download RDP Wrapper 1.6.2 and extract this to any directory.
2. Place `rdpwrap.ini` in the same directory.
3. Open CMD as administrator
4. Execute this commands
```
cd C:\path\to\directory\
rdpwinst -u -k
rdpwinst -i
```
5. Enjoy!

Original message: https://t.me/rdpwrap/49131

**Closed as not planned by sashaqwert** 2023-10-27 10:44 UTC
Labels: duplicate
