### ISSUE TITLE
no working in 22631.4249

### ISSUE THREAD

**Issue by RodolfoBigues** [stascorp/rdpwrap#3282] opened 2024-09-27 11:55 UTC
RDP Black no Work in 22631.4249 windows 11 pro has update at 03:00 and no support file rdp.ini file update need asap

**Comment by RodolfoBigues** [comment] 2024-09-27 11:58
retip the compilation version In Windows 11 Pro Version 23H2 (Compilación SO 22631.4249) not supported

**Comment by binarymaster** [comment] 2024-09-27 12:57
Duplicate of https://github.com/stascorp/rdpwrap/issues/3280.

**Closed as not planned by binarymaster** 2024-09-27 12:57 UTC
Labels: duplicate
