### ISSUE TITLE
RDPWrap cannot be installed on Windows 11 Home 23H2

### ISSUE THREAD

**Issue by Pittmann-XIE** [stascorp/rdpwrap#3255] opened 2024-08-18 19:57 UTC
Hello, I was trying to install RDPWrap on my Laptop. I made two attemps:
      1. I ran "install.bat" as administrator. But if failed. 
      2. I also tried to make windows defender scan the folder of RDPWrap and then ran "install.bat". But it faild again.

here's the error message:
a translation of it: "Zugriff verweigert" means "Access denied"
![image](https://github.com/user-attachments/assets/8fd42e2c-0cb9-467a-b6fd-0d51d8eafcf4)

here's the info of my system:
![image](https://github.com/user-attachments/assets/ec765d9d-e2ab-4d3c-8ac4-d2f62d9e1e25)

Thanks for your help!

**Comment by binarymaster** [comment] 2024-08-26 10:57
Duplicate of #1112.

**Closed as not planned by binarymaster** 2024-08-26 10:57 UTC
Labels: duplicate
