### ISSUE TITLE
 10.0.22631.2428 not supported ?

### ISSUE THREAD

**Issue by huake521** [stascorp/rdpwrap#2396] opened 2023-11-11 14:18 UTC

**Comment by huake521** [comment] 2023-11-11 14:23
![截图11月11_22 22 38](https://github.com/stascorp/rdpwrap/assets/55798180/d5bbba3e-b352-4820-b019-677c98b01343)

**Comment by huake521** [comment] 2023-11-11 14:27
[Uploading termsrv.dll.txt…]()

**Comment by sashaqwert** [comment] 2023-11-12 08:37
Duplicate of https://github.com/stascorp/rdpwrap/issues/2345

**Closed as not planned by sashaqwert** 2023-11-12 08:37 UTC
Labels: duplicate
