### ISSUE TITLE
Remotedekstopdienst / Terminalservice doesn't start after Update KB4056892

### ISSUE THREAD

**Issue by andhan83** [stascorp/rdpwrap#387] opened 2018-01-10 09:41 UTC
After the Update KB4056892 on Win10 1709, the Terminal Services can't be started!

![rdpwrp_status1](https://user-images.githubusercontent.com/35292637/34765473-855a4152-f5e9-11e7-81bf-92a308486f8f.jpg)

I have already reinstalled the newest Version 1.6.2 of RDPWrap

![rdpwrp_inst](https://user-images.githubusercontent.com/35292637/34765509-9bb22be0-f5e9-11e7-87e4-ed11ebf47d6a.jpg)
The Service can't start at Systemstart and I can't start it manualy. I get always an error message, Fault5: Access denied:

![rdpwrp_service](https://user-images.githubusercontent.com/35292637/34765445-770da418-f5e9-11e7-8e92-0d1d63fc31cb.jpg)

When i uninstall RDPWrp the Service can be started

![rdpwrp_status2](https://user-images.githubusercontent.com/35292637/34765581-cebbc9f6-f5e9-11e7-9ae1-4f8559a9dc61.jpg)

Do you have any ideas to solve this Problem?

**Comment by binarymaster** [comment] 2018-01-10 11:27
Fehler 5 == Error Code 5 == ACCESS_DENIED

This is either antivirus problem (#277) or incorrect ACL rights on file (#215).

Looks like totally a duplicate of #215.

**Closed by binarymaster** 2018-01-10 11:27 UTC
