### ISSUE TITLE
does rdpwarpper.ini work on 19043.1288

### ISSUE THREAD

**Issue by nattlip** [stascorp/rdpwrap#1587] opened 2021-11-05 16:33 UTC
does this version of rdpwrapper. ini on https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini works for 19043.1288

**Comment by sashaqwert** [comment] 2021-11-05 18:44
Please, attach your RDPConf screenshot.

**Comment by nattlip** [comment] 2021-11-06 11:52
but before i update to 19043.1288 i want to know if rdpwraps works,  i have now wonver 12043.1237 oktober update windows 1288


![rdpwrap 1043 1237](https://user-images.githubusercontent.com/7040452/140608599-812778cb-b919-413d-bfd4-5550064d9831.jpg)

**Comment by sashaqwert** [comment] 2021-11-07 05:50
Thanks!

Duplicate of https://github.com/stascorp/rdpwrap/issues/1509

**Comment by sashaqwert** [comment] 2021-11-07 07:17
@nattlip This will works.
![изображение](https://user-images.githubusercontent.com/24974508/140636048-42a74b8a-ed90-4163-9907-ce4bceb78625.png)

duplicate of https://github.com/stascorp/rdpwrap/issues/1542 (?) or https://github.com/stascorp/rdpwrap/issues/1509

**Comment by sebaxakerhtc** [comment] 2021-11-10 09:09
Acceptable to https://github.com/stascorp/rdpwrap/issues/1509

**Closed as completed by sebaxakerhtc** 2021-11-10 09:09 UTC
