### ISSUE TITLE
windows 11 24h2 26100.2314 not support 

### ISSUE THREAD

**Issue by killaragorn** [stascorp/rdpwrap#3350] opened 2024-11-19 07:21 UTC
![image](https://github.com/user-attachments/assets/87233e19-c5d2-4e21-9210-823e4aa5fed6)
[termsrv.zip](https://github.com/user-attachments/files/17811184/termsrv.zip)

**Comment by binarymaster** [comment] 2024-11-19 14:45
Duplicate of https://github.com/stascorp/rdpwrap/issues/3285.

**Closed as not planned by binarymaster** 2024-11-19 14:45 UTC
Labels: duplicate
