### ISSUE TITLE
Not working on ver. 10.0.19041.1348

### ISSUE THREAD

**Issue by FMBatista2022** [stascorp/rdpwrap#1793] opened 2022-03-29 07:33 UTC
![Captura de ecrã 2022-03-29 083254](https://user-images.githubusercontent.com/102580863/160558074-f6442474-1552-479a-8811-eab1f992a89f.jpg)

**Comment by sebaxakerhtc** [comment] 2022-03-29 08:13
Duplicate of https://github.com/stascorp/rdpwrap/issues/1595

**Closed as completed by sebaxakerhtc** 2022-03-29 08:13 UTC
