### ISSUE TITLE
10.0.19042 not support help

### ISSUE THREAD

**Issue by machusenpai** [stascorp/rdpwrap#1722] opened 2022-02-15 10:33 UTC
Alright I can't get mine supported. 
![NVIDIA_Share_YNo8pVEq5T](https://user-images.githubusercontent.com/99726975/154043878-1e2cd181-fe49-46ae-8373-54a0e870b2a0.png)

Here is my termsrv
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/8068292/termsrv.zip)

**Comment by sebaxakerhtc** [comment] 2022-02-15 10:43
Duplicate of https://github.com/stascorp/rdpwrap/issues/1630

**Closed as completed by sebaxakerhtc** 2022-02-15 10:43 UTC
