### ISSUE TITLE
Not supported on windows insider 17133.1

### ISSUE THREAD

**Issue by StoneNimRod** [stascorp/rdpwrap#460] opened 2018-05-01 16:30 UTC
Hello. This program doesn't work on my windows 10 home insider 17133.1. It's written that: Not listening, [not supported]. 
I don't know what to do (I'm new here).
Thanks

**Comment by binarymaster** [comment] 2018-05-01 18:28
Duplicate of #442.

**Closed by binarymaster** 2018-05-01 18:28 UTC

**Comment by StoneNimRod** [comment] 2018-05-01 18:32
Ok thanks. I had problems with permissions, but now I've solved them.
