### ISSUE TITLE
10.0.19041.3636 not supported windows 10 pro 22H2

### ISSUE THREAD

**Issue by abubakarnawaz670** [stascorp/rdpwrap#2501] opened 2024-02-26 19:30 UTC
![yttt](https://github.com/stascorp/rdpwrap/assets/161370559/2b800942-7134-499f-912b-2f21bc3228e1)
please give me solution

**Comment by siaunibit** [comment] 2024-02-26 20:35
The same problem!

**Comment by qwertynull** [comment] 2024-02-28 05:43
Up. I also have same problem.

**Comment by sashaqwert** [comment] 2024-02-28 07:34
Duplicate of https://github.com/stascorp/rdpwrap/issues/2381

**Closed as not planned by sashaqwert** 2024-02-28 07:34 UTC
Labels: duplicate
