### ISSUE TITLE
Access denied 

### ISSUE THREAD

**Issue by BROSKIEMANDS** [stascorp/rdpwrap#2073] opened 2022-12-22 22:45 UTC
![image](https://user-images.githubusercontent.com/121140503/208796105-725c8e5d-c875-4396-9aad-f2bfd08502f0.png)

![image](https://user-images.githubusercontent.com/121140503/209237905-6e572c50-c72e-4177-a327-890dce911ff1.png)

![image](https://user-images.githubusercontent.com/121140503/209238111-21c8ef35-5bf2-4552-856e-71a2312873be.png)

**Comment by binarymaster** [comment] 2022-12-22 23:22
Duplicate of #2070.

**Closed as not planned by binarymaster** 2022-12-22 23:22 UTC

**Comment by BROSKIEMANDS** [comment] 2022-12-22 23:40
@binarymaster bro what
my other one got closed for not enough information so i made a new one with more info
