### ISSUE TITLE
10.0.2261.3447 showing not supported.

### ISSUE THREAD

**Issue by WhatWhyIT** [stascorp/rdpwrap#2574] opened 2024-04-16 05:30 UTC
Reporting Not Supported
![not supported](https://github.com/stascorp/rdpwrap/assets/76672166/38a766db-6622-4cfe-80de-4c92f592014a)

**Comment by WhatWhyIT** [comment] 2024-04-16 05:33
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/14987232/termsrv.zip)
Attaching termsrv

**Comment by loyejaotdiqr47123** [comment] 2024-04-16 13:02
Duplicate of #2528

**Comment by loyejaotdiqr47123** [comment] 2024-04-19 13:44
Duplicate of #2549

**Comment by DF87SE** [comment] 2024-04-24 12:46
> Relatórios não suportados ![não suportado](https://private-user-images.githubusercontent.com/76672166/322712355-38a766db-6622-4cfe-80de-4c92f592014a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NjMwNzEsIm5iZiI6MTcxMzk2Mjc3MSwicGF0aCI6Ii83NjY3MjE2Ni8zMjI3MTIzNTUtMzhhNzY2ZGItNjYyMi00Y2ZlLTgwZGUtNGM5MmY1OTIwMTRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDEyNDYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkNjQ3OTdlNzRiZDQ2ZTFkY2M5Yzk4ZTRjZDAzMTI0Yzk5NzVhZDMyNmViNDExOGZhZjhhNzZjZmFiN2Y4ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JmPAvFS9q6n3AngIa1KeT4GQOY2gKf9qBbXW3LcH8hI)


O MEU NÃO PERMITI MULTIPLOS USUÁRIOS SIMULTANEAMENTE, PODES ME AJUDAR? UM DERRUBA O OUTRO

**Comment by sashaqwert** [comment] 2024-04-29 14:44
Duplicate of https://github.com/stascorp/rdpwrap/issues/2549

**Closed as not planned by sashaqwert** 2024-04-29 14:44 UTC
Labels: duplicate
