### ISSUE TITLE
10.0.18362.267 rdpwrap config

### ISSUE THREAD

**Issue by cosoc** [stascorp/rdpwrap#1459] opened 2021-07-05 10:03 UTC
10.0.18362.267 rdpwrap

**Comment by cosoc** [comment] 2021-07-05 10:11
链接: https://pan.baidu.com/s/1WjAJRa8DLjklF2x-SVS5Dg 提取码: uw39

**Comment by cosoc** [comment] 2021-07-05 10:11
有意义的博客:https://blog.csdn.net/u010804317/article/details/104011926

**Comment by mcok** [comment] 2021-07-09 17:12
感谢大哥的分享，问题解决了

**Comment by yuzheng310** [comment] 2021-12-04 12:04
thanks

**Comment by sebaxakerhtc** [comment] 2022-06-20 13:03
Duplicate of https://github.com/stascorp/rdpwrap/issues/871

**Closed as completed by sebaxakerhtc** 2022-06-20 13:03 UTC
