### ISSUE TITLE
10.0.19043.1766 Not supported

### ISSUE THREAD

**Issue by xnicox123** [stascorp/rdpwrap#1921] opened 2022-07-06 21:20 UTC
10.0.19043.1766 Not supported

**Comment by xnicox123** [comment] 2022-07-06 21:22
Microsoft Windows [Versión 10.0.19043.1766]
(c) Microsoft Corporation. Todos los derechos reservados.

**Comment by sashaqwert** [comment] 2022-07-07 05:23
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881

**Comment by sashaqwert** [comment] 2022-07-07 05:24
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881

**Comment by sashaqwert** [comment] 2022-07-07 05:29
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881

**Closed as not planned by sashaqwert** 2022-07-07 05:30 UTC
