### ISSUE TITLE
18362.295 not supported ---"fully supported" but cannot connect more than one

### ISSUE THREAD

**Issue by ichowck** [stascorp/rdpwrap#878] opened 2019-09-06 00:55 UTC
I use this .ini file:
https://raw.githubusercontent.com/saurav-biswas/rdpwrap-1/patch-1/res/rdpwrap.ini

<img width="1035" alt="截圖 2019-09-02 下午6 42 58" src="https://user-images.githubusercontent.com/51054809/64393411-ce2f2480-d083-11e9-855e-ab86c20239cd.png">
<img width="965" alt="64109412-07307600-cdb2-11e9-9d36-480517a1b940" src="https://user-images.githubusercontent.com/51054809/64393417-dab37d00-d083-11e9-896a-35ec1b1d0626.png">

**Comment by Benngy87** [comment] 2019-09-06 07:58
In the **Session Shadowing Mode** Section, select "**Full access without permission**"
That should fix it for you

**Comment by s0nic9** [comment] 2019-09-06 08:58
please use updater from https://github.com/stascorp/rdpwrap/pull/859

**Comment by ichowck** [comment] 2019-09-06 17:21
> please use updater from #859
i do it , cannot fix it.

**Comment by ichowck** [comment] 2019-09-06 20:22
<img width="424" alt="截圖 2019-09-07 上午1 21 36" src="https://user-images.githubusercontent.com/51054809/64447436-f7949280-d10d-11e9-95ac-7840fb8bca82.png">
<img width="1203" alt="截圖 2019-09-07 上午4 20 08" src="https://user-images.githubusercontent.com/51054809/64458033-d5f3d500-d126-11e9-8853-a89418c56071.png">

**Comment by s0nic9** [comment] 2019-09-06 20:30
x86 or x64 ?
Home or Pro ?

**Comment by ichowck** [comment] 2019-09-06 20:59
i use this file: asmtron-rdpwrap.ini-02.09.2019.zip

**Comment by ichowck** [comment] 2019-09-06 21:02
<img width="534" alt="截圖 2019-09-07 上午5 00 41" src="https://user-images.githubusercontent.com/51054809/64460300-a1831780-d12c-11e9-9e6f-ea658d2e838d.png">
<img width="616" alt="截圖 2019-09-07 上午5 01 42" src="https://user-images.githubusercontent.com/51054809/64460331-b65fab00-d12c-11e9-9050-97345271c7f9.png">

**Comment by ichowck** [comment] 2019-09-06 21:05
x64  Pro

**Comment by ichowck** [comment] 2019-09-06 21:05
> x86 or x64 ?
> Home or Pro ?

x64 Pro

**Comment by s0nic9** [comment] 2019-09-06 21:13
have you copied file directly or copy/paste content ?

**Comment by ichowck** [comment] 2019-09-06 21:57
> have you copied file directly or copy/paste content ?

yes

**Comment by s0nic9** [comment] 2019-09-06 22:05
you don't read carefully my question

**Comment by ichowck** [comment] 2019-09-06 22:19
> you don't read carefully my question

"copy/paste"
fr
/asmtron-rdpwrap.ini-02.09.2019/asmtron-rdpwrap.ini-02.09.2019/rdpwrap.ini
to 
C:\Program Files\RDP Wrapper/rdpwrap.ini

**Comment by min9139** [comment] 2019-09-07 03:50
ichowck 
how about my solution

uninstall all kinds of rdp wrapper 

1. reinstall
2. use autoupdate.bat 
https://github.com/stascorp/rdpwrap/issues/860 

( be careful #860 )
zip file must be inside c:\programfiles\rdpwrapper
and Decompression that folder
start autoupdate.bat -with administrator

all done!

**Comment by ichowck** [comment] 2019-09-09 03:36
> ichowck
> how about my solution
> 
> uninstall all kinds of rdp wrapper
> 
> 1. reinstall
> 2. use autoupdate.bat
>    #860
> 
> ( be careful #860 )
> zip file must be inside c:\programfiles\rdpwrapper
> and Decompression that folder
> start autoupdate.bat -with administrator
> 
> all done!

<img width="412" alt="截圖 2019-09-09 上午11 35 06" src="https://user-images.githubusercontent.com/51054809/64501885-e7d7a280-d2f5-11e9-85fc-1183b589cd06.png">
i do it , cannot fix it.

**Comment by mightytyphoon** [comment] 2019-09-11 13:32
Hi !
I am having the same problem with windows 
[version 10.0.18362.356] on host
[version 10.0.18362.295] on client

I am digging into it

**Comment by Mob002** [comment] 2019-09-12 12:51
After installation all files from RDPWrap-v1.6.2.zip you need to Copy/Paste to 
![зображення](https://user-images.githubusercontent.com/55241544/64785419-ff708e80-d574-11e9-99b1-8e391a6a299b.png)

And dont forget to run autoapdate

**Comment by carlos107fer** [comment] 2019-09-28 21:42
somebody found the solution ? with the ultimate version w10 pro ?

**Comment by mdnext** [comment] 2019-09-30 18:42
> ichowck
> how about my solution
> 
> uninstall all kinds of rdp wrapper
> 
> 1. reinstall
> 2. use autoupdate.bat
>    #860
> 
> ( be careful #860 )
> zip file must be inside c:\programfiles\rdpwrapper
> and Decompression that folder
> start autoupdate.bat -with administrator
> 
> all done!

Hi min9139,

I'm in a situation where I am unable to use the autoupdate.bat. Do you, or anyone else know if there is a procedure that list all the necessary steps to manually update rdpwrapper?

**Comment by sebaxakerhtc** [comment] 2022-06-20 10:12
Duplicate of https://github.com/stascorp/rdpwrap/issues/871

**Closed as completed by sebaxakerhtc** 2022-06-20 10:12 UTC
