### ISSUE TITLE
Install fails with "A program required for this install to complete could not be run".

### ISSUE THREAD

**Issue by ejohb** [stascorp/rdpwrap#688] opened 2019-03-03 11:24 UTC
![rdp_wrap_err](https://user-images.githubusercontent.com/30390944/53694439-d93c8b80-3da6-11e9-82e6-9975eb1fda1c.jpg)

**Comment by binarymaster** [comment] 2019-03-03 12:04
Duplicate of #377.

**Closed as completed by binarymaster** 2019-03-03 12:04 UTC
Labels: duplicate
