### ISSUE TITLE
Build 19043 Not supported

### ISSUE THREAD

**Issue by DillonJ** [stascorp/rdpwrap#2133] opened 2023-03-02 16:44 UTC
Hi folks - thanks for this great project!

Looks like build 19043 is not supported

**Comment by sashaqwert** [comment] 2023-03-02 17:32
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by DillonJ** [comment] 2023-03-02 18:12
Hi @sashaqwert 

Here you go:

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/10874340/termsrv.zip)

![image](https://user-images.githubusercontent.com/7080191/222515788-dacb0ba8-d5f5-41e8-8452-32f41cc41884.png)

**Comment by sashaqwert** [comment] 2023-03-02 18:45
Your `termsrv.dll` version is `10.0.19041.2075`.

One `termsrv.dll` version = one opened issue. This issue will be closed as duplicate...

**Comment by sashaqwert** [comment] 2023-03-02 18:46
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992

**Closed as not planned by sashaqwert** 2023-03-02 18:46 UTC
Labels: duplicate

**Comment by sashaqwert** [comment] 2023-03-02 18:48
You need replace the `rdpwrap.ini` file.

**Comment by DillonJ** [comment] 2023-03-02 20:50
Thanks @sashaqwert 

I have a couple of questions - I copied over the latest rdpwrap.ini file - there was none in the zip archive. I presume it should go in the same folder as the other files in the release package?

When I run RDPCheck.exe it seems to work

It seems like I'm missing something

 - . When I launch the remote desktop client on my local machine it asks for login details for the remote machine and when it connects, I see the windows login screen where I have to login again. I can't change the username, I can only choose from a list of local users (i.e. I can't log in with my microsoft account)
 - It still tells me there is another user logged in and they will be disconnected. I'm trying to log in to the remote machine as two different users from the same local machine, should this work? It doesn't let me log in as both simultaneously - it still boots the other user

**Comment by DillonJ** [comment] 2023-03-02 21:20
Maybe I have misunderstood how it works - can I only have multipe concurrent sessions by logging in once conventionally and then within that session, connect multiple times using the loopback ip address?

Is it possible for multple users to log in from different IPs concurrently? This doesn't appear to be working for me

**Comment by DillonJ** [comment] 2023-03-02 21:38
Note sure if I'm doing somethng wrong but it still says unsupported, even after updating

![image](https://user-images.githubusercontent.com/7080191/222561527-08677be1-8465-40de-afe6-a939bbaac786.png)

**Comment by sashaqwert** [comment] 2023-03-03 06:24
> Note sure if I'm doing somethng wrong but it still says unsupported, even after updating
> 
> ![image](https://user-images.githubusercontent.com/7080191/222561527-08677be1-8465-40de-afe6-a939bbaac786.png)

This is normal, because this project is not supported now by Stas'M. Use this tutorial http://www.youtube.com/watch?v=W9BpbEt1yJw

**Comment by sashaqwert** [comment] 2023-03-03 07:00
# You can find latest `rdpwrap.ini` [here](https://github.com/sebaxakerhtc/rdpwrap.ini)

**Comment by sashaqwert** [comment] 2023-03-03 07:41
> I can't log in with my microsoft account

You need convert your Microsoft account to a local account. After login to this local account you can convert it back to Microsoft account. This is a known bug.

> It still tells me there is another user logged in and they will be disconnected

You need `Fully supported` in RDPConf to use multi-session with RDP Wrapper.
Exclusion: Windows 10/11 Enterprise multi-session, Enterprise for Virtual desktops (ServerRdsh)

**Comment by DillonJ** [comment] 2023-03-03 07:57
> # You can find latest `rdpwrap.ini` [here](https://github.com/sebaxakerhtc/rdpwrap.ini)

Thank you so much - this is what I was missing! It's working perfectly now - than you so much!!!!
