### ISSUE TITLE
Access Denied Error: Windows 10  19045.2965

### ISSUE THREAD

**Issue by zenusop** [stascorp/rdpwrap#2227] opened 2023-05-29 11:47 UTC
Hello,

I've been recently trying to get RDP-Wrapper to work, but I have encountered a issue. When I get to the login page and I enter the password to the computer it just says "Access Denied" and I can do anything.

I will provide screenshots of the RDPconf and what pops up when I try to enter the password. I'm hoping someone can help me with this issue.
![pic1](https://github.com/stascorp/rdpwrap/assets/75637878/1a93c238-56c6-4d51-a3f2-fe139e3da510)
![pic2](https://github.com/stascorp/rdpwrap/assets/75637878/f9e7c241-c48a-4696-a108-58e189535094)
![pic3](https://github.com/stascorp/rdpwrap/assets/75637878/577ab50d-08d0-476f-a0b7-bd0cd8f9a0a6)

**Comment by sashaqwert** [comment] 2023-05-29 18:24
You need add your RDP users to Administrators or «Remote Desktop users» group.

**Comment by sashaqwert** [comment] 2023-05-29 18:25
One termsrv.dll version = ONE opened issue.

**Comment by sashaqwert** [comment] 2023-05-29 18:26
Duplicate of https://github.com/stascorp/rdpwrap/issues/2180

**Closed as not planned by sashaqwert** 2023-05-29 18:26 UTC
Labels: duplicate
