### ISSUE TITLE
10.0.22621.3593 - the number of connections to this computer is limited

### ISSUE THREAD

**Issue by christianarrer** [stascorp/rdpwrap#2619] opened 2024-05-22 23:33 UTC
i have downloaded RDPWrap-v1.6.2.zip extracted it, stopped termservice, launched the install.bat copied the correct ini file for 10.0.22621.3593.

made the following settings in gepedit.msc

Computer Configuration -> Administrative Templates -> Windows Components -> Remote Desktop Services -> Remote Desktop Session Host -> Connections:

Limit Number of connections: Enable and RD Maximum Connections allowed 999999

Computer Configuration -> Administrative Templates -> Windows Components -> Remote Desktop Services -> Remote Desktop Session Host -> Connections:

Restrict Remote Desktop Services users to a single Remote Desktop Services session: Disabled

rebooted

RDPConf.exe shows fully supported

and still i get "the number of connections to this computer is limited"

i am on windows 11 enterprise 10.0.22621.3593

thanks

**Comment by AllenTan7389** [comment] 2024-05-23 06:19
> 10.0.22621.3593

can u provide termsrv.dll ?

**Comment by christianarrer** [comment] 2024-05-23 07:09
Hey there,

https://1drv.ms/u/s!ApyxOPTqXK-QhNpbSBkdry41Rf73AA?e=WaR7xJ

No idea how to share it here ...

**Comment by AllenTan7389** [comment] 2024-05-23 07:11
> Hey there,
> 
> https://1drv.ms/u/s!ApyxOPTqXK-QhNpbSBkdry41Rf73AA?e=WaR7xJ
> 
> No idea how to share it here ...

can u ws me i anydesk help u solve it 
wa.me/60103322996

**Comment by christianarrer** [comment] 2024-05-23 07:38
> > Hey there,
> > https://1drv.ms/u/s!ApyxOPTqXK-QhNpbSBkdry41Rf73AA?e=WaR7xJ
> > No idea how to share it here ...
> 
> can u ws me i anydesk help u solve it wa.me/60103322996

sorry i had to report this incident on github. sorry dude maybe i did you wrong, my fault.

**Comment by loyejaotdiqr47123** [comment] 2024-05-23 13:03
Duplicate of #2611

**Closed as not planned** 2024-06-03 19:56 UTC
Labels: duplicate
