### ISSUE TITLE
Windows 10 Pro 10.0.19041.84 Not supporter

### ISSUE THREAD

**Issue by Ghost-729** [stascorp/rdpwrap#2247] opened 2023-06-15 13:20 UTC
Hello, 

My OS is not supported, can you help-me to solved the problem ?

![image](https://github.com/stascorp/rdpwrap/assets/136717315/cbcc311c-be06-4fc8-98ca-ee9eda50d299)

Regards

**Comment by sashaqwert** [comment] 2023-06-15 14:36
Duplicate of https://github.com/stascorp/rdpwrap/issues/1004

**Closed as not planned by sashaqwert** 2023-06-15 14:36 UTC
Labels: duplicate
