### ISSUE TITLE
Windows 10 22H2 10.0.19045.2788 not supported

### ISSUE THREAD

**Issue by sunspiritz** [stascorp/rdpwrap#2168] opened 2023-04-12 19:34 UTC
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/11215153/termsrv.zip)
![19045 2788_not_Supported](https://user-images.githubusercontent.com/81503208/231565446-1dde07cb-1f04-4a55-bb5c-19fdac933474.png)

**Comment by dbart126** [comment] 2023-04-12 23:03
Is it possible to just replace the term service DLL in build 19045.2846?  Doesn't seem to work in V 22H2

**Comment by sashaqwert** [comment] 2023-04-13 08:56
Duplicate of https://github.com/stascorp/rdpwrap/issues/2125

**Closed as not planned by sashaqwert** 2023-04-13 08:56 UTC
Labels: duplicate
