### ISSUE TITLE
win11 22621.3155 notworking

### ISSUE THREAD

**Issue by boson0725** [stascorp/rdpwrap#2485] opened 2024-02-14 07:05 UTC
![圖片](https://github.com/stascorp/rdpwrap/assets/97293165/4c1a4e2b-69a6-4cb0-b7f3-c2551fa55a00)

**Comment by sashaqwert** [comment] 2024-02-14 07:26
Please, attach your `termsrv.dll`

**Comment by boson0725** [comment] 2024-02-14 07:30
[termsrvback.zip](https://github.com/stascorp/rdpwrap/files/14276499/termsrvback.zip)

**Comment by sashaqwert** [comment] 2024-02-14 12:31
Thanks! Solution in https://github.com/stascorp/rdpwrap/issues/2469

Also your Wrapper version is strange --> invalid.

**Comment by sashaqwert** [comment] 2024-02-14 12:31
Duplicate of https://github.com/stascorp/rdpwrap/issues/2469

**Closed as not planned by sashaqwert** 2024-02-14 12:31 UTC
Labels: duplicate, invalid
