### ISSUE TITLE
Version 10.0.17763.1697 Windows 10 LTSC  x 32

### ISSUE THREAD

**Issue by tetas26** [stascorp/rdpwrap#1286] opened 2021-01-15 08:25 UTC
Can anyone with a x32 version of above help

**Comment by asmtron** [comment] 2021-01-18 21:20
please upload the 32Bit Version of termsrv.dll 10.0.17763.1697 (x86) ....

**Comment by tetas26** [comment] 2021-01-19 07:38
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/5834325/termsrv.zip)
Thank you.

**Comment by asmtron** [comment] 2021-01-24 09:52
add 10.0.17763.1697 (x86) to [rdpwrap.ini](https://github.com/asmtron/rdpwrap/blob/master/res/rdpwrap.ini)

[Download & Install](https://github.com/asmtron/rdpwrap/blob/master/binary-download.md)

**Comment by tetas26** [comment] 2021-01-24 17:06
Thank you.

**Comment by HamletShaoE** [comment] 2021-01-28 07:08
Hi, I installed the RDPwrapper, I also changed the ini file. the RDPconf.exe says all is right. But still can not have multiple people to login. I also tried to restart the computer, but RDPconf.exe. is fine but still no multiple access is allowed. Should I configure something more?
![图片](https://user-images.githubusercontent.com/4826601/106102579-9219c980-617a-11eb-88c9-b9339e3cb8e6.png)


> 
> 
> add 10.0.17763.1697 (x86) to [rdpwrap.ini](https://github.com/asmtron/rdpwrap/blob/master/res/rdpwrap.ini)
> 
> [Download & Install](https://github.com/asmtron/rdpwrap/blob/master/binary-download.md)

**Comment by sebaxakerhtc** [comment] 2022-06-20 12:41
Duplicate of https://github.com/stascorp/rdpwrap/issues/1276

**Closed as completed by sebaxakerhtc** 2022-06-20 12:41 UTC
