### ISSUE TITLE
10.0.19045.2251 (Win10 22H2 2022 Update)

### ISSUE THREAD

**Issue by btccoreblock** [stascorp/rdpwrap#2060] opened 2022-12-03 18:42 UTC
10.0.19045.2251 (Win10 22H2 2022 Update)
![Screenshot_1](https://user-images.githubusercontent.com/107360104/205456718-a8f8043d-f454-42b9-9496-df29210eae50.jpg)

**Comment by btccoreblock** [comment] 2022-12-03 19:04
https://github.com/Octanium91/rdpwupDownloads/blob/master/rdpwup_8.zip
![1f44d](https://user-images.githubusercontent.com/107360104/205457668-37e46d43-7f65-4afc-ab45-8cdbf7a907d0.png)
![Screenshot_2](https://user-images.githubusercontent.com/107360104/205457584-d16d9438-3dbd-412a-9088-8605d051eff8.jpg)

**Comment by sashaqwert** [comment] 2022-12-04 06:47
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992

**Closed as not planned by sashaqwert** 2022-12-04 06:47 UTC
Labels: duplicate
