### ISSUE TITLE
Windows 10 10.0.19041.330

### ISSUE THREAD

**Issue by princepsycho** [stascorp/rdpwrap#1123] opened 2020-07-18 13:31 UTC
Need rdpwrap.ini offset for this version of windows please,

**Comment by travismailsa** [comment] 2020-07-20 08:25
See if that INI helps you
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/4946424/rdpwrap.zip)

**Comment by princepsycho** [comment] 2020-07-20 16:46
No, still looking for this guys, can someone reverse enginer and get right offset for this version of windows ?????????????

**Comment by sebaxakerhtc** [comment] 2022-06-20 11:14
Duplicate of https://github.com/stascorp/rdpwrap/issues/1004

**Closed as completed by sebaxakerhtc** 2022-06-20 11:14 UTC
