### ISSUE TITLE
termserv.dll version 10.0.14393.0 - no second session

### ISSUE THREAD

**Issue by frankenzipfel** [stascorp/rdpwrap#170] opened 2016-10-07 13:28 UTC
no connection with second user possible.

termserv.dll version 10.0.14393.0

what is wrong in my system?

I uninstalled old version and installed new version with the fix (9 days before) again after a restart...

**Comment by binarymaster** [comment] 2016-10-07 13:33
Prodive diagnostics screenshot

**Comment by frankenzipfel** [comment] 2016-10-07 13:37
what for screenshot do you need?

**Comment by binarymaster** [comment] 2016-10-07 13:37
Screenshot with diagnostics. See `RDPConf` program

**Comment by frankenzipfel** [comment] 2016-10-07 13:37
latest windows update:
Update für Windows 10 Version 1607 für x64-Systeme (KB3176936)

**Comment by frankenzipfel** [comment] 2016-10-07 13:38
![2016-10-07 15_38_18-mremoteng - confcons xml - 10 5 76 15 - w10testmaschine-neu](https://cloud.githubusercontent.com/assets/20027810/19191770/1d062ac6-8ca4-11e6-8def-46a788922bd8.png)

**Comment by binarymaster** [comment] 2016-10-07 13:39
According to the screenshot, your RDP Wrapper installation is not latest / updated. You need to download latest release, uninstall and reinstall again. Because build `10.0.14393.0` is already added to support.

**Comment by frankenzipfel** [comment] 2016-10-07 13:40
where can i find a new version of "RDPWInst.exe" ?

**Comment by binarymaster** [comment] 2016-10-07 13:41
![image](https://cloud.githubusercontent.com/assets/578406/19191867/d8e995a4-8cac-11e6-931b-49a612a3e956.png)

Read README.md first

**Comment by binarymaster** [comment] 2016-10-07 13:43
Closed as a duplicate of #144.

**Closed by binarymaster** 2016-10-07 13:43 UTC
Labels: duplicate
