### ISSUE TITLE
Win 11h2 KB5046633  22631.4460 10.22621.4391 not supported

### ISSUE THREAD

**Issue by mamotttt** [stascorp/rdpwrap#3346] opened 2024-11-15 00:46 UTC
![Screenshot_4](https://github.com/user-attachments/assets/41677178-76a0-4d17-ba36-a1585bc5002f)

**Comment by robert0825** [comment] 2024-11-15 05:56
any

**Comment by binarymaster** [comment] 2024-11-15 13:30
Duplicate of https://github.com/stascorp/rdpwrap/issues/3316.

**Closed as not planned by binarymaster** 2024-11-15 13:30 UTC
Labels: duplicate
