### ISSUE TITLE
Does not work on TS Version 10.0.14393.2457

### ISSUE THREAD

**Issue by Basecatcherz** [stascorp/rdpwrap#569] opened 2018-09-24 07:20 UTC
Not supported since 2018-08 patch for Windows Server 2016 1607

**Comment by aecgithub** [comment] 2018-09-24 09:19
Uninstall rdpwrapper.

**Comment by binarymaster** [comment] 2018-09-24 10:46
Duplicate of #542.

**Closed by binarymaster** 2018-09-24 10:46 UTC
