### ISSUE TITLE
10.0.20348.2159

### ISSUE THREAD

**Issue by R3N0NS** [stascorp/rdpwrap#2461] opened 2023-12-30 10:39 UTC
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/13797784/termsrv.zip)

**Comment by sashaqwert** [comment] 2023-12-31 06:28
> [termsrv.zip](https://github.com/stascorp/rdpwrap/files/13797784/termsrv.zip)

<details>
<summary>Screenshot</summary>

![изображение](https://github.com/stascorp/rdpwrap/assets/24974508/76ffff79-b05f-4ec1-b701-a9cbf04303c4)

</details>

Your `termsrv.dll` version is `10.0.20348.2110`

**Comment by sashaqwert** [comment] 2023-12-31 06:29
Duplicate of https://github.com/stascorp/rdpwrap/issues/2405

**Closed as not planned by sashaqwert** 2023-12-31 06:29 UTC
Labels: duplicate
