### ISSUE TITLE
RDPConf is right. But turn off after 1 second of loading

### ISSUE THREAD

**Issue by blanket77** [stascorp/rdpwrap#2566] opened 2024-04-13 12:04 UTC
![Capture](https://github.com/stascorp/rdpwrap/assets/70279365/762350a3-172d-46a0-87f2-346a40b0e356)
Everything is normal in the settings. But I can't connect. It suddenly turns off after 1 second of loading.

**Comment by sashaqwert** [comment] 2024-04-14 08:32
Try:
1. Download RDP Wrapper 1.6.2 and extract this to any directory.
2. Place `rdpwrap.ini` in the same directory.
3. Open CMD as administrator
4. Execute this commands
```
cd C:\path\to\directory\
rdpwinst -u -k
rdpwinst -i
```
5. Enjoy!

Original message: https://t.me/rdpwrap/49131

**Comment by sashaqwert** [comment] 2024-04-14 08:33
Duplicate of https://github.com/stascorp/rdpwrap/issues/2529

**Comment by sashaqwert** [comment] 2024-04-14 08:34
One `termsrv.dll` version = ONE opened issue for one architecture.

**Closed as not planned by sashaqwert** 2024-04-14 08:33 UTC
