### ISSUE TITLE
Need new ini entry for 16299.19

### ISSUE THREAD

**Issue by MarkStega** [stascorp/rdpwrap#338] opened 2017-10-26 16:36 UTC
I updated to the fall creators version of win 10; The version is 16299.19 and RDPWrap is not functioning after the update. Presumably it just needs an additional ini entry.

**Comment by binarymaster** [comment] 2017-10-26 16:46
Diagnostics screenshot?

**Comment by MarkStega** [comment] 2017-10-26 18:59
![rdpconf_2017-10-26_14-50-23](https://user-images.githubusercontent.com/634561/32071767-41b91a20-ba5e-11e7-8ff5-03a50b95ec3e.png)

**Comment by binarymaster** [comment] 2017-10-26 19:00
Just reinstall it.

**Comment by binarymaster** [comment] 2017-10-26 19:02
> The version is 16299.19

And why you're posting wrong version while it's actually 16299.15 ? :confused: 

So it's duplicate of #316.

**Closed by binarymaster** 2017-10-26 19:02 UTC

**Comment by MarkStega** [comment] 2017-10-26 19:28
I was reporting the version that windows shows with the ver command

![cmd_2017-10-26_15-26-12](https://user-images.githubusercontent.com/634561/32072917-593eb2aa-ba62-11e7-8bed-f945fe4aae6a.png)

**Comment by binarymaster** [comment] 2017-10-26 19:42
Anyway it's wrong way, that lead to opening duplicate issues.

Only RDPConf could show real version of `termsrv`.

**Comment by c-edmonston** [comment] 2017-11-01 07:24
Unable to get RDP working with win10 16299.19 (trmsrv 16299.15)

![image](https://user-images.githubusercontent.com/11673043/32264232-cf28b690-bf31-11e7-8117-64bb8b1932cc.png)
![image](https://user-images.githubusercontent.com/11673043/32264236-d3a381e6-bf31-11e7-857f-b1abd9bacafa.png)

Been digging through issues to try and figure out why this isn't working, and I can't seem to find anything. 
Seems to be the same as this, and I don't want to make ANOTHER dupe issue.

**Comment by binarymaster** [comment] 2017-11-01 09:44
@c-edmonston please see https://github.com/stascorp/rdpwrap/issues/194#issuecomment-323564111
