### ISSUE TITLE
i experince crashes on termsrv ver 6.1.7601.24402

### ISSUE THREAD

**Issue by MiniK0nG** [stascorp/rdpwrap#2517] opened 2024-03-13 16:37 UTC
somtimes the wrapper says 
service state : stopped 
Listener state : Not Listening 
and i have to reinstalll all. Can you update the ini file pls, i can share the file here https://we.tl/t-EQ4HjcEr3f thanks for the help

**Comment by sashaqwert** [comment] 2024-03-14 06:56
Duplicate of https://github.com/stascorp/rdpwrap/issues/734

**Closed as not planned by sashaqwert** 2024-03-14 06:56 UTC
Labels: duplicate

**Comment by MiniK0nG** [comment] 2024-04-16 18:18
ok, i reposted there, sorry for the mess, pls can you answer there?
