### ISSUE TITLE
server 2016 preview 5 is not supported

### ISSUE THREAD

**Issue by RobertSpir** [stascorp/rdpwrap#115] opened 2016-05-01 07:53 UTC
termsrv.dll build 14300
http://tesla.math.sk/termsrv.zip

**Comment by binarymaster** [comment] 2016-05-08 13:31
Duplicate of https://github.com/stascorp/rdpwrap/issues/79

Added your build to TODO list

**Closed by binarymaster** 2016-05-08 13:31 UTC
Labels: duplicate
