### ISSUE TITLE
Terminal Services is not supported. 10.0.16299.15

### ISSUE THREAD

**Issue by CZcharlie** [stascorp/rdpwrap#362] opened 2017-12-04 19:38 UTC
Terminal Services is not supported. 10.0.16299.98

**Comment by binarymaster** [comment] 2017-12-06 20:44
Please provide RDPConf screenshot.

**Comment by tmknight** [comment] 2017-12-14 19:49
![image](https://user-images.githubusercontent.com/548588/34011408-e9ca26dc-e0dd-11e7-8da7-56cedb21f07a.png)

**Comment by CZcharlie** [comment] 2017-12-14 20:01
I apologize to them for my mistake


Charlie

**Comment by binarymaster** [comment] 2017-12-27 11:02
Duplicate of #316.

**Closed by binarymaster** 2017-12-27 11:02 UTC
