### ISSUE TITLE
McAffee flags the installer as a virus

### ISSUE THREAD

**Issue by mattcbro** [stascorp/rdpwrap#2447] opened 2023-12-14 06:30 UTC
At this date 12/13/2023,  the MacAfee anti virus software is flagging the installer as a virus.  Is this a problem?

**Comment by sashaqwert** [comment] 2023-12-14 06:37
Known issue. See https://github.com/stascorp/rdpwrap/issues/277

**Comment by sashaqwert** [comment] 2023-12-14 06:37
Duplicate of https://github.com/stascorp/rdpwrap/issues/277

**Closed as not planned by sashaqwert** 2023-12-14 06:37 UTC
Labels: duplicate
