### ISSUE TITLE
Support for release 18362.592

### ISSUE THREAD

**Issue by keimaster** [stascorp/rdpwrap#960] opened 2020-01-15 22:49 UTC
I know this update is brand new, and I have updated my rdpwrap.ini files many times before. But now I am missing the latest offset in order to make it work. I would greatly appreciate any help.

**Comment by zerg91** [comment] 2020-01-15 22:52
I have the same problem with 18362.592
Thank you

**Comment by keimaster** [comment] 2020-01-15 22:53
It will probably take some time for someone to generate the offset, but as I have dire needs for it I would greatly appreciate any help.

**Comment by bjgo** [comment] 2020-01-16 06:56
> It will probably take some time for someone to generate the offset, but as I have dire needs for it I would greatly appreciate any help.

whitch version of service in RDPConf app? 10.0.18362.267?

**Comment by zerg91** [comment] 2020-01-16 09:22
> > It will probably take some time for someone to generate the offset, but as I have dire needs for it I would greatly appreciate any help.
> 
> whitch version of service in RDPConf app? 10.0.18362.267?

Yes!, RDPConf app shows 10.0.18362.267 "Fully supported" using #859 
Windows shows build 18362.592 
Multi session not working
Thanks

**Comment by tafse** [comment] 2020-01-18 08:53
I got this issue too, windows version is 18362.592, and rdp wrapper version is 10.0.18362.267. someone would help? many thanks.

**Comment by s0nic9** [comment] 2020-01-18 10:56
Are you using Windows Pro ?

**Comment by tafse** [comment] 2020-01-18 12:24
> Are you using Windows Pro ?

no. Windows 10 Home

**Comment by s0nic9** [comment] 2020-01-18 12:30
@zerg91  just tested on windows 10 updated 592, rdpconf 267 , works here with 4 concurrents user. 
using  double check steps.

@tafse use updates from https://github.com/stascorp/rdpwrap/pull/859

**Comment by tafse** [comment] 2020-01-18 12:47
> @zerg91 just tested on windows 10 updated 592, rdpconf 267 , works here with 4 concurrents user.
> using double check steps.
> 
> @tafse use updates from #859

I tried it, but it doesn't work for me. :(

**Comment by geniusjoe** [comment] 2020-02-05 11:33
> > @zerg91 just tested on windows 10 updated 592, rdpconf 267 , works here with 4 concurrents user.
> > using double check steps.
> > @tafse use updates from #859
> 
> I tried it, but it doesn't work for me. :(

it work well for me.
and my version is win10 pro 1903 18362.592

**Comment by jfariasf** [comment] 2020-02-06 05:19
I have the same issue. Any user will be required to disconnect using the last ini file on Windows pro 1903 18362.592.

**Comment by geniusjoe** [comment] 2020-02-06 05:24
> I have the same issue. Any user will be required to disconnect using the last ini file.

try to use this rdpwrap.ini file if your version is 18362.592 win10 pro
[https://github.com/asmtron/rdpwrap/tree/master/res](url)

**Comment by jfariasf** [comment] 2020-02-06 05:28
Your link doesn't work but I get it's the file from the asmtron user. I just tried with the last one that says it was updated on Feb 5. The only difference is that the OS is in spanish. Edit: Also not activated but I don't think that would make a difference.

![meh](https://user-images.githubusercontent.com/10675509/73908403-8e10df80-4877-11ea-95c1-34330195a6e5.png)

**Comment by geniusjoe** [comment] 2020-02-06 05:42
> Your link doesn't work but I get it's the file from the asmtron user. I just tried with the last one that says it was updated on Feb 5. The only difference is that the OS is in spanish. Edit: Also not activated but I don't think that would make a difference.
> 
> ![meh](https://user-images.githubusercontent.com/10675509/73908403-8e10df80-4877-11ea-95c1-34330195a6e5.png)

![TIM截图20200206133633](https://user-images.githubusercontent.com/37236056/73908812-cb13bb00-48e5-11ea-8a26-d5e1a0ce5f3f.png)

Did you replace the previous rdpwrap.ini file with the new rdpwrap.ini file written by asmtron in the 
`Program Files\RDP Wrapper` folder? 
And my folder is configured using #859 issue.

**Comment by jfariasf** [comment] 2020-02-06 06:33
You were right. The utility had to check the missing dll. Now it works but I'm a bit worried. Can I trust this downloaded dll?

**Comment by geniusjoe** [comment] 2020-02-06 07:56
> You were right. The utility had to check the missing dll. Now it works but I'm a bit worried. Can I trust this downloaded dll?

To be honest, I don't know.lol

**Comment by gerardoparedes** [comment] 2020-02-08 18:22
I have the same issue:

 windows 10 PRO update 592, rdpconf 267

**Comment by sebaxakerhtc** [comment] 2022-06-20 10:22
Duplicate of https://github.com/stascorp/rdpwrap/issues/871

**Closed as completed by sebaxakerhtc** 2022-06-20 10:22 UTC
