### ISSUE TITLE
rdp warap not working in windows 10 21h2  os build 19044.1348

### ISSUE THREAD

**Issue by bonaccount** [stascorp/rdpwrap#1626] opened 2021-11-20 05:30 UTC
rdp warap not working in windows 10 21h2  os build 19044.1348

**Comment by sashaqwert** [comment] 2021-11-20 07:20
![изображение](https://user-images.githubusercontent.com/24974508/142718233-d8195d69-59da-43f9-9eb4-46c538343688.png)
Duplicate of https://github.com/stascorp/rdpwrap/issues/1595

**Closed as completed** 2021-11-20 09:05 UTC
