### ISSUE TITLE
1909(18363.1734)的版本有更新吗?

### ISSUE THREAD

**Issue by PromiseYa** [stascorp/rdpwrap#1505] opened 2021-08-31 07:29 UTC
如题,请问这个版本的dll有更新吗?我不会反编译,需要你们的帮助,感谢!!!

**Comment by feiazifeiazi** [comment] 2021-09-01 05:46
[+] Select option 1, install...
[*] Installing...
[+] termsrv.dll 10.0.18362.1533
[-] Not support the version of termsrv, please contact author to update.

**Comment by sebaxakerhtc** [comment] 2021-10-27 11:58
> [+] Select option 1, install... [*] Installing... [+] termsrv.dll 10.0.18362.1533 [-] Not support the version of termsrv, please contact author to update.

https://github.com/sebaxakerhtc/rdpwrap.ini/commit/4bb6124b27ae382e2b17c109695e40769b790c95

**Comment by sebaxakerhtc** [comment] 2021-10-27 12:36
Duplicate of https://github.com/stascorp/rdpwrap/issues/1418

**Closed as completed by sebaxakerhtc** 2021-10-27 12:36 UTC
