### ISSUE TITLE
10.0.17763.771 pls~

### ISSUE THREAD

**Issue by ygt1233211** [stascorp/rdpwrap#2011] opened 2022-10-07 04:36 UTC
10.0.17763.771 pls~

**Comment by sashaqwert** [comment] 2022-10-07 06:02
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by BadAss-King** [comment] 2022-10-07 14:44
Problem with Same Version

![image](https://user-images.githubusercontent.com/66208715/194580417-401cd5e3-ccd4-4000-9365-5ca4af69925b.png)

termsrv.dll>> https://we.tl/t-K1g1m837If

**Comment by sashaqwert** [comment] 2022-10-07 14:52
Duplicate of https://github.com/stascorp/rdpwrap/issues/1994

**Closed as not planned by sashaqwert** 2022-10-07 14:52 UTC
Labels: duplicate

**Comment by sashaqwert** [comment] 2022-10-07 14:55
> Problem with Same Version

`termsrv.dll` version ≠ Windows version.

If you think that it was closed by mistake, then attach the DLL and a screenshot of exactly the version that is in the name of isdue.
