### ISSUE TITLE
Listener state: Not supported, suddenly since today

### ISSUE THREAD

**Issue by Mig287** [stascorp/rdpwrap#3202] opened 2024-06-13 10:09 UTC
Hello,

RDP wrapper suddenly stopped working for me. 
[termsrv.zip](https://github.com/user-attachments/files/15817570/termsrv.zip)

I uploaded my termsrv.dll

I tried updating and reinstalling.

Thx in advance

**Comment by binarymaster** [comment] 2024-06-13 20:56
Duplicate of #2833.

**Closed as not planned by binarymaster** 2024-06-13 20:56 UTC
Labels: duplicate
