### ISSUE TITLE
Not working on 10.0.19041.867

### ISSUE THREAD

**Issue by bartm83** [stascorp/rdpwrap#1360] opened 2021-03-30 07:17 UTC
I need offset for 10.0.19041.867.
Can anybody help me?

**Comment by torenus** [comment] 2021-04-07 07:30
Tested on Windows 10 Home 20H2 19042.906 19042.867

INSTALL of RDP Wrapper and Autoupdater

Download "[RDPWrap-v1.6.2.zip](https://fex.net/ru/s/rys313t)" and extract all files to the "%ProgramFiles%\RDP Wrapper" directory
DO NOT use other directories to install/extract the RDP Wrapper files. USE ONLY the "%ProgramFiles%\RDP Wrapper" directory (normally C:\Program Files\RDP Wrapper)
Download [autoupdate.zip](https://fex.net/ru/s/dkkrnp2) and extract all files to the "%ProgramFiles%\RDP Wrapper" directory
To enable autorun of autoupdate.bat on system startup, run the folling helper batch file as administrator:
"%ProgramFiles%\RDP Wrapper\helper\autoupdate__enable_autorun_on_startup.bat"
Set in your Set in your Antivirus or Windows Defender an exclusion on the folder "%ProgramFiles%\RDP Wrapper" to prevent the deletion of RDP Wrapper files
Now you can use the autoupdate batch file to install and update the RDP Wrapper. Please run autoupdate.bat as administrator:
"%ProgramFiles%\RDP Wrapper\autoupdate.bat"

**Comment by TheNewCivilian** [comment] 2021-04-07 09:08
@torenus Please provide a more credible source for autoupdate.zip  than 'fex.net' if possible. Even if batch files are readable by nature keeping the download link interchangeable / having the update source provided by different Github users puts any user not capable of reading source or blindly trusting this tool in Danger!

**Comment by torenus** [comment] 2021-04-07 09:16
https://github.com/stascorp/rdpwrap/pull/1160#issue-480711748

Link to [Google Drive](https://drive.google.com/drive/folders/1AKjIlszQxB0J0X4hcbFQpLsuRaos4G73?usp=sharing)

**Comment by magicmopper** [comment] 2021-04-08 06:37
@torenus state is “not listening”

**Comment by TheNewCivilian** [comment] 2021-04-08 09:44
@jokerwenxiao

Did you check for Remote Desktop Access to be enabled in the windows settings?
[https://www.techbout.com/enable-remote-desktop-windows-41024/](https://www.techbout.com/enable-remote-desktop-windows-41024/)

**Comment by torenus** [comment] 2021-04-09 14:49
Please run autoupdate.bat as administrator!
It works for me.

https://github.com/stascorp/rdpwrap/issues/1361#issuecomment-814678724

**Comment by zdavis28** [comment] 2021-04-14 00:42
> Tested on Windows 10 Home 20H2 19042.906 19042.867
> 
> INSTALL of RDP Wrapper and Autoupdater
> 
> Download "[RDPWrap-v1.6.2.zip](https://fex.net/ru/s/rys313t)" and extract all files to the "%ProgramFiles%\RDP Wrapper" directory
> DO NOT use other directories to install/extract the RDP Wrapper files. USE ONLY the "%ProgramFiles%\RDP Wrapper" directory (normally C:\Program Files\RDP Wrapper)
> Download [autoupdate.zip](https://fex.net/ru/s/dkkrnp2) and extract all files to the "%ProgramFiles%\RDP Wrapper" directory
> To enable autorun of autoupdate.bat on system startup, run the folling helper batch file as administrator:
> "%ProgramFiles%\RDP Wrapper\helper\autoupdate__enable_autorun_on_startup.bat"
> Set in your Set in your Antivirus or Windows Defender an exclusion on the folder "%ProgramFiles%\RDP Wrapper" to prevent the deletion of RDP Wrapper files
> Now you can use the autoupdate batch file to install and update the RDP Wrapper. Please run autoupdate.bat as administrator:
> "%ProgramFiles%\RDP Wrapper\autoupdate.bat"

I love you.

**Comment by sebaxakerhtc** [comment] 2022-06-20 13:05
Duplicate of https://github.com/stascorp/rdpwrap/issues/1317

**Closed as completed by sebaxakerhtc** 2022-06-20 13:05 UTC
