### ISSUE TITLE
10.0.19045.4291 need support

### ISSUE THREAD

**Issue by a4081675** [stascorp/rdpwrap#2599] opened 2024-04-27 08:10 UTC
<img width="295" alt="image" src="https://github.com/stascorp/rdpwrap/assets/17973196/5334e3b9-c992-4989-a247-65395f90c1b7">
<img width="348" alt="image" src="https://github.com/stascorp/rdpwrap/assets/17973196/29c0deb2-f538-46eb-8094-eae92e11d0dd">

**Comment by 235623** [comment] 2024-04-27 12:44
no

**Comment by loyejaotdiqr47123** [comment] 2024-04-28 07:52
@a4081675 Can you upload termsrv.dll?

**Comment by a4081675** [comment] 2024-04-28 07:57
> @a4081675您可以上传termsrv.dll吗？

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/15141267/termsrv.zip)

**Comment by loyejaotdiqr47123** [comment] 2024-04-28 08:16
Duplicate of #1004

**Comment by binarymaster** [comment] 2024-04-28 15:08
> RDPConf shows "ver. N/A"

Not a serviceable issue, contact chat in Telegram instead.

**Closed as not planned by binarymaster** 2024-04-28 15:08 UTC
