### ISSUE TITLE
Google Chrome blocks rdpwrap downloading

### ISSUE THREAD

**Issue by daskol** [stascorp/rdpwrap#344] opened 2017-11-04 07:25 UTC
I have tried to download RDPwrap via [this link](https://github.com/stascorp/rdpwrap/releases/download/v1.6.1/RDPWrap-v1.6.1.zip) but Google Chrome blocks downloading because the archive is infected. What is the deal?

**Comment by binarymaster** [comment] 2017-11-04 10:52
> Google Chrome blocks downloading because the archive is infected

Google Chrome thinks it's malicious, but actually it's not. Try Mozilla Firefox or IE / Edge.

Duplicate of #277.

**Closed by binarymaster** 2017-11-04 10:52 UTC
Labels: duplicate

**Comment by RolfBly** [comment] 2022-09-16 13:11
Chrome, Firefox and Brave browsers all block it. Edge warns, shows it's infected with [PUA:Win32/Presenoker](https://www.partitionwizard.com/partitionmanager/what-is-puawin32presenoker.html) and lets you choose to quarantine, delete or allow.
