### ISSUE TITLE
Not listening

### ISSUE THREAD

**Issue by RandomPotato893** [stascorp/rdpwrap#1628] opened 2021-11-21 05:28 UTC
I am trying to update my ini file by pasting some text in, but im either doing it wrong or something else is wrong It says not listening
Thanks for any replies!
![image](https://user-images.githubusercontent.com/67339016/142750877-a95d1657-d4b4-40d6-8f06-699d8bfdd321.png)

**Comment by sashaqwert** [comment] 2021-11-21 07:55
Duplicate of https://github.com/stascorp/rdpwrap/issues/1600
Rule: one `termsrv.dll` version = one issue.

**Closed as completed** 2021-11-21 08:38 UTC

**Comment by RandomPotato893** [comment] 2021-11-21 20:21
I already used that file, it fixed the thing so now it says fully supported, however it isn't listening. On that tread I saw the .ini file, but when i tried to use that code, it didn't work. This is probably an obvious question but can you give me instructions on how to update the .ini file with that new code.

**Comment by RandomPotato893** [comment] 2021-11-21 20:29
Never mind, sorry I'm so stupid I don't know how to use GitHub. I got it working, thanks for your help.

**Comment by sebaxakerhtc** [comment] 2021-11-21 20:34
> 

Not so!
Many users of this tool can't get it working immediately.
But a good idea to read same errors and answers before posting "HELP - not work" 😉
