### ISSUE TITLE
windows 11 ver 10.0.22621.2506 not supported

### ISSUE THREAD

**Issue by githubanonym** [stascorp/rdpwrap#3363] opened 2024-11-23 11:01 UTC
![Sans titre](https://github.com/user-attachments/assets/f1308d58-0bd3-4fc9-b1c1-cb7835bffea7)
Hi, i can't make the wrapper work on my computer.
can you point to me what's the process please ?
i used the scripts install.bat and update.bat, but i can't see any ".ini" downloaded althougth the update.bat script tells me everything is up to date

**Comment by binarymaster** [comment] 2024-11-23 11:25
Duplicate of https://github.com/stascorp/rdpwrap/issues/2383.

**Closed as not planned by binarymaster** 2024-11-23 11:25 UTC
Labels: duplicate
