### ISSUE TITLE
RDP Wrapper not supported after Win10 Pro new installation 12/18

### ISSUE THREAD

**Issue by Deba1981** [stascorp/rdpwrap#629] opened 2018-12-29 14:58 UTC
Hello,

I installed Win10 Pro over my Win7 Pro.
No I tried to use the RDP Wrapper, but there´s the "Not Supported" Problem.
Because of the new install there´s no old termsrv.dll and no possibility to use an older Win10 Version.

How can I solve the problem?

**Comment by jtsshieh** [comment] 2018-12-30 02:32
I'm pretty sure you get remote access in pro version of windows (hosting the connection)...

**Comment by nejadmand** [comment] 2018-12-30 21:55
Hi
After update to 1809 we can not use WRAP :(
How we can resolve it?

**Comment by mikeb2** [comment] 2018-12-31 03:38
I am having the same problem since upgrading to Windows 10 1809. RDPConf.exe shows "not supported". I tried the rdpwrap.ini from this post https://github.com/stascorp/rdpwrap/issues/617 but the TermService service will not start when using this ini file. Please help!

**Comment by CharlieF2** [comment] 2019-01-03 04:08
It is very odd - I received a new PC running Windows 10 Pro v 1809 and I followed the posts and edited the RDPWrap.ini and RDP worked perfectly for about 2 weeks.  Now, not sure exactly when it started or why it started but as with Mikeb2 above - the TermService service will not start with the ini file - or with RDPWrap installed.  If I uninstall RDPWrap the Remote Desktop Services service Starts and Runs - but if I installed RDPWrap the Remote Desktop Services service will not run.  Is anyone else having this issue?  Has anyone else figured out a work around?

**Comment by mikeb2** [comment] 2019-01-04 03:49
The rdpwrap.ini from ditchmagnet in post https://github.com/stascorp/rdpwrap/issues/606 fixed the problem on my Windows 10 1089 computer. I downloaded the rdpwrap.zip, extracted the rdpwrap.ini to my RDP Wrapper installation folder, stopped and started the termservice service, the RDPConf.exe status is all green!

**Comment by binarymaster** [comment] 2019-01-06 19:33
Duplicate of #606.

**Closed as completed by binarymaster** 2019-01-06 19:33 UTC
Labels: duplicate
