### ISSUE TITLE
Help Please!!! All green but can't exceed 1 connection

### ISSUE THREAD

**Issue by hckrstudent** [stascorp/rdpwrap#3309] opened 2024-10-15 23:49 UTC
Help Please! 
I've tried everything but still no luck. How do i sort this out please? It was working perfectly fine last week. 

![image](https://github.com/user-attachments/assets/812cab3c-8908-41f6-b3e9-8d1fbb7b4e63)
![image](https://github.com/user-attachments/assets/6795bdb7-f7f8-452b-babf-e7ef6ebe62f2)

**Comment by binarymaster** [comment] 2024-10-16 09:42
Duplicate of #3305.

**Closed by binarymaster** 2024-10-16 09:42 UTC
