### ISSUE TITLE
OS 19044.1586

### ISSUE THREAD

**Issue by cptmachado** [stascorp/rdpwrap#1789] opened 2022-03-25 14:47 UTC
I'm a newbie, I just set up all RDP and I use version 19044.1586 and got the error:
"The number of connections to this computer is limited and all connections are in use right now. Try connecting later or contact your system administrator.

Could this be because of the Windows version?

![Capture](https://user-images.githubusercontent.com/102372136/160143851-0638c1ef-590e-4c7b-9bee-ca92b7ee58f6.JPG)

**Comment by sashaqwert** [comment] 2022-03-26 15:49
1. Try reboot
2. Duplicate of https://github.com/stascorp/rdpwrap/issues/1725

**Comment by sebaxakerhtc** [comment] 2022-03-26 16:59
> 1. Try reboot
> 
>     2. Duplicate of [Not supported 10.0.19041.1566 #1725](https://github.com/stascorp/rdpwrap/issues/1725)

**Closed as completed by sebaxakerhtc** 2022-03-26 16:59 UTC
