### ISSUE TITLE
rdp wrapper windows version 22h2 os build 19045.2364 Access is denied

### ISSUE THREAD

**Issue by Zander0005** [stascorp/rdpwrap#2068] opened 2022-12-17 23:59 UTC
when i log put in my email and password i get access denied 
![image](https://user-images.githubusercontent.com/103891923/208270624-c47dc6b4-41d4-4401-bf69-8e6821f98e11.png)
![image](https://user-images.githubusercontent.com/103891923/208270764-c7db1a82-fe9e-4580-9fdd-ee770cf7ece8.png)

**Comment by StrickCross** [comment] 2022-12-18 01:36
![imagen](https://user-images.githubusercontent.com/47129366/208272760-98e73b14-aaff-487c-ad73-f1099c1ffca9.png)
![imagen](https://user-images.githubusercontent.com/47129366/208272773-9b908061-4b2c-44be-a1e9-bd6ddad8c0fa.png)
Hello Zander, I have the same version as you, but in my case I can't find any rdpwrap.ini with the same windows version, where did you download it?  in order to achieve the fully supported, thanks

**Comment by Zander0005** [comment] 2022-12-18 01:40
i just downloaded and ran auto update

**Comment by StrickCross** [comment] 2022-12-18 01:47
Did you downloaded version 1.6.2 right?

**Comment by Zander0005** [comment] 2022-12-18 01:48
yeah? i think

**Comment by Zander0005** [comment] 2022-12-18 02:19
> Did you downloaded version 1.6.2 right?

i just downloaded auto updater and then ran it as admin

**Comment by StrickCross** [comment] 2022-12-18 02:38
> 
I did the same, but still doesn't work.. Could you share the rdpwrap.ini?      At least i would like to try if it works for me with the fully supported thing

**Comment by sashaqwert** [comment] 2022-12-18 06:19
@Zander0005
> access denied

Please, add your RDP users to Administrators or «Remote Desktop users» group.

**Comment by sashaqwert** [comment] 2022-12-18 08:25
One `termsrv.dll` version = one opened issue! --> Duplicate --> closed :)

**Comment by sashaqwert** [comment] 2022-12-18 08:25
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992

**Closed as not planned by sashaqwert** 2022-12-18 08:25 UTC
Labels: duplicate

**Comment by Zander0005** [comment] 2022-12-18 12:29
> @Zander0005
> 
> > access denied
> 
> Please, add your RDP users to Administrators or «Remote Desktop users» group.
The account im trying to log in to is an administrator

**Comment by sashaqwert** [comment] 2022-12-18 14:23
@Zander0005 
> The account im trying to log in to is an administrator

See https://github.com/stascorp/rdpwrap/issues/101#issuecomment-197057498

**Comment by Zander0005** [comment] 2023-01-02 21:11
@sashaqwert that didnt work is there any chance you can help me?

**Comment by sashaqwert** [comment] 2023-01-03 08:14
@Zander0005 
>  that didnt work is there any chance you can help me?

You can reinstall windows or ask this in official Telegram chat (link in repository README)

**Comment by Zander0005** [comment] 2023-01-22 20:29
@sashaqwert
what version would I need?

**Comment by dbart126** [comment] 2023-04-12 23:27
It seems everyone keeps pointing back to older versions.  Will 22h2 work with dll modification?  Build is 19045.2846, Or I am okay with wrapper but don't see a build or topic for 19405 that anyone is saying works.

**Comment by dbart126** [comment] 2023-04-13 01:08
> @Zander0005
> 
> > access denied
> 
> Please, add your RDP users to Administrators or «Remote Desktop users» group.

Doesn't that give them all access?  We want all users besides a few and non admin.  Is this required for it to work?  Does this also work on 19045.2846 or does it matter?

**Comment by santosh25344** [comment] 2023-08-11 06:47
Anybody can share Wrapper for windows 10 19045.2846 version ?
