### ISSUE TITLE
not supporting 10.0.19041.1202

### ISSUE THREAD

**Issue by Faisalsh44** [stascorp/rdpwrap#1965] opened 2022-08-22 03:59 UTC
![Screenshot 2022-08-22 080318](https://user-images.githubusercontent.com/111722117/185837204-be085876-29a9-49a0-bf62-5ce561d1c4ea.png)

**Comment by sashaqwert** [comment] 2022-08-22 10:15
Duplicate of https://github.com/stascorp/rdpwrap/issues/1509

**Closed as not planned by sashaqwert** 2022-08-22 10:15 UTC
Labels: duplicate
