### ISSUE TITLE
10.0.19044.2846

### ISSUE THREAD

**Issue by tiger8877** [stascorp/rdpwrap#2285] opened 2023-07-21 09:10 UTC

**Comment by sashaqwert** [comment] 2023-07-21 11:44
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by sashaqwert** [comment] 2023-07-21 11:46
> 10.0.19044.2846

See https://github.com/stascorp/rdpwrap/issues/1992#issuecomment-1507198724

**Comment by sashaqwert** [comment] 2023-07-21 11:47
Duplicate of https://github.com/stascorp/rdpwrap/issues/2125

**Closed as not planned by sashaqwert** 2023-07-21 11:47 UTC
Labels: duplicate
