### ISSUE TITLE
Terminal services not supported - no folder and or files are created

### ISSUE THREAD

**Issue by jay-sync** [stascorp/rdpwrap#2160] opened 2023-03-29 17:25 UTC
currently on a w11 stripped mod version done via NTlite

after running the `install.bat` file as an admin I get this output and nothing gets installed:

<img width="820" alt="image" src="https://user-images.githubusercontent.com/63868998/228618942-0eea5989-e731-48a2-8281-8943c2ed1e4a.png">

<img width="350" alt="image" src="https://user-images.githubusercontent.com/63868998/228619032-8915d019-be1b-4866-b0ac-f2926dfc9e3e.png">

**Comment by sashaqwert** [comment] 2023-03-30 06:20
Duplicate of https://github.com/stascorp/rdpwrap/issues/1883

**Closed as not planned by sashaqwert** 2023-03-30 06:20 UTC
Labels: duplicate
