### ISSUE TITLE
Windows 10 Pro 2004 RDPWrap when connecting client computer the RDP host stops working.

### ISSUE THREAD

**Issue by Nethercraft5608** [stascorp/rdpwrap#1150] opened 2020-08-25 05:02 UTC
I have the latest .ini file for Windows Version 2004.This is happened to me 2 times and the first time i just reset my whole computer.The service is listening and working properly but every time i connect a client it will say the same thing when the server is disconnected.The host RDP works when i open the application "RDPCheck.exe" but when connecting the client computer it instantly stops working and says "Disconnected By Server."

Could somebody please help me.

The last thing i installed when this occurred was a application.I don't think the application uses any remote access software or any connectivity that i know of.

Pictures:
![Screenshot (1)](https://user-images.githubusercontent.com/56810281/91124812-3c855080-e6f4-11ea-9f27-14458d2f76ae.png)

UPDATED:
![Screenshot (3)](https://user-images.githubusercontent.com/56810281/91126050-36dd3a00-e6f7-11ea-8db5-c7b461cf52b5.png)

From RDPCheck.exe (Included by ZIP file)
![Screenshot (2)](https://user-images.githubusercontent.com/56810281/91124913-7d7d6500-e6f4-11ea-8893-2d8a5c94ddb1.png)

**Comment by Nethercraft5608** [comment] 2020-08-25 05:04
On the config application it says that remote desktop is off.I can assure you it is on but it still does not work.

**Comment by robbak** [comment] 2020-08-25 05:10
Whatever is the reason why that checkbox isn't set, is the reason why
it isn't working. You must have a tick in that box. At the moment, the
answer to your question is, 'It isn't working because it's turned
off.'

Make sure that your antivirus isn't causing problems. If it works
while all antivirus are disabled (disable a third party one and
Windows Defender will silently enable itself) then look further.

**Comment by Nethercraft5608** [comment] 2020-08-25 05:17
> Make sure that your antivirus isn't causing problems. If it works while all antivirus are disabled (disable a third party one and Windows Defender will silently

My windows defender real time protection is off and firewall is off and i only have one antivirus which is the built in one.I have checked the enable remote access box but still got the same error.

**Comment by combi0496** [comment] 2020-10-20 08:34
I also facing this issue also when one time open this RDPCheck.exe can but when try for second time cannot and need to do restart pc . After restart ok but same problem also just can open one time only. before this my computer have running windows Update is it cause that issue happen?

**Comment by sebaxakerhtc** [comment] 2022-06-20 11:43
Duplicate of https://github.com/stascorp/rdpwrap/issues/1004

**Closed as completed by sebaxakerhtc** 2022-06-20 11:43 UTC
