### ISSUE TITLE
拒绝访问

### ISSUE THREAD

**Issue by zyjjack** [stascorp/rdpwrap#3230] opened 2024-07-16 09:51 UTC
﻿拒绝访问。
______________________________________________________________

You can check RDP functionality with RDPCheck program.
Also you can configure advanced settings with RDPConf program.

请按任意键继续. . .

**Comment by loyejaotdiqr47123** [comment] 2024-07-16 09:54
?杀软关了没

**Comment by FiendFEARing** [comment] 2024-07-16 11:25
管理员权限运行

**Comment by binarymaster** [comment] 2024-07-16 12:58
Duplicate of #1417. Check your antivirus.

Non-english issues not allowed.

**Closed as not planned by binarymaster** 2024-07-16 12:58 UTC
Labels: duplicate
