### ISSUE TITLE
10.0.18362.1316

### ISSUE THREAD

**Issue by Alex874** [stascorp/rdpwrap#1281] opened 2021-01-14 06:23 UTC
Good afternoon. RDP stopped working. Can anyone help me?

**Comment by andbener** [comment] 2021-01-14 07:46
the same problem

**Comment by sawwd** [comment] 2021-01-14 08:12
This might help you all https://github.com/stascorp/rdpwrap/issues/1278#issuecomment-760007826

**Comment by elihoo** [comment] 2021-01-14 08:39
> This might help you all [#1278 (comment)](https://github.com/stascorp/rdpwrap/issues/1278#issuecomment-760007826)

it helped. Thank you!!!

**Comment by Alex874** [comment] 2021-01-14 08:41
Thank you. It helped

**Comment by andbener** [comment] 2021-01-14 08:51
> This might help you all [#1278 (comment)](https://github.com/stascorp/rdpwrap/issues/1278#issuecomment-760007826)

Thank you so much

**Comment by fufaeff** [comment] 2021-01-14 09:51
Thank

**Comment by ganmosti** [comment] 2021-01-19 13:19
Thanks! it work

**Comment by ljcdndx** [comment] 2021-03-27 06:35
thanks a lot

**Comment by lybvest** [comment] 2021-04-11 13:46
![image](https://user-images.githubusercontent.com/64423128/114306694-34f1ab00-9b0f-11eb-8aee-f5445a98447c.png)
 i try all this steps,but also like this ,can anybody help me to solve it, thanks!

**Comment by sebaxakerhtc** [comment] 2022-06-20 12:36
Duplicate of https://github.com/stascorp/rdpwrap/issues/1278

**Closed as completed by sebaxakerhtc** 2022-06-20 12:36 UTC
