### ISSUE TITLE
Add Support remote audio microfon?

### ISSUE THREAD

**Issue by burluckoff** [stascorp/rdpwrap#488] opened 2018-05-21 00:46 UTC
![default](https://user-images.githubusercontent.com/36870158/40285839-791872e8-5ca9-11e8-9f52-425851c54bbf.png)

**Comment by binarymaster** [comment] 2018-05-21 09:44
This is built-in feature which is available in Pro editions or higher.

Duplicate of #74.

**Closed by binarymaster** 2018-05-21 09:44 UTC

**Comment by PGilm** [comment] 2019-03-18 17:13
Yes, but any way to wrap this feature for a Win 7 Home premium edition?
