### ISSUE TITLE
10.0.22621.4391 Not listening

### ISSUE THREAD

**Issue by nNelleFn** [stascorp/rdpwrap#3370] opened 2024-11-30 18:32 UTC
![{D9920B04-1048-4717-979D-00BE286AB8A2}](https://github.com/user-attachments/assets/c7ae061e-29c7-421f-8f4e-4577ca881c1a)
3316 It doesn't help
[termsrv.zip](https://github.com/user-attachments/files/17966427/termsrv.zip)

**Comment by binarymaster** [comment] 2024-11-30 19:07
One issue per version, duplicate of https://github.com/stascorp/rdpwrap/issues/3316.

If it works for others and not for you, make sure that changes to INI file have been entered correctly, keeping an empty line at the end of file. Additionally, the service must be restarted - and if that doesn't help, try these steps: https://t.me/rdpwrap/74040

**Closed as not planned by binarymaster** 2024-11-30 19:07 UTC
Labels: duplicate
