### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by mhtkumar0025** [stascorp/rdpwrap#3274] opened 2024-09-20 10:03 UTC
![Screenshot 2024-09-20 153319](https://github.com/user-attachments/assets/41c80c80-9960-4475-9f8e-aefcac217a53)

**Comment by binarymaster** [comment] 2024-09-20 11:04
Duplicate of https://github.com/stascorp/rdpwrap/issues/3238.

**Closed as not planned by binarymaster** 2024-09-20 11:04 UTC
Labels: duplicate
