### ISSUE TITLE
Windows 11     10.0.22000.318

### ISSUE THREAD

**Issue by Yeezkuailo** [stascorp/rdpwrap#1601] opened 2021-11-10 09:38 UTC
![1636536840(1)](https://user-images.githubusercontent.com/94045557/141088181-a09db3b6-0962-4da7-ab4c-10d9931819cc.png)
I tried a thousand things

From 10.0.22000.1 at the beginning to 10.0.22000.318 now

Who can tell me what to do now

The current system is Windows 11

**Comment by sashaqwert** [comment] 2021-11-10 14:15
Duplicate of https://github.com/stascorp/rdpwrap/issues/1599
![изображение](https://user-images.githubusercontent.com/24974508/141129151-f7cf7ed1-1380-48a4-99a5-f89dfcbfe039.png)

**Closed as completed** 2021-11-10 14:41 UTC
