### ISSUE TITLE
10.0.17134.706 everything green but not working

### ISSUE THREAD

**Issue by futuretristan** [stascorp/rdpwrap#814] opened 2019-06-17 13:07 UTC
I installed the RDP wrapper (1.6.2) on one of our Win 10 Enterprise workstations (w/o full internet access) and updated the ini file manually by appending the content of file 10.0.17134.706.txt in repo https://github.com/fre4kyC0de/rdpwrap, containing the following lines:
> [10.0.17134.706]
> LocalOnlyPatch.x86=1
> LocalOnlyOffset.x86=ADAB8
> LocalOnlyCode.x86=jmpshort
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=92521
> LocalOnlyCode.x64=jmpshort
> SingleUserPatch.x86=1
> SingleUserOffset.x86=36B1C
> SingleUserCode.x86=nop
> SingleUserPatch.x64=1
> SingleUserOffset.x64=1511C
> SingleUserCode.x64=Zero
> DefPolicyPatch.x86=1
> DefPolicyOffset.x86=33579
> DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=10E78
> DefPolicyCode.x64=CDefPolicy_Query_edi_rcx
> SLInitHook.x86=1
> SLInitOffset.x86=475DD
> SLInitFunc.x86=New_CSLQuery_Initialize
> SLInitHook.x64=1
> SLInitOffset.x64=22F5C
> SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.17134.706-SLInit]
> bInitialized.x86      =CBF38
> bServerSku.x86        =CBF3C
> lMaxUserSessions.x86  =CBF40
> bAppServerAllowed.x86 =CBF44
> bRemoteConnAllowed.x86=CBF48
> bMultimonAllowed.x86  =CBF4C
> ulMaxDebugSessions.x86=CBF50
> bFUSEnabled.x86       =CBF54
> 
> bServerSku.x64        =F1378
> lMaxUserSessions.x64  =F137C
> bAppServerAllowed.x64 =F1380
> bInitialized.x64      =F2430
> bRemoteConnAllowed.x64=F2434
> bMultimonAllowed.x64  =F2438
> ulMaxDebugSessions.x64=F243C
> bFUSEnabled.x64       =F2440

After restarting the service with `net stop termservice & net start termservice` and executing RDPConf.exe, everything seems to be fine (Wrapper state: Installed, Service state: Running, Listener state: Listening, [fully supported]). However, the tool doesn't work as expected.

When I try and log on with another user simultaneously, then the usual message appears saying that another user is currently logged in.

**Comment by futuretristan** [comment] 2019-06-18 06:22
Is there any debug log that I can use to further investigate this issue?

**Comment by futuretristan** [comment] 2019-06-19 06:44
I'm willing to contribute to solving this issue, but I need a bit of start-up support :)

**Comment by sebaxakerhtc** [comment] 2022-01-04 10:53
Duplicate of https://github.com/stascorp/rdpwrap/issues/721

**Closed as completed by sebaxakerhtc** 2022-01-04 10:53 UTC
