### ISSUE TITLE
Missing support for Win 10 Home x64 - Version 1809 (Build 10.0.17763.316)

### ISSUE THREAD

**Issue by ghost** [stascorp/rdpwrap#689] opened 2019-03-04 14:58 UTC
![28504c83-d2a2-4a32-949f-4e25cda02834 png](https://user-images.githubusercontent.com/29334879/53741158-0caa1380-3e96-11e9-8daa-bbdff48fd1f1.jpg)

I guess I'm not the only one who's having trouble with this on the Oct 2018 update.

Are there any news about fixes or workarounds?

I hate using TeamViewer as much as I hate buying Pro...

**Comment by buergi** [comment] 2019-03-04 18:53
Same for me, any chance to get RDP working again?

**Comment by binarymaster** [comment] 2019-03-04 19:48
Duplicate of #645.

**Closed as completed by binarymaster** 2019-03-04 19:48 UTC
Labels: duplicate
