### ISSUE TITLE
10.0.22621.3737not supported

### ISSUE THREAD

**Issue by connie-cc** [stascorp/rdpwrap#3218] opened 2024-06-25 23:18 UTC
Hi there,
Thanks as always for keep in up the project.
I got not supported for 10.0.22621.3737.
Can you help me?

**Comment by benrojas01** [comment] 2024-06-28 14:50
![Captura de pantalla 2024-06-28 094610](https://github.com/stascorp/rdpwrap/assets/32991065/dc0e5a26-b861-4f3b-b600-c088f98ce8b6)

**Comment by benrojas01** [comment] 2024-06-28 14:56
[termsrv.zip](https://github.com/user-attachments/files/16032340/termsrv.zip)

**Comment by binarymaster** [comment] 2024-06-28 15:43
Cleaned up unrelated messages.

**Comment by loyejaotdiqr47123** [comment] 2024-06-29 06:34
?
In the system version 19041.3737 the termsrv version is indeed 19041.3672.

**Comment by loyejaotdiqr47123** [comment] 2024-06-29 06:36
So Duplicate of #2833

**Closed as not planned** 2024-06-29 14:27 UTC
Labels: duplicate
