### ISSUE TITLE
Windows 10 20H2 New termsrv.dll version 10.0.19041.1503 not work

### ISSUE THREAD

**Issue by SUSIEE01** [stascorp/rdpwrap#1715] opened 2022-02-12 07:50 UTC
Wrapper state: Installed ver.1.5.0.0
Service state: Running ver. N/A
Listener state: Not listening [support level]

stop remote desktop services, replace rdpwrap.ini , restarted services not work.

Anyone help me? I've been trying for days but not work...
I'd appreciate it if you could help me...

![微信图片_20220212154612](https://user-images.githubusercontent.com/90890796/153703233-7ed346e8-6415-45ff-abac-de6b690b9063.png)

**Comment by SUSIEE01** [comment] 2022-02-12 07:55
![Uploading 微信图片_20220212154612.png…]()

**Comment by SUSIEE01** [comment] 2022-02-12 07:56
![微信图片_20220212154612](https://user-images.githubusercontent.com/90890796/153702674-ee9e59b7-d282-4d82-aabf-c32b63a24053.png)

**Comment by sebaxakerhtc** [comment] 2022-02-12 16:18
Duplicate of https://github.com/stascorp/rdpwrap/issues/1697

**Comment by sebaxakerhtc** [comment] 2022-02-12 16:19
Your problem is antivirus

**Closed as completed by sebaxakerhtc** 2022-02-12 16:18 UTC

**Comment by d3vilh** [comment] 2022-02-21 11:52
**No it isn't antivirus!**

During the re-installation wrapper found new "Terminal Services version: **10.0.19041.1387**"
and reports:
```
[-] This version of Terminal Services is not supported.
Send your termsrv.dll to project developer for support.
```

here is the [trmsvr.dll](https://github.com/d3vilh/my_files/blob/1298048abdc9db5d6d683e82b7afe4396fb18077/termsrv.dll)I have.

**Comment by sebaxakerhtc** [comment] 2022-02-21 11:56
> **No it isn't antivirus!**
> 
> During the re-installation wrapper found "Terminal Services version: 10.0.19041.1387" and reports:
> 
> ```
> [-] This version of Terminal Services is not supported.
> Send your termsrv.dll to project developer for support.
> ```

Download my ini file and replace yours or try my modded vetsion of rdpwrapper

**Comment by d3vilh** [comment] 2022-02-21 12:19
> Download my ini file and replace yours or try my modded vetsion o

Tried with the latest v.1.6.2 and with latest ini files `.\RDPWInst.exe -w`, but the result is still the same:

`Listener state: Not listening [not supported]`

It seems MS released new version of DLL which wrapper can't patch.

**Comment by sebaxakerhtc** [comment] 2022-02-21 12:23
> `RDPWInst.exe -w`,

This comman download OLD file.
You should manualy download latest ini from (for example) my source, then 
net stop termservice
Replace ini file
net start termservice

**Comment by d3vilh** [comment] 2022-02-21 19:02
> 



> Replace ini file

yes, did it, it says now "supported", but RDP-tcp listener still not running and `qwinsta` reports zero listeners.
Most probably our IT admins forcefully disabled RDP as a group policy, for local admin as well.

**Comment by sebaxakerhtc** [comment] 2022-02-21 19:04
> > 
> 
> > Replace ini file
> 
> yes, did it, it says now "supported", but RDP-tcp listener still not running and `qwinsta` reports zero listeners. Most probably our IT admins forcefully disabled RDP as a group policy, for local admin as well.

Try my modded version please

**Comment by greasemonkey2** [comment] 2022-02-26 16:53
> > > 
> > 
> > 
> > > Replace ini file
> > 
> > 
> > yes, did it, it says now "supported", but RDP-tcp listener still not running and `qwinsta` reports zero listeners. Most probably our IT admins forcefully disabled RDP as a group policy, for local admin as well.
> 
> Try my modded version please

I tried your ini file - it did not work. Uninstalling H0H2.
