### ISSUE TITLE
RDP installed and running, but not listening or supported (Win 10 Home 21H1 

### ISSUE THREAD

**Issue by Hamuj12** [stascorp/rdpwrap#1552] opened 2021-10-11 02:58 UTC
I've replaced the rdpwrap.ini file with the most recent version (made sure to stop the RDP service and then start after replacing the .ini) but it still says that its not supported and that its not listening. Any help is appreciated!
<img width="304" alt="Screenshot 2021-10-10 215814" src="https://user-images.githubusercontent.com/69257879/136727114-2e1c1f8d-7aae-4f62-b27d-0c4e3f22f345.png">

**Comment by hezhanbang** [comment] 2021-10-12 01:39
i have the same problem.  can you help me?

**Comment by sausix** [comment] 2021-10-12 13:14
Don't create new issues if there's already one for a specific version.

https://github.com/stascorp/rdpwrap/issues/1542

The provided ini file works.
And as always on updating to a new ini file, stop the service before and restart it after replacing!

**Comment by tjzxcv** [comment] 2021-10-14 08:18
It is recommended to find the relevant configuration of the system version and paste it into ini.The purpose of replacing ini is to adapt the version of the system

**Comment by Cosmits** [comment] 2021-10-18 09:05
[10.0.19041.1202-SLInit]
; no x86 section

bServerSku.x64        =10710C
bRemoteConnAllowed.x64=107120
bFUSEnabled.x64       =10712C
bAppServerAllowed.x64 =107118
bMultimonAllowed.x64  =107124
lMaxUserSessions.x64  =107110
ulMaxDebugSessions.x64=107128
bInitialized.x64      =107108

[10.0.19041.1202]
; no x86 section

LocalOnlyPatch.x64    =1
LocalOnlyOffset.x64   =89D81
LocalOnlyCode.x64     =jmpshort
SingleUserPatch.x64   =1
SingleUserOffset.x64  =0D212
SingleUserCode.x64    =Zero
DefPolicyPatch.x64    =1
DefPolicyOffset.x64   =19105
DefPolicyCode.x64     =CDefPolicy_Query_eax_rcx
SLInitHook.x64        =1
SLInitOffset.x64      =1E98C
SLInitFunc.x64        =New_CSLQuery_Initialize

**Comment by sebaxakerhtc** [comment] 2021-10-25 15:52
duplicate of https://github.com/stascorp/rdpwrap/issues/1509

**Closed as completed by sebaxakerhtc** 2021-10-25 15:52 UTC
