### ISSUE TITLE
22631.3880 bug

### ISSUE THREAD

**Issue by noober120** [stascorp/rdpwrap#3232] opened 2024-07-17 09:06 UTC
![image](https://github.com/user-attachments/assets/f86864fd-4c94-4f75-b7c1-1734a8b72032)

**Comment by loyejaotdiqr47123** [comment] 2024-07-17 09:15
Please, attach your RDPConf screenshot and termsrv.dll.

**Comment by loyejaotdiqr47123** [comment] 2024-07-17 09:20
Try run net start termservice？

**Comment by noober120** [comment] 2024-07-17 09:42
> Please, attach your RDPConf screenshot and termsrv.dll.

![image](https://github.com/user-attachments/assets/b632290d-ea10-4b78-99c6-8964ee9ee9be)
where termsrv.dll?

**Comment by loyejaotdiqr47123** [comment] 2024-07-17 10:03
windows/system32

**Comment by noober120** [comment] 2024-07-17 10:24
> windows/system32

[](url)
[Uploading termsrv.txt…]()

**Comment by noober120** [comment] 2024-07-17 10:25
> windows/system32

#
[termsrv.txt](https://github.com/user-attachments/files/16264015/termsrv.txt)

**Comment by loyejaotdiqr47123** [comment] 2024-07-17 13:07
> > Please, attach your RDPConf screenshot and termsrv.dll.
> 
> ![image](https://private-user-images.githubusercontent.com/175813574/349449095-b632290d-ea10-4b78-99c6-8964ee9ee9be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMjE4NTMsIm5iZiI6MTcyMTIyMTU1MywicGF0aCI6Ii8xNzU4MTM1NzQvMzQ5NDQ5MDk1LWI2MzIyOTBkLWVhMTAtNGI3OC05OWM2LTg5NjRlZTllZTliZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QxMzA1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDExOWM2N2Y0YjcxNTYxNDgxNjg0MDRhNmUzNjNhZjkyNDBlMTgxMzE0ZWIxYTE0OTJlMDMwYzRhOGZiNGVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D5NMVEHQlz8j9G0NOn-HeSvUnYR2cBhHhPr9dp7GoGA) where termsrv.dll?



> > Please, attach your RDPConf screenshot and termsrv.dll.
> 
> ![image](https://private-user-images.githubusercontent.com/175813574/349449095-b632290d-ea10-4b78-99c6-8964ee9ee9be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMjE4NTMsIm5iZiI6MTcyMTIyMTU1MywicGF0aCI6Ii8xNzU4MTM1NzQvMzQ5NDQ5MDk1LWI2MzIyOTBkLWVhMTAtNGI3OC05OWM2LTg5NjRlZTllZTliZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QxMzA1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDExOWM2N2Y0YjcxNTYxNDgxNjg0MDRhNmUzNjNhZjkyNDBlMTgxMzE0ZWIxYTE0OTJlMDMwYzRhOGZiNGVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D5NMVEHQlz8j9G0NOn-HeSvUnYR2cBhHhPr9dp7GoGA) where termsrv.dll?

Missing rdpwrap.dll
Please check your antivirus software.
Antivirus software may remove rdpwrap.dll

**Comment by binarymaster** [comment] 2024-07-17 14:06
Duplicate of #1112.

**Closed as not planned by binarymaster** 2024-07-17 14:06 UTC
Labels: duplicate
