### ISSUE TITLE
Windows 10 Pro version 22H2 SO build 19045.3393 not working

### ISSUE THREAD

**Issue by edo1977** [stascorp/rdpwrap#2337] opened 2023-09-20 10:19 UTC
Hi,

I recently updated my Windows 10 Pro to version 22H2 SO build 19045.3393.

I installed the RDP wrapper everything went OK but it was not working.

I went and replaced the original termsrv with one I found in another thread - termsrv--Win10--22H2--2023-06-28a--10.0.19041.3155--64bit.

The Wrapper diagnostics are in the image.
![wrapper](https://github.com/stascorp/rdpwrap/assets/145363647/d613b56c-5546-4234-a75e-ca28a13cddbf)

I'm able to open 1 remote desktop but if I try a second one it fails.

Can anyone help me?

Thank you

**Comment by sashaqwert** [comment] 2023-09-21 04:12
Duplicate of https://github.com/stascorp/rdpwrap/issues/2257

**Closed as not planned by sashaqwert** 2023-09-21 04:12 UTC
Labels: duplicate

**Comment by edo1977** [comment] 2023-09-21 10:11
Hi @sashaqwert 

I made the other one first by mistake (first time posting) as the thread was for another build. Already deleted it.

No resolution in either.

Now just this one.

Should I re-open it? Don't know how.

Thank you

**Comment by sashaqwert** [comment] 2023-09-21 17:06
> No resolution in either.

Solution: https://github.com/stascorp/rdpwrap/issues/2257#issuecomment-1610785539

You need replace the `rdpwrap.ini` file.

**Comment by edo1977** [comment] 2023-09-22 18:12
Hi,

Thank you. After replacing the .ini, updating and rebooting it's now working fine with multiple users.
