### ISSUE TITLE
Not listening

### ISSUE THREAD

**Issue by No738** [stascorp/rdpwrap#2026] opened 2022-10-22 12:54 UTC
Hi! 
After installing Windows 11 Pro, I tried to install RDP Wrap - it did not work. Despite full support, there is Not Listening status. 
I tried restarting the computer and the termService service via cmd, it doesn't help.
![изображение](https://user-images.githubusercontent.com/68585497/197340012-0fe39b71-f70c-41b8-9603-5dfd6324c502.png)
![изображение](https://user-images.githubusercontent.com/68585497/197340020-0695bd24-a3d5-4b73-a3d8-5bf60fa9ff3f.png)

**Comment by sashaqwert** [comment] 2022-10-22 16:17
One `termsrv.dll` version = ONE opened issue.

**Comment by sashaqwert** [comment] 2022-10-22 16:17
Duplicate of https://github.com/stascorp/rdpwrap/issues/1993

**Closed as not planned by sashaqwert** 2022-10-22 16:17 UTC
Labels: duplicate

**Comment by sashaqwert** [comment] 2022-10-22 16:19
Try:
1. CMD as Administrator
2. `net stop termService`
3. `net start termService`
4. Check RDPConf again.

**Comment by No738** [comment] 2022-10-24 11:43
> 

As I wrote, I have already tried restarting a service. It does not help

**Comment by pedrolucasp** [comment] 2023-02-22 12:45
I'm still dealing with this situation as well, any pointers?

**Comment by sashaqwert** [comment] 2023-02-22 12:54
> I'm still dealing with this situation as well, any pointers?

Try:
1. Download RDP Wrapper 1.6.2 and extract this to any directory.
2. Place `rdpwrap.ini` in the same directory.
3. Open CMD as administrator
4. Execute this commands
```
cd C:\path\to\directory\
rdpwinst -u -k
rdpwinst -i
```
5. Enjoy!

Original message: https://t.me/rdpwrap/49131

**Comment by pedrolucasp** [comment] 2023-02-22 13:00
> > I'm still dealing with this situation as well, any pointers?
> 
> Try:
> 
>     1. Download RDP Wrapper 1.6.2 and extract this to any directory.
> 
>     2. Place `rdpwrap.ini` in the same directory.
> 
>     3. Open CMD as administrator
> 
>     4. Execute this commands
> 
> 
> ```
> cd C:\path\to\directory\
> rdpwinst -u -k
> rdpwinst -i
> ```
> 
>     5. Enjoy!
> 
> 
> Original message: https://t.me/rdpwrap/49131

Will try, we can track back to the original open issue? I didn't realize that this one was closed.
