### ISSUE TITLE
10.0.19045.4780 not supported

### ISSUE THREAD

**Issue by shaoxiao-li** [stascorp/rdpwrap#3254] opened 2024-08-16 05:31 UTC

**Comment by loyejaotdiqr47123** [comment] 2024-08-17 07:13
Please, attach your RDPConf screenshot and termsrv.dll.

**Comment by TeFuirnever** [comment] 2024-08-18 03:09
![image](https://github.com/user-attachments/assets/dbfa8c52-8f00-4603-9e93-58d651fb23de)

**Comment by zicren** [comment] 2024-08-18 15:30
![RDPConf screenshot](https://github.com/user-attachments/assets/fc794ac5-5ed3-4bb7-836d-d5a1b17c5a53)

**Comment by zicren** [comment] 2024-08-18 15:41
Hello, this version (10.0.19045.4780) is not supported after latest updates Windows server 2022
[termsrv.zip](https://github.com/user-attachments/files/16649647/termsrv.zip)

**Comment by loyejaotdiqr47123** [comment] 2024-08-19 14:11
> Hello, this version (10.0.19045.4780) is not supported after latest updates Windows server 2022 [termsrv.zip](https://github.com/user-attachments/files/16649647/termsrv.zip)

Duplicate of #2840

**Closed as not planned** 2024-08-26 10:32 UTC
Labels: duplicate
