### ISSUE TITLE
Windows 11 Home Edition ni_release 10.0.22579.1 DEV

### ISSUE THREAD

**Issue by AstralFlare-owo** [stascorp/rdpwrap#1802] opened 2022-04-06 12:29 UTC
I'm finding about the rdpwrap.ini for Windows 11 Home Edition ni_release 10.0.22579.1.
Here's my "termsrv.ini" -> [termsrv.zip](https://github.com/sebaxakerhtc/rdpwrap.ini/files/8426767/termsrv.zip)

**Comment by sashaqwert** [comment] 2022-04-06 15:47
Duplicate of https://github.com/stascorp/rdpwrap/issues/1781

**Comment by sebaxakerhtc** [comment] 2022-04-07 20:10
> Duplicate of #1781

**Closed as completed by sebaxakerhtc** 2022-04-07 20:10 UTC
