### ISSUE TITLE
Windows 10 22H2 OS Build 19045.3208 not Supported

### ISSUE THREAD

**Issue by brillsense-shailesh** [stascorp/rdpwrap#2287] opened 2023-07-25 05:25 UTC
![image](https://github.com/stascorp/rdpwrap/assets/138963940/c2c62043-6948-468b-8823-ab58991f012d)

**Comment by sashaqwert** [comment] 2023-07-25 17:25
Duplicate of https://github.com/stascorp/rdpwrap/issues/2257

**Closed as not planned by sashaqwert** 2023-07-25 17:25 UTC
