### ISSUE TITLE
Access denied error when running RDPcheck

### ISSUE THREAD

**Issue by GambaGirl** [stascorp/rdpwrap#179] opened 2016-11-06 17:18 UTC
I was successfully using RDPwrapper to log into a Windows PC from OS X (2010 Macbook Air), but then stopped working when I upgraded to 2016 Macbook Air. Upgraded to Windows 10 on the PC, but that was earlier in the summer, and it worked fine between the windows upgrade and the Mac hardware upgrade.

There may have been a Windows software update after that, but unfortunately I can't remember. This has been going on a while, and I can't seem to figure it out on my own, so I'm reaching out here.

I've reinstalled everything on both machines and followed the setup instructions. When I run rdpcheck locally on the windows machine, I get an "Access is denied" error.

The windows machine is not connected to any network, so I'm not using any Microsoft services they want to initiate at login. And I admit to being a complete Windows neophyte. I do the bare minimum to run the app I need over there. 

It seems like it must be a login setting, but with my limited knowledge can't figure out what it is. Any suggestions would be much appreciated.

**Comment by GambaGirl** [comment] 2016-11-06 17:22
But I should have mentioned how great rdpwrap was for helping me access the windows machine from my Macbook. Made one aspect of my work much easier. I really miss it!

**Comment by binarymaster** [comment] 2016-11-19 20:49
Try reinstalling RDP Wrapper on Windows machine again, I've been updated INI file with latest build signatures just now.

Note that it may require internet connection to download updated INI file.

**Comment by GambaGirl** [comment] 2016-11-19 21:22
OK thanks! I was just starting to stew about what my alternatives are.
Hopefully this works. I probably won't be able to work on it until the
middle of the week. Stay tuned.

**Comment by GambaGirl** [comment] 2016-11-25 16:57
I just reinstalled 1.6.1 - that was the latest version I found. I had already installed that a few weeks ago, and the timestamps on the version I just downloaded are not that recent - July and August of 2016. I mention this in case I'm not getting what you've recently updated.

I uninstalled then reinstalled rdpwrap, in one more attempt to make sure I've done the right thing, to no avail.

To recap - I can successfully install rdpwrap on my windows machine, but when I run rdpcheck, I get an "Access Denied" screen after entering my password in the windows login screen.

I am running version 1607, OS build 14393.105 of Windows 10 Home - 64 bit version.

**Comment by GambaGirl** [comment] 2016-11-25 20:06
In desperation, went back to older version of Windows 10 - 1607 build 14393.0. RDPcheck still doesn't work, but tried to connect from Macbook anyway, and it worked. Not sure why - totally perplexed. But at least I'm back to my old work environment. This is with RDPwrap v1.6.1, FWIW.

**Comment by GambaGirl** [comment] 2016-11-25 20:07
To be clear - when I run rdpcheck, I get "Access Denied" from Windows. The program itself seemingly runs fine.

**Comment by binarymaster** [comment] 2016-11-25 20:12
Closing as a duplicate of issue #37.

**Closed by binarymaster** 2016-11-25 20:12 UTC

**Comment by palxex** [comment] 2017-11-29 19:21
Just experienced same error on Windows 10 pro( fall creator ). AND, when I try again on a up-to-date windows 7 laptop, the same error happened again. Seems It has no relation with windows 10 or tablet.
