### ISSUE TITLE
Request for Version [10.0.19041.3570] INI Configuration File

### ISSUE THREAD

**Issue by rKzenta** [stascorp/rdpwrap#2401] opened 2023-11-14 03:48 UTC
![image](https://github.com/stascorp/rdpwrap/assets/50146922/f168614d-9b6a-4ca2-b3b7-f3e588eb727b)

**Comment by sashaqwert** [comment] 2023-11-15 07:25
Duplicate of https://github.com/stascorp/rdpwrap/issues/2359

**Closed as not planned by sashaqwert** 2023-11-15 07:25 UTC
Labels: duplicate
