### ISSUE TITLE
19041.789 rdp check shows not correctly

### ISSUE THREAD

**Issue by SocialistDalao** [stascorp/rdpwrap#1365] opened 2021-04-08 04:10 UTC
![image](https://user-images.githubusercontent.com/44405722/113967278-3a2acd80-9863-11eb-9ddf-a33bc1459077.png)
![image](https://user-images.githubusercontent.com/44405722/113967306-49118000-9863-11eb-8149-4dfd6653c391.png)

The RDP check shows that it successfully connects to the host, but i can do nothing in it because it shows not correctly and the only thing i can do is controlling the host to shut down, sleep or restart.

**Comment by abvgdeyoj** [comment] 2021-04-08 21:55
![rdpwrapscreen2021](https://user-images.githubusercontent.com/1658871/114100624-3fbcfd80-98cd-11eb-915c-1a1c7e041553.png)
![rdpwrapconsole2021](https://user-images.githubusercontent.com/1658871/114101309-341e0680-98ce-11eb-8169-abc751bf0a51.png)

**Comment by 844655441** [comment] 2021-04-17 13:57
can you provide a config file for 19041.789 ? there is listen but not support in my PC

**Comment by sebaxakerhtc** [comment] 2022-03-30 13:09
Duplicate of https://github.com/stascorp/rdpwrap/issues/1317

**Closed as completed by sebaxakerhtc** 2022-03-30 13:09 UTC
