### ISSUE TITLE
19042.1526 ini

### ISSUE THREAD

**Issue by Mozharova** [stascorp/rdpwrap#1739] opened 2022-02-21 10:55 UTC
Good mornibg
I need: 19042.1526 ini, thanks/

**Comment by sashaqwert** [comment] 2022-02-21 13:47
RDPConf (or RDP_CnC) screenshot, please!

**Comment by sashaqwert** [comment] 2022-02-21 13:49
Duplicate of https://github.com/stascorp/rdpwrap/issues/1697

**Closed as completed** 2022-02-21 20:09 UTC

**Comment by Mozharova** [comment] 2022-02-21 20:19
![image](https://user-images.githubusercontent.com/92950657/155021477-91ac0b31-62c2-4e4a-94cf-2ab5482ffab8.png)

**Comment by Mozharova** [comment] 2022-02-21 20:38
i found ini here/ thanks
