### ISSUE TITLE
19044.1466 supported  ?

### ISSUE THREAD

**Issue by nattlip** [stascorp/rdpwrap#1685] opened 2022-01-14 09:48 UTC
is 19044.1466  21h2 supported yet ? or does update from working 19044 .1415 to 19044.1966 need a new rdpwrap.ini ?

**Comment by sebaxakerhtc** [comment] 2022-01-14 13:52
> is 19044.1466 21h2 supported yet ? or does update from working 19044 .1415 to 19044.1966 need a new rdpwrap.ini ?

Did you see your termsrv.dll version before creating issue?

Duplicate of https://github.com/stascorp/rdpwrap/issues/1630

**Closed as completed by sebaxakerhtc** 2022-01-14 13:52 UTC

**Comment by nattlip** [comment] 2022-01-14 16:10
didnt realize if termsrv.dll keeps same version no new ini is needed.  i asked this before i update and rdpwrap doesnt work 
anymore

**Comment by sebaxakerhtc** [comment] 2022-01-14 18:22
> didnt realize if termsrv.dll keeps same version no new ini is needed. i asked this before i update and rdpwrap doesnt work anymore

Show your RDPConf screenshot

**Comment by nattlip** [comment] 2022-01-14 21:13
i get it now . the the version seen in the rdpconf is the termsvr.dll version , not the windows version.

**Comment by sebaxakerhtc** [comment] 2022-01-14 21:16
> i get it now . the the version seen in the rdpconf is the termsvr.dll version , not the windows version.

Windows version doesn't matter, only termsrv.dll version matter

**Comment by nattlip** [comment] 2022-01-14 21:16
i get it the the version seen in the rdpconf is the termsvr.dll version , not the windows version. the january update of windows 10 doesnt change that 19041.1387 stays  the same updating to 19044.1466

**Comment by sebaxakerhtc** [comment] 2022-01-14 21:17
> i get it the the version seen in the rdpconf is the termsvr.dll version , not the windows version. the january update of windows 10 doesnt change that 19041.1387 stays the same updating to 19044.1466

Yes.
Windows version doesn't matter!!!
