### ISSUE TITLE
10.0.22621.1928 fully supported but not working

### ISSUE THREAD

**Issue by Dassie2019** [stascorp/rdpwrap#2834] opened 2024-05-30 08:43 UTC
![Screenshot (14)](https://github.com/stascorp/rdpwrap/assets/54889477/415c5f54-41bd-4036-a354-1867a24fa974)
RDP wrapper showing fully supported but still can't connect multiple users

Please help.

**Comment by loyejaotdiqr47123** [comment] 2024-05-31 11:32
@Dassie2019 Please upload termsrv.dll

**Comment by binarymaster** [comment] 2024-06-03 17:16
Duplicate of #2258.

**Closed as not planned by binarymaster** 2024-06-03 17:16 UTC
Labels: duplicate
