### ISSUE TITLE
my rdp conf is all green but i cannot login

### ISSUE THREAD

**Issue by MrDOntDIe** [stascorp/rdpwrap#1967] opened 2022-08-27 02:41 UTC
I launch the remote desktop and i get to the login screen with no login bars to enter password

**Comment by MrDOntDIe** [comment] 2022-08-27 02:41
![image](https://user-images.githubusercontent.com/101935753/187011182-8b8cf8c8-08a9-46c9-bc61-aa6fdf58d7b5.png)

**Comment by sashaqwert** [comment] 2022-08-27 06:33
Please, [convert your Microsoft account to a local account](https://support.microsoft.com/en-us/windows/switch-your-windows-10-device-to-a-local-account-eb7e78a9-88ee-9bc3-8f06-831b56e339fd).

**Comment by sashaqwert** [comment] 2022-08-27 06:34
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881

**Comment by sashaqwert** [comment] 2022-08-27 06:35
One `termsrv.dll` version = one opened issue...

**Closed as not planned by sashaqwert** 2022-08-27 06:34 UTC
