### ISSUE TITLE
Windows 10 Ver 2004 OS Build 19041.329 not working

### ISSUE THREAD

**Issue by StarfighterJ** [stascorp/rdpwrap#1087] opened 2020-06-10 22:09 UTC
I am getting:  a not listening and not Supported> FYI I just got this Feature 2004 update today. and the Autoupdate did not Fix Issue. Please help Thank you.

**Comment by andresamador** [comment] 2020-06-11 00:27
I have the 2004 update and mine shows wrapper state installed, service state running, and listening state as listening but then says not supported in red.

**Comment by andresamador** [comment] 2020-06-11 00:41
> I am getting: a not listening and not Supported> FYI I just got this Feature 2004 update today. and the Autoupdate did not Fix Issue. Please help Thank you.

Found the settings

[10.0.19041.84-SLInit]
bInitialized.x86      =CF920
bServerSku.x86        =CF924
lMaxUserSessions.x86  =CF928
bAppServerAllowed.x86 =CF930
bRemoteConnAllowed.x86=CF938
bMultimonAllowed.x86  =CF93C
ulMaxDebugSessions.x86=CF940
bFUSEnabled.x86       =CF944

bInitialized.x64      =103FF8
bServerSku.x64        =103FFC
lMaxUserSessions.x64  =104000
bAppServerAllowed.x64 =104008
bRemoteConnAllowed.x64=104010
bMultimonAllowed.x64  =104014
ulMaxDebugSessions.x64=104018
bFUSEnabled.x64       =10401C

[10.0.19041.84]
LocalOnlyPatch.x86    =1
LocalOnlyOffset.x86   =B46B9
LocalOnlyCode.x86     =jmpshort
LocalOnlyPatch.x64    =1
LocalOnlyOffset.x64   =87611
LocalOnlyCode.x64     =jmpshort
SingleUserPatch.x86   =1
SingleUserOffset.x86  =3AD27
SingleUserCode.x86    =Zero
SingleUserPatch.x64   =1
SingleUserOffset.x64  =0BF0C
SingleUserCode.x64    =Zero
DefPolicyPatch.x86    =1
DefPolicyOffset.x86   =3D7D9
DefPolicyCode.x86     =CDefPolicy_Query_eax_ecx
DefPolicyPatch.x64    =1
DefPolicyOffset.x64   =17ED5
DefPolicyCode.x64     =CDefPolicy_Query_eax_rcx
SLInitHook.x86        =1
SLInitOffset.x86      =66658
SLInitFunc.x86        =New_CSLQuery_Initialize
SLInitHook.x64        =1
SLInitOffset.x64      =1BDFC
SLInitFunc.x64        =New_CSLQuery_Initialize

**Comment by andresamador** [comment] 2020-06-11 00:42
[rdpwrap.txt](https://github.com/stascorp/rdpwrap/files/4761945/rdpwrap.txt)

**Comment by affinityv** [comment] 2020-06-11 18:00
Same file as [here](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini).

**Comment by StarfighterJ** [comment] 2020-06-11 18:08
> rdpwrap.txt  Going to be a little dumb here is this this New rdpwrap.ini file to be? meaning do I replace it and rename it to rdpwrap.ini?

**Comment by andresamador** [comment] 2020-06-11 18:10
Would let me.uoad the ini file so I changed the
Extension

Andres Amador
Director of Sales
Florida's Choice Contracting
cell: 786.570.3863

Statement of Confidentiality. This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

Sent from Samsung Galaxy smartphone.
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by StarfighterJ** [comment] 2020-06-11 18:23
Ok that makes Since Usually the .ini File is uploaded in a rdpwrap.zip file so it can be uploaded to the github. but thanks :) for help

**Comment by andresamador** [comment] 2020-06-11 18:25
It shows up all green and supported on my system just haven't had a chance to try it out

Andres Amador
Director of Sales
Florida's Choice Contracting
cell: 786.570.3863

Statement of Confidentiality. This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

Sent from Samsung Galaxy smartphone.
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by StarfighterJ** [comment] 2020-06-11 18:30
Anyone know how to get a hold of asmtron to fix the Autouppdater.?
Automatic RDP Wrapper installer and updater // asmtron (07-06-2020)

**Comment by robbak** [comment] 2020-06-11 20:56
Probably post an issue or pull request on his GitHub repo.

**Comment by StarfighterJ** [comment] 2020-06-12 13:59
> Probably post an issue or pull request on his GitHub repo.
> …

He does not have Issues opened on his GitHub Repo

**Comment by robbak** [comment] 2020-06-12 14:11
I noticed that. But he is active - he committed an update to his repo today. Have you checked to see whether it has fixed the problem for you?

https://github.com/asmtron/rdpwrap/commit/7797206c7c1c7351dc3e2054b94d065288b30a1c

Looking at the mess that people make of the issues system here - jumping on other's issues, never closing their issues when they've got it working - it isn't surprising that he wouldn't turn on issues. But if you have a working .ini file, you could make it available in a pull request.

**Comment by StarfighterJ** [comment] 2020-06-12 16:35
Yes I did and it works TY :)

**Comment by asmtron** [comment] 2020-06-12 17:21
can please someone upload the Win10 32Bit termsrv.dll 10.0.19041.84 (x86)

[stascorp/rdpwrap](https://github.com/edtrejo/rdpwrap) is the main repo and the right place to open issues. Open issues also on forked repos makes too much confusion.

**Comment by TheArgentinian** [comment] 2020-06-15 21:28
> 
> 
> > I am getting: a not listening and not Supported> FYI I just got this Feature 2004 update today. and the Autoupdate did not Fix Issue. Please help Thank you.
> 
> Found the settings
> 
> [10.0.19041.84-SLInit]
> bInitialized.x86 =CF920
> bServerSku.x86 =CF924
> lMaxUserSessions.x86 =CF928
> bAppServerAllowed.x86 =CF930
> bRemoteConnAllowed.x86=CF938
> bMultimonAllowed.x86 =CF93C
> ulMaxDebugSessions.x86=CF940
> bFUSEnabled.x86 =CF944
> 
> bInitialized.x64 =103FF8
> bServerSku.x64 =103FFC
> lMaxUserSessions.x64 =104000
> bAppServerAllowed.x64 =104008
> bRemoteConnAllowed.x64=104010
> bMultimonAllowed.x64 =104014
> ulMaxDebugSessions.x64=104018
> bFUSEnabled.x64 =10401C
> 
> [10.0.19041.84]
> LocalOnlyPatch.x86 =1
> LocalOnlyOffset.x86 =B46B9
> LocalOnlyCode.x86 =jmpshort
> LocalOnlyPatch.x64 =1
> LocalOnlyOffset.x64 =87611
> LocalOnlyCode.x64 =jmpshort
> SingleUserPatch.x86 =1
> SingleUserOffset.x86 =3AD27
> SingleUserCode.x86 =Zero
> SingleUserPatch.x64 =1
> SingleUserOffset.x64 =0BF0C
> SingleUserCode.x64 =Zero
> DefPolicyPatch.x86 =1
> DefPolicyOffset.x86 =3D7D9
> DefPolicyCode.x86 =CDefPolicy_Query_eax_ecx
> DefPolicyPatch.x64 =1
> DefPolicyOffset.x64 =17ED5
> DefPolicyCode.x64 =CDefPolicy_Query_eax_rcx
> SLInitHook.x86 =1
> SLInitOffset.x86 =66658
> SLInitFunc.x86 =New_CSLQuery_Initialize
> SLInitHook.x64 =1
> SLInitOffset.x64 =1BDFC
> SLInitFunc.x64 =New_CSLQuery_Initialize

Doesn't work.

**Comment by sk-lau** [comment] 2020-06-16 07:25
I have upgraded to Windows 10 version 2004. RDPWrapper no longer works. 

termsrv.dll is version 10.0.19041.84

I can confirm the above rdpwrap.ini codes does NOT work !

Does anyone have any idea?

**Comment by hdrsistemas** [comment] 2020-06-17 22:10
I have upgraded to Windows 10 version 2004. RDPWrapper WORK.

Windows 10 is version 10.0.19041.329

thanks to andresamador

**Comment by sk-lau** [comment] 2020-06-18 03:24
> I have upgraded to Windows 10 version 2004. RDPWrapper WORK.
> 
> Windows 10 is version 10.0.19041.329
> 
> thanks to andresamador

Hi, can you tell us exactly how you get this to work? 

I have use the rdpwrap.txt that andreasamador attached and it doesnt work. I'm running 64 bit  Windows 10 ver 2004

Thanks

**Comment by affinityv** [comment] 2020-06-18 03:48
https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini

**Comment by sk-lau** [comment] 2020-06-18 08:02
> https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini

Yes this is working (AWESOME) for Windows 10 version 2004 HOME version. Thanks

I'm still unable to get this to work on Windows 10 version 2004 PRO version 64bit

Any feedback from you guys ?

**Comment by robbak** [comment] 2020-06-18 08:36
That is suprising.

Can you confirm that both your windows home and you windows pro computers are using the same version of termsrv.dll? You can find the versions by running the rdpconf program, or by finding termsrv.dll in Windows/System32 and getting its properties from the right-click menu.

**Comment by affinityv** [comment] 2020-06-18 14:50
Look to Windows Defender and/or AV/security "protections" interfering....

**Comment by sk-lau** [comment] 2020-06-18 15:47
> That is suprising.
> 
> Can you confirm that both your windows home and you windows pro computers are using the same version of termsrv.dll? You can find the versions by running the rdpconf program, or by finding termsrv.dll in Windows/System32 and getting its properties from the right-click menu.

Both are version 10.0.19041.84

**Comment by sk-lau** [comment] 2020-06-18 15:50
> Look to Windows Defender and/or AV/security "protections" interfering....

I have turn off antivirus and firewall still cannot connect to the Pro machine

However on the Home machine even with anti virus turn on I can rdp to it. The error message are as below 👎 
![RDP](https://user-images.githubusercontent.com/30503455/85042990-73079200-b1be-11ea-9557-f7b929839977.PNG)

**Comment by affinityv** [comment] 2020-06-18 16:10
Turning off AV will help BEFORE it interferes with settings and files.... it may have already taken out RDP due to it's negligence.

**Comment by ForwardUntoDawn** [comment] 2020-06-18 16:15
> https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini
**FYI -**
This sorted the [not supported] issue for me on Windows 10 2004 v10.0.19041.329
I'm back up and running - Thanks for the assist dude!  You the man.

**Comment by rafaferreirasantos** [comment] 2020-06-18 19:51
Windows 10 Ver 2004 OS Build 19041.329 not working as well.
64 bits

**Comment by ForwardUntoDawn** [comment] 2020-06-18 20:24
@zecaloteiro 
I reran the v1.6.2 installer following the 2004 update to Windows 10 in addition to swapping in the new INI, if that helps you out any.

**Comment by affinityv** [comment] 2020-06-18 21:44
@zecaloteiro What version does `RDPConf.exe` show?

**Comment by VISHALVODRO** [comment] 2020-06-20 17:50
OK, here's what WORKED FOR ME 100%

**[Basic Information]**
Windows-10 Enterprise x64
Version : 2004 [19041.329]

RDPConf.exe
Wrapper State : Installed
Service State : Running
Listener State : Listening
ver. 1.5.0.0
ver. 10.0.19041.84
[Fully Supported]

**[Actions]**
1. Allow RDWrap in Firewall/Antivirus.

2. REPLACE rdpwrap.ini with the following [got this data from above here only]
[rdpwrap.txt](https://github.com/stascorp/rdpwrap/files/4808420/rdpwrap.txt) (Must rename the file extension as .ini before replacing)

3. Run RDPConf.exe
   Uncheck : single session per user
   > OK.

4. Run GPEDIT.MSC
Go To :
      Computer Configuration
      Administrative Templates
      Windows Components
      Remote Desktop Services
      Remote Desktop Session Host
      Connections
      Limit number of connections
      > Enabled
      > RD Maximum Connections allowed : 999999
      > OK

Reboot Computer

5. Try NOW

**Comment by affinityv** [comment] 2020-06-20 19:56
Your rdpwrap.txt file is the same as my [rdpwrap.ini](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini), except your file is missing the "required" blank line at the end (which I think is perhaps not really required as lost of people have said it is (the original ini file of the project doesn't have a blank line at the end).  What is definitely importantly is the DOS line endings for the file.

**Comment by VISHALVODRO** [comment] 2020-06-21 05:01
I didn't do any individual modifications to the file. I too got that file from here only. And I had to upload as text file only since you can't upload INI file here. So I had to change the extension.

Hope it works end of the day...

**Comment by zjuchenyuan** [comment] 2020-06-21 07:03
@VISHALVODRO works for me, thanks!

**Comment by llccd** [comment] 2020-06-21 15:46
Not fully working on my computers with enterprise version. I can only connect first time successfully, after that RDP seems broken.  

I got following error on client:
```
Your Remote Desktop Services session has ended, possibly for one of the following reasons:

The administrator has ended the session.
An error occurred while the connection was being established.
A network problem occurred.

For help solving the problem, see "Remote Desktop" in Help and Support.
```
Corresponding eventlog on server:
```
The device Microsoft Remote Display Adapter (location (unknown)) is offline due to a user-mode
driver crash. Windows will attempt to restart the device 5 more times. Please contact the device
manufacturer for more information about this problem.
```

**Comment by sk-lau** [comment] 2020-06-22 03:24
> Not fully working on my computers with enterprise version. I can only connect first time successfully, after that RDP seems broken.
> 
> I got following error on client:
> 
> ```
> Your Remote Desktop Services session has ended, possibly for one of the following reasons:
> 
> The administrator has ended the session.
> An error occurred while the connection was being established.
> A network problem occurred.
> 
> For help solving the problem, see "Remote Desktop" in Help and Support.
> ```
> 
> Corresponding eventlog on server:
> 
> ```
> The device Microsoft Remote Display Adapter (location (unknown)) is offline due to a user-mode
> driver crash. Windows will attempt to restart the device 5 more times. Please contact the device
> manufacturer for more information about this problem.
> ```

I have the same error messages as yours

Please remove RDPWRAP and enable normal RDP connection and see if it gives you the same error

I suspect Win 2004 updates have corrupted RDP services so it doesn't work anymore

**Comment by llccd** [comment] 2020-06-22 06:37
> 
> I have the same error messages as yours
> 
> Please remove RDPWRAP and enable normal RDP connection and see if it gives you the same error
> 
> I suspect Win 2004 updates have corrupted RDP services so it doesn't work anymore

Same problem without rdpwrap. Seems there is something wrong with RemoteFX display hardware acceleration (HOME version does NOT support this), upgrading driver of display adapters may help.

**Comment by sk-lau** [comment] 2020-06-23 04:37
So it would appear the problem is not RDPWrapper but the Windows update 2004 itself

I'm using VirtualBox and am already running the latest VB graphic driver and still not working

Does anyone manage to get RDPWrapper to  to work with Windows 10 update 2004 PRO version ?


> > I have the same error messages as yours
> > Please remove RDPWRAP and enable normal RDP connection and see if it gives you the same error
> > I suspect Win 2004 updates have corrupted RDP services so it doesn't work anymore
> 
> Same problem without rdpwrap. Seems there is something wrong with RemoteFX display hardware acceleration (HOME version does NOT support this), upgrading driver of display adapters may help.

**Comment by ForwardUntoDawn** [comment] 2020-06-23 14:23
@sk-lau 
Definitely working fine here post 2004 update.
The 2020-06-18 INI file provided by **affinityv** above coupled with a re-install of the wrapper put the box back to green.

![Win10-2004](https://user-images.githubusercontent.com/23408644/85415495-6034ea80-b53b-11ea-8deb-8ea996c1fe3c.JPG)
![RDP-2020-06-23](https://user-images.githubusercontent.com/23408644/85415633-8bb7d500-b53b-11ea-8de9-882e1003ddab.JPG)

**Comment by llccd** [comment] 2020-06-23 15:32
@sk-lau 
For me the problem solved with following step:

1.    Open the Edit Group Policy tool from Control Panel or use the Windows Search dialog (Windows Key + R, then type in gpedit.msc)
2.    Browse to: Local Computer Policy\Computer Configuration\Administrative Templates\Windows Components\Remote Desktop Services\Remote Desktop Session Host\Remote Session Environment
3.    Then change “Use hardware graphics adapters for all Remote Desktop Services sessions” to "Not Configured"
4.    Reboot the computer

**Comment by TheArgentinian** [comment] 2020-06-23 22:26
> 
> 
> @sk-lau
>     3. Then change “Use hardware graphics adapters for all Remote Desktop Services sessions” to "Not Configured"

I already had that option as "not configured" 

:(

**Comment by sk-lau** [comment] 2020-06-24 07:34
> > @sk-lau
> > 3. Then change “Use hardware graphics adapters for all Remote Desktop Services sessions” to "Not Configured"
> 
> I already had that option as "not configured"
> 
> :(

Set it to DISABLED then it works for me !!! Thanks to @llccd  :)

Is it all Windows 10 Pro machine will have this problem ?

**Comment by ForwardUntoDawn** [comment] 2020-06-24 14:01
> > > @sk-lau
> > > 3. Then change “Use hardware graphics adapters for all Remote Desktop Services sessions” to "Not Configured"
> > 
> > 
> > I already had that option as "not configured"
> > :(
> 
> Set it to DISABLED then it works for me !!! Thanks to @llccd :)
> 
> Is it all Windows 10 Pro machine will have this problem ?
@sk-lau 
That being the case your issue is/was very likely due to the specific graphics hardware / related drivers on your device, not whatever version or edition of Windows is installed.

**Comment by Somebodyisnobody** [comment] 2020-07-18 21:50
> 
> 
> > > @sk-lau
> > > 3. Then change “Use hardware graphics adapters for all Remote Desktop Services sessions” to "Not Configured"
> > 
> > 
> > I already had that option as "not configured"
> > :(
> 
> Set it to DISABLED then it works for me !!! Thanks to @llccd :)
> 
> Is it all Windows 10 Pro machine will have this problem ?

Seems as all machines where Windows decides to use hardware graphics adapters have this issue. It appeared on my machine after upgrading to 2004. I have a GeForce GTX 1070. Explicitly disabling the option worked for me. Microsoft forums couldn't help but I found this issue here. Thank you so much!

**Comment by Dbart1** [comment] 2020-07-29 08:28
Window 10 pro machine, new OS so has all the recent updates.   I adding the ini file (read somewhere was a space at the end or beginning that may have been missing), took the one from above and just copied and pasted the to text document then renamed it and moved over.  Deleted other file.  I just did this update rdpwrap_for_10.0.19041.84_fix_files and still nothing.  It is all green except nothing for supported.  When I run remote desktop it says it is too many users.  Please help, need it asap.

**Comment by mlvbible** [comment] 2020-09-03 20:37
You have to use 2 different user accounts for those who haven't figured it out. 

I have Win 10 Pro 2004 current updates and with the  {affinityv commented on Jun 20} .ini file installed and all is good. 

Thanks affinityv for helping us all out.

**Comment by mlvbible** [comment] 2020-09-03 20:37
You have to use 2 different user accounts for those who haven't figured it out. 

I have Win 10 Pro 2004 current updates and with the  {affinityv commented on Jun 20} .ini file installed and all is good. 

Thanks affinityv for helping us all out.

**Comment by mlvbible** [comment] 2020-09-10 14:23
Please someone take over this project, us non-profits can't afford Windows Server, setup & Calc's.

**Comment by mlvbible** [comment] 2020-09-10 14:24
Please someone take over this project, us non-profits can't afford Windows Server, setup & Calc's.

**Comment by GCTSOL** [comment] 2020-09-10 19:02
Ok so I have it working to allow remote connection using RDPWrapper but not sure what ini file I am using.  But my problem is a little different.  I can make the connection but it logs off the local user. 

SYSINFO:
Windows 10 Pro
Version 10.0.19041

 I have done all the following:
    Allow RDWrap in Firewall/Antivirus.

    REPLACE rdpwrap.ini with the following [got this data from above here only]
    rdpwrap.txt (Must rename the file extension as .ini before replacing)

    Run RDPConf.exe
    Uncheck : single session per user

        OK.

    Run GPEDIT.MSC
    Go To :
    Computer Configuration
    Administrative Templates
    Windows Components
    Remote Desktop Services
    Remote Desktop Session Host
    Connections
    Limit number of connections

        Enabled
        RD Maximum Connections allowed : 999999
        OK

Reboot Computer

![ch_RDPConf](https://user-images.githubusercontent.com/71097438/92786942-4bb00380-f36e-11ea-8cb5-6df957ac706e.PNG)

**Comment by affinityv** [comment] 2020-09-10 20:22
@GCTSOL, you are better off logging in as one user and pivotting to the other, perhaps even shadowing the session.  You can't rely upon /not/ taking over an existing session when you login with a username that is already logged in.

**Comment by GCTSOL** [comment] 2020-09-11 12:30
I have created a second user that needs to be able to login while not affecting the other user. User 1 logged in locally needs to continue running system as point of sale while user 2 logs in remotely doing financial and banking without user 1 being able to see what user 2 is doing?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by holmrn1** [comment] 2020-09-14 11:48
> 
> 
> > https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini
> 
> Yes this is working (AWESOME) for Windows 10 version 2004 HOME version. Thanks
> 
> I'm still unable to get this to work on Windows 10 version 2004 PRO version 64bit
> 
> Any feedback from you guys ?

Works on the 18363.1016 w10pro
👍👍👍

**Comment by GCTSOL** [comment] 2020-09-15 16:00
Still having issues with getting this to work.  When the remote user (user2) logs on, it logs off the local user (user1) and the local user can see everything that the remote user.  Using the Ini File from above post:
https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini

Windows 10 Pro - Version 10.0.19041 Build 19041

Again, I am able to establish the remote connection with the  username (user2) but it logs off local (user1) making it unable for both to use concurrently.  I have uninstalled, reinstalled, copied ini after reinstall, set gpedit to max users.  I cannot get this to work no matter what i do on this version windows without logging off the local user and the session being seen on the local system.  
Is it possible I need to make some changes in the registry or doe anyone have a working termserver.dll file that is working for doing this that they can send for me to attempt replacing original?

Here are the settings I have set on RDPConf.



![ch_RDPConf](https://user-images.githubusercontent.com/71097438/93235051-ad8fb500-f742-11ea-9a3b-00632ad18941.PNG)

**Comment by robbak** [comment] 2020-09-15 23:05
Someone else reported something similar, but the so-called local user was
not local at all-they were connecting using TeamViewer, and TeamViewer was
switching from the local user session to the rdp session.

Don't try to test rdp using TeamViewer. It doesn't work.

**Comment by viktor495** [comment] 2020-09-23 21:12
Thank god that worked for me, thanks @asmtron
Win10 Enterprise Ver 2004 10.0.19041.84
https://github.com/asmtron/rdpwrap/blob/master/binary-download.md

**Comment by demontes96** [comment] 2020-10-02 14:10
@GCTSOL I have exactly the same problem, i have followed every step you have mentioned, but i still can't allow simultaneos user login, have you already found a solution? I have Windows 10 pro (19041.508)

**Comment by pcislocked** [comment] 2020-10-04 16:06
(just a feedback - not a solution) Fresh install of Win10 pro 2004 x64(tr). Wrapper did install, everything was green but it was saying [not supported]. 

When I try to connect via RDP, it says another user is connected and if i connect, it will disconnect. When I click yes, a warning pops up at the console session(another user, actually my sister watching Netflix.). She says yes, and she gets disconnected. Now i'm connected but she can see and interact with my root user. What I want to achieve is I connect to my own session while she keeps his Netflix running at the actual computer, so I can manage my always-on script stuff at that computer.

When I connect while no one else is using the PC with no users logged in, it straight up works, but again, monitor is showing exactly what I'm doing. you know what i mean 

Tried .ini files as well as some gpedit steps mentionead above with tons of reboots but no luck. Seems like Microsoft done some tinkering to prevent pro users from creating multiple sessions im not sure though

**Comment by VincentChong123** [comment] 2020-10-25 04:03
Thanks @VISHALVODRO, 

> RD Maximum Connections allowed : 999999

your solution works for me 
windows 10 Pro ver 2004 (19041.572)

**Comment by ghost** [comment] 2020-11-11 03:29
> @GCTSOL, you are better off logging in as one user and pivotting to the other, perhaps even shadowing the session. You can't rely upon /not/ taking over an existing session when you login with a username that is already logged in.

I cannot get shadowing to work. Is there more detailed instructions on setting it up?

**Comment by danilosis** [comment] 2020-12-11 20:47
@viktor495 Muito obrigado. Obrigado a todos, resolveu meu problema com versão do Windows 10 20H2. Thank You community!

**Comment by sebaxakerhtc** [comment] 2022-06-20 10:40
Applicable to https://github.com/stascorp/rdpwrap/issues/1004

**Closed as completed by sebaxakerhtc** 2022-06-20 10:40 UTC
