### ISSUE TITLE
Fully supported and doesn't work rdpwrapper

### ISSUE THREAD

**Issue by amadorvz** [stascorp/rdpwrap#1460] opened 2021-07-05 10:40 UTC
![image](https://user-images.githubusercontent.com/79546520/124459012-fd04a780-dd8d-11eb-82cc-83608b986073.png)
Hi, as u can see I have rdp with full green and working 
![image](https://user-images.githubusercontent.com/79546520/124459129-1d346680-dd8e-11eb-92b1-44c2940382ff.png)
But when I try to connect to user "prueba tpv", it doesn't work, I need to close my session in usuario.

**Comment by amadorvz** [comment] 2021-07-05 10:41
![image](https://user-images.githubusercontent.com/79546520/124459280-494fe780-dd8e-11eb-8744-ee3792666ef1.png)
my w10 and rdp versions:

**Comment by sebaxakerhtc** [comment] 2021-10-27 11:29
> But when I try to connect to user "prueba tpv", it doesn't work, I need to close my session in usuario

Did you try switch to NLA?

**Comment by sebaxakerhtc** [comment] 2022-04-27 15:04
Duplicate of https://github.com/stascorp/rdpwrap/issues/872

**Closed as completed by sebaxakerhtc** 2022-04-27 15:04 UTC
