### ISSUE TITLE
Version 20H2 19042.1237 Not listening [Not supported]

### ISSUE THREAD

**Issue by C2usjb01** [stascorp/rdpwrap#1621] opened 2021-11-16 01:34 UTC
Edition	Windows 10 Home
Version	20H2
Installed on	‎5/‎21/‎2021
OS build	19042.1237
Experience	Windows Feature Experience Pack 120.2212.3530.0
Wrapper state: Installed ver. RDP Wrapper Library v1.6.2
Listener state: Not listening [Not supported]
RDP checker Socket Connection Failed.

**Comment by FX-FX** [comment] 2021-11-16 07:31
[10.0.19043.1237]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=89D81
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0CB26
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=19105
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=1E98C
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.19043.1237-SLInit]
bInitialized.x64 =107108
bServerSku.x64 =10710C
lMaxUserSessions.x64 =107110
bAppServerAllowed.x64 =107118
bRemoteConnAllowed.x64=107120
bMultimonAllowed.x64 =107124
ulMaxDebugSessions.x64=107128
bFUSEnabled.x64 =10712C


以上放到rdpwrap.ini文件后，重启就可以了

**Comment by sebaxakerhtc** [comment] 2021-11-16 19:16
Duplicate of https://github.com/stascorp/rdpwrap/issues/1509

**Closed as completed by sebaxakerhtc** 2021-11-16 19:16 UTC
Labels: duplicate

**Comment by C2usjb01** [comment] 2021-11-16 19:42
#1509 is for Windows 10 Version 21H1 for x64-based Systems (KB4023057)
10.0.19041.1081 and 10.0.19041.1202.

MInes is different. Does that matter?

**Comment by sebaxakerhtc** [comment] 2021-11-16 19:51
> MInes is different. Does that matter?

Yor Windows version doesn't matter. Version of termsrv.dll matter.
Attach the screenshot of rdpconf. Is it shows 19042.1237?

**Comment by C2usjb01** [comment] 2021-11-16 20:00
![Screenshot 2021-11-16 145920](https://user-images.githubusercontent.com/94012901/142057043-8f2fda99-071d-4fb5-9c51-6f9968ad6b6f.jpg)

**Comment by sebaxakerhtc** [comment] 2021-11-16 20:14
> 
> 
> 

So, as you can see - your termsrv.dll version is 1202, as i said you [here](https://github.com/stascorp/rdpwrap/issues/1621#issuecomment-970589849)

**Comment by C2usjb01** [comment] 2021-11-16 20:18
> > 
> 
> So, as you can see - your termsrv.dll version is 1202, as i said you [here](https://github.com/stascorp/rdpwrap/issues/1621#issuecomment-970589849)

Thanks. After I append. What do I do?

**Comment by sebaxakerhtc** [comment] 2021-11-16 20:40
> > > 
> > 
> > 
> > So, as you can see - your termsrv.dll version is 1202, as i said you [here](https://github.com/stascorp/rdpwrap/issues/1621#issuecomment-970589849)
> 
> Thanks. After I append. What do I do?

You should to add the offsets to your rdpwrap.ini or replace whole file.
Better way to use autoupdate.bat or my modded version of rdpwrapper.
See official Telegram or my discord server to have always working offsets
https://github.com/sebaxakerhtc/rdpwrap.ini/commit/7274f1a40f3293d21ed3383d1740e8b428fcae39#diff-9e5bbfbeae79b59b305dda13323ba2b041f30f4887a84120392c479e1f7bba33
