### ISSUE TITLE
RDPwrap is blocked by Chrome

### ISSUE THREAD

**Issue by cdlvcdlv** [stascorp/rdpwrap#592] opened 2018-10-24 10:22 UTC
Both .msi and .zip installs are blocked by Chrome.

It says is dangerous/malicious.

Edit: the same thing with Firefox. It says contains virus.

**Comment by binarymaster** [comment] 2018-10-24 10:54
Duplicate of #277.

**Closed by binarymaster** 2018-10-24 10:54 UTC
