### ISSUE TITLE
10.0.10941.1741 not supported

### ISSUE THREAD

**Issue by sicwolf** [stascorp/rdpwrap#1923] opened 2022-07-11 02:35 UTC
My laptop with windows system can't support 10.0.10941.1741, could some guy help me resolve this issue?

And how can I generate the right rdpwap.ini file after windows updated?

thanks so much for any help!

**Comment by sashaqwert** [comment] 2022-07-11 05:54
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881

**Closed as not planned by sashaqwert** 2022-07-11 05:54 UTC
