### ISSUE TITLE
RDP Wrapper stopped working and cannot not connect more than one user a time

### ISSUE THREAD

**Issue by morphx666** [stascorp/rdpwrap#2369] opened 2023-10-13 22:31 UTC
Everything was working just fine until today where I had to update the INI to support 10.0.19041.3570

Now, the Config utility reports that everything is fine, but when I try to connect I get the error message saying that no more connections are allowed.

![image](https://github.com/stascorp/rdpwrap/assets/12353675/ad87cf53-c935-4b02-8120-b9484b4fa471)

Any idea what could be causing this?

**Comment by tanmayjalan** [comment] 2023-10-14 09:54
Exactly the same issue is happening for me on [10.0.19041.3570] after updating ini

**Comment by sashaqwert** [comment] 2023-10-14 15:46
Duplicate of https://github.com/stascorp/rdpwrap/issues/2359

**Comment by sashaqwert** [comment] 2023-10-14 15:47
Try:
1. Download RDP Wrapper 1.6.2 and extract this to any directory.
2. Place `rdpwrap.ini` in the same directory.
3. Open CMD as administrator
4. Execute this commands
```
cd C:\path\to\directory\
rdpwinst -u -k
rdpwinst -i
```
5. Enjoy!

Original message: https://t.me/rdpwrap/49131

**Closed as not planned by sashaqwert** 2023-10-14 15:46 UTC
Labels: duplicate

**Comment by morphx666** [comment] 2023-10-14 16:00
@sashaqwert  Unfortunately this didn't work.
Same behavior as described in the first post.

![image](https://github.com/stascorp/rdpwrap/assets/12353675/b349a86b-427c-47bc-b77c-71f6c2b00c0d)

**Comment by sashaqwert** [comment] 2023-10-14 17:14
> Unfortunately this didn't work.\nSame behavior as described in the first post.\n\n

Try modded version by sebaxakerhtc https://github.com/sebaxakerhtc/rdpwrap/releases

**Comment by morphx666** [comment] 2023-10-25 15:47
Thank you @sashaqwert. That worked perfectly.

**Comment by johmercs** [comment] 2025-04-07 09:39
Is this still working ? Anyone tried?
