### ISSUE TITLE
win10  21H1 ver. 19043.1826 is not supported? #1826  is not listening. 

### ISSUE THREAD

**Issue by fernandokosta** [stascorp/rdpwrap#1937] opened 2022-07-21 12:35 UTC
Hi!
win10  21H1 ver. 19043.1826 is not supported? #1826  is not listening. 

Thanks

**Comment by sashaqwert** [comment] 2022-07-21 16:54
RDPConf screenshot, please!

**Comment by sashaqwert** [comment] 2022-07-21 16:58
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881

**Closed as not planned by sashaqwert** 2022-07-21 16:58 UTC
