### ISSUE TITLE
Unable to connect 22621.2428

### ISSUE THREAD

**Issue by frankhli843** [stascorp/rdpwrap#2387] opened 2023-10-29 12:19 UTC
![image](https://github.com/stascorp/rdpwrap/assets/51806469/506728c8-113c-42d2-9bb2-2059f1fadae9)

I tried running update as well

**Comment by sashaqwert** [comment] 2023-10-30 07:43
Duplicate of https://github.com/stascorp/rdpwrap/issues/2345

**Closed as not planned by sashaqwert** 2023-10-30 07:43 UTC
Labels: duplicate
