### ISSUE TITLE
RDP Wrapper 21h2 19042.1586

### ISSUE THREAD

**Issue by forms-Ali** [stascorp/rdpwrap#1774] opened 2022-03-15 23:29 UTC
Do you have some update?
![image](https://user-images.githubusercontent.com/101677853/158488699-06331eb5-a168-493d-903b-9e8553785bca.png)

**Comment by ptomebr** [comment] 2022-03-16 00:08
I also had this same problem after an update today

**Comment by sebaxakerhtc** [comment] 2022-03-16 06:35
Duplicate of https://github.com/stascorp/rdpwrap/issues/1725

**Closed as completed by sebaxakerhtc** 2022-03-16 06:35 UTC
