### ISSUE TITLE
RDP Wrapper has stopped working with the November feature update

### ISSUE THREAD

**Issue by blacktraceus** [stascorp/rdpwrap#926] opened 2019-11-14 10:23 UTC
I need a solution as soon as possible please, I am trying to fix the problem by applying the patch that I applied for the KB4519338 version but with the last update of November it appears as "Not Suported"

**Comment by SobieskiCodes** [comment] 2019-11-14 19:33
20/20 hindsight. Disable updates if you rely on a tool that is no longer updated. You'll have to wait until someone in the community feels like they want to mess with the new build (afaik no one has in the last 4 or 5 builds). Roll back or find a different solution until then.

**Comment by junkwes** [comment] 2019-11-17 02:34
Bump. 

Ver reported in RDPConf: 10.0.18362.267

Listener state: Not listening [not supported]

**Comment by sk-lau** [comment] 2019-11-17 03:47
> Bump.
> 
> Ver reported in RDPConf: 10.0.18362.267
> 
> Listener state: Not listening [not supported]

Have you tried to update using this ?  rdpwrap_ini_updater_.02_August_2019.zip

**Comment by sebaxakerhtc** [comment] 2022-06-20 10:17
Duplicate of https://github.com/stascorp/rdpwrap/issues/871

**Closed as completed by sebaxakerhtc** 2022-06-20 10:17 UTC
