### ISSUE TITLE
Not working for Windows April, 2018 Update

### ISSUE THREAD

**Issue by GregoryJ** [stascorp/rdpwrap#477] opened 2018-05-11 23:50 UTC
Edition:      Windows 10 Pro
Version:      1803
Installed on: 5/1/2018
OS build:     17134.48

**Comment by Gotcha88** [comment] 2018-05-12 08:27
I have same issue too. Listener state is not supported. Can't logon without current user permission.

**Comment by binarymaster** [comment] 2018-05-12 10:31
Duplicate of #456.

**Closed by binarymaster** 2018-05-12 10:31 UTC
