### ISSUE TITLE
Windows 11 Pro Build 22631.3296

### ISSUE THREAD

**Issue by Buetschgi** [stascorp/rdpwrap#2518] opened 2024-03-15 12:15 UTC
RDP Wrapper does not allow Multi User Access to Machine. Could you check it and post a correct rdpwrap.ini please. Thank you

**Comment by loyejaotdiqr47123** [comment] 2024-03-15 12:21
Please upload the termsrv.dll file and a screenshot of rdpconf

**Comment by Buetschgi** [comment] 2024-03-15 12:42
![RDP Wrapper Configuration](https://github.com/stascorp/rdpwrap/assets/163536932/f236f6b3-4ca5-467a-8a3b-4fd59540e2d5)
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/14615567/termsrv.zip)
See attached Files, thanks for supporting

**Comment by loyejaotdiqr47123** [comment] 2024-03-15 13:15
> RDP Wrapper does not allow Multi User Access to Machine. Could you check it and post a correct rdpwrap.ini please. Thank you

Did you reboot the pc?

**Comment by Buetschgi** [comment] 2024-03-15 13:35
Thats the reason why I am oppened a Issue, it shows "fully support" but the Multi User access to machine is not working, only one can access to the machine at same time. I rebooted the machine several times. I saw by other customers its working on Windows 10 Machines but not on Windows 11 Machines. The Build number in rdpconf is not the build number i set in title of this issue.

**Comment by loyejaotdiqr47123** [comment] 2024-03-15 13:44
Version shows the version of termsrv.dll, not the system version

**Comment by Buetschgi** [comment] 2024-03-15 13:52
Hmm, I've got two Windows 11 Machines with this Problem, the other 5 Machines are Windows 10 an working. I am out of the office now, I will check all build numbers. At this time I guess it is a Windows 11 Problem only. You will hear if I checked it. Thank you

**Comment by loyejaotdiqr47123** [comment] 2024-03-15 13:57
[RDPWrap-v1.8.1.zip](https://github.com/stascorp/rdpwrap/files/14616334/RDPWrap-v1.8.1.zip)
Try using this, you can uninstall first and then install the

**Comment by loyejaotdiqr47123** [comment] 2024-03-15 13:58
> 嗯，我有两台 Windows 11 机器有这个问题，其他 5 台机器是 Windows 10 工作。我现在不在办公室，我会检查所有内部版本号。目前，我想这只是 Windows 11 的问题。如果我检查过，你会听到的。谢谢

But for rdpwrap.ini, I checked without any problems.

**Comment by loyejaotdiqr47123** [comment] 2024-03-16 02:04
> Hmm, I've got two Windows 11 Machines with this Problem, the other 5 Machines are Windows 10 an working. I am out of the office now, I will check all build numbers. At this time I guess it is a Windows 11 Problem only. You will hear if I checked it. Thank you

Wait, you're saying there's a problem with win11? Did you replace termsrv.dll? Replacing it may cause it to be unavailable.

**Comment by sashaqwert** [comment] 2024-03-16 09:38
Duplicate of https://github.com/stascorp/rdpwrap/issues/2504

**Closed as not planned by sashaqwert** 2024-03-16 09:38 UTC
Labels: duplicate

**Comment by workheart** [comment] 2025-03-25 18:46
same problem here, i got it working with termserv patch but it stoped working sinc ~20th March so i tried rdpwrapper it also does not work also gets flaged as malware by winDefender
