### ISSUE TITLE
10.0.19041.1023 - Fully supported, running but not listening

### ISSUE THREAD

**Issue by robertodan** [stascorp/rdpwrap#2062] opened 2022-12-05 09:32 UTC
Stopped and restarted the service. Restarted the PC. Didn't work. 

What am I missing? Thanks!

![Screen Shot 2022-12-05 at 11 29 11](https://user-images.githubusercontent.com/77624321/205602709-b67c6654-5301-46d5-ab97-33d38bea59e4.jpg)

**Comment by sashaqwert** [comment] 2022-12-05 11:41
Try:
1. Download RDP Wrapper 1.6.2 and extract this to any directory.
2. Place `rdpwrap.ini` in the same directory.
3. Open CMD as administrator
4. Execute this commands
```
cd C:\path\to\directory\
rdpwinst -u -k
rdpwinst -i
```
5. Enjoy!

Original message: https://t.me/rdpwrap/49131

**Comment by sashaqwert** [comment] 2022-12-05 11:44
One termsrv.dll version = one opened issue --> duplicate.

**Comment by sashaqwert** [comment] 2022-12-05 11:44
Duplicate of https://github.com/stascorp/rdpwrap/issues/1420

**Closed as not planned by sashaqwert** 2022-12-05 11:44 UTC
Labels: duplicate
