### ISSUE TITLE
10.0.26100.2161 not supported

### ISSUE THREAD

**Issue by CQuarterz** [stascorp/rdpwrap#3320] opened 2024-10-26 04:08 UTC
![image](https://github.com/user-attachments/assets/69d6d8a5-6388-4900-9c5d-601416b3a611)

**Comment by yanggit33** [comment] 2024-10-26 06:38
[10.0.26100.1882]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=8ADA1
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=9778B
SingleUserCode.x64=mov_eax_1_nop_2
DefPolicyPatch.x64=1
DefPolicyOffset.x64=94BAF
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx_jmp
SLInitHook.x64=1
SLInitOffset.x64=AB430
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.26100.1882-SLInit]
bInitialized.x64=11ADF0
bServerSku.x64=11ADF4
lMaxUserSessions.x64=11ADF8
bAppServerAllowed.x64=11AE00
bRemoteConnAllowed.x64=11AE08
bMultimonAllowed.x64=11AE0C
ulMaxDebugSessions.x64=11AE14
bFUSEnabled.x64=11AE18

**Comment by binarymaster** [comment] 2024-10-26 15:16
Duplicate of https://github.com/stascorp/rdpwrap/issues/3285.

**Closed as not planned by binarymaster** 2024-10-26 15:16 UTC
Labels: duplicate
