### ISSUE TITLE
Not working on w10 pro 19042.906

### ISSUE THREAD

**Issue by jjvillegax** [stascorp/rdpwrap#1361] opened 2021-03-30 19:45 UTC
Hello, it is not working for me for this version. please can help me.

**Comment by hugoalves8** [comment] 2021-03-31 21:34
Same here :/

**Comment by Phierdomenico** [comment] 2021-04-01 21:52
same here!

**Comment by hyotio1** [comment] 2021-04-03 15:05
same here!

**Comment by torenus** [comment] 2021-04-07 07:34
Work on Windows 10 Pro 21H1 19043.906
![work](https://user-images.githubusercontent.com/82082739/113864629-cc739880-97b3-11eb-93d5-f7d4435e3411.jpg)

**Comment by j33333** [comment] 2021-04-07 15:17
Hi! I have the same picture with all green panels, but Its not working more than 1 RDP connection. If I try to reboot - RDP Windows Service run not correctly and RDP not working. Please help

**Comment by Xinjaaa** [comment] 2021-04-08 13:05
same here!It look like quite dififcult

**Comment by torenus** [comment] 2021-04-09 14:53
> Hi! I have the same picture with all green panels, but Its not working more than 1 RDP connection. If I try to reboot - RDP Windows Service run not correctly and RDP not working. Please help

Possible problems with Windows. Run sfc / scannow

**Comment by sebaxakerhtc** [comment] 2022-06-20 13:09
Duplicate of https://github.com/stascorp/rdpwrap/issues/1317

**Closed as completed by sebaxakerhtc** 2022-06-20 13:09 UTC
