### ISSUE TITLE
Windows 10 Version 1803

### ISSUE THREAD

**Issue by izotecarlitos** [stascorp/rdpwrap#466] opened 2018-05-04 03:22 UTC
I just tried this on Windows 10 Version 1803 and get this: 

![image](https://user-images.githubusercontent.com/35771489/39611818-f373c5aa-4f17-11e8-941c-4b0ab5304b1e.png)

![image](https://user-images.githubusercontent.com/35771489/39611822-fba23f36-4f17-11e8-8180-356d3229973b.png)

**Comment by F21** [comment] 2018-05-04 04:35
See #456

**Comment by binarymaster** [comment] 2018-05-04 09:32
Duplicate of #456.

**Closed by binarymaster** 2018-05-04 09:32 UTC
