### ISSUE TITLE
Not working on Windows 10 LTSC Ver: 19044.3570

### ISSUE THREAD

**Issue by andymi75** [stascorp/rdpwrap#2378] opened 2023-10-24 03:34 UTC
Not working on 10.0.19044.3570

**Comment by sashaqwert** [comment] 2023-10-25 05:37
Duplicate of https://github.com/stascorp/rdpwrap/issues/2359

**Comment by sashaqwert** [comment] 2023-10-25 05:38
`termsrv.dll` version != Windows version!

**Closed as not planned by sashaqwert** 2023-10-25 05:37 UTC
Labels: duplicate
