### ISSUE TITLE
WindowsPro23H2 22631.3672_Only_SingleConnection

### ISSUE THREAD

**Issue by dayspring-dev** [stascorp/rdpwrap#3116] opened 2024-06-02 21:35 UTC
Only one connection is allow for windows 11 Pro 23H2 22631.3672
[Windows11Pro_23H2_22631.3672.zip](https://github.com/user-attachments/files/15526976/Windows11Pro_23H2_22631.3672.zip)
![WindowsPro23H2 22631 3672_WorkingOnlyAllowSingleRDPConnection](https://github.com/stascorp/rdpwrap/assets/26641244/48277031-2409-495e-adc1-4454e00ae593)

**Comment by dayspring-dev** [comment] 2024-06-03 02:49
It looks like more than one concurrent connection is not allowed with RDP Wrapper on Windows 11 PRO 23H2 22631.3672

**Comment by binarymaster** [comment] 2024-06-03 17:12
Issue title is misleading, your termsrv build is 10.0.22621.3085

Duplicate of #2469.

**Closed as not planned by binarymaster** 2024-06-03 17:12 UTC
Labels: duplicate
