### ISSUE TITLE
HEPL VERSION 10.0.19041.1202

### ISSUE THREAD

**Issue by yaoGreat** [stascorp/rdpwrap#1575] opened 2021-10-27 10:53 UTC
![image](https://user-images.githubusercontent.com/8615967/139052415-d4929bf7-5e4b-49cb-a55f-9b11f282fb9c.png)

THANKS.

**Comment by sebaxakerhtc** [comment] 2021-10-27 10:55
Duplicate of https://github.com/stascorp/rdpwrap/issues/1509

**Closed as completed by sebaxakerhtc** 2021-10-27 10:55 UTC
