### ISSUE TITLE
termsrv 10.0.16299.15 not supported

### ISSUE THREAD

**Issue by Domas1232** [stascorp/rdpwrap#343] opened 2017-11-02 09:06 UTC
Hello,

[*] Terminal Services version: 10.0.16299.15
[-] This version of Terminal Services is not supported.

Windows 10 pro with creators fall update. Are you going to support it?

**Comment by binarymaster** [comment] 2017-11-02 09:11
Stop creating duplicate issues, read the README. :rage:

**Comment by binarymaster** [comment] 2017-11-02 09:12
Duplicate of #316.

**Closed by binarymaster** 2017-11-02 09:11 UTC
