### ISSUE TITLE
@stascorp  pls help us win11 pro .22621.2506

### ISSUE THREAD

**Issue by xoptoi** [stascorp/rdpwrap#2386] opened 2023-10-28 10:58 UTC
Reinstall log ------------------------------------------------
@stascop

[*] Installing...
[*] Terminal Services version: 10.0.22621.2506
[-] This version of Terminal Services is not supported.
Try running "update.bat" or "RDPWInst -w" to download latest INI file.
If it doesn't help, send your termsrv.dll to project developer for support.

![image](https://github.com/sebaxakerhtc/rdpwrap.ini/assets/75647741/225ee6ee-0c89-4f56-a5e6-42e4774aef0f)

**Comment by sashaqwert** [comment] 2023-10-28 17:00
> @stascop

This works only for `@stascorp/rdp-wrapper-mods` members. See correct ping "user". `@stascorp` is wring!

![изображение](https://github.com/stascorp/rdpwrap/assets/24974508/bb7b9948-7c01-4da7-8244-251d4349989c)

> If it doesn't help, send your termsrv.dll to project developer for support.

The developer of this software has been biased for a long time. He just doesn't add them yet. **Issues that contain offsets ready to be added to the official INI are marked with the "Add build" label**. All other issues indicating the same version will be closed as a duplicate in 98% of cases.

**Comment by sashaqwert** [comment] 2023-10-28 17:02
Duplicate of https://github.com/stascorp/rdpwrap/issues/2383

**Closed as not planned by sashaqwert** 2023-10-28 17:02 UTC
Labels: duplicate
