### ISSUE TITLE
Virus! Virus! Virus!

### ISSUE THREAD

**Issue by sathish109** [stascorp/rdpwrap#1161] opened 2020-09-07 15:11 UTC

**Comment by Monoverde888** [comment] 2020-09-11 22:22
what?

**Comment by marcboivin** [comment] 2020-09-18 12:46
Chrome won't let you download it anymore because it is flagged as a virus.

**Comment by robbak** [comment] 2020-09-18 21:04
That is your security program getting in the road. Chrome calls on it to
scan all downloads, and deletes the file if the program flags it as
malicious.

Use the software's web site to report the false positive, them uninstall
it, cancel your subscription, and use a different one.

**Comment by boukeversteegh** [comment] 2021-03-16 10:46
Any idea how todo this with Windows Defender?

**Comment by sebaxakerhtc** [comment] 2022-06-20 11:45
Duplicate of https://github.com/stascorp/rdpwrap/issues/277

**Closed as completed by sebaxakerhtc** 2022-06-20 11:45 UTC
