### ISSUE TITLE
rdp wrapper not working in windows 11 pro version 10.0.22000.493

### ISSUE THREAD

**Issue by manish031985** [stascorp/rdpwrap#1746] opened 2022-02-26 07:09 UTC
rdp wrapper not working in windows 11 pro version 10.0.22000.493

please provide rdpwrap.ini file for this updated version

**Comment by sebaxakerhtc** [comment] 2022-02-28 13:42
Duplicate of https://github.com/stascorp/rdpwrap/issues/1698

**Closed as completed by sebaxakerhtc** 2022-02-28 13:43 UTC
