### ISSUE TITLE
 Windows 10.0.17763.4499 not supported

### ISSUE THREAD

**Issue by AVDEEV-Tech** [stascorp/rdpwrap#2261] opened 2023-06-29 05:30 UTC
Hello. Need's help pls.

**Comment by sashaqwert** [comment] 2023-06-29 08:53
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by AVDEEV-Tech** [comment] 2023-06-29 14:41
Sorry, I don't check version of Windows in RDPConf first, but check it only in "cmd" with "ver" command.
Now I see in RDPConf what version of my Windows is 10.0.17763.**4252** and I can download correct rdpwrap.ini. 
And now I have [full supported].
Thx for help :) Sorry for noize.
![rdp](https://github.com/stascorp/rdpwrap/assets/138094220/6df78ee8-66dc-413c-8d9c-4eb3383fdb1d)

**Comment by sashaqwert** [comment] 2023-06-29 15:11
And some explanatory noise...

> I don't check version of Windows in RDPConf

RDPConf shows the version of `termsrv.dll`, not Windows.

---------

This issue will closed as duplicate of correct issue.

**Comment by sashaqwert** [comment] 2023-06-29 15:12
Duplicate of https://github.com/stascorp/rdpwrap/issues/2167

**Closed as not planned by sashaqwert** 2023-06-29 15:12 UTC
