### ISSUE TITLE
Windows 10 64-bit version 10.0.19044.1387 not working

### ISSUE THREAD

**Issue by zxinyun** [stascorp/rdpwrap#1655] opened 2021-12-10 02:42 UTC
[Uploading termsrv.zip…]()
![image](https://user-images.githubusercontent.com/6713648/145508333-11ea7cf6-3dd6-4764-b8fd-5453b38e0dee.png)

**Comment by sashaqwert** [comment] 2021-12-10 13:47
Duplicate of https://github.com/stascorp/rdpwrap/issues/1630

**Closed as completed** 2021-12-10 19:26 UTC
