### ISSUE TITLE
problem with rdp wrapper 10.0.18362

### ISSUE THREAD

**Issue by gitanoloco** [stascorp/rdpwrap#909] opened 2019-10-16 05:02 UTC
my problem is that i can not use rdp as normal, cant log 2 users at same time and i cant do anything because rdpconfig, rdp check and the .ini  files dissapear when i try to use... i try also to reeinstall and happends  samething, what i could do?

 i havent read about this problem here before so that why i open a new post about this.

sorry for my inglish and thanks for your time

**Comment by SobieskiCodes** [comment] 2019-10-16 12:52
https://github.com/stascorp/rdpwrap/issues/906
Try that (uninstall first), no idea whats going on with it deleting stuff - maybe shut off firewall/disable antivirus.

**Comment by NotAlkaline** [comment] 2019-10-16 15:38
I have the exact same problem, I can't log more than one user at the same time.

**Comment by SobieskiCodes** [comment] 2019-10-16 16:05
> 
> 
> I have the exact same problem, I can't log more than one user at the same time.

have you tried the above after uninstalling? Currently on his build with no problems.

**Comment by gitanoloco** [comment] 2019-10-25 19:02
> #906
> Try that (uninstall first), no idea whats going on with it deleting stuff - maybe shut off firewall/disable antivirus.

bro i have read everything you was posting this days and i still cant do multilogin.

i uninstall the antivirus that cant bring rdp to whitelist  reboot pc
install other, uninstal rdp and reboot pc again
follow step by step your process to fix it and change the rfxvmt.dll as other user say and still persist the problem... have any idea of what can i do?

**Comment by flydvorkin** [comment] 2019-10-31 15:13
18362.449 - working.
Check ini file from: https://github.com/stascorp/rdpwrap/issues/902
by @Techgoduk post.

If no C:\windows\system32\rfxvmt.dll file, then install
%windir%\servicing\Packages\Microsoft-Windows-Virtualization-RemoteFX-User-Mode-Transport-Package~*.mum
package by dism

**Comment by sebaxakerhtc** [comment] 2022-06-20 10:08
Duplicate of https://github.com/stascorp/rdpwrap/issues/902

**Closed as completed by sebaxakerhtc** 2022-06-20 10:08 UTC
