### ISSUE TITLE
still unsupport 10.0.18362.267 (after W7 -> W10 upgrade)

### ISSUE THREAD

**Issue by kuerbis42** [stascorp/rdpwrap#954] opened 2020-01-03 18:32 UTC
Hi, this is an additional to #848 

After UPGRADING W7 to W10, you aren't able to install RDPWrapper. All tries with the fixes descripted in #848 won't work, IF there is still the old terminal-service is activ.
What does that mean:
Open "services" and search for "remotedesktopservices". If you can't find this, but instead of this "terminal services" (maybe not started), then you not able to install RDPWrapper.

In this case you must import the following Reg-values:
```
 Windows Registry Editor Version 5.00
 
 [HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\TermService]
 "DependOnService"=hex(7):52,00,50,00,43,00,53,00,53,00,00,00,00,00
 "Description"="@%SystemRoot%\\System32\\termsrv.dll,-267"
 "DisplayName"="@%SystemRoot%\\System32\\termsrv.dll,-268"
 "ErrorControl"=dword:00000001
 "FailureActions"=hex:80,51,01,00,00,00,00,00,00,00,00,00,03,00,00,00,14,00,00,\
   00,01,00,00,00,60,ea,00,00,01,00,00,00,60,ea,00,00,00,00,00,00,60,ea,00,00
 "ImagePath"=hex(2):25,00,53,00,79,00,73,00,74,00,65,00,6d,00,52,00,6f,00,6f,00,\
   74,00,25,00,5c,00,53,00,79,00,73,00,74,00,65,00,6d,00,33,00,32,00,5c,00,73,\
   00,76,00,63,00,68,00,6f,00,73,00,74,00,2e,00,65,00,78,00,65,00,20,00,2d,00,\
   6b,00,20,00,4e,00,65,00,74,00,77,00,6f,00,72,00,6b,00,53,00,65,00,72,00,76,\
   00,69,00,63,00,65,00,00,00
 "ObjectName"="NT Authority\\NetworkService"
 "RequiredPrivileges"=hex(7):53,00,65,00,41,00,73,00,73,00,69,00,67,00,6e,00,50,\
   00,72,00,69,00,6d,00,61,00,72,00,79,00,54,00,6f,00,6b,00,65,00,6e,00,50,00,\
   72,00,69,00,76,00,69,00,6c,00,65,00,67,00,65,00,00,00,53,00,65,00,41,00,75,\
   00,64,00,69,00,74,00,50,00,72,00,69,00,76,00,69,00,6c,00,65,00,67,00,65,00,\
   00,00,53,00,65,00,43,00,68,00,61,00,6e,00,67,00,65,00,4e,00,6f,00,74,00,69,\
   00,66,00,79,00,50,00,72,00,69,00,76,00,69,00,6c,00,65,00,67,00,65,00,00,00,\
   53,00,65,00,43,00,72,00,65,00,61,00,74,00,65,00,47,00,6c,00,6f,00,62,00,61,\
   00,6c,00,50,00,72,00,69,00,76,00,69,00,6c,00,65,00,67,00,65,00,00,00,53,00,\
   65,00,49,00,6d,00,70,00,65,00,72,00,73,00,6f,00,6e,00,61,00,74,00,65,00,50,\
   00,72,00,69,00,76,00,69,00,6c,00,65,00,67,00,65,00,00,00,53,00,65,00,49,00,\
   6e,00,63,00,72,00,65,00,61,00,73,00,65,00,51,00,75,00,6f,00,74,00,61,00,50,\
   00,72,00,69,00,76,00,69,00,6c,00,65,00,67,00,65,00,00,00,00,00
 "ServiceSidType"=dword:00000001
 "Start"=dword:00000003
 "Type"=dword:00000020
 
 [HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\TermService\Parameters]
 "ServiceDll"=hex(2):25,00,50,00,72,00,6f,00,67,00,72,00,61,00,6d,00,46,00,69,\
   00,6c,00,65,00,73,00,25,00,5c,00,52,00,44,00,50,00,20,00,57,00,72,00,61,00,\
   70,00,70,00,65,00,72,00,5c,00,72,00,64,00,70,00,77,00,72,00,61,00,70,00,2e,\
   00,64,00,6c,00,6c,00,00,00
 "ServiceDllUnloadOnStop"=dword:00000001
 
 [HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\TermService\Performance]
 "Close"="CloseTSObject"
 "Collect"="CollectTSObjectData"
 "Collect Timeout"=dword:000003e8
 "Library"="C:\\Windows\\System32\\perfts.dll"
 "Open"="OpenTSObject"
 "Open Timeout"=dword:000003e8
 "InstallType"=dword:00000001
 "PerfIniFile"="tslabels.ini"
 "First Counter"=dword:0000238c
 "Last Counter"=dword:0000238c
 "First Help"=dword:0000238d
 "Last Help"=dword:0000238d
 "Object List"="9100"
 ```
This values are uptodate with the needed values for RDPWrapper:
```
Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TermService\Parameters
ServiceDll = %ProgramFiles%\RDP Wrapper\rdpwrap.dll
```
I think, the (windows) upgrade sometimes works incorrect, not updating this values.
After the import, reboot your PC and try it again. (Don't forget to save the original registry-values before)

**Comment by sebaxakerhtc** [comment] 2022-06-20 10:18
Duplicate of https://github.com/stascorp/rdpwrap/issues/871

**Closed as completed by sebaxakerhtc** 2022-06-20 10:18 UTC
