### ISSUE TITLE
Please add support for update KB4471332 windows 10

### ISSUE THREAD

**Issue by korolartemnexus** [stascorp/rdpwrap#613] opened 2018-12-14 10:11 UTC
Please add support for update KB4471332 windows 10
ver 10.0.1763.168 is not supported after windows update, please fix it.

**Comment by korolartemnexus** [comment] 2018-12-14 11:01
I changed ini file in C:\Program Files\RDP Wrapper to this https://raw.githubusercontent.com/stascorp/rdpwrap/2ded34c2399e3210f2929942e9cf1395b90daa5d/res/rdpwrap.ini and then restart terminal services net stop termserv and then start it

**Comment by korolartemnexus** [comment] 2018-12-14 11:03
Thank for support

**Comment by binarymaster** [comment] 2018-12-16 14:43
Duplicate of #606.

**Closed by binarymaster** 2018-12-16 14:43 UTC

**Comment by gustavoechavarria** [comment] 2018-12-28 08:18
Hi Everyone, I have tried with this .ini file and it worked for me, it's for 10.0.17763.167 version x64
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/2714373/rdpwrap.zip)
![image](https://user-images.githubusercontent.com/46215774/50508317-6681fd80-0a4f-11e9-9a4b-57872d4141f2.png)

First, stop the service running CMD as administrator, then run net stop termservice
Replace rdpwrap.ini in C:\Program Files\RDP Wrapper
then run net start termservice
Very important Reboot your PC
then when your pc rebooted, run RDPConf to check the states, make sure All states are green
