### ISSUE TITLE
10.0.19042.985 not supported

### ISSUE THREAD

**Issue by juanwrs** [stascorp/rdpwrap#1397] opened 2021-05-12 12:20 UTC
Can anyone help us with ini files for win 10 version 10.0.19042.985? Thank you.

**Comment by Iskandare** [comment] 2021-05-12 18:45
Here fiile for 10.0.19042.985
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/6468440/rdpwrap.zip)
![000283](https://user-images.githubusercontent.com/61160226/118028088-f6941980-b362-11eb-8336-2babfabd99ac.jpg)

**Comment by RChutchev** [comment] 2021-05-12 19:07
![image](https://user-images.githubusercontent.com/11131666/118030643-3dd3d780-b36e-11eb-84b9-2f56db6acbf5.png)
Hey, same problem with RDPWrap, unable to connect.
![image](https://user-images.githubusercontent.com/11131666/118030760-62c84a80-b36e-11eb-923f-4ef272368784.png)

**Comment by Iskandare** [comment] 2021-05-12 19:35
Try this action : 
1 - Download AutoUpdate : https://github.com/stascorp/rdpwrap/files/3588288/autoupdate-v07.09.2019.zip
2 - Extract "autoupdate.bat" to C:\Program Files\RDP Wrapper and right clic and execute as administrator
it will work !

**Comment by Iskandare** [comment] 2021-05-12 19:41
here solution to your problem : http://woshub.com/how-to-allow-multiple-rdp-sessions-in-windows-10/
See my screenshoot : 
![000284](https://user-images.githubusercontent.com/61160226/118034945-df592a00-b36a-11eb-872e-eefeed8fba74.jpg)

**Comment by RChutchev** [comment] 2021-05-12 20:14
> here solution to your problem : http://woshub.com/how-to-allow-multiple-rdp-sessions-in-windows-10/
> See my screenshoot :
> ![000284](https://user-images.githubusercontent.com/61160226/118034945-df592a00-b36a-11eb-872e-eefeed8fba74.jpg)

Yep, i did it but RPD still not working...
![Снимок экрана (1273)](https://user-images.githubusercontent.com/11131666/118038281-965ba280-b377-11eb-9e0c-7b5458645c9b.png)
![image](https://user-images.githubusercontent.com/11131666/118038369-b0958080-b377-11eb-961d-873f186b04a4.png)

**Comment by Iskandare** [comment] 2021-05-12 20:31
Добрый вечер Роман!
Я думаю над решением этой проблемы. И я напишу сразу как найду.

Решение ??   https://www.kapilarya.com/the-number-of-connections-to-this-computer-is-limited-windows-10

**Comment by RChutchev** [comment] 2021-05-12 20:48
> > here solution to your problem : http://woshub.com/how-to-allow-multiple-rdp-sessions-in-windows-10/
> > See my screenshoot :
> > ![000284](https://user-images.githubusercontent.com/61160226/118034945-df592a00-b36a-11eb-872e-eefeed8fba74.jpg)
> 
> Yep, i did it but RPD still not working...
> ![Снимок экрана (1273)](https://user-images.githubusercontent.com/11131666/118038281-965ba280-b377-11eb-9e0c-7b5458645c9b.png)
> ![image](https://user-images.githubusercontent.com/11131666/118038369-b0958080-b377-11eb-961d-873f186b04a4.png)

Добрый, спасибо, это уже установлено как 10 (a), но не работало
![image](https://user-images.githubusercontent.com/11131666/118041875-02d8a080-b37c-11eb-987f-49faec3e907d.png)

а вот тут ini который я закинул и оно вроде заработало
https://github.com/stascorp/rdpwrap/issues/1188#issuecomment-838350263
**For an English speaking audience: I have updated my .ini file and it works for me, try to download file from this comment.**

**Comment by greasemonkey2** [comment] 2021-05-13 13:33
> 
> 
> Here fiile for 10.0.19042.985
> [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/6468440/rdpwrap.zip)
> ![000283](https://user-images.githubusercontent.com/61160226/118028088-f6941980-b362-11eb-8336-2babfabd99ac.jpg)

Worked for me.... Will  this go in the autoupdater?

**Comment by simonsnow** [comment] 2021-05-13 20:10
working for me on V 10.0.19041 Build 19041. Thank you!

**Comment by creativ45** [comment] 2021-05-14 04:04
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/6476460/termsrv.zip)
Отредактированный termsrv.dll в HEX редакторе, заменить по пути c:\Windows\System32\termsrv.dll
Edited termsrv.dll in HEX editor, replace along the way c:\Windows\System32\termsrv.dll

**Comment by XFPDA** [comment] 2021-05-17 09:39
it's working , thanks

**Comment by ForwardUntoDawn** [comment] 2021-05-18 15:58
> Here fiile for 10.0.19042.985
> [rdpwrap.zip] (https://github.com/stascorp/rdpwrap/files/6468440/rdpwrap.zip)

Worked perfectly.
Thanks for the updated INI @Iskandare

**Comment by cenchale** [comment] 2022-01-13 12:33
> Here fiile for 10.0.19042.985 [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/6468440/rdpwrap.zip) ![000283](https://user-images.githubusercontent.com/61160226/118028088-f6941980-b362-11eb-8336-2babfabd99ac.jpg)

it works well on V 19043.928.thanks

**Comment by sebaxakerhtc** [comment] 2022-06-20 13:21
Duplicate of https://github.com/stascorp/rdpwrap/issues/1384

**Closed as completed by sebaxakerhtc** 2022-06-20 13:21 UTC
