### ISSUE TITLE
Cant connect more user Windows 10 32bit after update.

### ISSUE THREAD

**Issue by servisichoice** [stascorp/rdpwrap#912] opened 2019-10-22 10:59 UTC
Hi i cant connect more user on w10  Profi
![Snímek obrazovky (35)](https://user-images.githubusercontent.com/56356648/67279649-b8f34580-f4cb-11e9-954b-8395cde1ce25.png)

**Comment by s0nic9** [comment] 2019-10-22 11:02
Windows 10 pro ?

**Comment by servisichoice** [comment] 2019-10-22 11:35
yes Windows 10 Profi sorry

**Comment by s0nic9** [comment] 2019-10-22 11:58
please read before posting, you need a empty line at the end of the ini because you have edited the file manually.

**Comment by sebaxakerhtc** [comment] 2022-06-20 10:15
Duplicate of https://github.com/stascorp/rdpwrap/issues/871

**Closed as completed by sebaxakerhtc** 2022-06-20 10:15 UTC
