### ISSUE TITLE
Listener state = not listening  Help PLEASE!

### ISSUE THREAD

**Issue by AndreCTX** [stascorp/rdpwrap#3377] opened 2024-12-09 19:58 UTC
Hi i am having an issue where i try to use RDP Wrapper on windows 11.
I have it as:
Wrapper state: Installed
Wrapper ver. 1.7.4.0
Service State: Running
Listener State: **Not listening**
termsrv ver. 10.0.22621.4391
[Fully supported]

Any idea on how can I fix this issue? It never connects when i try .
my windows version says 

Windows 11 Home Single Language
23H2
22631.4460
![foto conf](https://github.com/user-attachments/assets/80f9b34f-632d-4154-8257-09c9b31b15e2)

If anyone can help please. many thanks in advance

**Comment by binarymaster** [comment] 2024-12-24 11:54
One issue per build number.

Duplicate of https://github.com/stascorp/rdpwrap/issues/3316.

**Closed as not planned by binarymaster** 2024-12-24 11:54 UTC
Labels: duplicate

**Comment by aneez11** [comment] 2025-01-17 12:13
i am also facing this issue, and nothing works, have anyone found alternative solution for this ?
