### ISSUE TITLE
Not Supported 10.0.22000.739 

### ISSUE THREAD

**Issue by yioye** [stascorp/rdpwrap#1907] opened 2022-06-19 05:27 UTC

**Comment by sashaqwert** [comment] 2022-06-19 09:27
Duplicate of https://github.com/stascorp/rdpwrap/issues/1868

**Comment by sebaxakerhtc** [comment] 2022-06-20 09:23
Duplicate of https://github.com/stascorp/rdpwrap/issues/1868

**Closed as completed by sebaxakerhtc** 2022-06-20 09:23 UTC
