### ISSUE TITLE
Problem with 10.0.18362.267 - User changes

### ISSUE THREAD

**Issue by technics1210** [stascorp/rdpwrap#961] opened 2020-01-16 10:07 UTC
Hello,

when I start the remote connection, the user selection comes.
I can then log in with the respective user.

for example User A works on the PC
User B logs on remote.

Then the PC is switched to user B, not logged out.
User A sees what User B does.

When user B logs out, automatically fall back to user A.

Problem has been since the last update.

Is there a solution?

Thanks

**Comment by technics1210** [comment] 2020-01-16 10:11
![Unbenanntes Bild](https://user-images.githubusercontent.com/46656712/72515839-e5132e00-3850-11ea-9a2e-e7a49636737a.png)

**Comment by Crakki** [comment] 2020-01-25 13:04
I have the same problem - 10.0.18362.267

**Comment by s0nic9** [comment] 2020-01-26 20:51
have you edited your .ini manually ?

**Comment by technics1210** [comment] 2020-01-28 16:34
Yes.
It doesn't work without editing.
The other user is logged off, if it will not be edited

**Comment by s0nic9** [comment] 2020-01-30 11:45
do you use TeamViewer ?

**Comment by technics1210** [comment] 2020-02-01 09:24
Yes, I have Teamviewer 13
Why?

**Comment by s0nic9** [comment] 2020-02-03 12:13
I have problem with TeamViewer 13 on an host, if I RDP into one session, my mouse move onto others sessions and I have weird screen. I must close fully TeamViewer on the host before RDP into.
sorry for my english.

**Comment by technics1210** [comment] 2020-02-05 18:10
Right.
When i close teamviewer it works :-)
Thanks for your help

**Comment by sebaxakerhtc** [comment] 2022-06-20 10:22
Duplicate of https://github.com/stascorp/rdpwrap/issues/871

**Closed as completed by sebaxakerhtc** 2022-06-20 10:22 UTC
