### ISSUE TITLE
10.0.19041.1202 no listening but fully supported

### ISSUE THREAD

**Issue by 2414466154** [stascorp/rdpwrap#1586] opened 2021-11-05 10:05 UTC
![image](https://user-images.githubusercontent.com/38528977/140493701-522ae6a8-4fc7-4315-a67c-f035ecd8d4ef.png)

my system is win10  * 64

**Comment by 2414466154** [comment] 2021-11-05 10:06
You have a solution

**Comment by sebaxakerhtc** [comment] 2021-11-05 12:13
Duplicate of https://github.com/stascorp/rdpwrap/issues/1509

**Closed as completed by sebaxakerhtc** 2021-11-05 12:13 UTC
