### ISSUE TITLE
Version 10.0.17763.1697 Windows 10 LTSC

### ISSUE THREAD

**Issue by FengAiLing2016** [stascorp/rdpwrap#1277] opened 2021-01-14 02:25 UTC
This morning RDP changed to only allow a single user to connect
![open](https://github.com/FengAiLing2016/stc_c/blob/master/Snipaste_2021-01-14_10-15-09.png?raw=true)
Then I updated the INI
After restarting it becomes
![open](https://github.com/FengAiLing2016/stc_c/blob/master/Snipaste_2021-01-14_10-14-05.png?raw=true)

What can I do? 
help me

**Comment by Leksandrua** [comment] 2021-01-14 08:06
[10.0.17763.1697]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=7E421
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=138BC
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=18545
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=21A3C
SLInitFunc.x64=New_CSLQuery_Initialize

It worked for me via autoupdate.bat

**Comment by test2a** [comment] 2021-01-14 11:40
i am seeing the  listener state: not listening 

https://pastebin.com/GbBEMgbB
my rdpwrap.ini file in C:\Program Files\RDP Wrapper

**Comment by Zelward** [comment] 2021-01-14 16:17
can anyone help?

[termsrv_10_0_17763_1697.zip](https://github.com/stascorp/rdpwrap/files/5815605/termsrv_10_0_17763_1697.zip)

**Comment by sebaxakerhtc** [comment] 2021-01-14 17:52
> 
> 
> can anyone help?
> 
> [termsrv_10_0_17763_1697.zip](https://github.com/stascorp/rdpwrap/files/5815605/termsrv_10_0_17763_1697.zip)

https://github.com/sebaxakerhtc/rdpwrap.ini/commit/2738288a7abd7f62026b085442f2f7920fcbdd25

**Comment by tetas26** [comment] 2021-01-14 20:37
sebaxakerhtc, can you help with a 32 bit verson?

**Comment by sebaxakerhtc** [comment] 2021-01-14 21:42
> sebaxakerhtc, can you help with a 32 bit verson?

Sorry, but no. I do it just fir x64.

**Comment by FengAiLing2016** [comment] 2021-01-15 01:51
> [10.0.17763.1697]
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=7E421
> LocalOnlyCode.x64=jmpshort
> SingleUserPatch.x64=1
> SingleUserOffset.x64=138BC
> SingleUserCode.x64=Zero
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=18545
> DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> SLInitHook.x64=1
> SLInitOffset.x64=21A3C
> SLInitFunc.x64=New_CSLQuery_Initialize
> 
> It worked for me via autoupdate.bat



> > can anyone help?
> > [termsrv_10_0_17763_1697.zip](https://github.com/stascorp/rdpwrap/files/5815605/termsrv_10_0_17763_1697.zip)
> 
> [sebaxakerhtc/rdpwrap.ini@2738288](https://github.com/sebaxakerhtc/rdpwrap.ini/commit/2738288a7abd7f62026b085442f2f7920fcbdd25)

thank you!

**Comment by test2a** [comment] 2021-01-19 04:58
i have this fix running but a weird bug. everytime the pc starts, remote clients cannot log in. i have to go to RDPcheck, open the window and log in to a user. 
then every other person can log in. does anyone know if this can be fixed somehow?

**Comment by 111blackjack111** [comment] 2021-01-25 07:47
> > can anyone help?
> > [termsrv_10_0_17763_1697.zip](https://github.com/stascorp/rdpwrap/files/5815605/termsrv_10_0_17763_1697.zip)
> 
> [sebaxakerhtc/rdpwrap.ini@2738288](https://github.com/sebaxakerhtc/rdpwrap.ini/commit/2738288a7abd7f62026b085442f2f7920fcbdd25)

It works. But you need to copy the text of the entire file rdpwrap.ini and replace it in yours

**Comment by sebaxakerhtc** [comment] 2021-01-25 07:52
> you need to copy the text of the entire file rdpwrap.ini and replace it in yours

Or add link to my ini in your rdpwrapper.ini and run autoupdate

**Comment by mariaczi** [comment] 2021-02-02 18:59
> Or add link to my ini in your rdpwrapper.ini and run autoupdate

@sebaxakerhtc Could you explain how to do it? Thanks in advance.

**Comment by sebaxakerhtc** [comment] 2021-02-02 19:30
Open your autoupdate.bat, add link to my ini and save

вт, 2 февр. 2021 г., 20:59 mariaczi <notifications@github.com>:

**Comment by sebaxakerhtc** [comment] 2022-06-20 12:39
Duplicate of https://github.com/stascorp/rdpwrap/issues/1276

**Closed as completed by sebaxakerhtc** 2022-06-20 12:39 UTC
