### ISSUE TITLE
19041.1566 win 21H2 - Not Supported

### ISSUE THREAD

**Issue by giordan-net** [stascorp/rdpwrap#1734] opened 2022-02-19 14:00 UTC
Wrapper state: Installed - ver. 1.5.0.0
Service state: Runnig - ver. 10.0.19041.1566 
Listener state: Listening - NOT SUPPORTED

Can anyone solve not supported state, plz

**Comment by sashaqwert** [comment] 2022-02-19 16:48
Duplicate of https://github.com/stascorp/rdpwrap/issues/1725

**Closed as completed** 2022-02-21 20:08 UTC

**Comment by robertodan** [comment] 2022-03-13 11:59
Used the ini file. Thanks! 

Fully supported but "not listening"... restarted the service, restarted the pc. Didn't work. 

What am I missing? Thank you!
