### ISSUE TITLE
10.0.19041.3570 - listening OK, running OK, installed OK, supported OK - no multi user access

### ISSUE THREAD

**Issue by daxtrajero** [stascorp/rdpwrap#2389] opened 2023-10-30 15:19 UTC
I have an issue where rdpwrap reports everything is running fine, but when a remote user logs in, it logs out the current user

Any ideas how to prevent this? I'm wondering if KB5031356 is causing the issue?
Sadly I don't know how to remove KB5031356 as I don't get an uninstall option like I do for other updates

**Comment by github00771** [comment] 2023-10-30 17:18
I have the same problem

**Comment by daxtrajero** [comment] 2023-10-31 18:00
As a temporary fix, try uninstalling Windows Security Update KB5031356 and reboot. You should now be able to get multi-user access

**Comment by sashaqwert** [comment] 2023-11-01 11:09
> 10.0.19041.3570

One `termsrv.dll` version = ONE opened issue for one architecture. This issue will closed as duplicate (I'm have permissions to do this ;))

> listening OK

This is correct, otherwise you would not be able to connect via RDP.

> installed OK, supported OK

Offsets is exists in local `rdpwrap.ini` and RDP Wrapper is installed

> KB5031356 as I don't get an uninstall option

Uninstalling updates is off-topic here.

> no multi user access

Try:
1. Download RDP Wrapper 1.6.2 and extract this to any directory.
2. Place `rdpwrap.ini` in the same directory.
3. Open CMD as administrator
4. Execute this commands
```
cd C:\path\to\directory\
rdpwinst -u -k
rdpwinst -i
```
5. Enjoy!

Original message: https://t.me/rdpwrap/49131

**Comment by sashaqwert** [comment] 2023-11-01 11:10
Duplicate of https://github.com/stascorp/rdpwrap/issues/2359

**Closed as not planned by sashaqwert** 2023-11-01 11:10 UTC
Labels: duplicate
