### ISSUE TITLE
Listener is not listening on Win 10 pro

### ISSUE THREAD

**Issue by shaheez** [stascorp/rdpwrap#483] opened 2018-05-15 14:37 UTC
Hello,

Thank you for rdpwrap!

Unfortunately, on Windows 10 pro edition, it is not working anymore since windows 10 version 1803 update lastweek
Rdpwrap is fully updated and says "fully supported", but Listener state is "not listening" for some reason.

Thank you!

**Comment by binarymaster** [comment] 2018-05-15 14:38
Duplicate of #456.

**Closed as completed by binarymaster** 2018-05-15 14:38 UTC
Labels: duplicate
