### ISSUE TITLE
Win8.1Pro

### ISSUE THREAD

**Issue by DATUC** [stascorp/rdpwrap#554] opened 2018-09-12 09:35 UTC
rdpwrap Not working this morgning
Windows 8.1 Pro
Wrapper state V: 1.5.0.0
Services state : 6.3.9600.19093
Listner : Not supported
![rdp](https://user-images.githubusercontent.com/26550824/45416340-a75c2f00-b677-11e8-98ff-7e42132aeacc.JPG)

**Comment by binarymaster** [comment] 2018-09-12 09:50
Duplicate of #549.

**Closed by binarymaster** 2018-09-12 09:50 UTC
