### ISSUE TITLE
I found ini file for 10.0.22581.1 but the listener doesn't work.

### ISSUE THREAD

**Issue by AstralFlare-owo** [stascorp/rdpwrap#1803] opened 2022-04-08 02:08 UTC
Wrapper installed, service running, system fully supported, but the listener doesn't work.
Wrapper version: 1.5.0.0
System: Windows 11 Home Edition Build 22581.ni_release 64bit DEV
Enable Remote Desktop: True
RDP Port: 3389
Single session per user: True
Hide users on logon screen: False
Allow to start custom programs: True
Authentication Mode: GUI Authentication Only
Session Shadowing Mode: Full access with user's permission
ini file: [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/8447940/rdpwrap.zip)
Download Source: This Github repository

**Comment by sashaqwert** [comment] 2022-04-08 07:13
Duplicate of https://github.com/stascorp/rdpwrap/issues/1791

**Comment by sashaqwert** [comment] 2022-04-08 07:16
> but the listener doesn't work

Try `net start termService` or/and reboot.

**Comment by sebaxakerhtc** [comment] 2022-04-08 11:05
> Duplicate of #1791

**Closed as completed by sebaxakerhtc** 2022-04-08 11:05 UTC
