### ISSUE TITLE
19042.746 X86 rdpwrap.ini

### ISSUE THREAD

**Issue by FlyingDutchman1965** [stascorp/rdpwrap#1297] opened 2021-01-20 15:33 UTC
Hi there, does anyone have the 32bit (X86) parameters to go in the rdpwrap.ini file?

All I can find is the X64 ones.

Thanks.

**Comment by sashaqwert** [comment] 2021-01-21 08:08
Please attach your termsrv.dll (in the `C:\Windows\System32` directory)

<details>
  <summary>Screenshot</summary>
   
![изображение](https://user-images.githubusercontent.com/24974508/105321794-fa940400-5bd8-11eb-8b74-414aa953eb2e.png)

</details>

**Comment by FlyingDutchman1965** [comment] 2021-01-22 13:21
Hope you can see this
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/5856065/termsrv.zip)

**Comment by sk-lau** [comment] 2021-01-23 04:42
> Hope you can see this
> [termsrv.zip](https://github.com/stascorp/rdpwrap/files/5856065/termsrv.zip)

but this version is 64bit version 10.0.19041.746

**Comment by asmtron** [comment] 2021-01-24 09:53
add 10.0.19041.746 (x86) to [rdpwrap.ini](https://github.com/asmtron/rdpwrap/blob/master/res/rdpwrap.ini)

[Download & Install](https://github.com/asmtron/rdpwrap/blob/master/binary-download.md)

**Comment by FlyingDutchman1965** [comment] 2021-01-25 13:37
Thanks asmtron, that works.

**Comment by sebaxakerhtc** [comment] 2022-06-20 12:42
Duplicate of https://github.com/stascorp/rdpwrap/issues/1270

**Closed as completed by sebaxakerhtc** 2022-06-20 12:42 UTC
