### ISSUE TITLE
19045.2486 [not supported]

### ISSUE THREAD

**Issue by JorBen23** [stascorp/rdpwrap#2084] opened 2023-01-13 01:24 UTC
Is not supported on Windows 10 Pro Version 22h2 (Compilation 19045.2486)

Thank you!

**Comment by sashaqwert** [comment] 2023-01-13 05:59
> 19045.2486

This is your Windows version (not `termsrv.dll`) --> incorrect.

Please, attach your RDPConf screenshot and `termsrv.dll`. Also this issue will be closed :)

**Comment by bradhowe** [comment] 2023-01-13 17:54
![image](https://user-images.githubusercontent.com/1062621/212387057-e09b2054-e725-42a8-bef3-c78888fd8102.png)
![image](https://user-images.githubusercontent.com/1062621/212387481-6dba7c7b-c216-49ff-a8b7-6de659c83be2.png)

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/10414122/termsrv.zip)

I am having the similar issue. I have added all exclusions but the listener will not come up.

**Comment by sashaqwert** [comment] 2023-01-13 18:18
@bradhowe thank you!

Correct version is 10.0.19041.2075.

Nerd replace the rdpwrap.ini.

More info in original issue (see next comment). This issue will be closed as duplicate of it.

**Comment by sashaqwert** [comment] 2023-01-13 18:19
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992

**Closed as not planned by sashaqwert** 2023-01-13 18:19 UTC
Labels: duplicate
