### ISSUE TITLE
Win11 Home Listener not listening 10.0.22000.556

### ISSUE THREAD

**Issue by Sugarsama** [stascorp/rdpwrap#1796] opened 2022-03-30 02:41 UTC
Now what should I do, port 3389 I have opened and restarted many times. I guess it's because my operating system is 556, but I don't have a 556 configuration file. Please help me. Thank you
现在我应该怎么办，3389端口我已经打开并且重新启动很多次。我猜可能是我的操作系统是556的原因，但我没有556的配置文件。请帮帮我，谢谢
![QQ截图20220330103014](https://user-images.githubusercontent.com/102638698/160740195-3daa1321-4d4d-46bb-b9f9-bc9db60713f9.png)

**Comment by sashaqwert** [comment] 2022-03-30 05:02
try `net start termService` or reboot.

One `termsrv.dll` version = one issue --> Duplicate of https://github.com/stascorp/rdpwrap/issues/1698

**Comment by sebaxakerhtc** [comment] 2022-03-30 08:49
> Duplicate of #1698

**Closed as completed by sebaxakerhtc** 2022-03-30 08:49 UTC
