### ISSUE TITLE
rdp wrapper  19041.1387 all green but not working

### ISSUE THREAD

**Issue by bubeconee** [stascorp/rdpwrap#1695] opened 2022-01-22 17:25 UTC
hi,
just moved a computer on a different location as well as static ip address.
when i start rdpconf.exe , all is green (see attached) but i can not connect via Remote Desktop Connection.
i Have checked ip address and it is the same, not sure what else to do
please help

![rdp](https://user-images.githubusercontent.com/78028143/150649043-28e27c9b-6e1e-49be-88e6-700323280e9a.jpg)

**Comment by bezik46** [comment] 2022-01-22 18:18
Uninstall, confirm that RD works at all.
Reinstall, update ini, rerun with -r switch to restart after update (or reboot your machine)
Test again

**Comment by sebaxakerhtc** [comment] 2022-01-22 18:30
Duplicate of https://github.com/stascorp/rdpwrap/issues/1630

**Closed as completed by sebaxakerhtc** 2022-01-22 18:30 UTC
