### ISSUE TITLE
Add support for termsrv 6.3.9600.18928

### ISSUE THREAD

**Issue by burluckoff** [stascorp/rdpwrap#418] opened 2018-02-27 01:46 UTC
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/1760917/termsrv.zip)
Dont working...

**Comment by KaterTomi** [comment] 2018-03-11 15:54
Also for me and certainly for many other peoples very important.

**Comment by NMCowboy** [comment] 2018-03-11 21:29
I didn't see this before I replied to Kipfun but I could use this one too. I read the Windows update descriptions but I didn't see anything about RDP. They are getting very sneaky.

**Comment by andydld** [comment] 2018-03-14 15:51
Same problem here.
Two Windows Server 2012 R2 Standard.
Problem since the most current Windows Updates (installed 13.03.2018/14.03.2018)

RDPwrapper 1.6.1 and 1.6.2

Wrapper state: Installed ver. 1.5.0.0
Service state: Running ver. 6.3.9600.18928
Listener state: Listening [not supported]

RDP.ini: 2017.12.27

Reinstall of RDPWrapper doesnt help.

**Comment by lalogago** [comment] 2018-03-14 15:54
Same here
![sin titulo](https://user-images.githubusercontent.com/37376519/37413881-bb7b5324-2786-11e8-917c-249be91cc88e.jpg)

Any ideas?

**Comment by burluckoff** [comment] 2018-03-14 20:39
Only change termsrv.dll file on old version in system32 directory till...
[termsrv18708.zip](https://github.com/stascorp/rdpwrap/files/1813001/termsrv18708.zip)

**Comment by andydld** [comment] 2018-03-14 21:47
I can confirm that the rollback to the older version auf termsrv.dll (like the one burluckoff posted) works with current version of rdpwrappers ini-file.

**Comment by NMCowboy** [comment] 2018-03-15 16:32
Worked great for me also - Thanks. I had to reboot this time and I normally don't have to but then it worked so alls well that ends well.

**Comment by DATUC** [comment] 2018-03-16 13:18
any update for this allready?

**Comment by amrgb** [comment] 2018-03-17 14:27
For the x64 version add the following to the rdpwrap.ini file.

[6.3.9600.18928]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=8B25D
LocalOnlyCode.x64=nopjmp
SingleUserPatch.x64=1
SingleUserOffset.x64=36C09
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=45495
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=5D830
SLInitFunc.x64=New_CSLQuery_Initialize

[6.3.9600.18928-SLInit]
bFUSEnabled.x64       =FA054
lMaxUserSessions.x64  =FA058
bAppServerAllowed.x64 =FA05C
bInitialized.x64      =FA060
bMultimonAllowed.x64  =FA064
bServerSku.x64        =FA068
ulMaxDebugSessions.x64=FA06C
bRemoteConnAllowed.x64=FA070

**Comment by burluckoff** [comment] 2018-03-17 16:56
On server2012 successfull.

**Comment by andydld** [comment] 2018-03-17 20:56
Doesnt work an Windows Server 2012 R2. RDPConf says "fully supported", but the Remotedesktopservice (Termservice) crashes.

**Comment by amrgb** [comment] 2018-03-18 13:40
This is my first rodeo, so I cannot confidently say what may be causing your problems.

Obviously this only works for x64. Depending on how the program reads the information from the ini, it may be possible that it says that it is supported for x86 because it finds the header, even though there is no variables for the x86 case.

Also, you have to be careful with the formatting of the ini file. From what I found, you must have an empty line at the end of the file. If you paste what I posted to the end of the file, it will likely not have that empty line at the end and will fail.

If it's neither of these, it could be something that's dependent on the configuration. Another user reported success on thread #432 

I'll leave my modified ini file to rule out problems with the formatting of the file.

[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/1822694/rdpwrap.zip)

**Comment by andydld** [comment] 2018-03-18 20:03
I confirm that it works under Windows Server 2012 R2.
Thanks @amrgb for the update and the explanation about the "empty line" at the end of the *.ini-file.

**Comment by unbrainwasher** [comment] 2018-03-20 00:46
Windows 8.1x64 and Server 2012R2 seems to work fine. And how about the Win8.1x86-Edition?

**Comment by Rebelpyr7** [comment] 2018-03-20 02:38
@amrgb 

I don't know what you did with your ini file that I didn't do but your's worked on my Windows 8.1 box where my version did not. I can confirm that version of the ini file definitely works.

**Comment by EliezerBee** [comment] 2018-03-20 16:42
@burluckoff, thank you very much for your [**post**](https://github.com/stascorp/rdpwrap/issues/418#issuecomment-373166618). I replaced my existing DLL with yours and RDP Wrap works again after only a reboot! Thank you much!

What is the plan going forward?
  1. Will we need to keep manually swapping out the DLL with each Windows Update?
  2. Assuming RDP Wrap _will_ be updated to get around this issue, will I need to do anything to RDP Wrap to update it?
  3. Will I need to get a new "official" version of the DLL at some point?
  4. Should I disable any of the Windows Updates - either those that are already installed or any future ones?

**Comment by EliezerBee** [comment] 2018-03-20 16:45
@amrgb, regarding your [post](https://github.com/stascorp/rdpwrap/issues/418#issuecomment-373924087), do you mean that's _all_ you changed - or did you _also_ replace your DLL as @burluckoff [recommended](https://github.com/stascorp/rdpwrap/issues/418#issuecomment-373166618)?

**Comment by amrgb** [comment] 2018-03-20 19:37
@EliezerBee 

For the termsrv version 6.3.9600.18928 x64 the only thing you need is my .ini file. No need to replace the dll.

I think many users don't understand how the rdpwrap works. In a nutshell, starting with version 1.5 all that is needed for the rdpwrap to work with newer versions of termsrv is to update the rdpwrap.ini file with the correct offsets for the new version of termsrv. In my first post here you see the kind of information that needs to be added to support a new version.

binarymaster has been updating the .ini file regularly, and when he does it, you can run the update.bat to automaticaly update the new .ini file. In the meantime, we can follow the excellent information he has posted on the mainpage (https://github.com/stascorp/rdpwrap), in particular this link to a video tutorial [(How to find offsets for new termsrv.dll versions)](http://www.youtube.com/watch?v=FiD86tmRBtk), and update the .ini file ourselves. 

That's what I did. It's not overly complicated, but it's tedious. Specially for binarymaster who has to do dozens of versions (I just did for the version I needed). If we learn to this ourserlves, we can then post here to help others and, hopefully, after enough confirmations that it's working binarymaster may use that information to update the official .ini file and save me some time.

**Comment by Flexperte** [comment] 2018-03-21 14:32
Thanks @amrgb your rdpwrap.ini worked perfect (Windows 8.1). 

But I ran into unexpected difficulties replacing the original .ini with yours, as adjusting permissions was not enough because the file was permanently "in use". Worked neither: uninstalling RDP Wrapper, placing your .ini, then installing again - because the installer would overwrite it with the latest official version. Write-protecting the .ini resulted in the installer aborting mid-way. I finally resorted to block the github server in the hosts file - that worked. 

Am I missing something? How do you edit or replace rdpwrap.ini?

**Comment by binarymaster** [comment] 2018-03-21 14:35
> Am I missing something? How do you edit or replace rdpwrap.ini?

https://github.com/stascorp/rdpwrap/commit/180f41197aa6384b918caaec24d2ce17b262b645

**Comment by amrgb** [comment] 2018-03-21 22:16
@Flexperte 

In my case, I just copy and pasted. If I drag the file to the "C:\Programs\RDP Wrapper" folder it fails, which seems odd. But if I copy and paste it on this folder, it works. I made sure that my administrator account is the owner and has full control permission on the original .ini file. 

By the way, this is with rdpwrap working, since I'm doing this through rdp. To load the new .ini you then have to restart the rdpwrap by running the command `RDPWInst -r`. You lose the rdp connection momentarily but it should come back. To be safe, do this step from teamviewer to have a backup access to the remote computer in case the terminal service doesn't come back up.

**Comment by Wajahat234** [comment] 2018-04-11 14:42
![ssssspng](https://user-images.githubusercontent.com/30357439/38623933-507237f0-3dc0-11e8-9f54-d818d1918237.PNG)
i m using windows server 2012 r2  please help me out

**Comment by burluckoff** [comment] 2018-04-11 15:49
See comments, them have answer on your question...

**Comment by Wajahat234** [comment] 2018-04-11 16:07
i have try all the above solutions but i am still getting same error.

**Comment by ivanmara555** [comment] 2018-04-13 07:06
confirm the same problem win8.1x64 ttermsvr.dll 6.3.9600.18928 from 26.01.2018 ... doesnot working !

**Comment by ivanmara555** [comment] 2018-04-13 08:01
the working solution for me win8.1x64  6.3.9600.18928 from 26.01.2018 is add sections to ini file from this post: https://github.com/stascorp/rdpwrap/issues/432 ... please add to ini !

**Comment by DakotaBcn** [comment] 2018-04-16 21:32
thanks @amrgb the ini updated work in Windows 2012R2

**Comment by sjoerdloeve** [comment] 2018-04-26 14:32
Is there already a fix for this problem? Running into the same problems.

**Comment by binarymaster** [comment] 2018-04-26 14:42
PR #436 is pending.

**Comment by TLBM** [comment] 2018-05-01 23:51
Hi!

Tried the modified ini-file on a german Windows 8.1 Pro x64 with all updates, but it is not working anymore though it reads now "[fully supported]". Also tried the one from #432  and the 1nd1g0 commit.
![20180502](https://user-images.githubusercontent.com/11824134/39498196-2c4526d6-4d96-11e8-8fb8-5febbc759bc7.png)

The second user get's a message that a user is already logged-in and that he will be disconnected.
![capture_05022018_011709](https://user-images.githubusercontent.com/11824134/39498202-33e52d28-4d96-11e8-9171-b4c41ddde4ed.png)

**Closed** 2018-05-16 06:59 UTC

**Comment by tangsg** [comment] 2018-10-29 02:48
I also have this problem and have not fixed it yet.

**Comment by easy1481437320** [comment] 2019-04-30 07:46
i m using windows10 Pro please help me out i try run install.bat --> updat.bat --> RDPConf
![123](https://user-images.githubusercontent.com/45909834/56947063-9ad10c00-6b5e-11e9-8e89-bb14a8e2cdf0.PNG)

**Comment by sjoerdloeve** [comment] 2019-04-30 08:00
@easy1481437320 Windows 10 Pro has remote desktop standard available, you can use it without this program. Go to system properties -> remote and set allow remote connections to this computer

**Comment by easy1481437320** [comment] 2019-04-30 08:19
@sjoerdloeve 
Thanks for your quick response，but how can i Multiuser remote login without the tool?
![456](https://user-images.githubusercontent.com/45909834/56948732-9ce99980-6b63-11e9-9f4f-fbc8039b26e2.PNG)

**Comment by sjoerdloeve** [comment] 2019-04-30 08:37
@easy1481437320 Not sure if it's possible to connect multiple users out of the box. But you're responding to an issue for version 6.3.9600.* while your version is 10.0.17134.*. Perhaps you should search for issues with this version number, like: https://github.com/stascorp/rdpwrap/issues/721

**Comment by easy1481437320** [comment] 2019-04-30 08:50
@sjoerdloeve ok thank you for your help

**Comment by easy1481437320** [comment] 2019-04-30 09:27
@sjoerdloeve Thank you so much !!! my problem was solved accroding to #721
