### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by mhtkumar0025** [stascorp/rdpwrap#3275] opened 2024-09-20 10:05 UTC
![Capture](https://github.com/user-attachments/assets/4ef24c49-54f7-40eb-9516-2cd80908aa50)

**Comment by binarymaster** [comment] 2024-09-20 11:03
Duplicate of https://github.com/stascorp/rdpwrap/issues/2840.

**Closed as not planned by binarymaster** 2024-09-20 11:03 UTC
Labels: duplicate
