### ISSUE TITLE
click any key to continue the installation (the console closes)

### ISSUE THREAD

**Issue by pdinxtsatiu** [stascorp/rdpwrap#3400] opened 2024-12-24 03:14 UTC
I'm writing through a translator, so I'm sorry. Opening install.bat I press any key and the console closes. I tried everything, and opened it from the administrator, and turned off the antivirus software, nothing helps. Please, what
![Screenshot_32](https://github.com/user-attachments/assets/1949af7d-272b-4941-b8cf-ba4a7caac4bb)

**Comment by binarymaster** [comment] 2024-12-24 11:08
Duplicate of https://github.com/stascorp/rdpwrap/issues/1592.

**Closed as not planned by binarymaster** 2024-12-24 11:08 UTC
Labels: duplicate

**Comment by pdinxtsatiu** [comment] 2024-12-24 12:01
> Quote reply

but i cant find how to fix my problem(
