### ISSUE TITLE
RDP Wrapper fully supported but cannot remote with multiple user.

### ISSUE THREAD

**Issue by PendekarLaut** [stascorp/rdpwrap#2446] opened 2023-12-14 03:13 UTC
Please help. RDP Wrapper ver 1.5.0.0 ( 10.0.19041.2670 ). 
<img width="217" alt="image" src="https://github.com/stascorp/rdpwrap/assets/153789228/fd86ef6c-e247-4280-ac14-bd3c6e086e6f">

<img width="325" alt="image" src="https://github.com/stascorp/rdpwrap/assets/153789228/905015c6-083a-456b-a950-772654f28247">

here rdpwrap.ini
[rdpwrap.txt](https://github.com/stascorp/rdpwrap/files/13667892/rdpwrap.txt)

**Comment by sashaqwert** [comment] 2023-12-14 06:35
> fully supported but cannot remote with multiple user

A common problem. Usually fixed by restarting the `termService` service, rebooting or reinstalling RDP Wrapper.

Try:
1. Download RDP Wrapper 1.6.2 and extract this to any directory.
2. Place `rdpwrap.ini` in the same directory.
3. Open CMD as administrator
4. Execute this commands
```
cd C:\path\to\directory\
rdpwinst -u -k
rdpwinst -i
```
5. Enjoy!

Original message: https://t.me/rdpwrap/49131

> 10.0.19041.2670

This is your `termsrv.dll` version. One `termsrv.dll` version = ONE opened issue for one architecture. This issue will closed as duplicate.

**Comment by sashaqwert** [comment] 2023-12-14 06:35
Duplicate of https://github.com/stascorp/rdpwrap/issues/2120

**Closed as not planned by sashaqwert** 2023-12-14 06:35 UTC
Labels: duplicate
