### ISSUE TITLE
Help in rdpwrap 1.6.2 and termsrv.dll 10.0.17763.168

### ISSUE THREAD

**Issue by jhugor123** [stascorp/rdpwrap#623] opened 2018-12-21 10:47 UTC
the steps I did to try to make rdpwrap 1.6.2 run with windows 10 1809 (termsrv.dll 10.0.17763.168) were as follows

I downloaded the rdpwrapper file here -> https://github.com/stascorp/rdpwrap/releases/download/v1.6.2/RDPWrap-v1.6.2.zip

-I have decompressed into a folder that will serve as a "server"
-installed with the command install.bat
-apps the installation, I went to the folder c: \ program files \ RDP Wrapper and gave permission to the user that was using

-in the folder I edited the rdpwrap.ini file

-I added the following lines at the end of the file

[10.0.17763.168]
LocalOnlyPatch.x64 = 1
LocalOnlyOffset.x64 = 77941
LocalOnlyCode.x64 = jmpshort
SingleUserPatch.x64 = 1
SingleUserOffset.x64 = 132F9
SingleUserCode.x64 = Zero
DefPolicyPatch.x64 = 1
DefPolicyOffset.x64 = 17F45
DefPolicyCode.x64 = CDefPolicy_Query_eax_rcx
SLInitHook.x64 = 1
SLInitOffset.x64 = 1ABFC
SLInitFunc.x64 = New_CSLQuery_Initialize

[10.0.17763.168-SLInit]
bInicializado.x64 = ECAB0
bServerSku.x64 = ECAB4
lMaxUserSessions.x64 = ECAB8
bAppServerAllowed.x64 = ECAC0
bRemoteConnAllowed.x64 = ECAC4
bMultimonAllowed.x64 = ECAC8
ulMaxDebugSessions.x64 = ECACC
bFUSEnabled.x64 = ECAD0

I saved the ini file.
I ran rdpconf.exe and everything was okay on screen
https://prnt.sc/lxub8o

so I tried to access it with the other user who has remote access permission

Not work!

http://prntscr.com/lxubk9
translate ( the number of connections with this computer is limited .... )

help me please!

**Comment by binarymaster** [comment] 2018-12-21 11:32
Duplicate of #606.

**Closed as completed by binarymaster** 2018-12-21 11:32 UTC
Labels: duplicate

**Comment by jhugor123** [comment] 2018-12-21 13:36
thanks man!

sorry!
