### ISSUE TITLE
Windows 11 PRO 24H2 OS BUILD 10.0.26100.2033 - Cannot connect

### ISSUE THREAD

**Issue by dayspring-dev** [stascorp/rdpwrap#3304] opened 2024-10-11 21:16 UTC
[termsrv-10.0.26100.2033.zip](https://github.com/user-attachments/files/17347466/termsrv-10.0.26100.2033.zip)
[rdpwrap_10.0.22621.4249.txt](https://github.com/user-attachments/files/17347469/rdpwrap_10.0.22621.4249.txt)
![RDPWrapperConfig](https://github.com/user-attachments/assets/edf5a6fe-1b19-45c5-adb3-1338505f7c2a)
![LimittedConnectionCannotConnect](https://github.com/user-attachments/assets/06c4e0e8-58ae-441b-bcd2-b7a9f766726b)
![Window_11_Pro_10 0 26100 2033](https://github.com/user-attachments/assets/5e230328-6fdf-40a2-9821-1efa80a05ac8)

**Comment by dayspring-dev** [comment] 2024-10-11 21:16
Fixed issue with zip file

**Comment by binarymaster** [comment] 2024-10-11 21:19
Attached termsrv.dll version is 10.0.26100.1882, duplicate of https://github.com/stascorp/rdpwrap/issues/3285.

**Closed as not planned by binarymaster** 2024-10-11 21:19 UTC
Labels: duplicate

**Comment by WTFaboutWTC7** [comment] 2024-12-24 11:07
I have version 1.5.0.0. / 10.0.19041.1348 installed under Windows 10 and want to know if I run into issues when I upgrade W10 to W11. Does RDP Wrapper work without any problems under Windows 11? If I look under the RDP Wrapper GitHub repository (https://github.com/stascorp/rdpwrap). "Confirmed working on:" I don't see Windows 11 there.
