### ISSUE TITLE
Can't update. Listener state - not listening

### ISSUE THREAD

**Issue by blazejp1337** [stascorp/rdpwrap#647] opened 2019-01-21 13:28 UTC
Hi guys,

Im trying to set up RDP on my Win10 Home. My listener state shows that its not listening so i was trying to update but it fails:

update.bat run with admin mode

> RDP Wrapper Library v1.6.2
> Installer v2.5
> Copyright (C) Stas'M Corp. 2017
> 
> [*] Checking for updates...
> [*] Current update date: 2015.07.30
> [*] Latest update date:  2018.10.10
> [+] New update is available, updating...
> [+] TermService found (pid 6720).
> [*] No shared services found.
> [*] Terminating service...
> [-] Failed to write INI file.

![przechwytywanie](https://user-images.githubusercontent.com/20696558/51477422-b6bb5980-1d88-11e9-9549-223402fe3fb1.PNG)

AV uninstalled . Win defender disabled.

**Comment by catexis** [comment] 2019-01-22 05:01
Same #194 
After last update of Win10 rdp service not starting. Log from `install.bat`:  
```cmd
PS D:\downloads\RDPWrap-v1.6.2> .\install.bat
RDP Wrapper Library v1.6.2
Installer v2.5
Copyright (C) Stas'M Corp. 2017

[*] Notice to user:
  - By using all or any portion of this software, you are agreeing
  to be bound by all the terms and conditions of the license agreement.
  - To read the license agreement, run the installer with -l parameter.
  - If you do not agree to any terms of the license agreement,
  do not use the software.
[*] Installing...
[*] Terminal Services version: 10.0.17763.168
[-] This version of Terminal Services is not supported.
Try running "update.bat" or "RDPWInst -w" to download latest INI file.
If it doesn't help, send your termsrv.dll to project developer for support.
[+] TermService found (pid 3840).
[*] No shared services found.
[*] Extracting files...
[+] Folder created: C:\Program Files\RDP Wrapper\
[*] Downloading latest INI file...
[+] Latest INI file -> C:\Program Files\RDP Wrapper\rdpwrap.ini
[+] Extracted rdpw64 -> C:\Program Files\RDP Wrapper\rdpwrap.dll
[*] Configuring service library...
[*] Checking dependencies...
[*] Checking CertPropSvc...
[*] Checking SessionEnv...
[*] Terminating service...
[*] Starting TermService...
[-] StartService error (code 1056).
[*] Configuring registry...
[*] Configuring firewall...
ОК.

[+] Successfully installed.
______________________________________________________________

You can check RDP functionality with RDPCheck program.
Also you can configure advanced settings with RDPConf program.

Для продолжения нажмите любую клавишу . . .
```
<img src='https://i.imgur.com/vOYBa9f.png'></img>  
<img src='https://i.imgur.com/jwltEYT.png'></img>

**Comment by binarymaster** [comment] 2019-01-22 06:50
Duplicate of #606.

**Closed as completed by binarymaster** 2019-01-22 06:50 UTC
Labels: duplicate

**Comment by gokul501** [comment] 2019-11-25 09:00
Hi ,

Please help me on this my problem is attached in below screenshot
![image](https://user-images.githubusercontent.com/58165621/69526274-d797a100-0f8f-11ea-8a76-3cbfeccbb1a4.png)
and my windows 10 os details with version details shown in below screenshot
![image](https://user-images.githubusercontent.com/58165621/69526375-0ca3f380-0f90-11ea-86c9-0daeeb95db2c.png)
Please help me how to fix this issue it is needfull
