### ISSUE TITLE
Fail after installing RDPWRAP

### ISSUE THREAD

**Issue by barrycklee** [stascorp/rdpwrap#1874] opened 2022-05-28 07:55 UTC
I have install the  RDPWRAP according to the procedure . But there is not work.

Did any one know why with reference to the below attachment?

![program list](https://user-images.githubusercontent.com/106425438/170816305-2cdacea7-8689-421b-be9b-f8436d62ae1d.JPG)
![Capture](https://user-images.githubusercontent.com/106425438/170816316-2f75c365-45a5-4608-9802-379c62a84226.JPG)

**Comment by sashaqwert** [comment] 2022-05-28 09:19
Duplicate of https://github.com/stascorp/rdpwrap/issues/1823

**Comment by sebaxakerhtc** [comment] 2022-05-29 10:13
> Duplicate of #1823

**Closed as completed by sebaxakerhtc** 2022-05-29 10:13 UTC
