### ISSUE TITLE
10.0.22621.1992 aint supported

### ISSUE THREAD

**Issue by ZhaoyangHan04** [stascorp/rdpwrap#2276] opened 2023-07-14 06:39 UTC

**Comment by sashaqwert** [comment] 2023-07-14 15:40
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by sashaqwert** [comment] 2023-07-14 15:45
Your `termsrv.dll` version is `10.0.22621.1928`

![изображение](https://github.com/stascorp/rdpwrap/assets/24974508/75f45832-dc18-4441-ad16-ed8b7a9ab00b)

**Comment by sashaqwert** [comment] 2023-07-14 15:45
Duplicate of https://github.com/stascorp/rdpwrap/issues/2258

**Closed as not planned by sashaqwert** 2023-07-14 15:45 UTC
Labels: duplicate
