### ISSUE TITLE
Trojan in .zip?

### ISSUE THREAD

**Issue by davejcoyne** [stascorp/rdpwrap#887] opened 2019-09-26 15:42 UTC
Have been having trouble getting RDP Wrapper working correctly.  Downloaded .zip on one machine and ran it unsuccessfully.  Indicators are green, but no go.  I am trying to test on a second machine and get a virus warning when downloading.  Scanners shows the following: 
![Capture](https://user-images.githubusercontent.com/55846990/65703307-8e3fd980-e052-11e9-9f96-4a185816a5d2.PNG)

Is this w32.riskware.rdp a valid component or is it a trojan?

**Comment by talexg** [comment] 2019-09-27 15:42
I'm getting a malware report too.
![image](https://user-images.githubusercontent.com/55889087/65782379-709f6c80-e145-11e9-92bb-b33cf8a47035.png)
Is it AV being overly cautious (similar to reporting perfectly safe password revealers to be malware) or have the files been compromised?

**Comment by eatingsins** [comment] 2019-09-28 16:21
I too would like to know if rdpwrap is safe.

**Comment by sebaxakerhtc** [comment] 2022-04-27 15:05
Duplicate of https://github.com/stascorp/rdpwrap/issues/277

**Closed as completed by sebaxakerhtc** 2022-04-27 15:05 UTC
