### ISSUE TITLE
Terminal Services version: 10.0.19041.4474 not supported

### ISSUE THREAD

**Issue by ce10003** [stascorp/rdpwrap#3373] opened 2024-12-04 17:40 UTC
[*] Installing...
[*] Terminal Services version: 10.0.19041.4474
[-] This version of Terminal Services is not supported.
Try running "update.bat" or "RDPWInst -w" to download latest INI file.   <------------- reports "Everything is up to date"
If it doesn't help, send your termsrv.dll to project developer for support.   <----------- DLL attached as required.. 

[termsrv.zip](https://github.com/user-attachments/files/18012160/termsrv.zip)

**Comment by binarymaster** [comment] 2024-12-04 18:10
Duplicate of https://github.com/stascorp/rdpwrap/issues/2840.

**Closed as not planned by binarymaster** 2024-12-04 18:10 UTC
Labels: duplicate
