### ISSUE TITLE
请问RDPCheck.exe运行之后出现 not supported,如何解决呀版本是：10.0.18362.267

### ISSUE THREAD

**Issue by ghost** [stascorp/rdpwrap#2185] opened 2023-04-29 11:26 UTC
/

**Comment by ghost** [comment] 2023-04-29 11:27
![{E356E78F-DD8D-448A-9A7F-CB192C4846BF}](https://user-images.githubusercontent.com/72814023/235300167-5bdcf0b7-b085-4c10-87e0-79930f2cc03b.png)

**Comment by sashaqwert** [comment] 2023-04-29 17:05
Offsets available here: https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

**Comment by sashaqwert** [comment] 2023-04-29 17:06
Duplicate of https://github.com/stascorp/rdpwrap/issues/871

**Closed as not planned by sashaqwert** 2023-04-29 17:06 UTC
Labels: duplicate
