### ISSUE TITLE
Add support for Build 1803 (17134.523)

### ISSUE THREAD

**Issue by phoenixsampras** [stascorp/rdpwrap#639] opened 2019-01-12 22:49 UTC
Add support for Build 1803 (17134.523)

Thank you!

**Comment by binarymaster** [comment] 2019-01-13 05:56
@phoenixsampras please post diagnostics screenshot.

**Comment by infobel** [comment] 2019-01-13 07:57
Hello, same problem on 2 installs. 1 old, been updated by microsoft update and 1 all new fresh install yesterday with 5 users, this morning broken.

Only one user by RDP.

Screenshot :
[https://ibb.co/hXKjSnc](url)

**Comment by binarymaster** [comment] 2019-01-13 08:30
@infobel you're posting offtopic here.

Take your build number from your screenshot and search an appropriate issue.

**Comment by fre4kyC0de** [comment] 2019-01-14 00:19
AFAIK 2018-12 and 2019-01 didn‘t add any new versions of termsrv.dll

**Comment by megapro17** [comment] 2019-01-14 18:12
uhhm 1809 also not working..

**Comment by megapro17** [comment] 2019-01-14 18:17
If anyone need solution right now https://www.mysysadmintips.com/windows/clients/545-multiple-rdp-remote-desktop-sessions-in-windows-10

**Comment by binarymaster** [comment] 2019-01-15 18:15
No screenshot provided by @phoenixsampras.

> AFAIK 2018-12 and 2019-01 didn‘t add any new versions of termsrv.dll

So this is 90% a duplicate of one of existing issues.

**Closed as completed by binarymaster** 2019-01-15 18:15 UTC
Labels: duplicate
