### ISSUE TITLE
Windows 11 10.0.22621.2066 Supported only 1 session 

### ISSUE THREAD

**Issue by MixtraderARG** [stascorp/rdpwrap#2282] opened 2023-07-17 13:08 UTC
I have fully supported version, but only 1 connection at the time.
And ideas?
![imagen](https://github.com/stascorp/rdpwrap/assets/139776813/4ea4caed-00bd-46fd-9b9f-598607063e90)

**Comment by sashaqwert** [comment] 2023-07-17 17:48
One `termsrv.dll` version = ONE opened issue. This issue will closed as duplicate...

**Comment by sashaqwert** [comment] 2023-07-17 17:49
Duplicate of https://github.com/stascorp/rdpwrap/issues/2278

**Closed as not planned by sashaqwert** 2023-07-17 17:49 UTC
Labels: duplicate

**Comment by sashaqwert** [comment] 2023-07-17 17:50
> I have fully supported version, but only 1 connection at the time.
> And ideas?

Try restart service or reboot

OR

Try:
1. Download RDP Wrapper 1.6.2 and extract this to any directory.
2. Place `rdpwrap.ini` in the same directory.
3. Open CMD as administrator
4. Execute this commands
```
cd C:\path\to\directory\
rdpwinst -u -k
rdpwinst -i
```
5. Enjoy!

Original message: https://t.me/rdpwrap/49131
