### ISSUE TITLE
The number of connections to this computer is limited and all connections are in use right now.

### ISSUE THREAD

**Issue by ImTheNewGuy** [stascorp/rdpwrap#626] opened 2018-12-27 05:41 UTC
Hi all,

I have been struggling with this issue all day. I am getting the error:

> The number of connections to this computer is limited and all connections are in use right now. Try connecting later or contact your system administrator.

I have gone through [this guide](https://troubleshooter.xyz/wiki/fix-the-number-of-connections-to-this-computer-is-limited/) to fix the issue, but it has not resolved the problem. Running the RDPCheck yields the same result as my RDT (see pics).

![rdt error](https://user-images.githubusercontent.com/21069394/50467165-c8ae1480-09f5-11e9-8468-4294adb06a67.png)

![rdt error2](https://user-images.githubusercontent.com/21069394/50467166-c8ae1480-09f5-11e9-9dd6-a14251d7db01.PNG)

![rdt error3](https://user-images.githubusercontent.com/21069394/50467167-c946ab00-09f5-11e9-901f-b1d2183f3cb0.PNG)

Running Windows 10 Pro. Had this working yesterday after my reformat, but when I booted the PC up today it has stopped working and I am getting the error.

Any assistance would be greatly appreciated.

**Comment by MerisaCWC** [comment] 2018-12-27 10:05
The same problem. It seems to be the Windows Update KB 4470502?
Does anyone have any idea what to do to make it work again?

![grafik](https://user-images.githubusercontent.com/46190635/50476157-5de5e480-09c7-11e9-94e2-111e0b94e3b4.png)

**Comment by binarymaster** [comment] 2018-12-27 10:46
Duplicate of #606.

**Closed as completed by binarymaster** 2018-12-27 10:46 UTC
Labels: duplicate
