### ISSUE TITLE
10.0.14393.29066 not listening on Windows 10 Pro

### ISSUE THREAD

**Issue by OnePrg** [stascorp/rdpwrap#2196] opened 2023-05-10 10:13 UTC
I have error "not listening".

I did reinstall, update.

What else can I do?

https://imagizer.imageshack.com/img923/7232/snG31J.png

**Comment by sashaqwert** [comment] 2023-05-10 18:09
> What else can I do?

 You can try modded version by sebaxakerhtc: https://github.com/sebaxakerhtc/rdpwrap/releases

**Comment by sashaqwert** [comment] 2023-05-10 18:10
One `termsrv.dll` version = ONE opened issue.

**Comment by sashaqwert** [comment] 2023-05-10 18:11
Duplicate of https://github.com/stascorp/rdpwrap/issues/723

**Closed as not planned by sashaqwert** 2023-05-10 18:11 UTC
Labels: duplicate
