### ISSUE TITLE
10.0.26100.1882 The number of connection limitted

### ISSUE THREAD

**Issue by minhlieubk** [stascorp/rdpwrap#3343] opened 2024-11-13 19:46 UTC
![image](https://github.com/user-attachments/assets/9c7bb7c5-2320-44a3-ace1-b55f1d1839e1)

it's all green after I put below to rdpwrap.ini

[10.0.26100.1882]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=8AC61
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=9764B
SingleUserCode.x64=mov_eax_1_nop_2
DefPolicyPatch.x64=1
DefPolicyOffset.x64=94A6F
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx_jmp
SLInitHook.x64=1
SLInitOffset.x64=AB2F0
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.26100.1882-SLInit]
bInitialized.x64      =11ADF0
bServerSku.x64        =11ADF4
lMaxUserSessions.x64  =11ADF8
bAppServerAllowed.x64 =11AE00
bRemoteConnAllowed.x64=11AE08
bMultimonAllowed.x64  =11AE0C
ulMaxDebugSessions.x64=11AE14
bFUSEnabled.x64       =11AE18

But it always got error connection limitted when I have tried to do remote even restarted or increased the number of connection.
This issue just happen today when I do upgrade my OS to 24H2. Please advise

**Comment by minhlieubk** [comment] 2024-11-13 19:54
![image](https://github.com/user-attachments/assets/88728ced-36d0-48c6-aa5a-211823581605)

Not sure what is missing. Please advise. Thanks

**Comment by binarymaster** [comment] 2024-11-13 20:23
Contact Telegram support group.

Closing this as duplicate of https://github.com/stascorp/rdpwrap/issues/3285 (one issue per build).

**Closed as not planned by binarymaster** 2024-11-13 20:23 UTC
Labels: duplicate
