### ISSUE TITLE
Not supported 10.0.22000.653

### ISSUE THREAD

**Issue by Skrillen** [stascorp/rdpwrap#1875] opened 2022-05-28 11:23 UTC
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/8791028/termsrv.zip)

**Comment by sashaqwert** [comment] 2022-05-28 16:22
Duplicate of https://github.com/stascorp/rdpwrap/issues/1843

**Closed as completed** 2022-05-28 22:16 UTC
