### ISSUE TITLE
10.0.22621.674 [not supported]

### ISSUE THREAD

**Issue by deng947** [stascorp/rdpwrap#2134] opened 2023-03-03 01:17 UTC
10.0.22621.674 [not supported]

**Comment by sashaqwert** [comment] 2023-03-03 06:14
Duplicate of https://github.com/stascorp/rdpwrap/issues/2006

**Comment by sashaqwert** [comment] 2023-03-03 06:15
`termsrv.dll` version ≠ Windows version!

**Closed as not planned by sashaqwert** 2023-03-03 06:14 UTC
Labels: duplicate
