### ISSUE TITLE
rdp wrapper x64 10.0.19041.3271 not supported on win10 

### ISSUE THREAD

**Issue by 17886365143** [stascorp/rdpwrap#2413] opened 2023-11-17 09:13 UTC

**Comment by sashaqwert** [comment] 2023-11-18 06:17
Duplicate of https://github.com/stascorp/rdpwrap/issues/2289

**Closed as not planned by sashaqwert** 2023-11-18 06:17 UTC
Labels: duplicate

**Comment by sashaqwert** [comment] 2023-11-18 06:18
![изображение](https://github.com/stascorp/rdpwrap/assets/24974508/b2e68a8d-63a1-4e0d-9e65-f084f9f00132)
