### ISSUE TITLE
Windows 10 19043.985 not supported

### ISSUE THREAD

**Issue by julianlandthaler** [stascorp/rdpwrap#1402] opened 2021-05-21 10:01 UTC
Hi guys,

can someone please help me out?

Thanks!

**Comment by ChocalateWZLH** [comment] 2021-05-21 15:58
Hi guys,

can someone please help me out?

Thanks!

**Comment by zekecarter** [comment] 2021-05-22 23:30
TESTED
windows 21h1
compilation 10.0.19043.985 x64

[10.0.19043.985]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=89F31
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0CB22
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=18A15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=1E29C
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.19043.985-SLInit]
bInitialized.x64      =107108
bServerSku.x64        =10710C
lMaxUserSessions.x64  =107110
bAppServerAllowed.x64 =107118
bRemoteConnAllowed.x64=107120
bMultimonAllowed.x64  =107124
ulMaxDebugSessions.x64=107128
bFUSEnabled.x64       =10712C

**Comment by rafaferreirasantos** [comment] 2021-05-23 01:25
https://github.com/stascorp/rdpwrap/issues/1397

**Comment by batero2000** [comment] 2021-05-23 23:51
Hi, I'm having issues too since I updated to 21H1, can't use RDP Wapper, I also have 19043.985 winver. Does someone have the working .ini file?

**Comment by jefeana** [comment] 2021-05-24 11:37
all month the same problem, if some one can sale a final solution for us

**Comment by batero2000** [comment] 2021-05-24 23:47
> TESTED
> windows 21h1
> compilation 10.0.19043.985 x64
> 
> [10.0.19043.985]
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=89F31
> LocalOnlyCode.x64=jmpshort
> SingleUserPatch.x64=1
> SingleUserOffset.x64=0CB22
> SingleUserCode.x64=Zero
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=18A15
> DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> SLInitHook.x64=1
> SLInitOffset.x64=1E29C
> SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.19043.985-SLInit]
> bInitialized.x64 =107108
> bServerSku.x64 =10710C
> lMaxUserSessions.x64 =107110
> bAppServerAllowed.x64 =107118
> bRemoteConnAllowed.x64=107120
> bMultimonAllowed.x64 =107124
> ulMaxDebugSessions.x64=107128
> bFUSEnabled.x64 =10712C

That doesn't work for me, idk why RDP Wrapper conf now is showing me my previous winver (19041) even though I've updated to 21H1 (19043).

**Comment by sebaxakerhtc** [comment] 2022-06-20 13:23
Duplicate of https://github.com/stascorp/rdpwrap/issues/1384

**Closed as completed by sebaxakerhtc** 2022-06-20 13:23 UTC
