### ISSUE TITLE
Bro..

### ISSUE THREAD

**Issue by B3ni15** [stascorp/rdpwrap#2576] opened 2024-04-16 13:07 UTC
https://www.virustotal.com/gui/file/35a9481ddbed5177431a9ea4bd09468fe987797d7b1231d64942d17eb54ec269?nocache=1

**Comment by sashaqwert** [comment] 2024-04-17 16:38
Duplicate of https://github.com/stascorp/rdpwrap/issues/277

**Closed as not planned by sashaqwert** 2024-04-17 16:38 UTC
