### ISSUE TITLE
win11 PRO ver. 10.0.22000.469 does not work even with the .ini patch

### ISSUE THREAD

**Issue by kursatu** [stascorp/rdpwrap#1741] opened 2022-02-23 00:14 UTC
I can't have multiple users login at the same time.
Applied the patch here, it did not make any difference.
https://github.com/stascorp/rdpwrap/issues/1707
With the patch, it reads not listening
W/o the patch , it seems fine but it does not really work
![image](https://user-images.githubusercontent.com/1686475/155241550-357c8b2d-ab08-423e-a33b-8cc7ee8ce3cb.png)

**Comment by proactivepcc** [comment] 2022-02-24 05:06
I'm experiencing the same issue.  Listener fully supported and connection does work, but does not allow multiple connections.  RDP connection always kicks out local user.  Same is happening with sebaxakerhtc's mod.

Windows 10 seems to still work, just Windows 11 issue.

**Comment by sebaxakerhtc** [comment] 2022-02-24 08:17
Duplicate of https://github.com/stascorp/rdpwrap/issues/1698

**Closed as completed by sebaxakerhtc** 2022-02-24 08:17 UTC

**Comment by kursatu** [comment] 2022-02-25 05:08
@sebaxakerhtc Please reopen this issue. As @proactivepcc also stated, it is not fixed nor a duplicate of the other one.

**Comment by sebaxakerhtc** [comment] 2022-02-25 05:54
> @sebaxakerhtc Please reopen this issue. As @proactivepcc also stated, it is not fixed nor a duplicate of the other one.

1 version of termsrv.dll = 1 issue
https://github.com/stascorp/rdpwrap/issues/1698#issuecomment-1030679727
Also
https://github.com/stascorp/rdpwrap/issues/1698#issuecomment-1033735078

**Comment by sebaxakerhtc** [comment] 2022-02-25 09:02
> @sebaxakerhtc Please reopen this issue. As @proactivepcc also stated, it is not fixed nor a duplicate of the other one.


![22000 469](https://user-images.githubusercontent.com/32651506/155686397-d938bbdd-9cfc-4d2a-bd6f-3c124a1ee7a4.png)
