### ISSUE TITLE
Windows 11 Pro 10.0.22621.3672, Stopped and Not listening!!

### ISSUE THREAD

**Issue by manuel231509** [stascorp/rdpwrap#3103] opened 2024-06-02 15:13 UTC
![image](https://github.com/stascorp/rdpwrap/assets/75493236/73f31d92-e396-4004-80f5-e0e92982070c)

**Comment by binarymaster** [comment] 2024-06-03 17:12
Duplicate of #2833.

**Closed as not planned by binarymaster** 2024-06-03 17:12 UTC
Labels: duplicate

**Comment by lenkunz** [comment] 2024-07-11 18:00
> Duplicate of #2833.

Not that duplicate. It said supported which mean they have updated the rdpwrap.ini

I suggest you to copy entire rdpwrap.ini and try again. Seems like wrapper crash at the start.
