### ISSUE TITLE
Termsrv.dll for Windows 10 version 10.0.18362.267

### ISSUE THREAD

**Issue by nvdkzyp** [stascorp/rdpwrap#2149] opened 2023-03-19 06:15 UTC
Termsrv.dll for Windows 10 version 10.0.18362.267

[Uploading termsrv.zip…]()

**Comment by nvdkzyp** [comment] 2023-03-19 06:19
Although it still appears as not supported in Listener state, it is possible for multiple users to log in simultaneously.
![捕获](https://user-images.githubusercontent.com/85109133/226157315-afe5b986-5e6e-4b36-afdf-56c37e71efd7.PNG)

**Comment by sashaqwert** [comment] 2023-03-19 08:55
Duplicate of https://github.com/stascorp/rdpwrap/issues/871

**Closed as not planned by sashaqwert** 2023-03-19 08:55 UTC
Labels: duplicate
