### ISSUE TITLE
Add support for build 10.0.17763.316

### ISSUE THREAD

**Issue by redlin46** [stascorp/rdpwrap#667] opened 2019-02-14 20:35 UTC

**Comment by hookymd** [comment] 2019-02-14 23:46
I am waiting for solution.
I edited and replaced rdpwrap.ini and termsrv.dll
RDPConf is green.
But all PDP connections are connected to one (Administrator) - Mirror

**Comment by Binhbnt** [comment] 2019-02-15 01:27
Please add support for Windows 10 1809 - Windows10_Version_1809.Build_17763.316_x64. I have attached the termsrv.dll file. Thanks
[termsrv-Windows10_Version_1809.Build_17763.316_x64.zip](https://github.com/stascorp/rdpwrap/files/2867425/termsrv-Windows10_Version_1809.Build_17763.316_x64.zip)

**Comment by butaford** [comment] 2019-02-15 06:19
> Please add support for Windows 10 1809 - Windows10_Version_1809.Build_17763.316_x64. I have attached the termsrv.dll file. Thanks
> [termsrv-Windows10_Version_1809.Build_17763.316_x64.zip](https://github.com/stascorp/rdpwrap/files/2867425/termsrv-Windows10_Version_1809.Build_17763.316_x64.zip)

Му version windows and termsrv.dll
![2019-02-15_091527](https://user-images.githubusercontent.com/5542160/52838092-7d190c80-3102-11e9-88ee-c4e7c928936f.jpg)
Your version termsrv.dll 
![2019-02-15_091547](https://user-images.githubusercontent.com/5542160/52838108-8efaaf80-3102-11e9-8a6e-d8f7e699a378.jpg)

Working  rdpwrap.ini
[rdpwrap.ini.zip](https://github.com/stascorp/rdpwrap/files/2868032/rdpwrap.ini.zip)

**Comment by moaeddy** [comment] 2019-02-15 06:44
thanks @butaford your solution works for me after doing everything others have put up

**Comment by Redshoee** [comment] 2019-02-15 07:07
@butaford 's solution is working for me for the first.
but after I rerun the install and do the same step ,it wont work anymore.
![image](https://user-images.githubusercontent.com/8359308/52840377-0563d580-3134-11e9-8a11-366e3cbc2504.png)

[termsrv292.zip](https://github.com/stascorp/rdpwrap/files/2868096/termsrv292.zip)

**Comment by Binhbnt** [comment] 2019-02-15 07:37
> > Please add support for Windows 10 1809 - Windows10_Version_1809.Build_17763.316_x64. I have attached the termsrv.dll file. Thanks
> > [termsrv-Windows10_Version_1809.Build_17763.316_x64.zip](https://github.com/stascorp/rdpwrap/files/2867425/termsrv-Windows10_Version_1809.Build_17763.316_x64.zip)
> 
> Му version windows and termsrv.dll
> ![2019-02-15_091527](https://user-images.githubusercontent.com/5542160/52838092-7d190c80-3102-11e9-88ee-c4e7c928936f.jpg)
> Your version termsrv.dll
> ![2019-02-15_091547](https://user-images.githubusercontent.com/5542160/52838108-8efaaf80-3102-11e9-8a6e-d8f7e699a378.jpg)
> 
> Working rdpwrap.ini
> [rdpwrap.ini.zip](https://github.com/stascorp/rdpwrap/files/2868032/rdpwrap.ini.zip)

Sorry! Always not working, i try copy rdrwrap.ini no working!
![image](https://user-images.githubusercontent.com/31411996/52841550-3097f600-312f-11e9-9b05-c41a27c231fb.png)

**Comment by moaeddy** [comment] 2019-02-15 07:42
did u replace termsrv.dll in c:\windows\system32 ? wherever u running it from make sure u net stop "termservice" /y delete any existing termsrv.dll in system32 and replace with the one posted here, also delete any rdpwrap.ini in c:\program files\rdpwrapper and replace with the one posted here then net start "termservice" /y

see how that goes

**Comment by hookymd** [comment] 2019-02-15 08:49
I am replaced by termsrv.dll and rdpwrap.ini on 2 PC (unrelated)
Does not work.
When the user starts the RDP, he disables the Administrator and they both see the same screen.

**Comment by redlin46** [comment] 2019-02-15 08:49
Goigin to try that one @moaeddy  Got 12 systems down ... lol

**Comment by wendy2702** [comment] 2019-02-15 12:46
Hi,

I'm using this WIN Version:

![image](https://user-images.githubusercontent.com/33424168/52857502-a7c98c00-3127-11e9-8d73-dee22a52bbbb.png)

And latest Version of RDP Wrapper which was not working.

After stopping the termservice, copying the rdpwrap.ini, start termservice i'm able to use RDP.

Please remember that you need to stop the termservice as administrator.

Br

**Comment by Redshoee** [comment] 2019-02-15 13:43
1. execute uninstall.bat
2. delete C:\Program Files\RDP Wrapper manually
3. now use RDPConf.exe to check the original rdp is working .
4. execute install.bat
5. replace the ini file that @butaford  provide
6.  now use RDPConf.exe to check should all working.
all of the step should run as administrator.

![image](https://user-images.githubusercontent.com/8359308/52860548-b6856280-316a-11e9-8862-fb2032528341.png)

**Comment by binarymaster** [comment] 2019-02-15 16:06
Duplicate of #645.

**Closed as completed by binarymaster** 2019-02-15 16:06 UTC
Labels: duplicate

**Comment by JEmlay** [comment] 2019-02-16 00:14
So in other words...Windows 10.0.17763.316 works just fine with .292 INI.  Working fine here, thanks for .292 config!

**Comment by maro55** [comment] 2019-02-24 13:37
@JEmlay  - not quite:
On Windows 10.0.17763.316, did whole procedure of @Redshoee and got to the same all-green status, however: 
1) does still not allow for concurrent remote sessions (need to log out other user)
2) after restart of machine, TermService tries to start but then stops; restarting the service stops it immediately again, so RDPconf consistently sqys service state = stopped (and not listening)

**Comment by JEmlay** [comment] 2019-02-24 15:40
> @JEmlay - not quite:
> On Windows 10.0.17763.316, did whole procedure of @Redshoee and got to the same all-green status, however:
> 
> 1. does still not allow for concurrent remote sessions (need to log out other user)
> 2. after restart of machine, TermService tries to start but then stops; restarting the service stops it immediately again, so RDPconf consistently sqys service state = stopped (and not listening)

Works perfectly fine for me on all existing deployments as well as new deployments. Over 300 machines.  Maybe stop doing “whole procedure of redshoee”.  There’s nothing to do.  Just install RDPWrapper and update the INI.

**Comment by axel237** [comment] 2019-02-26 15:16
Thanks @butaford for the .INI provided, im on build 17763.316 and now working perfectly.

What i did:
1)Download .ini file provided by @butaford: [rdpwrap.ini.zip](https://github.com/stascorp/rdpwrap/files/2868032/rdpwrap.ini.zip)
2) Uninstall existing rdp from Uninstall.bat open as administrator
3) Install.bat as an admin
4) Go to C:\program files\RDP Wrapper
5) Open task manager -> "Services" tab -> find TermService ->right click stop
6) Replace the .ini provided or change the name of the previous to rdpwrapbak.ini
7) Go again to services -> TermService -> right click Start
8) To check: open RDPConf.exe and see if its green "installed" "Running" "Listening" and [Fully Supported]

Now its working perfectly for me via internet.

Cheers

**Comment by maro55** [comment] 2019-03-01 11:34
> Thanks @butaford for the .INI provided, im on build 17763.316 and now working perfectly.
> 
> What i did:
> 1)Download .ini file provided by @butaford: [rdpwrap.ini.zip](https://github.com/stascorp/rdpwrap/files/2868032/rdpwrap.ini.zip)
> 2) Uninstall existing rdp from Uninstall.bat open as administrator
> 3) Install.bat as an admin
> 4) Go to C:\program files\RDP Wrapper
> 5) Open task manager -> "Services" tab -> find TermService ->right click stop
> 6) Replace the .ini provided or change the name of the previous to rdpwrapbak.ini
> 7) Go again to services -> TermService -> right click Start
> 8) To check: open RDPConf.exe and see if its green "installed" "Running" "Listening" and [Fully Supported]
> 
> Now its working perfectly for me via internet.
> 
> Cheers

Did exactly the above on .316, once more, after a fresh restart with only 1 admin and no other users logged on, and this now seems to work indeed! (no clue what was different in my previous reported attempt)
(still to check if it survives reboot from here though, but not seeing any TermService self-stopping behaviour anymore now)

**Comment by idamcevski** [comment] 2019-04-12 14:11
> > > Please add support for Windows 10 1809 - Windows10_Version_1809.Build_17763.316_x64. I have attached the termsrv.dll file. Thanks
> > > [termsrv-Windows10_Version_1809.Build_17763.316_x64.zip](https://github.com/stascorp/rdpwrap/files/2867425/termsrv-Windows10_Version_1809.Build_17763.316_x64.zip)
> > 
> > 
> > Му version windows and termsrv.dll
> > ![2019-02-15_091527](https://user-images.githubusercontent.com/5542160/52838092-7d190c80-3102-11e9-88ee-c4e7c928936f.jpg)
> > Your version termsrv.dll
> > ![2019-02-15_091547](https://user-images.githubusercontent.com/5542160/52838108-8efaaf80-3102-11e9-8a6e-d8f7e699a378.jpg)
> > Working rdpwrap.ini
> > [rdpwrap.ini.zip](https://github.com/stascorp/rdpwrap/files/2868032/rdpwrap.ini.zip)
> 
> Sorry! Always not working, i try copy rdrwrap.ini no working!
> ![image](https://user-images.githubusercontent.com/31411996/52841550-3097f600-312f-11e9-9b05-c41a27c231fb.png)



> > Please add support for Windows 10 1809 - Windows10_Version_1809.Build_17763.316_x64. I have attached the termsrv.dll file. Thanks
> > [termsrv-Windows10_Version_1809.Build_17763.316_x64.zip](https://github.com/stascorp/rdpwrap/files/2867425/termsrv-Windows10_Version_1809.Build_17763.316_x64.zip)
> 
> Му version windows and termsrv.dll
> ![2019-02-15_091527](https://user-images.githubusercontent.com/5542160/52838092-7d190c80-3102-11e9-88ee-c4e7c928936f.jpg)
> Your version termsrv.dll
> ![2019-02-15_091547](https://user-images.githubusercontent.com/5542160/52838108-8efaaf80-3102-11e9-8a6e-d8f7e699a378.jpg)
> 
> Working rdpwrap.ini
> [rdpwrap.ini.zip](https://github.com/stascorp/rdpwrap/files/2868032/rdpwrap.ini.zip)

Confirmed, working on the build specified LTSC
