### ISSUE TITLE
Windows 10.0.18362.388 becomes unresponsive with multiple RDP connections

### ISSUE THREAD

**Issue by itsAllDigital** [stascorp/rdpwrap#899] opened 2019-10-08 11:14 UTC
I'm running a Windows 10 (Pro) kvm on my home server. I access it over an openvpn connection.

When only one user connects to it everything works fine.
Multiple users work until everyone disconnects without logging out.
Trying to login again (no matter which user) ends in a login loop as the connection prompt will not go passt trying to configure the connection.

In the kvm manager the vm has also become unresponsive to any action (ACPI calls being ignored as well)

Wrapper Version: 1.5.0.0
Service Version: 10.0.18362.267

Authentication Mode is the default rdp authentication.
Shadowing mode is full access with user's permission.

Attached is the rdpwrap.ini I'm using.
[rdpwrap.txt](https://github.com/stascorp/rdpwrap/files/3702079/rdpwrap.txt)

**Comment by s0nic9** [comment] 2019-10-08 11:27
https://github.com/stascorp/rdpwrap/issues/858#issuecomment-523192537

**Comment by sebaxakerhtc** [comment] 2022-06-20 10:13
Duplicate of https://github.com/stascorp/rdpwrap/issues/871

**Closed as completed by sebaxakerhtc** 2022-06-20 10:13 UTC
