### ISSUE TITLE
windows10 ver 10.0.19041.3271,Not listening fully supported. try to update but it didn't work

### ISSUE THREAD

**Issue by gujiaping** [stascorp/rdpwrap#2323] opened 2023-08-30 12:46 UTC

**Comment by southfanning** [comment] 2023-08-30 18:51
Same issue on win10 v10.0.19045

**Comment by sashaqwert** [comment] 2023-08-31 09:19
Duplicate of https://github.com/stascorp/rdpwrap/issues/2289

**Closed as not planned by sashaqwert** 2023-08-31 09:19 UTC
Labels: duplicate
