### ISSUE TITLE
help with the problem, I have not found a way to solve it on the Internet

### ISSUE THREAD

**Issue by Popaba312s** [stascorp/rdpwrap#3263] opened 2024-09-01 11:57 UTC
![2024-09-01_14-56-57](https://github.com/user-attachments/assets/ca6d417c-1828-40bd-82b4-3b1586b34d39)

**Comment by binarymaster** [comment] 2024-09-01 12:16
Duplicate of #1618.

**Closed as not planned by binarymaster** 2024-09-01 12:16 UTC
Labels: duplicate
