### ISSUE TITLE
Singe user multiple sessions - cannot disable

### ISSUE THREAD

**Issue by amberzombie** [stascorp/rdpwrap#2163] opened 2023-04-05 05:25 UTC
Since the latest wrapper update, for some reason users can be connected to RDP multiple times, which causes issues with software like Outlook (ost file already open)

Is there a way to kill the option to allow multiple sessions per user?

Note - in RDP Wrapper config, single session per user box is ticked
<img width="413" alt="Screenshot 2023-04-05 at 3 40 12 pm" src="https://user-images.githubusercontent.com/129928504/229990843-3f801dae-0dbf-4c50-b9c5-aa2220e268c4.png">

**Comment by sashaqwert** [comment] 2023-04-05 07:34
Try:
1. Download RDP Wrapper 1.6.2 and extract this to any directory.
2. Place `rdpwrap.ini` in the same directory.
3. Open CMD as administrator
4. Execute this commands
```
cd C:\path\to\directory\
rdpwinst -u -k
rdpwinst -i
```
5. Enjoy!

Original message: https://t.me/rdpwrap/49131

**Comment by sashaqwert** [comment] 2023-04-05 07:35
One `termsrv.dll` version = one opened issue.

**Comment by sashaqwert** [comment] 2023-04-05 07:36
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992

**Closed as not planned by sashaqwert** 2023-04-05 07:36 UTC
Labels: duplicate
