### ISSUE TITLE
Not supported 10.0.19041.1503

### ISSUE THREAD

**Issue by Vedmed2022** [stascorp/rdpwrap#1837] opened 2022-05-07 05:31 UTC
Please Help me!
Not supported 10.0.19041.1503
![RDP](https://user-images.githubusercontent.com/105096734/167239983-02fa037d-4ff2-477d-9389-eca4ab4a86a3.png)

**Comment by sebaxakerhtc** [comment] 2022-05-07 21:17
Duplicate of https://github.com/stascorp/rdpwrap/issues/1697

**Closed as completed by sebaxakerhtc** 2022-05-07 21:17 UTC
