### ISSUE TITLE
VirusTotal - 43 engines detected this file Trojan.Autoruns.*

### ISSUE THREAD

**Issue by angelperezleon** [stascorp/rdpwrap#1047] opened 2020-04-07 09:03 UTC
https://www.virustotal.com/gui/file/35a9481ddbed5177431a9ea4bd09468fe987797d7b1231d64942d17eb54ec269/detection

**Comment by daveybops** [comment] 2020-04-07 10:45
Similarly, Firefox warning "This file contains a virus or malware".
EDIT: Antivirus apps (and Firefox) detecting this as a virus since it has been used by attackers https://news.softpedia.com/news/danabot-banking-trojan-moves-to-europe-adds-rdp-and-64-bit-support-522842.shtml (in the same way that nirsoft's apps are "viruses").

**Comment by daveybops** [comment] 2020-04-07 11:06
Multiple issues opened over the same problem.  Sure this will be closed shortly as a duplicate.  Original Issue ID #227 still showing as opened.  Copying my comments to the original Issue ID. SHA256 and a statement from the developer on the home-page nice to have.

**Comment by sebaxakerhtc** [comment] 2022-04-27 15:59
Duplicate of https://github.com/stascorp/rdpwrap/issues/277

**Closed as completed by sebaxakerhtc** 2022-04-27 15:59 UTC
