### ISSUE TITLE
W11 Build 22631.4169 Not Listening

### ISSUE THREAD

**Issue by CURSRvlre** [stascorp/rdpwrap#3289] opened 2024-10-03 19:10 UTC
Following .ini just fixed **Not Supported** -> **Fully Supporter** | _Listener still "Not Listening"_
[rdpwrap.ini.txt](https://github.com/user-attachments/files/17248919/rdpwrap.ini.txt)
Screenshot:
![Screenshot 2024-10-03 210834](https://github.com/user-attachments/assets/99f5db29-8467-4d65-85b7-2354d6dd1a5c)

**Comment by loyejaotdiqr47123** [comment] 2024-10-06 03:24
Please, attach your  termsrv.dll.

**Comment by franciscoalcibar** [comment] 2024-10-11 23:11
[10.0.22621.3958]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=9EFB1
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=C503
SingleUserCode.x64=mov_eax_1_nop_2
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1C415
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=2C040
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.22621.3958-SLInit]
bInitialized.x64=12DF6C
bServerSku.x64=12DF70
lMaxUserSessions.x64=12DF74
bAppServerAllowed.x64=12DF78
bRemoteConnAllowed.x64=12DF84
bMultimonAllowed.x64=12DF88
ulMaxDebugSessions.x64=12DF90
bFUSEnabled.x64=12DF94

**Comment by CURSRvlre** [comment] 2024-10-18 22:21
https://gist.github.com/CURSRvlre/3f4d8711f77c765f806ac93ae7fe5a73
it's in here (too long)
my RDPwrapper.ini

**Comment by binarymaster** [comment] 2024-10-18 22:37
The working solution should be here: https://github.com/stascorp/rdpwrap/issues/3238#issuecomment-2252092213

**Comment by loyejaotdiqr47123** [comment] 2024-10-19 03:02
Duplicate of #3238

**Closed as not planned** 2024-10-19 15:07 UTC
Labels: duplicate
