### ISSUE TITLE
Windows 10 19045.3208 not support

### ISSUE THREAD

**Issue by MihanLee** [stascorp/rdpwrap#2281] opened 2023-07-17 03:23 UTC
Hi 

There is a new revision of Windows 10.
![20230717104032](https://github.com/stascorp/rdpwrap/assets/53245837/56a25c0c-6a88-41f0-b55b-3549b97db5e0)

need a new file for it, thank you.

**Comment by sashaqwert** [comment] 2023-07-17 17:46
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by sashaqwert** [comment] 2023-07-17 17:58
`termsrv.dll` version != Windows version! You can find this in RDPConf.

![изображение](https://github.com/stascorp/rdpwrap/assets/24974508/af9a6eed-4cb8-43d3-a8f2-2a2c1696dfa5)

**Comment by sashaqwert** [comment] 2023-07-17 17:59
Duplicate of https://github.com/stascorp/rdpwrap/issues/2257

**Closed as not planned by sashaqwert** 2023-07-17 17:59 UTC
Labels: duplicate
