### ISSUE TITLE
10.0.19045.4412

### ISSUE THREAD

**Issue by sbjw** [stascorp/rdpwrap#2612] opened 2024-05-15 01:14 UTC
after windows update , the version is changed，now the version of 10.0.19045.4412 is not support.

**Comment by sashaqwert** [comment] 2024-05-15 11:27
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by ascendingnode112** [comment] 2024-05-15 18:09
I have the same issue. Please find attached the screenshot but how do I attach the dll file?
![image](https://github.com/stascorp/rdpwrap/assets/169935099/2e39150a-185d-41cb-935a-5f806faed85c)

**Comment by servitec366** [comment] 2024-05-16 05:07
![366](https://github.com/stascorp/rdpwrap/assets/165140094/82c9a4c8-e820-43e1-bc34-e7f72d9fa627)
apoyo por favor

**Comment by ghost** [comment] 2024-05-16 05:37
same problem here,  10.0.19045.4412
termsrv.dll file
https://file.io/f5taNlSwwA9e

![Zrzut ekranu 2024-05-16 073256](https://github.com/stascorp/rdpwrap/assets/62281641/a764927b-9e89-4a36-a7dd-0deb72288803)
 
![Zrzut ekranu 2024-05-16 073220](https://github.com/stascorp/rdpwrap/assets/62281641/17f2fb2e-3fc4-4c0e-a510-ad7ba841cc4c)

**Comment by LonchakovAV** [comment] 2024-05-16 11:53
Windows 10 Pro x64  22H2 19045.4412
I haven't checked other versions of termsrv.dll.
![image](https://github.com/stascorp/rdpwrap/assets/45339400/227b534c-ebaa-4502-8df4-10e58b1c4b51)

**Comment by ghost** [comment] 2024-05-16 16:19
For me the solution was this workaround. I hope it will work for you as well.
https://github.com/sebaxakerhtc/rdpwrap/releases/tag/v1.8.9.9

But you can try that one solution if above will fail (4355 has same offsets as 4353)
https://github.com/stascorp/rdpwrap/issues/2590#issuecomment-2075033988

**Comment by tuanhd8789** [comment] 2024-05-17 01:47
> For me the solution was this workaround. I hope it will work for you as well. https://github.com/sebaxakerhtc/rdpwrap/releases/tag/v1.8.9.9
> 
> But you can try that one solution if above will fail (4355 has same offsets as 4353) [#2590 (comment)](https://github.com/stascorp/rdpwrap/issues/2590#issuecomment-2075033988)

Virus detected on my computer.

**Comment by rioda-org** [comment] 2024-05-19 15:37
> > For me the solution was this workaround. I hope it will work for you as well. https://github.com/sebaxakerhtc/rdpwrap/releases/tag/v1.8.9.9
> > But you can try that one solution if above will fail (4355 has same offsets as 4353) [#2590 (comment)](https://github.com/stascorp/rdpwrap/issues/2590#issuecomment-2075033988)
> 
> Virus detected on my computer.

I have not gone through the code, but it makes sense that Windows labels it as virus, because you are editing the system to have Windows Server functionality.

**Comment by sashaqwert** [comment] 2024-05-21 11:03
Duplicate of https://github.com/stascorp/rdpwrap/issues/2590

**Closed as not planned by sashaqwert** 2024-05-21 11:03 UTC
Labels: duplicate
