### ISSUE TITLE
rdp wrapper don't work 10.0.19041.2075

### ISSUE THREAD

**Issue by neovoesp** [stascorp/rdpwrap#2030] opened 2022-10-23 19:33 UTC
![image](https://user-images.githubusercontent.com/116518481/197413768-efd6c41f-f676-40e4-92e9-70b3bfeb9ea2.png)

I have all in green but don't work . i only can conect 1 session.

**Comment by sashaqwert** [comment] 2022-10-24 05:24
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992

**Comment by sashaqwert** [comment] 2022-10-24 05:25
Try:
1. Download RDP Wrapper 1.6.2 and extract this to any directory.
2. Place `rdpwrap.ini` in the same directory.
3. Open CMD as administrator
4. Execute this commands
```
cd C:\path\to\directory\
rdpwinst -u -k
rdpwinst -i
```
5. Enjoy!

Original message: https://t.me/rdpwrap/49131

**Closed as not planned by sashaqwert** 2022-10-24 05:24 UTC
Labels: duplicate
