### ISSUE TITLE
Need help: 10.0.22621.900

### ISSUE THREAD

**Issue by SnowUnderwater** [stascorp/rdpwrap#2065] opened 2022-12-11 10:51 UTC
Need rdpwrap.ini .

**Comment by SnowUnderwater** [comment] 2022-12-11 10:52
Thank you.

**Comment by sashaqwert** [comment] 2022-12-11 12:13
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by sashaqwert** [comment] 2022-12-11 12:32
`termsrv.dll` version != Windows version.

![изображение](https://user-images.githubusercontent.com/24974508/206903637-88365eb8-336f-470e-a554-a29414cf957b.png)

Your version: 10.0.22621.608

**Comment by sashaqwert** [comment] 2022-12-11 12:33
Duplicate of https://github.com/stascorp/rdpwrap/issues/2006

**Closed as not planned by sashaqwert** 2022-12-11 12:33 UTC
Labels: duplicate

**Comment by SnowUnderwater** [comment] 2022-12-15 09:43
Thank you. It can run now!
That's right:
![](http://22c-files-1.wdfiles.com/local--files/files%3Ahelloosme/rdp-termsrv)
