### ISSUE TITLE
Latest ini file update 2018-05-16 does not work with Windows Home 10.0.17134.1

### ISSUE THREAD

**Issue by drshock** [stascorp/rdpwrap#485] opened 2018-05-16 11:37 UTC
FYI, I already had a working rdpwrap for 1803 as mentioned in issue 456, using a hand edited rdpwrap.ini.

I updated the latest ini update from today just to move onto the latest content from repo, applied by running v1.6.2 update.bat as admin and then restarting the PC.   Update successful to latest ini file, but RDP stopped working for me with this published ini.  Also this ini introduces a full screen remote procedure call error message from Windows whenever logging in regularly (not using RDP).   

I am using the virgin untouched termsrv.dll from Microsoft, no patches whatsoever.

I reverted back to the ini values I reported as working in closed issue 456, posted by macchrome originally, which continue to work fine for me and the remote procedure call error is never present.   The new ini is not using these same values. 

Values for the rdpwrap.ini working for me on 64bit Windows Home 10.0.17134.1 below:
 
[10.0.17134.1]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=925D1
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=18B64
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=10E72
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=22E6C
SLInitFunc.x64=New_CSLQuery_Initialize

Could the default ini not working be related to not having an updated rfxvmt.dll for Home edition?  I am using the one installed prior to the Windows 10 1803 upgrade, when I had installed rdpwrap 1.6.2, which is dll file version 10.0.15063.1.  

Curious if its just me or is anyone else seeing a problem after updating today.

**Comment by binarymaster** [comment] 2018-05-16 11:59
> SingleUserOffset.x64=18B64
> DefPolicyOffset.x64=10E72

These two offsets are not looking correct:
```
.text:0000000180018B61                 lea     r14d, [rdi+1]     << no jump here
.text:0000000180018B65                 mov     [rdx], r14d
.text:0000000180018B68                 call    sub_180035DD4
.text:0000000180018B6D                 mov     ebx, eax
.text:0000000180018B6F                 test    eax, eax
```
```
.text:0000000180010E72                 mov     ebx, [rcx+63Ch]   << points here
.text:0000000180010E78                 mov     edi, [rcx+638h]
.text:0000000180010E7E                 cmp     ebx, edi          << actually should be there
.text:0000000180010E80                 jz      loc_18003AF9C
```

> Could the default ini not working be related to not having an updated rfxvmt.dll for Home edition?

Could be that.

**Comment by binarymaster** [comment] 2018-05-16 14:11
Closing as a duplicate of #486, because it contains more useful information.

**Closed by binarymaster** 2018-05-16 14:11 UTC
