### ISSUE TITLE
Ver 10.0.19041.2673 showing as Fully Supported but not allowing multiple logins

### ISSUE THREAD

**Issue by jlayton74** [stascorp/rdpwrap#2153] opened 2023-03-23 15:23 UTC
Hello.  For version 10.0.19041.2673, I applied the update provided by netcuter in the previous Issue post, but it is still not allowing multiple RDP sessions, even though it shows as fully supported.  Can someone please help with this?

![RDP Wrap](https://user-images.githubusercontent.com/128716575/227251433-72b7a661-cbd4-4f69-bece-ed752c2fe1cb.jpg)

**Comment by sashaqwert** [comment] 2023-03-24 07:22
Duplicate of https://github.com/stascorp/rdpwrap/issues/2125

**Closed as not planned by sashaqwert** 2023-03-24 07:22 UTC

**Comment by sashaqwert** [comment] 2023-03-24 07:23
Try:
1. Download RDP Wrapper 1.6.2 and extract this to any directory.
2. Place `rdpwrap.ini` in the same directory.
3. Open CMD as administrator
4. Execute this commands
```
cd C:\path\to\directory\
rdpwinst -u -k
rdpwinst -i
```
5. Enjoy!

Original message: https://t.me/rdpwrap/49131

**Comment by kingstar1115** [comment] 2023-04-29 13:10
Good! That's well done.
