### ISSUE TITLE
add support for Windows 7 build 6.1.7601.24326 (2019-02)

### ISSUE THREAD

**Issue by fre4kyC0de** [stascorp/rdpwrap#668] opened 2019-02-14 23:26 UTC
As I can't answer to the existing issue (https://github.com/stascorp/rdpwrap/issues/646):

https://github.com/fre4kyC0de/rdpwrap/blob/master/6.1.7601.24326.txt

**Comment by fre4kyC0de** [comment] 2019-02-14 23:27
https://github.com/stascorp/rdpwrap/issues/646

**Comment by gitgotgone** [comment] 2019-02-15 06:33
Here's an interim fix:
https://github.com/stascorp/rdpwrap/issues/669

**Comment by joebrug** [comment] 2019-02-15 06:43
That's a workaround. The fix is getting rdpwrap to work with latest termsrv.dll. thanks @fre4kyC0de will try this tomorrow. Would love to know how you figured it out. I tried following the YouTube without luck.

**Comment by gitgotgone** [comment] 2019-02-15 06:57
Yeah, fix to the lack of access, not to the software. I don't have nearly the knowledge to fix that!

**Comment by binarymaster** [comment] 2019-02-15 16:07
Duplicate of #646.

**Closed as completed by binarymaster** 2019-02-15 16:07 UTC
Labels: duplicate
