### ISSUE TITLE
Version 10.0.190401.789 Not Supported

### ISSUE THREAD

**Issue by Hidlsh** [stascorp/rdpwrap#1387] opened 2021-04-30 03:56 UTC
![RDPConf_9tsEJlfiFn](https://user-images.githubusercontent.com/67646781/116646494-d4030900-a93d-11eb-90fd-d4c886703e97.png)

I've tried many solutions, including this one [https://github.com/stascorp/rdpwrap/issues/999#issuecomment-586757085](url) but nothing seems to work.

**Comment by Asyw** [comment] 2021-04-30 05:08
Have you solved it?

**Comment by sydtc5545741** [comment] 2021-05-01 16:17
> 
> 
> ![RDPConf_9tsEJlfiFn](https://user-images.githubusercontent.com/67646781/116646494-d4030900-a93d-11eb-90fd-d4c886703e97.png)
> 
> I've tried many solutions, including this one [https://github.com/stascorp/rdpwrap/issues/999#issuecomment-586757085](url) but nothing seems to work.


windows version 19042.928 win10 20H2 
RDPWARP Version 10.0.190401.789
now work！！！！！

try this link download rdpwarp.ini https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini

**Comment by seedsnj** [comment] 2021-05-02 07:30
The auto update script retrieved through the above link indeed works to enable RDP connection on 10.0.19042.928 (shown by winver).

rdpwrap.ini downloaded by the script says however "10.0.19041.964-...". Nonetheless this works.

**Comment by affinityv** [comment] 2021-05-03 11:14
Updated my [INI](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini) file for this.

**Comment by sboychenko** [comment] 2021-05-03 17:04
> Updated my [INI](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini) file for this.

Yep!  It's work for me, thx
![image](https://user-images.githubusercontent.com/6670837/116907820-c5bd3180-ac4a-11eb-8dd3-40389bc9827a.png)

**Comment by engr-mazdaa-razavi** [comment] 2021-05-04 20:49
> > ![RDPConf_9tsEJlfiFn](https://user-images.githubusercontent.com/67646781/116646494-d4030900-a93d-11eb-90fd-d4c886703e97.png)
> > I've tried many solutions, including this one [https://github.com/stascorp/rdpwrap/issues/999#issuecomment-586757085](url) but nothing seems to work.
> 
> windows version 19042.928 win10 20H2
> RDPWARP Version 10.0.190401.789
> now work！！！！！
> 
> try this link download rdpwarp.ini https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini

Hi
the latest rdpwrap.ini (21332.1000-SLInit) do not worked on windows 10 20h2.
Please help me figure out how to fix this problem.
Thanks 


![RDPWrap-Configuration-1400-02-14](https://user-images.githubusercontent.com/83561176/117068025-fd59d580-ad3f-11eb-9a73-03901ae069f8.JPG)
![RDPWrap-Error-1400-02-14](https://user-images.githubusercontent.com/83561176/117068029-fe8b0280-ad3f-11eb-877b-337fb4bdfd3d.JPG)

**Comment by sebaxakerhtc** [comment] 2022-03-30 13:09
Duplicate of https://github.com/stascorp/rdpwrap/issues/1317

**Closed as completed by sebaxakerhtc** 2022-03-30 13:09 UTC
