### ISSUE TITLE
termsrv.dll文件

### ISSUE THREAD

**Issue by MyMilkGit** [stascorp/rdpwrap#1651] opened 2021-12-07 06:34 UTC
我现在有一个问题，我的dll文件是18362.1766，但是我一直找不到相关的ini文件。
所以我想对termsrv.dll文件进行降级，但是不知道可以在哪里找到靠谱的dll文件。
我感觉找不到什么好的解决办法了。
所以请各位大神指条明路。

以下为谷歌翻译。
The following is Google Translate.

I have a problem now. My dll file is 18362.1766, but I can't find the related ini file.
So I want to downgrade the termsrv.dll file, but I don’t know where to find a reliable dll file.
I don't think I can find any good solutions.
So please show me the way.

**Comment by sebaxakerhtc** [comment] 2021-12-07 09:33
Duplicate of https://github.com/stascorp/rdpwrap/issues/1582

**Closed as completed by sebaxakerhtc** 2021-12-07 09:33 UTC
