### ISSUE TITLE
Windows 11 - 22621.1848

### ISSUE THREAD

**Issue by Razuken** [stascorp/rdpwrap#2279] opened 2023-07-16 09:33 UTC
''the number of connections to this computer is limited'' how to fix this ?
![Ekran görüntüsü 2023-07-16 123316](https://github.com/stascorp/rdpwrap/assets/102856653/d3f9384a-b667-46a6-8303-a396b9001768)

**Comment by sashaqwert** [comment] 2023-07-16 10:07
Duplicate of https://github.com/stascorp/rdpwrap/issues/2213

**Closed as not planned by sashaqwert** 2023-07-16 10:07 UTC
Labels: duplicate

**Comment by sashaqwert** [comment] 2023-07-16 10:09
> ''the number of connections to this computer is limited'' how to fix this ?

If Fully supported and this error:

Try restart service or reboot.

OR

Try:
1. Download RDP Wrapper 1.6.2 and extract this to any directory.
2. Place `rdpwrap.ini` in the same directory.
3. Open CMD as administrator
4. Execute this commands
```
cd C:\path\to\directory\
rdpwinst -u -k
rdpwinst -i
```
5. Enjoy!

Original message: https://t.me/rdpwrap/49131
