### ISSUE TITLE
10.0.19041.746

### ISSUE THREAD

**Issue by Alex874** [stascorp/rdpwrap#1273] opened 2021-01-13 08:20 UTC
Good afternoon. RDP stopped working. Can anyone help me?

**Comment by Alex874** [comment] 2021-01-13 08:26
Can anyone help me?

**Comment by javedsumaro** [comment] 2021-01-13 08:34
add this GIST in autoupdate file 

https://gist.githubusercontent.com/javedsumaro/11fcabdf595241148ab962660ed470cc/raw/b5b1ff7a9cb72dea84b4dad3697680d0846aa62f/rdpwrap.ini

**Comment by Alex874** [comment] 2021-01-13 08:38
There version 10.0.19041.662 and I have 10.0.19041.746

**Comment by javedsumaro** [comment] 2021-01-13 09:01
Just try it once... i was having the same issue.. in same version

**Comment by martin-korf** [comment] 2021-01-13 09:05
This configuration is working for me:
```
[10.0.19041.746]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=88F31
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0CB22
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=18A15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=1D5BC
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.19041.746-SLInit]
bInitialized.x64 =106028
bServerSku.x64 =10602C
lMaxUserSessions.x64 =106030
bAppServerAllowed.x64 =106038
bRemoteConnAllowed.x64=106040
bMultimonAllowed.x64 =106044
ulMaxDebugSessions.x64=106048
bFUSEnabled.x64 =10604C
```

**Comment by chap-s** [comment] 2021-01-13 10:04
```
add this GIST in autoupdate file

https://gist.githubusercontent.com/javedsumaro/11fcabdf595241148ab962660ed470cc/raw/b5b1ff7a9cb72dea84b4dad3697680d0846aa62f/rdpwrap.ini

```
Thanks, configuration is working 19041.746

**Comment by joebeem** [comment] 2021-01-13 10:06
> add this GIST in autoupdate file
> 
> https://gist.githubusercontent.com/javedsumaro/11fcabdf595241148ab962660ed470cc/raw/b5b1ff7a9cb72dea84b4dad3697680d0846aa62f/rdpwrap.ini

That worked for me.

**Comment by Alex874** [comment] 2021-01-13 10:22
Thank you very much

**Comment by mh-yavari** [comment] 2021-01-13 10:40
I can't delete or edit the file "rdpwrap.ini" to change it same you, how can I do that?

**Comment by Alex874** [comment] 2021-01-13 10:47
> I can't delete or edit the file "rdpwrap.ini" to change it same you, how can I do that?

Need to stop the Remote Desktop service

**Comment by mh-yavari** [comment] 2021-01-13 11:11
> > I can't delete or edit the file "rdpwrap.ini" to change it same you, how can I do that?
> 
> Need to stop the Remote Desktop service

![image](https://user-images.githubusercontent.com/77387770/104444591-39103a00-55ad-11eb-8b17-fb26d7987d37.png)

I have stoped it here but it doesn't solve

**Comment by asmtron** [comment] 2021-01-13 11:15
add 10.0.18362.1316 (x64) and 10.0.19041.746 (x64)
[autoupdate (recommended)](https://github.com/asmtron/rdpwrap/blob/master/binary-download.md)
_Info: please use/downlaod the latest autoupdate.bat file (added "Wait for network connection" :: important fix)_

or

[rdpwrap.ini](https://github.com/asmtron/rdpwrap/blob/master/res/rdpwrap.ini)
```

[10.0.19041.746]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=88F31
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0CA4C
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=18A15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=1D5BC
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.19041.746-SLInit]
bInitialized.x64      =106028
bServerSku.x64        =10602C
lMaxUserSessions.x64  =106030
bAppServerAllowed.x64 =106038
bRemoteConnAllowed.x64=106040
bMultimonAllowed.x64  =106044
ulMaxDebugSessions.x64=106048
bFUSEnabled.x64       =10604C

```

-------------------

please upload the 32Bit variant of termsrv.dll v.10.0.18362.1316 and v.10.0.19041.746

**Comment by eslamiar** [comment] 2021-01-13 11:32
Removing KB459842 and KB4598481 will get it going again if .ini isn't updated yet

**Comment by Bolex80** [comment] 2021-01-13 11:40
Hello,
I have updated the to the last rdwrap.ini file and my RDPWrapConf is successful, but still I am unable to have concurrent users in windows, it says another user is logged in.
This is the first time this happens since I have been using RDP Wrapper.

![rdpwrapconf](https://user-images.githubusercontent.com/8085823/104447684-6a343e80-559c-11eb-82f9-d5146b467e1f.png)

Can anyone help with this?
Why is it not letting me have concurrent users?

Thanks

**Comment by FoxMulder0815** [comment] 2021-01-13 16:30
Hello

i have the Same Problem

"I have updated the to the last rdwrap.ini file and my RDPWrapConf is successful, but still I am unable to have concurrent users in windows, it says another user is logged in.
This is the first time this happens since I have been using RDP Wrapper."

all green but not more then one user at the same time .... 

please help ... i need the function .... 

with 10.0.19041.662 and 10.0.19041.746

Thanks
![grafik](https://user-images.githubusercontent.com/77403269/104480554-fce8d380-55c4-11eb-9713-5077d61087ab.png)

**Comment by oshoincontrol** [comment] 2021-01-13 16:35
[termsrv.dll.10.0.19041.746.x86.zip](https://github.com/stascorp/rdpwrap/files/5809929/termsrv.dll.10.0.19041.746.x86.zip)

**Comment by Bolex80** [comment] 2021-01-13 18:54
> [termsrv.dll.10.0.19041.746.x86.zip](https://github.com/stascorp/rdpwrap/files/5809929/termsrv.dll.10.0.19041.746.x86.zip)

Hello oshoincontrol,
I appreciate the help sending us the file, unfortunately, when I put in in Windows/system32 instead of the old file, My terminal services, do not start anymore and are in a constant crash state.
I execute in CMD (administrator rights):
      - net stop termservice (this works ok)
      - change the name of the original termsrv.dll to termserv-old.dll
      - copy your version of the file (provided in zip file above)
      - net start termservice (service cannot start, it says it is starting, but stays frozen, nothing happens)  

If I reboot windows, nothing changes. Same status.
I had to revert to the previous file to get terminal services working again.

Is there any other solution?
Thanks
:)

**Comment by oshoincontrol** [comment] 2021-01-13 19:03
Hi, it is original and unpatched file from my today installed and updated 32bit x86 system (Win 10 Home). I don't know why it doesn't work and what are you trying to achieve. I have uploaded it here as was requested for this version by asmtron (probably to be searched for correct dll entries to be added to rdpwrap.ini for this version), though request was targeted to someone else.

**Comment by Bolex80** [comment] 2021-01-13 19:20
Hi All,
Sorry for this misunderstanding (didnt realize you had the 32 bit version, that's why mine failed).
 
I found the solution and it was as simple as installing it via the Autoupdate service (few posts above): https://github.com/asmtron/rdpwrap/blob/master/binary-download.md

After rebooting, I can have concurrent users again.
Thank you to all

**Comment by oshoincontrol** [comment] 2021-01-19 14:51
asmtron, any chance to add 19041.746 x86 version to autoupdate? Thanks.

**Comment by maxi32uy** [comment] 2021-01-19 17:27
someone can fix it? i try all your post and nothing for fix this version, RDPConf appear on green but still not concurrent users.

**Comment by some1o1** [comment] 2021-01-20 04:30
I do have same problem , anyone can help .. win10 pro 32bit - version 19041.746  

cannot concurrent users..

**Comment by MarcinWerra** [comment] 2021-01-20 08:22
Settings for the x86 and x64 version:
```
[10.0.19041.746]
LocalOnlyPatch.x86  =1
LocalOnlyOffset.x86 =B5979
LocalOnlyCode.x86   =jmpshort
SingleUserPatch.x86 =1
SingleUserOffset.x86=3BC05
SingleUserCode.x86  =nop
DefPolicyPatch.x86  =1
DefPolicyOffset.x86 =3E779
DefPolicyCode.x86   =CDefPolicy_Query_eax_ecx
SLInitHook.x86      =1
SLInitOffset.x86    =67B9A
SLInitFunc.x86      =New_CSLQuery_Initialize

LocalOnlyPatch.x64  =1
LocalOnlyOffset.x64 =88F31
LocalOnlyCode.x64   =jmpshort
SingleUserPatch.x64 =1
SingleUserOffset.x64=0CB22
SingleUserCode.x64  =Zero
DefPolicyPatch.x64  =1
DefPolicyOffset.x64 =18A15
DefPolicyCode.x64   =CDefPolicy_Query_eax_rcx
SLInitHook.x64      =1
SLInitOffset.x64    =1D5BC
SLInitFunc.x64      =New_CSLQuery_Initialize

[10.0.19041.746-SLInit]
bInitialized.x86      =D0954
bServerSku.x86        =D0958
lMaxUserSessions.x86  =D095C
bAppServerAllowed.x86 =D0964
bRemoteConnAllowed.x86=D096C
bMultimonAllowed.x86  =D0970
ulMaxDebugSessions.x86=D0974
bFUSEnabled.x86       =D0978

bInitialized.x64      =106028
bServerSku.x64        =10602C
lMaxUserSessions.x64  =106030
bAppServerAllowed.x64 =106038
bRemoteConnAllowed.x64=106040
bMultimonAllowed.x64  =106044
ulMaxDebugSessions.x64=106048
bFUSEnabled.x64       =10604C

```

**Comment by some1o1** [comment] 2021-01-20 09:06
> Settings for the x86 and x64 version:
> 
> ```
> [10.0.19041.746]
> LocalOnlyPatch.x86  =1
> LocalOnlyOffset.x86 =B5979
> LocalOnlyCode.x86   =jmpshort
> SingleUserPatch.x86 =1
> SingleUserOffset.x86=3BC05
> SingleUserCode.x86  =nop
> DefPolicyPatch.x86  =1
> DefPolicyOffset.x86 =3E779
> DefPolicyCode.x86   =CDefPolicy_Query_eax_ecx
> SLInitHook.x86      =1
> SLInitOffset.x86    =67B9A
> SLInitFunc.x86      =New_CSLQuery_Initialize
> 
> LocalOnlyPatch.x64  =1
> LocalOnlyOffset.x64 =88F31
> LocalOnlyCode.x64   =jmpshort
> SingleUserPatch.x64 =1
> SingleUserOffset.x64=0CB22
> SingleUserCode.x64  =Zero
> DefPolicyPatch.x64  =1
> DefPolicyOffset.x64 =18A15
> DefPolicyCode.x64   =CDefPolicy_Query_eax_rcx
> SLInitHook.x64      =1
> SLInitOffset.x64    =1D5BC
> SLInitFunc.x64      =New_CSLQuery_Initialize
> 
> [10.0.19041.746-SLInit]
> bInitialized.x86      =D0954
> bServerSku.x86        =D0958
> lMaxUserSessions.x86  =D095C
> bAppServerAllowed.x86 =D0964
> bRemoteConnAllowed.x86=D096C
> bMultimonAllowed.x86  =D0970
> ulMaxDebugSessions.x86=D0974
> bFUSEnabled.x86       =D0978
> 
> bInitialized.x64      =106028
> bServerSku.x64        =10602C
> lMaxUserSessions.x64  =106030
> bAppServerAllowed.x64 =106038
> bRemoteConnAllowed.x64=106040
> bMultimonAllowed.x64  =106044
> ulMaxDebugSessions.x64=106048
> bFUSEnabled.x64       =10604C
> ```

Thank you . Now is can work . Thank you so much !!

**Comment by w1lddog2** [comment] 2021-01-21 15:07
Indeed it works on x86

**Comment by HBastet** [comment] 2021-01-24 21:51
Hello,Thank you very much  for solution. But could someone explaine how is it possible to find it by ourselves ?

**Comment by malicon** [comment] 2021-02-04 23:34
Sovepro

> 
> 
> Hello,Thank you very much for solution. But could someone explaine how is it possible to find it by ourselves ?

Not an easy task!  One must reverse engineer termsrv.dll (Windows/system32) that implements most of Remote desktop.  See "Practical reverse engineering (for RDP Wrapper)" at [https://www.youtube.com/watch?v=FiD86tmRBtk](url).  Turn off the music of before it drives you crazy.  Then be ready to pause that video quite often so to get a chance to understand what it's going on.  It's very old and many things have changed thow it's still basically the same idea.  Get a free copy of IDA freeware no need to buy it but you'll need some understanding of assembler.  Roughly speeking RDPwrapper loads termsrv.dll in memory then using info it finds in RDPwrap.ini file it locates crucial places in the original coding & creates an altered version of termsrv.dll  that bypasses (by recoding) the limitation checks Windows puts on.  Without those check the dll is much more powerful  dll.  You don't need to understand what the dll code is doing but need to locate where certain passages are (IDA is a must).  I was about to understand most of it but life drag me elsewhere and  someone posted what I needed.  Take a look at stscorp/rdpwrap/technical.txt  file.  The video uses one similar.  Take a look at the source code you'll find there (pascal/delphi but quite easy to understand.  And, if you're patient  enough ...  Good luck and let us know.

**Comment by sebaxakerhtc** [comment] 2022-06-20 12:26
Duplicate of https://github.com/stascorp/rdpwrap/issues/1270

**Closed as completed by sebaxakerhtc** 2022-06-20 12:26 UTC
