### ISSUE TITLE
WRAPPER STATE : 3rd Party

### ISSUE THREAD

**Issue by mhtkumar0025** [stascorp/rdpwrap#1618] opened 2021-11-15 10:07 UTC
Please Help
I am unable to use Remote desktop. I'm using quick heal antivirus

![redp](https://user-images.githubusercontent.com/74907458/141762786-3edde8b2-2c04-425a-8e31-4cf22cab7854.PNG)

I will be highly obliged.

**Comment by sebaxakerhtc** [comment] 2021-11-15 18:32
Closed as duplicate of https://github.com/stascorp/rdpwrap/issues/1595

**Closed as completed by sebaxakerhtc** 2021-11-15 18:32 UTC

**Comment by mhtkumar0025** [comment] 2021-11-16 09:31
I have copied termserv file but it's still the same

**Comment by mhtkumar0025** [comment] 2021-11-16 09:33
> Closed as duplicate of #1595

I have updated termser file still not able to use. It's the same issue. Please help

**Comment by sebaxakerhtc** [comment] 2021-11-16 09:53
> > Closed as duplicate of #1595
> 
> I have updated termser file still not able to use. It's the same issue. Please help

Go to official Telegram channel for getting help

**Comment by IslamYheya1611** [comment] 2022-08-15 15:46
](url)![RDP Wrapper !](https://user-images.githubusercontent.com/111299221/184668596-d8a500f2-9674-471e-9072-dac7fc337a96.PNG)

Can you please help on this case?

**Comment by Cosmits** [comment] 2022-12-16 17:21
RDP Wrapper deleted by antivirus.
Try this command as Administrator:
reg add HKLM\SYSTEM\CurrentControlSet\Services\TermService\Parameters /v ServiceDll /t REG_EXPAND_SZ /d "%SystemRoot%\system32\termsrv.dll" /f

If not work (service status = unknown): try restore backup from original (clean) OS
Windows 10 21H1 [here](https://t.me/rdpwrap/38025)
Windows 11 21H2 [here](https://t.me/rdpwrap/40042)
Windows 10 LTSC 1809 [here](https://t.me/rdpwrap/41015)

Restoring a registry branch from a backup:
1. Download .reg file
2. Open this (dual left click)
3. Press yes
4. Reboot

After following these instructions, you need to reinstall RDP Wrapper.

-----------------

RDP Wrapper удалён антивирусом.
Нужно восстановить стандартный DLL в реестре с помощью одной команды от администратора:
reg add HKLM\SYSTEM\CurrentControlSet\Services\TermService\Parameters /v ServiceDll /t REG_EXPAND_SZ /d "%SystemRoot%\system32\termsrv.dll" /f

Если не работает (Service status = unknown), то нужно восстановить реестр службы от чистой ОС.:
Windows 10 21H1 [here](https://t.me/rdpwrap/38025)
Windows 11 21H2 [here](https://t.me/rdpwrap/40042)
Windows 10 LTSC 1809 [here](https://t.me/rdpwrap/41015)

Восстановление ветки реестра из резервной копии:
1. Загрузите файл .reg
2. Откройте его в программе по-умолчанию (двойной клик ЛКМ)
3. Согласитесь с внесением изменений в реестр
4. Перезагрузите систему.

После выполнения данной инструкции нужно заново установить RDP Wrapper.
