### ISSUE TITLE
10.0.18368.836

### ISSUE THREAD

**Issue by drummerdude152002** [stascorp/rdpwrap#1219] opened 2020-11-29 21:44 UTC
Hello there, long time listener, first time caller. 

I've been using RDPWrap for some time and never had any issues until this version. 

I'm getting Listener: Listening and Fully supported, all checkmarks are green, yet when I run the check tool, it just sits on "connecting". 

I've got the autoupdate.bat tool

On 1.6.2, the conf tool shows ver 1.5.0

I've disabled my firewall. I've tried the INI file found [Here](https://github.com/stascorp/rdpwrap/issues/999#issuecomment-672962479) and yet I still cannot get it to play nicely. Everything says it should all work, but no dice. 

I've even added the localgoup "Remote Desktop Users" and added the local account to it

Anything I'm missing?

**Comment by cbx040** [comment] 2020-11-29 23:11
I had the same problem, but I found this post

[https://github.com/stascorp/rdpwrap/issues/1083#issuecomment-641003880](https://github.com/stascorp/rdpwrap/issues/1083#issuecomment-641003880)

Just add these lines to the bottom of your config file.

**Comment by drummerdude152002** [comment] 2020-11-30 00:19
> 
> 
> I had the same problem, but I found this post
> 
> [#1083 (comment)](https://github.com/stascorp/rdpwrap/issues/1083#issuecomment-641003880)
> 
> Just add these lines to the bottom of your config file.

Tried it. Ran net stop termservice
then pasted the info to the rdpwrap.ini file at the bottom. 

When i tried to save, it told me I didn't have permission, so I took ownership, did it again
Then ran net start termservice
checked in the conf file, shows listening and supported
but the check file still only shows connecting. 

Did I do something wrong? I even ran rdpwinst -r and though it did it's job, I still can't get past the "connecting" screen. 

Anything I'm missing? Some assumed process I'm missing or something?

**Comment by cbx040** [comment] 2020-11-30 18:18
Try rebooting and having another go.

**Comment by drummerdude152002** [comment] 2020-12-02 01:24
Still no dice. Might just have to buy a pro key and call it a day

**Comment by doing-cr7** [comment] 2021-01-09 17:57
listener state: Not listening [fully supported]

**Comment by sebaxakerhtc** [comment] 2022-06-20 11:55
Duplicate of https://github.com/stascorp/rdpwrap/issues/1083

**Closed as completed by sebaxakerhtc** 2022-06-20 11:55 UTC
