### ISSUE TITLE
not supported windows server 2022

### ISSUE THREAD

**Issue by Mariojd1980** [stascorp/rdpwrap#3261] opened 2024-08-23 12:24 UTC
good day. Please help, rdpwrapper stopped working. I attach files
[Files.zip](https://github.com/user-attachments/files/16728602/Files.zip)

**Comment by loyejaotdiqr47123** [comment] 2024-08-23 15:43
Duplicate of #3199

**Closed as not planned** 2024-08-26 16:28 UTC
Labels: duplicate
