### ISSUE TITLE
10.0.22621.3374

### ISSUE THREAD

**Issue by pakosanz** [stascorp/rdpwrap#2544] opened 2024-04-05 18:01 UTC
![image](https://github.com/stascorp/rdpwrap/assets/13137950/e4cc88fe-0c73-4b4a-a39d-0330049357ae)
![image](https://github.com/stascorp/rdpwrap/assets/13137950/71bb7215-902a-4f1e-b904-055e447e066c)
 need help with this build

**Comment by loyejaotdiqr47123** [comment] 2024-04-06 02:27
Duplicate of #2528

**Comment by sashaqwert** [comment] 2024-04-06 16:43
Duplicate of https://github.com/stascorp/rdpwrap/issues/2528

**Closed as not planned by sashaqwert** 2024-04-06 16:43 UTC
Labels: duplicate
