### ISSUE TITLE
10.0.19041.662 not supported

### ISSUE THREAD

**Issue by JackChen0910** [stascorp/rdpwrap#1667] opened 2021-12-19 13:22 UTC

**Comment by zekecarter** [comment] 2021-12-19 17:33
> _No description provided._

10.0.19041.662]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=88E81
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0CAE2
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=189D5
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=1D50C
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.19041.662-SLInit]
bInitialized.x64      =106028
bServerSku.x64        =10602C
lMaxUserSessions.x64  =106030
bAppServerAllowed.x64 =106038
bRemoteConnAllowed.x64=106040
bMultimonAllowed.x64  =106044
ulMaxDebugSessions.x64=106048
bFUSEnabled.x64       =10604C

**Comment by zekecarter** [comment] 2021-12-19 18:23
> _No description provided._

Try with this version of **[rdpwrap.ini](https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini)**

**Comment by sashaqwert** [comment] 2021-12-21 13:51
Please attach your RDPConf screenshot. This will determine if the issue is a duplicate.
In addition, if this is not a duplicate, you will be able to make offsets for your version (for this, on request, you will need to send `termsrv.dll`)

**Comment by mikemtz-slt** [comment] 2021-12-28 23:43
> > _No description provided._
> 
> Try with this version of **[rdpwrap.ini](https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini)**

Excelent tks amigo

**Comment by sebaxakerhtc** [comment] 2022-06-20 13:31
Duplicate of https://github.com/stascorp/rdpwrap/issues/1220

**Closed as completed by sebaxakerhtc** 2022-06-20 13:31 UTC
