### ISSUE TITLE
23h2 not supported

### ISSUE THREAD

**Issue by ghost** [stascorp/rdpwrap#2449] opened 2023-12-14 12:56 UTC
![Screenshot 2023-12-14 135527](https://github.com/stascorp/rdpwrap/assets/153830907/31b8cfc4-f19e-4f0b-a21c-3e9f904d5fb0)

**Comment by Plawasan** [comment] 2023-12-14 13:53
https://github.com/stascorp/rdpwrap/issues/2443

**Comment by sashaqwert** [comment] 2023-12-15 12:56
Duplicate of https://github.com/stascorp/rdpwrap/issues/2443

**Closed as not planned by sashaqwert** 2023-12-15 12:56 UTC
Labels: duplicate
