### ISSUE TITLE
Windows Server 2019 Standard [Fully Supported, but only two connections are working]

### ISSUE THREAD

**Issue by ghost** [stascorp/rdpwrap#2294] opened 2023-07-27 20:16 UTC
Hi 

Does anyone help me with this issue. Fully Supported, but only two connections are working

I try to add one more blank line to rdpini but that doesnt work for me.

![Captura de pantalla 2023-07-27 171230](https://github.com/stascorp/rdpwrap/assets/121802452/baeb3e04-945c-4e57-8e49-1da119d4fdb0)

![image](https://github.com/stascorp/rdpwrap/assets/121802452/4a5d7b24-9410-4456-b46a-71a049775882)

Thanks!

**Comment by sashaqwert** [comment] 2023-07-28 08:47
Try:
1. Download RDP Wrapper 1.6.2 and extract this to any directory.
2. Place `rdpwrap.ini` in the same directory.
3. Open CMD as administrator
4. Execute this commands
```
cd C:\path\to\directory\
rdpwinst -u -k
rdpwinst -i
```
5. Enjoy!

Original message: https://t.me/rdpwrap/49131

**Comment by sashaqwert** [comment] 2023-07-28 08:49
One `termsrv.dll` version = ONE opened issue!

**Comment by sashaqwert** [comment] 2023-07-28 08:50
Duplicate of https://github.com/stascorp/rdpwrap/issues/2167

**Closed as not planned by sashaqwert** 2023-07-28 08:50 UTC
Labels: duplicate

**Comment by Jeyzen** [comment] 2023-07-29 13:59
Thanks a LOT! Finally it works.
