### ISSUE TITLE
Need help with 10.0.19045.2130

### ISSUE THREAD

**Issue by zwtm** [stascorp/rdpwrap#2031] opened 2022-10-24 02:26 UTC

**Comment by sashaqwert** [comment] 2022-10-24 05:28
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992

**Closed as not planned by sashaqwert** 2022-10-24 05:28 UTC
Labels: duplicate

**Comment by sashaqwert** [comment] 2022-10-24 05:30
If wrong, please, send RDPConf screenshot and `termsrv.dll`
