### ISSUE TITLE
Windows 11 Build 10.0.20348.2652 Not Supported

### ISSUE THREAD

**Issue by JeremyPerpignani** [stascorp/rdpwrap#3310] opened 2024-10-17 03:34 UTC
Hello, this update broke my setup. Can anyone help please?
![helppls](https://github.com/user-attachments/assets/64a8db8a-feae-4f65-9269-40a68fb9d313)

[termsrv.zip](https://github.com/user-attachments/files/17405646/termsrv.zip)

I appreciate you guys so much!

**Comment by binarymaster** [comment] 2024-10-17 18:39
Duplicate of https://github.com/stascorp/rdpwrap/issues/3253.

**Closed as not planned by binarymaster** 2024-10-17 18:39 UTC
Labels: duplicate
