### ISSUE TITLE
user limit

### ISSUE THREAD

**Issue by yuxiE5** [stascorp/rdpwrap#2537] opened 2024-04-02 02:55 UTC
How does this software limit the number of users? I currently log in to up to 15 users at the same time. How to achieve the same functionality as windows10 Enterprise Virtual Desktop Edition

**Comment by sashaqwert** [comment] 2024-04-06 16:29
Duplicate of https://github.com/stascorp/rdpwrap/issues/192

**Closed as not planned by sashaqwert** 2024-04-06 16:29 UTC
