### ISSUE TITLE
RDP WRAPPER CONFIG

### ISSUE THREAD

**Issue by MrDOntDIe** [stascorp/rdpwrap#1780] opened 2022-03-19 14:03 UTC
![image](https://user-images.githubusercontent.com/101935753/159124146-2aa2a10f-0534-4292-ab36-351c7eb449c4.png)
 it wont listen and it isnt supported?

**Comment by MrDOntDIe** [comment] 2022-03-19 14:03
well now the service state is green but nothin else

**Comment by sebaxakerhtc** [comment] 2022-03-19 15:30
Duplicate of https://github.com/stascorp/rdpwrap/issues/1725

**Closed as completed by sebaxakerhtc** 2022-03-19 15:30 UTC
