### ISSUE TITLE
10.0.19041.1566 w10. X86

### ISSUE THREAD

**Issue by yorchwa** [stascorp/rdpwrap#1760] opened 2022-03-06 08:48 UTC
Please , somebody has rdwrap.ini for  10.0.19041.1566 w10 X86. Find attached termsrv.dll file.

Thanks

[termsrv.10.0.19041.1566.zip](https://github.com/stascorp/rdpwrap/files/8192212/termsrv.10.0.19041.1566.zip)

**Comment by sebaxakerhtc** [comment] 2022-03-07 11:11
> Please , somebody has rdwrap.ini for 10.0.19041.1566 w10 X86. Find attached termsrv.dll file.
> 
> Thanks
> 
> [termsrv.10.0.19041.1566.zip](https://github.com/stascorp/rdpwrap/files/8192212/termsrv.10.0.19041.1566.zip)

https://github.com/sebaxakerhtc/rdpwrap.ini/blob/a18e7bfc60b37dd869f129996c4b1874f9c2a3b2/rdpwrap.ini#L4923

**Comment by sebaxakerhtc** [comment] 2022-03-07 11:11
Duplicate of https://github.com/stascorp/rdpwrap/issues/1725

**Closed as completed by sebaxakerhtc** 2022-03-07 11:11 UTC

**Comment by yorchwa** [comment] 2022-03-08 17:55
It works for me. Thanks
