### ISSUE TITLE
Windows 11 Build 10.0.22621.4249 Not Supported

### ISSUE THREAD

**Issue by Drgntr** [stascorp/rdpwrap#3311] opened 2024-10-17 13:18 UTC
![a68086be-b9a9-402e-9554-938ce363bf49](https://github.com/user-attachments/assets/02c996fa-58f7-45e1-bc21-07fa86255ba5)

[termsrv.zip](https://github.com/user-attachments/files/17413099/termsrv.zip)

**Comment by binarymaster** [comment] 2024-10-17 18:50
Duplicate of https://github.com/stascorp/rdpwrap/issues/3280.

**Closed as not planned by binarymaster** 2024-10-17 18:50 UTC
Labels: duplicate
