### ISSUE TITLE
10.0.22631.2715

### ISSUE THREAD

**Issue by Boo-Booo** [stascorp/rdpwrap#2425] opened 2023-11-24 07:44 UTC

**Comment by sashaqwert** [comment] 2023-11-24 07:59
![изображение](https://github.com/stascorp/rdpwrap/assets/24974508/3e22dd4d-4486-4f43-8d27-e12477c9da03)

**Comment by sashaqwert** [comment] 2023-11-24 08:00
Duplicate of https://github.com/stascorp/rdpwrap/issues/2383

**Closed as not planned by sashaqwert** 2023-11-24 08:00 UTC
Labels: duplicate
