### ISSUE TITLE
detected by avs

### ISSUE THREAD

**Issue by princepsycho** [stascorp/rdpwrap#779] opened 2019-05-10 15:01 UTC
Rdpwrap is getting detected by all avs now, people says its detected as false positive but its not as majority of RAT on the internet and botnets are using RDPWRAP to install a kind of hidden RDP, its getting very annoying, is there a guy here who made his own concurrent rdp build none detected by antivirus ?

**Comment by NetVicious** [comment] 2019-05-17 10:41
Add RDPWrap folder to the whitelist of your antivirus.

**Comment by sebaxakerhtc** [comment] 2022-01-29 10:22
Duplicate of https://github.com/stascorp/rdpwrap/issues/277

**Closed as completed by sebaxakerhtc** 2022-01-29 10:22 UTC
