### ISSUE TITLE
I need help with the .ini for this update

### ISSUE THREAD

**Issue by wualdo81** [stascorp/rdpwrap#2604] opened 2024-05-04 16:13 UTC
Hello community, first of all, thank you for the support, in the past few days Windows 10 was updated and now I have a problem with the version, in the check I have version 10.0.19041.42.39 and I need to update the .ini to be able to use it again, yes Does anyone already have the solution, I would appreciate it. error screen annex
![WhatsApp Image 2024-05-04 at 12 01 15 PM](https://github.com/stascorp/rdpwrap/assets/168922903/8cc4df8c-2bff-4f07-96d6-c5108b76b9d5)
![WhatsApp Image 2024-05-04 at 12 01 15 PM](https://github.com/stascorp/rdpwrap/assets/168922903/7ff327a1-e547-497f-ae1d-a1bf95252221)

**Comment by binarymaster** [comment] 2024-05-04 16:37
Duplicate of #2529.

**Closed as not planned by binarymaster** 2024-05-04 16:37 UTC
Labels: duplicate
