### ISSUE TITLE
10.0.19041.1620 not supported

### ISSUE THREAD

**Issue by Ptitloupsuisse** [stascorp/rdpwrap#2044] opened 2022-11-11 15:54 UTC
Hi all,

10.0.19041.1620 is not supported on windows 10 21H1....

![2022-11-11_16h37_05](https://user-images.githubusercontent.com/118003917/201377010-88faca8d-ecb8-4f1e-bf7e-981983c8a53b.png)
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/9991431/termsrv.zip)

Thank you !

**Comment by sashaqwert** [comment] 2022-11-11 19:12
Duplicate of https://github.com/stascorp/rdpwrap/issues/1786

**Closed as not planned by sashaqwert** 2022-11-11 19:12 UTC
Labels: duplicate
