### ISSUE TITLE
RDPConf not supported winver 10.0.19044.2728

### ISSUE THREAD

**Issue by Phreaky1221** [stascorp/rdpwrap#2164] opened 2023-04-05 16:20 UTC
Hey all, geting an error on winver 19044.2728 (as stated in title lol). RDPConf showing version 10.0.19041.2673. I looked to see if there was a new ini for 19044.2728 but don't see one anywhere. Does anyone have the correct ini or can I get a build?

**Comment by Phreaky1221** [comment] 2023-04-05 16:26
I'm going to attach a copy of termsrv.dll
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/11160939/termsrv.zip)

**Comment by sashaqwert** [comment] 2023-04-05 17:24
Your version is `10.0.19041.2673`
![изображение](https://user-images.githubusercontent.com/24974508/230156561-8c12eabd-996a-424f-bf08-a3f44e9f9620.png)

> new ini for 19044.2728 but don't see one anywhere.

This is your Windows version. You need find INI with `termsrv.dll` version (avalible in RDPConf)

**Comment by sashaqwert** [comment] 2023-04-05 17:25
Duplicate of https://github.com/stascorp/rdpwrap/issues/2125

**Closed as not planned by sashaqwert** 2023-04-05 17:25 UTC
Labels: duplicate
