### ISSUE TITLE
Problem with the last version of Windows

### ISSUE THREAD

**Issue by kekko2525** [stascorp/rdpwrap#680] opened 2019-02-22 19:09 UTC
Hi,
I use the version 1.6.2 from many years, since one month when the last version of windows was released, the software doesn't work.

How can I solve this problem?

**Comment by joebrug** [comment] 2019-02-22 19:51
You don't mention what version of windows you're using, etc... but look through the latest "issues" to see if your problem hasn't already been resolved. You need to manually update the rdpwrap.ini with values that others have found. The official "update" option within RDPWrap is never updated anymore by author.

**Comment by infowayrs** [comment] 2019-02-22 19:51
in this repository I pasted some ini W10 1809 tested in Pro x64 : https://github.com/infowayrs/INI-RDPWRAP

**Comment by binarymaster** [comment] 2019-02-22 22:39
Probably a duplicate of #645.

**Closed as completed by binarymaster** 2019-02-22 22:39 UTC
Labels: duplicate
