### ISSUE TITLE
19043.985 not supported

### ISSUE THREAD

**Issue by ChocalateWZLH** [stascorp/rdpwrap#1408] opened 2021-05-25 14:04 UTC
I'd appreciate it if you could help me sort it out

**Comment by Dofollow** [comment] 2021-06-02 06:10
+++

**Comment by Matsumotorise** [comment] 2021-06-06 02:07
+++

**Comment by sebaxakerhtc** [comment] 2022-06-20 13:23
Duplicate of https://github.com/stascorp/rdpwrap/issues/1384

**Closed as completed by sebaxakerhtc** 2022-06-20 13:23 UTC
