### ISSUE TITLE
Not Supported 10.0.19042.1526

### ISSUE THREAD

**Issue by zldlhn** [stascorp/rdpwrap#1731] opened 2022-02-18 09:03 UTC
After Running windows updates.....not supported

![微信图片_20220218170252](https://user-images.githubusercontent.com/56494498/154651531-0f3f1d93-23e9-4067-92bc-b3acb3821f0f.png)
![微信图片_20220218170246](https://user-images.githubusercontent.com/56494498/154651566-9ed87fc3-35f8-462f-b1c9-e2c3c29492aa.png)

**Comment by sashaqwert** [comment] 2022-02-18 09:10
Your version is supported.
https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

**Comment by zldlhn** [comment] 2022-02-18 09:25
> Your version is supported. https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

thank you.I will try

**Comment by zldlhn** [comment] 2022-02-18 09:34
> Your version is supported. https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

it works well on V19042.1526. Thanks

**Comment by sebaxakerhtc** [comment] 2022-02-18 12:22
Duplicate of https://github.com/stascorp/rdpwrap/issues/1697

**Closed as completed by sebaxakerhtc** 2022-02-18 12:22 UTC
