### ISSUE TITLE
Not listening Win Server 2022 updated

### ISSUE THREAD

**Issue by heavymasterx** [stascorp/rdpwrap#2181] opened 2023-04-26 13:12 UTC
already follow all the tips that I found here in this session, I already uninstalled and installed, commands and more commands without solution.
I'll attach my DLL, so you can look.
![Captura de tela 2023-04-26 095658](https://user-images.githubusercontent.com/131882272/234585029-2de92132-eee1-4f28-ad60-fd2d302f7575.png)

[Uploading termsrv.zip…]()

**Comment by sashaqwert** [comment] 2023-04-26 13:14
Duplicate of https://github.com/stascorp/rdpwrap/issues/2169

**Comment by heavymasterx** [comment] 2023-04-26 13:15
Not duplicate this solution not work

**Closed as not planned by sashaqwert** 2023-04-26 13:14 UTC
Labels: duplicate

**Comment by sashaqwert** [comment] 2023-04-26 14:44
> Not duplicate this solution not work

Please, write your questions to INI developer in Discord: https://discord.gg/N27yFftWP3
