### ISSUE TITLE
Help rdpwrap.ini for Windows 10 Build 19045.5011 is not support

### ISSUE THREAD

**Issue by avatarlmao** [stascorp/rdpwrap#3298] opened 2024-10-11 04:49 UTC
I have a new window update install adn the rdpwrap is not support can anyone help?

**Comment by avatarlmao** [comment] 2024-10-11 05:07
[termsrv.zip](https://github.com/user-attachments/files/17337963/termsrv.zip)
Here is the file Thank you for support me asap

**Comment by RLang0980** [comment] 2024-10-11 15:01
Hi. Could yo tell me how to use the file termsrv.dll? Thanks a lot.

**Comment by binarymaster** [comment] 2024-10-11 20:37
The version of termsrv.dll attached is 10.0.19041.4474, so this is duplicate of https://github.com/stascorp/rdpwrap/issues/2840.

**Closed as not planned by binarymaster** 2024-10-11 20:37 UTC
Labels: duplicate
