### ISSUE TITLE
fully supported but [Not Listening] on 19041.622

### ISSUE THREAD

**Issue by ElliotQi** [stascorp/rdpwrap#1251] opened 2020-12-17 12:43 UTC
![image](https://user-images.githubusercontent.com/46469021/102488971-cc864600-40a7-11eb-8ec4-3d53b4aa06f8.png)
I've changed my rfxvmt.dll, reinstalled rdp. But it didn't  work

**Comment by ElliotQi** [comment] 2020-12-17 13:04
Oh, I solved the problem by restart the termservice
net stop termservice
net start termservice
And the Listener state turned to be green

**Comment by look0613415** [comment] 2020-12-25 11:45
https://github.com/stascorp/rdpwrap/issues/1246#issuecomment-751237612

**Comment by look0613415** [comment] 2020-12-25 11:45
https://github.com/stascorp/rdpwrap/issues/1246#issuecomment-751237612

**Comment by ElliotQi** [comment] 2020-12-25 11:55
> [#1246 (comment)](https://github.com/stascorp/rdpwrap/issues/1246#issuecomment-751237612)

fully supported 代表已经更新到最新版本到配置文件了

**Comment by JiangYizhou16** [comment] 2021-01-14 01:43
I met the same problem. I updated my ini and restart the termservice, however it still doesn't works 'Not listening'...
Does the same probelm happen to you anymore?

**Comment by ElliotQi** [comment] 2021-01-14 06:13
> I met the same problem. I updated my ini and restart the termservice, however it still doesn't works 'Not listening'...
> Does the same probelm happen to you anymore?

After restarting the termservice , my rdpwrapper works well. Could you check the process of restarting?

**Comment by JiangYizhou16** [comment] 2021-01-16 11:59
I have never solved this problem in 19041.622, but it works after I updated to 19041.746 …… amazing

**Comment by sebaxakerhtc** [comment] 2022-04-27 15:04
Duplicate of https://github.com/stascorp/rdpwrap/issues/872

**Comment by ElliotQi** [comment] 2022-04-27 15:05
您好,邮件已收到,会尽快处理

**Closed as completed by sebaxakerhtc** 2022-04-27 15:04 UTC

**Comment by dahe46** [comment] 2023-04-03 15:26
> > I met the same problem. I updated my ini and restart the termservice, however it still doesn't works 'Not listening'...
> > Does the same probelm happen to you anymore?
> 
> After restarting the termservice , my rdpwrapper works well. Could you check the process of restarting?

I met the same problem,help me
