### ISSUE TITLE
Not working on Build 14352.rs1_release.160522-1930 with latest update

### ISSUE THREAD

**Issue by garrettwp** [stascorp/rdpwrap#122] opened 2016-06-02 08:32 UTC
The latest update to support Windows 10 version 14352 is not working. When trying to remote desktop I receive the following dialog message "An internal error occurred." Then the terminal service stops running and needs to be restarted and same issue happens again.

Screen Shots:

![rdp_error](https://cloud.githubusercontent.com/assets/9434840/15738783/e3188008-287a-11e6-9a5d-2269df15a33e.jpg)
![rdpwrapconfig](https://cloud.githubusercontent.com/assets/9434840/15738782/e3168d2a-287a-11e6-9892-6d1c4d0e5389.jpg)

Attached event log:

[rdp_error.txt](https://github.com/stascorp/rdpwrap/files/295179/rdp_error.txt)

**Comment by binarymaster** [comment] 2016-06-17 19:13
Duplicate of https://github.com/stascorp/rdpwrap/issues/121

(fixed, run update)

**Closed by binarymaster** 2016-06-17 19:13 UTC
Labels: duplicate
