### ISSUE TITLE
Not Supported 10.0.22610.1

### ISSUE THREAD

**Issue by dungmn** [stascorp/rdpwrap#1835] opened 2022-05-06 10:14 UTC
![image](https://user-images.githubusercontent.com/28902802/167112689-6823af2d-4eff-48f0-9366-faed06322d07.png)
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/8639242/termsrv.zip)
Plz help me!

**Comment by sebaxakerhtc** [comment] 2022-05-07 21:14
Duplicate of https://github.com/stascorp/rdpwrap/issues/1830

**Closed as completed by sebaxakerhtc** 2022-05-07 21:14 UTC
