### ISSUE TITLE
Problems with RDP wrapper after Windows 10 Pro update (version 1703 x64) KB4338826 (2018-07)

### ISSUE THREAD

**Issue by Yoki90** [stascorp/rdpwrap#525] opened 2018-07-25 07:11 UTC
RDP Wrapper Listener state: Listening [Not Supported] after the latest Windows 10 Pro update.  Wrapper version 1.5.0.0.

Any ideas to let it work with the newest update? Reïnstalling RDP Wrapper or updating the ini-file does not help. Thanks!

**Comment by Yoki90** [comment] 2018-07-25 09:59
Sorry, forgot to mention the termsrv.dll version number. Before the update I had version: 10.0.15063.0 and after the update, the version number is: 10.0.15063.1155.

Thank you!

**Comment by Yoki90** [comment] 2018-07-25 10:02
This is the file (version 10.0.15063.1155): [termsrv.zip](https://github.com/stascorp/rdpwrap/files/2227467/termsrv.zip)

**Comment by binarymaster** [comment] 2018-07-25 11:19
Your issue is a duplicate of #506 then.

**Closed by binarymaster** 2018-07-25 11:19 UTC
