### ISSUE TITLE
10.0.19041.1741 [Not supported] 

### ISSUE THREAD

**Issue by christian-westbrook** [stascorp/rdpwrap#1954] opened 2022-08-08 03:04 UTC
File upload: [termsrv.zip](https://github.com/stascorp/rdpwrap/files/9278379/termsrv.zip)

**Comment by christian-westbrook** [comment] 2022-08-08 03:06
Hello! GitHub says that it doesn't support .dll files. I'd like to upload my termsrv.dll file as requested under other issues.

Edit: Uploaded as a .zip!

**Comment by sashaqwert** [comment] 2022-08-08 05:43
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881

**Closed as not planned by sashaqwert** 2022-08-08 05:43 UTC
