### ISSUE TITLE
"Fully suppoerted" has been displayed, but multiple RDP still does not work.

### ISSUE THREAD

**Issue by HubertStone** [stascorp/rdpwrap#1930] opened 2022-07-13 12:18 UTC
"Fully suppoerted" is displayed on RDP conf, but multiple remote desktop connections are still not allowed. "Another user is signed in. If you continue, they'll be disconnected. Do youwant to sign in anyway?" is displayed in the log in screen.
![image](https://user-images.githubusercontent.com/44018104/178731590-a4af2c04-0842-4ac3-823e-c6b112c685bf.png)

**Comment by HubertStone** [comment] 2022-07-13 12:22
![image](https://user-images.githubusercontent.com/44018104/178732344-e050dc78-7fb9-4aee-a207-1b2e6a5dff36.png)
The text means that "Another user is signed in. If you continue, they'll be disconnected. Do youwant to sign in anyway?"

**Comment by sashaqwert** [comment] 2022-07-13 12:38
Duplicate of https://github.com/stascorp/rdpwrap/issues/1868

**Comment by sashaqwert** [comment] 2022-07-13 12:39
Try reboot Windows or restart service

**Closed as completed** 2022-07-13 12:40 UTC

**Comment by HubertStone** [comment] 2022-07-13 12:43
> ry reboot Windows or restart service

Thanks. But they don't work.

**Comment by sashaqwert** [comment] 2022-07-13 14:00
Try modded version by sebaxakerhtc
https://github.com/sebaxakerhtc/rdpwrap/releases
