### ISSUE TITLE
The window version is not recognized

### ISSUE THREAD

**Issue by jingxin-yingsi-shaosiming-daye** [stascorp/rdpwrap#3356] opened 2024-11-22 02:30 UTC
![c3ff82881663223bd1e9febbe23b407](https://github.com/user-attachments/assets/7885349f-b86c-4bbc-a9dd-9dd26345115c)

**Comment by jingxin-yingsi-shaosiming-daye** [comment] 2024-11-22 02:33
![image](https://github.com/user-attachments/assets/983c6cd4-4ec5-41dd-9de7-eb52cdd68a00)

**Comment by binarymaster** [comment] 2024-11-22 11:50
> ver. N/A

You have been antivirused (your antivirus software is too smart and deleted critical system files), contact Telegram support.

Not RDP Wrapper problem. Duplicate of https://github.com/stascorp/rdpwrap/issues/277.

**Closed as not planned by binarymaster** 2024-11-22 11:50 UTC
Labels: duplicate
