### ISSUE TITLE
Win 11 10.0.22621.3085

### ISSUE THREAD

**Issue by UmfOfficial** [stascorp/rdpwrap#2482] opened 2024-02-10 08:18 UTC
Hello, it doesn't work for me.

![Névtelen](https://github.com/stascorp/rdpwrap/assets/159612888/e6dadc8c-e404-4a20-bee4-f74feb31da80)

**Comment by sashaqwert** [comment] 2024-02-10 13:32
Duplicate of https://github.com/stascorp/rdpwrap/issues/2469

**Closed as not planned by sashaqwert** 2024-02-10 13:32 UTC
Labels: duplicate
