### ISSUE TITLE
10.0.17763.168 This version of Terminal Services is not supported.

### ISSUE THREAD

**Issue by etalot** [stascorp/rdpwrap#3386] opened 2024-12-14 15:15 UTC
Please add support 10.0.17763.168

![RDP](https://github.com/user-attachments/assets/6bae40e6-2aa2-4e2d-b72b-2e6c8aae8283)

![RDP2](https://github.com/user-attachments/assets/87ff5105-0627-408a-bace-5860bf2e183d)

[termsrv.dll.zip](https://github.com/user-attachments/files/18136352/termsrv.dll.zip)

**Comment by binarymaster** [comment] 2024-12-14 15:26
Duplicate of https://github.com/stascorp/rdpwrap/issues/606.

**Closed as not planned by binarymaster** 2024-12-14 15:26 UTC
Labels: duplicate
