### ISSUE TITLE
how to fix Wrapper state: 3rd-party

### ISSUE THREAD

**Issue by isotiredqq** [stascorp/rdpwrap#3264] opened 2024-09-03 13:57 UTC
![image](https://github.com/user-attachments/assets/e0a3336d-d56b-4053-a2ba-b9947f7bea75)

**Comment by binarymaster** [comment] 2024-09-03 13:59
Duplicate of #1618.

**Closed as not planned by binarymaster** 2024-09-03 13:59 UTC
Labels: duplicate

**Comment by isotiredqq** [comment] 2024-09-03 14:13
or how to uninstall

**Comment by binarymaster** [comment] 2024-09-03 14:15
Consult the information in referred ticket.
