### ISSUE TITLE
Isn't this illegal?

### ISSUE THREAD

**Issue by icofs223** [stascorp/rdpwrap#2343] opened 2023-09-25 19:22 UTC
It likely violates the EULA of Microsoft.

**Comment by sashaqwert** [comment] 2023-09-25 19:39
Duplicate of https://github.com/stascorp/rdpwrap/issues/26

**Comment by sashaqwert** [comment] 2023-09-25 19:41
Duplicate of https://github.com/stascorp/rdpwrap/issues/26

**Closed as not planned by sashaqwert** 2023-09-25 19:41 UTC
Labels: duplicate
