### ISSUE TITLE
is there a problem with my termsrv

### ISSUE THREAD

**Issue by undead2cold** [stascorp/rdpwrap#1732] opened 2022-02-18 20:45 UTC
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/8100309/termsrv.zip)

my service still isnt working.

**Comment by sashaqwert** [comment] 2022-02-20 15:29
Your DLL version is 10.0.19041.1503.
Please, do not change DLL to ZIP.
Please, pack your DLL in ZIP archive...

# Duplicate of https://github.com/stascorp/rdpwrap/issues/1697

**Closed as completed** 2022-02-21 20:07 UTC
