### ISSUE TITLE
Connecting to Win10 Home - worked for 2 weeks and now it doesent?

### ISSUE THREAD

**Issue by hemantx** [stascorp/rdpwrap#146] opened 2016-08-26 14:29 UTC
Not sure what has happened. Installed 1.6.1 on 8/16 and have been using it fine ever since. Now today, when i try to connect, it appears that the connection occurs...I get a black screen as it is initializing the desktop, then it closes out.

On the Win10 pc, the only event that appears is in the Windows Application log - I see event 4005 "The Windows logon process has unexpectedly terminated.".

Any assistance would be greatly appreciated. 

FYI Termsrv.dll is 10.0.10586.0.

Thanks!

**Comment by binarymaster** [comment] 2017-01-20 07:53
No answers from other users since August 2016, so closing as can't reproduce.

**Closed by binarymaster** 2017-01-20 07:53 UTC

**Comment by jmbeach** [comment] 2017-03-13 19:22
Same error

**Comment by binarymaster** [comment] 2017-03-13 19:27
@jmbeach Diagnostics screenshot? System configuration?

**Comment by jmbeach** [comment] 2017-03-13 23:20
Restart fixed it.

**Comment by jmbeach** [comment] 2017-03-13 23:20
Windows 10 Home. Event Viewer said failed to login user.
Steps: Installed with batch file and tried rdp into my machine

**Comment by binarymaster** [comment] 2017-03-14 08:18
You need to use valid administrator account for logging in remotely.

**Comment by jmbeach** [comment] 2017-03-14 13:48
I did. Don't think that was the problem. It was the first time I used it. For whatever reason, restarting fixed the problem. I tried using `RDPCheck.exe`, using RDP from my machine, and another machine. They would log in, go to a black screen and then fail with an error message I can't remember. And "User log on failed" was in the event logs.

**Comment by djrobx** [comment] 2017-03-20 03:21
I'm seeing issues like this too, on Win10 Pro.   It will work for a short period of time following reboot (and the RDP session will work fine indefinitely, if it successsfully connects), but after some amount of time, trying to re-login results in a black screen.  The event log is full of 4005 winlogon errors.  

No unusual software loaded.  Tried two different network adapters.

There is some reports of similar issues on Windows Server 2012R2 especially if Webroot is installed.  Unfortunately on Win10 if it inherited this "bug" its much more difficult to remove the offending patch since they seem to roll everything up.
