### ISSUE TITLE
Access denied error

### ISSUE THREAD

**Issue by KNavin10** [stascorp/rdpwrap#2224] opened 2023-05-27 17:01 UTC
Hi,
I am not able to login to remote desktop using RDPCheck.exe, have given my Microsoft user login
![image](https://github.com/stascorp/rdpwrap/assets/128822880/2aa1402b-e0d2-4e0e-838b-be55561e155c)

Following is my config:
![image](https://github.com/stascorp/rdpwrap/assets/128822880/f6d869e1-8763-4f76-93d2-43ade5b13f55)

This is for Windows 10 Home edition, so cant add user to RDP group.

**Comment by sashaqwert** [comment] 2023-05-27 18:22
> This is for Windows 10 Home edition, so cant add user to RDP group.

You can add administrators.

One `termsrv.dll` version = ONE opened issue.

**Comment by sashaqwert** [comment] 2023-05-27 18:24
Duplicate of https://github.com/stascorp/rdpwrap/issues/2180

**Closed as not planned by sashaqwert** 2023-05-27 18:24 UTC
Labels: duplicate

**Comment by KNavin10** [comment] 2023-05-28 02:31
The user I am using in RDPCheck.exe is already added to administrators.
Still getting 'Access is denied'

**Comment by sashaqwert** [comment] 2023-05-28 07:23
> The user I am using in RDPCheck.exe is already added to administrators.
> Still getting 'Access is denied'

See https://github.com/stascorp/rdpwrap/issues/101
