### ISSUE TITLE
19041.4235 rdp not work

### ISSUE THREAD

**Issue by compocare** [stascorp/rdpwrap#2525] opened 2024-03-21 08:40 UTC
rdp  not work in win 10 pro 64bit how to resolve this problem

**Comment by loyejaotdiqr47123** [comment] 2024-03-22 08:14
#2524

**Comment by sashaqwert** [comment] 2024-03-23 14:21
Duplicate of https://github.com/stascorp/rdpwrap/issues/2524

**Closed as not planned by sashaqwert** 2024-03-23 14:21 UTC
Labels: duplicate
