### ISSUE TITLE
10.0.19041.2075 - multiple RDP sessions working ok but logs off local session

### ISSUE THREAD

**Issue by JayMonkey** [stascorp/rdpwrap#2064] opened 2022-12-07 18:30 UTC
Hi,

So after successfully installing RDP Wrapper with the updated ini file, running RDPConf shows all is well in the diagnostics and I can use RDPCheck to create multiple sessions locally ... so RDP Wrapper is working ok in that respect.

However when I start a RDP session from a remote client and log in with the same user id as the local session, it logs off the local session ?

I'm running Windows 10 Pro version 22H2, termsvr.dll is reported as version 10.0.19041.2075.

Is there some registry setting or group policy that needs setting so that the local session is **not** logged out when a RDP session is started with the same user account / id ?

I never had this issue with the previous version of Windows 10 ?

Many thanks in advance

Cheers
Jay

**Comment by Cybernose** [comment] 2022-12-07 18:35
Did you make sure that you have the box unchecked for single connections?

**Comment by JayMonkey** [comment] 2022-12-07 21:55
> Did you make sure that you have the box unchecked for single connections?

Yes,

Check box for single connection is unchecked in RDPConf

I also checked in gpedit 

Allow RDP connections is enabled
Single connection is disabled

like i said, i can use RDPCheck multiple times on the host to create multiple local RDP sessions in a browser and it's working fine and it does not log off the main local session.

I just need to stop it logging off the local session when a remote RDP session is started.

**Comment by Cybernose** [comment] 2022-12-07 23:04
Attaching RDP Wrapper Configuration probably will not help.

![Screenshot 2022-12-07 170207](https://user-images.githubusercontent.com/25756235/206316009-09793f27-beb3-4dda-97f5-ca072ab54ce2.png)

**Comment by Cybernose** [comment] 2022-12-07 23:07
As a last thought, I usually set up an admin account on the computer with RDP Wrapper and have different accounts for the end user(s).

**Comment by sashaqwert** [comment] 2022-12-08 08:27
This is known bug ()Not associated with a specific version of `termsrv.dll` and offsets for it

**Comment by sashaqwert** [comment] 2022-12-08 08:27
Duplicate of https://github.com/stascorp/rdpwrap/issues/1952

**Closed as not planned by sashaqwert** 2022-12-08 08:27 UTC

**Comment by JayMonkey** [comment] 2022-12-08 14:03
Ok so I've done some more testing today and this is what I've found : -

1. Boot up host computer and login.
2. Initiate RDP session on remote computer - causes session on remote host to logout
3. Log back on, on the host with the same user id and the remote session is unaffected.
4. After this I can disconnect remote RDP session and re-connect with effecting the local session on the host.

**Summary:** Only the first remote RDP session will cause the local session on the host to logout, after that the local session on the remote host can be re-logged in and remote RDP sessions can then be done as many times as required (connect/disconnect) without effecting the local session on the host computer until the host is rebooted.

My previous versions of Windows 10 Pro did not do the so this is either a bug or a new behavior by design (Thanks M$)

**Edit:** I've since also found that if I start a  remote RDP session while the host is still logging in for the first time (I have auto login enabled on the host) then both the host and remote session will start ok (without the host logging off). Timing needs to be perfect but it does work. II can do this as the host is in the next room, but this obviously won't work for the majority of users.

It seems that the initial host local session being logged off is bug with version 10.0.19041.2075 as reported by multiple users in the link posted below.

Cheers
Jay

**Comment by RickTorresJr** [comment] 2023-03-09 00:46
> Ok so I've done some more testing today and this is what I've found : -
> 
> 1. Boot up host computer and login.
> 2. Initiate RDP session on remote computer - causes session on remote host to logout
> 3. Log back on, on the host with the same user id and the remote session is unaffected.
> 4. After this I can disconnect remote RDP session and re-connect with effecting the local session on the host.
> 
> **Summary:** Only the first remote RDP session will cause the local session on the host to logout, after that the local session on the remote host can be re-logged in and remote RDP sessions can then be done as many times as required (connect/disconnect) without effecting the local session on the host computer until the host is rebooted.
> 
> My previous versions of Windows 10 Pro did not do the so this is either a bug or a new behavior by design (Thanks M$)
> 
> **Edit:** I've since also found that if I start a remote RDP session while the host is still logging in for the first time (I have auto login enabled on the host) then both the host and remote session will start ok (without the host logging off). Timing needs to be perfect but it does work. II can do this as the host is in the next room, but this obviously won't work for the majority of users.
> 
> It seems that the initial host local session being logged off is bug with version 10.0.19041.2075 as reported by multiple users in the link posted below.
> 
> Cheers Jay

Thanks for sharing your work around. I had the same problem but I couldn't get your workaround going until I did the following:


* `gpedit` -> Computer Configuration -> Administrative Templates -> Windows Components -> Remote Desktop Services -> Remote Desktop Session Host -> Connections section ->
    * "Restrict Remote Desktop Services users to a single Remote Desktop session" -> **DISABLED (previously enabled as instructed in guides to override the next option)**
    * “Limit number of connections” -> Change its value to 999999
    * Admin Command Prompt: `gpupdate /force`

**Comment by Haithamdarweash** [comment] 2023-11-20 10:20
i tried all the solutions but the RDP is not wokring anymore for the multi users
