### ISSUE TITLE
Windows 10 10.0.19045.2965 not supported

### ISSUE THREAD

**Issue by wox080xow** [stascorp/rdpwrap#2214] opened 2023-05-25 02:18 UTC
My Windows 10 version is 10 10.0.19045.2965.
![Screen Shot 2023-05-25 at 10 03 31 ](https://github.com/stascorp/rdpwrap/assets/50339668/155ecdd2-577e-4daf-a3ac-61605f6d1b56)

I found the the INI file of version 10.0.19041.2913 is not fully supported for my Windows 10.
![Screen Shot 2023-05-25 at 10 03 04 ](https://github.com/stascorp/rdpwrap/assets/50339668/4be3e455-d125-4e0e-9517-4563456bbf7c)

Could you please help us fix the problem?
The attachment is the `termsrv.dll` of Windows 10 of version 10.0.19045.2965.
[termsrv.dll.zip](https://github.com/stascorp/rdpwrap/files/11560520/termsrv.dll.zip)

**Comment by sashaqwert** [comment] 2023-05-25 06:21
Duplicate of https://github.com/stascorp/rdpwrap/issues/2180

**Closed as not planned by sashaqwert** 2023-05-25 06:21 UTC
Labels: duplicate

**Comment by sashaqwert** [comment] 2023-05-25 06:23
> The attachment is the `termsrv.dll` of Windows 10 of version 10.0.19045.2965.

`termsrv.dll` version != Windows version. Please, use only `termsrv.dll` version in issue title

**Comment by wox080xow** [comment] 2023-05-26 01:50
Thank you! Finally, I am able to log in remotely with multiple users.
