### ISSUE TITLE
Windows Server 2008 R2 (and maybe Windows 7) RDPWrap killed by update 4462923 

### ISSUE THREAD

**Issue by kevindaley** [stascorp/rdpwrap#587] opened 2018-10-11 10:37 UTC
Windows Update KB4462923 renders RDPWrap inoperative. RDP is limited to the standard 2 connections. Removing the update allows RDPWrap to work again. Switching automatic updates off prevents the change occurring .... but for how long?

Who knows whether this is a bug that can be fixed, or a move by Microsoft, who apparently now own GitHub, to kill the utility.

Anyone in the RDPWrap dev team know the answer?

**Comment by binarymaster** [comment] 2018-10-11 11:05
Are you using RDP Wrapper for the first time? **RTFM!**

Duplicate of #572 and #586 !

**Closed by binarymaster** 2018-10-11 11:05 UTC

**Comment by kevindaley** [comment] 2018-10-11 13:01
No. I've been using RDP Wrapper for over 3 years and this problem has not
occurred before.

What are you referring to in TFM?

**Comment by binarymaster** [comment] 2018-10-11 15:02
@kevindaley I'm referring to the update procedure.

**Comment by kevindaley** [comment] 2018-10-12 11:00
Removed the Windows Update and RDPWrap. Installed the Windows Update again
(+ all others available), then RDPWrap + update, and this time all is well.

**Comment by ZeljkoManjkas** [comment] 2018-10-12 13:43
kevindaley. Can you explain your steps in deep?
I have same problems.

**Comment by kevindaley** [comment] 2018-10-12 15:56
Sure. Windows 2008 R2 Server (based on Windows 7) installed an automatic
update KB4462923, that stopped RDPWrap from operating. Only the standard 2
remote sessions could be used.

I removed the Windows Update and RDPWrap ran fine for a day, but overnight
the update was reinstalled and the 2 session restriction came back.

So I removed both RDPWrap and the Windows Update, then manually installed
all available Windows Updates. I then reinstalled RDPWrap and its updates.

The additional sessions became available and have been fine for 2 days now.

Hope this helps

**Comment by ZeljkoManjkas** [comment] 2018-10-16 12:35
Thank you kevindaley.
Now works.

Uninstall RDPWrap with uninstall.bat, remove KB4462923 (restart), TermSrv.dll is still .24234, remove KB4457139 (restart), now TermSrv.dll is .18637, install KB4462923, install RDPWrap with install.bat, check third user with RDPCheck (1 console user and 2 RDP users),

**Comment by juanjuanjo** [comment] 2018-10-16 21:54
Thanks a lot! Now works
