### ISSUE TITLE
Win srv2022 21H2 10.0.20348.1607 [not supported]

### ISSUE THREAD

**Issue by inter010** [stascorp/rdpwrap#2237] opened 2023-06-02 01:44 UTC
Hello, I had 'not supported' problem win srv2022 
I attach termsrv.dll file.

Thank you for your support and help.
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/11631083/termsrv.zip)

**Comment by sebaxakerhtc** [comment] 2023-06-02 06:20
> Hello, I had 'not supported' problem win srv2022 I attach termsrv.dll file.
> 
> Thank you for your support and help. [termsrv.zip](https://github.com/stascorp/rdpwrap/files/11631083/termsrv.zip)

Look at termsrv.dll version, not Windows version!
Your termsrv.dll version is 10.0.20348.1547

Duplicate of https://github.com/stascorp/rdpwrap/issues/2117

**Closed as completed by sebaxakerhtc** 2023-06-02 06:20 UTC
Labels: duplicate

**Comment by deepalarm** [comment] 2023-06-02 07:07
not working 
win srv 2022 stardart 
21h2

**Comment by inter010** [comment] 2023-06-02 08:25
> > Hello, I had 'not supported' problem win srv2022 I attach termsrv.dll file.
> > Thank you for your support and help. [termsrv.zip](https://github.com/stascorp/rdpwrap/files/11631083/termsrv.zip)
> 
> Look at termsrv.dll version, not Windows version! Your termsrv.dll version is 10.0.20348.1547
> 
> Duplicate of #2117

OMG sorry. 
now it works well.

many thanks :)
