### ISSUE TITLE
Both Windows Defender and Malwarebytes detect PUAs and malware.

### ISSUE THREAD

**Issue by revantTNK** [stascorp/rdpwrap#2136] opened 2023-03-06 09:01 UTC
Hi.
I am trying to install RDPWrap on Windows 11 Home, and when I try and unzip the binary or open the MSI installer, Windows Defender blocks it and Malwarebytes detects "Bladabindi.Backdoor.Bot.DDS". Is this a false positive or something else?

![image](https://user-images.githubusercontent.com/88229702/223064063-571d3bb0-d57b-4ee1-b9b1-2ee3c56800c6.png)

![image](https://user-images.githubusercontent.com/88229702/223064241-6e8690e8-5690-4e74-9b89-70b938b09e4e.png)

**Comment by sashaqwert** [comment] 2023-03-06 17:10
Duplicate of https://github.com/stascorp/rdpwrap/issues/277

**Closed as not planned by sashaqwert** 2023-03-06 17:10 UTC
Labels: duplicate

**Comment by sashaqwert** [comment] 2023-03-06 17:12
> MSI installer

MSI is not works correctly now. Use ZIP version, them replace the `rdpwrap.ini` manually.
