### ISSUE TITLE
ver. 10.0.19041.2075 not supported

### ISSUE THREAD

**Issue by EliasEnns** [stascorp/rdpwrap#2059] opened 2022-11-29 11:23 UTC
![image](https://user-images.githubusercontent.com/38816416/204516493-37f7dcbc-b492-468f-9bdd-0ec8f2b97b7b.png)

**Comment by sashaqwert** [comment] 2022-11-29 11:29
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992

**Closed as not planned by sashaqwert** 2022-11-29 11:29 UTC
Labels: duplicate
