### ISSUE TITLE
Windows 10 Home Single Language

### ISSUE THREAD

**Issue by irwingato** [stascorp/rdpwrap#917] opened 2019-10-27 19:30 UTC
I have already tried all the possilities listed right here but none of them worked, I am using the Windows 10 Home Single Language version 1903(Compilation of the operacional System 18362.418).
Does anyone know what I should do in my computer to the program work fine here?
I tried to download the lastest version, but didn't work here, I tried other solutions too

**Comment by SobieskiCodes** [comment] 2019-10-28 11:50
What are some of the 'solutions' you've tried? Can't help you if you can't give me details.
You don't bring your car to the mechanic and say 'it doesn't work'

**Comment by irwingato** [comment] 2019-10-28 12:09
I have tried this #906, #837, and others, that is the image that show when I use the RDPConf
![image](https://user-images.githubusercontent.com/45997584/67677231-44545700-f962-11e9-813e-7c0560260ed2.png)

**Comment by SobieskiCodes** [comment] 2019-10-28 12:12
10 home should be the same build as https://github.com/stascorp/rdpwrap/issues/906
Can you walk me through the steps you've taken when trying them?
You've completely uninstalled before attempting any new configurations and rebooted before trying the new one, correct?

**Comment by irwingato** [comment] 2019-10-29 00:30
I forgot to uninstall and reboot the system now it is working on my pc

**Comment by sebaxakerhtc** [comment] 2022-06-20 10:15
Duplicate of https://github.com/stascorp/rdpwrap/issues/871

**Closed as completed by sebaxakerhtc** 2022-06-20 10:15 UTC
