### ISSUE TITLE
W11 Pro - 22H2 - 22621.1848

### ISSUE THREAD

**Issue by Razuken** [stascorp/rdpwrap#2250] opened 2023-06-18 06:36 UTC
the issue is ;
the number of connections to this computer is limited and all connections are in use right now.

**Comment by sashaqwert** [comment] 2023-06-18 10:37
~~Please, attach your RDPConf screenshot and `termsrv.dll`.~~

**Comment by sashaqwert** [comment] 2023-06-18 10:39
`termsrv.dll` version != Windows version!

![изображение](https://github.com/stascorp/rdpwrap/assets/24974508/30614d9d-4f90-4998-b6fe-ad255143a409)

**Comment by sashaqwert** [comment] 2023-06-18 10:41
Duplicate of https://github.com/stascorp/rdpwrap/issues/2213

**Closed as not planned by sashaqwert** 2023-06-18 10:41 UTC
Labels: duplicate
