### ISSUE TITLE
10.0.19041.3636 not supported

### ISSUE THREAD

**Issue by JEST28** [stascorp/rdpwrap#2407] opened 2023-11-15 13:32 UTC
![image](https://github.com/stascorp/rdpwrap/assets/150926597/c64f9fa6-95d3-419b-b4fe-ab6d4487a533)

**Comment by fweb** [comment] 2023-11-15 16:48
rdpwrap.ini from this https://github.com/stascorp/rdpwrap/issues/2406 fixed it for me. maybe you can try?

**Comment by sashaqwert** [comment] 2023-11-16 07:02
Duplicate of https://github.com/stascorp/rdpwrap/issues/2381

**Closed as not planned by sashaqwert** 2023-11-16 07:02 UTC
Labels: duplicate
