### ISSUE TITLE
Windows 21H2 (OS Build 19044.1503)

### ISSUE THREAD

**Issue by ServerSheila** [stascorp/rdpwrap#1700] opened 2022-01-28 12:59 UTC
I upgraded Windows Build without noticing it.  Current build is Windows 21H2 OS Build 19044.1503) (as of 1/28/22) and now RD Wrap is not working.  

Please update ini file.

**Comment by sashaqwert** [comment] 2022-01-28 15:11
RDPConf screenshot, please...

**Comment by nattlip** [comment] 2022-01-28 15:14
https://github.com/stascorp/rdpwrap/issues/1697 ?

**Comment by ServerSheila** [comment] 2022-01-28 15:56
![Windows Version](https://user-images.githubusercontent.com/98594614/151579236-70c69988-3f30-4470-bb3f-95f62766aa59.PNG)

**Comment by ServerSheila** [comment] 2022-01-28 16:00
I uninstalled the upgrade and went to version 19044.1469 and now I can reconnect.  I will wait until a fix is announced before upgrading again.  thanks.

**Comment by sebaxakerhtc** [comment] 2022-01-29 09:17
Duplicate of https://github.com/stascorp/rdpwrap/issues/1697

**Closed as completed by sebaxakerhtc** 2022-01-29 09:17 UTC

**Comment by gan-iv** [comment] 2022-02-05 13:06
Hello!
Today I upgraded windows home to 19044.1503 release (21h2), and now have not worked rdpwrapper.
![screen](https://user-images.githubusercontent.com/99079671/152643198-c1406161-da4f-4e10-aea2-a1b06ba0c4b5.png)

**Comment by sashaqwert** [comment] 2022-02-05 13:53
@gan-iv 
> now have not worked rdpwrapper.

RDP Wrapper has been removed by antivirus.
The anti-virus cleared the Terminal server registry branch when uninstalling.  It needs to be restored from another system.

Backup from Windows 10 21H2: https://t.me/rdpwrap/38026
