### ISSUE TITLE
 or RDP wrapper dosent work on Windows 10  Pro 1709 or 1803

### ISSUE THREAD

**Issue by Mindaugas85** [stascorp/rdpwrap#684] opened 2019-02-25 11:45 UTC
I'm confused..
it seems so easy to install and configure, BUT maby i do wrong steps.
1. Ok, i'm installed fresh Windows 10 1709, disabled win updates.
2. Downloaded last rdprap 1.6.2
3. Extracted zip file
4. stopping terminal services in powershell
net stop termservice /y
5. run as administrator file:  install.bat (no errors)
6. run as administrator file: RDPConf.exe - everything fine- greennnn greeeen, checked NLA/ full user permsssions..
7. run as admin: RDP check - and -BAAAD 
ok, no proble, i'm configuring termsrv.dll file - changing values:
as here: https://www.mysysadmintips.com/windows/clients/545-multiple-rdp-remote-desktop-sessions-in-windows-10
copyring dll file to desktop>modyfying values, run in to hirens boot cd and replacing termsrv.dll file.
Restarting and- nooooo,- not working :((
It was one successfull way in 1803 update, but after restart - again the same..
What i do wrong??
in c:\program files\rdp wrapper\rdpwrap.ini list supports my terminal service version...

**Comment by binarymaster** [comment] 2019-02-25 12:17
Duplicate of #638 or #645. When in doubt, run RDPConf.

> What i do wrong??

The only thing you're doing wrong here is using GitHub issues for user support. You should use Telegram chat for it instead (see Readme).

**Closed as completed by binarymaster** 2019-02-25 12:17 UTC
Labels: duplicate
