### ISSUE TITLE
Version not supported: windows 11 22631.3880

### ISSUE THREAD

**Issue by xiaochopin** [stascorp/rdpwrap#3242] opened 2024-07-27 13:48 UTC
![image](https://github.com/user-attachments/assets/d275b7d1-4856-4a2d-a50c-30fd8e3926f3)

**Comment by binarymaster** [comment] 2024-07-27 14:43
Duplicate of https://github.com/stascorp/rdpwrap/issues/2833.

**Closed as not planned by binarymaster** 2024-07-27 14:43 UTC
Labels: duplicate
