### ISSUE TITLE
Not Working on W10 - version 1607 (build OS 14393.2485)

### ISSUE THREAD

**Issue by dimapplk** [stascorp/rdpwrap#555] opened 2018-09-12 21:04 UTC
![9210e40ec5](https://user-images.githubusercontent.com/43221158/45452877-ceeae000-b6e7-11e8-87a1-24136dce76fd.jpg)

1607 (14393.2485) is lasted for Windows 10 LTSB

[termserv.dll](https://yadi.sk/d/6LPyPhOugd36_Q)

**Comment by dimapplk** [comment] 2018-09-12 21:07
1607 (14393.2485) is lasted for Windows 10 LTSB

**Comment by binarymaster** [comment] 2018-09-12 22:02
Duplicate of #542.

**Closed by binarymaster** 2018-09-12 22:02 UTC
