### ISSUE TITLE
Windows update last friday broke my RDP

### ISSUE THREAD

**Issue by sk-lau** [stascorp/rdpwrap#1016] opened 2020-03-02 03:05 UTC
I'm using Windows 10 and last friday after the windows update it broke the multi user RDP

Does anyone have the same problem and the solution?

**Comment by leebinx** [comment] 2020-03-02 12:38
same issue, just updated on saturday night and went to login, no longer allows multiple logins. Will let you know if I find a fix for this.

**Comment by leebinx** [comment] 2020-03-02 12:40
may be the same issue as: https://github.com/stascorp/rdpwrap/issues/1013
I'm trying it and will update

**Comment by COIN1974** [comment] 2020-03-02 13:07
Have you tried to apply issue #860 ?

**Comment by leebinx** [comment] 2020-03-02 13:10
applied #988  - is now working :) 
you may need to restart the computer after updating the .ini file

**Comment by fatherchristmas87** [comment] 2020-03-02 18:59
I’m sorry, but what exactly in #988 worked for you? Can you post the correct INI and the steps you tried?

**Comment by leebinx** [comment] 2020-03-02 23:33
> I’m sorry, but what exactly in #988 worked for you? Can you post the correct INI and the steps you tried?

Problem: could not have multiple people logged in at one time (only one login per user name) 

Solution: downloaded the INI from https://github.com/stascorp/rdpwrap/issues/988 (at the top of the page there is a .zip file) and restarted my computer. 

It worked for me, your results may vary.

**Comment by sk-lau** [comment] 2020-03-03 07:13
Its working after applying #988

**Comment by sebaxakerhtc** [comment] 2022-06-20 10:28
Duplicate of https://github.com/stascorp/rdpwrap/issues/983

**Closed as completed by sebaxakerhtc** 2022-06-20 10:28 UTC
