### ISSUE TITLE
Windows 10 21H1 Update ~ 15th December, 2021 -- New termsrv.dll version 10.0.19043.1415

### ISSUE THREAD

**Issue by val-mik** [stascorp/rdpwrap#1664] opened 2021-12-16 07:17 UTC
Current RDPWrap settings
![rdpwrap_10-0-19043-1348](https://user-images.githubusercontent.com/96224445/146318258-1b8983e7-c88a-4a41-b630-d9876975ca2f.png)

Current OS versions
![termsrv--10 0 19043 1415--64bit_OS-specifications](https://user-images.githubusercontent.com/96224445/146324821-7f7a7388-d2bd-4646-b418-c5db73bcec55.png)

![termsrv--10 0 19043 1415--64bit_Installed_Programs](https://user-images.githubusercontent.com/96224445/146324844-86e7b7d8-1450-4355-8d03-10e13bc6c124.png)

![termsrv--10 0 19043 1415--64bit_Installed_updates](https://user-images.githubusercontent.com/96224445/146324859-931650c7-c8cf-43fc-b3c5-122f56717073.png)

![termsrv--10 0 19043 1415--64bit_search](https://user-images.githubusercontent.com/96224445/146324872-d3fe6ecd-0034-40f8-9534-472c1790a92f.png)

This update for Windows 10 20H1 has installed a new termsrv.dll

Here is the 64 bit version of the new DLL from Windows 10 20H1
[termsrv--10.0.19043.1415--64bit.zip](https://github.com/stascorp/rdpwrap/files/7725245/termsrv--10.0.19043.1415--64bit.zip)

Cant find settings for rdpwrap.ini for this OS build.

Please HELP

**Comment by LightmanHub** [comment] 2021-12-16 08:28
Use sections [10.0.19041.1387] and [10.0.19041.1387-SLInit] from here 
https://github.com/stascorp/rdpwrap/issues/1662

**Comment by ForwardUntoDawn** [comment] 2021-12-16 14:00
This fix set the wrapper state to "Fully Supported" but oddly I cannot make multiple connections to the box without a message that another user is signed in - I don't think I've run into that oddity before.  Any suggestions for an additional edit to the INI?

![RDP 2021-12-15](https://user-images.githubusercontent.com/23408644/146385405-2550aa6e-8c19-4096-9052-6a439325bf33.jpg)

**Comment by toitc** [comment] 2021-12-16 16:32
Same issue here.  Shows fully supported but multi-user logins don't actually work.  

And I cannot seem to be able to uninstall the Service Stack Update.

**Comment by sashaqwert** [comment] 2021-12-16 16:50
Duplicate of https://github.com/stascorp/rdpwrap/issues/1630
Windows version doesn't matter. Search is carried out ONLY according to termsrv.dll version (can be found in RDPConf)

**Comment by DonoDayZ** [comment] 2021-12-16 17:34
![image](https://user-images.githubusercontent.com/37817874/146420686-1bdf9b3b-5cfc-4bb3-b30a-dd81a3f32129.png)
not work for me

**Comment by ForwardUntoDawn** [comment] 2021-12-16 17:43
> Duplicate of #1630 Windows version doesn't matter. Search is carried out ONLY according to termsrv.dll version (can be found in RDPConf)

Rock on, @sashaqwert - That sorted me out.  Thanks for the assist and pointing me in the right direction.
Apologies for the post in the duplicate issue. I often have a hard time figuring out which of these I should be looking in for the updated INI.

**Comment by sebaxakerhtc** [comment] 2021-12-17 15:43
Duplicate of https://github.com/stascorp/rdpwrap/issues/1630

**Closed as completed by sebaxakerhtc** 2021-12-17 15:43 UTC
