### ISSUE TITLE
Not supported 10.0.17763.4644 Help 

### ISSUE THREAD

**Issue by hknclk34** [stascorp/rdpwrap#2363] opened 2023-10-11 10:57 UTC
![image](https://github.com/stascorp/rdpwrap/assets/95570730/434ea331-d327-45fb-8427-94577570fac5)

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/12868587/termsrv.zip)

**Comment by sashaqwert** [comment] 2023-10-12 04:50
Duplicate of https://github.com/stascorp/rdpwrap/issues/2274

**Closed as not planned by sashaqwert** 2023-10-12 04:50 UTC
Labels: duplicate
