### ISSUE TITLE
10.0.19044.2251 not supported

### ISSUE THREAD

**Issue by namtn2** [stascorp/rdpwrap#2043] opened 2022-11-11 09:01 UTC
![image](https://user-images.githubusercontent.com/26757976/201305128-493baaad-8329-4407-9795-1db7fec52cc9.png)

**Comment by namtn2** [comment] 2022-11-11 09:06
> ![image](https://user-images.githubusercontent.com/26757976/201305128-493baaad-8329-4407-9795-1db7fec52cc9.png)

please help

**Comment by namtn2** [comment] 2022-11-11 09:06
please help

**Comment by sashaqwert** [comment] 2022-11-11 12:35
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by paulofrazao** [comment] 2022-11-11 21:45
same here. No longer working

**Comment by paulofrazao** [comment] 2022-11-11 21:46
![image](https://user-images.githubusercontent.com/45883050/201435294-d5dfaf88-ae13-4b0e-8705-306179303f38.png)
![image](https://user-images.githubusercontent.com/45883050/201435328-0c2f1ae6-c35f-40f1-b4ae-2dbc6f115605.png)

**Comment by namtn2** [comment] 2022-11-12 00:54
I don't have `termsrv.dll` 
![image](https://user-images.githubusercontent.com/26757976/201448665-17a2c979-6a84-4364-b89a-5c0608530ba2.png)

**Comment by namtn2** [comment] 2022-11-12 00:55
This is my `rdpwrap.ini`

[Main]
Updated=2022-09-26 
LogFile=\rdpwrap.txt
SLPolicyHookNT60=1
SLPolicyHookNT61=1

[SLPolicy]
TerminalServices-RemoteConnectionManager-AllowRemoteConnections=1
TerminalServices-RemoteConnectionManager-AllowMultipleSessions=1
TerminalServices-RemoteConnectionManager-AllowAppServerMode=1
TerminalServices-RemoteConnectionManager-AllowMultimon=1
TerminalServices-RemoteConnectionManager-MaxUserSessions=0
TerminalServices-RemoteConnectionManager-ce0ad219-4670-4988-98fb-89b14c2f072b-MaxSessions=0
TerminalServices-RemoteConnectionManager-45344fe7-00e6-4ac6-9f01-d01fd4ffadfb-MaxSessions=2
TerminalServices-RDP-7-Advanced-Compression-Allowed=1
TerminalServices-RemoteConnectionManager-45344fe7-00e6-4ac6-9f01-d01fd4ffadfb-LocalOnly=0
TerminalServices-RemoteConnectionManager-8dc86f1d-9969-4379-91c1-06fe1dc60575-MaxSessions=1000
TerminalServices-DeviceRedirection-Licenses-TSEasyPrintAllowed=1
TerminalServices-DeviceRedirection-Licenses-PnpRedirectionAllowed=1
TerminalServices-DeviceRedirection-Licenses-TSMFPluginAllowed=1
TerminalServices-RemoteConnectionManager-UiEffects-DWMRemotingAllowed=1

[PatchCodes]
nop=90
Zero=00
jmpshort=EB
nopjmp=90E9
CDefPolicy_Query_edx_ecx=BA000100008991200300005E90
CDefPolicy_Query_eax_rcx_jmp=B80001000089813806000090EB
CDefPolicy_Query_eax_esi=B80001000089862003000090
CDefPolicy_Query_eax_rdi=B80001000089873806000090
CDefPolicy_Query_eax_ecx=B80001000089812003000090
CDefPolicy_Query_eax_ecx_jmp=B800010000898120030000EB0E
CDefPolicy_Query_eax_rcx=B80001000089813806000090
CDefPolicy_Query_edi_rcx=BF0001000089B938060000909090

[10.0.19041.2075]
LocalOnlyPatch.x86=1
LocalOnlyOffset.x86=C3229
LocalOnlyCode.x86=jmpshort
SingleUserPatch.x86=1
SingleUserOffset.x86=3CC17
SingleUserCode.x86=Zero
DefPolicyPatch.x86=1
DefPolicyOffset.x86=3E1E9
DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
SLInitHook.x86=1
SLInitOffset.x86=70BC8
SLInitFunc.x86=New_CSLQuery_Initialize

[SLInit]
bServerSku=1
bRemoteConnAllowed=1
bFUSEnabled=1
bAppServerAllowed=1
bMultimonAllowed=1
lMaxUserSessions=0
ulMaxDebugSessions=0
bInitialized=1

[10.0.19041.2075-SLInit]
bInitialized.x86      =E498C
bServerSku.x86        =E4990
lMaxUserSessions.x86  =E4994
bAppServerAllowed.x86 =E499C
bRemoteConnAllowed.x86=E49A4
bMultimonAllowed.x86  =E49A8
ulMaxDebugSessions.x86=E49AC
bFUSEnabled.x86       =E49B0

**Comment by namtn2** [comment] 2022-11-12 00:58
my previous window version is 10.0.19041.2075

**Comment by yong718100** [comment] 2022-11-12 04:48
I used the following configuration to test successfully

https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/autogenerated/10.0.19041.2075-autogenerated_x64.ini

![image](https://user-images.githubusercontent.com/13732785/201457584-8d6ca479-3a28-4a74-adaa-79d0b179a328.png)

**Comment by sashaqwert** [comment] 2022-11-12 08:26
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992

**Closed as not planned by sashaqwert** 2022-11-12 08:26 UTC
Labels: duplicate

**Comment by sashaqwert** [comment] 2022-11-12 08:34
There is no way to determine the correct version of termsrv.dll for this issue without special search.

The name should contain the version of `termsrv.dll` from RDPConf that you want to support. Otherwise - the version is determined by me AT RANDOM from any RDPConf screenshot in this issue.

If it seems that the found version of `termsrv.dll` already matches another issue, then this one is closed as a duplicate to it.

# `termsrv.dll` version != Windows version!!!

**Comment by sashaqwert** [comment] 2022-11-12 08:36
> I don't have termsrv.dll

You can find this in `C:\Windows\System32` directory
