### ISSUE TITLE
19044.1706 [Not supported]

### ISSUE THREAD

**Issue by aa3000** [stascorp/rdpwrap#1960] opened 2022-08-15 08:18 UTC
![image](https://user-images.githubusercontent.com/488463/184600724-6cb6c089-a74b-44c0-a45c-092b1841f2a0.png)

**Comment by aa3000** [comment] 2022-08-15 08:22
[termsrv.dll.zip](https://github.com/stascorp/rdpwrap/files/9335981/termsrv.dll.zip)

**Comment by sashaqwert** [comment] 2022-08-15 09:06
Duplicate of https://github.com/stascorp/rdpwrap/issues/1823

**Closed as not planned by sashaqwert** 2022-08-15 09:06 UTC
Labels: duplicate

**Comment by aa3000** [comment] 2022-08-15 10:07
@sashaqwert Yes, thanks a lot
