### ISSUE TITLE
19041.1415 Not Supported

### ISSUE THREAD

**Issue by bestxiaoxiaoming-hm** [stascorp/rdpwrap#1688] opened 2022-01-18 10:02 UTC
[](url)
![image](https://user-images.githubusercontent.com/56991983/149915319-a3c13de6-6acc-4ba4-84db-4a3dda9d5ba4.png)

**Comment by sebaxakerhtc** [comment] 2022-01-18 10:13
Duplicate of https://github.com/stascorp/rdpwrap/issues/1630

**Closed as completed by sebaxakerhtc** 2022-01-18 10:13 UTC
