### ISSUE TITLE
fSingleSessionPerUser not work

### ISSUE THREAD

**Issue by mikeleblank** [stascorp/rdpwrap#2563] opened 2024-04-12 18:41 UTC
fSingleSessionPerUser is 1 not working last update.
Windows 10 22H2 19045.4291

**Comment by sashaqwert** [comment] 2024-04-12 19:08
What is your `termsrv.dll` version?

**Comment by mikeleblank** [comment] 2024-04-12 19:26
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/14962755/termsrv.zip)
10.0.19041.4239

**Comment by loyejaotdiqr47123** [comment] 2024-04-13 03:49
Duplicate of #2529

**Comment by sashaqwert** [comment] 2024-04-13 09:26
Duplicate of https://github.com/stascorp/rdpwrap/issues/2529

**Comment by sashaqwert** [comment] 2024-04-13 09:27
Please, ask this in correct thread (see link above)

**Closed as not planned by sashaqwert** 2024-04-13 09:26 UTC
Labels: duplicate

**Comment by sashaqwert** [comment] 2024-04-13 09:28
https://t.me/rdpwrap/68769
