### ISSUE TITLE
RDPWRAP Windows Pro Version 1909 Build 18363.959

### ISSUE THREAD

**Issue by Mextos** [stascorp/rdpwrap#1137] opened 2020-07-27 14:38 UTC
Hello everyone,

I installed a windows 10 Pro WM in a lab environment and i need to enable multiple connections on RDP.
Does anyone have the termserv,dll for this build?
Also RDP Wrapper 1.6.2 didn't work.

Thanks,

**Comment by GOOD-Stuff** [comment] 2020-07-27 15:25
Worked .ini settings you can find here #1127 

TL;DR: update **rdpwrap.ini**, exclude folder with *RDPWrap* from Windows Defender and execute in command line `RDPWinst.exe -i`

**Comment by zolymo** [comment] 2020-07-28 07:46
Hello, u have an ini file for Windows 1909 Build 18363.959
![borrar](https://user-images.githubusercontent.com/8655032/88634770-6eb37c00-d07c-11ea-897d-eeb2004898f5.png)

RDPWrap show Build 18362.836
![borrar2](https://user-images.githubusercontent.com/8655032/88634782-7410c680-d07c-11ea-9f52-7b2f4b0283ae.png)

Regards

**Comment by Mextos** [comment] 2020-07-28 16:04
Hi Zolymo and Good-Stuff,
Haven't had the time to try yet. But as soon as i got some free time i will try and let you know.
I do appreciate your help.

**Comment by johncharly26** [comment] 2020-07-29 16:21
ayudaa con este compilación

**Comment by ind3p3nd3nt** [comment] 2020-07-30 23:04
https://github.com/independentcod/RDPWraper
Instructions are included.
Have a nice day!

**Comment by wmonref** [comment] 2020-08-07 19:04
> 
> 
> https://github.com/independentcod/RDPWraper
> Instructions are included.
> Have a nice day!

Hi. I followed the instructions, but still am unable to get it working... 
The RDPWinst.exe -i command does not work when internet connection is off

**Comment by affinityv** [comment] 2020-08-08 14:32
Do a normal install WITH the Internet connected, make sure that Windows Defender (or any other AV or "security" product) has exclusions for the program files directory of RDP Wrapper.  Copy in this [INI](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini) file to that directory and do `RDPWInst -r`.

**Comment by sebaxakerhtc** [comment] 2022-06-20 11:39
Duplicate of https://github.com/stascorp/rdpwrap/issues/1083

**Closed as completed by sebaxakerhtc** 2022-06-20 11:39 UTC
