### ISSUE TITLE
What am i missing, i stuck on this screen

### ISSUE THREAD

**Issue by asdfgurke** [stascorp/rdpwrap#1877] opened 2022-06-01 18:34 UTC
![Download (1)](https://user-images.githubusercontent.com/106699857/171477434-fe2cfd4d-97b6-4485-ab00-85ff1580307c.png)

No clue what i am missing... maybe someone can help? :D

**Comment by sashaqwert** [comment] 2022-06-02 06:43
You need to [convert your Microsoft account to local account](https://www.techbout.com/switch-microsoft-account-to-local-windows-11-71385/).

One termsrv.dll version = one opened issue --> duplicate of https://github.com/stascorp/rdpwrap/issues/1843

**Comment by sebaxakerhtc** [comment] 2022-06-02 10:42
> duplicate of #1843

**Closed as completed by sebaxakerhtc** 2022-06-02 10:42 UTC

**Comment by asdfgurke** [comment] 2022-06-02 10:58
> You need to [convert your Microsoft account to local account](https://www.techbout.com/switch-microsoft-account-to-local-windows-11-71385/).
> 
> One termsrv.dll version = one opened issue --> duplicate of #1843

Thx :) worked for me
