### ISSUE TITLE
listener state not supported ver. 10.22000.653

### ISSUE THREAD

**Issue by 2549373113** [stascorp/rdpwrap#1864] opened 2022-05-20 12:46 UTC
![zL6Imt9rxC](https://user-images.githubusercontent.com/28761850/169530868-7c5d2bd3-ce06-4e51-ab5d-0be10f6cb19b.jpg)

**Comment by 2549373113** [comment] 2022-05-20 12:52
My OS is Window11 home basic version

**Comment by sashaqwert** [comment] 2022-05-21 14:16
try `net start termService` or reboot.

Duplicate of https://github.com/stascorp/rdpwrap/issues/1843

**Comment by sebaxakerhtc** [comment] 2022-05-23 15:22
> try `net start termService` or reboot.
> 
> Duplicate of #1843

**Closed as completed by sebaxakerhtc** 2022-05-23 15:22 UTC
