### ISSUE TITLE
Windows 10 1803 no RDP

### ISSUE THREAD

**Issue by Julien-nl** [stascorp/rdpwrap#469] opened 2018-05-05 20:35 UTC
Hi guys,
Windows 10 1803 installed the RDPWRAP unfortunately it not allowing multiple RDP versions.

1.6.2 RDP WRAP
Windows 10 1803 Pro.

thank you

**Comment by dmcdivitt** [comment] 2018-05-05 21:01
same issue

**Comment by binarymaster** [comment] 2018-05-05 21:13
Duplicate of #456.

**Closed by binarymaster** 2018-05-05 21:13 UTC
