### ISSUE TITLE
Listener state: Not listening, was working just yesterday

### ISSUE THREAD

**Issue by Laneark2** [stascorp/rdpwrap#2155] opened 2023-03-25 01:24 UTC
It was working yesterday, but isnt anymore, second day using it
Not listening but suppported
![image](https://user-images.githubusercontent.com/128872630/227676170-1dcd6d58-d5af-4a39-a77f-a1f7a3272c14.png)
Ive tried redownloading different .ini files, and completely deleted it and redownloaded it, anyone got another solution?

Im running windows 11 Pro N if that affects the situation.

Since the not listening issue its ive had zero audio on my pc too!

**Comment by sashaqwert** [comment] 2023-03-25 06:47
Duplicate of https://github.com/stascorp/rdpwrap/issues/2006

**Closed as not planned by sashaqwert** 2023-03-25 06:47 UTC
Labels: duplicate

**Comment by sashaqwert** [comment] 2023-03-25 06:49
One `termsrv.dll` version = one opened issue.

Try:
1. Download RDP Wrapper 1.6.2 and extract this to any directory.
2. Place `rdpwrap.ini` in the same directory.
3. Open CMD as administrator
4. Execute this commands
```
cd C:\path\to\directory\
rdpwinst -u -k
rdpwinst -i
```
5. Enjoy!

Original message: https://t.me/rdpwrap/49131
