### ISSUE TITLE
After KB4022720 ONLY 2 users can connect

### ISSUE THREAD

**Issue by mac1239** [stascorp/rdpwrap#271] opened 2017-06-29 18:52 UTC
Hi,

I have install the KB4022720 
and now in this server can connect only 2 users.
(Windows Server 2012 R2)

**Comment by binarymaster** [comment] 2017-06-29 19:52
KB4022720 contains `termsrv.dll` build `6.3.9600.18692` so closing as duplicate of #269.

**Closed by binarymaster** 2017-06-29 19:52 UTC
Labels: duplicate
