### ISSUE TITLE
10.0.19041.2075 - Windows 10 Pro 22H2 Only one session 

### ISSUE THREAD

**Issue by JayMonkey** [stascorp/rdpwrap#2063] opened 2022-12-07 17:25 UTC
Hi Guys,

Recently updated both my Windows 10 Pro systems to 22H2

RDP Wrapper installed ok and fully supported using updated INI file.
However on both systems no matter what I do I can only get one session running.

I've tried both Stas'M version 1.6.2 and sebaxakerhtc version 1.7.4.0 both versions install ok and diagnostics shows all is good with the updated ini file installed.

![Wrapper Debug](https://user-images.githubusercontent.com/5662056/206247162-ee6dd274-e882-4dd4-8f8c-5e4d24c28d7c.png)

As soon as I start a remote RDP session it logs the current local session out on the remote machine.
And behaves like the windows 10 default with no RDP Wrapper installed

As an experiment I also tried manually patching termsrv.dll with a hex editor and it too behaved the same allowing only one session at a time.  I've since restored termsrv.dll back to its original version and gone back to sebaxakerhtc version 1.7.4.0.

I see the same on both systems which are running Windows 10 pro - version 22H2 with all updates applied.
RDP Wrapper diagnostics report termsvr.dll as version 10.0.19041.2075.

I've attached a zip archive below of the unmodified termsvr.dll and a copy of the rdpwrap.ini file I'm using.

Any help would be much appreciated.

[Archive.zip](https://github.com/stascorp/rdpwrap/files/10178463/Archive.zip)

**Comment by sashaqwert** [comment] 2022-12-07 17:30
> RDP Wrapper installed ok and fully supported using updated INI file.
However on both systems no matter what I do I can only get one session running.

Try restart service, reboot
OR:
1. Download RDP Wrapper 1.6.2 and extract this to any directory.
2. Place `rdpwrap.ini` in the same directory.
3. Open CMD as administrator
4. Execute this commands
```
cd C:\path\to\directory\
rdpwinst -u -k
rdpwinst -i
```
5. Enjoy!

Original message: https://t.me/rdpwrap/49131

**Comment by sashaqwert** [comment] 2022-12-07 17:36
One `termsrv.dll` version = one opened issue --> this issue will closed as duplicate :)

**Comment by sashaqwert** [comment] 2022-12-07 17:36
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992

**Closed as not planned by sashaqwert** 2022-12-07 17:36 UTC
Labels: duplicate
