### ISSUE TITLE
rdpwrap.ini for 17763.475 - Win10 X64

### ISSUE THREAD

**Issue by ricardolazzari** [stascorp/rdpwrap#777] opened 2019-05-09 23:23 UTC
Hello,

After the 17763.475 update of Win10 X64 the RDP Wrapper has stopped working.
I used rdpwrap.ini for version 437 and it worked, but it is locking the terminals a lot.
Does anyone have the definitive fix for version 475?

**Comment by sebaxakerhtc** [comment] 2022-01-04 10:49
Duplicate of https://github.com/stascorp/rdpwrap/issues/720

**Closed as completed by sebaxakerhtc** 2022-01-04 10:49 UTC
