### ISSUE TITLE
Keyboard writing elsewhere

### ISSUE THREAD

**Issue by Zenida89** [stascorp/rdpwrap#178] opened 2016-11-04 10:20 UTC
It's a long time since my keyboard (or others) are typing elsewherre. I'm going to explain it better.
When me or someone else is typing on his keyboard, the text appears on other remote session.

Usually, it happens in Browser textboxes. For example, if i write something in the my Google textfield from Chrome or Firefox, I can't see any character, but maybe it is typing on another PC and not in my remote session.

It's really frustrating.

**Comment by binarymaster** [comment] 2016-11-04 14:04
Duplicate of #110.

**Closed by binarymaster** 2016-11-04 14:04 UTC
Labels: duplicate

**Comment by kbalandin** [comment] 2017-03-11 18:35
I know this issue is closed, but I can easily reproduce it, and it only happens with RDPWrap. One user (remoting) should open Microsoft Word. Another user (local) should open amazon/orders, and position the cursor in the "search orders" text box. When remoting user starts typing anything in Word, the text appears in the "search orders" text box. Reproducible every time. It could be as well Remote Desktop bug, not really sure.
