### ISSUE TITLE
Not working anymore since Windows Update KB4486563 (February 2019)

### ISSUE THREAD

**Issue by untroll** [stascorp/rdpwrap#663] opened 2019-02-13 14:51 UTC
The software is not working anymore since Windows Update of February 2019 (KB4486563) on Windows 7. I don't khow if the problem is present with other Windows version. Could you please fix ASAP?

Thank you!

**Comment by binarymaster** [comment] 2019-02-13 15:22
What is termsrv.dll build number? RDPConf sceenshot?

**Comment by davidboily** [comment] 2019-02-13 15:38
I have the same problem with Windows 10. The termsrv.dll file version says 10.0.17134.1. Here is the RDPConf screenshot. I have RDPWrap 1.6.2.
![rdpconf](https://user-images.githubusercontent.com/18334482/52723368-61cfc500-2f7b-11e9-83ce-a0b84f023692.PNG)

**Comment by binarymaster** [comment] 2019-02-13 15:44
@davidboily the question was directed to issue creator, please refrain from offtopic.

**Comment by jdodge99** [comment] 2019-02-13 15:50
I had same issue: termsrv.dll build:  6.1.7601.24326   modified date of 12/2/2018  11:06am
Installed with KB4486563 
RDPConf screenshot attached:
![image](https://user-images.githubusercontent.com/23003076/52724327-21714680-2f7d-11e9-999f-bc80e3f98301.png)
I saved a copy of the termsrv.dll before rolling back if that's helpful.

**Comment by CharlieF2** [comment] 2019-02-13 17:22
In my case - after the February 2019 Microsoft Update on Windows 7 Professional - same Listener State of Partially Supported - and 2 users can be logged in but not more than 2 - if a third attempts to log in then they are presented with a message that someone will be booted off.  If you proceed - one of the two is logged off and the 2 sessions continue to be supported.  So it appears that this update has put a cap on the number of open RDP sessions

**Comment by cstrife1** [comment] 2019-02-13 17:23
On Windows 2008 R2, same issue (max 2 users). Rolled back and it was fine after.

**Comment by CharlieF2** [comment] 2019-02-13 17:37
I uninstalled KB4483458 and KB4486563 and that seems to solve the problem

**Comment by CharlieF2** [comment] 2019-02-13 17:40
And - sorry - I uninstalled and re-installed RDP Wrap 1.62 after removing those two Microsoft Windows Updates - and that fixed the issue - the Listener State is now fully supported

**Comment by binarymaster** [comment] 2019-02-13 18:00
Duplicate of #646.

**Closed as completed by binarymaster** 2019-02-13 18:00 UTC
Labels: duplicate

**Comment by untroll** [comment] 2019-02-14 15:16
Is there a fix for termsrv.dll version 6.1.7601.24326?
