### ISSUE TITLE
Windows ver. 10.0.14393.5582 not working

### ISSUE THREAD

**Issue by Autestian** [stascorp/rdpwrap#2235] opened 2023-06-01 20:06 UTC
![Capture](https://github.com/stascorp/rdpwrap/assets/130386577/2c69dcfd-bfc1-44aa-8acd-1deff64d50d6)

**Comment by sebaxakerhtc** [comment] 2023-06-02 06:25
Duplicate of https://github.com/stascorp/rdpwrap/issues/2067

**Closed as completed by sebaxakerhtc** 2023-06-02 06:25 UTC
Labels: duplicate
