### ISSUE TITLE
I need a INI file for 10.0.22000.1 - WIN 11

### ISSUE THREAD

**Issue by marciifee** [stascorp/rdpwrap#1528] opened 2021-09-18 11:53 UTC
hi, I am really new in this topic and I can't run the RDP Wrapper on Win 11.
Maybe the rdpwrap.ini file is not compatible with win 11.

**Comment by marciifee** [comment] 2021-09-18 11:59
problem solved for win 11 pro with this:
https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini
thanks <3

**Comment by HKMV** [comment] 2021-09-18 16:17
非常感谢师傅,解决了我在win11家庭版22458.1000上不可用的问题.

**Comment by sebaxakerhtc** [comment] 2021-10-25 16:09
duplicate of https://github.com/stascorp/rdpwrap/issues/1455

**Closed as completed by sebaxakerhtc** 2021-10-25 16:10 UTC

**Comment by manish031985** [comment] 2022-02-16 06:19
not working in windows 11 pro version 10.0.22000.493
