### ISSUE TITLE
cannot have concurrent users

### ISSUE THREAD

**Issue by james28909** [stascorp/rdpwrap#1908] opened 2022-06-19 21:32 UTC
<img width="297" alt="rdp" src="https://user-images.githubusercontent.com/16311827/174501074-96e46d34-ed38-49d2-911a-7236d4e0bc2b.png">
<img width="493" alt="rdp1" src="https://user-images.githubusercontent.com/16311827/174501325-b1b84bcb-125e-412c-a63b-970e282af3c7.png">

it says supported but i still cannot log in to the same machine remotely as a different user. says the number of connections is limited. please advise and thanks in advance

**Comment by james28909** [comment] 2022-06-19 21:47
please mark as solved/closed. i had made some changes to group policy through gpedit.msc yesterday before installing rdpwrap because this page said that it could work: [https://devsjournal.com/how-to-enable-rdp-for-multiple-users-on-windows-11.html](https://devsjournal.com/how-to-enable-rdp-for-multiple-users-on-windows-11.html).

but ofcourse it didnt work and also seem to have messed with rdpwrap somehow. reverting the changes made in gpedit.msc looks like it fixed it (or maybe rebooting my pc after changing gpedit setting fix it, who knows!). i can log into other users using the rdpcheck.exe. sorry for the trouble

**Comment by sashaqwert** [comment] 2022-06-20 06:06
Duplicate of https://github.com/stascorp/rdpwrap/issues/1871

Try reboot or this commands as Administrator
```
net stop termService
net start termService
```

**Comment by sebaxakerhtc** [comment] 2022-06-20 09:24
Applicable to https://github.com/stascorp/rdpwrap/issues/1871

**Closed as completed by sebaxakerhtc** 2022-06-20 09:24 UTC
