### ISSUE TITLE
10.0.20348.502 help not working

### ISSUE THREAD

**Issue by HYDCURSED** [stascorp/rdpwrap#2141] opened 2023-03-15 15:34 UTC
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/10981792/termsrv.zip)

![изображение](https://user-images.githubusercontent.com/86727612/225360833-813a74cb-f1aa-43e5-b687-5b7470aaaba2.png)

![изображение](https://user-images.githubusercontent.com/86727612/225360993-1cf24f95-7594-4f83-a731-73e47c6a0931.png)

**Comment by sashaqwert** [comment] 2023-03-15 16:22
Duplicate of https://github.com/stascorp/rdpwrap/issues/1704

**Closed as not planned by sashaqwert** 2023-03-15 16:22 UTC
Labels: duplicate
