### ISSUE TITLE
Windows 10 rdp wrapper 10.0.19041.3271 fully supported but not working

### ISSUE THREAD

**Issue by NaffeeYalta** [stascorp/rdpwrap#2315] opened 2023-08-21 07:37 UTC
help please)

![Безымянный](https://github.com/stascorp/rdpwrap/assets/142481828/bfe2e493-6fef-4190-bf9f-deb5d2748f84)

**Comment by sashaqwert** [comment] 2023-08-21 08:54
One `termsrv.dll` version = ONE opened issue!

**Comment by sashaqwert** [comment] 2023-08-21 08:55
Duplicate of https://github.com/stascorp/rdpwrap/issues/2289

**Comment by sashaqwert** [comment] 2023-08-21 08:56
Try:
1. Download RDP Wrapper 1.6.2 and extract this to any directory.
2. Place `rdpwrap.ini` in the same directory.
3. Open CMD as administrator
4. Execute this commands
```
cd C:\path\to\directory\
rdpwinst -u -k
rdpwinst -i
```
5. Enjoy!

Original message: https://t.me/rdpwrap/49131

**Closed as not planned by sashaqwert** 2023-08-21 08:55 UTC
Labels: duplicate

**Comment by NaffeeYalta** [comment] 2023-08-21 09:28
> 

![image](https://github.com/stascorp/rdpwrap/assets/142481828/71206a7c-a880-43b5-96ce-7691c9507b38)
now the termservice won't start

**Comment by alalid** [comment] 2023-10-08 10:07
Can you help me with this version?
rdp wrapper 10.0.190241.3271

**Comment by sashaqwert** [comment] 2023-10-08 10:31
@alalid 

> 10.0.190**2**41.3271

Is your version correct???

You also can ask in Telegram chat https://t.me/rdpwrap

<details>
<summary>lol</summary>

![изображение](https://github.com/stascorp/rdpwrap/assets/24974508/25b43c9c-bc69-45e3-a1a5-d7cec70ab748)


</details>
