### ISSUE TITLE
Please, support Win 10 19045.2965

### ISSUE THREAD

**Issue by etonocolia** [stascorp/rdpwrap#2197] opened 2023-05-10 16:30 UTC
The RDPWrapper bad

**Comment by etonocolia** [comment] 2023-05-10 16:44
Help me, please
Win 22H2 
19045.2965

I need .ini

Thanks

**Comment by sashaqwert** [comment] 2023-05-10 17:30
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by jpewpew** [comment] 2023-05-10 20:10
Jumping in because i have the same issue

![image](https://github.com/stascorp/rdpwrap/assets/133163478/973e76bf-9412-4e43-9087-35f54bbec898)

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/11445615/termsrv.zip)

**Comment by sashaqwert** [comment] 2023-05-11 08:04
Thanks! Solution in my next comment

**Comment by sashaqwert** [comment] 2023-05-11 08:04
Duplicate of https://github.com/stascorp/rdpwrap/issues/2180

**Closed as not planned by sashaqwert** 2023-05-11 08:04 UTC
Labels: duplicate

**Comment by etonocolia** [comment] 2023-05-11 15:05
![Captura](https://github.com/stascorp/rdpwrap/assets/8352283/ff9a8900-1b6c-4c7e-b7df-c6fd015c95f3)

**Comment by etonocolia** [comment] 2023-05-11 15:06
![image](https://github.com/stascorp/rdpwrap/assets/8352283/6c0509b5-3153-4186-9e50-dd3937bede62)

**Comment by sashaqwert** [comment] 2023-05-11 17:41
@etonocolia 

Are you replaced rdpwrap.ini file from https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

**Comment by kelitonnunes** [comment] 2023-05-13 18:00
> @etonocolia
> 
> Você substituiu o arquivo rdpwrap.ini de https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

Parabéns resolveu o caso aqui.

**Comment by etonocolia** [comment] 2023-05-13 18:09
Yes, worked

Many thanks

👍👍👍

**Comment by susl16c** [comment] 2025-10-15 07:09
19045.6456 is there no solution for such an assembly?
