### ISSUE TITLE
10.0.19041.1387   

### ISSUE THREAD

**Issue by hazywx** [stascorp/rdpwrap#1740] opened 2022-02-21 15:26 UTC

**Comment by hazywx** [comment] 2022-02-21 15:26
![QQ截图20220221230757](https://user-images.githubusercontent.com/100095010/154984549-45e79295-15f2-490e-8d19-cff88405996c.png)

**Comment by hazywx** [comment] 2022-02-21 15:26
![QQ截图20220221230613](https://user-images.githubusercontent.com/100095010/154984593-3899b4de-1471-451b-b8aa-69caedcf19ba.png)
[https://github.com/sebaxakerhtc/rdpwrap.ini/blob/281891c82fc888b12a697b8bb99f5b1b80435ece/autogenerated/10.0.19041.1387-autogenerated_x64.ini](url)   copy   rdpwrap    autoupdate  Flash back

**Comment by hazywx** [comment] 2022-02-21 15:28
The number of connections to this computer is limited and all connections are in use right now. Try connecing later or contact your system administrato

**Comment by sashaqwert** [comment] 2022-02-21 15:56
Duplicate of https://github.com/stascorp/rdpwrap/issues/1630
One issue = one `termsrv.dll` version

**Closed as completed** 2022-02-21 20:09 UTC
