### ISSUE TITLE
10.0.19044.3086

### ISSUE THREAD

**Issue by ghost** [stascorp/rdpwrap#2311] opened 2023-08-18 20:39 UTC
I've attached the file
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/12383863/termsrv.zip)

**Comment by sashaqwert** [comment] 2023-08-19 08:26
Duplicate of https://github.com/stascorp/rdpwrap/issues/2180

**Closed as not planned by sashaqwert** 2023-08-19 08:26 UTC
Labels: duplicate
