### ISSUE TITLE
Printer redirection

### ISSUE THREAD

**Issue by wormsloe** [stascorp/rdpwrap#487] opened 2018-05-18 19:46 UTC
After applying the recent fix, we can access multiple sessions remotely, but we cannot get printer redirection to work. Any ideas?

**Comment by burluckoff** [comment] 2018-05-21 01:40
Add printer driver on server.
1. Запускаем gpedit.msc, откроется "редактор локальной групповой политики" 
2. заходим на "Административные шаблоны" 
3. Далее "Принтеры" 
4. Находим "выполнить драйверы принтеров в изолированных процессах" и включаем 
5. Там же находим "переопределить параметр совместимости выполнения драйвера печати, назначенный драйвером печати" и тоже включаем. 
6. "Конфигурация компьютера -> Административные шаблоны -> Компоненты Windows -> Службы удаленных рабочих столов -> Узел сеансов удаленных рабочих столов -> Перенаправление принтеров" 
Параметр Use Terminal Services Easy Print printer driver first (Использовать в первую очередь драйвер принтера Easy Print удаленного рабочего стола) переводим в Disable.

**Comment by binarymaster** [comment] 2018-05-21 09:53
Duplicate of #270.

**Closed by binarymaster** 2018-05-21 09:53 UTC

**Comment by SeRom7640** [comment] 2018-06-05 15:02
it's not duplicate, it appears with the 1803 version of Windows 10, see my #504

**Comment by bulgaru** [comment] 2019-02-11 16:02
Hey, guys!

I've spent a day trying to figure out how come my old Windows 10 Pro instances had printer forwarding working properly, while the new Windows 10 Enterprise instances were not. It turns out - there was some version of the wrapper that worked like a charm for 1803 version. I am not technically skilled to understand what is the difference between the latest version and the one that i am using, but i hope it'll help some of you out there. There are 3 files ([patched.zip](https://github.com/stascorp/rdpwrap/files/2851823/patched.zip)):

1. termsrv.dll - goes into system32 folder
2. rdpwrap.dll - goes into the wrapper's Program Files folder
3. rdpwrap.ini - goes into the wrapper's Program Files folder

**Keep in mind!** You need to update all files at once, otherwise you risk locking yourself out of the windows and you'll need to boot into Safe Mode to correct it. The best approach is, if you have a VM with windows running - get console access (not RDP) to edit all the files (otherwise you'll get the complaint that some of these files are in use).

The installation algorithm for installation:

1. Backup your original termsrv.dll (system32 folder, by changing ownership and granting full rights) and rdpwrap.dll & rdpwrap.dll (Program Files inside RDP Wrapper folder)
2. Install the latest RDPWrap
3. Test it, so that you are certain that it works
4. Login via console and substitute (delete and copy the ones from the archive) all 3 files [patched.zip](https://github.com/stascorp/rdpwrap/files/2851823/patched.zip)

I encourage the maintainers to have a look at these files in order to understand why the latest version does not work, while this one does.

Best of luck and thank you to the creators of this awesome tool!
