### ISSUE TITLE
10.0.19041.2075 X64 No Login Form

### ISSUE THREAD

**Issue by damon-ho** [stascorp/rdpwrap#2147] opened 2023-03-18 01:39 UTC
![Snipaste_2023-03-18_09-30-56](https://user-images.githubusercontent.com/67131159/226076290-81c2fd10-4036-48a8-b10d-4b4c6b8c4d36.png)
![Snipaste_2023-03-18_09-29-51](https://user-images.githubusercontent.com/67131159/226076334-738ba7f7-3e97-46c3-ac13-8c0435296d44.png)

RDP config OK, But no login form when connecting. Need help to check. Thanks.

**Comment by sashaqwert** [comment] 2023-03-18 04:43
You need to [convert your Microsoft account to a local account](https://support.microsoft.com/en-us/windows/switch-your-windows-10-device-to-a-local-account-eb7e78a9-88ee-9bc3-8f06-831b56e339fd).

**Comment by sashaqwert** [comment] 2023-03-18 04:44
One `termsrv.dll` version = one opened issue!
This issue will closed as duplicate.

**Comment by sashaqwert** [comment] 2023-03-18 04:46
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992

**Closed as not planned by sashaqwert** 2023-03-18 04:46 UTC
Labels: duplicate
