### ISSUE TITLE
Issue with with windows build number 19044.1826

### ISSUE THREAD

**Issue by LeeW2022** [stascorp/rdpwrap#1934] opened 2022-07-19 12:12 UTC
Hi frist of all say thank you for all your hard work. 

I have an Issue with with windows build number 19044.1826 21H2 win pro only allow one conection per time. Was working fine before last windows update

[termsrv (1).LOG](https://github.com/stascorp/rdpwrap/files/9140913/termsrv.1.LOG) Change this file to *.Log to be able to upload it here. 

![RDP Wrapper configuration](https://user-images.githubusercontent.com/109596403/179745622-67ab485c-f0ef-4da4-9e16-2cb0478949b9.jpg)

Thanks in advance

**Comment by sashaqwert** [comment] 2022-07-19 14:38
Try:
1. CMD as Administrator
2. `net stop termService`
3. `net start termService`

Or reboot.

After this check again.

If this not work try modded version by sebaxakerhtc: https://github.com/sebaxakerhtc/rdpwrap/releases
DISABLE ANTI-VIRUS BEFORE INSTALLING this mod! (You can turn it on after installing and adding exclusion directory `C:\Program Files\RDP Wrapper`)

**Comment by sashaqwert** [comment] 2022-07-19 14:45
This issue will be closed because for one version `termsrv.dll` there is exactly one open issue.

Duplicate of https://github.com/stascorp/rdpwrap/issues/1881

-----------------

The problem that is described here is common and does not apply to many versions of termsrv. Read more in https://github.com/stascorp/rdpwrap/issues/1883 --> Note

**Closed as completed by sashaqwert** 2022-07-19 14:45 UTC
