### ISSUE TITLE
10.0.19043.1766  Not supported

### ISSUE THREAD

**Issue by shaozhuyong** [stascorp/rdpwrap#1911] opened 2022-06-22 03:29 UTC
10.0.19043.1766  Not supported 

![image](https://user-images.githubusercontent.com/20103939/174937576-c588c595-d4ef-4bf1-ae7f-d3d25cbe85b1.png)

**Comment by sashaqwert** [comment] 2022-06-22 07:23
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881

**Comment by sebaxakerhtc** [comment] 2022-06-22 13:51
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881

**Closed as completed by sebaxakerhtc** 2022-06-22 13:51 UTC
