### ISSUE TITLE
RDP Wrapper limiting connections on 10.0.19041.2075

### ISSUE THREAD

**Issue by nottychap2002** [stascorp/rdpwrap#1998] opened 2022-09-24 13:52 UTC
Hi,

I am facing issues with the number of connections allowed after the recent update. Please find below attached screenshots of the existing configuration.

![image](https://user-images.githubusercontent.com/114296985/192101477-8649b047-fca8-4f3d-8191-322584002e1c.png)
![image](https://user-images.githubusercontent.com/114296985/192101514-e9c52ada-d150-429a-8416-294ec8a57216.png)
![image](https://user-images.githubusercontent.com/114296985/192101593-e804988d-7fcb-4b40-911e-245d262d3533.png)

**Comment by sashaqwert** [comment] 2022-09-24 14:32
One `termsrv.dll` version = one opened issue --> this issue will be closed...........

**Comment by sashaqwert** [comment] 2022-09-24 14:32
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992

**Closed as not planned by sashaqwert** 2022-09-24 14:32 UTC

**Comment by sashaqwert** [comment] 2022-09-24 14:39
Try:
1. Download RDP Wrapper 1.6.2 and extract this to any directory.
2. Place `rdpwrap.ini` in the same directory.
3. Open CMD as administrator
4. Execute this commands
```
cd C;\path\to\directory\
rdpwinst -u -k
rdpwinst -i
```
5. Enjoy!

Original message: https://t.me/rdpwrap/49131

**Comment by lakysir** [comment] 2022-10-14 02:50
Thanks, it't the best solution for this version issue.

**Comment by jansonleeljs** [comment] 2022-12-15 08:32
Thank you for providing such a great route to solve the bug!
