### ISSUE TITLE
Virusscanner disables RDPConf.exe

### ISSUE THREAD

**Issue by andrePKI** [stascorp/rdpwrap#598] opened 2018-11-13 18:48 UTC
This download may trigger your virusscanner: 
[VirusTotal](https://www.virustotal.com/#/file/4f9ea0c2ef2e6df72c42e47abcf591dde2f59716a2bc48c353697261c1462e53/detection). I have McAfee and it quarantines rdpconf.exe RDPwrapper does work, however.

**Comment by binarymaster** [comment] 2018-11-13 19:44
Duplicate of #277.

**Closed by binarymaster** 2018-11-13 19:44 UTC
