### ISSUE TITLE
10.0.22631.2861 not support

### ISSUE THREAD

**Issue by hony-tom** [stascorp/rdpwrap#2602] opened 2024-05-04 00:40 UTC

**Comment by loyejaotdiqr47123** [comment] 2024-05-04 02:47
@hony-tom Please uplod termsrv.dll

**Comment by hony-tom** [comment] 2024-05-04 03:34
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/15206508/termsrv.zip)

**Comment by loyejaotdiqr47123** [comment] 2024-05-04 03:43
Duplicate of #2443

**Comment by sashaqwert** [comment] 2024-05-05 10:14
Duplicate of https://github.com/stascorp/rdpwrap/issues/2443

**Closed as not planned by sashaqwert** 2024-05-05 10:14 UTC
Labels: duplicate
