### ISSUE TITLE
All status green but cannot connect, it says the number of connection is limited

### ISSUE THREAD

**Issue by ryannining** [stascorp/rdpwrap#2540] opened 2024-04-03 02:37 UTC
![image](https://github.com/stascorp/rdpwrap/assets/11457832/75d7421c-2a85-4181-b0d6-d41b1bcb7c6e)

**Comment by sashaqwert** [comment] 2024-04-06 16:36
Please ask this question in the topic of your version of termsrv.dll, because there may be several problems, including incorrect offsets (and they will only be suggested there).

Universal solutions could be restarting the service, rebooting or reinstalling RDP Wrapper.

**Comment by sashaqwert** [comment] 2024-04-06 16:36
Duplicate of https://github.com/stascorp/rdpwrap/issues/2469

**Closed as not planned by sashaqwert** 2024-04-06 16:36 UTC
