### ISSUE TITLE
Windows 10 18362.449 is not working

### ISSUE THREAD

**Issue by thorstencoordes** [stascorp/rdpwrap#918] opened 2019-10-30 08:15 UTC
I need a fix for the current Windows 10 release 18362.449.

**Comment by SobieskiCodes** [comment] 2019-10-30 11:45
Try https://github.com/stascorp/rdpwrap/issues/906 I don't have a machine running .449, but looking at the notes nothing changed with it.
UNINSTALL YOUR CURRENT RDPWRAP AND REBOOT BEFORE ATTEMPTING. 
If it works make sure you disable windows updates. This project is long past dead.

**Comment by flydvorkin** [comment] 2019-10-31 15:11
18362.449 - working.
Check ini file from: https://github.com/stascorp/rdpwrap/issues/902
by @Techgoduk post.

If no C:\windows\system32\rfxvmt.dll file, then install
%windir%\servicing\Packages\Microsoft-Windows-Virtualization-RemoteFX-User-Mode-Transport-Package~*.mum
package by dism

**Comment by thorstencoordes** [comment] 2019-10-31 17:54
It is working now. I have not taken the correct path for the ini file. I deleted the dead installation from previous attemps to not getting into this trouble again. Sorry for bothering.

**Comment by sebaxakerhtc** [comment] 2022-06-20 10:15
Duplicate of https://github.com/stascorp/rdpwrap/issues/871

**Closed as completed by sebaxakerhtc** 2022-06-20 10:15 UTC
