### ISSUE TITLE
Not able to RDP into computer after installing RDP Wrapper.

### ISSUE THREAD

**Issue by IzPhilip** [stascorp/rdpwrap#1108] opened 2020-06-27 04:46 UTC
I was able to RDP into my computer previously but it did not allow multiple servers at the same time, so I installed this RDP Wrapper.
The RDPConf.exe shows everything is working.
![image](https://user-images.githubusercontent.com/9902265/85914776-2b07f100-b7f6-11ea-9ad1-ab947aecd02e.png)

Running RDPCheck.exe works too.

However when I try to connect using the remote desktop connection program, it gives me the error that I am unable to connect to the computer. It was connecting fine before I installed RDP Wrapper. And I double checked the IP is correct. The ip is pingable too.
![image](https://user-images.githubusercontent.com/9902265/85914796-74f0d700-b7f6-11ea-9962-667379f0c77a.png)

Does anyone have any ideas?

**Comment by edgd1er** [comment] 2020-06-27 06:32
Default port for rdp is 3389, 51451 is defined here. Did you set it in  the client also?

You need to either restore the default one or set the defined one in the client?

**Comment by sebaxakerhtc** [comment] 2022-06-20 11:04
Duplicate of https://github.com/stascorp/rdpwrap/issues/1083

**Closed as completed by sebaxakerhtc** 2022-06-20 11:04 UTC

**Comment by arash927** [comment] 2025-11-11 16:54
i have the same proplem

**Comment by arash927** [comment] 2025-11-11 16:54
i tested everything
