### ISSUE TITLE
Windows 11 10.0.22621.2134 not supported.

### ISSUE THREAD

**Issue by dayspring-dev** [stascorp/rdpwrap#2305] opened 2023-08-09 16:08 UTC
Please add offsets for Windows 11 10.0.22621.2134
Thank you very much for your time.

Windows 11 version 22H2, all editions
Latest windows 11 update - August 8, 2023—KB5029263 (OS Build 22621.2134)
https://support.microsoft.com/en-us/topic/august-8-2023-kb5029263-os-build-22621-2134-f8d4d3de-47c1-40e1-a2e6-97c2770ee2e8

**Comment by sashaqwert** [comment] 2023-08-10 14:31
> Please add offsets for Windows 11 10.0.22621.2134

RDPConf screenshot, please!

**Comment by sashaqwert** [comment] 2023-08-11 11:38
Duplicate of https://github.com/stascorp/rdpwrap/issues/2290

**Closed as not planned by sashaqwert** 2023-08-11 11:38 UTC
Labels: duplicate
