### ISSUE TITLE
Windows Version 10.0.19041.1348 Not Supported?

### ISSUE THREAD

**Issue by Errorbot1122** [stascorp/rdpwrap#1660] opened 2021-12-15 15:07 UTC
![image](https://user-images.githubusercontent.com/65428515/146211472-6c67f141-8c02-49b3-be28-30d2ee0b8ab3.png)

**Comment by JhonRen** [comment] 2021-12-16 02:00
update the file rdpwrap.ini


[10.0.19041.1348-SLInit]
bServerSku.x86        =D1A08
bRemoteConnAllowed.x86=D1A1C
bFUSEnabled.x86       =D1A28
bAppServerAllowed.x86 =D1A14
bMultimonAllowed.x86  =D1A20
lMaxUserSessions.x86  =D1A0C
ulMaxDebugSessions.x86=D1A24
bInitialized.x86      =D1A04

bServerSku.x64        =10710C
bRemoteConnAllowed.x64=107120
bFUSEnabled.x64       =10712C
bAppServerAllowed.x64 =107118
bMultimonAllowed.x64  =107124
lMaxUserSessions.x64  =107110
ulMaxDebugSessions.x64=107128
bInitialized.x64      =107108

[10.0.19041.1348]
LocalOnlyPatch.x86    =1
LocalOnlyOffset.x86   =B64A9
LocalOnlyCode.x86     =jmpshort
SingleUserPatch.x86   =1
SingleUserOffset.x86  =3BDE7
SingleUserCode.x86    =Zero
DefPolicyPatch.x86    =1
DefPolicyOffset.x86   =3E899
DefPolicyCode.x86     =CDefPolicy_Query_eax_ecx
SLInitHook.x86        =1
SLInitOffset.x86      =68578
SLInitFunc.x86        =New_CSLQuery_Initialize

LocalOnlyPatch.x64    =1
LocalOnlyOffset.x64   =89AC1
LocalOnlyCode.x64     =jmpshort
SingleUserPatch.x64   =1
SingleUserOffset.x64  =0D1E2
SingleUserCode.x64    =Zero
DefPolicyPatch.x64    =1
DefPolicyOffset.x64   =190D5
DefPolicyCode.x64     =CDefPolicy_Query_eax_rcx
SLInitHook.x64        =1
SLInitOffset.x64      =1E6AC
SLInitFunc.x64        =New_CSLQuery_Initialize

**Comment by Errorbot1122** [comment] 2021-12-16 02:27
how do I even do that in the first place @JhonRen

**Comment by sebaxakerhtc** [comment] 2021-12-17 15:44
Duplicate of https://github.com/stascorp/rdpwrap/issues/1595

**Closed as completed by sebaxakerhtc** 2021-12-17 15:44 UTC

**Comment by Errorbot1122** [comment] 2021-12-17 16:47
@sebaxakerhtc What do I do then

**Comment by sebaxakerhtc** [comment] 2021-12-17 16:56
> @sebaxakerhtc What do I do then

Variant No 1: [Modded rdpwrapper](https://github.com/sebaxakerhtc/rdpwrap/releases) 
Variant No 2: [Autoupdate](https://github.com/asmtron/rdpwrap)

**Comment by Errorbot1122** [comment] 2021-12-17 17:42
Should I choose NO. 1 or NO. 2

**Comment by sebaxakerhtc** [comment] 2021-12-17 18:05
> Should I choose NO. 1 or NO. 2

You should to choose.
You can try both variants and then...
1st is my modded version of rdpwrapper, uses my ini only.
2nd checks multi sources of ini and uses original rdpwrapper

**Comment by Errorbot1122** [comment] 2021-12-17 18:12
okay thank you :)
