### ISSUE TITLE
Windows 10 10.0.19041.789 not support

### ISSUE THREAD

**Issue by chenyuxiangg** [stascorp/rdpwrap#1797] opened 2022-03-30 12:31 UTC
Listener state: Not listening Not supported
Please add support for
Windows 10 10.0.19041.789

**Comment by sebaxakerhtc** [comment] 2022-03-30 13:04
https://github.com/sebaxakerhtc/rdpwrap.ini/blob/8f4d2935fb544bce01b2c4ad32a9b8ecf8e40c68/rdpwrap.ini#L4616

**Comment by sebaxakerhtc** [comment] 2022-03-30 13:09
Duplicate of https://github.com/stascorp/rdpwrap/issues/1317

**Closed as completed by sebaxakerhtc** 2022-03-30 13:09 UTC
