### ISSUE TITLE
Add support for build 10.0.17763.292

### ISSUE THREAD

**Issue by Xavii1205** [stascorp/rdpwrap#655] opened 2019-02-06 17:16 UTC
Already do all the established with the code but still the remote error error Simultaneous, Do you have any changes in the windows registers, or in the ini, to activate this option ?, I am very aware since it handles 3 users to time and your app has been a great help.

![image](https://user-images.githubusercontent.com/47395037/52360009-02b50200-2a09-11e9-8d4c-14a2a478dedc.png)

Thnks for your help.

**Comment by PotatoDestroyer** [comment] 2019-02-06 17:33
am getting the same error, need a fix

**Comment by miglaranjeira** [comment] 2019-02-06 21:51
I used this 
https://troubleshooter.xyz/wiki/fix-the-number-of-connections-to-this-computer-is-limited/
and now works fine

**Comment by ultragithub** [comment] 2019-02-06 22:41
same problem here and the above fix didn't work

**Comment by SIMBaIrk** [comment] 2019-02-07 07:05
need wrap for 10.0.17763.163

**Comment by Xavii1205** [comment] 2019-02-07 13:22
Good day for everyone, 

I tell you that my solution was to uninstall the updates generated by the windows update, to date and restart the program again; if you have unistall antivirus, to be able to use the tool, I work and I am operative, also make some changes in the registry cleaning with CClean, or if you are cautious re install a record that I had saved.

This worked, I hope it works for you.

- uninstall updates

Win + r> Control> programs and features> view instantaneous updates (select the latest updates and uninstall them).

Disable automatic updates of Windows Update.

services.msc> windows update> disable.

Be it working for them.

regards

![image](https://user-images.githubusercontent.com/47395037/52414102-61ce5180-2ab1-11e9-85c9-636d5e6f9b85.png)

![image](https://user-images.githubusercontent.com/47395037/52414132-77437b80-2ab1-11e9-8fe1-11c456074b82.png)

**Comment by Xavii1205** [comment] 2019-02-07 13:25
> Utilicé este 
> https://troubleshooter.xyz/wiki/fix-the-number-of-connections-to-this-computer-is-limited/
> y ahora funciona bien

Thanks for your answer.

your solution did not work but I appreciate the information.

**Comment by Xavii1205** [comment] 2019-02-07 14:57
I forgot to add, to make some changes in the windows registry so that they could solve the flaw also by the registry of users. I leave the route with the change.

![whatsapp image 2019-02-07 at 9 46 07 am](https://user-images.githubusercontent.com/47395037/52419790-cfcd4580-2abe-11e9-90aa-4195b420a2b9.jpeg)

**Comment by binarymaster** [comment] 2019-02-07 15:22
Duplicate of #645.

**Closed as completed by binarymaster** 2019-02-07 15:22 UTC
Labels: duplicate

**Comment by ultragithub** [comment] 2019-02-07 23:04
this did not fix the problem for me
