### ISSUE TITLE
rdp 21h2 os build 19044.2006 not working need fix

### ISSUE THREAD

**Issue by prestonj00** [stascorp/rdpwrap#1986] opened 2022-09-16 16:49 UTC
![image](https://user-images.githubusercontent.com/113713474/190689259-083f3060-c0c1-4778-8d79-efcff967a035.png)

**Comment by sashaqwert** [comment] 2022-09-17 07:06
Duplicate of https://github.com/stascorp/rdpwrap/issues/1968

**Closed as not planned by sashaqwert** 2022-09-17 07:06 UTC
Labels: duplicate
