### ISSUE TITLE
There are 19045.3324 rdpwrap.ini files ？

### ISSUE THREAD

**Issue by gzlj007** [stascorp/rdpwrap#2314] opened 2023-08-21 01:57 UTC
There are 19045.3324 rdpwrap.ini files ？

**Comment by sashaqwert** [comment] 2023-08-21 08:53
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by sebaxakerhtc** [comment] 2023-08-21 10:01
@sashaqwert 
https://github.com/sebaxakerhtc/rdpwrap.ini/issues/278

**Comment by sebaxakerhtc** [comment] 2023-08-21 10:02
Duplicate of https://github.com/stascorp/rdpwrap/issues/2257

**Closed as not planned by sebaxakerhtc** 2023-08-21 10:02 UTC
Labels: duplicate

**Comment by gzlj007** [comment] 2023-08-21 10:23
> Duplicate of #2257

Thank you very much. I couldn't copy the ini link you provided directly. I searched for the version you provided in the project and reinstalled it. Thank you again

**Comment by gzlj007** [comment] 2023-08-21 10:24
> Duplicate of #2257

How can I determine which version of ini to use based on the DLL?
