### ISSUE TITLE
Listener State: Not Listening  and Not Supported in Windows 10 Home 22H2 19045

### ISSUE THREAD

**Issue by sultanmansoor40** [stascorp/rdpwrap#2371] opened 2023-10-15 10:51 UTC
After Updating Windows RDP is not working and showing the below error:
![image](https://github.com/stascorp/rdpwrap/assets/48856235/faa45dd3-ed79-4a06-ae61-4c59d07bb423)

Also While Running RDPCheck.exe I receive the following error:
![image](https://github.com/stascorp/rdpwrap/assets/48856235/ec35b2aa-7e22-403a-999f-b4e118289ee9)

Tried All kinds of solutions suggested in the issues list:
- Deactivated the Windows Defender
- uninstall then install the rdpwrap
- made changes to rdpwrap.ini
- running  RDPWInst.exe
- updated rfxvmt.dll in both System32 and SysWOW64 Folder
- Created autoupdate.bat and ran it
- restarting the windows after I made the above changes
- Changed the Port

Nothing has worked.
Kindly suggest a solution or contact me at sultanmansoor40@gmail.com

**Comment by sashaqwert** [comment] 2023-10-16 07:12
Duplicate of https://github.com/stascorp/rdpwrap/issues/2359

**Closed as not planned by sashaqwert** 2023-10-16 07:12 UTC
Labels: duplicate

**Comment by sashaqwert** [comment] 2023-10-16 07:16
> * made changes to rdpwrap.ini

`C:\Program Files\RDP Wrapper\rdpwrap.ini`?



> * running  RDPWInst.exe
> 
> * updated rfxvmt.dll in both System32 and SysWOW64 Folder
> 
> * Created autoupdate.bat and ran it

What??? Describe...

https://t.me/rdpwrap
