### ISSUE TITLE
README: outdated link to mydigitallife.net

### ISSUE THREAD

**Issue by moritztim** [stascorp/rdpwrap#2410] opened 2023-11-16 19:28 UTC
These links work:
https://forums.mydigitallife.net/threads/windows-product-policy-editor.39411/
https://forums.mydigitallife.net/threads/39411

**Comment by sashaqwert** [comment] 2023-12-02 09:12
Duplicate of https://github.com/stascorp/rdpwrap/issues/2083

**Closed as not planned by sashaqwert** 2023-12-02 09:12 UTC
Labels: duplicate
