### ISSUE TITLE
[Request] Version 10.0.19041.207

### ISSUE THREAD

**Issue by ahkui** [stascorp/rdpwrap#1070] opened 2020-04-29 17:48 UTC
![Screen Shot 2020-04-30 at 1 47 46 AM](https://user-images.githubusercontent.com/14049597/80628870-9a769400-8a84-11ea-86c7-c795f7db14eb.png)

**Comment by ahkui** [comment] 2020-04-29 17:49
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/4553394/termsrv.zip)

**Comment by ahkui** [comment] 2020-04-29 17:50
Same as #1067

**Comment by sebaxakerhtc** [comment] 2022-06-20 10:33
Duplicate of Duplicate of https://github.com/stascorp/rdpwrap/issues/1004

**Closed as completed by sebaxakerhtc** 2022-06-20 10:33 UTC
