### ISSUE TITLE
version:10.0.19044.1320

### ISSUE THREAD

**Issue by BlitheLe** [stascorp/rdpwrap#1692] opened 2022-01-20 08:54 UTC
How to edit the rdpwrap.ini to make RDPConf available?

**Comment by sashaqwert** [comment] 2022-01-20 10:01
Please, attach rour RDPConf screenshot.
You can get this in [RDPWrap ZIP (release 1.6.2)](https://github.com/stascorp/rdpwrap/releases/download/v1.6.2/RDPWrap-v1.6.2.zip) --> RDPConf.exe

**Comment by sebaxakerhtc** [comment] 2022-01-20 12:34
Duplicate of https://github.com/stascorp/rdpwrap/issues/1574

**Closed as completed by sebaxakerhtc** 2022-01-20 12:34 UTC
