### ISSUE TITLE
Need help with redirecting printers

### ISSUE THREAD

**Issue by Kanakrinolaas** [stascorp/rdpwrap#2047] opened 2022-11-15 14:26 UTC
Hello! Sorry for my English... I've got such a problem. I'm using Win10pro with RdpWrap as a server for my buisness and some Windows clients. Every approximately month I update Windows and rdpwrap.ini file at sever during more than one year. And always everything worked well, but about 2 months ago, after regular updating - redirecting of all printers stoped working. (I mean all users, who connected to the server don't see their local printers in the server printers list and can't use them - so this is a server and not clients problem - because it stoped work with all clients at the same moment). Of course, check marks about redirecting printers in local devices and resourses of connetction properties are active. I read a lot of texts about problems with redirrecting printers, but all of them about Windows Server - servers, so the ways these texts about - It's not possible to use. There aren't even such programs and components in Win10pro, that needed to solve the problem. I even tried ScrewDrivers, installation was ok, but I could't make it work anyway...:/ May be someone had the same problems at the same time or another time and can help me what to do? Or I can pay some money if somebody would be able to solve the problem, because I give up... Help me please! Thank you in advance! Yuriy.

**Comment by sashaqwert** [comment] 2022-11-15 14:40
Duplicate of https://github.com/stascorp/rdpwrap/issues/504

**Comment by sashaqwert** [comment] 2022-11-15 14:41
EasyPrint now not working correctly with RDP Wrapper. You can try install printer driver on server.

Or you can uninstall RDP Wrapper and try ServerRdsh (use Google and My Digital Life forum)

**Closed as not planned by sashaqwert** 2022-11-15 14:40 UTC
Labels: duplicate
