### ISSUE TITLE
rdp wrapper not supported windows 10 20h2 19042.844

### ISSUE THREAD

**Issue by ateeqshafiq** [stascorp/rdpwrap#1339] opened 2021-03-04 09:31 UTC

**Comment by ateeqshafiq** [comment] 2021-03-04 10:01
plz send rdpwrap.ini.

**Comment by ninjacarlo** [comment] 2021-03-06 13:59
I doesn't work for me either!

**Comment by sebaxakerhtc** [comment] 2022-06-20 13:02
Duplicate of https://github.com/stascorp/rdpwrap/issues/1317

**Closed as completed by sebaxakerhtc** 2022-06-20 13:02 UTC
