### ISSUE TITLE
Help: need ini file for windows 10 22h2 build 19045.46.51

### ISSUE THREAD

**Issue by tomer676** [stascorp/rdpwrap#3252] opened 2024-08-12 12:52 UTC
Hello, 

Need help please.

I tryed to install the rdpwrap tool using the Install file batch , problem is I have no internet conntcion in this machine, so the installing is stuck on "downloading ini file..."

Can someone upload for me please the needed ini file (i guess it's called "rdpwrap.ini") for my os version (windows 10 22h2 build 19045.46.51) 

My goal is only to enable a multi rdp session simultaneously.

The version of the file c:\Windows\System32\termsrv.dll is 10.0.19041.4474

Thanks in adavnace !!

Tomer

**Comment by loyejaotdiqr47123** [comment] 2024-08-12 13:20
Duplicate of #2840

**Comment by tomer676** [comment] 2024-08-12 13:40
> Duplicate of #2840

Thanks for reply!

#2840  This discussion is in Russian, could you please give me the installation instructions for the solution I need here please ? 
thanks in advance!

**Comment by tomer676** [comment] 2024-08-12 14:44
![Untitled](https://github.com/user-attachments/assets/866ca9d1-de5d-4cc2-afec-c151fd8a6cb3)

i followed up #2840 and used this ini file https://github.com/sebaxakerhtc/rdpwrap.ini/

I managed to get the RDP Wrapper status O.K, but i still can't make multi rdp session simultaneously.

i added a screenshot

**Comment by tomer676** [comment] 2024-08-12 14:54
> Duplicate of #2840

thanks. i used the ini added there and it's works like a charm !

**Closed as completed** 2024-08-14 08:27 UTC
Labels: duplicate
