### ISSUE TITLE
10.0.19045.2006

### ISSUE THREAD

**Issue by 763a** [stascorp/rdpwrap#2499] opened 2024-02-26 07:32 UTC
![截图-20240226152156](https://github.com/stascorp/rdpwrap/assets/160987479/2df50c8f-1be8-403a-9806-38a0ae39bf44)

[Uploading termsrv.zip…]()

**Comment by sashaqwert** [comment] 2024-02-26 15:26
Duplicate of https://github.com/stascorp/rdpwrap/issues/1968

**Closed as not planned by sashaqwert** 2024-02-26 15:26 UTC
Labels: duplicate
