### ISSUE TITLE
Version 10.0.19042.844

### ISSUE THREAD

**Issue by 314t** [stascorp/rdpwrap#1338] opened 2021-03-03 23:43 UTC
It need rdpwrap.ini.
Anybody?

**Comment by ateeqshafiq** [comment] 2021-03-04 09:39
plz send file

**Comment by edy-dev** [comment] 2021-03-04 13:48
20H2 - 19042.844 - 10.0.19041.789 some solution for RDP?

**Comment by No1Alien** [comment] 2021-03-04 15:01
From 19042.844
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/6084555/termsrv.zip)

> plz send file

**Comment by ninjacarlo** [comment] 2021-03-06 14:00
> > plz send file

I replaced my termsrv with this one, but it still doesn't work.

What's the string that we need to change, and what do we need to replace it with?

Thanks in advance!

**Comment by Jimmnj** [comment] 2021-03-08 16:34
I installed KB4601382 which updates the OS Build to 19042.844.  However the version of termsrv.dll did not change from 19041.789.  Rdpconf.exe listener state shows "listening [fully supported]" and Remote Desktop is working as expected without me making any changes.

**Comment by wuzhiwyyx** [comment] 2021-03-09 12:19
> I installed KB4601382 which updates the OS Build to 19042.844. However the version of termsrv.dll did not change from 19041.789. Rdpconf.exe listener state shows "listening [fully supported]" and Remote Desktop is working as expected without me making any changes.

could you please share your termsrv.dll, i encountered the same question, thx very much!

**Comment by A5KkdtxsccH** [comment] 2021-03-10 14:57
have some problem
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/6116751/termsrv.zip)

**Comment by A5KkdtxsccH** [comment] 2021-03-10 15:35
Edition	Windows 10 Home N
Version	20H2
OS build	19042.844
Experience	Windows Feature Experience Pack 120.2212.551.0

**Comment by sebaxakerhtc** [comment] 2022-06-20 13:02
Duplicate of https://github.com/stascorp/rdpwrap/issues/1317

**Closed as completed by sebaxakerhtc** 2022-06-20 13:02 UTC
