### ISSUE TITLE
 I stop/start termservice  but still not listening

### ISSUE THREAD

**Issue by aq834086242** [stascorp/rdpwrap#1963] opened 2022-08-19 22:00 UTC
> ![image](https://user-images.githubusercontent.com/34222926/170659467-46497a0f-d196-4d12-9a44-74acebdfb7d7.png) I also encounter the same problem. fully supported but no listening

https://github.com/sebaxakerhtc/rdpwrap.ini

in cmd
net stop termservice
And then
replace rdpwrap.ini by overhead
And then
net start termservice
And then
restart windows！！！

_Originally posted by @Tomchil in https://github.com/stascorp/rdpwrap/issues/1868#issuecomment-1159911704_

**Comment by sashaqwert** [comment] 2022-08-20 08:26
Try Autoupdate https://github.com/stascorp/rdpwrap/pull/1160

**Comment by sashaqwert** [comment] 2022-08-20 13:20
Duplicate of https://github.com/stascorp/rdpwrap/issues/1868

**Closed as not planned by sashaqwert** 2022-08-20 13:20 UTC
