### ISSUE TITLE
terminal service version : 10.0.18362.836 windows 10 home supported but not listening

### ISSUE THREAD

**Issue by islamelarif** [stascorp/rdpwrap#1193] opened 2020-10-31 08:01 UTC
i tried the difference solutions in other threads but unfortunetly none worked for me,
![config](https://user-images.githubusercontent.com/33578064/97774378-ebfcfa00-1b5f-11eb-8270-c5d5ff4b2d3e.jpg)

so i you can find my 

termsrv.dll file if you can help i will be gratefull

**Comment by islamelarif** [comment] 2020-10-31 08:03
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/5468748/termsrv.zip)

**Comment by robbak** [comment] 2020-10-31 08:21
that version 10.0.18362.836 is supported by affinityv's .ini file.
https://github.com/affinityv/INI-RDPWRAP/blob/master/rdpwrap.ini

**Comment by islamelarif** [comment] 2020-10-31 10:52
i tried the redpwrap.ini that from affinityv's file but unfortunately  now it shows this message
![bug](https://user-images.githubusercontent.com/33578064/97777296-dbf11480-1b77-11eb-96dd-a7ea8d25a95c.jpg)

i replaced the old file with it and then restarted the computer  but still not listening

**Comment by robbak** [comment] 2020-10-31 10:57
That sounds a lot like the "Unix line endings" issue outlined in an issue
currently near the top in the list of problem reports. Check that issue out
and confirm that the file you downloaded doesn't have this problem.

**Comment by islamelarif** [comment] 2020-10-31 18:55
Thats true the file is in theunix code 
I used notepad++ and switched it to windows format
But after so the remote desktop service fails to start

**Comment by permanoob** [comment] 2020-11-28 13:58
Hey, all. I've got the 10.0.18362.836 driver and was having the same issue, with the listener state starting off at "Not listening / not supported," and switching to "not listening / fully supported" after trying affinityv's file and converting it to ANSI with Notepad ++. But then I screwed around with it and got it to work. I'm not quite savvy, so I'll just say what I did, to the best of my memory, and let the big-brains figure out what happened:

1. Extracted the *.zip version of the download to "C:\Program Files\RDP Wrapper," and installed with install.bat. Ran update.bat. No joy.
1. Tried copying the ini into the "C:\Program Files\RDP Wrapper" directory after it was installed and running. Checked with RDPConf. No joy.
2. Uninstalled, using uninstall.bat.
3. Reinstalled, copied ini to the directory before running RDPConf. No joy.
4. Uninstalled.
---
5. (All of this below is the part I think did something.) Copied ini file to directory while RDP Wrapper was NOT installed.
6. Left ini file in "C:\Program Files\RDP Wrapper" open in Notepad++.
7. Reinstalled.
8. Alt-tabbed to Notepad++, had it tell me that the file had changed and told it that I did NOT want to reload the newer version. MAYBE saved the new file in Notepad++. I'm not sure if I saved before or after getting it working. If it breaks again, I'll try and figure out why and give an update.
9. Opened up RDPConf, and the listener state was green and green. Checked with RDPCheck, and got to the logon screen.
10. Cried tears of joy. (Probably optional.)

There might have been some runs of update.bat mixed in there, but I can't really remember where.

Like I said, I have no clue what worked or why. For all I know, the newest ini file might have just gotten updated under my nose while I was tinkering with things. I just thought I'd give a new data point for y'all to chew over.

Thank you for coming to my first GitHub post.

**Comment by Kagamine-Rin** [comment] 2020-11-30 15:16
> i tried the redpwrap.ini that from affinityv's file but unfortunately now it shows this message
> ![bug](https://user-images.githubusercontent.com/33578064/97777296-dbf11480-1b77-11eb-96dd-a7ea8d25a95c.jpg)
> 
> i replaced the old file with it and then restarted the computer but still not listening

Same issue, here's one solution that worked for me:
1. Set the latest ini file to read-only
2. Run uninstall.bat
3. Run install.bat
And it works.

**Comment by sebaxakerhtc** [comment] 2022-06-20 11:51
Duplicate of https://github.com/stascorp/rdpwrap/issues/1083

**Closed as completed by sebaxakerhtc** 2022-06-20 11:51 UTC
