### ISSUE TITLE
1.6.2 msi download gets blocked as "infected by a virus"

### ISSUE THREAD

**Issue by lemmy04** [stascorp/rdpwrap#916] opened 2019-10-27 12:58 UTC

**Comment by SobieskiCodes** [comment] 2019-10-28 11:54
Try reading the FAQ.

> RDP Wrapper can be removed by AVG Free Antivirus and Norton Antivirus - first make sure you downloaded official release from GitHub, then add it to exclusions.


Allow it through your firewall.

**Comment by lemmy04** [comment] 2019-10-28 12:05
..i don't use either, its firefox itself that is complaining when I try to download.

**Comment by SobieskiCodes** [comment] 2019-10-28 12:09
Include that in your post?
https://imgur.com/a/mMFME17

**Comment by lemmy04** [comment] 2019-10-28 12:13
Are you saying when pretty much every AV software on my computer warns me about a piece of software I'm supposed to just say "fck you, i'm installing this anyways?"

**Comment by SobieskiCodes** [comment] 2019-10-28 12:14
Do you understand what this software does? Just curious. This literally modifies your OS, why would any OS think an exe modifying the OS would be 'safe'? It IS a virus in every sense lol. You are modifying your computer to allow it to do something its not supposed to do.

**Comment by lemmy04** [comment] 2019-10-28 14:40
found a better solution - there are legit Windows Pro keys to be purchased. Now my Laptop's running win 10 Pro instead of Home, and I don't need this anymore.

That being said, I scanned the unpacked zip instead of the MSI, and that came in as clean in every scanner i used, so i tried it, and it didn't actually work... no errors or anything, just the connection timed out when trying to connect.

**Comment by SobieskiCodes** [comment] 2019-10-28 15:42
well, as you can see this project hasn't been updated in years.. so it working out of the box isn't going to happen - however the community has plenty of working solutions in the issues section. Windows 10 pro doesn't handle multiple connections.

**Comment by bezik46** [comment] 2020-01-16 06:38
Just about anything & everything blocks this download these days

**Comment by sebaxakerhtc** [comment] 2022-04-27 15:25
Duplicate of https://github.com/stascorp/rdpwrap/issues/277

**Closed as completed by sebaxakerhtc** 2022-04-27 15:25 UTC
