### ISSUE TITLE
Win32/Mamson.A!AC detected using RDP sebaxakerhtc version

### ISSUE THREAD

**Issue by terrencew13** [stascorp/rdpwrap#2107] opened 2023-02-09 15:46 UTC
Win32/Mamson.A!AC detected using RDP sebaxakerhtc version

Windows defender is detecting this as sever risk virus.  Is this a false positive?

**Comment by sashaqwert** [comment] 2023-02-09 17:29
> RDP sebaxakerhtc version

This issues section for official RDP Wrapper (by Stas'M).

Issues for nod here: https://github.com/sebaxakerhtc/rdpwrap.ini

**Comment by sashaqwert** [comment] 2023-02-09 17:32
Duplicate of https://github.com/stascorp/rdpwrap/issues/277

**Closed as not planned by sashaqwert** 2023-02-09 17:32 UTC
Labels: duplicate
