### ISSUE TITLE
windows11 10.0.22621.4391 not supported

### ISSUE THREAD

**Issue by coolanmy** [stascorp/rdpwrap#3352] opened 2024-11-20 16:52 UTC
![image](https://github.com/user-attachments/assets/3ed253a1-5543-40ed-868d-1f87e3d64e09)

**Comment by binarymaster** [comment] 2024-11-20 16:55
Duplicate of https://github.com/stascorp/rdpwrap/issues/3316.

**Closed as not planned by binarymaster** 2024-11-20 16:55 UTC
Labels: duplicate

**Comment by coolanmy** [comment] 2024-11-20 16:56
The firewall has been turned off, and still not listening！
