### ISSUE TITLE
Win 10 1909 186363.1139 (10.0.18.18362.836)

### ISSUE THREAD

**Issue by penarthlan** [stascorp/rdpwrap#1186] opened 2020-10-21 16:46 UTC
Does anyone have a working INI for this update of windows? 1909 186363.1139 (Win 10 Pro)

![image](https://user-images.githubusercontent.com/73247112/96751573-4611f880-13c5-11eb-988b-79e9b56d8088.png)

I'm getting Listening [Not Supported] atm.

**Comment by sk-lau** [comment] 2020-10-22 04:49
From what i know this can be fixed by the Auto update .bat file

**Comment by penarthlan** [comment] 2020-10-22 10:01
No dice on that. Tried the latest INI and the update.bat file,

**Comment by hradec** [comment] 2020-10-23 21:27
I'm also having the same problem with this version: 
![image](https://user-images.githubusercontent.com/806743/97055479-bf335c00-153b-11eb-95e7-97caf324805c.png)
Tried the update.bat file, no change.

**Comment by vinitubr** [comment] 2020-10-25 22:26
Hello brothers. I upgraded Windows today to 1909 18363.1139. Everything broke ((Anyone have a solution?

**Comment by awsfanatic** [comment] 2020-11-02 15:27
Same here with 1903 18362.1139.

**Comment by aPollO2k** [comment] 2020-11-04 17:26
I am also looking for an solution.
![grafik](https://user-images.githubusercontent.com/5796295/98145496-39b09400-1ecb-11eb-9b5e-0a1cee106106.png)

**Comment by sebaxakerhtc** [comment] 2022-06-20 11:48
Duplicate of https://github.com/stascorp/rdpwrap/issues/1083

**Closed as completed by sebaxakerhtc** 2022-06-20 11:48 UTC
