### ISSUE TITLE
New Updated termsrv.dll  6.3.96.00.18928 26.01.2018

### ISSUE THREAD

**Issue by tigos1** [stascorp/rdpwrap#423] opened 2018-03-07 18:35 UTC
After update my Windows 8.1 i have this DLL

termsrv.dll
6.3.96.00.18928
26.01.2018

Patch is not working

**Comment by binarymaster** [comment] 2018-03-08 09:11
Duplicate of #418.

**Closed by binarymaster** 2018-03-08 09:11 UTC
