### ISSUE TITLE
10.0.22000.795 Not supported

### ISSUE THREAD

**Issue by HubertStone** [stascorp/rdpwrap#1927] opened 2022-07-13 10:55 UTC

**Comment by HubertStone** [comment] 2022-07-13 10:56
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/9101399/termsrv.zip)

**Comment by HubertStone** [comment] 2022-07-13 10:57
![image](https://user-images.githubusercontent.com/44018104/178718026-38f12b23-4527-4c9c-97bf-6a7c9e6fe305.png)

**Comment by binarymaster** [comment] 2022-07-13 11:01
Duplicate of #1868.

**Closed as completed by binarymaster** 2022-07-13 11:01 UTC
Labels: duplicate

**Comment by HubertStone** [comment] 2022-07-13 11:03
> Duplicate of #1868.

Is 10.0.22000.795 the same as 708?

**Comment by binarymaster** [comment] 2022-07-13 11:26
You can read what is written on screenshot posted by you?

**Comment by HubertStone** [comment] 2022-07-13 11:27
> You can read what is written on screenshot posted by you?

OK, thanks!

**Comment by Shujee** [comment] 2022-07-24 09:37
For some reason `RDPConf.exe` reports s `10.0.22000.795` as `s `10.0.22000.708`:

![image](https://user-images.githubusercontent.com/5603658/180641058-f21d90f2-3c17-4369-b5b9-1a9c68d3d445.png)

when Windows thinks its version is:

![image](https://user-images.githubusercontent.com/5603658/180641148-d5d1faf0-0f04-4b87-becd-fbe41950b19d.png)

Also, even after using the 706 ini file mentioned above, concurrent connections do not work even though all items are green in `RDPConf` dialog as shown above. I get the error saying that a user is already signed in and trying to connect will move him out.

**Comment by nenka01** [comment] 2022-08-02 13:17
> For some reason `RDPConf.exe` reports s `10.0.22000.795` as `s `10.0.22000.708`:
> 
> ![image](https://user-images.githubusercontent.com/5603658/180641058-f21d90f2-3c17-4369-b5b9-1a9c68d3d445.png)
> 
> when Windows thinks its version is:
> 
> ![image](https://user-images.githubusercontent.com/5603658/180641148-d5d1faf0-0f04-4b87-becd-fbe41950b19d.png)
> 
> Also, even after using the 706 ini file mentioned above, concurrent connections do not work even though all items are green in `RDPConf` dialog as shown above. I get the error saying that a user is already signed in and trying to connect will move him out.

I'm also same problem
