### ISSUE TITLE
may somebody help me???

### ISSUE THREAD

**Issue by gitanoloco** [stascorp/rdpwrap#1119] opened 2020-07-15 15:28 UTC
I have been having connection problems on my remote device for some time but it did not interfere much with my work .... lately I can't even open the google page ... the rdp seems to work perfectly but only when I use it is when the Another device has connection problems ... Any idea what I can do?

![Cgithub](https://user-images.githubusercontent.com/56621653/87564346-dc61be80-c6f2-11ea-9fbf-48a8e5e40b93.PNG)

![Capture](https://user-images.githubusercontent.com/56621653/87564392-e97ead80-c6f2-11ea-8db6-14befb3167f0.PNG)

**Comment by travismailsa** [comment] 2020-07-20 10:46
That seems strange. Is the machine using a proxy?

**Comment by sebaxakerhtc** [comment] 2022-06-20 11:08
Duplicate of https://github.com/stascorp/rdpwrap/issues/1083

**Closed as completed by sebaxakerhtc** 2022-06-20 11:08 UTC
