### ISSUE TITLE
10.0.19041.1741 NOT SUPPORT

### ISSUE THREAD

**Issue by EnigmAze** [stascorp/rdpwrap#1918] opened 2022-06-29 15:46 UTC
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/9012007/termsrv.zip)

**Comment by sashaqwert** [comment] 2022-06-29 17:32
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881

**Comment by sebaxakerhtc** [comment] 2022-06-30 08:36
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881

**Closed as completed by sebaxakerhtc** 2022-06-30 08:36 UTC
