### ISSUE TITLE
not supported message

### ISSUE THREAD

**Issue by srosam** [stascorp/rdpwrap#1252] opened 2020-12-18 11:37 UTC
Hi. I am using this version and getting not supported.
![image](https://user-images.githubusercontent.com/1799158/102610462-2416c700-4125-11eb-96fd-fd8443b07a9f.png)

Windows is ver 1909 build 18363.1256

Anything I should check or try?

**Comment by Damasker** [comment] 2020-12-18 13:35
I have the same issue. Windows is ver 1909 build 18363.1256
I tried to replace rfxvmt.dll, reinstall RDPwrap, update...

**Comment by Damasker** [comment] 2020-12-18 13:56
I find solution.
net stop TermService
replace rdpwrap.ini from my archive [rdpwrap.ini.zip](https://github.com/stascorp/rdpwrap/files/5716048/rdpwrap.ini.zip)
net start TermService

**Comment by kolgorin** [comment] 2020-12-19 04:37
I have the same issue, but I am on the latest Win10 20H2: build 19042.685.
Any idea how to make it working?

It is also weird that the RDPConf says I have a version 19041.662.

![image](https://user-images.githubusercontent.com/76019677/102680851-8a025d80-41bc-11eb-9413-2a33d1926627.png)

**Comment by Damasker** [comment] 2020-12-19 16:05
> I have the same issue, but I am on the latest Win10 20H2: build 19042.685.
> Any idea how to make it working?
> 
> It is also weird that the RDPConf says I have a version 19041.662.
> 
> ![image](https://user-images.githubusercontent.com/76019677/102680851-8a025d80-41bc-11eb-9413-2a33d1926627.png)


How you tried to resolve?
You tried to use my .ini? you installed new DLL or used some instruction?

**Comment by sebaxakerhtc** [comment] 2022-06-20 12:11
Duplicate of https://github.com/stascorp/rdpwrap/issues/1083

**Closed as completed by sebaxakerhtc** 2022-06-20 12:11 UTC
