### ISSUE TITLE
10.0.18362.267 not supported

### ISSUE THREAD

**Issue by littleyanglovegithub** [stascorp/rdpwrap#1932] opened 2022-07-16 03:37 UTC
10.0.18362.267 not supported

**Comment by sashaqwert** [comment] 2022-07-16 07:20
~~Please, attach your RDPConf screenshot and `termsrv.dll`.~~

**Comment by sashaqwert** [comment] 2022-07-16 07:22
Offsets here: https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

I can't find first issue with correct title.

**Comment by sashaqwert** [comment] 2022-07-17 06:06
Duplicate of https://github.com/stascorp/rdpwrap/issues/871

**Closed as not planned** 2022-07-17 06:15 UTC
