### ISSUE TITLE
Windows 10 19045.2913 not listening - Tried multiple ini files off the github

### ISSUE THREAD

**Issue by Soliux** [stascorp/rdpwrap#2193] opened 2023-05-07 16:44 UTC
Restarted termservice and tried multiple ini files but nothing seems to work. All supported but will not start listening state.
![image](https://user-images.githubusercontent.com/66280234/236690896-46e60e7d-ea31-45fe-b97e-0b9703ac1a2a.png)

**Comment by sashaqwert** [comment] 2023-05-07 16:55
One `termsrv.dll` version = ONE opened issue. This issue will closed as duplicate.

**Comment by sashaqwert** [comment] 2023-05-07 16:55
Duplicate of https://github.com/stascorp/rdpwrap/issues/2180

**Comment by sashaqwert** [comment] 2023-05-07 16:56
Try:
1. Download RDP Wrapper 1.6.2 and extract this to any directory.
2. Place `rdpwrap.ini` in the same directory.
3. Open CMD as administrator
4. Execute this commands
```
cd C:\path\to\directory\
rdpwinst -u -k
rdpwinst -i
```
5. Enjoy!

Original message: https://t.me/rdpwrap/49131

**Closed as not planned by sashaqwert** 2023-05-07 16:55 UTC
Labels: duplicate

**Comment by hifihedgehog** [comment] 2023-05-07 20:40
> Try:
> 
> 1. Download RDP Wrapper 1.6.2 and extract this to any directory.
> 2. Place `rdpwrap.ini` in the same directory.
> 3. Open CMD as administrator
> 4. Execute this commands
> 
> ```
> cd C:\path\to\directory\
> rdpwinst -u -k
> rdpwinst -i
> ```
> 
> 5. Enjoy!
> 
> Original message: [t.me/rdpwrap/49131](https://t.me/rdpwrap/49131)

![image](https://user-images.githubusercontent.com/16614343/236701565-5d28ad81-ba75-489b-9a86-26af1034567c.png)

Maybe I am missing something, but 1904_***5***_.2913 is not the same as 1904_***1***_.2913
