### ISSUE TITLE
"Not supported" in RDP config screen after windows updates

### ISSUE THREAD

**Issue by djsuntheone** [stascorp/rdpwrap#556] opened 2018-09-12 21:59 UTC
Windows 8 ver 6.3 build 9600
TERM Ver 6.3.9600.19093

Stopped working after windows updates installed on 9-12-18

Any suggestions to get it working again? i tried uninstalling and reinstalling as "Admin".

**Comment by binarymaster** [comment] 2018-09-12 22:01
Duplicate of #549.

**Closed by binarymaster** 2018-09-12 22:01 UTC
