### ISSUE TITLE
10.0.22621.3527 (Solution) [x64 Bit Version]

### ISSUE THREAD

**Issue by xelenez** [stascorp/rdpwrap#2594] opened 2024-04-24 15:58 UTC
For those running 10.0.22621.3527 (YOURE WELCOME)

[10.0.22621.3527]
SingleUserPatch.x64=1
SingleUserOffset.x64=C4D3
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1C3C5
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=9D6F1
LocalOnlyCode.x64=jmpshort
SLInitHook.x64=1
SLInitOffset.x64=29F60
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.22621.3527-SLInit]
bServerSku.x64=12BF50
bRemoteConnAllowed.x64=12BF64
bFUSEnabled.x64=12BF74
bAppServerAllowed.x64=12BF5C
bMultimonAllowed.x64=12BF68
lMaxUserSessions.x64=12BF54
ulMaxDebugSessions.x64=12BF70
bInitialized.x64=12BF4C

**Comment by TanMan1217** [comment] 2024-04-24 16:17
Thanks very much. This worked!

By the way, this is the x64 version.

**Comment by DF87SE** [comment] 2024-04-24 17:12
> Para aqueles que executam 10.0.22621.3527 (BEM-VINDO)
> 
> [10.0.22621.3527] SingleUserPatch.x64=1 SingleUserOffset.x64=C4D3 SingleUserCode.x64=Zero DefPolicyPatch.x64=1 DefPolicyOffset.x64=1C3C5 DefPolicyCode.x64=CDefPolicy_Query_eax_rcx LocalOnlyPatch.x64=1 LocalOnlyOffset. x64=9D6F1 LocalOnlyCode.x64=jmpshort SLInitHook.x64=1 SLInitOffset.x64=29F60 SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.22621.3527-SLInit] bServerSku.x64=12BF50 bRemoteConnAllowed.x64=12BF64 bFUSEnabled.x64=12BF74 bAppServerAllowed.x64=12BF5C bMultimonAllowed.x64=12BF68 lMaxUserSessions.x64 =12 BF54 ulMaxDebugSessions.x64 =12BF70 bInitialized.x64=12BF4C

o meu aparece suportado, mas só permite uma conexão por usuário, ou seja para um usuário acessar tem que derrubar o logado! tem a solução para isso tbm?

**Comment by headak002** [comment] 2024-04-24 18:39
> For those running 10.0.22621.3527 (YOURE WELCOME)
> 
> [10.0.22621.3527] SingleUserPatch.x64=1 SingleUserOffset.x64=C4D3 SingleUserCode.x64=Zero DefPolicyPatch.x64=1 DefPolicyOffset.x64=1C3C5 DefPolicyCode.x64=CDefPolicy_Query_eax_rcx LocalOnlyPatch.x64=1 LocalOnlyOffset.x64=9D6F1 LocalOnlyCode.x64=jmpshort SLInitHook.x64=1 SLInitOffset.x64=29F60 SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.22621.3527-SLInit] bServerSku.x64=12BF50 bRemoteConnAllowed.x64=12BF64 bFUSEnabled.x64=12BF74 bAppServerAllowed.x64=12BF5C bMultimonAllowed.x64=12BF68 lMaxUserSessions.x64=12BF54 ulMaxDebugSessions.x64=12BF70 bInitialized.x64=12BF4C



where do i have to paste this

**Comment by DF87SE** [comment] 2024-04-24 18:56
> Para aqueles que executam 10.0.22621.3527 (BEM-VINDO)
> 
> [10.0.22621.3527] SingleUserPatch.x64=1 SingleUserOffset.x64=C4D3 SingleUserCode.x64=Zero DefPolicyPatch.x64=1 DefPolicyOffset.x64=1C3C5 DefPolicyCode.x64=CDefPolicy_Query_eax_rcx LocalOnlyPatch.x64=1 LocalOnlyOffset. x64=9D6F1 LocalOnlyCode.x64=jmpshort SLInitHook.x64=1 SLInitOffset.x64=29F60 SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.22621.3527-SLInit] bServerSku.x64=12BF50 bRemoteConnAllowed.x64=12BF64 bFUSEnabled.x64=12BF74 bAppServerAllowed.x64=12BF5C bMultimonAllowed.x64=12BF68 lMaxUserSessions.x64 =12 BF54 ulMaxDebugSessions.x64 =12BF70 bInitialized.x64=12BF4C

My RDPWRAP is supported and updated for sure, but it only allows one connection per user, that is, for a user to access they have to log in! Do you have a solution for this too?

**Comment by TanMan1217** [comment] 2024-04-24 19:01
> where do i have to paste this

Use autoupdate from @asmtron:

https://github.com/asmtron/rdpwrap

If you use this and run his autoupdate, you won't have to edit the rdpwrap.ini yourself.

**Comment by loyejaotdiqr47123** [comment] 2024-04-25 12:57
Duplicate of #2589

**Comment by DF87SE** [comment] 2024-04-25 13:17
does not work, I don't allow multiple users

**Comment by headak002** [comment] 2024-04-25 14:31
> > where do i have to paste this
> 
> Use autoupdate from @asmtron:
> 
> https://github.com/asmtron/rdpwrap
> 
> If you use this and run his autoupdate, you won't have to edit the rdpwrap.ini yourself.

already have still facing not supported issues

**Comment by headak002** [comment] 2024-04-25 14:43
> > where do i have to paste this
> 
> Use autoupdate from @asmtron:
> 
> https://github.com/asmtron/rdpwrap
> 
> If you use this and run his autoupdate, you won't have to edit the rdpwrap.ini yourself.

yep tried it but not working, pasted autoupdate file at the location where rdpwrap.ini file is and run it as administator

**Comment by headak002** [comment] 2024-04-25 14:52
> For those running 10.0.22621.3527 (YOURE WELCOME)
> 
> [10.0.22621.3527] SingleUserPatch.x64=1 SingleUserOffset.x64=C4D3 SingleUserCode.x64=Zero DefPolicyPatch.x64=1 DefPolicyOffset.x64=1C3C5 DefPolicyCode.x64=CDefPolicy_Query_eax_rcx LocalOnlyPatch.x64=1 LocalOnlyOffset.x64=9D6F1 LocalOnlyCode.x64=jmpshort SLInitHook.x64=1 SLInitOffset.x64=29F60 SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.22621.3527-SLInit] bServerSku.x64=12BF50 bRemoteConnAllowed.x64=12BF64 bFUSEnabled.x64=12BF74 bAppServerAllowed.x64=12BF5C bMultimonAllowed.x64=12BF68 lMaxUserSessions.x64=12BF54 ulMaxDebugSessions.x64=12BF70 bInitialized.x64=12BF4C

where to edit rdpwrap.ini file??

**Comment by sashaqwert** [comment] 2024-04-29 14:38
Duplicate of https://github.com/stascorp/rdpwrap/issues/2589

**Closed as not planned by sashaqwert** 2024-04-29 14:38 UTC
Labels: duplicate
