### ISSUE TITLE
The specified file cannot be found“ termsrv.dll " version.

### ISSUE THREAD

**Issue by Wpenga** [stascorp/rdpwrap#1309] opened 2021-01-27 18:09 UTC
NOT found "termsrv.dll" version entry **[10.0.18362.1316]** in file "C:\Program Files\RDP Wrapper\rdpwrap.ini"!

**Comment by sebaxakerhtc** [comment] 2022-06-20 12:44
Duplicate of https://github.com/stascorp/rdpwrap/issues/1278

**Closed as completed by sebaxakerhtc** 2022-06-20 12:44 UTC
