### ISSUE TITLE
Windows 10 Pro 32 bits  [10.0.19041.3636] x86 Not listering

### ISSUE THREAD

**Issue by r-troncoso** [stascorp/rdpwrap#2390] opened 2023-10-30 22:06 UTC
Windows 10 Pro 32 bits  [10.0.19041.3636] x86 Not listering

![Captura de pantalla 2023-10-30 225343](https://github.com/stascorp/rdpwrap/assets/104627081/ba7093d2-5283-4501-b305-b5b106799f77)

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/13210194/termsrv.zip)

thank you so much

**Comment by sashaqwert** [comment] 2023-11-01 11:17
https://github.com/sebaxakerhtc/rdpwrap.ini/commit/40e4c3d10a143e8afa82199d270d6a5486fe9d3d

**Comment by sashaqwert** [comment] 2023-11-01 11:18
> service status = starting...

See https://github.com/stascorp/rdpwrap/issues/1883

**Comment by r-troncoso** [comment] 2023-11-01 13:29
Thanks for your response, I am using the new rdpwrap.ini dated 2023-10-27, edited by sebaxakerhtc and the same problem continues. With termsrv.dll version 10.0.19041.3570, it works perfectly, but when installing the KB5031445 Windows 10 32-bit update with termsrv.dll version 10.0.19041.3636, remote desktop does not work. was tested on two PCs with the same result

[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/13227319/rdpwrap.zip)

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/13227323/termsrv.zip)

![Captura de pantalla 2023-11-01 135518](https://github.com/stascorp/rdpwrap/assets/104627081/98938510-f78f-4f02-8a00-e6cfa963ed79)

Uninstalling version KB5031445 of windows 10 pro 32 bit and termsrv.dll with version 10.0.19041.3570, it works perfectly


![Captura de pantalla 2023-11-01 134639](https://github.com/stascorp/rdpwrap/assets/104627081/b3ce0ea7-316f-4abf-b665-22233bf611f3)

thank you sashaqwert

**Comment by sashaqwert** [comment] 2023-11-01 13:36
> Thanks for your response, I am using the new rdpwrap.ini dated 2023-10-27, edited by sebaxakerhtc and the same problem continues. With termsrv.dll version 10.0.19041.3570, it works perfectly, but when installing the KB5031445 Windows 10 32-bit update with termsrv.dll version 10.0.19041.3636, remote desktop does not work. was tested on two PCs with the same result

Please, join to https://t.me/rdpwrap and member @sebaxakerhtc (INI developer)

**Comment by r-troncoso** [comment] 2023-11-01 13:57
Telegram Desktop does not work for me in 32 bits

With RDP_CnC.exe, [Update INI] and [Restart TermService], I have the same results.

From what I saw, the parameters of version 10.0.19041.3570 x86 and 10.0.19041.3636 x86 are the same in rdpwrap.ini. You could check it again

Excuse my English, I'm Spanish

**Comment by sashaqwert** [comment] 2023-11-01 16:24
> Telegram Desktop does not work for me in 32 bits

https://web.telegram.org :)

> You could check it again

Waiting sebaxakerhtc here or in Telegram/Discord

**Comment by r-troncoso** [comment] 2023-11-01 16:58
ready, and now?

**Comment by hovanaz** [comment] 2023-11-21 06:19
did you solve this problem , me too :(

**Comment by sashaqwert** [comment] 2023-11-21 17:16
> did you solve this problem , me too :(

Won't fixed. See https://t.me/rdpwrap/63606

**Comment by sashaqwert** [comment] 2024-01-08 08:32
UPD: Now RDP Wrapper works only in Pro / Education / Enterprise.

Home: won't fix.

**Comment by loyejaotdiqr47123** [comment] 2024-02-22 15:21
> Windows 10 Pro 32 bits [10.0.19041.3636] x86 Not listering
> 
> ![Captura de pantalla 2023-10-30 225343](https://private-user-images.githubusercontent.com/104627081/279205807-ba7093d2-5283-4501-b305-b5b106799f77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MTU0NjEsIm5iZiI6MTcwODYxNTE2MSwicGF0aCI6Ii8xMDQ2MjcwODEvMjc5MjA1ODA3LWJhNzA5M2QyLTUyODMtNDUwMS1iMzA1LWI1YjEwNjc5OWY3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMlQxNTE5MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYzQ0ZTZmYWE4ODZlOWI5ZDllYmQyMjc2ZDk3Mzg4Y2YwYmYzY2M1NDY3MmE3OTI4OTQ1ZGY4MWFlMzFkYWRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eiSyuLumV6TxznaZIMXPSTtJ6yD_3UAXpUSwJc3tJZA)
> 
> [termsrv.zip](https://github.com/stascorp/rdpwrap/files/13210194/termsrv.zip)
> 
> thank you so much


[10.0.19041.3636]
LocalOnlyPatch.x86=1
LocalOnlyOffset.x86=C3299
LocalOnlyCode.x86=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=3FDB0
SingleUserCode.x64=nop
DefPolicyPatch.x86=1
DefPolicyOffset.x86=41999
DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
SLInitHook.x86=1
SLInitOffset.x86=70E18
SLInitFunc.x86=New_CSLQuery_Initialize

[10.0.19041.3636-SLInit]
bInitialized.x86=E498C
bServerSku.x86=E4990
lMaxUserSessions.x86  =E4994
bAppServerAllowed.x86 =E499C
bRemoteConnAllowed.x86=E49A4
bMultimonAllowed.86=E49A8
ulMaxDebugSessions.x86=E49AC
bFUSEnabled.x86=E49B0
You can try this offsets.

**Comment by sebaxakerhtc** [comment] 2024-02-24 08:20
> UPD: Now RDP Wrapper works only in Pro / Education / Enterprise.
> 
> Home: won't fix.

Fixed. All works fine now.
The problem was from autogenerated file with a BUG - the same offset for 2 variables
```
bAppServerAllowed.x86 =E499C
bRemoteConnAllowed.x86=E499C
```

**Comment by sebaxakerhtc** [comment] 2024-02-24 08:40
![изображение](https://github.com/stascorp/rdpwrap/assets/32651506/e0de3937-edaa-4ad6-a009-5747c6c71ca6)

**Comment by sashaqwert** [comment] 2024-02-24 09:47
> Home: won't fix

Fixed in https://github.com/sebaxakerhtc/rdpwrap.ini/commit/593a7bc143ef5712eedd99ec18f584a360d28ed1

**Comment by binarymaster** [comment] 2024-07-04 16:35
Duplicate of #2381.

**Closed as not planned by binarymaster** 2024-07-04 16:35 UTC
Labels: duplicate
