### ISSUE TITLE
RDP not supported on ver 10.0.19041.1387

### ISSUE THREAD

**Issue by africa1207** [stascorp/rdpwrap#2403] opened 2023-11-14 09:21 UTC
![image](https://github.com/stascorp/rdpwrap/assets/21698755/7a39f4e1-3d09-47f2-affc-b2349949be11)

**Comment by sashaqwert** [comment] 2023-11-15 07:28
Duplicate of https://github.com/stascorp/rdpwrap/issues/1630

**Closed as not planned by sashaqwert** 2023-11-15 07:28 UTC
Labels: duplicate
