### ISSUE TITLE
10.0.19041.2075 not work

### ISSUE THREAD

**Issue by jsf459189749** [stascorp/rdpwrap#2106] opened 2023-02-09 10:58 UTC
![1675939580342](https://user-images.githubusercontent.com/26958874/217792265-36af1e59-3b87-4a27-a74e-34311e4fa97a.png)
![1675940230869](https://user-images.githubusercontent.com/26958874/217793881-7084939d-7e6a-4cdf-bd7b-f074713145f5.png)
I can't currently see the installed version number in the application, but I can see the actual system version number when I execute install.
I have replaced the ini. I don't know what went wrong.
Have you encountered the same error, can you tell me how to solve this problem.

Thanks.

**Comment by sashaqwert** [comment] 2023-02-09 17:34
Duplicate of https://github.com/stascorp/rdpwrap/issues/1883

**Comment by sashaqwert** [comment] 2023-02-09 17:34
And https://github.com/stascorp/rdpwrap/issues/1992

Please, repair your operating system.

**Closed as not planned by sashaqwert** 2023-02-09 17:34 UTC
Labels: duplicate
