### ISSUE TITLE
Windows 11 Pro 23H2 22631.2715

### ISSUE THREAD

**Issue by matrunchyk** [stascorp/rdpwrap#2432] opened 2023-11-30 07:27 UTC
`Listening`, but `[not supported]`

[termsrv.dll.zip](https://github.com/stascorp/rdpwrap/files/13509769/termsrv.dll.zip)

**Comment by sashaqwert** [comment] 2023-12-02 09:17
Duplicate of https://github.com/stascorp/rdpwrap/issues/2383

**Closed as not planned by sashaqwert** 2023-12-02 09:17 UTC
Labels: duplicate
