### ISSUE TITLE
ini for ver 10.0.19044.1415?

### ISSUE THREAD

**Issue by quintanaolvis** [stascorp/rdpwrap#1659] opened 2021-12-15 14:44 UTC
Hello guys,

My windows, just have been installed updates and ruined my rdp setting,

anyone have test any solution for version 21H2 (so compilation 19044.1415)

**Comment by sebaxakerhtc** [comment] 2021-12-17 15:44
Duplicate of https://github.com/stascorp/rdpwrap/issues/1630

**Closed as completed by sebaxakerhtc** 2021-12-17 15:44 UTC
