### ISSUE TITLE
win10 不支持版本19044:1706

### ISSUE THREAD

**Issue by Sue-Tin** [stascorp/rdpwrap#1857] opened 2022-05-17 02:12 UTC
![image](https://user-images.githubusercontent.com/85327521/168714352-80b92abe-2f50-449b-b427-12ef4b1c99b6.png)
![Uploading image.png…]()

**Comment by TimTse2020** [comment] 2022-05-17 07:43
是的，我也是这个版本，无法开启多用户远程。
![QQ截图20220517163254](https://user-images.githubusercontent.com/105480183/168767635-c54e6928-5a7a-4a17-9e56-6b1826082286.png)
![QQ截图20220517163220](https://user-images.githubusercontent.com/105480183/168767646-55264d72-1efb-4e50-9667-a53e6957cc76.png)
![QQ截图20220517163244](https://user-images.githubusercontent.com/105480183/168767661-4326cf27-ef02-49fa-8db6-adebdd4c70f6.png)
![QQ截图20220517163253](https://user-images.githubusercontent.com/105480183/168767679-2a4d09a2-a971-4d16-9593-3520c2a986c1.png)

**Comment by sashaqwert** [comment] 2022-05-17 15:51
Duplicate of https://github.com/stascorp/rdpwrap/issues/1823

Rule: one **termsrv** version = one issue. Other issues (duplicates) will closed.

Note: You can see a `termsrv.dll` version in RDPConf. Do not use version from winver, cmd, etc.

**Comment by wxpanada** [comment] 2022-05-19 03:30
https://github.com/anhkgg/SuperRDP
You can set the checkbox AutoSupport， then SuperRDP2 will automatically support the new version

**Comment by sebaxakerhtc** [comment] 2022-05-20 07:42
> Duplicate of #1823

**Closed as completed by sebaxakerhtc** 2022-05-20 07:42 UTC
