### ISSUE TITLE
need help for 10.0.22000.1

### ISSUE THREAD

**Issue by m5p2022** [stascorp/rdpwrap#1547] opened 2021-10-05 05:39 UTC
Hello, 

my configuration on win 11 shows me not supported.
Can anyone help me ?
Thanks!
![image](https://user-images.githubusercontent.com/91935489/135966553-2c837120-1f07-4447-b03b-3432c0526cd0.png)

**Comment by emzilla2** [comment] 2021-10-05 14:05
https://github.com/stascorp/rdpwrap/issues/1481

**Comment by sebaxakerhtc** [comment] 2021-10-25 16:10
duplicate of https://github.com/stascorp/rdpwrap/issues/1455

**Closed as completed by sebaxakerhtc** 2021-10-25 16:10 UTC
