### ISSUE TITLE
Not listening / Wrong version

### ISSUE THREAD

**Issue by mroook** [stascorp/rdpwrap#2028] opened 2022-10-22 19:08 UTC

**Comment by mroook** [comment] 2022-10-22 19:08
i need the ini for the new version

**Comment by mroook** [comment] 2022-10-22 19:09
![image](https://user-images.githubusercontent.com/110442940/197358362-425e639c-7fa7-4ac2-ae6b-29efb050ce03.png)

**Comment by sashaqwert** [comment] 2022-10-23 07:29
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992

**Closed as not planned by sashaqwert** 2022-10-23 07:29 UTC
Labels: duplicate
