### ISSUE TITLE
shows "fully supported & listening" but still cant be connected

### ISSUE THREAD

**Issue by renjc-pro** [stascorp/rdpwrap#2556] opened 2024-04-11 01:50 UTC
![image](https://github.com/stascorp/rdpwrap/assets/31948088/9427f893-1e32-4fee-a951-9cde19554db1)
![image](https://github.com/stascorp/rdpwrap/assets/31948088/3e356633-c368-49a9-97a3-cdc175dc7518)

after installed KB5036893 (OS Builds 22621.3447 and 22631.3447)

**Comment by BlueWhale52** [comment] 2024-04-11 09:59
I have never encountered this situation, but after the update, listener state is not supported.
After updating the configuration it was ok. 
The configuration code corresponding to this version is as follows

`
[10.0.22621.3447]
SingleUserPatch.x64=1
SingleUserOffset.x64=C3F3
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1C2E5
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=9D661
LocalOnlyCode.x64=jmpshort
SLInitHook.x64=1
SLInitOffset.x64=29ED0
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.22621.3447-SLInit]
bServerSku.x64=12BF50
bRemoteConnAllowed.x64=12BF64
bFUSEnabled.x64=12BF74
bAppServerAllowed.x64=12BF5C
bMultimonAllowed.x64=12BF68
lMaxUserSessions.x64=12BF54
ulMaxDebugSessions.x64=12BF70
bInitialized.x64=12BF4C
`

**Comment by loyejaotdiqr47123** [comment] 2024-04-11 12:34
Duplicate of #2549

**Comment by Baggio824** [comment] 2024-04-11 13:22
> > ![зображення](https://private-user-images.githubusercontent.com/31948088/321458532-9427f893-1e32-4fee-a951-9cde19554db1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4Mzk0NDgsIm5iZiI6MTcxMjgzOTE0OCwicGF0aCI6Ii8zMTk0ODA4OC8zMjE0NTg1MzItOTQyN2Y4OTMtMWUzMi00ZmVlLWE5NTEtOWNkZTE5NTU0ZGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDEyMzkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4MGZjODVkOTljZjgzOWQ5YWMzOWI1MWM1N2Q5YTQ4YzJlYzdhMjJkN2U5NzRjOWQ4NmJkMzAxYjVmYzQwZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZnbnJqq7GVKelV8IYO-2RJlqBis-nT7pqhKWpjcvlic) ![зображення](https://private-user-images.githubusercontent.com/31948088/321458581-3e356633-c368-49a9-97a3-cdc175dc7518.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4Mzk0NDgsIm5iZiI6MTcxMjgzOTE0OCwicGF0aCI6Ii8zMTk0ODA4OC8zMjE0NTg1ODEtM2UzNTY2MzMtYzM2OC00OWE5LTk3YTMtY2RjMTc1ZGM3NTE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDEyMzkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3ZDAwOGFhMTI0NWEzZjkxYTA1ZWExYmFmNzllNDFjNmI5NjFhMzIyOTBkOTViZTA3OWVjMzBmODAwNzE3N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lU9DXb40i2cm2RS3eogOO7Kf1vPLEdvnLs0_FMabrBM)
> > після встановлення KB5036893 (збірки ОС 22621.3447 і 22631.3447)
> 
> [RDPWrap-v1.8.2.zip](https://github.com/stascorp/rdpwrap/files/14946207/RDPWrap-v1.8.2.zip) 尝试使用这个 你必须卸载rdpwrap1.6.2且使用1.6.2自带的uninstall.bat，然后在使用1.8.2的install.bat

Thank you! Will your program run automatically? Does it already have RDPWrapOffsetFinder built in?

**Comment by renjc-pro** [comment] 2024-04-11 23:54
> > ![image](https://private-user-images.githubusercontent.com/31948088/321458532-9427f893-1e32-4fee-a951-9cde19554db1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4Mzk0NDgsIm5iZiI6MTcxMjgzOTE0OCwicGF0aCI6Ii8zMTk0ODA4OC8zMjE0NTg1MzItOTQyN2Y4OTMtMWUzMi00ZmVlLWE5NTEtOWNkZTE5NTU0ZGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDEyMzkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4MGZjODVkOTljZjgzOWQ5YWMzOWI1MWM1N2Q5YTQ4YzJlYzdhMjJkN2U5NzRjOWQ4NmJkMzAxYjVmYzQwZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZnbnJqq7GVKelV8IYO-2RJlqBis-nT7pqhKWpjcvlic) ![image](https://private-user-images.githubusercontent.com/31948088/321458581-3e356633-c368-49a9-97a3-cdc175dc7518.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4Mzk0NDgsIm5iZiI6MTcxMjgzOTE0OCwicGF0aCI6Ii8zMTk0ODA4OC8zMjE0NTg1ODEtM2UzNTY2MzMtYzM2OC00OWE5LTk3YTMtY2RjMTc1ZGM3NTE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDEyMzkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3ZDAwOGFhMTI0NWEzZjkxYTA1ZWExYmFmNzllNDFjNmI5NjFhMzIyOTBkOTViZTA3OWVjMzBmODAwNzE3N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lU9DXb40i2cm2RS3eogOO7Kf1vPLEdvnLs0_FMabrBM)
> > after installed KB5036893 (OS Builds 22621.3447 and 22631.3447)
> 
> [RDPWrap-v1.8.2.zip](https://github.com/stascorp/rdpwrap/files/14946207/RDPWrap-v1.8.2.zip) 尝试使用这个 你必须卸载rdpwrap1.6.2且使用1.6.2自带的uninstall.bat，然后在使用1.8.2的install.bat

试过了 还是一样的问题

**Comment by loyejaotdiqr47123** [comment] 2024-04-12 08:24
> > > ![image](https://private-user-images.githubusercontent.com/31948088/321458532-9427f893-1e32-4fee-a951-9cde19554db1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4Mzk0NDgsIm5iZiI6MTcxMjgzOTE0OCwicGF0aCI6Ii8zMTk0ODA4OC8zMjE0NTg1MzItOTQyN2Y4OTMtMWUzMi00ZmVlLWE5NTEtOWNkZTE5NTU0ZGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDEyMzkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4MGZjODVkOTljZjgzOWQ5YWMzOWI1MWM1N2Q5YTQ4YzJlYzdhMjJkN2U5NzRjOWQ4NmJkMzAxYjVmYzQwZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZnbnJqq7GVKelV8IYO-2RJlqBis-nT7pqhKWpjcvlic) ![image](https://private-user-images.githubusercontent.com/31948088/321458581-3e356633-c368-49a9-97a3-cdc175dc7518.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4Mzk0NDgsIm5iZiI6MTcxMjgzOTE0OCwicGF0aCI6Ii8zMTk0ODA4OC8zMjE0NTg1ODEtM2UzNTY2MzMtYzM2OC00OWE5LTk3YTMtY2RjMTc1ZGM3NTE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDEyMzkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3ZDAwOGFhMTI0NWEzZjkxYTA1ZWExYmFmNzllNDFjNmI5NjFhMzIyOTBkOTViZTA3OWVjMzBmODAwNzE3N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lU9DXb40i2cm2RS3eogOO7Kf1vPLEdvnLs0_FMabrBM)
> > > after installed KB5036893 (OS Builds 22621.3447 and 22631.3447)
> > 
> > 
> > [RDPWrap-v1.8.2.zip](https://github.com/stascorp/rdpwrap/files/14946207/RDPWrap-v1.8.2.zip) 尝试使用这个 你必须卸载rdpwrap1.6.2且使用1.6.2自带的uninstall.bat，然后在使用1.8.2的install.bat
> 
> 试过了 还是一样的问题

[SuperRDP2_ini-2024-4-11.zip](https://github.com/stascorp/rdpwrap/files/14956124/SuperRDP2_ini-2024-4-11.zip)
试下这个，别同步最新配置，不然ini就会被覆盖掉了

**Comment by sashaqwert** [comment] 2024-04-12 14:51
Duplicate of https://github.com/stascorp/rdpwrap/issues/2549

**Closed as not planned by sashaqwert** 2024-04-12 14:51 UTC
Labels: duplicate
