### ISSUE TITLE
Need help with 10.0.17763.1369

### ISSUE THREAD

**Issue by EronHou** [stascorp/rdpwrap#2013] opened 2022-10-10 16:06 UTC
![微信图片_20221011000618](https://user-images.githubusercontent.com/45758981/194909071-4b850dad-7f71-4ecb-ae78-413d37799f91.png)

**Comment by tetas26** [comment] 2022-10-10 21:40
https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

**Comment by sashaqwert** [comment] 2022-10-11 08:19
Duplicate of https://github.com/stascorp/rdpwrap/issues/1953

**Closed as not planned by sashaqwert** 2022-10-11 08:19 UTC
Labels: duplicate
