### ISSUE TITLE
RPD wrapper for windows 10 21h2 19044.1741 not supported

### ISSUE THREAD

**Issue by jason9233** [stascorp/rdpwrap#1886] opened 2022-06-03 16:12 UTC
Hi,

Someone have the .ini to this version  windows 10 21h2 19044.1741

greetings

**Comment by sashaqwert** [comment] 2022-06-04 04:47
RDPConf screenshot, please!

**Comment by sashaqwert** [comment] 2022-06-04 04:55
Solved here: https://github.com/sebaxakerhtc/rdpwrap.ini/issues/116

Please, rename your issue to `19041.1741 not supported`

**Comment by sebaxakerhtc** [comment] 2022-06-04 11:17
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881

**Closed as completed by sebaxakerhtc** 2022-06-04 11:17 UTC

**Comment by AlexNaBo** [comment] 2022-06-06 13:31
Help please
.ini uploaded

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/8844766/termsrv.zip)
![Безымянный](https://user-images.githubusercontent.com/106975860/172169857-f76b72e1-ef0b-48bb-b0fa-94d275720076.png)

**Comment by sashaqwert** [comment] 2022-06-06 13:38
@AlexNaBo 
Try `net start termService` (as Administrator)

**Comment by AlexNaBo** [comment] 2022-06-06 14:10
> @AlexNaBo Попробуйте `net start termService`(как администратор)
termService restarted many times, does not help
