### ISSUE TITLE
Win11 22h2 not supported

### ISSUE THREAD

**Issue by Penguk** [stascorp/rdpwrap#2560] opened 2024-04-11 15:44 UTC
Hello, 

probabbly duplicated but if you could help me with the correct ini file I should use I'd appreciate the help.
![Screenshot_1](https://github.com/stascorp/rdpwrap/assets/65315964/76f197a2-eaaa-47b8-beae-0c36e7ff681a)
[RDP Wrapper.zip](https://github.com/stascorp/rdpwrap/files/14948317/RDP.Wrapper.zip)

**Comment by Penguk** [comment] 2024-04-11 15:52
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/14948404/termsrv.zip)
Forgot termsrv

**Comment by robyDima21** [comment] 2024-04-12 09:30
Come si può fare per risolvere questo problma?

**Comment by sashaqwert** [comment] 2024-04-12 17:46
Duplicate of https://github.com/stascorp/rdpwrap/issues/2549

**Closed as not planned by sashaqwert** 2024-04-12 17:46 UTC
Labels: duplicate
