### ISSUE TITLE
10.0.19045.2545 is not supported

### ISSUE THREAD

**Issue by luckyEason** [stascorp/rdpwrap#2089] opened 2023-01-16 04:21 UTC

**Comment by sashaqwert** [comment] 2023-01-16 07:35
Please, attach your RDPConf screenshot and `termsrv.dll`.
Also this issue will closed as incorrect.

**Comment by hosseinadib-hub** [comment] 2023-01-16 20:36
I have same problem
![image](https://user-images.githubusercontent.com/663815/212761919-746ca25f-8bb4-41ee-9b21-99f53cbcc5bf.png)

**Comment by sashaqwert** [comment] 2023-01-17 06:13
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992

**Closed as not planned by sashaqwert** 2023-01-17 06:13 UTC
Labels: duplicate
