### ISSUE TITLE
Windows 10 Home 1703 (OS build 15063.0) - Running, fully supported but not listening

### ISSUE THREAD

**Issue by ultradj83** [stascorp/rdpwrap#228] opened 2017-04-06 15:33 UTC
Dears,
   I'm running Windows 10 Home 1703 (OS build 15063.0).
Wrapped state is Running, fully supported but Not Listening.

This is the log:
`>>> SvchostPushServiceGlobals
Loading configuration...
Configuration file: c:\program files\rdp wrapper\rdpwrap.ini
Initializing RDP Wrapper...
Base addr:  0x00007FFE19340000
SvcMain:    termsrv.dll+0x00000000000313F0
SvcGlobals: termsrv.dll+0x0000000000031460
Version:    10.0.15063.0
Freezing threads...
Patch CEnforcementCore::GetInstanceOfTSLicense
Patch CSessionArbitrationHelper::IsSingleSessionPerUserEnabled
Patch CDefPolicy::Query
Hook CSLQuery::Initialize
Resumimg threads...
<<< SvchostPushServiceGlobals
>>> ServiceMain
<<< ServiceMain
>>> CSLQuery::Initialize
SLInit [0x00007FFE19429484] bServerSku = 1
SLInit [0x00007FFE1942946C] bRemoteConnAllowed = 1
SLInit [0x00007FFE19429478] bFUSEnabled = 1
SLInit [0x00007FFE1942948C] bAppServerAllowed = 1
SLInit [0x00007FFE19429470] bMultimonAllowed = 1
SLInit [0x00007FFE19429488] lMaxUserSessions = 0
SLInit [0x00007FFE19429474] ulMaxDebugSessions = 0
SLInit [0x00007FFE19429468] bInitialized = 1
<<< CSLQuery::Initialize
`

SmartScreen is disabled, Windows Firewall is disabled.

What can I do?

Thanks a lot.

**Comment by binarymaster** [comment] 2017-04-06 18:03
> What can I do?

Look for existing issues before creating a new one. Closed as duplicate of #194.

**Closed by binarymaster** 2017-04-06 18:03 UTC
Labels: duplicate

**Comment by ultradj83** [comment] 2017-04-07 09:15
Dear @binarymaster ,
   I'm sorry but I could find no useful information in #194.
I only found a hint to add a line at the bottom in the .ini file but I can't do this cause it's opened by critical system services I cannot stop.

Tks.

**Comment by binarymaster** [comment] 2017-04-07 09:19
INI file is not related to this problem.

**Comment by ultradj83** [comment] 2017-04-07 09:32
I'm sorry @binarymaster but I don't understand.
What should I get from #194 to fix this problem?

Tks.

**Comment by binarymaster** [comment] 2017-04-07 09:39
You should understand that this problem is not just your problem, this is general known issue for all Windows 10 Home users with build 15002 and higher.

**Comment by ultradj83** [comment] 2017-04-07 09:40
Oh, I couldn't understand there's no solution.

Tks.

**Comment by binarymaster** [comment] 2017-04-07 09:47
You can track the issue #194, it will be closed when we found the solution.
