### ISSUE TITLE
RDPWrapper not completely uninstalled

### ISSUE THREAD

**Issue by rac19** [stascorp/rdpwrap#400] opened 2018-01-27 13:17 UTC
When I ran the uninstall batch file (as Admin), RDPWrap seemed to uninstall properly but the RDP Wrapper Library was left behind. It I attempt to uninstall it, I get an error. I have recently upgraded to Windows 10 Pro and no longer need RDPWrap. I would like to completely remove it if possible. Thank you.

![rdpwrapper](https://user-images.githubusercontent.com/20808962/35472276-7f85db4e-03c0-11e8-88f9-ecfa9e41df09.JPG)

**Comment by binarymaster** [comment] 2018-01-27 13:40
Duplicate of #377. You shouldn't use MSI installer in Win 10.

**Closed by binarymaster** 2018-01-27 13:40 UTC

**Comment by galeksandrp** [comment] 2018-01-29 11:27
This is not an Windows 10 issue. MSI uninstaller itself uses tool from batch file to uninstall RDPWrap, but since you already uninstalled RDPWrap completely, MSI uninstaller fails.

Since MSI does not support different actions for different exit codes, MSI uninstaller can't designate in which cases it's safe to finish uninstall.

As a temporary workaround you can install rdpwap with batch file, and then delete with MSI uninstaller.
