### ISSUE TITLE
Listener state: Not listening [not supported]

### ISSUE THREAD

**Issue by mitchstein443** [stascorp/rdpwrap#2113] opened 2023-02-13 22:54 UTC
windows 10 home 19045.2486
![image](https://user-images.githubusercontent.com/21157042/218592593-de230557-5bab-4724-84a4-04f53df23d90.png)

giving the not listening error. 

I tried adding the ini entries in the revious closed post.
I restarted, reinstalled as admin, reran everything as admin and copied all the files into the program dir... 

Any ideas what to try next?
![image](https://user-images.githubusercontent.com/21157042/218592759-861ed8cb-8796-4891-9ae7-1279ff9fe52e.png)

**Comment by sashaqwert** [comment] 2023-02-14 08:02
> I tried adding the ini entries in the revious closed post.

Trolling detected. Your GitHub account is no have other issues in this repository

<details>
<summary>Screenshot of search</summary>

![изображение](https://user-images.githubusercontent.com/24974508/218675067-8a930d57-d9be-4bd0-a231-123f7e76648d.png)


</details>

**Comment by sashaqwert** [comment] 2023-02-14 08:03
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992

**Closed by sashaqwert** 2023-02-14 08:03 UTC

**Comment by mitchstein443** [comment] 2023-02-15 19:54
!
1) I was not trolling I have this issue with the software. I even posted the screen shots to prove it.
2) it is not a "DUPLICATE" issue, it is an new issue as I tried ALL the solutions in the former closed post and it did not fix the issue.

frankly, just forget about it, the attitude of support on this feed is the pits and I would not depend on any developer with this attitude of simple dismissle of  legit problem.

Thanks for all the hard work to accomplishment nothing. In my day of shareware/freeware we actually responded with usable information and did not just dismiss our users problems. I'll evelop my own and just compete aginst you with it. ridiculous attitude.

**Comment by sashaqwert** [comment] 2023-02-16 05:26
> frankly, just forget about it, the attitude of support on this feed is the pits and I would not depend on any developer with this attitude of simple dismissle of legit problem.\n\nThanks for all the hard work to accomplishment nothing. In my day of shareware/freeware we actually responded with usable information and did not just dismiss our users problems. I'll evelop my own and just compete aginst you with it. ridiculous attitude.

This project is not officially supported by Stas'M.  The task of the designated moderators is simply to close the issue, leaving one issue per version of `termsrv.dll`.

0. Upgrade to Pro via official GVLK key from Microsoft.
1. Uninstall RDP Wrapper and check original RDP. If this not work check your OS.
2. Google --> Windows 10 ServerRdsh (Enterprise for virtual desktops)
3. Change edition to Enterprise for Virtual desktops.

Do not ask keys here.
