### ISSUE TITLE
22000.832 Not Supported

### ISSUE THREAD

**Issue by nenka01** [stascorp/rdpwrap#1949] opened 2022-08-02 11:18 UTC
Please Help

**Comment by sashaqwert** [comment] 2022-08-02 11:21
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by nenka01** [comment] 2022-08-02 11:36
> 
![Send](https://user-images.githubusercontent.com/84552503/182365344-6ad8b07e-a54b-4a86-996d-badde1db409f.png)
https://www23.zippyshare.com/v/9atUFElB/file.html
this the screenshoot and the termsrv.dll
Sorry, my telegram had banned i will join next time to telegram group, please help

**Comment by sashaqwert** [comment] 2022-08-02 12:40
One `termsrv.dll` version = one opened issue. --> duplicate of https://github.com/stascorp/rdpwrap/issues/1868

> Not supported

In your screenshot - Fully supported. `termsrv.dll` version != Windows version!!!

**Closed as not planned by sashaqwert** 2022-08-02 12:40 UTC

**Comment by nenka01** [comment] 2022-08-02 14:32
> One `termsrv.dll` version = one opened issue. --> duplicate of https://github.com/stascorp/rdpwrap/issues/1868
> 
> > Not supported
> 
> In your screenshot - Fully supported. `termsrv.dll` version != Windows version!!!

R I have to change my termsrv.dll version?

**Comment by sashaqwert** [comment] 2022-08-02 15:21
> I have to change my termsrv.dll version?

RDP Wrapper requires the original version of `termsrv.dll` to work properly (it usually doesn't work with a patched DLL).

You can get the original back with `sfc /scannow` command.

**Comment by nenka01** [comment] 2022-08-02 15:48
The dll version is original version, but when I remote then always show you have been disconnect because another connection was made to the remote computer, though me had set limit 99999

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sashaqwert** [comment] 2022-08-02 16:20
> The dll version is original version, but when I remote then always show you have been disconnect because another connection was made to the remote computer, though me had set limit 99999

No ideas. You can ask in Telegram chat.

---------------------

Also you can try Windows 10/11 Enterprise multi-session.

Before the transition, you need to remove the RDP Wrapper.

```
slmgr.vbs /ipk CPWHC-NT2C7-VYW78-DHDB2-PG3GK
```

Also you can create ISO via [UUP dump](https://uupdump.net/).

**Comment by nenka01** [comment] 2022-08-03 05:42
> > The dll version is original version, but when I remote then always show you have been disconnect because another connection was made to the remote computer, though me had set limit 99999
> 
> No ideas. You can ask in Telegram chat.
> 
> ---------------------
> 
> Also you can try Windows 10/11 Enterprise multi-session.
> 
> Before the transition, you need to remove the RDP Wrapper.
> 
> ```
> slmgr.vbs /ipk CPWHC-NT2C7-VYW78-DHDB2-PG3GK
> ```
> 
> Also you can create ISO via [UUP dump](https://uupdump.net/).

My windows is windows 11 home single language, version 22000.832

**Comment by sashaqwert** [comment] 2022-08-03 06:11
To use RDP without problems:

1. Open CMD as Administrator
2. Enter command

```
slmgr.vbs /skms kms.loli.best
```

3. Change your product key to Enterprise via Settings App (System -->. Activation --> change product key)

```
NPPR9-FWDCX-D2C8J-H872K-2YT43
```

4. Reboot
5. Check RDP Wrapper again.

**Comment by nenka01** [comment] 2022-08-14 09:44
> To use RDP without problems:
> 
> 1. Open CMD as Administrator
> 2. Enter command
> 
> ```
> slmgr.vbs /skms kms.loli.best
> ```
> 
> 3. Change your product key to Enterprise via Settings App (System -->. Activation --> change product key)
> 
> ```
> NPPR9-FWDCX-D2C8J-H872K-2YT43
> ```
> 
> 4. Reboot
> 5. Check RDP Wrapper again.

Unable to upgrade sir, 0x80073701
