### ISSUE TITLE
Listener state: not supported

### ISSUE THREAD

**Issue by de-don** [stascorp/rdpwrap#356] opened 2017-11-27 03:07 UTC
Hi, I have Windows 10 Insider Preview 17025.1000 (rs_prerelease), and rdp wrapper not work :(

![image](https://user-images.githubusercontent.com/14067329/33248991-7738e0a8-d35a-11e7-9385-abcbf2c27e55.png)

I try update, reinstall, but rdp not woking(

**Comment by binarymaster** [comment] 2017-11-27 09:58
Duplicate of #339.

**Closed by binarymaster** 2017-11-27 09:58 UTC
