### ISSUE TITLE
10.019041.4239 Not Supported

### ISSUE THREAD

**Issue by tetas26** [stascorp/rdpwrap#2551] opened 2024-04-10 05:24 UTC
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/14927600/termsrv.zip)

**Comment by loyejaotdiqr47123** [comment] 2024-04-10 12:40
Duplicate of #2529

**Comment by sashaqwert** [comment] 2024-04-12 04:56
Duplicate of https://github.com/stascorp/rdpwrap/issues/2529

**Closed as not planned by sashaqwert** 2024-04-12 04:56 UTC
