### ISSUE TITLE
10.0.22000.1817 Not Supported

### ISSUE THREAD

**Issue by maxshic** [stascorp/rdpwrap#2184] opened 2023-04-28 01:46 UTC

**Comment by sashaqwert** [comment] 2023-04-28 05:07
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by sashaqwert** [comment] 2023-04-28 05:09
See https://github.com/sebaxakerhtc/rdpwrap.ini/issues/229#issuecomment-1525971437

--> Duplicate

**Comment by sashaqwert** [comment] 2023-04-28 05:09
Duplicate of https://github.com/stascorp/rdpwrap/issues/2126

**Closed as not planned by sashaqwert** 2023-04-28 05:09 UTC
Labels: duplicate
