### ISSUE TITLE
[NOT SUPPORTED]

### ISSUE THREAD

**Issue by zenusop** [stascorp/rdpwrap#1890] opened 2022-06-06 23:13 UTC
I need the ini file for 21H2 22000.708

**Comment by mingxin505** [comment] 2022-06-07 03:00
I need the ini file for 10.0.10.0.19041.1741

**Comment by sashaqwert** [comment] 2022-06-07 06:17
Duplicate of https://github.com/stascorp/rdpwrap/issues/1868

**Comment by sebaxakerhtc** [comment] 2022-06-07 06:55
> Duplicate of #1868

**Closed as completed by sebaxakerhtc** 2022-06-07 06:55 UTC
