### ISSUE TITLE
Not listenning [18362.592]

### ISSUE THREAD

**Issue by matrixrap** [stascorp/rdpwrap#979] opened 2020-02-04 23:25 UTC
Windows 10 Home
1903
18362.592
Help me please,  I already installed everything, changed rdpwrap.ini for my device. I wasted about 40 hours to repair it. 

What can you advise?
a matter of life and death

**Comment by matrixrap** [comment] 2020-02-05 01:38
UPD: I installed another ini. It became fully support but not listening also.......

**Comment by JaJe92** [comment] 2020-02-05 15:03
I have the same issue and hope for a new fix to come. Win 10 - 1903

**Comment by hamzahassan52** [comment] 2020-02-07 19:03
I have same issue

**Comment by gerardoparedes** [comment] 2020-02-08 18:17
on the same boat here, shows all the green lights lit, but not working

**Comment by asmtron** [comment] 2020-02-12 07:39
please upload termsrv.dll 18362.592

**Comment by gerardoparedes** [comment] 2020-02-16 15:12
here is my termsrv.dll for windows 18362.592 10 pro edition
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/4209964/termsrv.zip)

**Comment by sebaxakerhtc** [comment] 2022-06-20 10:23
Duplicate of https://github.com/stascorp/rdpwrap/issues/871

**Closed as completed by sebaxakerhtc** 2022-06-20 10:23 UTC
