### ISSUE TITLE
19042.804

### ISSUE THREAD

**Issue by Melnick704** [stascorp/rdpwrap#1323] opened 2021-02-10 05:59 UTC
It's work for 19042.804
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/5956122/rdpwrap.zip)

**Comment by i2sly** [comment] 2021-02-10 06:39
Does this only need to go in the "C:\Program Files\RDP Wrapper" folder?  I updated it there and rebooted and still not working for me

**Comment by latchuk** [comment] 2021-02-10 20:30
Thank's @Melnick704 !
It's working like a charm.

**Comment by FMYY** [comment] 2021-02-12 07:03
Change C:\Program Files\RDP Wrapper

Ithanks OK  Thanks

**Comment by XelaUA** [comment] 2021-02-12 09:38
what u mean 19042.804? we have 19041.804 and this .ini dont work for us

**Comment by Melnick704** [comment] 2021-02-12 10:56
> what u mean 19042.804? we have 19041.804 and this .ini dont work for us

I have 19042, no 19041

**Comment by FMYY** [comment] 2021-02-12 13:16
My PC is 19042. user Melnick704's file it is OK.  
Change C:\Program Files\RDP Wrapper

Thanks for  Melnick704

**Comment by tisc0** [comment] 2021-02-13 10:00
Hi,
No "19042.804" entry in your file @Melnick704 , normal ? 
If it doesn't work, I lose accces to the remote machine.

**Comment by teoformartel** [comment] 2021-02-13 10:03
Works for 19042.804 (20H2)
I've updated using rdp only

**Comment by Melnick704** [comment] 2021-02-13 10:11
But it work 🤷‍♂️

**Comment by Melnick704** [comment] 2021-02-13 10:12
But it work 🤷‍♂️> Hi,
> 
> No "19042.804" entry in your file @Melnick704 , normal ? 
> 
> If it doesn't work, I lose accces to the remote machine.
> 
>

**Comment by luizamorimsouza** [comment] 2021-02-13 18:20
Thank's @Melnick704 worked for me too. 19042.804 (20H2)

**Comment by Andrea2099** [comment] 2021-02-14 20:43
It works for me. thank you!

**Comment by Zykov-Alexey** [comment] 2021-02-15 08:56
It works for me. thank you!

**Comment by plmuthiah** [comment] 2021-02-15 20:01
it doesn't work for me :( ...  winver - 19042.804 , i loose access to remote machine

**Comment by master-yun-yun** [comment] 2021-02-16 05:59
> It's work for 19042.804
> [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/5956122/rdpwrap.zip)

can you upload your termsrv.dll file?
thx

**Comment by plmuthiah** [comment] 2021-02-16 08:06
PFA
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/5987008/termsrv.zip)

**Comment by XelaUA** [comment] 2021-02-16 09:02
> what u mean 19042.804? we have 19041.804 and this .ini dont work for us

all good, need to be copied with administrator rights

**Comment by BALAHLOP** [comment] 2021-02-16 14:20
I replaced the file, and status went to fully supported but i can't connect to computer! what should i do???

**Comment by BALAHLOP** [comment] 2021-02-17 06:51
I am sorry, everything is working, i forget to set number of connections... :)

**Comment by regissg** [comment] 2021-02-17 08:24
@BALAHLOP where do you set the number of connections ?

**Comment by BALAHLOP** [comment] 2021-02-17 08:47
@regissg run gpedit.msc, then choose Computer Configuration -> Administrative Templates -> Windows Components ->Remote Desktop Services ->Remote Desktop Session Host -> Connections-> Limit number of connections, set conecctions to 999999, restart computer....

![image](https://user-images.githubusercontent.com/79150938/108178722-6fd9f280-710d-11eb-8129-4e6615170e97.png)

**Comment by regissg** [comment] 2021-02-17 09:01
@BALAHLOP thanks, it works. That was a rather hidden feature...

**Comment by IcemanEA** [comment] 2021-02-17 21:15
Help me plz! This is my first attempt at using the program. Windows version Windows 10 Pro 20H2 19042.804. Install RDP Wrapper. Use ini file from Melnick704, all os status green color, but work only one connection. What am I doing wrong? 
![Снимок экрана 2021-02-18 в 00 15 34](https://user-images.githubusercontent.com/20644248/108269017-72286500-717e-11eb-9d94-5bc3ce22bbc0.png)

**Comment by BALAHLOP** [comment] 2021-02-17 21:33
@IcemanEA  run gpedit.msc, then choose Computer Configuration -> Administrative Templates -> Windows Components ->Remote Desktop Services ->Remote Desktop Session Host -> Connections-> Limit number of connections, set conecctions to 999999, restart computer....

**Comment by IcemanEA** [comment] 2021-02-17 21:39
> @IcemanEA run gpedit.msc, then choose Computer Configuration -> Administrative Templates -> Windows Components ->Remote Desktop Services ->Remote Desktop Session Host -> Connections-> Limit number of connections, set conecctions to 999999, restart computer....

Yes, I did it, but it doesn't help

**Comment by XXcage** [comment] 2021-02-21 23:33
![image](https://user-images.githubusercontent.com/79426486/108642489-fe53c880-74ad-11eb-9cb8-29078ac02556.png)

**Comment by 0sdelta0** [comment] 2021-03-10 19:35
> It's work for 19042.804
> [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/5956122/rdpwrap.zip)

Thanks a lot! It's working fine

![image](https://user-images.githubusercontent.com/63894224/110686935-92f44100-81a5-11eb-93a0-bd64920bdf04.png)

**Comment by qbano36** [comment] 2021-03-11 13:56
Thanks a lot, worked for me too OS Build 10.0.19042.867 (20H2)

**Comment by gohellp** [comment] 2021-06-21 21:10
> [termsrv.zip](https://github.com/stascorp/rdpwrap/files/5987008/termsrv.zip)

Thx! I replaced this one .dll and everything worked

**Comment by DmitriyPankratov** [comment] 2021-09-10 09:26
> It's work for 19042.804
> [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/5956122/rdpwrap.zip)

It's work for 19041.789

**Comment by sebaxakerhtc** [comment] 2022-06-20 12:55
Duplicate of https://github.com/stascorp/rdpwrap/issues/1317

**Closed as completed by sebaxakerhtc** 2022-06-20 12:55 UTC
