### ISSUE TITLE
Windows 10  21H2 10.0.19041.2075 support missing

### ISSUE THREAD

**Issue by swordXwind** [stascorp/rdpwrap#2129] opened 2023-02-28 07:08 UTC
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/10847422/termsrv.zip)

**Comment by swordXwind** [comment] 2023-02-28 07:09
Thank you for support and help.

**Comment by loyejaotdiqr47123** [comment] 2023-02-28 10:32
[10.0.19041.2075]
SingleUserPatch.x64=1
SingleUserOffset.x64=F303
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1F2A5
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=932F1
LocalOnlyCode.x64=jmpshort
SLInitHook.x64=1
SLInitOffset.x64=2877C
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.19041.2075-SLInit]
bServerSku.x64=125088
bRemoteConnAllowed.x64=12509C
bFUSEnabled.x64=1250A8
bAppServerAllowed.x64=125094
bMultimonAllowed.x64=1250A0
lMaxUserSessions.x64=12508C
ulMaxDebugSessions.x64=1250A4
bInitialized.x64=125084

**Comment by sashaqwert** [comment] 2023-02-28 14:57
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992

**Closed as not planned by sashaqwert** 2023-02-28 14:57 UTC
Labels: duplicate
