### ISSUE TITLE
Random Crashes ...HELP!

### ISSUE THREAD

**Issue by Zatanus** [stascorp/rdpwrap#2056] opened 2022-11-28 11:53 UTC
Hi.
I have this version apparently running OK.

![MAD-RDPw162](https://user-images.githubusercontent.com/119299362/204260176-b9bc7dd1-4264-4751-b2df-f194e13093e8.PNG)

THE PC:
Installed v1.6.2 in RDP Wrapper folder in C:\Program Files
autoupdate.bat working OK  (with Task Scheduled for startups).
Windows 10 PRO 21H2  19044.1766
CPU AMD Ryzen3 3300 (8 threads) 3.80 Mhz
32 GB DDR4 RAM 3200 Mhz
Nvidia GeForce GT730 4GB vRAM
AnyDesk is installed (but uninstall it not change anything).
Some Acronis backup software running.
All for emails, MS-Excel and MS-Access tasks, printing, etc.

With 1 or 2 additional sessions works OK  (some 1080p, 2K or 4K).
With more than 3 sessions randomly crashes, closes. Sometimes only Windows Clients closes and session in the main computer is still open and running, and the solution is reconnect.
Another times, sessions seem freeze and the only solution is to close client, and reopen, finding all work lost. Most times totally crashes, client closes, and any work in programs was lost at reopen.

Most connections are LAN and some ones are Zero-Tier VPN. This ones fail less.
Sometimes at login passwords are well entered but not accepted, and need to be reentered.

Another similar PC with more powerful hardware (32 threads, 8GB vRAM) works with same version, supporting without problems more than 8 sessions mostly 1080p (no ZeroTier VPN in this one).

Can anyone please help?

**Comment by sashaqwert** [comment] 2022-11-28 18:26
Are you using original `termsrv.dll`?

Try `sfc /scannow`

**Comment by Zatanus** [comment] 2022-11-28 19:31
> Are you using original `termsrv.dll`?
> 
> Try `sfc /scannow`


I have not knowingly made any modifications or manually applied any patches to the termsrv.dll file.
Nothing intentional. How could I confirm that it is the original?

The sfc /scannow thing was the first thing I did when the problems arose. This is a fresh Windows 10 installation, on new hardware. Previously there was a Windows 7 pro with rdp wrapper on that PC as well, working for years without any problem. This is a fresh new install of Windows 10, with these problems from the start, from 5 months or so ago.

Thanx for reply.

**Comment by sashaqwert** [comment] 2022-11-29 06:20
> I have not knowingly made any modifications or manually applied any patches to the termsrv.dll file.
Nothing intentional. How could I confirm that it is the original?

Checking the integrity of system files (`sfc /scannow`) is usually sufficient for this.

>  This is a fresh new install of Windows 10, with these problems from the start, from 5 months or so ago.

Perhaps the problems are offsets, but I doubt that in a few months no one else noticed them.

If you want to make sure that the problem is not with the system, but with the RDP Wrapper, then look at the ServerRdsh (Enterprise for Virtual Desktops) edition. All the information is on Google and on the My Digital Life forum. (Do not ask about this here)

**Comment by sashaqwert** [comment] 2022-11-29 08:01
For a better clarification of the reason, it is better to ask in the [Telegram chat](https://t.me/rdpwrap) of the project or in the [Discoed server](https://discord.gg/N27yFftWP3) of the offset developer (sebaxakerhtc)

**Comment by sashaqwert** [comment] 2022-11-29 17:50
Closed as answered. The causes of random crashes are currently unknown.

**Closed as completed by sashaqwert** 2022-11-29 17:50 UTC

**Comment by Zatanus** [comment] 2023-02-14 23:22
> Closed as answered. The causes of random crashes are currently unknown.

I found the solution.

The solution was in the gpedit.msc, disabling the WDDM driver for remote sessions:

https://support.skylinesoft.com/hc/en-us/articles/4408342643986-Direct3D-Errors-When-Using-Remote-Desktop-Connection
