### ISSUE TITLE
10.0.17763.5830 Not Supported

### ISSUE THREAD

**Issue by xausky** [stascorp/rdpwrap#3335] opened 2024-11-09 12:47 UTC
![image](https://github.com/user-attachments/assets/32d78d64-67ab-4651-8df8-ccb404552212)

[termsrv.zip](https://github.com/user-attachments/files/17687117/termsrv.zip)

**Comment by binarymaster** [comment] 2024-11-09 14:50
Duplicate of https://github.com/stascorp/rdpwrap/issues/2622.

**Closed as not planned by binarymaster** 2024-11-09 14:50 UTC
Labels: duplicate
