### ISSUE TITLE
RDP Wrapper broke by a Windows update

### ISSUE THREAD

**Issue by sretlow** [stascorp/rdpwrap#158] opened 2016-09-14 19:17 UTC
Today RDP Wrapper didn't work anymore. I knew from a time ago that certain Windows Updates broke down RDP Wrapper. And this morning my Windows 10 was updated. So I did a system reset to yesterday. It worked. So there is an update which breaks down RDP Wrapper. I don't know which update package it is. 

1. Can I disable Windows updates? How?
2. Does anybode know which update is causing problems?
3. Or...will there be an update from RDP Wrapper
4. Is there an other possibility to create multi login?

**Comment by binarymaster** [comment] 2016-09-14 19:30
Duplicate of #157 

It's update KB3185614

**Closed by binarymaster** 2016-09-14 19:30 UTC
Labels: duplicate
