### ISSUE TITLE
Server 2019 Standard Not supported 10.0.17763.4492 Help please

### ISSUE THREAD

**Issue by syfllh** [stascorp/rdpwrap#2376] opened 2023-10-22 13:56 UTC
![sss](https://github.com/stascorp/rdpwrap/assets/78797525/4a1cfe30-2969-4f7f-ab76-5a41d5ae8249)

**Comment by sashaqwert** [comment] 2023-10-22 17:38
Duplicate of https://github.com/stascorp/rdpwrap/issues/2303

**Closed as not planned by sashaqwert** 2023-10-22 17:38 UTC
Labels: duplicate
