### ISSUE TITLE
Windows 11 10.0.22000.1641 not supported

### ISSUE THREAD

**Issue by Maricolin** [stascorp/rdpwrap#2245] opened 2023-06-13 03:34 UTC
![image](https://github.com/stascorp/rdpwrap/assets/88125929/1e71f7ce-59ab-495c-8749-531604eb0e00)

**Comment by sashaqwert** [comment] 2023-06-14 08:17
Duplicate of https://github.com/stascorp/rdpwrap/issues/2126

**Closed as not planned by sashaqwert** 2023-06-14 08:17 UTC
Labels: duplicate
