### ISSUE TITLE
RDP 10.0.22621.3672 Windows 11 Pro Fully Supported Not Working

### ISSUE THREAD

**Issue by kevincp061** [stascorp/rdpwrap#3231] opened 2024-07-16 22:35 UTC
![image](https://github.com/user-attachments/assets/b4f540d9-5e2b-48d7-9cc9-200446d926a4)

my rdp check is completely green. i used tailscale as a portforward to make rdp work until i woke up in the morning and its suddenly not working. it lasted less than 24 hours.

when i use rdp check it completely loads in, so i know the set up is correct. I cannot login to my router configuration as the admin password doesnt work for some reason.  I am also unable to use port 3389 because it says session already in use ( not really sure thats an issue as i was able to use port 3388 anyway when it worked), i have checked for apps using port 3389 nothing comes up. resetting term service doesnt help, disabling firewall and antivirus changes nothing, i have seperated actual rdp from the rest as the issue solution said in github did nothing. can anyone help me in solving this?

**Comment by loyejaotdiqr47123** [comment] 2024-07-17 13:09
Try reboot？

**Comment by kevincp061** [comment] 2024-07-18 00:50
> Try reboot？

this been going on for days and days reboot doesnt help

**Comment by loyejaotdiqr47123** [comment] 2024-07-18 02:15
Try run net start umrdpservice

**Comment by kevincp061** [comment] 2024-07-18 04:02
> Try run net start umrdpservice

nothing changes

**Comment by adream100** [comment] 2024-07-18 23:15
Check your registry subkey: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp\PortNumber, change it to a new value, such as 33890 or 12345. save and reboot.

**Comment by loyejaotdiqr47123** [comment] 2024-07-19 02:29
> ![image](https://private-user-images.githubusercontent.com/175755352/349293515-b4f540d9-5e2b-48d7-9cc9-200446d926a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTU3ODEsIm5iZiI6MTcyMTM1NTQ4MSwicGF0aCI6Ii8xNzU3NTUzNTIvMzQ5MjkzNTE1LWI0ZjU0MGQ5LTVlMmItNDhkNy05Y2M5LTIwMDQ0NmQ5MjZhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOVQwMjE4MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MGNkNGNhMzI1NzJiNDZhOTE2NTE4MmEzZWJhZWI4NjYxNTE1NGE0ODJiZDZjZjdkYjI4OTIyMWQ3M2U3NDIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g_bnqjwYXyOvykkNZoArOUPUVQVbe5TC_oGQNeoiGSY)
> 
> 我使用 tailscale 作为端口转发，使 rdp 正常工作，直到早上醒来，它突然失效了。
> 
> 当我使用 rdp 检查时，它能完全加载，所以我知道设置是正确的。我无法登录路由器配置，因为管理员密码不知为何不起作用。我也无法使用 3389 端口，因为它说会话已在使用中（我不太确定这是否是个问题，因为我可以使用 3388 端口，反正它也能用），我检查了使用 3389 端口的应用程序，但什么也没显示出来。

Check your firewall?
Try run
```
netsh advfirewall firewall add rule name="Remote Desktop" dir=in protocol=tcp localport=3389 profile=any action=allow
netsh advfirewall firewall add rule name="Remote Desktop" dir=in protocol=udp localport=3389 profile=any action=allow
```

**Comment by kevincp061** [comment] 2024-07-23 06:13
none of this is working but thanks for trying

**Comment by antmarortega** [comment] 2024-07-24 15:51
Having the same problem on Windows 11 Pro x64 (NL=Dutch) up to date till Wednesday 24.07.2024.
For test purposes, I am running this Windows 11 Pro in a VmWare Workstation Pro.

I am using the **2024-07-17** rdpwrap.ini by sebaxakerhtc
which has the sections **[10.0.22621.3672]** and **[10.0.22621.3672-SLInit]**
but maybe some patch pointers are off.

Does anyone has the above version 10.0.22621.3672 working ?

**Comment by antmarortega** [comment] 2024-07-25 08:31
![image](https://github.com/user-attachments/assets/484df94a-6d96-47bf-9fdd-bbcfb4796b85)
[termsrv Win11 (v10.0.22621.3672).zip](https://github.com/user-attachments/files/16430639/termsrv.Win11.v10.0.22621.3672.zip)


Added **RDConf.exe** screenshot and the **termsrv.dll** found in my c:\windows\system32
**### ZIP UPDATED 30/7/2024 because termsrv in older ZIP somehow as 0 bytes!**

**Comment by loyejaotdiqr47123** [comment] 2024-07-26 06:48
> ![image](https://private-user-images.githubusercontent.com/120402505/352024856-484df94a-6d96-47bf-9fdd-bbcfb4796b85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NzYzNTYsIm5iZiI6MTcyMTk3NjA1NiwicGF0aCI6Ii8xMjA0MDI1MDUvMzUyMDI0ODU2LTQ4NGRmOTRhLTZkOTYtNDdiZi05ZmRkLWJiY2ZiNDc5NmI4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQwNjQwNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jN2IzOTA0ZDgwNTI5ZDdjNzRkMjlmMTM1MjQ5ZmJhMWEyMDgwNGU1YzA4Y2NlYWE3YjY3YzdjNTQxNzljMzdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ET4iJ1ZfnMPsR90n4uxTU31ppXuSdhKHZjOcSD8T-0E) [termsrv_Win11_10.0.22621.3672.zip](https://github.com/user-attachments/files/16372978/termsrv_Win11_10.0.22621.3672.zip)
> 
> Added **RDConf.exe** screenshot and the **termsrv.dll** found in my c:\windows\system32

![image](https://github.com/user-attachments/assets/c75e9f9a-d4d8-438a-bab1-f27fedc9e132)

Your termsrv.dll file size is 0.

**Comment by loyejaotdiqr47123** [comment] 2024-07-26 06:54
> ![image](https://private-user-images.githubusercontent.com/120402505/352024856-484df94a-6d96-47bf-9fdd-bbcfb4796b85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NzYzNTYsIm5iZiI6MTcyMTk3NjA1NiwicGF0aCI6Ii8xMjA0MDI1MDUvMzUyMDI0ODU2LTQ4NGRmOTRhLTZkOTYtNDdiZi05ZmRkLWJiY2ZiNDc5NmI4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQwNjQwNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jN2IzOTA0ZDgwNTI5ZDdjNzRkMjlmMTM1MjQ5ZmJhMWEyMDgwNGU1YzA4Y2NlYWE3YjY3YzdjNTQxNzljMzdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ET4iJ1ZfnMPsR90n4uxTU31ppXuSdhKHZjOcSD8T-0E) [termsrv_Win11_10.0.22621.3672.zip](https://github.com/user-attachments/files/16372978/termsrv_Win11_10.0.22621.3672.zip)
> 
> Added **RDConf.exe** screenshot and the **termsrv.dll** found in my c:\windows\system32

@antmarortega 
![image](https://github.com/user-attachments/assets/b6670abf-06ae-4d6c-b1a0-bb4127d9dea9)

Your termsrv size is 0.

**Comment by binarymaster** [comment] 2024-07-26 07:01
Duplicate of https://github.com/stascorp/rdpwrap/issues/2833.

GitHub issues is only for reporting bugs, not for discussing struggles. Contact Telegram support group instead.

**Closed as not planned by binarymaster** 2024-07-26 07:01 UTC
Labels: duplicate

**Comment by antmarortega** [comment] 2024-07-30 16:15
@loyejaotdiqr47123 - Somehow whwn adding the termsrv.dll to the zip the size was 0 bytes. Don't know what happend.
                                 I updated the ZIP-file with the correct termsrv.dll now!

@binarymaster - This seems to be a bug in the wrapper.ini or termsrv.dll changed so the RDWrap won't work anymore.
                            Tested on WIndows 10 and RDPWrap + rdpwrap.ini is working.
                            So for Win11 imho there is a bug because "the same" installation on Win 10 works.
                            Just my 2 cents ;-)
