### ISSUE TITLE
10.0.22631.4460 is supported

### ISSUE THREAD

**Issue by patrickwoo33** [stascorp/rdpwrap#3372] opened 2024-12-03 05:24 UTC
Use CMD, type "winver" to check your window patch version.
If the version is 23H2 (10.0.22631.4460), you can add the below in the rdpwrap.ini file.

[10.0.22631.4460]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=A3021
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=C893
SingleUserCode.x64=mov_eax_1_nop_2
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1C755
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=2FF60
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.22631.4460-SLInit]
bInitialized.x64      =131FA8
bServerSku.x64        =131FAC
lMaxUserSessions.x64  =131FB0
bAppServerAllowed.x64 =131FB4
bRemoteConnAllowed.x64=131FC0
bMultimonAllowed.x64  =131FC4
ulMaxDebugSessions.x64=131FCC
bFUSEnabled.x64       =131FD0

**Comment by binarymaster** [comment] 2024-12-03 15:48
Invalid and duplicate of #3366.

Version numbers in the INI file are based on termsrv.dll version, not system version.

**Closed as not planned by binarymaster** 2024-12-03 15:48 UTC
Labels: duplicate

**Comment by JVMM25** [comment] 2024-12-11 23:39
Requiero el código para la versión Windows 11 23H2 (Compilación SO 22631.4602) 
![1](https://github.com/user-attachments/assets/fe211d6c-dd1a-4d0f-b660-d4749ac6a334)
![2](https://github.com/user-attachments/assets/83e358d6-7cf9-42d3-a898-bfaa8c9d719b)
