### ISSUE TITLE
Virus Warning

### ISSUE THREAD

**Issue by BigMikeC** [stascorp/rdpwrap#379] opened 2017-12-28 15:09 UTC
I know its been mentioned before and i have read the discussions here why this is happening but the Virus alert blocks are now much worse with Version 1.6.2. It is now 21 alerts (rising from the previous 15) on VirusTotal. Both Google Chrome and Firefox are specifically blocking the download of both the MSI and ZIP files and with Github warning that IE will soon not be supported, we are rapidly going to lose the capacity to get RDP Wrap to work. Kaspersky, Malwarebytes and many more of the 21 packages actually name the virus software that they think is present in the code. There must be something that you can do to calm down their fears?

**Comment by binarymaster** [comment] 2017-12-28 15:26
They would fear much more if they see issue with that name...

Duplicate of #277 (let's continue discussing there).

**Closed by binarymaster** 2017-12-28 15:26 UTC
