### ISSUE TITLE
Terminal Services version: 10.0.18362.657 not supported.zip

### ISSUE THREAD

**Issue by egmsystems** [stascorp/rdpwrap#1075] opened 2020-05-02 19:58 UTC
RDP Wrapper Library v1.6.2
Installer v2.5
Copyright (C) Stas'M Corp. 2017

[*] Notice to user:
  - By using all or any portion of this software, you are agreeing
  to be bound by all the terms and conditions of the license agreement.
  - To read the license agreement, run the installer with -l parameter.
  - If you do not agree to any terms of the license agreement,
  do not use the software.
[*] Installing...
[*] Terminal Services version: 10.0.18362.657
[-] This version of Terminal Services is not supported.
Try running "update.bat" or "RDPWInst -w" to download latest INI file.
If it doesn't help, send your termsrv.dll to project developer for support.
[+] TermService found (pid 3364).
[*] No shared services found.
[*] Extracting files...
[+] Folder created: C:\Program Files\RDP Wrapper\
[+] Extracted config -> C:\Program Files\RDP Wrapper\rdpwrap.ini
[+] Extracted rdpw64 -> C:\Program Files\RDP Wrapper\rdpwrap.dll
[*] Configuring service library...
[*] Checking dependencies...
[*] Checking CertPropSvc...
[*] Checking SessionEnv...
[*] Terminating service...
[*] Starting TermService...
[-] StartService error (code 1056).
[*] Configuring registry...
[*] Configuring firewall...
Aceptar

[+] Successfully installed.
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/4568672/termsrv.zip)

**Comment by affinityv** [comment] 2020-05-03 05:53
https://github.com/stascorp/rdpwrap/issues/1022#issuecomment-596437997

**Comment by sebaxakerhtc** [comment] 2022-06-20 10:36
Duplicate of https://github.com/stascorp/rdpwrap/issues/983

**Closed as completed by sebaxakerhtc** 2022-06-20 10:36 UTC
