### ISSUE TITLE
Cannot enable remote desktop in Windows 10 System Settings

### ISSUE THREAD

**Issue by alu890** [stascorp/rdpwrap#1117] opened 2020-07-11 07:51 UTC
Hello, I have installed RDP wrapper and the RDPCheck works -

<img width="305" alt="rdpwrapperpic" src="https://user-images.githubusercontent.com/68143626/87219488-80deac00-c353-11ea-970c-08376f3c9c75.png">

So now I want to log into the computer I have installed RDP wrapper on from a laptop but when I go to remote desktop settings to get the computer name it is not available because I am on Windows 10 Home, is there anything else I need to do?

<img width="610" alt="rp" src="https://user-images.githubusercontent.com/68143626/87219499-a4a1f200-c353-11ea-8ce9-0e0a61a42122.png">

**Comment by robbak** [comment] 2020-07-11 10:50
That is correct. rdpwrapper enables it by adjusting how the services are used. The windows settings doesn't know anything about that, and will continue to say it isn't available. Try to connect to your computer anyway, and it should work. 

You configure rdp using rdpcheck.exe, not the windows settings tools. You generally connect using the IP address, but it might well work using the computer name, which you can obtain from other places.

**Comment by alu890** [comment] 2020-07-12 19:40
OK, when I type my computer name into the laptop that I am trying to use for the remote connection it says that the computer name cannot be found. I have also tried using the IPv4 address of my computer and the laptop goes to a log in screen that I would see when I turn the laptop on, rather than the computer, almost as if it is trying to connect to itself.

**Comment by travismailsa** [comment] 2020-07-20 10:54
Have you allowed port 3389 on your firewall?

**Comment by sebaxakerhtc** [comment] 2022-06-20 11:08
Duplicate of https://github.com/stascorp/rdpwrap/issues/1083

**Closed as completed by sebaxakerhtc** 2022-06-20 11:08 UTC
