### ISSUE TITLE
replacing RDPWrap.ini is not working

### ISSUE THREAD

**Issue by pmirza** [stascorp/rdpwrap#1544] opened 2021-09-30 11:12 UTC
Hi

As per the article on website http://woshub.com/how-to-allow-multiple-rdp-sessions-in-windows-10/ I tried to follow the step to enable my PC to have multiple remote sessions. Actually, I just need 1 RDP while one user continues to work on the PC.

I tried replacing RDPWrap.ini file (https://github.com/stascorp/rdpwrap/files/3863419/rdpwrap_10.0.18363.476_1909.zip) and restarting the termservice, its not working. When I run RDPConf, It still shows **[not supported]**. I have Windows 10 Pro version 21H1. 

What do I need to do now?
![image](https://user-images.githubusercontent.com/55858755/135445526-fe0040c7-5728-4fdd-82cc-c462d414ff4c.png)

Should I try change the termsrv.dll as explained in the article?

Thanks,
Parvez

**Comment by zekecarter** [comment] 2021-10-01 15:04
> Hi
> 
> As per the article on website http://woshub.com/how-to-allow-multiple-rdp-sessions-in-windows-10/ I tried to follow the step to enable my PC to have multiple remote sessions. Actually, I just need 1 RDP while one user continues to work on the PC.
> 
> I tried replacing RDPWrap.ini file (https://github.com/stascorp/rdpwrap/files/3863419/rdpwrap_10.0.18363.476_1909.zip) and restarting the termservice, its not working. When I run RDPConf, It still shows **[not supported]**. I have Windows 10 Pro version 21H1.
> 
> What do I need to do now? ![image](https://user-images.githubusercontent.com/55858755/135445526-fe0040c7-5728-4fdd-82cc-c462d414ff4c.png)
> 
> Should I try change the termsrv.dll as explained in the article?
> 
> Thanks, Parvez

[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/7268166/rdpwrap.zip) try this one, remember to stop the remote desktop service before replacing it otherwise you will cause a failure at login time

**Comment by zekecarter** [comment] 2021-10-01 15:06
![tested](https://user-images.githubusercontent.com/83554130/135643556-78a78f5f-88e9-4631-85cd-1861f2e886af.png)

**Comment by pmirza** [comment] 2021-10-01 22:09
> [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/7268166/rdpwrap.zip) try this one, remember to stop the remote desktop service before replacing it otherwise you will cause a failure at login time

I will try this later to see if this solutions works. For now I have changed the termsrv.dll as suggested and it is working.

Thanks so much for your response.

**Comment by rfarkv** [comment] 2021-10-07 23:54
> > Hi
> > As per the article on website http://woshub.com/how-to-allow-multiple-rdp-sessions-in-windows-10/ I tried to follow the step to enable my PC to have multiple remote sessions. Actually, I just need 1 RDP while one user continues to work on the PC.
> > I tried replacing RDPWrap.ini file (https://github.com/stascorp/rdpwrap/files/3863419/rdpwrap_10.0.18363.476_1909.zip) and restarting the termservice, its not working. When I run RDPConf, It still shows **[not supported]**. I have Windows 10 Pro version 21H1.
> > What do I need to do now? ![image](https://user-images.githubusercontent.com/55858755/135445526-fe0040c7-5728-4fdd-82cc-c462d414ff4c.png)
> > Should I try change the termsrv.dll as explained in the article?
> > Thanks, Parvez
> 
> [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/7268166/rdpwrap.zip) try this one, remember to stop the remote desktop service before replacing it otherwise you will cause a failure at login time

This one worked for me too. 19043.1110.
Thanks!!

**Comment by sebaxakerhtc** [comment] 2021-10-27 11:50
Duplicate of https://github.com/stascorp/rdpwrap/issues/1509

**Closed as completed by sebaxakerhtc** 2021-10-27 11:50 UTC
