### ISSUE TITLE
Windows 22H2 (19045.2913) No support RDPWrapper

### ISSUE THREAD

**Issue by Mhalvarez75** [stascorp/rdpwrap#2183] opened 2023-04-27 18:20 UTC
Buenas tardes escribo porque no puedo hacer funcionar el RDPWrapper en Windows 10 22H2
Good afternoon, I am writing because I cannot get the RDPWrapper to work on Windows 10 22H2
![Error Escritorio Remoto](https://user-images.githubusercontent.com/86836143/234956262-6c5962cf-001f-4b1d-a08c-0e52d76ae3b0.JPG)

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/11346730/termsrv.zip)

**Comment by sashaqwert** [comment] 2023-04-28 05:05
Duplicate of https://github.com/stascorp/rdpwrap/issues/2180

**Closed as not planned by sashaqwert** 2023-04-28 05:05 UTC
Labels: duplicate
