### ISSUE TITLE
10.0.14393.4704 not working

### ISSUE THREAD

**Issue by Prakhov** [stascorp/rdpwrap#1560] opened 2021-10-18 19:07 UTC
![image](https://user-images.githubusercontent.com/49492863/137791633-b359286b-3e53-4772-984e-55dc8e71d10b.png)

Do you have any medicine for this?

**Comment by aclar** [comment] 2021-10-18 19:43
https://github.com/stascorp/rdpwrap/issues/1555

**Comment by Prakhov** [comment] 2021-10-18 21:02
Thanks a lot!

**Comment by Th0rules** [comment] 2021-10-20 11:27
Great Works !! tnx man.

**Comment by sebaxakerhtc** [comment] 2021-10-27 08:24
Duplicate of https://github.com/stascorp/rdpwrap/issues/1555

**Closed as completed by sebaxakerhtc** 2021-10-27 08:24 UTC
