### ISSUE TITLE
Please help multi remote Windows 10 19044.1288

### ISSUE THREAD

**Issue by vuyen** [stascorp/rdpwrap#2468] opened 2024-01-23 04:19 UTC
Dear
Please path help me file tearm Windows 10 19044.1288. Thanks so much
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/14018278/termsrv.zip)

**Comment by sashaqwert** [comment] 2024-01-25 07:49
duplicate of https://github.com/stascorp/rdpwrap/issues/1509

**Closed as not planned by sashaqwert** 2024-01-25 07:49 UTC
Labels: duplicate
