### ISSUE TITLE
Listener state: Not listening [not supported]

### ISSUE THREAD

**Issue by zhang-ray** [stascorp/rdpwrap#742] opened 2019-04-12 07:02 UTC
OS: Windows 10 Home (Version 1803, OS Build 17134.706)

RDP Wrapper 1.6.2

I got `Listener state: Not listening` in `RDPConf.exe`; and `RDPCheck.exe` told me `Socket connection failed.`

**Comment by hwase0ng** [comment] 2019-04-12 10:11
Latest security update Security update KB4493464 on April 11, 2019 has just broken my RDP wrapper v1.6.2 with this very same message. Uninstalled this latest security update and it now works again.

**Comment by zhang-ray** [comment] 2019-04-12 11:06
> 
> 
> Latest security update Security update KB4493464 on April 11, 2019 has just broken my RDP wrapper v1.6.2 with this very same message. Uninstalled this latest security update and it now works again.

OK, thank you for your information 🙂

**Comment by rmcgarity** [comment] 2019-04-13 20:21
I have the same problem.

**Comment by fre4kyC0de** [comment] 2019-04-13 21:16
Add these offsets to your rdpwrap.ini:
https://github.com/fre4kyC0de/rdpwrap/blob/master/10.0.17134.706.txt

**Comment by DeH4eG** [comment] 2019-04-14 13:52
> Latest security update Security update KB4493464 on April 11, 2019 has just broken my RDP wrapper v1.6.2 with this very same message. Uninstalled this latest security update and it now works again.

Thanks, worked for me. 17134.648

**Comment by rmcgarity** [comment] 2019-04-14 22:47
@fre4kyC0de 
Thank you for this suggestion. I attempted your suggestion, but without success. I've not changed the RDPWrap.ini file before, so I may not have done it correctly. I did these steps:

1. Uninstalled RDPWrap, using the uninstall.bat file in a directory where I had extracted the RDP Wrap files (D:Downloads\RDPWrapcreated in my download directory called RDPWrap.
2. Ran RDPConf.exe and verified that it was uninstalled. However, the Service state was "Not listening".
3. Copy/Pasted the contents of the file above to Notepad, and saved it to .....Downloads/RDPWrap so that it is alongside the RDPWInst.exe.
4. Ran RDPWInst.exe
5. Ran RDPConf.exe and saw the same "Not listening [not supported]" error message.

I would be grateful if someone could either help me correct any misstep above.

**Comment by linqifengyun** [comment] 2019-04-15 03:44
> 
> 
> > Latest security update Security update KB4493464 on April 11, 2019 has just broken my RDP wrapper v1.6.2 with this very same message. Uninstalled this latest security update and it now works again.
> 
> OK, thank you for your information 🙂

is that safe for going back?

**Comment by 42Drut** [comment] 2019-04-15 04:16
Thanks fre4kyC0de. Worked very well for me.

**Comment by hwase0ng** [comment] 2019-04-15 04:40
> Add these offsets to your rdpwrap.ini:
> https://github.com/fre4kyC0de/rdpwrap/blob/master/10.0.17134.706.txt

Tested working for me, and this is after KB4493464 has been reinstalled by windows update :-)

**Comment by hwase0ng** [comment] 2019-04-15 04:42
> @fre4kyC0de
> Thank you for this suggestion. I attempted your suggestion, but without success. I've not changed the RDPWrap.ini file before, so I may not have done it correctly. I did these steps:
> 
> Uninstalled RDPWrap, using the uninstall.bat file in a directory where I had extracted the RDP Wrap files (D:Downloads\RDPWrapcreated in my download directory called RDPWrap.
> Ran RDPConf.exe and verified that it was uninstalled. However, the Service state was "Not listening".
> Copy/Pasted the contents of the file above to Notepad, and saved it to .....Downloads/RDPWrap so that it is alongside the RDPWInst.exe.
> Ran RDPWInst.exe
> Ran RDPConf.exe and saw the same "Not listening [not supported]" error message.
> 
> I would be grateful if someone could either help me correct any misstep above.

You should append the offset to the rdpwrap.ini file. And don't forget to restart windows after that.

**Comment by BarryBA** [comment] 2019-04-15 07:00
> KB4493464

Sorry, but I can't understand your reply, can you explain:
what is the "KB4493464"? 
what is the security update?
and how to uninstalled this latest security update? 
Thank you

**Comment by BarryBA** [comment] 2019-04-15 07:00
> > Add these offsets to your rdpwrap.ini:
> > https://github.com/fre4kyC0de/rdpwrap/blob/master/10.0.17134.706.txt
> 
> Tested working for me, and this is after KB4493464 has been reinstalled by windows update :-)

Sorry, but I can't understand your reply, can you explain:
what is the "KB4493464"?
what is the security update?
and how to uninstalled this latest security update?
Thank you

**Comment by BarryBA** [comment] 2019-04-15 07:26
> Latest security update Security update KB4493464 on April 11, 2019 has just broken my RDP wrapper v1.6.2 with this very same message. Uninstalled this latest security update and it now works again.

Thank you very much.
At the begining, my Listener state is: **Not listening [not supported]** 
Firstly, I uninstalled the windows security update "KB4493464",
Then, following the suggestion of @fre4kyC0de , I added the offsets in the end of the file "rdpwrap.ini" （https://github.com/fre4kyC0de/rdpwrap/blob/master/10.0.17134.706.txt）,
Last, reboot. And the Listener state becomes: Listening [fully supported] 
Thanks a lot to your suggestions @hwase0ng @fre4kyC0de

**Comment by zhang-ray** [comment] 2019-04-15 09:10
> 
> 
> > Latest security update Security update KB4493464 on April 11, 2019 has just broken my RDP wrapper v1.6.2 with this very same message. Uninstalled this latest security update and it now works again.
> 
> Thank you very much.
> At the begining, my Listener state is: **Not listening [not supported]**
> Firstly, I uninstalled the windows security update "KB4493464",
> Then, following the suggestion of @fre4kyC0de , I added the offsets in the end of the file "rdpwrap.ini" （[https://github.com/fre4kyC0de/rdpwrap/blob/master/10.0.17134.706.txt）](https://github.com/fre4kyC0de/rdpwrap/blob/master/10.0.17134.706.txt%EF%BC%89),
> Last, reboot. And the Listener state becomes: Listening [fully supported]
> Thanks a lot to your suggestions @hwase0ng @fre4kyC0de

These steps not worked well for me... After removing all KB security updates and adding the section into "rdpwrap.ini", I got *Service state: Stopped* and *Listener state: Not Listening [fully supported]* in RDPConf.exe

**Comment by BarryBA** [comment] 2019-04-15 09:30
> > > Latest security update Security update KB4493464 on April 11, 2019 has just broken my RDP wrapper v1.6.2 with this very same message. Uninstalled this latest security update and it now works again.
> > 
> > 
> > Thank you very much.
> > At the begining, my Listener state is: **Not listening [not supported]**
> > Firstly, I uninstalled the windows security update "KB4493464",
> > Then, following the suggestion of @fre4kyC0de , I added the offsets in the end of the file "rdpwrap.ini" （[https://github.com/fre4kyC0de/rdpwrap/blob/master/10.0.17134.706.txt）](https://github.com/fre4kyC0de/rdpwrap/blob/master/10.0.17134.706.txt%EF%BC%89),
> > Last, reboot. And the Listener state becomes: Listening [fully supported]
> > Thanks a lot to your suggestions @hwase0ng @fre4kyC0de
> 
> These steps not worked well for me... After removing all KB security updates and adding the section into "rdpwrap.ini", I got _Service state: Stopped_ and _Listener state: Not Listening [fully supported]_ in RDPConf.exe

Try to uninstall the rdpwrap and install it again. Then do the same steps.
I met the same problem before. And uninstall and reinstall solves it.

**Comment by rmcgarity** [comment] 2019-04-15 22:26
@hwase0ng @fre4kyC0de 
Thank you for responding. The directory containing RDPWInst.exe did not contain a RDPWrap.ini file, so I didn't ADD to that file; I simply created a new RDPWrap.ini and pasted in the contents of the 10.0.17134.706.txt file that fre4kyCode provided. I did reboot, both after uninstalling and after reinstalling, but still got the same result when I ran RDPConf.exe - "Not Listening". I'm running Windows 10 Home, 10.0.17134.706, build 17134. I don't know how to find the security patch version.

Please help me learn what I am doing incorrectly.

**Comment by joebrug** [comment] 2019-04-15 23:01
@rmcgarity I might be misunderstanding what you're doing.. but when you INSTALL rdpwrap, it puts a rdpwrap.ini file in (at least on windows 7) "c:\program files\RDP Wrapper". This file will have some defaults in it already, which you should keep.. but you need to ADD the sections that @fre4kyC0de gave to the existing rdpwrap.ini file. Make sense? Install RDP Wrap program > edit rdpwrap.ini file it creates > add sections > save > restart PC.

**Comment by rmcgarity** [comment] 2019-04-15 23:11
@joebrug Thank you for responding! I just removed the RDPWrap.ini file that I created, ran uninstall.bat, ran RDPWrap.exe, rebooted, and it did not create a RDPWrap.ini file in the directory. Any ideas why it didn't do this?

**Comment by joebrug** [comment] 2019-04-15 23:18
@rmcgarity You mention you ran uninstall.bat, but what about install.bat? :) install.bat is what creates the rdpwrap.ini file in c:\program files\rdp wrapper\ (at least on Win7 x64).. the install.bat will tell you where it put it.

**Comment by rmcgarity** [comment] 2019-04-16 00:47
@joebrug Thank you - Now it's listening! I didn't know where the RDPWrap.ini file was located.

**Comment by feritgoksen** [comment] 2019-04-18 10:36
Should we reinstall the update after all of these?

**Comment by hwase0ng** [comment] 2019-04-18 10:40
> Should we reinstall the update after all of these?

If you are referring to the KB4493464 security update, windows will do it automatically for you :-)

**Comment by feritgoksen** [comment] 2019-04-18 10:45
> > Should we reinstall the update after all of these?
> 
> If you are referring to the KB4493464 security update, windows will do it automatically for you :-)

I have done the steps the same. I uninstalled update, done steps, it worked. But when I installed update again same problem occured.

**Comment by Gojakdzevad** [comment] 2019-04-19 05:47
If this issue appear again after removing  KB 4493464 ( or 4493470 for Win 10 LTSB) you need to download 
tool for hiding windows update  ( https://www.repairwin.com/prevent-a-specific-windows-update-or-driver-from-installing-in-windows-10/)
Edit : RDPWrap is not only software that is affected with this update , i have similar problems with Fax  client software

**Comment by duytan412** [comment] 2019-05-17 19:54
Thank you @fre4kyC0de Summarize for those who are not good at computer like me:
1. Install using install.bat in the zip file from https://github.com/stascorp/rdpwrap/releases
2. Copy the code from fre4kyC0de above to the end of C:\Program Files\RDP Wrapper\rdpwrap.ini file (You may need to give it permission. Properties, Edit, Choose Users, Allow in Full Control). Save it.
3. Reboot.

**Comment by NataschaDeCraene** [comment] 2019-07-19 08:23
Hello,
I have the same issue.
But I don't have the specific KB4493464 installed on the Win10Home pc (1803).
I followed the instructions of duytan412 (adding the extra code to the ini-file).
I also used the suggested termsrv.dll, but I wasn't able to start the Remotedesktop services afterwards.
Any idea?
![Capture](https://user-images.githubusercontent.com/53077926/61520738-25fbc880-aa0f-11e9-99eb-c15d3dc04686.PNG)

**Comment by zaniety** [comment] 2019-07-23 21:02
7/23/19 windows version 17763.615 
wont work for me any fix i get the not listening error i did the ini thing above didnt fix it any ideas
![image](https://user-images.githubusercontent.com/52260372/61747314-3390b580-ad63-11e9-9426-f628ff7c11b2.png)

**Comment by yurii20041** [comment] 2019-08-20 08:23
Hi guys, that helped me with solving the issue for WIndows 10 home 1809:
https://www.vcloudpoint.com/fixing-the-problem-of-windows-system-patch-causing-concurrent-multi-user-login-failed/

Hope it will help.

**Comment by arpcpro** [comment] 2019-09-25 13:17
Edit: It worked with rdpwrapper_ini_updater and re-install.bat. Super! :)

> Thanks, but this is not very convenient since if windows updates itself on the remote computer, I might lose access to the machine. 
> Anyway I cannot get this to work on Win10 Home version 10.0.18362.356. There is no ini file for this version :(
> Also my windows does not allow KB4493464 to be removed. It is simply not on the installed updates list.

**Comment by surya002** [comment] 2019-10-01 18:01
> Thank you @fre4kyC0de Summarize for those who are not good at computer like me:
> 
> 1. Install using install.bat in the zip file from https://github.com/stascorp/rdpwrap/releases
> 2. Copy the code from fre4kyC0de above to the end of C:\Program Files\RDP Wrapper\rdpwrap.ini file (You may need to give it permission. Properties, Edit, Choose Users, Allow in Full Control). Save it.
> 3. Reboot.

Does this work with the May 2019 Windows update? Because I tried all these steps and it is still not listening

**Comment by MCarrDallasTx** [comment] 2019-10-01 20:52
So the INI add-on lines did not work for me.
Based on reading above ...
I looked at Windows 10 installed Windows updates and uninstalled the only security update I saw.
(Does not seem like a viable longterm solution.)
I'll try to attach a screenshot of the UNINSTALL KB4516058 in progress--not attaching, so there you are.
...
Now RDP Wrapper works fine. 
I'm leaving the INI file add-on lines in place in case they are critical path.
This system is Windows 10 Home 64-bit version 1803 installed 9/17/19.

**Comment by jh2222** [comment] 2019-10-13 01:55
Not listening raised its ugly head again. This occurred after Windows 2019—KB4519338 was installed on my Windows 10 computer (Home version) on October 9, 2019. Any solution?

**Comment by zzeuli** [comment] 2019-11-11 15:46
Hi jh2222.
I was in your same situation and the great "carlos107fer" commented on 29 Sep, made a solution that worked for me. 
Follow the steps below:
-----------------------
stop the service running CMD as administrator
net stop termservice
Replace rdpwrap.ini in C:\Program Files\RDP Wrapper
net start termservice
Reboot your PC
[rdpwrap_10.0.18362.267_x64.zip](https://github.com/stascorp/rdpwrap/files/3439496/rdpwrap_10.0.18362.267_x64.zip)
------------------------

**Comment by jh2222** [comment] 2019-11-12 15:18
Thanks zzeuli. Unfortunately, your proposed solution did not work.
I followed all the steps you suggested, including the replacement of rdpwrap.ini  from the provided
rdpwrap_10.0.18362.267_x64.zip. Still the listening stated was not listening.
I am running Windows 10 Home, OS build 17763.805. 
Maybe you are running an earlier OS build?

**Comment by zzeuli** [comment] 2019-11-12 16:31
I'm sorry. For me was the only solution worked after the last Windows update 1903.
Since with every major Windows update RDP WRAPPER stops working, It happened to me 3 times, then I found the final solution I would recommend.
I purchased a Win 10 PROFESSIONAL Product Key for € 5 (ebay or Amazon).

**Choose the W10PRO KEY that let you UPGRADE from Home to Pro.**

Below the email text after purchasing
" If your upgrading from Windows 10 Home to Win 10 Pro. Before upgrading, make sure your device is up to date and running the most recent version of Win 10 Home. 

There's no download needed to upgrade from Win 10 Home to Win 10 pro.
1: Select the Start button, then select Settings > Update & security > Activation.
2: Select Change product key, and then enter the 25-character Windows 10 Pro product key.
3: Your system will start upgrading. "

bye!

**Comment by mcdachpappe** [comment] 2019-12-05 19:58
> ## Hi jh2222.
> I was in your same situation and the great "carlos107fer" commented on 29 Sep, made a solution that worked for me.
> Follow the steps below:
> ## stop the service running CMD as administrator
> net stop termservice
> Replace rdpwrap.ini in C:\Program Files\RDP Wrapper
> net start termservice
> Reboot your PC
> [rdpwrap_10.0.18362.267_x64.zip](https://github.com/stascorp/rdpwrap/files/3439496/rdpwrap_10.0.18362.267_x64.zip)

Thank you very much for this solution. I'm currently on Windows 10 x64 Home [Version 1909 Build 18363.476] and this finally worked out for me.

Instead of providing a .zip file I'm going to provide the lines which have to be added to the existing rdpwrap.ini [located at: C:\Program Files\RDP Wrapper]:

```
[10.0.18362.267]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=82FB5
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0DBFC
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1FE15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=22DDC
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.18362.267-SLInit]
bInitialized.x64 =F6A8C
bServerSku.x64 =F6A90
lMaxUserSessions.x64 =F6A94
bAppServerAllowed.x64 =F6A9C
bRemoteConnAllowed.x64=F6AA0
bMultimonAllowed.x64 =F6AA4
ulMaxDebugSessions.x64=F6AA8
bFUSEnabled.x64 =F6AAC

```

Note: There must be an empty line at the bottom of the .ini file! Restart your machine and you should be fine :)

Thanks again to @zzeuli for this fix!

**Comment by Cuchunlain** [comment] 2020-02-11 08:48
> > ## Hi jh2222.
> > I was in your same situation and the great "carlos107fer" commented on 29 Sep, made a solution that worked for me.
> > Follow the steps below:
> > ## stop the service running CMD as administrator
> > net stop termservice
> > Replace rdpwrap.ini in C:\Program Files\RDP Wrapper
> > net start termservice
> > Reboot your PC
> > [rdpwrap_10.0.18362.267_x64.zip](https://github.com/stascorp/rdpwrap/files/3439496/rdpwrap_10.0.18362.267_x64.zip)
> 
> Thank you very much for this solution. I'm currently on Windows 10 x64 Home [Version 1909 Build 18363.476] and this finally worked out for me.
> 
> Instead of providing a .zip file I'm going to provide the lines which have to be added to the existing rdpwrap.ini [located at: C:\Program Files\RDP Wrapper]:
> 
> ```
> [10.0.18362.267]
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=82FB5
> LocalOnlyCode.x64=jmpshort
> SingleUserPatch.x64=1
> SingleUserOffset.x64=0DBFC
> SingleUserCode.x64=Zero
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=1FE15
> DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> SLInitHook.x64=1
> SLInitOffset.x64=22DDC
> SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.18362.267-SLInit]
> bInitialized.x64 =F6A8C
> bServerSku.x64 =F6A90
> lMaxUserSessions.x64 =F6A94
> bAppServerAllowed.x64 =F6A9C
> bRemoteConnAllowed.x64=F6AA0
> bMultimonAllowed.x64 =F6AA4
> ulMaxDebugSessions.x64=F6AA8
> bFUSEnabled.x64 =F6AAC
> ```
> 
> Note: There must be an empty line at the bottom of the .ini file! Restart your machine and you should be fine :)
> 
> Thanks again to @zzeuli for this fix!

Good morning,
I have tried to make the proposed solution, and the result I get is this:

Wrapper state: installed
Service state: Stopped
Listener state: Not Listening [fully supported]

Then, I try to start the termservice from CMD to change the service state.

In CMD as administrator I execute the command "net start termservice" and it shows me the message: the process has been started successfully, but Service state continues in Stopped and Listener state in Not Listening.

Does anyone have any idea?
I'm running Windows 10 Education

Thanks

**Comment by loggan26** [comment] 2020-02-13 18:13
![rdwrap new](https://user-images.githubusercontent.com/61024389/74464866-41875e80-4e8c-11ea-90ae-112ba078184a.png)
there is a new version in the last windows update, the rdpwrap.ini needs updated with the new version 10.0.18362.657. tested and it works fine as in the pic.

**Comment by joebrug** [comment] 2020-02-13 18:16
So what did you add in the rdpwrap.ini?

**Comment by loggan26** [comment] 2020-02-14 08:42
[10.0.18362.657]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=82FB5
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0DBFC
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1FE15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=22DDC
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.18362.657-SLInit]
bInitialized.x64 =F6A8C
bServerSku.x64 =F6A90
lMaxUserSessions.x64 =F6A94
bAppServerAllowed.x64 =F6A9C
bRemoteConnAllowed.x64=F6AA0
bMultimonAllowed.x64 =F6AA4
ulMaxDebugSessions.x64=F6AA8
bFUSEnabled.x64 =F6AAC


Add this to the bottom of existing rdpwrap.ini leaving a space below the last line and save it!

**Comment by Cuchunlain** [comment] 2020-02-14 08:57
Thanks to all of you, I finally solved it using the auto-updater mentioned in this post.
https://github.com/stascorp/rdpwrap/issues/860
This solution has worked for me on two computers with different versions of windows.

Greetings.

**Comment by TheArgentinian** [comment] 2020-02-26 12:50
> 
> 
> [10.0.18362.657]
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=82FB5
> LocalOnlyCode.x64=jmpshort
> SingleUserPatch.x64=1
> SingleUserOffset.x64=0DBFC
> SingleUserCode.x64=Zero
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=1FE15
> DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> SLInitHook.x64=1
> SLInitOffset.x64=22DDC
> SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.18362.657-SLInit]
> bInitialized.x64 =F6A8C
> bServerSku.x64 =F6A90
> lMaxUserSessions.x64 =F6A94
> bAppServerAllowed.x64 =F6A9C
> bRemoteConnAllowed.x64=F6AA0
> bMultimonAllowed.x64 =F6AA4
> ulMaxDebugSessions.x64=F6AA8
> bFUSEnabled.x64 =F6AAC
> 
> Add this to the bottom of existing rdpwrap.ini leaving a space below the last line and save it!

I did this but now I get "Listener state: not listening (red)    fully supported (green)"

Help!

**Comment by Isaacwm** [comment] 2020-03-23 11:19
> Thank you @fre4kyC0de Summarize for those who are not good at computer like me:
> 
> 1. Install using install.bat in the zip file from https://github.com/stascorp/rdpwrap/releases
> 2. Copy the code from fre4kyC0de above to the end of C:\Program Files\RDP Wrapper\rdpwrap.ini file (You may need to give it permission. Properties, Edit, Choose Users, Allow in Full Control). Save it.
> 3. Reboot.

Done this but still getting the 'Not Listening [not supported]' on config. Adding the lines @fre4kyC0de linked I assume is done by going to the end of the .ini file, making a new line then pasting in?

**Comment by tohidul1** [comment] 2020-04-02 06:10
Guys can you help me plz.
windows 10 pro v.1909
![rdp](https://user-images.githubusercontent.com/63036563/78216085-e01e5c00-74da-11ea-8274-195f5ccae370.JPG)

**Comment by ChrisWLeon** [comment] 2020-04-12 14:17
> Thanks to all of you, I finally solved it using the auto-updater mentioned in this post.
> #860
> This solution has worked for me on two computers with different versions of windows.
> 
> Greetings.

I have installed the updater and it works, but VirusTotal online flagged the autoupdate.bat file as a Trojan.DL.Scrip.VBS.Agent Malware?

**Comment by jarbnyc2017** [comment] 2020-04-20 19:17
> Latest security update Security update KB4493464 on April 11, 2019 has just broken my RDP wrapper v1.6.2 with this very same message. Uninstalled this latest security update and it now works again.

uninstall updates sucks, is better to buy the version 10 pro

**Comment by ChadThomsen** [comment] 2020-04-21 02:04
Last windows update broke it again.... and update to the rdpwrap.ini file?  Thanks in advanced.

**Comment by robbak** [comment] 2020-04-21 02:41
Check the version of your termserv.dll file. We know there is an update
coming in the 05 2020 windows version (termsrv.dll version 10.0.19041.84),
and drDrrae already has the offsets for the x86 file. See whether there are
offsets for the version you have in the rdpwrap.ini file - the sections
headed [10.0.nnnnn.nn], where the ns match your version.

**Comment by robbak** [comment] 2020-04-21 02:47
> > Thanks to all of you, I finally solved it using the auto-updater mentioned in this post.
> > #860
> > This solution has worked for me on two computers with different versions of windows.
> > Greetings.
> 
> I have installed the updater and it works, but VirusTotal online flagged the autoupdate.bat file as a Trojan.DL.Scrip.VBS.Agent Malware?

That happens. Either get a better antivirus solution, or whitelist it. It is kind of understandable that an unrecognised bat file that changes system files will be marked as malicious.

**Comment by TheArgentinian** [comment] 2020-04-25 16:52
> 
> Check the version of your termserv.dll file. We know there is an update coming in the 05 2020 windows version (termsrv.dll version 10.0.19041.84), and drDrrae already has the offsets for the x86 file. See whether there are offsets for the version you have in the rdpwrap.ini file - the sections headed [10.0.nnnnn.nn], where the ns match your version.
> .

In English?

**Comment by acyli84** [comment] 2020-06-24 09:55
I have tried to copy a new set of values into ini file catering for the new version. But it does not work. There is an internal error when trying to remote desktop.

**Comment by Lm-shen** [comment] 2020-09-05 07:30
> OS: Windows 10 Home (Version 1803, OS Build 17134.706)
> 
> RDP Wrapper 1.6.2
> 
> I got `Listener state: Not listening` in `RDPConf.exe`; and `RDPCheck.exe` told me `Socket connection failed.`

I am also the same version, encountered the same problem, how do you solve the last, convenient to tell me
![D8E)OPA XDIOGH)C70_JG0](https://user-images.githubusercontent.com/69762316/92300596-b805be00-ef8e-11ea-999e-912fbde3be8b.png)

**Comment by robione-nr** [comment] 2020-09-27 00:17
Same issue - service version: 10.0.18362.836

**Comment by sebaxakerhtc** [comment] 2022-01-04 10:30
Duplicate of https://github.com/stascorp/rdpwrap/issues/721

**Closed as completed by sebaxakerhtc** 2022-01-04 10:30 UTC
