### ISSUE TITLE
10.0.19041.1949 [ not supported]

### ISSUE THREAD

**Issue by Henton** [stascorp/rdpwrap#1988] opened 2022-09-18 14:59 UTC
Please help, it's not supported:
![image](https://user-images.githubusercontent.com/20090790/190913626-35d31d35-460e-4340-b9e3-5cfcb0838410.png)
Thanks!
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/9594238/termsrv.zip)

**Comment by KennyMcc0rmick** [comment] 2022-09-18 17:32
https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

issue resolved))

**Comment by sebaxakerhtc** [comment] 2022-09-19 07:43
Duplicate of https://github.com/stascorp/rdpwrap/issues/1968

**Closed as completed by sebaxakerhtc** 2022-09-19 07:43 UTC
