### ISSUE TITLE
10.0.19042.662

### ISSUE THREAD

**Issue by StarfighterJ** [stascorp/rdpwrap#1222] opened 2020-12-01 21:34 UTC
I made new thread with correct version I am still not working I do not see 10.0.19042.662 in the new ini Autoupdate created. please help.

**Comment by sebaxakerhtc** [comment] 2020-12-02 15:52
You should look at termsrv.dll version(for example in rdpwrap.conf or file properties), not a Windows version!
<img width="414" alt="Снимок экрана 2020-12-02 в 17 50 03" src="https://user-images.githubusercontent.com/32651506/100896255-19bec100-34c7-11eb-9ad1-eaeb3dc5e17a.png">

**Comment by strarsis** [comment] 2020-12-02 20:11
Probably related: https://github.com/stascorp/rdpwrap/issues/1223

**Comment by frandj99** [comment] 2020-12-03 08:28
So the only way to fix at the moment is to uninstall the KB4586853 update?

**Comment by sebaxakerhtc** [comment] 2020-12-03 08:40
> So the only way to fix at the moment is to uninstall the KB4586853 update?

If you on x86 Windows
You have 3 ways:
1) Find values by yourself
2) Uninstall update
3) Wait while anybody find values

**Comment by pcaste2000** [comment] 2020-12-05 14:59
> So the only way to fix at the moment is to uninstall the KB4586853 update?

It's exactly what I did, returning to 10.0.19041.84 and the it worked! Not a smart solution but [fully supported] :-)

**Comment by pcaste2000** [comment] 2020-12-05 15:20
> > So the only way to fix at the moment is to uninstall the KB4586853 update?
> 
> It's exactly what I did, returning to 10.0.19041.84 and the it worked! Not a smart solution but [fully supported] :-)

Solved: I found all .ini versions at: https://github.com/sebaxakerhtc/rdpwrap.ini (thanks to the user, nice work!)

**Comment by strarsis** [comment] 2020-12-05 16:02
@sebaxakerhtc: For whatever reason I get a security error (red screen, no skip possible) in Chrome when opening the `rdpwrap.ini` in your GitHub fork.

**Comment by sebaxakerhtc** [comment] 2020-12-05 16:15
> @sebaxakerhtc: For whatever reason I get a security error (red screen, no skip possible) in Chrome when opening the `rdpwrap.ini` in your GitHub fork.

Yes, i know. It's normal, because there are link for a my modded version of rdpwrapper.
Just accept risk and go.
You can to not use my modded version if you want.

**Comment by sebaxakerhtc** [comment] 2022-06-20 11:57
Duplicate of https://github.com/stascorp/rdpwrap/issues/1220

**Closed as completed by sebaxakerhtc** 2022-06-20 11:57 UTC
