### ISSUE TITLE
Termsrv.dll ver 10.0.17134.1

### ISSUE THREAD

**Issue by piripallo** [stascorp/rdpwrap#464] opened 2018-05-03 09:45 UTC
termsrv.dll ver 10.0.17134.1 (windows 10, update 1803)  is not supported.
Solution in issue #456 works.

![rdpwrapper](https://user-images.githubusercontent.com/38940599/39570055-5a162d58-4ec7-11e8-9a5a-8295a080e820.png)

**Comment by binarymaster** [comment] 2018-05-03 11:55
Duplicate of #456.

**Closed by binarymaster** 2018-05-03 11:55 UTC
