### ISSUE TITLE
ver 10.0.19041.1348 Listerner state:Not listening

### ISSUE THREAD

**Issue by cc852852** [stascorp/rdpwrap#1652] opened 2021-12-07 13:28 UTC
Can anyone help me? Please~
![](https://s3.bmp.ovh/imgs/2021/12/430be9a432cd95cc.png)

**Comment by sebaxakerhtc** [comment] 2021-12-07 14:50
Duplicate of https://github.com/stascorp/rdpwrap/issues/1595

**Closed as completed by sebaxakerhtc** 2021-12-07 14:50 UTC
