### ISSUE TITLE
need support for 19045.2486

### ISSUE THREAD

**Issue by yzq8948** [stascorp/rdpwrap#2115] opened 2023-02-14 23:43 UTC
The system version is 19045.2486 and running RDPconfig shows that it can be supported, but the multi-user remote connection test still cannot be connected. May I ask what is wrong with this, please help to answer it, thank you
![1](https://user-images.githubusercontent.com/125414359/218888010-abe9b81c-385d-4031-af6a-585ce66ec84b.png)
![2](https://user-images.githubusercontent.com/125414359/218888032-eb515fc1-f36d-4787-a6d2-bec5b2073d1c.png)
![3](https://user-images.githubusercontent.com/125414359/218888054-d3acf800-5c00-436a-83ab-ebc3d39ff190.png)

**Comment by sashaqwert** [comment] 2023-02-15 07:04
Please, add your RDP users to Administrators or «Remote Desktop users» group.

**Comment by sashaqwert** [comment] 2023-02-15 07:06
Duplicate of https://github.com/stascorp/rdpwrap/issues/1083

**Closed as not planned by sashaqwert** 2023-02-15 07:06 UTC
Labels: duplicate
