### ISSUE TITLE
saying not supported in rdp wrap configuration 10. 0. 19041. 1949

### ISSUE THREAD

**Issue by narggari** [stascorp/rdpwrap#1985] opened 2022-09-16 16:28 UTC
i copy pasted this
LocalOnlyPatch.x86=1
LocalOnlyOffset.x86=C2749
LocalOnlyCode.x86=jmpshort
SingleUserPatch.x86=1
SingleUserOffset.x86=3CAE7
SingleUserCode.x86=Zero
DefPolicyPatch.x86=1
DefPolicyOffset.x86=3E0B9
DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
SLInitHook.x86=1
SLInitOffset.x86=6F388
SLInitFunc.x86=New_CSLQuery_Initialize
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=922A1
LocalOnlyCode.x64=jmpshort
 in to the rdp wrap thing but still it doesnt work

**Comment by narggari** [comment] 2022-09-16 16:34
and when i try to connect with remote desktop connection it says "this compunters connections are limited . and are in use right now"

**Comment by narggari** [comment] 2022-09-16 17:12
i got it to sayiong "fully supported" but why does it say" the connections to this compunter is limited and all connections ARE IN USE RIGHT NOW"

**Comment by narggari** [comment] 2022-09-16 17:15
![Desktop Screenshot 2022 09 16 - 20 14 36 83](https://user-images.githubusercontent.com/113712058/190693408-d6313def-cf7f-49b2-99c3-67b2f7531e9f.png)

**Comment by narggari** [comment] 2022-09-16 17:56
how do i fix this??

**Comment by sashaqwert** [comment] 2022-09-17 07:08
Duplicate of https://github.com/stascorp/rdpwrap/issues/1968

**Closed as not planned by sashaqwert** 2022-09-17 07:08 UTC
Labels: duplicate

**Comment by sashaqwert** [comment] 2022-09-17 07:10
> i copy pasted this

Recommended to fully replace the `rdpwrap.ini`: https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini
