### ISSUE TITLE
Does anyone have settings for 10.0.19041.1741

### ISSUE THREAD

**Issue by BrianDent** [stascorp/rdpwrap#1887] opened 2022-06-03 16:18 UTC
Thank you.

**Comment by sashaqwert** [comment] 2022-06-04 04:51
Duplicate of https://github.com/stascorp/rdpwrap/issues/1886

Windows versions 19041 - 19044 have the same version of `termsrv.dll`.
Since there is ONE open issue per version of `termsrv.dll`, this one will be closed soon...

**Comment by sebaxakerhtc** [comment] 2022-06-04 11:18
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881

**Closed as completed by sebaxakerhtc** 2022-06-04 11:18 UTC
