### ISSUE TITLE
New Windows 10 Fall Creators Home Edition Stiil not supported

### ISSUE THREAD

**Issue by StarfighterJ** [stascorp/rdpwrap#351] opened 2017-11-17 19:33 UTC
Is All Creators Home Editions now Dead and this Program  RDPWRAP will no longer be supported and Work Again?

**Comment by binarymaster** [comment] 2017-11-17 19:34
Did you tried to run update and install external depedencies?

**Comment by CaptainThrowback** [comment] 2017-11-17 19:36
https://github.com/stascorp/rdpwrap/blob/master/README.md
3rd Bullet point in "Known Issues" - helps to actually read the README ;)

**Comment by StarfighterJ** [comment] 2017-11-17 21:33
I ran update Did not see anything on install external Dependencies. But I di go to the README.md and click on more info part of 3rd Bullet point under known Issues" and downloaded the rfxvmt.dll put into Windows/System32 Directory. I uninstalled RDPWrap-v1.61, re-Installed it, ran update bat. And Everything is working like it is suppose to. Thank all very much. 👍 :)

**Comment by binarymaster** [comment] 2017-11-18 11:11
So closing as duplicate of #194.

**Closed by binarymaster** 2017-11-18 11:11 UTC
