### ISSUE TITLE
some issues installing and even uninstalling rdpwrap

### ISSUE THREAD

**Issue by gartha1** [stascorp/rdpwrap#1072] opened 2020-05-01 01:42 UTC
my version of termsrv.dll is 10.0.18362.657

First I tried download the code as a zip and extracting it and doing "runas administrator" on install.bat , it said "installer executable not found". And indeed in that bin directory there is only 3 bat files. install.bat, uninstall.bat ,update.bat    no exe files there.  But ok that's is from the codebase, so I then tried under release.

Then I tried under release, the MSI installer and that gave some error. When I try to reinstall it the installer gives no error, but I get no concurrent feature. And when I try to uninstall it it says "there is a problem with this windows installer package".

Then instead of trying to install it those ways,  I tried downloading the Zip file under Releases. I extracted that, and it has some executables there including RDPWInst.exe , which I understand is good that should be there,, and I ran cmd as Administrator, and I tried install.bat 

And it said

```
C:\rdpwrap>dir
 Volume in drive C has no label.
 Volume Serial Number is 646E-DA1B

 Directory of C:\rdpwrap

01/05/2020  00:45    <DIR>          .
01/05/2020  00:45    <DIR>          ..
30/04/2020  22:27               160 .gitattributes
30/04/2020  22:27               191 .gitignore
30/04/2020  22:27    <DIR>          bin
01/05/2020  00:45               458 install.bat
30/04/2020  22:27            10,854 LICENSE
01/05/2020  00:45         1,045,504 RDPCheck.exe
01/05/2020  00:45         1,096,192 RDPConf.exe
01/05/2020  00:45         1,460,224 RDPWInst.exe
30/04/2020  22:27            22,472 README.md
30/04/2020  22:27    <DIR>          res
30/04/2020  22:27    <DIR>          src-installer
30/04/2020  22:27    <DIR>          src-rdpcheck
30/04/2020  22:27    <DIR>          src-rdpconfig
30/04/2020  22:27    <DIR>          src-x86-binarymaster
30/04/2020  22:27    <DIR>          src-x86-x64-Fusix
30/04/2020  22:27            26,068 technical.txt
01/05/2020  00:45               249 uninstall.bat
01/05/2020  00:45               249 update.bat
              11 File(s)      3,662,621 bytes
               9 Dir(s)  185,500,344,320 bytes free

C:\rdpwrap>install
RDP Wrapper Library v1.6.2
Installer v2.5
Copyright (C) Stas'M Corp. 2017

[*] Notice to user:
  - By using all or any portion of this software, you are agreeing
  to be bound by all the terms and conditions of the license agreement.
  - To read the license agreement, run the installer with -l parameter.
  - If you do not agree to any terms of the license agreement,
  do not use the software.
[*] Installing...
[*] Terminal Services version: 10.0.18362.657
[-] This version of Terminal Services is not supported.
Try running "update.bat" or "RDPWInst -w" to download latest INI file.
If it doesn't help, send your termsrv.dll to project developer for support.
[+] TermService found (pid 1328).
[*] No shared services found.
[*] Extracting files...
[+] Folder created: C:\Program Files\RDP Wrapper\
[*] Downloading latest INI file...
[+] Latest INI file -> C:\Program Files\RDP Wrapper\rdpwrap.ini
[+] Extracted rdpw64 -> C:\Program Files\RDP Wrapper\rdpwrap.dll
[*] Configuring service library...
[*] Checking dependencies...
[*] Checking CertPropSvc...
[*] Checking SessionEnv...
[*] Terminating service...
[*] Starting TermService...
[-] StartService error (code 1056).
[*] Configuring registry...
[*] Configuring firewall...
Ok.

[+] Successfully installed.
______________________________________________________________

You can check RDP functionality with RDPCheck program.
Also you can configure advanced settings with RDPConf program.

Press any key to continue . . .

C:\rdpwrap>
```

I then did rdpcheck, and it said number of connections is limited.

I noticed "[-] StartService error (code 1056)."   I don't know if that has anything to do with it.

So then I read that I need rdpwrap.ini 
  
I saw that when I ran install.bat  even though it said "Successfully installed." and "[*] Downloading latest INI file..."   and "[+] Latest INI file -> C:\Program Files\RDP Wrapper\rdpwrap.ini"  It also said  "[-] This version of Terminal Services is not supported.  Try running "update.bat" or "RDPWInst -w" to download latest INI file."

So I tried RDPWInst -w  then rdpcheck, but it still said that "the number of connections to this computer is limited.." 

c:\rdpwrap>RDPWInst -w
RDP Wrapper Library v1.6.2
Installer v2.5
Copyright (C) Stas'M Corp. 2017

[*] Checking for updates...
[*] Current update date: 2018.10.10
[*] Latest update date:  2018.10.10
[*] Everything is up to date.

c:\rdpwrap>install
RDP Wrapper Library v1.6.2
Installer v2.5
Copyright (C) Stas'M Corp. 2017

[*] RDP Wrapper Library is already installed.
______________________________________________________________

You can check RDP functionality with RDPCheck program.
Also you can configure advanced settings with RDPConf program.

Press any key to continue . . .

c:\rdpwrap>rdpcheck

c:\rdpwrap>

I don't really know if the version of rdpwrap.ini has to be built for the exact same version as my termsrv.dll  or whether a current/later verson of rdpwrap.ini is still fine.

I looked at https://github.com/stascorp/rdpwrap/issues/1008 because the title of that thread has the same version of termsrv.dll as I do 10.0.18362.657  and from there I downloaded this rdpwrap.ini  that was mentioned there https://raw.githubusercontent.com/asmtron/rdpwrap/master/res/rdpwrap.ini and added it to what I extracted from RDPWrap-v1.6.2

Still though rdpcheck didn't show it working.

**Comment by robbak** [comment] 2020-05-01 08:45
You seem to have done enough - apart from not restarting the remote desktop service after replacing the .dll file.

I make use of the autoupdate.bat file in #859 Put all the files in it's zip file and put it in your program files/rdpwrapper folder, run the autoupdate.bat file and it will pull updated .ini files from some trusted github repositories when needed. Us the scripts in the utilities folder to add a sheduled task to make sure you are always up to date.

**Comment by gartha1** [comment] 2020-05-01 11:17
Thanks.. Judging by how my termsrv.dll isn't the latest one,(maybe I haven't updated windows 10 on there), then would the latest rdpwrap.ini be compatible with it?

**Comment by robbak** [comment] 2020-05-01 11:25
The rdpwrap.ini files in this repostiory are not updated regularly. You can find updated ones in this repository's pull requests, or in other users own repositories. 

The autoupdate.bat pulls ini files from those other repositories.

[This .ini file](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini) provided by @affinityv has the latest updates.

**Comment by gartha1** [comment] 2020-05-01 11:57
thanks, I see that ini file you link to is most up to date and it mentions the date at the top of it.. 
I notice that RDPWinst -w , for me,  isn't actually downloading any ini file to anywhere. (likewise update.bat which I think just runs RDPWinst -w).
Also, I notice I have an rdpwrap.ini in the res subdirectory.
I have been putting the rdpwrap.ini in the main directory where I extracted the release zip to, i.e. c:\rdpwrap, which is where install.bat is. Is the rdpwrap.ini I put in there meant to be in the main directory level, with install.bat, or in the res subdirectory?
Also, should I update my windows 10(That way my termsrv.dll will hopefully match the latest rdpwrap.ini), since maybe the ini file isn't backwards compatible with older versions of termsrv.dll?
Thanks

**Comment by robbak** [comment] 2020-05-01 12:01
No - these ini files contain the information for all the termsrv.dll files we know of - updating windows risks updating to a version we don't know about. Not something that will happen at this time, but it does happen.

It should install and save .ini files from C:/Program Files/RDPWrapper/ . That is where the .ini file normally is found. Have you checked there?

RDPWinst -w pulls .ini files from this repository only, and the files in this repository aren't up to date any more.

**Comment by gartha1** [comment] 2020-05-01 14:30
OK thanks. I see I have a "c:\program files\rdp wrapper" directory with rdpwrap.dll and rdpwrap.ini 

Am I supposed to have two directories, the directory I extracted the zip to, and the "C:\program files\rdp wrapper" directory. Or am I supposed to have just one directory "c:\program files\rdp wrapper" and extract the zip there?

**Comment by gartha1** [comment] 2020-05-01 15:51
ok I see it looks like I should have both directories. The dll  and ini in program files.  
rdpconf.exe says "fully supported", when I use the ini file you mention earlier in this thread, dated 2020-03-29  And  rdpcheck initially said "limited.." but once rdpconf said fully supported and i'd stopped and started 'remote desktop services', then it worked.

So mine is now fine. Thanks.

It does make me wonder though how one would normally go about getting the latest ini (2020-03-29) ? 

I understand that the update.bat file that runs rdpwinst.exe -w,  doesn't get the latest ini to program files.  I read that it's a good idea to look at pull requests, but if I look at the most recent pull request  https://github.com/stascorp/rdpwrap/pull/1039  all I see there is an ini from 2018-10-10   

Thanks

**Comment by sebaxakerhtc** [comment] 2022-06-20 10:35
Duplicate of https://github.com/stascorp/rdpwrap/issues/983

**Closed as completed by sebaxakerhtc** 2022-06-20 10:35 UTC
