### ISSUE TITLE
WIn10 Prof .267 version kills sessions unexpectedly

### ISSUE THREAD

**Issue by han-the-man** [stascorp/rdpwrap#935] opened 2019-11-28 09:54 UTC
We have a strange issue with 2 windows10 prof machines, both were updated with the nov2019 feature update. After this, RDP works, but users are quite frequently disconnected and their sessions completely lost. That is, all applications are killed without saving data etc.

We are running the latest INI file, with support for the .267 version of termsvr. Any help greatly appreciated!

![image](https://user-images.githubusercontent.com/58291678/69795973-6cd3a900-11cd-11ea-857f-27cee0c0facc.png)

**Comment by derekz007** [comment] 2019-11-30 23:10
I've been having the same problem. Any ideas appreciated. Windows 10 Pro, .267

**Comment by derekz007** [comment] 2019-11-30 23:16
oh, also I started to get a screen flicker after fixing RDP after the latest update that corresponded with this problem of disconnects started at the same time. basically before the update, no problems, and after it is both flickering occasionally, I sit at the computer, and disconnects the other remote users sporadically.

**Comment by Kollegue** [comment] 2019-12-02 15:21
exact same problem. Using Windows 10 Education 1909 (18363.476). Any suggestions?

**Comment by oslecpt** [comment] 2019-12-12 08:34
Same here for vesion .437

**Comment by s0nic9** [comment] 2020-01-08 12:49
fix https://github.com/stascorp/rdpwrap/issues/858#issuecomment-523192537

**Comment by sebaxakerhtc** [comment] 2022-06-20 10:18
Duplicate of https://github.com/stascorp/rdpwrap/issues/871

**Closed as completed by sebaxakerhtc** 2022-06-20 10:18 UTC
