### ISSUE TITLE
It says Not Listening 

### ISSUE THREAD

**Issue by NitradoAdmin** [stascorp/rdpwrap#2008] opened 2022-10-01 15:29 UTC
![image](https://user-images.githubusercontent.com/113641561/193416657-04db4beb-20a9-4085-aa83-3408cc9ee1e4.png)

**Comment by sashaqwert** [comment] 2022-10-01 17:30
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881

**Closed as not planned by sashaqwert** 2022-10-01 17:30 UTC
Labels: duplicate
