### ISSUE TITLE
This version of Terminal Services is not supported 

### ISSUE THREAD

**Issue by sgbr82** [stascorp/rdpwrap#1106] opened 2020-06-26 08:40 UTC
Hi Team,

When i run Install.bat i got the error message as below 
 
"This version of Terminal Services is not supported.
Try running "update.bat" or "RDPWInst -w" to download latest INI file.
If it doesn't help, send your termsrv.dll to project developer for support"

Below is the my RDPConf.exe output screenshot 
![RDPConf](https://user-images.githubusercontent.com/31039043/85838048-4b2ab680-b7dc-11ea-9a26-87bae30e1dd8.PNG)

Please help me in rectifying this issue

**Comment by robbak** [comment] 2020-06-26 08:49
You will need an updated rdpwrap.ini file. This is what practically every
second issue in this entire list is about. Why didn't you read any of them
before you asked the same question, again?

The latest rdpwrap.ini update is in pull request #1105. Check the 'files
changed' tab.

**Comment by sebaxakerhtc** [comment] 2022-06-20 11:04
Duplicate of https://github.com/stascorp/rdpwrap/issues/1083

**Closed as completed by sebaxakerhtc** 2022-06-20 11:04 UTC
