### ISSUE TITLE
19045.2251 not listening

### ISSUE THREAD

**Issue by likemodzz** [stascorp/rdpwrap#2049] opened 2022-11-20 22:39 UTC
![image](https://user-images.githubusercontent.com/110046374/202930170-d86dc9fd-2f5d-469c-8ac8-c48db961f586.png)
![image](https://user-images.githubusercontent.com/110046374/202930193-ee73b0bc-259d-446c-ad53-3fc7ae628082.png)

**Comment by sashaqwert** [comment] 2022-11-21 08:31
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992

**Comment by sashaqwert** [comment] 2022-11-21 08:31
Try:
1. Download RDP Wrapper 1.6.2 and extract this to any directory.
2. Place `rdpwrap.ini` in the same directory.
3. Open CMD as administrator
4. Execute this commands
```
cd C:\path\to\directory\
rdpwinst -u -k
rdpwinst -i
```
5. Enjoy!

Original message: https://t.me/rdpwrap/49131

**Closed as not planned by sashaqwert** 2022-11-21 08:31 UTC
Labels: duplicate

**Comment by sashaqwert** [comment] 2022-11-21 08:46
> Duplicate of #1992

One `termsrv.dll` version = one opened issue.

**Comment by likemodzz** [comment] 2022-11-21 20:16
> Try:
> 
> 1. Download RDP Wrapper 1.6.2 and extract this to any directory.
> 2. Place `rdpwrap.ini` in the same directory.
> 3. Open CMD as administrator
> 4. Execute this commands
> 
> ```
> cd C:\path\to\directory\
> rdpwinst -u -k
> rdpwinst -i
> ```
> 
> 5. Enjoy!
> 
> Original message: https://t.me/rdpwrap/49131

did this nothing changed its still not listening
