### ISSUE TITLE
Windows 10 10.0.19045 support missing

### ISSUE THREAD

**Issue by CodeAnthem** [stascorp/rdpwrap#2130] opened 2023-02-28 14:05 UTC
Hello, could you help me to get this version supported? Thanks 

Edit:
Running latest version and update.bat didn't work.

Version 10.0.19045.2604

**Comment by sashaqwert** [comment] 2023-02-28 14:49
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992

**Closed as not planned by sashaqwert** 2023-02-28 14:49 UTC
Labels: duplicate

**Comment by sashaqwert** [comment] 2023-02-28 14:51
> Version 10.0.19045.2604

19041 - 19045 - one core 19041. termsrv.dll is `10.0.19041.XXX`
Original issue detected via previous duplicate https://github.com/stascorp/rdpwrap/issues/2127
