### ISSUE TITLE
10.0.19041.964 not supported

### ISSUE THREAD

**Issue by szczebel** [stascorp/rdpwrap#1514] opened 2021-09-08 09:42 UTC
![image](https://user-images.githubusercontent.com/1488353/132486420-d063fe9e-8343-421a-813c-15e258bca1ba.png)

**Comment by sebaxakerhtc** [comment] 2022-06-20 13:28
Duplicate of https://github.com/stascorp/rdpwrap/issues/1384

**Closed as completed by sebaxakerhtc** 2022-06-20 13:28 UTC
