### ISSUE TITLE
Add support for termsrv 6.3.9600.18928 for x86 machines

### ISSUE THREAD

**Issue by dfoster388** [stascorp/rdpwrap#454] opened 2018-04-19 22:54 UTC
I see that there have been updates to the ini file for .18928 for x64 machines but these offsets don't work for x86 based machines. Is it possible to get the ini file updated to support .18928 for x86 machines?

**Comment by binarymaster** [comment] 2018-04-21 21:24
Duplicate of #418.

**Closed by binarymaster** 2018-04-21 21:24 UTC
