### ISSUE TITLE
Support build 10.0.17074.1000

### ISSUE THREAD

**Issue by jonstanley** [stascorp/rdpwrap#389] opened 2018-01-13 05:11 UTC
Also cross-ref bug #378, as this build likely to fail with RDPCheck "Unknown Error 0x4"

**Comment by marcwebdude** [comment] 2018-01-24 17:44
fulfilling this could possibly resolve my build request: https://github.com/stascorp/rdpwrap/issues/396

**Comment by binarymaster** [comment] 2018-05-16 08:41
Probably a duplicate of #396.

**Closed by binarymaster** 2018-05-16 08:41 UTC
