### ISSUE TITLE
RDPWrap no longer working probably after windows update

### ISSUE THREAD

**Issue by user78792** [stascorp/rdpwrap#284] opened 2017-07-20 21:33 UTC
Hi, 
I'm using windows 10 Home x64. Version: 1703, Build 15063.0
It appears that after windows update, RdpWrap no longer works.

I tried:
-reinstalling,
-modifying folder permissions of program files folder of RdpWrap, to full to System and Administrators, Current user, etc.
-disabling firewall,
-uninstalling antivirus.
-tried the update method RDPWInst.exe -w
-tried the update method using the bat file.

Symptoms:
while installed, RdpWrap shows:
![untitled-2](https://user-images.githubusercontent.com/30327965/28439485-c537e5d0-6daa-11e7-8c49-215d2dead9ba.jpg)

![untitled-3](https://user-images.githubusercontent.com/30327965/28439523-f6535e10-6daa-11e7-9812-0f1be2c6e681.jpg)

A few days before, rdpWrap worked like a charm, what can I say.

Cannot use windows restore as it was disabled.
Cannot uninstall all the recent updates. Some don't have the uninstall button available.

Any thoughts on this ?
Many thanks.
Joe.

**Comment by manuc66** [comment] 2017-07-20 22:04
Hi, this seem to have already reported, see #235

**Comment by binarymaster** [comment] 2017-07-21 06:56
This is duplicate of #235 and #194.

**Closed by binarymaster** 2017-07-21 06:56 UTC
Labels: duplicate
