### ISSUE TITLE
10.0.22631.2861

### ISSUE THREAD

**Issue by GitYeJiaWei** [stascorp/rdpwrap#2458] opened 2023-12-25 03:14 UTC
10.0.22631.2861

**Comment by GitYeJiaWei** [comment] 2023-12-25 03:15
Request support for this version

**Comment by sashaqwert** [comment] 2023-12-25 08:53
> 10.0.22631.2861

This is not a `termsrv.dll` version. `termsrv.dll` version != Windows version!

**Comment by sashaqwert** [comment] 2023-12-25 08:53
Duplicate of https://github.com/stascorp/rdpwrap/issues/2443

**Closed as not planned by sashaqwert** 2023-12-25 08:53 UTC
Labels: duplicate
