### ISSUE TITLE
Not Supported 10.0.22000.675

### ISSUE THREAD

**Issue by shiroamada** [stascorp/rdpwrap#1845] opened 2022-05-12 03:25 UTC
10.0.22000.675 not working, can help?

**Comment by demicus** [comment] 2022-05-12 07:12
10.0.22000.675 and me please((

**Comment by ZOAR05** [comment] 2022-05-15 16:51
Me  three. please  help.

**Comment by jodkiam** [comment] 2022-05-15 17:16
how to do friends 10.0.22000.675

**Comment by Raoniq** [comment] 2022-05-16 18:55
same here, not supported :(

**Comment by Raoniq** [comment] 2022-05-16 19:38
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/8702944/termsrv.zip)

if anyone is interesting on helping us :D pleeeeeeease

**Comment by phiclin** [comment] 2022-05-18 02:43
10.0.22000.675 and me please help

**Comment by wxpanada** [comment] 2022-05-19 03:31
https://github.com/anhkgg/SuperRDP
You can set the checkbox AutoSupport， then SuperRDP2 will automatically support the new version

**Comment by sebaxakerhtc** [comment] 2022-05-20 08:02
Duplicate of https://github.com/stascorp/rdpwrap/issues/1843

**Closed as completed by sebaxakerhtc** 2022-05-20 08:02 UTC

**Comment by Raoniq** [comment] 2022-05-22 11:06
No one ? :(

**Comment by sebaxakerhtc** [comment] 2022-05-22 11:51
> No one ? :(

All works fine. Look upper https://github.com/stascorp/rdpwrap/issues/1845#issuecomment-1132602432
