### ISSUE TITLE
RDP WRAPPER NOT SUPPORTED

### ISSUE THREAD

**Issue by sunandan2003** [stascorp/rdpwrap#3237] opened 2024-07-25 02:44 UTC
MY VERSION IS 10.0.17763.168

**Comment by loyejaotdiqr47123** [comment] 2024-07-25 05:32
Please, attach your RDPConf screenshot and termsrv.dll.

**Comment by binarymaster** [comment] 2024-07-25 15:51
Duplicate of #606.

**Closed as not planned by binarymaster** 2024-07-25 15:51 UTC
Labels: duplicate
