### ISSUE TITLE
RDP WRAPPER 10.0.22621.608 NOT SUPPORTED

### ISSUE THREAD

**Issue by RakibMKhan** [stascorp/rdpwrap#2082] opened 2023-01-08 08:10 UTC
RDP WRAPPER 10.0.22621.608 NOT SUPPORTED

**Comment by sashaqwert** [comment] 2023-01-08 08:23
Duplicate of https://github.com/stascorp/rdpwrap/issues/2006

**Closed as not planned by sashaqwert** 2023-01-08 08:23 UTC
Labels: duplicate
