### ISSUE TITLE
10.19045.3570 socket issue on RDPCheck

### ISSUE THREAD

**Issue by jonhbm** [stascorp/rdpwrap#2408] opened 2023-11-15 17:18 UTC
The RDPConf is all green, but whenever I try to run RDPCheck it loads in but stays frozen on the "Connecting..." or a black screen and eventually closes itself. I've gotten an error message along the lines of "Socket failed" sometimes. 

![image](https://github.com/stascorp/rdpwrap/assets/126407633/f34d44f7-91d0-4f88-8213-03105219542e)

I've tried looking through past posts from people who have similar issues, but none of them have worked. 

Any help is appreciated.

**Comment by sashaqwert** [comment] 2023-11-15 17:27
Try mstsc --> `127.0.0.2`

**Comment by sashaqwert** [comment] 2023-11-15 17:28
One `termsrv.dll` version = ONE opened issue!

**Comment by sashaqwert** [comment] 2023-11-15 17:28
Duplicate of https://github.com/stascorp/rdpwrap/issues/2359

**Closed as not planned by sashaqwert** 2023-11-15 17:28 UTC
Labels: duplicate

**Comment by sashaqwert** [comment] 2023-11-15 17:29
If you have other questions, please use https://t.me/rdpwrap
