### ISSUE TITLE
Not supported  10.0.18362.1316

### ISSUE THREAD

**Issue by jellyDL** [stascorp/rdpwrap#1748] opened 2022-02-28 08:38 UTC

**Comment by sebaxakerhtc** [comment] 2022-02-28 13:48
https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini

**Comment by sebaxakerhtc** [comment] 2022-06-20 13:32
Duplicate of https://github.com/stascorp/rdpwrap/issues/1278

**Closed as completed by sebaxakerhtc** 2022-06-20 13:32 UTC
