### ISSUE TITLE
Not Supported 10.0.22610.1

### ISSUE THREAD

**Issue by ghost** [stascorp/rdpwrap#1834] opened 2022-05-05 22:48 UTC
After installing RDPWrap-v1.6.2 it has the Service State and Listenet state in green and it just says not supported by the .ini file, after changing the .ini file to the version Updated=2022-05-02 it changes to fully supported but Service State and Listener State remain in the red.

![Captura de tela 2022-05-05 194521](https://user-images.githubusercontent.com/19479739/167037036-cd46af70-85d8-437d-9704-5ad2d54f217f.png)

**Comment by ghost** [comment] 2022-05-05 23:06
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/8636546/termsrv.zip)
here is the termsrv.dll

**Comment by sebaxakerhtc** [comment] 2022-05-07 21:14
Duplicate of https://github.com/stascorp/rdpwrap/issues/1830

**Closed as completed by sebaxakerhtc** 2022-05-07 21:14 UTC
