### ISSUE TITLE
10.0.22621.3447 not supportted

### ISSUE THREAD

**Issue by TennyOx** [stascorp/rdpwrap#2580] opened 2024-04-17 22:37 UTC

**Comment by ganeshchavan786** [comment] 2024-04-18 09:06
https://github.com/stascorp/rdpwrap/issues/2569

**Comment by loyejaotdiqr47123** [comment] 2024-04-18 13:00
Duplicate of #2549

**Comment by sashaqwert** [comment] 2024-04-19 05:59
Duplicate of https://github.com/stascorp/rdpwrap/issues/2549

**Closed as not planned by sashaqwert** 2024-04-19 05:59 UTC
Labels: duplicate
