### ISSUE TITLE
Not support 10.0.19041.1620

### ISSUE THREAD

**Issue by panmyuan** [stascorp/rdpwrap#1824] opened 2022-04-27 03:19 UTC
setting
![image](https://user-images.githubusercontent.com/48192787/165433522-313070af-de64-4cd7-9f03-f77bb6488265.png)

**Comment by sashaqwert** [comment] 2022-04-27 04:49
https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

**Comment by sashaqwert** [comment] 2022-04-27 04:50
Duplicate of https://github.com/stascorp/rdpwrap/issues/1786

**Comment by davidvieira13** [comment] 2022-04-27 08:39
I have the same problem

**Comment by sebaxakerhtc** [comment] 2022-04-27 14:02
> Duplicate of #1786

**Closed as completed by sebaxakerhtc** 2022-04-27 14:02 UTC
