### ISSUE TITLE
not supported 10.0.19041.1503

### ISSUE THREAD

**Issue by DenDeXd** [stascorp/rdpwrap#3328] opened 2024-11-01 18:00 UTC
I cant support it
![image](https://github.com/user-attachments/assets/0abc83d3-8c12-49f2-a268-09e1b110bc8c)

**Comment by binarymaster** [comment] 2024-11-01 18:14
Duplicate of https://github.com/stascorp/rdpwrap/issues/1697.

**Closed as not planned by binarymaster** 2024-11-01 18:14 UTC
Labels: duplicate
