### ISSUE TITLE
10.0.20348.1311 Not Supported (Windows Server 2022 Datacenter 21H2)

### ISSUE THREAD

**Issue by ismilawd** [stascorp/rdpwrap#3336] opened 2024-11-10 05:44 UTC
<img width="406" alt="Screenshot 2024-11-10 at 9 13 59 AM" src="https://github.com/user-attachments/assets/c079b7c5-171a-42ff-ac3d-c6f2f668cb7a">

**Comment by bobo334** [comment] 2024-11-10 08:14
Please, attach your termsrv.dll.

**Comment by ismilawd** [comment] 2024-11-10 08:18
[termsrv.dll.zip](https://github.com/user-attachments/files/17690660/termsrv.dll.zip)

I copied from system32 directory is that ok?

**Comment by bobo334** [comment] 2024-11-10 08:39
Duplicate of #2051

**Comment by ismilawd** [comment] 2024-11-10 08:43
> Duplicate of #2051 

I ran update.bat file but it didnt fix the issue

**Comment by binarymaster** [comment] 2024-11-10 14:50
> I ran update.bat file but it didnt fix the issue

Contact Telegram support group, GitHub is for bug reports. Closed as duplicate.

**Closed as not planned by binarymaster** 2024-11-10 14:50 UTC
Labels: duplicate
