### ISSUE TITLE
RDP Services Error 193: 0xc1

### ISSUE THREAD

**Issue by jatincpa** [stascorp/rdpwrap#2395] opened 2023-11-10 18:03 UTC
I have installed Windows 11 Enterprise on Parallels Desktop (Main machine is Apple Mac Studio M2 Ultra 2023 Release.

I have installed the RDP wrapper following instructions.

Still have issues with the following error Attached image name RDP Error
![RDP Error](https://github.com/stascorp/rdpwrap/assets/6811477/023a6af0-b64b-4408-ba79-a56ff43c4848)

I try to restart the termserver but no success.
Attached Terminal server command response.
![Term Server Message](https://github.com/stascorp/rdpwrap/assets/6811477/4f9eda0b-f231-411c-91cf-d81af6285c9a)

I am not sure how to resolve this.

thanks for any help.

**Comment by binarymaster** [comment] 2023-11-10 18:07
RDP Wrapper hasn't been ported to ARM64 systems yet.

**Comment by jatincpa** [comment] 2023-11-10 18:08
Thank you for quick response so this will not work for now.

**Comment by binarymaster** [comment] 2023-11-10 18:09
Yes, closing as duplicate of #2078.

**Closed as not planned by binarymaster** 2023-11-10 18:09 UTC
