### ISSUE TITLE
10.0.22621.674

### ISSUE THREAD

**Issue by xiwuyun** [stascorp/rdpwrap#2018] opened 2022-10-14 02:43 UTC
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/9782012/termsrv.zip)
Need help with 10.0.22621.674
Thank you

**Comment by sebaxakerhtc** [comment] 2022-10-14 05:36
Duplicate of https://github.com/stascorp/rdpwrap/issues/2006
Look at termsrv.dll version, not the Windows version

**Closed as completed by sebaxakerhtc** 2022-10-14 05:36 UTC
Labels: duplicate

**Comment by xiwuyun** [comment] 2022-10-19 17:40
> Duplicate of #2006 Look at termsrv.dll version, not the Windows version

Thank you
