### ISSUE TITLE
10.0.22621.3447 not supported

### ISSUE THREAD

**Issue by polpo84** [stascorp/rdpwrap#2553] opened 2024-04-10 07:38 UTC
can someone help me?
thanks

**Comment by lucky1luc** [comment] 2024-04-10 09:43
see https://github.com/stascorp/rdpwrap/issues/2552 and https://github.com/stascorp/rdpwrap/issues/2549

**Comment by loyejaotdiqr47123** [comment] 2024-04-11 12:34
Duplicate of #2549

**Comment by sashaqwert** [comment] 2024-04-12 14:45
Duplicate of https://github.com/stascorp/rdpwrap/issues/2549

**Closed as not planned by sashaqwert** 2024-04-12 14:45 UTC
Labels: duplicate
