### ISSUE TITLE
I seem to have issues updating

### ISSUE THREAD

**Issue by ovizii** [stascorp/rdpwrap#393] opened 2018-01-16 10:23 UTC
I was using version 1.5.0.0 for quite some time. Today I downloaded the zip of version 1.6.2.0 and overwrote  the old version without a problem. However I had expected to hit problems as it should be running (I am connected to it). 

Anyway, right click on RDPConf.exe => Details shows version 1.6.2.0  but actually starting RDPConf.exe it shows version 1.5.0.0

Its all working fine, I just wanted to know if anyone else got RDPConf.exe to show the current version or maybe someone can point out what I'm doing wrong?

**Comment by binarymaster** [comment] 2018-01-16 10:33
Duplicate of #100.

**Closed by binarymaster** 2018-01-16 10:33 UTC
