### ISSUE TITLE
Not Working at Win 11 Pro after Update KB5028185 

### ISSUE THREAD

**Issue by funky123** [stascorp/rdpwrap#2295] opened 2023-07-28 11:14 UTC
Latest RDP Wrapper isn't working since Update 

2023-07 Kumulatives Update für Windows 11 Version 22H2 für x64-basierte Systeme (KB5028185)

![image](https://github.com/stascorp/rdpwrap/assets/12056510/5a21bc90-8305-4256-9c15-630e3fd871b7)

**Comment by sashaqwert** [comment] 2023-07-29 09:12
# `termsrv.dll` version != Windows version!

![изображение](https://github.com/stascorp/rdpwrap/assets/24974508/b2f4f576-cc7e-4977-8943-266765ffb393)

**Comment by sashaqwert** [comment] 2023-07-29 09:13
Duplicate of https://github.com/stascorp/rdpwrap/issues/2258

**Closed as not planned by sashaqwert** 2023-07-29 09:13 UTC
Labels: duplicate
