### ISSUE TITLE
Windows 11 10.0.23486.1000 not supported

### ISSUE THREAD

**Issue by DsffqfsNQH** [stascorp/rdpwrap#2265] opened 2023-07-02 03:54 UTC
Windows 11 10.0.23486.1000 not supported

**Comment by DsffqfsNQH** [comment] 2023-07-02 03:56
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/11928663/rdpwrap.zip)

**Comment by loyejaotdiqr47123** [comment] 2023-07-02 06:21
[10.0.23486.1000]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=9B961
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=186C2
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1C145
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=28850
SLInitFunc.x64=New_CSLQuery_Initialize
[10.0.23486.1000-SLInit]
bInitialized.x64      =128F4C
bServerSku.x64        =128F50
lMaxUserSessions.x64  =128F54
bAppServerAllowed.x64 =128F5C
bRemoteConnAllowed.x64=128F64
bMultimonAllowed.x64  =128F68
ulMaxDebugSessions.x64=128F70
bFUSEnabled.x64       =128F74

**Comment by sashaqwert** [comment] 2023-07-02 08:45
Duplicate of https://github.com/stascorp/rdpwrap/issues/2254

**Closed as not planned by sashaqwert** 2023-07-02 08:45 UTC
Labels: duplicate
