### ISSUE TITLE
Win 10 19043.1348 update .ini file

### ISSUE THREAD

**Issue by mispl-2021** [stascorp/rdpwrap#1616] opened 2021-11-13 08:50 UTC

**Comment by mispl-2021** [comment] 2021-11-13 08:52
[19043.1348 .txt](https://github.com/stascorp/rdpwrap/files/7531686/19043.1348.txt)
Replace This .ini Its work

**Comment by sebaxakerhtc** [comment] 2021-11-13 15:47
Duplicate of https://github.com/stascorp/rdpwrap/issues/1595

**Closed as completed by sebaxakerhtc** 2021-11-13 15:47 UTC

**Comment by priyadarshanparida** [comment] 2021-11-16 01:24
> [19043.1348 .txt](https://github.com/stascorp/rdpwrap/files/7531686/19043.1348.txt) Replace This .ini Its work

@mispl-2021, the file you shared worked a treat! Thank you.

**Comment by bazhi-star** [comment] 2021-12-06 01:50
> [19043.1348 .txt.ini](https://github.com/stascorp/rdpwrap/files/7531686/19043.1348.txt)其工作进行替换

Which port should I use?                 3389 warning: "Not listening"

**Comment by bazhi-star** [comment] 2021-12-06 02:00
> [19043.1348 .txt](https://github.com/stascorp/rdpwrap/files/7531686/19043.1348.txt) Replace This .ini Its work

It's OK,  Thanks!  Just restart the remote desktop services.

**Comment by keerthir99** [comment] 2021-12-06 10:00
![Screenshot (5)](https://user-images.githubusercontent.com/94477131/144826353-d4a61897-9eb5-46a5-8ee0-b67b4bb646b8.png)

**Comment by keerthir99** [comment] 2021-12-06 10:02
pls help me sir i will update 11/12/2021 

 19044.1387
