### ISSUE TITLE
Windows 11 10.0.22621.1778 not supported

### ISSUE THREAD

**Issue by chshux** [stascorp/rdpwrap#2271] opened 2023-07-07 13:26 UTC
rdp 10.0.22621.1778
![image](https://github.com/stascorp/rdpwrap/assets/97433796/6573b87a-e3a9-4a65-8c42-d3a120fec74a)

**Comment by sashaqwert** [comment] 2023-07-07 16:21
Duplicate of https://github.com/stascorp/rdpwrap/issues/2213

**Closed as not planned by sashaqwert** 2023-07-07 16:21 UTC
Labels: duplicate
