### ISSUE TITLE
19041.1503 says not listening and not supported

### ISSUE THREAD

**Issue by xsrvv** [stascorp/rdpwrap#1738] opened 2022-02-21 10:09 UTC
![2022-02-21 (2)](https://user-images.githubusercontent.com/100127669/154933912-f8e034da-369b-45f7-9933-421b58305ce0.png)
any help with this issue ive been trying for hours to fix this and nothing has helped

**Comment by d3vilh** [comment] 2022-02-21 12:24
Have the same issue (`Listener state: Not listening [not supported]`) with the latest v.1.6.2 and with latest ini files `.\RDPWInst.exe -w`.

It seems MS released new version of DLL which we cant wrap.

During the re-installation wrapper found new "Terminal Services version: **10.0.19041.1387**"
and reports:
```
[-] This version of Terminal Services is not supported.
Send your termsrv.dll to project developer for support.
```

here is the new [trmsvr.dll](https://github.com/d3vilh/my_files/blob/1298048abdc9db5d6d683e82b7afe4396fb18077/termsrv.dll) I have.

winver reports: `Win10, Version 20H2 (OS Build 19042.1466)`


**Update:**
With the latest ini file from [here](https://github.com/sebaxakerhtc/rdpwrap.ini/blob/6b2d18a1aace5ad51c7f5992295dbb4a29048f3f/rdpwrap.ini) Listener state is `[fully supported]` but Listener is in `"Not listening"` status.

**Update2:**
I really don't have DRP-tcp listener running for some reason. 
you can check it by running following in shell under windows root:
```qwinsta```
there should be RDP-tcp listener running.
As a fix MS recommends to export registry branch from the working computer :)

**Comment by sebaxakerhtc** [comment] 2022-02-21 20:08
Duplicate of https://github.com/stascorp/rdpwrap/issues/1697

**Closed as completed by sebaxakerhtc** 2022-02-21 20:08 UTC
