### ISSUE TITLE
support needed for v.10.0.18362.267

### ISSUE THREAD

**Issue by patzelbert** [stascorp/rdpwrap#955] opened 2020-01-04 14:30 UTC
v.10.0.18362.267

**Comment by s0nic9** [comment] 2020-01-04 15:56
https://github.com/stascorp/rdpwrap/pull/859

**Comment by buzon7** [comment] 2020-01-10 16:59
tried everyting here, including reg fix in #954. nothing. termserv just dies (((

**Comment by DamianMorozov** [comment] 2020-01-11 10:10
> #859

It's working, thank you for support.

**Comment by l-enenen** [comment] 2020-01-24 01:22
same thing happen for me, I tried 859 as well
![image](https://user-images.githubusercontent.com/59414803/73037395-baeade80-3e03-11ea-8e9b-408551b6c2a1.png)

**Comment by sebaxakerhtc** [comment] 2022-06-20 10:19
Duplicate of https://github.com/stascorp/rdpwrap/issues/871

**Closed as completed by sebaxakerhtc** 2022-06-20 10:19 UTC
