### ISSUE TITLE
10.0.19044.1566 Not Supported

### ISSUE THREAD

**Issue by spike63995** [stascorp/rdpwrap#1743] opened 2022-02-23 06:57 UTC
Can I please get an ini and/or termservice dll for 10.0.19044.1566 windows 10?

Thanks.

**Comment by sebaxakerhtc** [comment] 2022-02-24 08:15
Duplicate of https://github.com/stascorp/rdpwrap/issues/1725

**Closed as completed by sebaxakerhtc** 2022-02-24 08:15 UTC

**Comment by gitsorcor** [comment] 2022-02-24 08:56
hi
we would want fix for 1904**4**, not 1904**1**
the duplicate is for 1904**1**, and not running for me (i have10.0.1904**4**.1566)
thank's for job

**Comment by sebaxakerhtc** [comment] 2022-02-24 09:03
> hi we would want fix for 1904**4**, not 1904**1** the duplicate is for 1904**1**, and not running for me (i have10.0.1904**4**.1566) thank's for job

See carefuly your termsrv.dll version and say me if it 19044 😉

**Comment by spike63995** [comment] 2022-02-24 09:49
> 

But I still don't know how to fix it? Are you saying I can use the term service from that other issue? Because I tried that and I had to system restore cause the remote services got messed and I couldn't load Windows.

**Comment by gitsorcor** [comment] 2022-02-24 10:31
sorry for loose your time, it was just that i don't reboot computer after change the rdwrap.ini file...
That's work ! :)

in the read me, frequently asked questions, maybe you can add these lines 
 - install steps 
         launch in admin mode install.bat
        get the rdwrap.ini file for your windows version in issue section
       replace the ‪C:\Program Files\RDP Wrapper\rdpwrap.ini by this one
       add users in "Remote Desktop Users" group 
       reboot !!!!
      
one more time, thanks :)

**Comment by spike63995** [comment] 2022-02-24 10:35
Glad it worked for you, but simply replacing the ini didn't work for me, stopped term service, replaced ini, turned term service service back on, rebooted and nothing changed.

**Comment by sebaxakerhtc** [comment] 2022-02-24 10:37
> Glad it worked for you, but simply replacing the ini didn't work for me, stopped term service, replaced ini, turned term service service back on, rebooted and nothing changed.

Try autoupdate from asmtron or my modded rdpwrapper

**Comment by spike63995** [comment] 2022-02-24 11:52
> > Glad it worked for you, but simply replacing the ini didn't work for me, stopped term service, replaced ini, turned term service service back on, rebooted and nothing changed.
> 
> Try autoupdate from asmtron or my modded rdpwrapper

Was I not supposed to use the black version? I tried installing it and now my Remote Desktop Services service won't start.

EDIT: I used an image to restore a proper version of termservice.dll and restored the regedit parameters for RDP so it would start the service again. I tried asmtron this time and it works fine now. Thanks!
