### ISSUE TITLE
Windows 11 PRO - 22H2 10.0.19045.3393 not supported

### ISSUE THREAD

**Issue by machi67** [stascorp/rdpwrap#2321] opened 2023-08-26 20:47 UTC
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/12446694/termsrv.zip)

**Comment by sashaqwert** [comment] 2023-08-29 15:03
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by sashaqwert** [comment] 2023-08-29 15:06
Duplicate of https://github.com/stascorp/rdpwrap/issues/2289

**Closed as not planned by sashaqwert** 2023-08-29 15:06 UTC
Labels: duplicate
