### ISSUE TITLE
rdpwrap + windows10 + remotefx

### ISSUE THREAD

**Issue by fabry2206** [stascorp/rdpwrap#208] opened 2017-02-15 09:55 UTC
Hello, I have the following configuration:
Host Windows Server 2012 Hyper-V
Client Windows 10 build 1607
I have installed rdpwrap and it is fully functional. If I enable  RemoteFX in the client (windows10), I can not more connect remotely with multiple users.

**Comment by HwangTW** [comment] 2017-02-25 03:58
I have same problem too
host: Windows server 2016 Hyper-V
clent Windows 10 build 1607

but I find some thing interesting
on windows 10 1607 clean install , it working
after update that aren't working
so I think this problem caused by update

**Comment by fabry2206** [comment] 2017-02-27 08:20
Great. I will do this test.

**Comment by HwangTW** [comment] 2017-03-04 08:03
now i check one thing
this problem just in hyper-v
else vm can run rdp wrappe
so maybe is hyper-v problem?

**Comment by HwangTW** [comment] 2017-03-04 08:06
because I change my system to windows10 form server2016 then install hyper-V
rdp wrapper is not working.

**Comment by binarymaster** [comment] 2017-03-11 12:09
This issue seems similar to #59, so I close it.

Please move the conversation to #127.

**Closed by binarymaster** 2017-03-11 12:09 UTC
