### ISSUE TITLE
not supported Win 10 21H1 19043.1645

### ISSUE THREAD

**Issue by xuxunjiang** [stascorp/rdpwrap#1808] opened 2022-04-14 08:09 UTC
windows 10  19043.1645, request the latest version  [RDPwrap .ini],  thanks.

**Comment by sashaqwert** [comment] 2022-04-14 12:39
RDPConf screenshot, please!

Your version is 10.0.1904**1**.XXX.
Please, see this in RDPConf and rename your issue.

**Comment by gasl20** [comment] 2022-04-14 13:28
![2022-04-14_09h27_37](https://user-images.githubusercontent.com/66622710/163400842-a550b88a-8390-491a-b864-fa995d5d45b4.png)
![2022-04-14_09h27_17](https://user-images.githubusercontent.com/66622710/163400847-b3a98950-8b85-4035-9989-aaba7bc2025e.png)

**Comment by gasl20** [comment] 2022-04-14 13:38
this helping for me
https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

**Comment by sashaqwert** [comment] 2022-04-14 16:48
Duplicate of https://github.com/stascorp/rdpwrap/issues/1786

**Comment by sebaxakerhtc** [comment] 2022-04-15 07:23
> Duplicate of #1786

**Closed as completed by sebaxakerhtc** 2022-04-15 07:23 UTC

**Comment by Jorge888812** [comment] 2022-05-14 00:15
> this helping for me https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

tankyou
