### ISSUE TITLE
[22631.4602] / 10.0.22621.4541 listener state is not listening

### ISSUE THREAD

**Issue by jju2ee** [stascorp/rdpwrap#3390] opened 2024-12-16 04:40 UTC
![image](https://github.com/user-attachments/assets/860e42bb-4eeb-42f3-a6e1-86a525af0040)

This is my OS build number (22631.4602)

<img width="267" alt="image" src="https://github.com/user-attachments/assets/c6c3df2a-0d6a-4685-bd43-f0b8b58bb975" />

And this is my RDP Wrapper Config (which version is 10.0.22621.4541).
I searched and downloaded this version according to some case in this issue tab.

Could you give any advise if the RDP Wrapper version is correct ?
Because remote network connection is still not working.

**Comment by binarymaster** [comment] 2024-12-16 10:32
Duplicate of https://github.com/stascorp/rdpwrap/issues/3354.

**Closed as not planned by binarymaster** 2024-12-16 10:32 UTC
Labels: duplicate
