### ISSUE TITLE
10.0.22621.4541 Not Supported

### ISSUE THREAD

**Issue by mephisto0127** [stascorp/rdpwrap#3360] opened 2024-11-23 00:15 UTC
![image](https://github.com/user-attachments/assets/0b1691ad-7ac2-419d-853c-9cfca7b9bf07)
Help me!

**Comment by binarymaster** [comment] 2024-11-23 10:06
Duplicate of https://github.com/stascorp/rdpwrap/issues/3354.

**Closed as not planned by binarymaster** 2024-11-23 10:06 UTC
Labels: duplicate
