### ISSUE TITLE
Working setup for win10 home v18362.267 through 18362.418 + win10privacy inside.

### ISSUE THREAD

**Issue by SobieskiCodes** [stascorp/rdpwrap#906] opened 2019-10-14 13:04 UTC
https://github.com/SobieskiCodes/RDPWrap
Fairly straight forward, tested on every build between (this should be the newest build).

> Download the full zip and extract.
> Run install.bat
> Move all files from the zip into /programfiles/rdpwrap
> Run autoupdate as admin
> Run RDPConf.exe to verify working condition.
> Right-click W10Privacy.exe and choose Run as administrator from the context menu. Choose to make a system restore point. It’s also worth making a full system backup (just in case).
> Go to Extras > Windows Updates to manage the options. There are six different check boxes.
> Check the first five options
> Click Set changed settings

I take no credit for any of the tools, just put it all together after digging through everything.

**Comment by fdiperna** [comment] 2019-10-15 15:32
Hi..
After reinstall RDP Wrapper, works fine with  18362.418, but every user wich open session, must wait, at less, 5 mins to view their desktop.... it is a bug or i need to investigate why in the OS?
Thank you in advance....

**Comment by fdiperna** [comment] 2019-10-15 15:34
sorry.. "at least"

**Comment by SobieskiCodes** [comment] 2019-10-15 15:36
Also running .418 at the moment, no delay for me (only have 3 users using it - only issue i've come across is the screen flicker when someone else connects).
I'd check resource usage.

**Comment by fdiperna** [comment] 2019-10-15 16:11
ok, i´ll check... thank you.

**Comment by flydvorkin** [comment] 2019-10-31 15:13
18362.449 - working.
Check ini file from: https://github.com/stascorp/rdpwrap/issues/902
by @Techgoduk post.

If no C:\windows\system32\rfxvmt.dll file, then install
%windir%\servicing\Packages\Microsoft-Windows-Virtualization-RemoteFX-User-Mode-Transport-Package~*.mum
package by dism

**Comment by SobieskiCodes** [comment] 2019-10-31 16:30
> 
> 
> 18362.449 - working.
> Check ini file from: #902
> by @Techgoduk post.
> 
> If no C:\windows\system32\rfxvmt.dll file, then install
> %windir%\servicing\Packages\Microsoft-Windows-Virtualization-RemoteFX-User-Mode-Transport-Package~*.mum
> package by dism

Awesome, I'll package it this weekend.

**Comment by flydvorkin** [comment] 2019-10-31 16:36
> > 18362.449 - working.
> > Check ini file from: #902
> > by @Techgoduk post.
> > If no C:\windows\system32\rfxvmt.dll file, then install
> > %windir%\servicing\Packages\Microsoft-Windows-Virtualization-RemoteFX-User-Mode-Transport-Package~*.mum
> > package by dism
> 
> Awesome, I'll package it this weekend.

Thanx, but original Stascorp wrapper work good.
Why should we use another product?

**Comment by SobieskiCodes** [comment] 2019-10-31 16:41
> 
> 
> > > 18362.449 - working.
> > > Check ini file from: #902
> > > by @Techgoduk post.
> > > If no C:\windows\system32\rfxvmt.dll file, then install
> > > %windir%\servicing\Packages\Microsoft-Windows-Virtualization-RemoteFX-User-Mode-Transport-Package~*.mum
> > > package by dism
> > 
> > 
> > Awesome, I'll package it this weekend.
> 
> Thanx, but original Stascorp wrapper work good.
> Why should we use another product?

If it works you don't have to :) mine is just all of them compiled together so you don't have to change/edit worry about anything. In no way shape or form would i say you should use it, but its there for those that don't understand the process.

**Comment by gamma-577** [comment] 2019-11-01 10:14
@SobieskiCodes ,

Thank you for compiling the code. Very useful learning for me.

I was about to install the wrapper on my 32 bit Enterprise. I had a quick look at rdpwrap.ini but there are no entries for .x86 in [10.0.18362.267] and [10.0.18362.267-SLInit] sections. I am running 32 bit Enterprise version1903/18362.418 .

Am I missing something obvious here? Can I go ahead and install the wrapper?

Thanks once again.

-Gamma

**Comment by Techgoduk** [comment] 2019-11-01 10:28
@gamma-577, are using the original rdpwrap.ini? Try my .ini file from here https://github.com/stascorp/rdpwrap/issues/902#issuecomment-541559295

**Comment by gamma-577** [comment] 2019-11-01 10:43
@Techgoduk ,

I have the ini file from the link https://github.com/SobieskiCodes/RDPWrap , which is same as mentioned at the top of this thread.

But thanks for your link. I saw your ini file does have .x86 entries. Will give it a try! :-)

-Gamma

**Comment by SobieskiCodes** [comment] 2019-11-01 11:12
> 
> 
> @SobieskiCodes ,
> 
> Thank you for compiling the code. Very useful learning for me.
> 
> I was about to install the wrapper on my 32 bit Enterprise. I had a quick look at rdpwrap.ini but there are no entries for .x86 in [10.0.18362.267] and [10.0.18362.267-SLInit] sections. I am running 32 bit Enterprise version1903/18362.418 .
> 
> Am I missing something obvious here? Can I go ahead and install the wrapper?
> 
> Thanks once again.
> 
> -Gamma

I don't have any 32 bit devices to test with - you'll have to let me know :)

**Comment by gamma-577** [comment] 2019-11-01 11:13
@Techgoduk ,

Aha! Your file is working beautifully well. Thanks for the x86 offset codes. :-)

-Gamma

**Comment by gamma-577** [comment] 2019-11-01 11:28
> 
> I don't have any 32 bit devices to test with - you'll have to let me know :)

@SobieskiCodes , Yes Techgoduk's ini file worked well on my 32 bit enterprise version 18362.418 (termserv.dll version 18362.267). Thank you! :-)

-Gamma

**Comment by sicwolf** [comment] 2020-01-09 16:06
It work well for me with below steps

https://github.com/SobieskiCodes/RDPWrap

Download the full zip and extract.
Run install.bat
Move all files from the zip into /programfiles/rdpwrap
Run autoupdate as admin
Run RDPConf.exe to verify working condition. (It works well till this steps)

**Comment by sebaxakerhtc** [comment] 2022-06-20 10:07
Duplicate of https://github.com/stascorp/rdpwrap/issues/902

**Closed as completed by sebaxakerhtc** 2022-06-20 10:07 UTC
