### ISSUE TITLE
windows 10  64bit  21h2 not supported version 19044.1288

### ISSUE THREAD

**Issue by Lsunny2021** [stascorp/rdpwrap#1674] opened 2021-12-29 04:08 UTC
![image](https://user-images.githubusercontent.com/96612545/147626318-fbb21366-9af4-4156-ae03-240d2e234420.png)

**Comment by Lsunny2021** [comment] 2021-12-29 05:32
ok。
The ini data come from: https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

**Comment by sebaxakerhtc** [comment] 2021-12-29 08:53
> ok。 The ini data come from: https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

Is your Windows x86 or x64?

**Comment by sebaxakerhtc** [comment] 2021-12-29 08:54
Duplicate of https://github.com/stascorp/rdpwrap/issues/1509

**Closed as completed by sebaxakerhtc** 2021-12-29 08:54 UTC
