### ISSUE TITLE
Windows 10 21H2 19041.2075 [not supported]

### ISSUE THREAD

**Issue by paranormalific** [stascorp/rdpwrap#2139] opened 2023-03-14 13:15 UTC
Hi, don`t work :( Please help!

![QIP Shot - Screen 051](https://user-images.githubusercontent.com/35814891/225011580-62d39fb2-4ed1-4b48-8c10-fc6846434996.png)
![QIP Shot - Screen 053](https://user-images.githubusercontent.com/35814891/225098736-04364adb-437a-473b-9df9-b513893424c8.png)

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/10968919/termsrv.zip)

**Comment by sashaqwert** [comment] 2023-03-15 06:03
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992

**Closed as not planned by sashaqwert** 2023-03-15 06:03 UTC
Labels: duplicate
