### ISSUE TITLE
Windows Update to new version 10.0.17134.1 and can't connect

### ISSUE THREAD

**Issue by jdiazcdmx** [stascorp/rdpwrap#481] opened 2018-05-14 17:53 UTC
Hello,

I updated my windows and RDP stopped working, in RDPConf i show a new version 10.0.17134.1. 
Can someone help me with this problem?
![screenshot from 2018-05-14 12-51-48](https://user-images.githubusercontent.com/39276205/40014246-a5d02562-5775-11e8-9792-3c3e0a777e12.png)

**Comment by binarymaster** [comment] 2018-05-14 17:56
Duplicate of #456.

**Closed by binarymaster** 2018-05-14 17:56 UTC
