### ISSUE TITLE
10.0.17763.3232 / Server 2019 not supported

### ISSUE THREAD

**Issue by CryRocks** [stascorp/rdpwrap#2244] opened 2023-06-10 19:35 UTC
![mstsc_QA4EJIAUyb](https://github.com/stascorp/rdpwrap/assets/107412582/e751a9a3-0445-42aa-b4c1-f3812d6b8557)
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/11713161/termsrv.zip)

thanks a lot!

**Comment by CryRocks** [comment] 2023-06-10 19:52
so i found the 3232 version and installed it, but it doesn't show fully supported. Started reinstall as admin etc. but didn't work.

winver is saying 10.0.17763.3287 not sure if that has something to do with it.

**Comment by sashaqwert** [comment] 2023-06-11 13:57
Duplicate of https://github.com/stascorp/rdpwrap/issues/1940

**Closed as not planned by sashaqwert** 2023-06-11 13:57 UTC
Labels: duplicate

**Comment by sashaqwert** [comment] 2023-06-11 14:01
> Started reinstall as admin etc. but didn't work

Try modded version by sebaxakerhtc: https://github.com/sebaxakerhtc/rdpwrap/releases

**Comment by CryRocks** [comment] 2023-06-11 16:51
![grafik](https://github.com/stascorp/rdpwrap/assets/107412582/b775b917-be37-419f-ae8b-9e53c145eacd)
seems to work now, thanks a lot! :)
