### ISSUE TITLE
rdpwrap v1.6.2 Not working for Windows 10 Home Version - 21H1 & OS Build - 19043.1415

### ISSUE THREAD

**Issue by priyadarshanparida** [stascorp/rdpwrap#1658] opened 2021-12-14 21:47 UTC
rdpwrap worked fine on my laptop. It has stopped working after the latest patch installation. Can someone share the updated .ini file please? Here are the details:
Edition: Windows 10 Home
Version: 21H1
OS build: 19043.1415

This is what I see on running rdpconf (as an administrator)
Wrapper state: Installed ver. 1.5.0.0
Service state: Running ver. 10.0.19041.1202
Listener state: Not listening [not supported]

![rdpwrap](https://user-images.githubusercontent.com/16783956/146084550-07e0a6f4-978b-4d09-b772-676938ece6e1.jpg)

**Comment by sebaxakerhtc** [comment] 2021-12-15 06:07
Duplicate of https://github.com/stascorp/rdpwrap/issues/1630

**Closed as completed by sebaxakerhtc** 2021-12-15 06:07 UTC

**Comment by xticaox** [comment] 2021-12-15 22:30
preciso de ajuda pra configura tbm

**Comment by priyadarshanparida** [comment] 2021-12-16 01:40
I am not sure why this was closed. I am unable to find a solution for 19043.1415 in issue #1630.
@sebaxakerhtc can you please share clear steps I should follow to fix this issue?

**Comment by sebaxakerhtc** [comment] 2021-12-16 06:40
> solution for 19043.1415 in issue

Look at your screenshot - termsrv.dll version matter. Windows version doesn't matter.
Clear steps:
Use my [modded version](https://github.com/sebaxakerhtc/rdpwrap/releases/tag/v1.8.6.1) 
or
Download Autoupdate.bat and my ini
