### ISSUE TITLE
Windows 10 19045.3086 not supported

### ISSUE THREAD

**Issue by andreiyv** [stascorp/rdpwrap#2256] opened 2023-06-27 15:16 UTC
[termsrv.zip](https://disk.yandex.ru/d/GelSiOhLusGWTA)

**Comment by sashaqwert** [comment] 2023-06-27 16:57
> [termsrv.zip](https://disk.yandex.ru/d/GelSiOhLusGWTA)

Your version is 10.0.19041.2913

**Comment by sashaqwert** [comment] 2023-06-27 16:58
Duplicate of https://github.com/stascorp/rdpwrap/issues/2180

**Closed as not planned by sashaqwert** 2023-06-27 16:58 UTC
Labels: duplicate
