### ISSUE TITLE
Windows 10 64-bit version 10.0.19041.1741 not working

### ISSUE THREAD

**Issue by GeneXiao** [stascorp/rdpwrap#1978] opened 2022-09-04 08:50 UTC
![rdpwrap](https://user-images.githubusercontent.com/100252418/188305307-d35d6ef6-fa31-41dc-b69f-29bf6d2cc87c.png)

**Comment by QuentinBubu** [comment] 2022-09-04 09:40
https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

**Comment by sebaxakerhtc** [comment] 2022-09-05 07:30
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881

**Closed as completed by sebaxakerhtc** 2022-09-05 07:30 UTC
