### ISSUE TITLE
Support required for 10.0.18363.535 

### ISSUE THREAD

**Issue by qwepirt** [stascorp/rdpwrap#952] opened 2020-01-02 01:09 UTC

**Comment by Feriwa** [comment] 2020-01-07 09:51
Same for us. Our new installed Win 10 is version 1909 Build  10.0.18363.535
Thanks in advance

**Comment by s0nic9** [comment] 2020-01-08 12:48
use updated version https://github.com/stascorp/rdpwrap/pull/859

**Comment by Feriwa** [comment] 2020-01-08 14:55
thx it works!

**Comment by ziggysnorkel** [comment] 2020-01-09 02:49
Hi. Would you please detail how you got it to work step by step? I'm not really that sophisticated with this stuff and I'm trying to learn.  Thank you so much!

**Comment by Feriwa** [comment] 2020-01-09 10:23
Download 1.6.2 from Code [releases](https://github.com/stascorp/rdpwrap/releases) and
autoupdate-v07.09.2019.zip from #859 ; follow the instructions  inside:

INSTALL of RDP Wrapper and Autoupdater
 ======================================

 1. Copy the files from the archive "RDPWrap-v1.6.2.zip" (or newer) to the "%ProgramFiles%\RDP Wrapper" directory

    DO NOT use other location to install/extract the RDP Wrapper files.
    USE ONLY the "%ProgramFiles%\RDP Wrapper" directory (normally C:\Program Files\RDP Wrapper)


 2. Copy the files/folder from the archive "autoupdate-v07.09.2019.zip" (or newer) to the "%ProgramFiles%\RDP Wrapper" directory


 3. To enable autorun of autoupdate.bat on system startup, run the folling helper batch file as administrator:

    "%ProgramFiles%\RDP Wrapper\helper\autoupdate__enable_autorun_on_startup.bat"


 4. Set in your Antivirus/WindowsDefender an exclusion on the folder "%ProgramFiles%\RDP Wrapper" to prevent the deletion of RDP Wrapper files


 5. Now you can use the autoupdate batch file to install and update the RDP Wrapper. Please run autoupdate.bat as administrator:

   "%ProgramFiles%\RDP Wrapper\autoupdate.bat"

**Comment by ziggysnorkel** [comment] 2020-01-09 18:46
Thank you so much.

**Comment by qwepirt** [comment] 2020-01-10 12:56
It works，Thank you!

**Comment by Silver7758** [comment] 2020-01-22 11:40
@Feriwa I've installed the Autoupdater, however, it didn't have worked. I believe I need some help. Thanks in advance! 
![image](https://user-images.githubusercontent.com/46341546/72891243-f2a44880-3d67-11ea-8ab1-40fe14d51b3e.png)

**Edit: The issue has been resolved. The Autoupdater only supports RDP Wrapper to be installed inside "C:\Program Files\RDP Wrapper". Not any other paths.**

**Comment by muaddib912** [comment] 2020-01-27 23:10
I tried this but was unable to run the RDP service afterward, gives the standard error of Error 126, the specified module could not be found.

Is there a fix for this windows build for Windows 10 Enterprise as that is what we are running.

**Comment by sebaxakerhtc** [comment] 2022-06-20 10:19
Duplicate of https://github.com/stascorp/rdpwrap/issues/871

**Closed as completed by sebaxakerhtc** 2022-06-20 10:19 UTC
