### ISSUE TITLE
Não suportado WIN10 21H2 19044.1741

### ISSUE THREAD

**Issue by fernandohcmelo** [stascorp/rdpwrap#1896] opened 2022-06-13 12:13 UTC
Olá, alguém teria essa versão atualizada ?

**Comment by fernandohcmelo** [comment] 2022-06-13 12:15
![not](https://user-images.githubusercontent.com/61550415/173351374-7a8c8eaa-dfcb-42aa-bab4-50c0fc5f26d0.png)

**Comment by sashaqwert** [comment] 2022-06-13 15:10
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881

**Comment by MKKLR21** [comment] 2022-06-15 09:15
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/8907813/termsrv.zip)
Here's the termsrv.dll

**Comment by sebaxakerhtc** [comment] 2022-06-15 15:42
> Duplicate of #1881

**Closed as completed by sebaxakerhtc** 2022-06-15 15:42 UTC
