### ISSUE TITLE
Access denied windows server

### ISSUE THREAD

**Issue by Mariojd1980** [stascorp/rdpwrap#3288] opened 2024-10-03 15:03 UTC
Good morning, when I want to log in with any user it gives me access denied. rpwrap is all green and I connect to the server but the only user that lets me access is the administrator, any other user does not let me, I already deleted the user and created it again, I also checked the permissions and everything is ok. I attached screenshots
[Archivos.zip](https://github.com/user-attachments/files/17246177/Archivos.zip)

**Comment by binarymaster** [comment] 2024-10-03 16:48
Technically it's duplicate of #2080 / #2224 / #2227 => #391 (which has been addressed in the installer).

Feel free to use ProcMon or API Monitor to check where the privileges are missing.

**Comment by franciscoalcibar** [comment] 2024-10-14 23:21
[10.0.17763.4252]
SingleUserPatch.x64=1
SingleUserOffset.x64=17362
SingleUserCode.x64=mov_eax_1_nop_1
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1FF75
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=8A321
LocalOnlyCode.x64=jmpshort
SLInitHook.x64=1
SLInitOffset.x64=2C06C
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.17763.4252-SLInit]
bServerSku.x64=114D20
bRemoteConnAllowed.x64=114D30
bFUSEnabled.x64=114D3C
bAppServerAllowed.x64=114D2C
bMultimonAllowed.x64=114D34
lMaxUserSessions.x64=114D24
ulMaxDebugSessions.x64=114D38
bInitialized.x64=114D1C

**Closed as completed** 2024-10-25 17:04 UTC
