### ISSUE TITLE
Listener state is "Not Listening".

### ISSUE THREAD

**Issue by alxndrr** [stascorp/rdpwrap#266] opened 2017-06-22 22:20 UTC
Listener state - not listening in RDPConf. How to fix it?
OS: Windows 10 Home 1703 (build 15063.413).

**Comment by shinyplastic** [comment] 2017-06-23 00:52
I think this is a duplicate of [#194](https://github.com/stascorp/rdpwrap/issues/194), and the very smart and dedicated folk are looking at it.

**Closed** 2017-06-23 07:02 UTC
Labels: duplicate
