### ISSUE TITLE
Need Help 10.0.2621.1825

### ISSUE THREAD

**Issue by heerxingen** [stascorp/rdpwrap#2225] opened 2023-05-28 12:42 UTC
<img width="294" alt="image" src="https://github.com/stascorp/rdpwrap/assets/102276349/bdf398fd-ffa6-48c9-bad0-6249f707150f">

**Comment by sashaqwert** [comment] 2023-05-28 12:52
Duplicate of https://github.com/stascorp/rdpwrap/issues/2221

**Closed as not planned by sashaqwert** 2023-05-28 12:52 UTC
Labels: duplicate
