### ISSUE TITLE
Not listening 10.0.19041.1566 (W10 x86)

### ISSUE THREAD

**Issue by LorenzoTecnab** [stascorp/rdpwrap#1801] opened 2022-04-06 10:36 UTC
From yesterday system tell me not listening.
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/8426092/rdpwrap.zip)

**Comment by LorenzoTecnab** [comment] 2022-04-06 15:18
Excuse me, i èposted the wrong file. Here the termsrv.dll (x86)
Can you update the .ini?
Thx
Lorenzo
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/8428285/termsrv.zip)

**Comment by sebaxakerhtc** [comment] 2022-04-07 20:09
Duplicate of https://github.com/stascorp/rdpwrap/issues/1725

**Closed as completed by sebaxakerhtc** 2022-04-07 20:09 UTC
