### ISSUE TITLE
ver 10.0.19041.2075 fully supported but multiple RDP d'ont work

### ISSUE THREAD

**Issue by Splifshow** [stascorp/rdpwrap#2104] opened 2023-02-08 18:07 UTC
HI,
RDP Wrapper Configuration is full OK.

But when i test, I can only connect one sessions. The other connections says me (in french) : le nombre de connexions à cet ordinateur est limité et toues les connexions sont actuellement utilisées.

**Comment by sashaqwert** [comment] 2023-02-09 06:54
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992

**Comment by sashaqwert** [comment] 2023-02-09 06:55
Try:
1. Download RDP Wrapper 1.6.2 and extract this to any directory.
2. Place `rdpwrap.ini` in the same directory.
3. Open CMD as administrator
4. Execute this commands
```
cd C:\path\to\directory\
rdpwinst -u -k
rdpwinst -i
```
5. Enjoy!

Original message: https://t.me/rdpwrap/49131

**Closed as not planned by sashaqwert** 2023-02-09 06:54 UTC
Labels: duplicate
