### ISSUE TITLE
rdp listener's state not supported vv 10.0.19041.662

### ISSUE THREAD

**Issue by mhtkumar0025** [stascorp/rdpwrap#1233] opened 2020-12-09 07:03 UTC
Please help. 
it was working earlier but idk why from 2-3 days it's not working. I'm attaching the screenshots. Please help on urgent basis.
![rdp ss](https://user-images.githubusercontent.com/74907458/101596278-cd213b80-3a1a-11eb-943e-7754264b9830.PNG)
![version ss](https://user-images.githubusercontent.com/74907458/101596285-ce526880-3a1a-11eb-8d63-e7fabf1e416d.PNG)

**Comment by SantaDamon** [comment] 2020-12-09 08:37
It works https://yadi.sk/d/thuPIABnGuZZ-Q
19042.685

**Comment by asmtron** [comment] 2020-12-09 08:44
add support for 10.0.19041.662 (x64) on rdpwrap autoupdate https://github.com/stascorp/rdpwrap/pull/1160

please upload the 32Bit version of termsrv.dll v.10.0.19041.662

**Comment by ghost** [comment] 2020-12-09 09:14
doesn't work

**Comment by mhtkumar0025** [comment] 2020-12-09 09:28
UMMM, DO I HAVE TO UPLOAD ANYTHING OR WHAT? I'M NOT A TECHIE AS SUCH BUT CAN UNDERSTAND IF YOU EXPLAIN ME WITH STEPS. 

PLEASE HELP ME AS I AM NOT ABLE TO RUN MY CLIENT.

**Comment by ghost** [comment] 2020-12-09 10:00
Hi everyone !  It doesn't work even when i've upgraded from my legal home version to a cracked pro version , yesterday "update" did successfully f*ck again the entire RDP ..
i did update, autoupdate and try all the versions of the corresponding .ini files

10.0.19041.662 (x64)

OS BUILD: 19042.685

but rdp wrapper shows this:
![Clip116](https://user-images.githubusercontent.com/65355324/101614860-bd4f2a80-3a0d-11eb-9e25-6eddc0af3062.png)


RDP Wrapper still  doesn't  work with this build. 

I've tried several times uninstall , reinstall , reboot, etc.. every possible combinations ... still doesn't work

![Screenshot 2020-12-09 12 33 22](https://user-images.githubusercontent.com/65355324/101625010-1d000280-3a1b-11eb-96e0-8e0156e871f4.png)

Any help would appreciated

'Thank you" "Dear" Microsoft for the f*cking this feature month by month !

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/5665638/termsrv.zip)

**Comment by 1Pekol** [comment] 2020-12-09 10:17
Please, can someone clever solve 32bit termsrv.dll 10.0.19041.662. Thanks
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/5665133/termsrv.zip)

**Comment by card0384** [comment] 2020-12-09 12:51
To the developer of rdpwrapper: It would be good if the screenshot of the rdpwrapper says X86 or X64 somewhere - this makes troubleshooting a lot easier

**Comment by robbak** [comment] 2020-12-09 13:00
Unfortunately, the developer and only committer for this project is no
longer involved in it. When he was last pinged, he told the person to stop,
because he has abandoned it.

So, if anyone has skills to maintain this, it is crying out to be rehomed
on someone else's repo, and the last 3 or 4 years of pull request be merged.

**Comment by zebwqfox** [comment] 2020-12-09 16:33
请尝试删除名为“KB4592438”的更新，然后重新启动
Please try to remove the update named "KB4592438" and restart
![屏幕截图 2020-12-10 001957](https://user-images.githubusercontent.com/46518540/101657726-2de25f80-3a7f-11eb-94db-d1d691a4a22e.png)
![屏幕截图 2020-12-10 002203](https://user-images.githubusercontent.com/46518540/101657730-2f138c80-3a7f-11eb-8e9a-b35ef8701d14.png)

**Comment by asmtron** [comment] 2020-12-09 21:17
@1Pekol: add support for 32bit termsrv.dll 10.0.19041.662

@mailor33: run autoupdate again (as admin) an it should work

[autoupdate ](https://github.com/stascorp/rdpwrap/pull/1160) (recommended) or [ini ](https://raw.githubusercontent.com/asmtron/rdpwrap/master/res/rdpwrap.ini)

**Comment by ghost** [comment] 2020-12-10 00:53
> @1Pekol: add support for 32bit termsrv.dll 10.0.19041.662
> 
> @mailor33: run autoupdate again (as admin) an it should work
> 
> [autoupdate ](https://github.com/stascorp/rdpwrap/pull/1160) (recommended) or [ini ](https://raw.githubusercontent.com/asmtron/rdpwrap/master/res/rdpwrap.ini)

Thank you so much ! This finally works !

**Comment by SeanLauSL** [comment] 2020-12-10 05:22
> @1Pekol: add support for 32bit termsrv.dll 10.0.19041.662
> 
> @mailor33: run autoupdate again (as admin) an it should work
> 
> [autoupdate ](https://github.com/stascorp/rdpwrap/pull/1160) (recommended) or [ini ](https://raw.githubusercontent.com/asmtron/rdpwrap/master/res/rdpwrap.ini)

[autoupdate](https://github.com/stascorp/rdpwrap/pull/1160) didn't work, but [ini ](https://raw.githubusercontent.com/asmtron/rdpwrap/master/res/rdpwrap.ini) solved my problem. Thank you so much!!!

**Comment by mhtkumar0025** [comment] 2020-12-10 06:16
![SS](https://user-images.githubusercontent.com/74907458/101728854-25b90d00-3add-11eb-956d-d5ecb139c401.PNG)
 Everythig worked, the status on RDP is all green but when I run from the client this is the problem. Please help me solve this too. I have tried restarting both my PC's and switching on/off my routher and also added a registry edit. 


Please Help

**Comment by robbak** [comment] 2020-12-10 06:23
There's a number of registry and policy tweaks to do to solve that one. It
is an rdp issue, not to do with the wrapper. Search on the text of that
message and you'll find suggestions.

**Comment by 1Pekol** [comment] 2020-12-10 08:50
@asmtron: thaks a lot, version 32bit 10.0.19041.662 wokrs fine with your ini

**Comment by Maddoccc** [comment] 2020-12-10 13:02
> 
> 
> It works https://yadi.sk/d/thuPIABnGuZZ-Q
> 19042.685

Hi. Can't speak Russian, unfortunately. Can I download the ini file from somewhere else?

**Comment by ashpraj** [comment] 2020-12-10 13:28
Can somebody please share link of ini file for 19042.685 64bit

**Comment by leorheidanowski** [comment] 2020-12-10 14:15
Hi, I have the same problem in rdpwrap and windows 10 64bits version 19041.685

**Comment by toddeTV** [comment] 2020-12-10 14:30
> [autoupdate ](https://github.com/stascorp/rdpwrap/pull/1160) (recommended) or [ini ](https://raw.githubusercontent.com/asmtron/rdpwrap/master/res/rdpwrap.ini)

`Listener state: Not listening` but `[fully supported]` with ini (see above).  
Service ver. 10.0.19041.662  
Wrapper ver. 1.5.0.0  
Windows 10 Home 64-bit  
(`rfxvmt.dll` exists.)  
(`autoupdate` results in `Listener state: Not listening` and `[not supported]`)

**Comment by dimrim** [comment] 2020-12-10 15:11
Hello again,
thanks to everyone who works on this project. In my case, the asmtron INI file didn‘t work again. RDPconf has indicated that everything is ok, but only one user could log in. I don't know what the problem is, but written in a slightly different order it works again. Here is the file with my changes for [10.0.19041.662] 64 bit. 
[rdpwrap.ini.zip](https://github.com/stascorp/rdpwrap/files/5673696/rdpwrap.ini.zip)

**Comment by Maddoccc** [comment] 2020-12-10 16:04
> It works https://yadi.sk/d/thuPIABnGuZZ-Q
> 19042.685

Unfortunately, the Windows RDP service no longer starts with this ini file.

**Comment by toddeTV** [comment] 2020-12-10 16:49
> 
> 
> Hello again,
> thanks to everyone who works on this project. In my case, the asmtron INI file didn‘t work again. RDPconf has indicated that everything is ok, but only one user could log in. I don't know what the problem is, but written in a slightly different order it works again. Here is the file with my changes for [10.0.19041.662] 64 bit.
> [rdpwrap.ini.zip](https://github.com/stascorp/rdpwrap/files/5673696/rdpwrap.ini.zip)

works for me, thx.

**Comment by eslamiar** [comment] 2020-12-10 18:21
Latest 20H2 broke RDPWrap after it was working for a longtime, today I used this found in issue thread that started when Windows Update broke this. The auto-update tool link is below and from another GH user, make sure it's placed in directory where .dll/.ini are located as well as the .exe (that are whitelisted in AV) 

https://github.com/asmtron/rdpwrap/blob/master/binary-download.md

The alternative is to stop Remote Desktop in services, copy the .dll and .ini contained in .zip to your working directory for RDPWrap. (C:\program files\RDPWrapper 

[rdpwrap_ini.zip](https://github.com/stascorp/rdpwrap/files/5674844/rdpwrap_ini.zip)
.ini and .dll the auto-update generated that works with latest build of Windows Updates

**Comment by Maddoccc** [comment] 2020-12-10 19:54
Perfect. Its works. Thank you.

**Comment by Maddoccc** [comment] 2020-12-10 20:15
It shows that it is fully supported, but multiple registrations at the same time do not work. :(

**Comment by dcbasso** [comment] 2020-12-10 20:49
> Hi, I have the same problem in rdpwrap and windows 10 64bits version 19041.685

same here!

**Comment by haobinnan** [comment] 2020-12-11 03:57
你解决了吗 @MinecraftMEMZ

**Comment by Zhuzzq** [comment] 2020-12-11 05:46
> Hello again,
> thanks to everyone who works on this project. In my case, the asmtron INI file didn‘t work again. RDPconf has indicated that everything is ok, but only one user could log in. I don't know what the problem is, but written in a slightly different order it works again. Here is the file with my changes for [10.0.19041.662] 64 bit.
> [rdpwrap.ini.zip](https://github.com/stascorp/rdpwrap/files/5673696/rdpwrap.ini.zip)

thx a lot! It works for 19042.685

**Comment by akshayagrwl** [comment] 2020-12-11 08:55
> ![SS](https://user-images.githubusercontent.com/74907458/101728854-25b90d00-3add-11eb-956d-d5ecb139c401.PNG)
> Everythig worked, the status on RDP is all green but when I run from the client this is the problem. Please help me solve this too. I have tried restarting both my PC's and switching on/off my routher and also added a registry edit.
> 
> Please Help

Had the same issue. Manual update didn't work but following procedure worked as given by @eslamiar 
https://github.com/asmtron/rdpwrap/blob/master/binary-download.md

**Comment by dimrim** [comment] 2020-12-11 09:38
Windows Key + R >> Type MMC.exe >> then Control + M >> Select Group Policy Object >> then Add >> then finish >> then OK

Double click on Local Computer Policy > Computer Configuration > Administrative Templates > Windows Components > Remote Desktop Services > Remote Desktop Session Host > Connections. Limit Number of Connections = 999999. Restrict Remote Desktop Services users to a single Remote Desktop Services session = DISABLED.

**Comment by dimrim** [comment] 2020-12-11 09:39
> > ![SS](https://user-images.githubusercontent.com/74907458/101728854-25b90d00-3add-11eb-956d-d5ecb139c401.PNG)
> > Everythig worked, the status on RDP is all green but when I run from the client this is the problem. Please help me solve this too. I have tried restarting both my PC's and switching on/off my routher and also added a registry edit.
> > Please Help
> 
> Had the same issue. Manual update didn't work but following procedure worked as given by @eslamiar
> https://github.com/asmtron/rdpwrap/blob/master/binary-download.md

Windows Key + R >> Type MMC.exe >> then Control + M >> Select Group Policy Object >> then Add >> then finish >> then OK

Double click on Local Computer Policy > Computer Configuration > Administrative Templates > Windows Components > Remote Desktop Services > Remote Desktop Session Host > Connections. Limit Number of Connections = 999999. Restrict Remote Desktop Services users to a single Remote Desktop Services session = DISABLED.

**Comment by josuhap** [comment] 2020-12-11 10:57
> > > ![SS](https://user-images.githubusercontent.com/74907458/101728854-25b90d00-3add-11eb-956d-d5ecb139c401.PNG)
> > > Everythig worked, the status on RDP is all green but when I run from the client this is the problem. Please help me solve this too. I have tried restarting both my PC's and switching on/off my routher and also added a registry edit.
> > > Please Help
> > 
> > 
> > Had the same issue. Manual update didn't work but following procedure worked as given by @eslamiar
> > https://github.com/asmtron/rdpwrap/blob/master/binary-download.md
> 
> Windows Key + R >> Type MMC.exe >> then Control + M >> Select Group Policy Object >> then Add >> then finish >> then OK
> 
> Double click on Local Computer Policy > Computer Configuration > Administrative Templates > Windows Components > Remote Desktop Services > Remote Desktop Session Host > Connections. Limit Number of Connections = 999999. Restrict Remote Desktop Services users to a single Remote Desktop Services session = DISABLED.

After do it, the users can not make login "The number of connections to this computer.... bla bla bla"

**Comment by dimrim** [comment] 2020-12-11 11:10
@josuhap 
Try to set "Limit Number of Connections" and "Restrict Remote Desktop Services users to a single Remote Desktop Services session" to "not configured" and restart Windows? Maybe that would help?

**Comment by josuhap** [comment] 2020-12-11 11:26
still doesnt work
![image](https://user-images.githubusercontent.com/50111030/101898265-b65a2080-3ba3-11eb-9370-3c6a1a76d7e3.png)


:(

**Comment by dimrim** [comment] 2020-12-11 12:31
@josuhap It is not an issue for this thread. I think your problem is your RDP configuration. If you've used ini-autoupdater, you may try to completely remove and reinstall RDP-Wrapper. Then search for the appropriate INI-file for your system and add it manually.  For more help should you open a new thread.

**Comment by zebwqfox** [comment] 2020-12-12 06:21
> @josuhap
> 尝试将“限制连接数”和“将远程桌面服务用户限制为一个远程桌面服务会话”设置为“未配置”，然后重新启动Windows？也许会有帮助吗？

设置为“已启用”
Set to "enabled"
![image](https://user-images.githubusercontent.com/46518540/101976923-ed543300-3c84-11eb-9b61-97e63ca00d55.png)
![image](https://user-images.githubusercontent.com/46518540/101976936-0361f380-3c85-11eb-9979-185b376e5adc.png)
Please set it like this

**Comment by zebwqfox** [comment] 2020-12-12 06:22
> 你解决了吗 @MinecraftMEMZ

我卸载了一个更新来达到临时解决的目的

**Comment by K8-and-a-half-1000** [comment] 2020-12-12 13:42
@robbak 
Consider this a legendary artifact with the ability to create unexpected security weaknesses.
Getting involved and updating this would imply an interest in such things. That's not the kind of attention anyone really wants.

Still, as someone who likes peculiar code, I might make a new version during the holidays.
No promises though.

**Comment by josuhap** [comment] 2020-12-12 17:35
> > @josuhap
> > 尝试将“限制连接数”和“将远程桌面服务用户限制为一个远程桌面服务会话”设置为“未配置”，然后重新启动Windows？也许会有帮助吗？
> 
> 设置为“已启用”
> Set to "enabled"
> ![image](https://user-images.githubusercontent.com/46518540/101976923-ed543300-3c84-11eb-9b61-97e63ca00d55.png)
> ![image](https://user-images.githubusercontent.com/46518540/101976936-0361f380-3c85-11eb-9979-185b376e5adc.png)
> Please set it like this

I dont knoe what are u modifying the picture is in chinese :D

**Comment by ghost** [comment] 2020-12-14 15:55
Watch this video and fix your issue.
[https://youtu.be/hTnpRXHwXhM](url)

**Comment by ghost** [comment] 2020-12-14 15:56
> Please help.
> it was working earlier but idk why from 2-3 days it's not working. I'm attaching the screenshots. Please help on urgent basis.
> ![rdp ss](https://user-images.githubusercontent.com/74907458/101596278-cd213b80-3a1a-11eb-943e-7754264b9830.PNG)
> ![version ss](https://user-images.githubusercontent.com/74907458/101596285-ce526880-3a1a-11eb-8d63-e7fabf1e416d.PNG)

https://youtu.be/hTnpRXHwXhM

**Comment by josuhap** [comment] 2020-12-14 21:17
Its 100% working, thanks!!!!!!!!

**Comment by jmeile** [comment] 2020-12-15 19:31
> Had the same issue. Manual update didn't work but following procedure worked as given by @eslamiar
> https://github.com/asmtron/rdpwrap/blob/master/binary-download.md

Yes, this worked for me. Thanks

**Comment by Cenbylin** [comment] 2021-01-02 03:05
> Hello again,
> thanks to everyone who works on this project. In my case, the asmtron INI file didn‘t work again. RDPconf has indicated that everything is ok, but only one user could log in. I don't know what the problem is, but written in a slightly different order it works again. Here is the file with my changes for [10.0.19041.662] 64 bit.
> [rdpwrap.ini.zip](https://github.com/stascorp/rdpwrap/files/5673696/rdpwrap.ini.zip)

worked for me. thanks!

**Comment by AndyDavis8** [comment] 2021-01-03 08:24
> Hello again,
> thanks to everyone who works on this project. In my case, the asmtron INI file didn‘t work again. RDPconf has indicated that everything is ok, but only one user could log in. I don't know what the problem is, but written in a slightly different order it works again. Here is the file with my changes for [10.0.19041.662] 64 bit.
> [rdpwrap.ini.zip](https://github.com/stascorp/rdpwrap/files/5673696/rdpwrap.ini.zip)

Worked for me.  Termsrv.dll ver: [10.0.19041.662] 64 bit   OS ver:  20H2  19042.685

THX!

**Comment by DefiedParty** [comment] 2021-01-15 14:07
## EN
**Here is my solution**

Origin status: *not listening* , *not supported*

- Update rdpwrap.ini form [rdpwrap.ini.zip](https://github.com/stascorp/rdpwrap/files/5673696/rdpwrap.ini.zip)

Now status: *not listhing* , *fully supported*

- Start Menu 👉 Administrative Tools 👉 Windows Defender Firewall with Advanced Security 👉 Open 3389 TCP

Now status: *not listhing* , *fully supported*

- Start Menu 👉 Administrative Tools 👉 Services 👉 Stop "Remote Desktop Services UserMode Port Redirector"

Now status: *all green!*


## CN
**这里是我的解决方法**

初始状态： *not listening* , *not supported*

- 从 [rdpwrap.ini.zip](https://github.com/stascorp/rdpwrap/files/5673696/rdpwrap.ini.zip) 更新 rdpwrap.ini

状态变为：*not listhing* , *fully supported*

- 开始菜单 👉 Windows管理工具 👉 高级安全 Windows Defender 防火墙 👉 新建规则打开3389TCP端口

状态变为：*not listhing* , *fully supported*

- 开始菜单 👉 Windows管理工具 👉 服务 👉 停止 "Remote Desktop Services UserMode Port Redirector"

状态全绿啦！

**Comment by DefiedParty** [comment] 2021-01-15 14:14
排错思路
是否开启服务？
是否开放端口？
是否使用最新的rdpwrap.ini？
是否缺失rfxvmt.dll？[更多信息](https://github.com/stascorp/rdpwrap/issues/194#issuecomment-323564111) [下载](https://github.com/stascorp/rdpwrap/issues/194#issuecomment-325627235)
是否停止“Remote Desktop Services UserMode Port Redirector”服务？

**Comment by bazhi-star** [comment] 2021-09-23 07:31
![image](https://user-images.githubusercontent.com/52441818/134469497-8cd86af2-84b4-4fad-8364-f224a3727b27.png)
![image](https://user-images.githubusercontent.com/52441818/134469636-c5cfd2ea-dd96-435a-8023-5144b7aff255.png)

**Comment by sebaxakerhtc** [comment] 2022-06-20 12:00
Applicable to https://github.com/stascorp/rdpwrap/issues/1220

**Closed as completed by sebaxakerhtc** 2022-06-20 12:00 UTC
