### ISSUE TITLE
New build Windows 10 Version 19044.1586 Not Supported

### ISSUE THREAD

**Issue by ghost** [stascorp/rdpwrap#1776] opened 2022-03-16 14:49 UTC
Hi

I updated today to 19044.1586 version and it's not working.

I attach termsrv.dll file

Thanks
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/8263357/termsrv.zip)
!

**Comment by sebaxakerhtc** [comment] 2022-03-17 07:55
Duplicate of https://github.com/stascorp/rdpwrap/issues/1725

**Closed as completed by sebaxakerhtc** 2022-03-17 07:55 UTC
