### ISSUE TITLE
install.bat not working (access denied)

### ISSUE THREAD

**Issue by Cheesytaco25** [stascorp/rdpwrap#3340] opened 2024-11-12 18:51 UTC
when i try to press the install.bat program inside the RDPWrap it tells me the access is denied even tho ive opened it with administrator permissions what could be the issue

![image](https://github.com/user-attachments/assets/2c2f9519-8aa3-40bf-b2ee-2e29771bef82)

**Comment by binarymaster** [comment] 2024-11-12 20:59
Duplicate of #3222.

**Closed as not planned by binarymaster** 2024-11-12 20:59 UTC
Labels: duplicate
