### ISSUE TITLE
Mouse controlled by other user

### ISSUE THREAD

**Issue by hacqua** [stascorp/rdpwrap#615] opened 2018-12-15 17:19 UTC
After installing RDP Wrapper in Windows 10 I can have two simultaneous sessions open, but whenever the user who is connected to the physical PC uses a game controller, the same movement is replicated in the remote user's session as a mouse movement, what makes it impossible to use.

**Comment by sagtlt** [comment] 2018-12-15 18:56
I happen someone writes over the remote connection on the keyboard and the letters on my local computer appear.
Me, too, this very interestingly

**Comment by binarymaster** [comment] 2018-12-16 14:41
Duplicate of #110 and #178.

**Closed by binarymaster** 2018-12-16 14:41 UTC
