### ISSUE TITLE
10.0.18362.1766 not supported

### ISSUE THREAD

**Issue by gsons** [stascorp/rdpwrap#1582] opened 2021-11-03 01:24 UTC
10.0.18362.1766 not supported,what's the ini?

**Comment by sebaxakerhtc** [comment] 2021-11-03 12:07
> 10.0.18362.1766 not supported,what's the ini?

Attach your termsrv.dll and a screenshot of RDPConf

**Comment by sebaxakerhtc** [comment] 2021-11-03 13:07
There is solution for the x64 Windows in my repo
https://github.com/sebaxakerhtc/rdpwrap.ini/commit/b6f6dbb57c9f3d656604cbe03d06a47200c9067e#diff-9e5bbfbeae79b59b305dda13323ba2b041f30f4887a84120392c479e1f7bba33

**Comment by gsons** [comment] 2021-11-05 06:43
> > 10.0.18362.1766 not supported,what's the ini?
> 
> Attach your termsrv.dll and a screenshot of RDPConf

## it show full supported,but really it does not  work

![微信图片_20211105143917](https://user-images.githubusercontent.com/15610655/140468974-03d0f251-06d4-46ec-8159-822be13ba680.png)
![微信图片_20211105143921](https://user-images.githubusercontent.com/15610655/140468981-1d82aa63-0561-4cad-b1d2-0c49a7be378d.png)
![微信图片_20211105143924](https://user-images.githubusercontent.com/15610655/140468984-6443ec41-f28d-4c41-b5dc-11a4eab14954.png)

**Comment by gsons** [comment] 2021-11-12 07:09
> > 10.0.18362.1766 not supported,what's the ini?
> 
> Attach your termsrv.dll and a screenshot of RDPConf

can you help me? thannks

**Comment by sebaxakerhtc** [comment] 2021-11-12 07:24
> can you help me? thannks

With what?
You have a link to rdpwrap.ini
Is your Windows x64?

**Comment by gsons** [comment] 2021-11-12 08:04
> > can you help me? thannks
> 
> With what? You have a link to rdpwrap.ini Is your Windows x64?

off course  Windows x64 ,hear are link to rdpwrap.ini ,[https://raw.githubusercontent.com/gsons/gsons.github.io/master/rdpwrap.ini](url)

**Comment by sebaxakerhtc** [comment] 2021-11-12 08:22
> ,hear are link to rdpwrap.ini

The offsets are working. The problem is on your side

**Comment by gsons** [comment] 2021-11-12 08:31
it show supported,but not work. i don't konw why
![image](https://user-images.githubusercontent.com/15610655/141435520-194421c6-f5d4-4147-aca9-bed9246f9de6.png)

**Comment by MyMilkGit** [comment] 2021-12-07 10:18
@sebaxakerhtc

万分感谢大神带到这里来，我这边已经完美解决了。
我的操作是，先Uninstall之前的数据，然后Install新的数据，随后更改ini文件，最后重启，完美解决。
非常感谢！

以下为谷歌翻译。
The following is Google Translate.

I am very grateful to the Great God for being here, I have solved it perfectly.
My operation is to uninstall the previous data, then Install the new data, then change the ini file, and finally restart, which is a perfect solution.
thank you very much!

**Comment by gsons** [comment] 2021-12-10 01:25
> @sebaxakerhtc
> 
> 万分感谢大神带到这里来，我这边已经完美解决了。 我的操作是，先Uninstall之前的数据，然后Install新的数据，随后更改ini文件，最后重启，完美解决。 非常感谢！
> 
> 以下为谷歌翻译。 The following is Google Translate.
> 
> I am very grateful to the Great God for being here, I have solved it perfectly. My operation is to uninstall the previous data, then Install the new data, then change the ini file, and finally restart, which is a perfect solution. thank you very much!

根据你的方法的 我这边也解决了 之前好像是我没重启的原因 一直不行

**Comment by MyMilkGit** [comment] 2021-12-10 03:17
那就好，遇事不决就重启，重启可以解决99%的问题，剩下的1%就是换电脑。

**Comment by sebaxakerhtc** [comment] 2022-01-18 22:18
Duplicate of https://github.com/stascorp/rdpwrap/issues/1522

**Closed as completed by sebaxakerhtc** 2022-01-18 22:18 UTC
