### ISSUE TITLE
RDPWrapper not support 19044.2130

### ISSUE THREAD

**Issue by EthanChenLi** [stascorp/rdpwrap#2024] opened 2022-10-19 10:42 UTC
![image](https://user-images.githubusercontent.com/6337626/196669603-71c0df1b-d350-4b7b-b7aa-86892e01a694.png)

**Comment by maralboga** [comment] 2022-10-19 14:51
now use installer to update INI file
https://github.com/stascorp/rdpwrap

**Comment by sashaqwert** [comment] 2022-10-19 15:52
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992

**Closed as not planned by sashaqwert** 2022-10-19 15:52 UTC
Labels: duplicate

**Comment by sashaqwert** [comment] 2022-10-19 15:58
@maralboga 
> now use installer to update INI file
https://github.com/stascorp/rdpwrap

This version is not supported now officially --> MSI installer not support this version.
