### ISSUE TITLE
10.0.17763.437 not supported please help sir

### ISSUE THREAD

**Issue by sailendra00** [stascorp/rdpwrap#739] opened 2019-04-12 05:03 UTC
After a recent update i cant use rdp its showing not supported  10.0.17763.437 not supported please help sir provide me ini file sir

**Comment by sailendra00** [comment] 2019-04-12 05:29
listener not supported after adding text to .ini file what to do should we change termsv.dll file??

**Comment by dimonpanik** [comment] 2019-04-12 05:34
та же проблема

**Comment by error2221** [comment] 2019-04-12 06:09
after update doesnt work, before it worked on windows server 2016

**Comment by IngArt** [comment] 2019-04-12 06:20
Решение в соседней ветке https://github.com/stascorp/rdpwrap/issues/729 <= Solution for x64
Для х64 мне помогло

**Comment by msap12** [comment] 2019-04-24 17:04
I'm looking for INI patch code for version 10.0.17763.437-SLInit    **x86**

**Comment by sebaxakerhtc** [comment] 2022-01-04 10:24
Duplicate of https://github.com/stascorp/rdpwrap/issues/720

**Closed as completed by sebaxakerhtc** 2022-01-04 10:24 UTC
