### ISSUE TITLE
10.0.22621.3085

### ISSUE THREAD

**Issue by vassooooo** [stascorp/rdpwrap#2491] opened 2024-02-17 05:46 UTC
[termsrv.zip.zip](https://github.com/stascorp/rdpwrap/files/14317861/termsrv.zip.zip)

**Comment by sashaqwert** [comment] 2024-02-17 11:09
Duplicate of https://github.com/stascorp/rdpwrap/issues/2469

**Closed as not planned by sashaqwert** 2024-02-17 11:09 UTC
Labels: duplicate
