### ISSUE TITLE
windows 10 home ver .10.0.15063.0 .  listener state: not listening

### ISSUE THREAD

**Issue by szpebble** [stascorp/rdpwrap#315] opened 2017-10-04 03:48 UTC
windows 10 home(china) ver .10.0.15063.0 .  
wrapper state: installed
service state: running
listener state: **not listening**

**Comment by binarymaster** [comment] 2017-10-04 11:19
Duplicate of #194.

**Closed by binarymaster** 2017-10-04 11:19 UTC
