### ISSUE TITLE
Windows 10 RS1 - 10.0.14393.1198

### ISSUE THREAD

**Issue by fre4kyC0de** [stascorp/rdpwrap#558] opened 2018-09-17 22:28 UTC
[10.0.14393.1198]
LocalOnlyPatch.x86=1
LocalOnlyOffset.x86=A6088
LocalOnlyCode.x86=jmpshort
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=8D781
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x86=1
SingleUserOffset.x86=359C5
SingleUserCode.x86=nop
SingleUserPatch.x64=1
SingleUserOffset.x64=299A4
SingleUserCode.x64=Zero
DefPolicyPatch.x86=1
DefPolicyOffset.x86=2FF29
DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1AFC5
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x86=1
SLInitOffset.x86=45636
SLInitFunc.x86=New_CSLQuery_Initialize
SLInitHook.x64=1
SLInitOffset.x64=C930
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.14393.1198-SLInit]
bInitialized.x86      =C1F6C
bServerSku.x86        =C1F70
lMaxUserSessions.x86  =C1F74
bAppServerAllowed.x86 =C1F78
bRemoteConnAllowed.x86=C1F7C
bMultimonAllowed.x86  =C1F80
ulMaxDebugSessions.x86=C1F84
bFUSEnabled.x86       =C1F88

bServerSku.x64        =E73D0
lMaxUserSessions.x64  =E73D4
bAppServerAllowed.x64 =E73D8
bInitialized.x64      =E8470
bRemoteConnAllowed.x64=E8474
bMultimonAllowed.x64  =E8478
ulMaxDebugSessions.x64=E847C
bFUSEnabled.x64       =E8480

**Comment by fre4kyC0de** [comment] 2018-09-18 22:08
corrected typo

**Comment by binarymaster** [comment] 2018-10-03 15:46
Could you please share x64 build of 10.0.14393.1198 termsrv.dll?

**Comment by fre4kyC0de** [comment] 2018-10-03 23:02
You can find it inside KB4019472 and newer (up to KB4039396).

http://download.windowsupdate.com/c/msdownload/update/software/secu/2017/05/windows10.0-kb4019472-x64_dda304140351259fcf15ca7b1f5b51cb60445a0a.msu

I extract it using "expand .\<cab name>.cab /f:termsrv.dll ."

**Comment by binarymaster** [comment] 2018-10-03 23:29
> I extract it using "expand .<cab name>.cab /f:termsrv.dll ."

What I'm doing wrong?
```
Microsoft Windows [Version 10.0.17134.228]

C:\Users\user\Downloads\msu>expand Windows10.0-KB4019472-x64.cab /f:termsrv.dll .
Microsoft (R) File Expansion Utility
Copyright (c) Microsoft Corporation. All rights reserved.

windows10.0-kb4019472-x64.cab: No files matching 'termsrv.dll'.
```

**Comment by binarymaster** [comment] 2018-10-03 23:39
I'll retry on more modern Win10 installation later.

**Comment by fre4kyC0de** [comment] 2018-10-04 17:19
Some updates are split into multiple cabs.
Try first extracting the windows10.0-kb4019472-x64.cab with „/f:*.cab“ and then the resulting CABs using the command above.

**Comment by binarymaster** [comment] 2018-10-04 20:38
So, resolving as duplicate of #245, since `10.0.14393.1198` x64 binary does not exist (at least publicly).

**Closed by binarymaster** 2018-10-04 20:38 UTC
Labels: add build
