### ISSUE TITLE
Windows 11 Pro Number of connections is limited 

### ISSUE THREAD

**Issue by kamakazie2** [stascorp/rdpwrap#2071] opened 2022-12-21 02:01 UTC
Hello. Im on windows 11 pro 10.0.22621.608 Fully supported and i cannot log in with another user.

I updated to the latest INI file and i tried editing local policy to allow for 999999 connections. 

Any advice?

![image](https://user-images.githubusercontent.com/41803214/208802825-ee61693e-d04d-468c-813a-5b9a8b37e9d8.png)
![image](https://user-images.githubusercontent.com/41803214/208802857-476aae29-5ca9-409f-8233-9dcf83f21dae.png)

**Comment by sashaqwert** [comment] 2022-12-21 10:54
Try restart service or reboot.

Or

Try:
1. Download RDP Wrapper 1.6.2 and extract this to any directory.
2. Place `rdpwrap.ini` in the same directory.
3. Open CMD as administrator
4. Execute this commands
```
cd C:\path\to\directory\
rdpwinst -u -k
rdpwinst -i
```
5. Enjoy!

Original message: https://t.me/rdpwrap/49131

**Comment by sashaqwert** [comment] 2022-12-21 11:40
One `termsrv.dll` version = one opened issue --> Duplicate.

**Comment by sashaqwert** [comment] 2022-12-21 11:41
Duplicate of https://github.com/stascorp/rdpwrap/issues/2006

**Closed as not planned by sashaqwert** 2022-12-21 11:41 UTC
Labels: duplicate
