### ISSUE TITLE
19043.1202

### ISSUE THREAD

**Issue by Melnick704** [stascorp/rdpwrap#1517] opened 2021-09-09 06:30 UTC
it's work
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/7134015/rdpwrap.zip)

**Comment by Iskandare** [comment] 2021-09-13 09:25
Thank you, it's work also for **19043.1165**

**Comment by ddominq** [comment] 2021-09-15 14:48
Amazing work! Why isn't this in autoupdate? Thanks a lot!

**Comment by heychief3000** [comment] 2021-09-15 21:31
Thanks, I can confirm this works for me too.  Autoupdate didn't work.

For Reference:
net stop termservice
Copy over file
net start termservice

**Comment by everdominguez** [comment] 2021-09-17 01:52
Hi everyone,

This ini file works fine in 10.0.19041.1202.

Thanks a lot

**Comment by LudwigHao** [comment] 2021-09-17 07:28
This file also works fine in 19043.1100.

**Comment by danielgindi** [comment] 2021-09-17 10:55
```ini
[10.0.19041.1202-SLInit]
; no x86 section

bInitialized.x64      =107108
bServerSku.x64        =10710C
lMaxUserSessions.x64  =107110
bAppServerAllowed.x64 =107118
bRemoteConnAllowed.x64=107120
bMultimonAllowed.x64  =107124
ulMaxDebugSessions.x64=107128
bFUSEnabled.x64       =10712C

[10.0.19041.1202]
; no x86 section

LocalOnlyPatch.x64    =1
LocalOnlyOffset.x64   =89D81
LocalOnlyCode.x64     =jmpshort
SingleUserPatch.x64   =1
SingleUserOffset.x64  =0D13C
SingleUserCode.x64    =Zero
DefPolicyPatch.x64    =1
DefPolicyOffset.x64   =19105
DefPolicyCode.x64     =CDefPolicy_Query_eax_rcx
SLInitHook.x64        =1
SLInitOffset.x64      =1E98C
SLInitFunc.x64        =New_CSLQuery_Initialize
```

**Comment by IljaM13** [comment] 2021-09-17 11:10
And now please for x86 :-)

**Comment by huanhaishijie** [comment] 2021-09-18 03:11
![image](https://user-images.githubusercontent.com/59204122/133870595-b0ae2edd-0b34-480a-8a1f-95c1a97fe4a5.png)

**Comment by panhaoyu** [comment] 2021-09-24 11:49
Nice work! works fine on my machine.

**Comment by sebaxakerhtc** [comment] 2021-10-25 16:07
duplicate of https://github.com/stascorp/rdpwrap/issues/1509

**Closed as completed by sebaxakerhtc** 2021-10-25 16:07 UTC
