### ISSUE TITLE
 10.0.19045.3803 no supported,please help me 

### ISSUE THREAD

**Issue by chaochaoluo** [stascorp/rdpwrap#3224] opened 2024-07-04 14:08 UTC
thank you,my friend!

**Comment by chaochaoluo** [comment] 2024-07-04 14:14
10.0.19045.3803 x64

**Comment by loyejaotdiqr47123** [comment] 2024-07-04 14:40
Please, attach your RDPConf screenshot and termsrv.dll.

**Comment by chaochaoluo** [comment] 2024-07-04 15:56
![1720107605599](https://github.com/stascorp/rdpwrap/assets/39582470/8414af7d-ad26-4600-bd87-d658ef1148fc)
[termsrv.zip](https://github.com/user-attachments/files/16100997/termsrv.zip)

**Comment by chaochaoluo** [comment] 2024-07-04 15:56
> Please, attach your RDPConf screenshot and termsrv.dll.

thank you

**Comment by binarymaster** [comment] 2024-07-04 16:35
Duplicate of #2381.

**Closed as not planned by binarymaster** 2024-07-04 16:35 UTC
Labels: duplicate

**Comment by chaochaoluo** [comment] 2024-07-05 00:42
> Duplicate of #2381.

 I can't thank you enough for your helping!
