### ISSUE TITLE
10.0.22621.4249 (All green but can't exceed 1 connection)

### ISSUE THREAD

**Issue by Chikara-Kwon** [stascorp/rdpwrap#3290] opened 2024-10-04 02:46 UTC
All Green BUT limited connection
OS build is on the screenshot

![Screenshot 2024-10-04 104404](https://github.com/user-attachments/assets/8e770de0-7e37-4afa-84cd-7ee2cff065e8)
![Screenshot 2024-10-04 104431](https://github.com/user-attachments/assets/b7eede83-cc6e-4099-9d73-b3d2112c1562)

**Comment by binarymaster** [comment] 2024-10-04 10:14
Duplicate of #1054.

**Closed as not planned by binarymaster** 2024-10-04 10:14 UTC
Labels: duplicate
