### ISSUE TITLE
Unable to open multiple remote desktop connections with latest windows 10 update

### ISSUE THREAD

**Issue by sporadicsmiles** [stascorp/rdpwrap#2158] opened 2023-03-28 06:56 UTC
As the title suggests. Everything else is up to date. I have downloaded the most recent rdpwrapper.ini file and get all green indications when confirming. Using the following settings.
![image](https://user-images.githubusercontent.com/129151402/228152416-ddf54af3-3155-495f-9655-b525c76574bc.png)

I have updated to 99999 (or whatever the recommended number is for number of connections. 

When I try to connect, I get the following.

![image](https://user-images.githubusercontent.com/129151402/228152809-cae2f2fc-7551-4bc3-8fec-94fd9d20a8c6.png)
When using the RDPCheck.

When using another computer I get a message saying I will disconnect the other session and a message on the computer asking I will accept or decline this. 

Any help appreciated.

**Comment by sashaqwert** [comment] 2023-03-28 07:59
Duplicate of https://github.com/stascorp/rdpwrap/issues/2125

**Closed as not planned by sashaqwert** 2023-03-28 07:59 UTC
Labels: duplicate
