### ISSUE TITLE
10.0.17763.5936 x64

### ISSUE THREAD

**Issue by Martizaker** [stascorp/rdpwrap#3223] opened 2024-07-04 12:37 UTC
Hello. RPDWrap not work. Please help me!

**Comment by chaochaoluo** [comment] 2024-07-04 15:45
> Please, attach your RDPConf screenshot and termsrv.dll.

thank you bro

**Comment by Martizaker** [comment] 2024-07-04 16:37
[RDPWrap.zip](https://github.com/user-attachments/files/16101297/RDPWrap.zip)

![image](https://github.com/stascorp/rdpwrap/assets/174715468/4d05e374-1dc0-4169-bc9b-557f69c7d562)

**Comment by binarymaster** [comment] 2024-07-04 16:47
Duplicate of https://github.com/stascorp/rdpwrap/issues/559.

**Closed as not planned by binarymaster** 2024-07-04 16:47 UTC
Labels: duplicate
