### ISSUE TITLE
10.0.18362.657 is not working, please help, thanks

### ISSUE THREAD

**Issue by peixunbu201** [stascorp/rdpwrap#1040] opened 2020-03-28 04:39 UTC

**Comment by RTCProjects** [comment] 2020-03-28 07:22
I had similar problem. You can use 
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/4396763/rdpwrap.zip)
for support RDP on current version Windows.

Step by step:
1. Run PS from Administrator
2. Exec "get-service termservice|stop-service  -force"
3. Replace original rdpwrap.ini in C:\Program Files\RDP Wrapper\ on rdpwrap in zip attached.
4. Exec "get-service termservice|start-service"

Done

**Comment by Stevemaster92** [comment] 2020-03-28 13:16
Thanks, it works! I guess the update will come with the next version (see PR #1039 )

**Comment by LYB926** [comment] 2020-03-28 15:20
> I had similar problem. You can use
> rdpwrap.zip
> for support RDP on current version Windows.
> Step by step:
> 
> Run PS from Administrator
> Exec "get-service termservice|stop-service  -force"
> Replace original rdpwrap.ini in C:\Program Files\RDP Wrapper\ on rdpwrap in zip attached.
> Exec "get-service termservice|start-service"
> 
> Done

Thank you!

**Comment by peixunbu201** [comment] 2020-03-31 14:28
Thank you!

**Comment by Arenoros** [comment] 2020-03-31 22:36
I added patch from https://github.com/stascorp/rdpwrap/pull/1039 , but get error start service
```
>>> SvchostPushServiceGlobals
Loading configuration...
Configuration file: c:\program files\rdp wrapper\rdpwrap.ini
Initializing RDP Wrapper...
Base addr:  0x00007FFA51980000
SvcMain:    termsrv.dll+0x0000000000037350
SvcGlobals: termsrv.dll+0x0000000000037BE0
Version:    10.0.18362.657
Freezing threads...
Patch CEnforcementCore::GetInstanceOfTSLicense
Patch CSessionArbitrationHelper::IsSingleSessionPerUserEnabled
Patch CDefPolicy::Query
Hook CSLQuery::Initialize
Resumimg threads...
<<< SvchostPushServiceGlobals
>>> ServiceMain
<<< ServiceMain
>>> CSLQuery::Initialize
SLInit [0x00007FFA51A76A90] bServerSku = 1
SLInit [0x00007FFA51A76AA0] bRemoteConnAllowed = 1
```
![Capture](https://user-images.githubusercontent.com/2578918/78081339-00ee9080-73b9-11ea-9253-cac508c80593.PNG)

Windows 10 Home Single Language
PS.
Checked on another pc with Windows 10 Pro, same problem

PPS.
This work https://github.com/stascorp/rdpwrap/issues/1040#issuecomment-605407827

**Comment by MosheL** [comment] 2020-04-10 08:36
working. thanks

**Comment by LazyQuad** [comment] 2020-04-28 18:12
Just to add for anyone that needs to fix this remotely.  I was able to apply the ini provided above https://github.com/stascorp/rdpwrap/issues/1040#issuecomment-605407827 and then restart "Remote Desktop Services" via services.msc with everything working perfectly.  Thx!

**Comment by sebaxakerhtc** [comment] 2022-04-27 15:57
Duplicate of https://github.com/stascorp/rdpwrap/issues/983

**Closed as completed by sebaxakerhtc** 2022-04-27 15:57 UTC
