### ISSUE TITLE
Not listening 10.0.19041.1387 I Need Help

### ISSUE THREAD

**Issue by AngelSakura** [stascorp/rdpwrap#1706] opened 2022-02-03 13:42 UTC
![RDPConf_x1dc4fyJMJ](https://user-images.githubusercontent.com/98960417/152354004-31b1c0b1-7fb7-44b1-8369-0cc5a7265391.png)

**Comment by sebaxakerhtc** [comment] 2022-02-04 08:36
Duplicate of https://github.com/stascorp/rdpwrap/issues/1630

**Closed as completed by sebaxakerhtc** 2022-02-04 08:36 UTC
