### ISSUE TITLE
Windows 10 10.0.19041.2673 need supporting

### ISSUE THREAD

**Issue by vvsopk** [stascorp/rdpwrap#2192] opened 2023-05-06 12:24 UTC
![image](https://user-images.githubusercontent.com/95007437/236623839-b32f2ac7-d3d1-4139-ab4a-5664387115bd.png)

**Comment by sashaqwert** [comment] 2023-05-06 12:36
Duplicate of https://github.com/stascorp/rdpwrap/issues/2125

**Closed as not planned by sashaqwert** 2023-05-06 12:36 UTC
Labels: duplicate
