### ISSUE TITLE
Win10 pro 22H2 19045.3693, "fully supported" but do not support more than 5 connections 

### ISSUE THREAD

**Issue by reexpi** [stascorp/rdpwrap#2441] opened 2023-12-12 14:57 UTC
At first the version of the current system could not be detected on Win10 pro 22H2 19045.3693. And the screenshot of RDFConf is as below.
![微信图片_20231212224300](https://github.com/stascorp/rdpwrap/assets/69749384/5507eadb-a405-44cf-a844-a8a94a3897bb)
I fixed this according to https://github.com/stascorp/rdpwrap/issues/2411.
![微信图片_20231212224510](https://github.com/stascorp/rdpwrap/assets/69749384/536e4236-2c3e-45a2-8754-4b9c9b18ca9e)
**But RDPCheck still can't work. And When there are more than 5  connections, a new connection will fail.**
Is this a problem with newer versions of windows or something else?
Any help greatly appreciated.
Thank you!

**Comment by Birdog737** [comment] 2023-12-12 21:45
Yeah same issue after restart...
![RDPConf_f7cbZlS9ki](https://github.com/stascorp/rdpwrap/assets/132885775/7ea927c1-7c67-4f62-8fbd-2b748361508c)

But my limit is 7 connections, 8th one gives black screen and error:
![mstsc_vMoH2XJXvY](https://github.com/stascorp/rdpwrap/assets/132885775/3ad3dd77-d528-4ea5-87b6-7d4c6f1a9ee1)

Before I could run 20 connections...

**Comment by reexpi** [comment] 2023-12-13 02:37
> Yeah same issue after restart... ![RDPConf_f7cbZlS9ki](https://private-user-images.githubusercontent.com/132885775/290011519-7ea927c1-7c67-4f62-8fbd-2b748361508c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MzUwOTIsIm5iZiI6MTcwMjQzNDc5MiwicGF0aCI6Ii8xMzI4ODU3NzUvMjkwMDExNTE5LTdlYTkyN2MxLTdjNjctNGY2Mi04ZmJkLTJiNzQ4MzYxNTA4Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QwMjMzMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NDM5MzY5NzFkNDYxNjg3NTMyNWFjOTIzODkwMTdmOGZiMDFmNDgwYzQxMjdkNzNlYTQzODZkMjliOWI0YjVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AkMlnlFzFZJO1PwR3lHO6xJ9-yPoDDA4Hj4rpvvMiUE)
> 
> But my limit is 7 connections, 8th one gives black screen and error: ![mstsc_vMoH2XJXvY](https://private-user-images.githubusercontent.com/132885775/290011764-3ad3dd77-d528-4ea5-87b6-7d4c6f1a9ee1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MzUwOTIsIm5iZiI6MTcwMjQzNDc5MiwicGF0aCI6Ii8xMzI4ODU3NzUvMjkwMDExNzY0LTNhZDNkZDc3LWQ1MjgtNGVhNS04N2I2LTdkNGM2ZjFhOWVlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QwMjMzMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NWU1NzhmOGNlOWMzOTAyMWU1ZDFkMWMzMjU3YTE4YjdkYmNkMDM2N2I3YzUxZjFiMDllMWQ0ODE0YWY4NjAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.t65tqtkFdEuhsvFCbaxazmSQMFB4NjP99wYwFBRatDY)
> 
> Before I could run 20 connections...

It seems that we have the same problem.

**Comment by sashaqwert** [comment] 2023-12-13 06:49
One termsrv.dll version = ONE opened issue!

**Comment by sashaqwert** [comment] 2023-12-13 06:49
Duplicate of https://github.com/stascorp/rdpwrap/issues/2381

**Closed as not planned by sashaqwert** 2023-12-13 06:49 UTC
Labels: duplicate
