### ISSUE TITLE
listener not listening

### ISSUE THREAD

**Issue by MikeSam06** [stascorp/rdpwrap#232] opened 2017-04-09 06:24 UTC
![image](https://cloud.githubusercontent.com/assets/18574834/24835281/41095bd8-1d30-11e7-9d1b-487475386173.png)

and checked, it's latest version

**Comment by Recka50** [comment] 2017-04-09 09:55
Same here, Win 10 Home, build 1703 (creators), worked before upgrading to 1703.

**Comment by binarymaster** [comment] 2017-04-09 10:25
Duplicate of #194.

**Closed by binarymaster** 2017-04-09 10:25 UTC
Labels: duplicate
