### ISSUE TITLE
10.0.17134.1 need help

### ISSUE THREAD

**Issue by justblues** [stascorp/rdpwrap#2206] opened 2023-05-19 06:51 UTC
RDP Wrapper configuration fully support,but RDPCheck.exe failed ,and Remote access to my computer from another computer, display other accounts, log in with my account password and show "password error"
![rdpcheck_failed](https://github.com/stascorp/rdpwrap/assets/8804041/fff16a7d-bc3a-4d94-94ad-149746210230)
![rdfconf_success](https://github.com/stascorp/rdpwrap/assets/8804041/9b3a790e-4b86-42ef-9fe3-b96c5f3150ea)
![mstsc_failed](https://github.com/stascorp/rdpwrap/assets/8804041/9c7d3cd9-fff8-4df7-aae9-76c1b329d741)

**Comment by sashaqwert** [comment] 2023-05-19 07:35
Try add your RDP users to Administrators or "Remote desktop users" group.

**Comment by sashaqwert** [comment] 2023-05-19 07:39
One `termsrv.dll` version = ONE opened issue!

You can read about moderation [here](https://t.me/rdpwrap/37173) (in Russian)

**Comment by sashaqwert** [comment] 2023-05-19 07:41
Duplicate of https://github.com/stascorp/rdpwrap/issues/2201

**Closed as not planned by sashaqwert** 2023-05-19 07:41 UTC
Labels: duplicate
