### ISSUE TITLE
10.0.19042.1466 not supported

### ISSUE THREAD

**Issue by MarcosMoura90** [stascorp/rdpwrap#1708] opened 2022-02-04 19:06 UTC
Can anyone help us with ini files for win 10 version 10.0.19042.1466? Thank you
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/8005781/termsrv.zip)
.

**Comment by sebaxakerhtc** [comment] 2022-02-04 21:25
Duplicate of https://github.com/stascorp/rdpwrap/issues/1630

**Closed as completed by sebaxakerhtc** 2022-02-04 21:25 UTC
