### ISSUE TITLE
win11 family ver:10.0.22000.1641

### ISSUE THREAD

**Issue by zqshan2000** [stascorp/rdpwrap#3228] opened 2024-07-14 01:56 UTC
rdpwrap.ini
[rdpwrap.zip](https://github.com/user-attachments/files/16215346/rdpwrap.zip)

**Comment by loyejaotdiqr47123** [comment] 2024-07-14 13:14
？
Please, attach your RDPConf screenshot and termsrv.dll.

**Comment by binarymaster** [comment] 2024-07-14 14:40
Duplicate of #2126.

**Closed as not planned by binarymaster** 2024-07-14 14:40 UTC
Labels: duplicate
