### ISSUE TITLE
"Access Denied"

### ISSUE THREAD

**Issue by WiertOlise** [stascorp/rdpwrap#3397] opened 2024-12-23 09:34 UTC
![IMG_3834](https://github.com/user-attachments/assets/ce40562c-8bc8-4920-a027-eff559e42dab)
I keep coming across this error, if you know anything about it. Please feel free to assist my problem. Would be much appreciated. 

Also, I've done about anything in my ability to possibly fix it. I made sure I had the right User Permissions, antivirus/firewall permissions were disabled, The Build is supported, its the latest one on Windows 11.

**Comment by binarymaster** [comment] 2024-12-23 11:00
Duplicate of #2080 / #2224 / #2227 => #391

**Closed as not planned by binarymaster** 2024-12-23 11:00 UTC
Labels: duplicate
