### ISSUE TITLE
RDP + Local User this PC win10

### ISSUE THREAD

**Issue by edgiru** [stascorp/rdpwrap#767] opened 2019-04-30 12:29 UTC
you can not work a local user on the computer and the RDP user simultaneously. If the RDP user enters the computer over the network under the name for example: "buh" of the local user for example: "Administrator" switches to "buh". The local user and the RDP user see the same desktop.

**Comment by lehha** [comment] 2019-05-13 13:24
I have a similar problem: if you work locally, and then connect via RDP, then a new session starts with this user (in parallel, the current one does not throw out). This with option "Single session per user"

**Comment by johnnyontheweb** [comment] 2019-06-20 19:51
Same problem for me. I disabled multiple access to same user but nothing. I'm running Windows 10 home 1903 with INI file.
it's really annoying, Onedrive resets every time a multiple session for same user has started.
![Cattura](https://user-images.githubusercontent.com/10365055/59877142-7bf43680-93a5-11e9-86d0-a10221d8105c.PNG)

can you help?

**Comment by Mayar** [comment] 2019-10-08 19:32
Нas anyone found the solution?

**Comment by edgiru** [comment] 2019-10-09 06:58
> Нas anyone found the solution?

no solution yet

**Comment by Mayar** [comment] 2019-10-09 08:44
How to workaround the problem? Change .dll?

**Comment by s0nic9** [comment] 2019-10-09 08:48
no workaround, rdpwrap works with updates from others users, read issues carefully.

**Comment by Mayar** [comment] 2019-10-10 19:36
На всех машинах такая байда. Как решали, коллеги?

**Comment by sebaxakerhtc** [comment] 2022-01-04 10:28
Duplicate of https://github.com/stascorp/rdpwrap/issues/720

**Closed as completed by sebaxakerhtc** 2022-01-04 10:28 UTC
