### ISSUE TITLE
 working on one pc, not on another, same versions

### ISSUE THREAD

**Issue by wagner2029** [stascorp/rdpwrap#1909] opened 2022-06-20 23:03 UTC
tested on 4 computers, the 4 in version 21h2 19044.17166
rdp wrapper 1.5.0.0 dll 10.0.19041.1741.
I copied the same installer to the 4 computers, I copied the same dll, I ran install, autoupdate.
wrapper state installed.
service state: running
Listener state: listening.
fully supported.
on two computers it works, on two when I run it drops the logged in user.
Everything is in the same version, I'm out of ideas
[rdpwrap.txt](https://github.com/stascorp/rdpwrap/files/8944553/rdpwrap.txt)
.

**Comment by sashaqwert** [comment] 2022-06-21 06:01
One `termsrv.dll` version = one opened issue --> duplicate of https://github.com/stascorp/rdpwrap/issues/1881

> I copied the same dll

What? Do not patch `termsrv.dll`. Installing RDP Wrapper does not imply any DLL copying...

**Comment by sebaxakerhtc** [comment] 2022-06-21 10:31
duplicate of https://github.com/stascorp/rdpwrap/issues/1881

**Closed as completed by sebaxakerhtc** 2022-06-21 10:31 UTC
