### ISSUE TITLE
10.0.22621.3085 fully supported not listening

### ISSUE THREAD

**Issue by vassooooo** [stascorp/rdpwrap#2492] opened 2024-02-17 05:48 UTC

**Comment by sashaqwert** [comment] 2024-02-17 11:10
Try:
1. Download RDP Wrapper 1.6.2 and extract this to any directory.
2. Place `rdpwrap.ini` in the same directory.
3. Open CMD as administrator
4. Execute this commands
```
cd C:\path\to\directory\
rdpwinst -u -k
rdpwinst -i
```
5. Enjoy!

Original message: https://t.me/rdpwrap/49131

**Comment by sashaqwert** [comment] 2024-02-17 11:11
One `termsrv.dll` version = ONE opened issue!

**Comment by sashaqwert** [comment] 2024-02-17 11:11
Duplicate of https://github.com/stascorp/rdpwrap/issues/2469

**Closed as not planned by sashaqwert** 2024-02-17 11:11 UTC
Labels: duplicate
