### ISSUE TITLE
Virus detected in package

### ISSUE THREAD

**Issue by MrVolcano** [stascorp/rdpwrap#507] opened 2018-06-18 12:19 UTC
Google Chrome's download protection and Webroot antivirus both report that the files contact viruses.

**Comment by thaguitarist** [comment] 2018-06-18 18:20
Surely a false positive. 
Just put it in exception list as it's safe to download.

**Comment by binarymaster** [comment] 2018-06-18 21:54
Duplicate of #277.

**Closed by binarymaster** 2018-06-18 21:54 UTC
