### ISSUE TITLE
10.0.26090.112

### ISSUE THREAD

**Issue by bowjacon** [stascorp/rdpwrap#2538] opened 2024-04-02 05:24 UTC
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/14831894/termsrv.zip)

**Comment by bowjacon** [comment] 2024-04-02 05:28
I tried the latest version of the ini file, but the following problem still occurred
![image](https://github.com/stascorp/rdpwrap/assets/99178447/69ca16ba-3d5d-4386-8f7f-3ffece0aeffb)

**Comment by loyejaotdiqr47123** [comment] 2024-04-03 09:56
Duplicate of #2534

**Comment by sashaqwert** [comment] 2024-04-06 16:30
Duplicate of https://github.com/stascorp/rdpwrap/issues/2534

**Closed as not planned by sashaqwert** 2024-04-06 16:30 UTC
Labels: duplicate
