### ISSUE TITLE
rdpwrap.ini

### ISSUE THREAD

**Issue by 87782902** [stascorp/rdpwrap#2249] opened 2023-06-18 06:25 UTC
能帮找一下这个ini文件吗？谢谢
ver.  10.0.20348.1668

**Comment by sashaqwert** [comment] 2023-06-18 10:34
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by sashaqwert** [comment] 2023-06-18 10:43
Duplicate of https://github.com/stascorp/rdpwrap/issues/2169

**Closed as not planned by sashaqwert** 2023-06-18 10:43 UTC
Labels: duplicate
