### ISSUE TITLE
Does any one solve the win 10 18362.1016 ?

### ISSUE THREAD

**Issue by wenan1130** [stascorp/rdpwrap#1149] opened 2020-08-24 04:19 UTC
Hi, all, does any one solve the win 10 18362.1019?

**Comment by ghost** [comment] 2020-08-25 09:17
https://github.com/tmaguire/rdpwrap/tree/master/res

**Comment by affinityv** [comment] 2020-08-25 12:10
I've updated my [INI (use this one)](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini) file with two extra x86 sections found in the above referred [INI](https://raw.githubusercontent.com/tmaguire/rdpwrap/master/res/rdpwrap.ini) file from [tmaguire](https://github.com/tmaguire).

NB: There were no new INI file sections, just adjustments to existing sections to add in the extra x86 and some comments; I believe my INI file is the most complete one available, there are quite alot of extra INI file sections in my own version and some formatting is improved.

**Comment by affinityv** [comment] 2020-08-25 12:12
@wenan1130 -- what is the version of the termsrv.dll as shown by `RDPConf.exe` ?

**Comment by wenan1130** [comment] 2020-08-26 03:03
@affinityv thanks for your help. I have solved this issue. Here is my operation system information:
win 10 professional 1903, os build 18362.1016,  [termsrv.dll](https://mega.nz/file/iKwx0RAQ#MDtT6I2j1FjjNFs_U2nqDrjbuqWPMU3lcJLPuBcaSMU), [rdpwrap.ini](https://mega.nz/file/OShDHbyb#wRYfQfp2Jmrx9wbUlkpGmsE6TPP_Wrmh0mIVN5NFeyA)

**Comment by affinityv** [comment] 2020-08-26 06:53
@wenan1130  Okay, your termsrv.dll version is 10.0.18362.836 (that is what you will see with `RDPConf.exe`)
The INI file you are using is my one.
So long as you don't have Windows Defender or an AV product interfering, then you should be good.

**Comment by Zakspeed** [comment] 2020-09-24 11:40
I am not able to replace the "termsrv.dll" you indicate.

i tried: in Admin CMD
"net stop TermService"

**Comment by affinityv** [comment] 2020-09-26 15:37
You DON'T replace the termsrv.dll .... you replace the [INI](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini) file and restart the service.  `RDPWInst.exe -r`

**Comment by sebaxakerhtc** [comment] 2022-06-20 11:43
Duplicate of https://github.com/stascorp/rdpwrap/issues/1083

**Closed as completed by sebaxakerhtc** 2022-06-20 11:43 UTC
