### ISSUE TITLE
I think we're going to face a big problem

### ISSUE THREAD

**Issue by daivdedibuduo** [stascorp/rdpwrap#2479] opened 2024-02-05 16:17 UTC
Hi, 
with the latest update of svchost.exe  (10.0.19041.3636, 01/25/2024) rdp service cannot start anymore on windows 10 with the message
"the file contains a virus or a potentially unwanted software"
No matter disabling windows defender, the message stays there.
I'm worried 'cause i think they've managed to block rdpwrapper at the begininng.
Anyone is facing a similar problem?

**Comment by farmaleader** [comment] 2024-02-05 17:58
Hi Davide,
I checked my system Win10 22H2 with Service state: 10.0.19041.3636 and works fine.
This is svchost
![image](https://github.com/stascorp/rdpwrap/assets/72986559/6db9731a-c674-486d-8247-02368388c501)

**Comment by sashaqwert** [comment] 2024-02-06 07:57
> 10.0.19041.3636

Discussion in https://github.com/stascorp/rdpwrap/issues/2381

> rdp service cannot start anymore on windows 10 with the message

RDPConf screenshot, please!

**Comment by sashaqwert** [comment] 2024-02-06 07:58
Duplicate of https://github.com/stascorp/rdpwrap/issues/2381

**Closed as not planned by sashaqwert** 2024-02-06 07:58 UTC
Labels: duplicate
