### ISSUE TITLE
Listener not supported after Windows Update KB4088876 and KB4088879

### ISSUE THREAD

**Issue by yesidhm1** [stascorp/rdpwrap#434] opened 2018-03-20 18:53 UTC
Hi, After applying the updates for the month of March, the rdpwapper 1.6.2 application stopped working. The patches that affect are KB4088876 and KB4088879. Could you please confirm if there is a fix that activates the rdpwapper 1.6.2 again? Thank you very much.

**Comment by 1valdis** [comment] 2018-03-20 22:30
Same problem here. Waiting for update...

**Comment by gabor-farkas** [comment] 2018-03-21 11:52
What's your version of termsrv.dll?
Doesn't this help: https://github.com/stascorp/rdpwrap/issues/418 ?

**Comment by KEVORK890** [comment] 2018-03-28 10:24
same problem with windows 8.0

**Comment by binarymaster** [comment] 2018-05-16 07:27
Duplicate of #418.

**Closed by binarymaster** 2018-05-16 07:27 UTC
