### ISSUE TITLE
Please help me for 10.0.19041.2075, thanks!

### ISSUE THREAD

**Issue by zk36** [stascorp/rdpwrap#2079] opened 2023-01-02 06:00 UTC
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/10330196/termsrv.zip)

**Comment by sashaqwert** [comment] 2023-01-02 07:41
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992

**Closed as not planned by sashaqwert** 2023-01-02 07:41 UTC
Labels: duplicate

**Comment by zk36** [comment] 2023-01-02 09:16
Thank you!

There is solution that helped me:

Put new rdpwrap.ini in the same folder as rdpwinst.exe
Open command line
rdpwinst -u -k
rdpwinst -i
