### ISSUE TITLE
17763.1999 not working

### ISSUE THREAD

**Issue by buzzyun** [stascorp/rdpwrap#1427] opened 2021-06-10 04:53 UTC
please help
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/6644898/termsrv.zip)

**Comment by sebaxakerhtc** [comment] 2021-06-10 07:49
> please help

Please, attach your zipped c:\windows\system32\tremsrv.dll

**Comment by Random920612** [comment] 2021-06-10 11:39
same problem
thats my termsrv.dll in archive
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/6630989/termsrv.zip)

**Comment by sebaxakerhtc** [comment] 2021-06-10 11:57
> same problem
> thats my termsrv.dll in archive
> [termsrv.zip](https://github.com/stascorp/rdpwrap/files/6630989/termsrv.zip)

Your termsrv.dll version is 17763.1971
I have a solution for this one 
![Снимок экрана 2021-06-10 в 14 55 05](https://user-images.githubusercontent.com/32651506/121520674-da37db00-c9fb-11eb-82da-6c148f8f7f47.png)

[Look here](https://github.com/stascorp/rdpwrap/issues/1415) or directly from my project [here](https://github.com/sebaxakerhtc/rdpwrap.ini)

**Comment by buzzyun** [comment] 2021-06-14 00:09
17763.1999 problem
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/6644894/termsrv.zip)

**Comment by zekecarter** [comment] 2021-06-19 01:03
@sebaxakerhtc 
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/6679743/termsrv.zip)
Windows 10 LTSC x64
10.0.17763.1971
compilation 17763.1999
Not working
i try your fix but not working
![login error](https://user-images.githubusercontent.com/83554130/122626423-24f6ca00-d070-11eb-8128-e2b41ba71c30.png)

**Comment by varlock9k** [comment] 2021-07-16 17:56
@buzzyun
I used rdpwrap.ini & termsrv.dll from 10.0.17763.292
https://github.com/stascorp/rdpwrap/issues/699#issuecomment-473434247
It works!

**Comment by konstz43** [comment] 2021-07-28 10:09
> > same problem
> > thats my termsrv.dll in archive
> > [termsrv.zip](https://github.com/stascorp/rdpwrap/files/6630989/termsrv.zip)
> 
> Your termsrv.dll version is 17763.1971
> I have a solution for this one
> ![Снимок экрана 2021-06-10 в 14 55 05](https://user-images.githubusercontent.com/32651506/121520674-da37db00-c9fb-11eb-82da-6c148f8f7f47.png)
> 
> [Look here](https://github.com/stascorp/rdpwrap/issues/1415) or directly from my project [here](https://github.com/sebaxakerhtc/rdpwrap.ini)

Thank's! It helped me.
It works on my system: compilation 17763.2061

**Comment by sebaxakerhtc** [comment] 2021-10-27 12:37
Duplicate of https://github.com/stascorp/rdpwrap/issues/1415

**Closed as completed by sebaxakerhtc** 2021-10-27 12:37 UTC
