### ISSUE TITLE
Important delays openning users session in win10 18362.418 after Windows update

### ISSUE THREAD

**Issue by fdiperna** [stascorp/rdpwrap#908] opened 2019-10-15 15:45 UTC
Hi..
After reinstall RDP Wrapper, works fine with  win10 18362.418, but every user wich open session, must wait, at least, 5 mins to view their desktop....
Bug or i need to investigate why in the OS?
Thank you in advance....

**Comment by Dabao2010** [comment] 2019-10-31 00:35
I have the same problem on my desktop with os 17134.885.

if trying to log on within 5 minutes after startup, the remote window will be closed soon and you will never log on remotely and even cannot logon on the console.

**Comment by sebaxakerhtc** [comment] 2022-06-20 10:14
Duplicate of https://github.com/stascorp/rdpwrap/issues/871

**Closed as completed by sebaxakerhtc** 2022-06-20 10:14 UTC
