### ISSUE TITLE
Windows 10 Pro ver 10.0.18363.778

### ISSUE THREAD

**Issue by MurrayWatts** [stascorp/rdpwrap#1062] opened 2020-04-22 23:59 UTC
Does anyone know if there is an update for Windows 10 Pro ver 10.0.18363.778?

**Comment by maniek6** [comment] 2020-04-23 09:19
Try this:
https://github.com/DrDrrae/rdpwrap/blob/72e6b9ec967d50c9e213fce65422099edceecc6e/res/rdpwrap.ini

**Comment by Hagrid78** [comment] 2020-04-23 09:57
im trying this now but it still shows the older build number but if you look at the code it shows build 2004 from 1903 but there is no 1909 very odd
![image](https://user-images.githubusercontent.com/26916567/80086121-3fdeb480-8527-11ea-9f66-2b395f1115bf.png)

**Comment by maniek6** [comment] 2020-04-23 10:12
"fully supported" what you want more?

**Comment by s0nic9** [comment] 2020-04-23 13:09
"fully supported" doesn't mean patch is applied.
if .ini is malformed about missing ending blank line or incorrect encoding file. rdpconf say "fully supported" but the rdpwrap.dll cannot load .ini so rdpwrap is inactive.

**Comment by Hagrid78** [comment] 2020-04-24 03:36
@maniek6  if you go [here]( https://github.com/stascorp/rdpwrap/issues/1060)  you will see the issue im having.

**Comment by devsk** [comment] 2020-04-26 18:48
> Try this:
> https://github.com/DrDrrae/rdpwrap/blob/72e6b9ec967d50c9e213fce65422099edceecc6e/res/rdpwrap.ini

This doesn't seem to work. I get no remote desktop....:-(

Looks like the latest supported Windows 10 build is 10.0.18362.657 but I am at 18363.778.

**Comment by devsk** [comment] 2020-05-03 17:56
Is anyone looking at adding support for the latest Windows 10 Pro build in the rdpwrap.ini?

**Comment by sebaxakerhtc** [comment] 2022-04-27 16:06
Duplicate of https://github.com/stascorp/rdpwrap/issues/1059

**Closed as completed by sebaxakerhtc** 2022-04-27 16:06 UTC
