### ISSUE TITLE
Add support for termsrv 9600.18931

### ISSUE THREAD

**Issue by KipFun** [stascorp/rdpwrap#421] opened 2018-03-02 08:21 UTC
Win 8.1 build 9600.18931, please add support 
[termsrv_9600.18931.zip](https://github.com/stascorp/rdpwrap/files/1774209/termsrv_9600.18931.zip)

**Comment by NMCowboy** [comment] 2018-03-11 21:22
I have Windows 8.1 on my Media Center and it also just got updated but with Version 18928 but it is much larger than yours. Did you send the 32 bit version by any chance? And yes, I unzipped yours before comparing.

**Comment by binarymaster** [comment] 2018-05-16 07:47
Attached binary have build number 6.3.9600.18928, so duplicate of #418.

**Closed by binarymaster** 2018-05-16 07:47 UTC
