### ISSUE TITLE
PROBLEM RDP STATE:   NOT LISTENING 

### ISSUE THREAD

**Issue by LCoelhoRJ** [stascorp/rdpwrap#1759] opened 2022-03-04 19:54 UTC
I need help as I have LISTENER STATE with NOT LISTENING status. I've rebooted the desktop many times, modified the RDPWRAP.INI file, but the problem remains.

Windows Version:  21H1
\\rdp Wrapper ver. 1.5.0.0
                         ver. 10.0.19041.1503

**Comment by LCoelhoRJ** [comment] 2022-03-04 19:55
![image](https://user-images.githubusercontent.com/100963723/156832544-4375a25d-7d43-4116-9fac-e90c8052d9b6.png)

I NEED HELP !!!

**Comment by sashaqwert** [comment] 2022-03-05 15:34
Duplicate of https://github.com/stascorp/rdpwrap/issues/1697

Please, reboot your PC (Server) and check RDPConf again...

**Closed as completed** 2022-03-07 11:08 UTC
