### ISSUE TITLE
Not Listening fully supported 19041.1348

### ISSUE THREAD

**Issue by oliverkristianfritsche** [stascorp/rdpwrap#1842] opened 2022-05-11 00:35 UTC
![image](https://user-images.githubusercontent.com/61664788/167746041-8e18ec95-bc89-4dca-953e-17ab099b6da3.png)

**Comment by sebaxakerhtc** [comment] 2022-05-11 06:37
Duplicate of https://github.com/stascorp/rdpwrap/issues/1595

**Closed as completed by sebaxakerhtc** 2022-05-11 06:37 UTC
