### ISSUE TITLE
Not working on Windows 10 Professional (x64) Version 2009 (build 19042.1288)

### ISSUE THREAD

**Issue by cheshyrex** [stascorp/rdpwrap#1559] opened 2021-10-17 19:13 UTC
PC recently updated to Windows 10 Professional (x64) Version 2009 (build 19042.1288)

[autoupdate.log (attached)](https://github.com/stascorp/rdpwrap/files/7360670/autoupdate.log) gives error message referencing different version:
`NOT found "termsrv.dll" version entry [10.0.19041.1202] in file "C:\Program Files\RDP Wrapper\rdpwrap_new.ini"!`

RDPComp says not supported:
![image](https://user-images.githubusercontent.com/18754753/137641500-448f5270-2057-49a9-88c9-360cc3585410.png)
What further info do you need?

**Comment by Cosmits** [comment] 2021-10-18 09:03
[10.0.19041.1202-SLInit]
; no x86 section

bServerSku.x64        =10710C
bRemoteConnAllowed.x64=107120
bFUSEnabled.x64       =10712C
bAppServerAllowed.x64 =107118
bMultimonAllowed.x64  =107124
lMaxUserSessions.x64  =107110
ulMaxDebugSessions.x64=107128
bInitialized.x64      =107108

[10.0.19041.1202]
; no x86 section

LocalOnlyPatch.x64    =1
LocalOnlyOffset.x64   =89D81
LocalOnlyCode.x64     =jmpshort
SingleUserPatch.x64   =1
SingleUserOffset.x64  =0D212
SingleUserCode.x64    =Zero
DefPolicyPatch.x64    =1
DefPolicyOffset.x64   =19105
DefPolicyCode.x64     =CDefPolicy_Query_eax_rcx
SLInitHook.x64        =1
SLInitOffset.x64      =1E98C
SLInitFunc.x64        =New_CSLQuery_Initialize

**Comment by om50896** [comment] 2021-10-18 09:05
The newest rdpwrap.ini, link located below, is tested and 100% working.
https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

**Comment by cheshyrex** [comment] 2021-10-21 21:29
autoupdate.bat currently has the following lines:
`set rdpwrap_ini_update_github_1="https://raw.githubusercontent.com/asmtron/rdpwrap/master/res/rdpwrap.ini"
set rdpwrap_ini_update_github_2="https://raw.githubusercontent.com/saurav-biswas/rdpwrap-1/patch-1/res/rdpwrap.ini"
REM set rdpwrap_ini_update_github_3="https://raw.githubusercontent.com/....Extra.3...."`
I removed the REM on line 3 and changed the URL to the one provided.
And that seemed to work (at least according to RDPComp - haven't logged in remotely yet).

Huzzah!

And, thank you VERY much.

**Comment by kostyanp95** [comment] 2021-10-22 12:26
> The newest rdpwrap.ini, link located below, is tested and 100% working. https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

Why it work for 19043.1288 version?

![image](https://user-images.githubusercontent.com/51831069/138458484-bafb9577-48f1-4255-aed4-dc1ee5da24a6.png)

**Comment by RodolfoBigues** [comment] 2021-10-22 12:47
![image](https://user-images.githubusercontent.com/92989780/138455915-ea440295-abed-4f60-93ab-2066a2d09c64.png)
How i fix this problem?

**Comment by sebaxakerhtc** [comment] 2021-10-25 15:44
duplicate of https://github.com/stascorp/rdpwrap/issues/1509

**Closed as completed by sebaxakerhtc** 2021-10-25 15:44 UTC
