### ISSUE TITLE
19044.1826 Not Supported

### ISSUE THREAD

**Issue by jikeidea** [stascorp/rdpwrap#1928] opened 2022-07-13 11:08 UTC
help me

**Comment by jikeidea** [comment] 2022-07-13 11:09
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/9101501/termsrv.zip)

**Comment by jikeidea** [comment] 2022-07-13 11:19
![image](https://user-images.githubusercontent.com/43924085/178721888-2d42855b-aea6-4df5-adaa-b98e6e1f496f.png)

**Comment by jikeidea** [comment] 2022-07-13 11:25
When I use this ini, it is fully supported in RDPConf, but only one user is allowed to be online remotely。
[rdpwrap.txt](https://github.com/stascorp/rdpwrap/files/9101596/rdpwrap.txt)

**Comment by binarymaster** [comment] 2022-07-13 11:27
Duplicate of #1881.

**Closed as completed by binarymaster** 2022-07-13 11:27 UTC
Labels: duplicate

**Comment by jikeidea** [comment] 2022-07-13 11:30
I use the ini of #1881, but it doesn't work

**Comment by zldlhn** [comment] 2022-07-16 07:22
> I use the ini of #1881, but it doesn't work

Have you found a solution? I have encountered the same problem
