### ISSUE TITLE
rdpwrap v1.6.2 Not working for Remote Desktop Service version 10.0.19041.1503 | Windows 10 Home Version - 21H1 & OS Build - 19043.1526

### ISSUE THREAD

**Issue by priyadarshanparida** [stascorp/rdpwrap#1711] opened 2022-02-09 12:31 UTC
rdpwrap worked fine on my laptop. It has stopped working after the latest patch installation. Can someone share the updated .ini file please? Here are the details:
Edition: Windows 10 Home
Version: 21H1
OS build: 19043.1526

This is what I see on running rdpconf (as an administrator)
Wrapper state: Installed ver. 1.5.0.0
Service state: Running ver. 10.0.19041.1503
Listener state: Not listening [not supported]

![image](https://user-images.githubusercontent.com/16783956/153201336-f51685f7-f6b4-4b5c-befb-29d76bf68bbf.png)

**Comment by dooet46** [comment] 2022-02-09 12:48
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/8032796/termsrv.zip)

**Comment by smasterru** [comment] 2022-02-09 13:12
https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

**Comment by sebaxakerhtc** [comment] 2022-02-09 15:09
Duplicate of https://github.com/stascorp/rdpwrap/issues/1697

**Closed as completed by sebaxakerhtc** 2022-02-09 15:09 UTC

**Comment by priyadarshanparida** [comment] 2022-02-09 15:18
Thank you @smasterru & @sebaxakerhtc! The linked ini worked a treat.

**Comment by holmrn1** [comment] 2022-02-14 10:56
> https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini
THX! Works - 19042.1526 👍👍👍👍
