### ISSUE TITLE
I need the INI configuration file 10.0.19041.1202 x64

### ISSUE THREAD

**Issue by huanhaishijie** [stascorp/rdpwrap#1527] opened 2021-09-18 03:07 UTC

**Comment by huanhaishijie** [comment] 2021-09-18 03:23
I need the INI configuration file for 10.0.19041.1202 x64

**Comment by ufxpri** [comment] 2021-09-18 06:20
maybe this comment would help you
[https://github.com/stascorp/rdpwrap/issues/1520#issuecomment-920577168](https://github.com/stascorp/rdpwrap/issues/1520#issuecomment-920577168)
he uploaded his ini file with 10.0.19041.1201 in there

**Comment by huanhaishijie** [comment] 2021-09-18 07:19
thank you！

**Comment by Tonk2415** [comment] 2021-09-23 07:58
thank you

**Comment by sebaxakerhtc** [comment] 2021-10-25 16:06
duplicate of https://github.com/stascorp/rdpwrap/issues/1509

**Closed as completed by sebaxakerhtc** 2021-10-25 16:06 UTC
