### ISSUE TITLE
Not supported 

### ISSUE THREAD

**Issue by paujan12** [stascorp/rdpwrap#1493] opened 2021-08-19 18:33 UTC
![image](https://user-images.githubusercontent.com/35859205/130124749-2f9fee6f-e352-4904-94ba-5593c4440094.png)

This is my system
Edition: Windows 10 Pro
Version: 20H2
OS build: 19042.1165

**Comment by varlock9k** [comment] 2021-08-19 23:33
@paujan12 

Try rdpwrap.ini from 10.0.19041.1081

https://github.com/stascorp/rdpwrap/issues/1490#issuecomment-902317744

**Comment by JungsonStone** [comment] 2021-08-29 09:01
I've already replaced the rdpwrap.ini with https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini
it is right to use the resolution of version 19041.1081

**Comment by sebaxakerhtc** [comment] 2021-10-25 16:09
duplicate of https://github.com/stascorp/rdpwrap/issues/1447

**Closed as completed by sebaxakerhtc** 2021-10-25 16:09 UTC
