### ISSUE TITLE
Tried all the Fixes I can find for Listener State Not Listening

### ISSUE THREAD

**Issue by Maverick494** [stascorp/rdpwrap#649] opened 2019-01-27 19:36 UTC
I have replaced the term dll and the rfxvmt as suggested in all the other posts I can find and I still get:

<a href="https://imgbb.com/"><img src="https://i.ibb.co/ZzDwy1b/Broken-RDPWrapper.jpg" alt="Broken-RDPWrapper" border="0"></a><br />

I have uninstalled and reinstalled.  I have stopped and restarted termservice.

What else is there to try?

**Comment by binarymaster** [comment] 2019-01-27 21:47
Duplicate of #645.

**Closed as completed by binarymaster** 2019-01-27 21:47 UTC
Labels: duplicate
