### ISSUE TITLE
ver. 10.0.19041.3636 [not supported]

### ISSUE THREAD

**Issue by Henzato** [stascorp/rdpwrap#2440] opened 2023-12-10 23:38 UTC
having trouble unfortunately 

![image_2023-12-10_163652543](https://github.com/stascorp/rdpwrap/assets/153467238/530dd37d-6255-4123-90f5-abf2780ba132)

**Comment by Henzato** [comment] 2023-12-11 02:09
using windows 10 pro btw

**Comment by DnsZhou** [comment] 2023-12-13 00:22
Duplicated with https://github.com/stascorp/rdpwrap/issues/2381 , see https://github.com/stascorp/rdpwrap/issues/2381#issuecomment-1782856121 for the fix.

**Comment by sashaqwert** [comment] 2023-12-13 06:47
Duplicate of https://github.com/stascorp/rdpwrap/issues/2381

**Closed as not planned by sashaqwert** 2023-12-13 06:47 UTC
Labels: duplicate
