### ISSUE TITLE
Version 6.3.9600.20165 not supported

### ISSUE THREAD

**Issue by sbdman** [stascorp/rdpwrap#1604] opened 2021-11-10 15:26 UTC
I'd kindly appreciate if someone could give the offsets for an ini file for Termsrv.dll version 6.3.9600.20165.
This is my HTPC running a digital cable card for TV viewing on Windows 8 Pro.
RDPWrapper is an absolute necesity - thanks in advance!

**Comment by sashaqwert** [comment] 2021-11-10 15:42
Original DLL: https://t.me/rdpwrap/37768

**Comment by sbdman** [comment] 2021-11-10 16:04
Sorry, just saw this is originally in #1597.
I'll wait for the new offsets in that post.

**Comment by sebaxakerhtc** [comment] 2021-11-10 16:05
Duplicate of https://github.com/stascorp/rdpwrap/issues/1597

**Closed as completed by sebaxakerhtc** 2021-11-10 16:05 UTC
