### ISSUE TITLE
10.0.17763.771 Not supported

### ISSUE THREAD

**Issue by Sentinas** [stascorp/rdpwrap#3324] opened 2024-10-31 09:42 UTC
Hi there,
Thanks for keeping up this project!
I'm getting not supported for this version.
Can you help me out?
[termsrv.zip](https://github.com/user-attachments/files/17585799/termsrv.zip)

**Comment by binarymaster** [comment] 2024-10-31 17:39
Duplicate of https://github.com/stascorp/rdpwrap/issues/886.

**Closed as not planned by binarymaster** 2024-10-31 17:39 UTC
Labels: duplicate
