### ISSUE TITLE
New build Windows 10 Version 19044.1568 Not Supported

### ISSUE THREAD

**Issue by Stefpls** [stascorp/rdpwrap#1775] opened 2022-03-16 07:15 UTC
The new Windows 10 build 19044.1568 is not supported. "rdpwrap.ini" file from dear sir sebaxakerhtc no longer works

**Comment by martnbee** [comment] 2022-03-16 10:06
could it be 19044.1586  ?

**Comment by sebaxakerhtc** [comment] 2022-03-17 07:54
> The new Windows 10 build 19044.1568 is not supported. "rdpwrap.ini" file from dear sir sebaxakerhtc no longer works

Rdpconf screenshot please

**Comment by sebaxakerhtc** [comment] 2022-03-17 07:56
Looks like duplicate of https://github.com/stascorp/rdpwrap/issues/1725
But with error in Version

**Closed as completed by sebaxakerhtc** 2022-03-17 07:56 UTC

**Comment by Stefpls** [comment] 2022-03-18 13:12
> could it be 19044.1586 ?

Yes! 19044.1586!
