### ISSUE TITLE
10.0.19041.4474 please help, “access denied.”

### ISSUE THREAD

**Issue by ebladekidd** [stascorp/rdpwrap#3262] opened 2024-08-30 13:44 UTC
![image](https://github.com/user-attachments/assets/24810ac4-a235-463f-8f64-869f7efb2763)
![image](https://github.com/user-attachments/assets/eb341ca0-b9e3-4a2e-9ef6-2fb4b06eec2a)
![image](https://github.com/user-attachments/assets/f9218ea4-ea5e-42ab-9e78-bda9533c1cde)
why it doesnt work? I can't even download it.

**Comment by binarymaster** [comment] 2024-08-30 16:13
Duplicate of #3222.

**Closed as not planned by binarymaster** 2024-08-30 16:13 UTC
Labels: duplicate
