### ISSUE TITLE
Can't uninstall RDP

### ISSUE THREAD

**Issue by Daniel-Zheleznov** [stascorp/rdpwrap#1376] opened 2021-04-17 18:14 UTC
So My RDP Wrapper didn't work so I tried to uninstall it using the bat file it said it finished but i went to control panel and it said it didn't uninstall so I tried uninstalling it through control panel now it is yelling at me this.
![Screenshot 2021-04-17 141411](https://user-images.githubusercontent.com/66643531/115122681-3b58aa80-9f87-11eb-8046-8517a7f64878.png)

**Comment by sebaxakerhtc** [comment] 2022-06-03 10:44
Duplicate of https://github.com/stascorp/rdpwrap/issues/1078

**Closed as completed by sebaxakerhtc** 2022-06-03 10:44 UTC
