### ISSUE TITLE
Windows 10 Pro 10.0.19045.2965 not supported 

### ISSUE THREAD

**Issue by ChasNetFL** [stascorp/rdpwrap#2236] opened 2023-06-01 20:55 UTC
Cannot find solution to 'not supported' for this 22H2 OS version.  Cannot locate/identify rdpwrap.ini solution or replacement code for termsrv.dll approach.

**Comment by sebaxakerhtc** [comment] 2023-06-02 06:24
> Cannot locate/identify rdpwrap.ini solution

Attach your zipped termsrv.dll and screenshot of RDP_CnC or RDPConf
termsrv.dll can't version 19045 it should be 19041

**Comment by sebaxakerhtc** [comment] 2023-06-02 06:35
Duplicate of https://github.com/stascorp/rdpwrap/issues/2180

**Closed as completed by sebaxakerhtc** 2023-06-02 06:35 UTC
Labels: duplicate

**Comment by ChasNetFL** [comment] 2023-06-02 15:19
Thank you for your support.
Chas

Chas M White, MS - President
White Associates Research & Development, LLC
Melbourne, FL USA 32940
Global TN +1 321 276 5561 (Mobile & WhatsApp)
eMail: ***@***.******@***.***>
***@***.*** <http://www.linkedin.com/in/chaswhite> Join me on LinkedIn<https://www.linkedin.com/in/ChasWhite>

**Comment by ChasNetFL** [comment] 2023-06-02 17:58
This resolved my problem.  Thanks!

Sent from my iPhone
Mobile : +1 321-276-5561

On Jun 2, 2023, at 02:35, sebaxakerhtc ***@***.***> wrote:

﻿

Duplicate of #2180<https://github.com/stascorp/rdpwrap/issues/2180>

**Comment by ChasNetFL** [comment] 2023-06-02 17:58
﻿This resolved my problem.  Thanks!

Sent from my iPhone
Mobile : +1 321-276-5561

On Jun 2, 2023, at 02:35, sebaxakerhtc ***@***.***> wrote:

﻿

Duplicate of #2180<https://github.com/stascorp/rdpwrap/issues/2180>
