### ISSUE TITLE
Not supported 19044.1586

### ISSUE THREAD

**Issue by ermannog** [stascorp/rdpwrap#1763] opened 2022-03-09 15:35 UTC
After Windows Update on March 8, 2022—KB5011487. Thank you for your support in fixing this :-)

**Comment by gsvano** [comment] 2022-03-10 01:23
https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini

**Comment by sebaxakerhtc** [comment] 2022-03-10 10:06
Duplicate of https://github.com/stascorp/rdpwrap/issues/1725

**Closed as completed by sebaxakerhtc** 2022-03-10 10:06 UTC

**Comment by ermannog** [comment] 2022-03-10 11:35
Many thanks!

**Comment by ermannog** [comment] 2022-03-11 17:05
Many thanks, I confirm that the ini file works!
