### ISSUE TITLE
10.0.17763.1697 not supported

### ISSUE THREAD

**Issue by yybinpitaya** [stascorp/rdpwrap#1562] opened 2021-10-19 03:09 UTC
10.0.17763.1697 not supported

**Comment by sebaxakerhtc** [comment] 2021-10-25 15:32
> 10.0.17763.1697 not supported

Is your version of Windows x86 or x64?

**Comment by auliarahmed** [comment] 2021-10-27 03:53
omg, same version here, not supported, any solution?

**Comment by auliarahmed** [comment] 2021-10-27 04:25
> > 10.0.17763.1697 not supported
> 
> Is your version of Windows x86 or x64?

64 bit, any solution sir?

**Comment by sebaxakerhtc** [comment] 2021-10-27 08:09
> > > 10.0.17763.1697 not supported
> > 
> > 
> > Is your version of Windows x86 or x64?
> 
> 64 bit, any solution sir?

https://github.com/sebaxakerhtc/rdpwrap.ini/commit/2738288a7abd7f62026b085442f2f7920fcbdd25

**Comment by sebaxakerhtc** [comment] 2022-06-20 13:29
Duplicate of https://github.com/stascorp/rdpwrap/issues/1276

**Closed as completed by sebaxakerhtc** 2022-06-20 13:29 UTC
