### ISSUE TITLE
Help Windows 10 Version 20H2 OS Build 19042.1348 listener state: Listening but [not supported]

### ISSUE THREAD

**Issue by bryandavis1970** [stascorp/rdpwrap#1634] opened 2021-11-24 11:23 UTC

**Comment by sebaxakerhtc** [comment] 2021-11-25 11:18
Duplicate of https://github.com/stascorp/rdpwrap/issues/1595

**Closed as completed by sebaxakerhtc** 2021-11-25 11:18 UTC

**Comment by sidiosidi** [comment] 2021-11-30 10:00
Not duplicate, It's 19042.1348 not 19041.1348

**Comment by sebaxakerhtc** [comment] 2021-11-30 10:22
Look at your termsrv.dll version!

вт, 30 нояб. 2021 г., 12:00 sidiosidi ***@***.***>:
