### ISSUE TITLE
Windows 10 Home [not supported]

### ISSUE THREAD

**Issue by grant-h** [stascorp/rdpwrap#109] opened 2016-04-18 19:10 UTC
With a fresh install of Windows 10 Home from this tool (v1.6) doesnt appear to be supported.
Below is the system info. If you need more info, let me know.

![config](https://cloud.githubusercontent.com/assets/3030665/14616269/97235c16-0577-11e6-85a3-822b57bece8c.PNG)
![rdpwrap-version](https://cloud.githubusercontent.com/assets/3030665/14616271/9a86ed82-0577-11e6-9220-4559e3f48ec3.PNG)
![updates](https://cloud.githubusercontent.com/assets/3030665/14616275/9d04e15e-0577-11e6-971e-9003738a6075.PNG)
![win-version](https://cloud.githubusercontent.com/assets/3030665/14616277/a055c940-0577-11e6-8346-ed261c2043b8.PNG)

**Comment by binarymaster** [comment] 2016-04-19 16:04
Duplicate of https://github.com/stascorp/rdpwrap/issues/87

**Closed by binarymaster** 2016-04-19 16:04 UTC
Labels: duplicate
