### ISSUE TITLE
Fully Supported but Notlistening Windows 10 Ver 19041.1620 after update

### ISSUE THREAD

**Issue by saivedasree** [stascorp/rdpwrap#1794] opened 2022-03-29 08:31 UTC
![image](https://user-images.githubusercontent.com/102572944/160568073-42c22051-f654-4859-87d9-7955b5f8ff41.png)
![image](https://user-images.githubusercontent.com/102572944/160568619-994893d5-549e-445c-a3b2-a93bafe9193e.png)
Even after run the command same issue

**Comment by saivedasree** [comment] 2022-03-29 08:32
Can i Share Termservice.dll ?

**Comment by sebaxakerhtc** [comment] 2022-03-29 08:51
cmd as admin:
net start termservice
Duplicate of https://github.com/stascorp/rdpwrap/issues/1786

**Closed as completed by sebaxakerhtc** 2022-03-29 08:51 UTC
