### ISSUE TITLE
Win 10 x64 Pro - 10.0.19041.1620 not supported

### ISSUE THREAD

**Issue by ghost** [stascorp/rdpwrap#1784] opened 2022-03-23 02:34 UTC
!
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/8329232/termsrv.zip)
[capture](https://user-images.githubusercontent.com/43813712/159612556-c9595c47-6994-4020-b679-294a834f344f.PNG)

thanks in advance to anyone who can help me out.

**Comment by Champion1971** [comment] 2022-03-23 08:40
yes... the new version and the settings is missing here too

**Comment by sebaxakerhtc** [comment] 2022-03-23 10:12
Duplicate of https://github.com/stascorp/rdpwrap/issues/1783

**Closed as completed by sebaxakerhtc** 2022-03-23 10:12 UTC
