### ISSUE TITLE
Windows 11 PRO 10.02261.2361 not Supported 

### ISSUE THREAD

**Issue by dayspring-dev** [stascorp/rdpwrap#2350] opened 2023-10-02 10:38 UTC
![Windows 11 PRO 10 02261 2361 not Supported](https://github.com/stascorp/rdpwrap/assets/26641244/d41b76d1-e652-4b3a-8b3c-6a2376bc6505)

**Comment by dayspring-dev** [comment] 2023-10-02 10:43
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/12781934/termsrv.zip)

**Comment by dayspring-dev** [comment] 2023-10-02 16:21
Hello All
Installed the INI file 
https://github.com/sebaxakerhtc/rdpwrap.ini/blob/a929f7d8e2f09ff2058d9495408ee61b45463ab6/rdpwrap.ini

It now works correctly

**Comment by coreyman** [comment] 2023-10-03 13:55
@msturtz2017 thanks for posting your solution. It worked for me with that .ini as well.

**Comment by sashaqwert** [comment] 2023-10-03 17:30
Duplicate of https://github.com/stascorp/rdpwrap/issues/2345

**Closed as not planned by sashaqwert** 2023-10-03 17:30 UTC
Labels: duplicate
