### ISSUE TITLE
Windows 10 10.0.19045.2846 not supported

### ISSUE THREAD

**Issue by shixiaop** [stascorp/rdpwrap#2226] opened 2023-05-29 03:59 UTC
![图片](https://github.com/stascorp/rdpwrap/assets/45790553/645ad079-27e4-461e-a33c-62b6aa756a58)

**Comment by sashaqwert** [comment] 2023-05-29 07:03
Duplicate of https://github.com/stascorp/rdpwrap/issues/2125

**Closed as not planned** 2023-05-29 07:04 UTC
Labels: duplicate
