### ISSUE TITLE
 Windows 10 Pro 10.0.23466.1001 not supported

### ISSUE THREAD

**Issue by foxi1982** [stascorp/rdpwrap#2234] opened 2023-06-01 15:28 UTC
![grafik](https://github.com/stascorp/rdpwrap/assets/16001828/ec7d20da-2576-43e7-8ae4-6bc81b7dbc02)

this version not working, please help

**Comment by sebaxakerhtc** [comment] 2023-06-02 06:15
Duplicate of https://github.com/stascorp/rdpwrap/issues/2231

**Closed as completed by sebaxakerhtc** 2023-06-02 06:15 UTC
Labels: duplicate
