### ISSUE TITLE
Not Supported 10.0.19041.1741 WIN10

### ISSUE THREAD

**Issue by Tastenkasper** [stascorp/rdpwrap#1884] opened 2022-06-03 10:40 UTC
![image](https://user-images.githubusercontent.com/48354951/171838935-cbdb4fbc-bffb-4034-9a22-3de611ab659e.png)

**Comment by sebaxakerhtc** [comment] 2022-06-03 10:46
Duplicate of https://github.com/stascorp/rdpwrap/issues/1881

**Closed as completed by sebaxakerhtc** 2022-06-03 10:46 UTC
