### ISSUE TITLE
10.0.17763.5206

### ISSUE THREAD

**Issue by herrComputerVision** [stascorp/rdpwrap#2480] opened 2024-02-06 15:38 UTC
Requesting for this build. Thanks!

**Comment by sashaqwert** [comment] 2024-02-07 07:13
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by herrComputerVision** [comment] 2024-02-08 12:32
Hi! please find the win_ver, RDPconfig and termsrv,dll file!

Thanks!!
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/14209227/termsrv.zip)
![win_ver](https://github.com/stascorp/rdpwrap/assets/79802181/4584ed0a-959e-42bf-b647-e92d6069b16e)
![rdp_config](https://github.com/stascorp/rdpwrap/assets/79802181/811cfe61-30a2-4261-a277-e9732740f7f5)

**Comment by sashaqwert** [comment] 2024-02-08 13:18
Thanks! Solution in https://github.com/stascorp/rdpwrap/issues/2404

**Comment by sashaqwert** [comment] 2024-02-08 13:18
Duplicate of https://github.com/stascorp/rdpwrap/issues/2404

**Closed as not planned by sashaqwert** 2024-02-08 13:18 UTC
Labels: duplicate
