### ISSUE TITLE
Sessions Limite 15 - Window 10 x64 1903

### ISSUE THREAD

**Issue by DarKWinGTM** [stascorp/rdpwrap#833] opened 2019-07-14 18:13 UTC
Sessions Limite 15 - Window 10 x64 1903

My remote desktop patched with full support, But i found some issue remote desktop have connection limite 15 connection.

- Already config in "gpedit.msc"
- Already config in registery "MaxInstanceCount"

**Comment by songlim327** [comment] 2019-07-17 08:40
Hi,  i faced the same issue with Windows 10 x64 1903, do you found a solution for it?

**Comment by DarKWinGTM** [comment] 2019-07-17 09:13
No.

**Comment by DarKWinGTM** [comment] 2019-07-18 07:51
I found Solution for this issue, So am not sure it's bug in 1903 or not but you can startup all remote desktop as select all *.rdp file then press enter to open and connect all remote desktop in one enter action, This trick will bypass limite connection in 1903.

**Comment by DarKWinGTM** [comment] 2019-07-18 07:52
I found Solution for this issue, So am not sure it's bug in 1903 or not, You can startup all remote desktop by select all *.rdp file then press enter to open all connect remote desktop in one action with enter, This trick will bypass limite connection in 1903.

**Comment by chocolait** [comment] 2019-08-03 05:15
could you clarify?

**Comment by mrselek** [comment] 2019-10-25 15:59
My Sessions Limite is 5. How can I more? without *,rdp file!

**Comment by sebaxakerhtc** [comment] 2022-04-27 14:53
Duplicate of https://github.com/stascorp/rdpwrap/issues/512

**Closed as completed by sebaxakerhtc** 2022-04-27 14:53 UTC
