### ISSUE TITLE
22631.3737 on Windows 11 not supported

### ISSUE THREAD

**Issue by omln** [stascorp/rdpwrap#3219] opened 2024-06-27 23:38 UTC
help me please
rdpwrap.ini needs update.

**Comment by loyejaotdiqr47123** [comment] 2024-06-28 07:52
@revistasp Please, attach your RDPConf screenshot and termsrv.dll.

**Comment by omln** [comment] 2024-06-28 10:45
termsrv.dll is a file fully encrypted, but here is the screenshot:
![image](https://github.com/stascorp/rdpwrap/assets/125148176/77a522b5-962d-428d-a858-c282f0b60f1f)
![image](https://github.com/stascorp/rdpwrap/assets/125148176/0dd363d9-2350-4696-bb99-50145ca4191b)

**Comment by loyejaotdiqr47123** [comment] 2024-06-28 10:47
Duplicate of #2833

**Comment by omln** [comment] 2024-06-28 11:41
![image](https://github.com/stascorp/rdpwrap/assets/125148176/47c7cfc8-7750-44c1-a1b7-f72f870f52be)

rdpwrap.ini content:

```
; RDP Wrapper Library configuration
; Do not modify without special knowledge
; Edited by sebaxakerhtc

[Main]
Updated=2024-06-27
LogFile=\rdpwrap.txt
SLPolicyHookNT60=1
SLPolicyHookNT61=1

[SLPolicy]
TerminalServices-RemoteConnectionManager-AllowRemoteConnections=1
TerminalServices-RemoteConnectionManager-AllowMultipleSessions=1
TerminalServices-RemoteConnectionManager-AllowAppServerMode=1
TerminalServices-RemoteConnectionManager-AllowMultimon=1
TerminalServices-RemoteConnectionManager-MaxUserSessions=0
TerminalServices-RemoteConnectionManager-ce0ad219-4670-4988-98fb-89b14c2f072b-MaxSessions=0
TerminalServices-RemoteConnectionManager-45344fe7-00e6-4ac6-9f01-d01fd4ffadfb-MaxSessions=2
TerminalServices-RDP-7-Advanced-Compression-Allowed=1
TerminalServices-RemoteConnectionManager-45344fe7-00e6-4ac6-9f01-d01fd4ffadfb-LocalOnly=0
TerminalServices-RemoteConnectionManager-8dc86f1d-9969-4379-91c1-06fe1dc60575-MaxSessions=1000
TerminalServices-DeviceRedirection-Licenses-TSEasyPrintAllowed=1
TerminalServices-DeviceRedirection-Licenses-PnpRedirectionAllowed=1
TerminalServices-DeviceRedirection-Licenses-TSMFPluginAllowed=1
TerminalServices-RemoteConnectionManager-UiEffects-DWMRemotingAllowed=1

[PatchCodes]
nop=90
Zero=00
jmpshaort=EB
nopjmp=90E9
CDefPolicy_Query_edx_ecx=BA000100008991200300005E90
CDefPolicy_Query_eax_rcx_jmp=B80001000089813806000090EB
CDefPolicy_Query_eax_esi=B80001000089862003000090
CDefPolicy_Query_eax_rdi=B80001000089873806000090
; CDefPolicy_Query_eax_ecx=B80001000089812003000090
CDefPolicy_Query_eax_ecx=B80001000089812403000090
CDefPolicy_Query_eax_ecx_jmp=B800010000898120030000EB0E
CDefPolicy_Query_eax_rcx=B80001000089813806000090
CDefPolicy_Query_edi_rcx=BF0001000089B938060000909090
; new patch by sebaxakerhtc
; CDefPolicy_Query_eax_rdi_jmp=B800010000898738060000EB0D
; Edited patch by bobo
CDefPolicy_Query_eax_rdi_jmp=B80001000089873806000090EB
nop_3=909090
nop_7=90909090909090
mov_eax_1_nop_1=B80100000090
mov_eax_1_nop_2=B8010000009090
nop_4=90909090
pop_eax_add_esp_12_nop_2=5883C40C9090

[10.0.22621.3672]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=9EFB1
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
;SingleUserOffset.x64=C4D3
;SingleUserCode.x64=Zero
SingleUserOffset.x64=C503
SingleUserCode.x64=mov_eax_1_nop_2
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1C415
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=2C040
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.22621.3672-SLInit]
bInitialized.x64=      12DF6C
bServerSku.x64=        12DF70
lMaxUserSessions.x64=  12DF74
bAppServerAllowed.x64= 12DF7C
bRemoteConnAllowed.x64=12DF84
bMultimonAllowed.x64=  12DF88
ulMaxDebugSessions.x64=12DF90
bFUSEnabled.x64=       12DF94
```

**Comment by loyejaotdiqr47123** [comment] 2024-06-28 11:45
@revistasp 
Please, attach your termsrv.dll file

**Comment by omln** [comment] 2024-06-28 11:47
[termsrv.zip](https://github.com/user-attachments/files/16028826/termsrv.zip)

**Comment by omln** [comment] 2024-06-28 12:12
issue solved >
[rdpwrap.zip](https://github.com/user-attachments/files/16029340/rdpwrap.zip)

NOTE: [not supported] still appears, but it worked perfectly.

**Comment by loyejaotdiqr47123** [comment] 2024-06-28 12:23
[RDPWrap-v1.8.5.zip](https://github.com/user-attachments/files/16029502/RDPWrap-v1.8.5.zip)
Try running RDPWInst.exe -w

**Closed as not planned** 2024-06-28 13:09 UTC
Labels: duplicate
