### ISSUE TITLE
 limit of nine connections

### ISSUE THREAD

**Issue by infowayrs** [stascorp/rdpwrap#674] opened 2019-02-19 03:01 UTC
Friends when connecting the tenth user comes to me the following error msg:

your remote desktop session has been closed. Possible reasons:
the administrator has closed his session
There was an error establishing the connection
There was a problem on the network
![erro](https://user-images.githubusercontent.com/45184792/52986725-53e4ce80-33d7-11e9-8c9a-b9d0a260f79c.png)
my term.dll version
![rdpwrap](https://user-images.githubusercontent.com/45184792/52987170-dcb03a00-33d8-11e9-851c-dbde72945f20.png)

**Comment by infowayrs** [comment] 2019-02-19 03:02
I already tested 10.0.17763.165 and 10.0.17763.168 and 10.0.17763.288 also could not run 10.0.0.17763.1 the service does not start with this dll

**Comment by infowayrs** [comment] 2019-02-19 03:07
hardware
![config](https://user-images.githubusercontent.com/45184792/52987528-349b7080-33da-11e9-81b3-ced319d1cd64.png)

**Comment by binarymaster** [comment] 2019-02-19 14:16
> I already tested 10.0.17763.165 and 10.0.17763.168 and 10.0.17763.288 also could not run 10.0.0.17763.1 the service does not start with this dll

See existing issues. Your issue is a duplicate of them.

**Closed as completed by binarymaster** 2019-02-19 14:16 UTC
Labels: duplicate
