### ISSUE TITLE
how  to make it works?OS 19042.789

### ISSUE THREAD

**Issue by DakenYue** [stascorp/rdpwrap#1322] opened 2021-02-08 23:17 UTC
Listener state is listening but not supported.
![image](https://user-images.githubusercontent.com/38303129/107219005-6a184900-6a4b-11eb-9809-0f86c651c5f8.png)
i use the autoupdate.bat
but it show this
![image](https://user-images.githubusercontent.com/38303129/107292908-919bff80-6aa5-11eb-9e5c-c5148202d7ba.png)
Wait for network connection is available...

upload my termsrv.dll
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/5947378/termsrv.zip)

Please help

**Comment by ghost** [comment] 2021-02-10 01:20
Try with this..
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/5955274/rdpwrap.zip)

**Comment by remmahad** [comment] 2021-02-18 15:52
> Try with this..
> [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/5955274/rdpwrap.zip)

Worked for me, thanks!

**Comment by sebaxakerhtc** [comment] 2022-03-30 13:09
Duplicate of https://github.com/stascorp/rdpwrap/issues/1317

**Comment by DakenYue** [comment] 2022-03-30 13:09
您好，您的邮件  张越   已收到！

**Closed as completed by sebaxakerhtc** 2022-03-30 13:09 UTC
