### ISSUE TITLE
win10 -8362.836  not Supported

### ISSUE THREAD

**Issue by craca** [stascorp/rdpwrap#1096] opened 2020-06-16 06:13 UTC
Cracked file has taken effect.
However, multi-user connections are still not available

Trouble solving

![image](https://user-images.githubusercontent.com/3276069/84737365-59a5f080-afda-11ea-9e34-055b87044670.png)

![image](https://user-images.githubusercontent.com/3276069/84737480-97a31480-afda-11ea-993d-fa7876019f71.png)

**Comment by pepepl** [comment] 2020-06-16 06:43
I have the same service state version, here is a file. Just copy to installation folder
[rdpwrap.txt](https://github.com/stascorp/rdpwrap/files/4784839/rdpwrap.txt)
Change .txt to .ini. Change to "GUI Authentication Only".  Uncheck "Single Session Per User".After that just reboot PC

**Comment by craca** [comment] 2020-06-16 06:52
Thank you，I'll test it

**Comment by athos9204** [comment] 2020-06-16 20:11
I can confirm, it works for me now. Thanks

**Comment by D-Macc** [comment] 2020-06-23 12:36
> I have the same service state version, here is a file. Just copy to installation folder
> [rdpwrap.txt](https://github.com/stascorp/rdpwrap/files/4784839/rdpwrap.txt)
> Change .txt to .ini. Change to "GUI Authentication Only". Uncheck "Single Session Per User".After that just reboot PC

I followed the steps above.
All systems green, but still can't log in multiple users at the same time. 
Any advice?

![2020-06-23_1413_56_DM](https://user-images.githubusercontent.com/67323354/85404164-d9920480-b55e-11ea-8e18-185737d7e192.png)
![2020-06-23_1413_46_DM](https://user-images.githubusercontent.com/67323354/85404230-f0d0f200-b55e-11ea-92d6-338196f171f4.png)

**Comment by munziliashali** [comment] 2020-07-03 04:13
@D-Macc  have you solved this issue?

**Comment by robbak** [comment] 2020-07-03 05:19
Multiple sessions per user is always iffy. If you log on remotely, it will always disconnect the local session (returning the computer's display to the lock screen). This is unavoidable. But without the 'single session per user' option, a second remote user could also connect, and/or the local user could log back in to create a new session. Mostky, though, you should have separate user accounts for each person who wants to connect.

About this 'connections limited' error - there is a registry key that seems to control this. On the surface, it doesn't seem to be related - but I think that when it says 'connections' in this error message it means network socket connections, not RDP connections. (RDP makes many network socket connections) See https://www.kapilarya.com/the-number-of-connections-to-this-computer-is-limited-windows-10

The keys are in HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings , and are called MaxConnectionsPer1_0Server and MaxConnectionsPerServer . Yes, that is 1_0, (one_zero) not I_O as you might expect. Create them as DWORD Values. This recommends setting them to '10'. I think I have seen others setting them to '99999'

Other people have noted that it has causes that are temporary issues fixed by rebooting. Which means that you are going to find many people who stated how they fixed it - they did who knows what that did nothing to help it, and rebooted, which is what did fix the problem. Similarly with people disabling and enabling, or resetting, network adapters. 

Here is a page outlining how one person troubleshot their issue. It may help you, too - http://www.kuskaya.info/2014/05/23/how-to-troubleshoot-the-number-of-connections-to-this-computer-is-limited-and-all-connections-are-in-use-right-now-try-connecting-later-or-contact-your-system-administrator-warning-message/ His conclusion is that the error is misleading - the problem was, instead, a generic network connectivity and DNS issue.

Let us know how you go.

**Comment by strarsis** [comment] 2020-12-10 16:39
Was able to fix it using some INI from another user - but `RDPConf.exe` incorrectly indicates an unsupported version, see https://github.com/stascorp/rdpwrap/issues/1054#issuecomment-742637185.

**Comment by sebaxakerhtc** [comment] 2022-06-20 11:03
Duplicate of https://github.com/stascorp/rdpwrap/issues/1083

**Closed as completed by sebaxakerhtc** 2022-06-20 11:03 UTC
