### ISSUE TITLE
rdpwrap.ini for Windows 10 10.0.19041.2913 Not work

### ISSUE THREAD

**Issue by Celeroncillo** [stascorp/rdpwrap#2182] opened 2023-04-26 15:45 UTC
I need the ini file for this windows version, at my windows version show: 19045.2913.

Thanks

**Comment by AntSanDev** [comment] 2023-04-26 15:58
> I need the ini file for this windows version, at my windows version show: 19045.2913.
> 
> Thanks

There is already an [issue opened](https://github.com/stascorp/rdpwrap/issues/2180) for that version.

**Comment by sashaqwert** [comment] 2023-04-26 16:18
Duplicate of https://github.com/stascorp/rdpwrap/issues/2180

**Closed as not planned by sashaqwert** 2023-04-26 16:18 UTC
