### ISSUE TITLE
MY RDP IS SHOWING NOT SUPPORTED PLZZ HELP ME 

### ISSUE THREAD

**Issue by RakibMKhan** [stascorp/rdpwrap#2086] opened 2023-01-14 17:39 UTC
[New Microsoft Office Word Document (2).docx](https://github.com/stascorp/rdpwrap/files/10418406/New.Microsoft.Office.Word.Document.2.docx)

**Comment by sashaqwert** [comment] 2023-01-15 06:30
Duplicate of https://github.com/stascorp/rdpwrap/issues/1093

**Closed as not planned by sashaqwert** 2023-01-15 06:30 UTC
Labels: duplicate
