### ISSUE TITLE
Can't use multi-session since update 1809

### ISSUE THREAD

**Issue by tibast01** [stascorp/rdpwrap#644] opened 2019-01-18 21:09 UTC
Since we update Windows 10 to 1809 build, we can't use multi-session RDP like before.

Tried to re-install RDPWrapper and updated it, but it doesn't work.

![image](https://user-images.githubusercontent.com/46828467/51413010-79ae5780-1b3b-11e9-8f62-c1de222adba6.png)

**Comment by binarymaster** [comment] 2019-01-19 08:52
Duplicate of #601.

**Closed as completed by binarymaster** 2019-01-19 08:52 UTC
Labels: duplicate
