### ISSUE TITLE
Need help with running RDP-WRAPPER on windows 11

### ISSUE THREAD

**Issue by realaintreal** [stascorp/rdpwrap#2207] opened 2023-05-19 09:00 UTC
I've tried a few different things, but I can't seem to get my thing to work. When I connect using 127.0.0.1 it connects, but I can't do anything from there. What I mean is there is no place to enter my username or password and stuff like that. 

The windows version I'm on is  22621.1702
I'll provide as many screenshots as I can.
![Screenshot 2023-05-19 020013](https://github.com/stascorp/rdpwrap/assets/134051583/24aaa1d6-02a8-4102-adf7-165509e29715)
![Screenshot 2023-05-19 015947](https://github.com/stascorp/rdpwrap/assets/134051583/db2d4b7a-4c8a-45ec-8d8f-a7f30cf1b227)
![Screenshot 2023-05-19 015930](https://github.com/stascorp/rdpwrap/assets/134051583/7cb9b3dd-b1e3-47b5-b528-3e202768b209)

**Comment by sashaqwert** [comment] 2023-05-20 09:17
You need to [convert your Microsoft account to local account](https://www.digitalcitizen.life/switch-to-local-account-from-microsoft-windows-11/).

**Comment by sashaqwert** [comment] 2023-05-20 09:18
One `termsrv.dll` version = ONE opened issue.

**Comment by sashaqwert** [comment] 2023-05-20 09:18
Duplicate of https://github.com/stascorp/rdpwrap/issues/2006

**Closed as not planned by sashaqwert** 2023-05-20 09:18 UTC
Labels: duplicate
