### ISSUE TITLE
An unsupported version of Windows 10 Pro( for workstation) termsrv.dll, can you help?  10.0.19041.4474

### ISSUE THREAD

**Issue by Gitsmyth** [stascorp/rdpwrap#3299] opened 2024-10-11 09:01 UTC
I have bought from Dell a refurbished Dell Workstation that came with Windows 10 Pro for Workstation on the MB. 
termsrv.dll file reports version 10.0.19041.4474.
This is classed as unsupported.
Can you help?

Many Thanks
![Screenshot 2024-10-11 at 09 56 34](https://github.com/user-attachments/assets/723eae79-bac0-46ee-9fef-a24191ca5661)

**Comment by binarymaster** [comment] 2024-10-11 20:37
Duplicate of https://github.com/stascorp/rdpwrap/issues/2840.

**Closed as not planned by binarymaster** 2024-10-11 20:37 UTC
Labels: duplicate
