### ISSUE TITLE
There is a malware in RDPWrap-v1.6.2.zip or github (Avast blocked the download)

### ISSUE THREAD

**Issue by lboisvert** [stascorp/rdpwrap#381] opened 2017-12-30 23:34 UTC
There is a malware in RDPWrap-v1.6.2.zip  or github as per Avast and Avast blocks the download. Same thing for the msi version.
Chrome says that there is something dangerous in the RDPWrap-v1.6.1.zip version and stop the download.
RDPWrap-v1.6.zip is downloadable.

This is the message from Avast when downloading RDPWrap-v1.6.2.zip
![image](https://user-images.githubusercontent.com/34967178/34457939-b5568e82-ed8e-11e7-962f-14e5a5af3df5.png)

Thanks

**Comment by binarymaster** [comment] 2018-01-01 13:22
Duplicate of #277.

**Closed by binarymaster** 2018-01-01 13:22 UTC

**Comment by HAPPYSLAP5** [comment] 2019-09-25 10:33
why make software behave this way, it fails to install and the thing is not user-friendly in the slightest, will be uninstalling haven't got time for it.
