### ISSUE TITLE
ACCESS DENIED ON WINDOWS SERVER 2022

### ISSUE THREAD

**Issue by Mariojd1980** [stascorp/rdpwrap#3287] opened 2024-10-03 00:36 UTC
Good evening,
I have some problems with rdpwrap, the most important is that it gives me access denied, I can only log in with the administrator user but not with the rest of the users.
Now I also get not supported. Attached files.
Thank you very much for any help you can provide.
Regards
[Archivos.zip](https://github.com/user-attachments/files/17237717/Archivos.zip)

**Comment by binarymaster** [comment] 2024-10-03 07:37
Your screenshot in the zip archive shows `10.0.17763.4252 [not supported]`, so this is duplicate of #2167.

**Closed as not planned by binarymaster** 2024-10-03 07:37 UTC
Labels: duplicate
