### ISSUE TITLE
Win10 Home, v.1709, OS build 16299.64, termsrv.dll 10.0.16299.15 is NOT listening

### ISSUE THREAD

**Issue by radoslavv** [stascorp/rdpwrap#354] opened 2017-11-24 00:31 UTC
After OS updates done few days ago RDPwrap is not working.
Even termsrv.dll 10.0.16299.15 is supported (also found in rdpwrap.ini), it does not work.

RDPConf reports:
Wrapper state: Installed
ver. 1.5.0.0 (I have used rdpwrap v.1.6.1, but rdpwrap.dll reports v.1.5.0.0)
Service state: Running
ver. 10.0.16299.15
Listener state: **Not listening**
[fully supported]

Uninstallation and installation does not helped, no matter if there is reboot between uninstallation and install performed.

**Comment by justin522** [comment] 2017-11-24 05:30
I'm having the same issue all info the same except: ver. 10.0.15063.0

**Comment by binarymaster** [comment] 2017-11-24 06:21
You did not read `README` and existing issues. Duplicate of #194.

**Closed by binarymaster** 2017-11-24 06:21 UTC
