### ISSUE TITLE
rdp listener's state not supported vv 10.0.19041.1348

### ISSUE THREAD

**Issue by zavolo** [stascorp/rdpwrap#1649] opened 2021-12-06 16:41 UTC
Please help, Windows 10 Home
![image](https://user-images.githubusercontent.com/90477403/144885959-c66523f2-3ce6-4709-81fc-2fbbcde26617.png)
![image](https://user-images.githubusercontent.com/90477403/144886071-ad655b37-4d4e-4f4b-b590-7dd5113e2aad.png)

**Comment by sebaxakerhtc** [comment] 2021-12-06 21:42
Duplicate of https://github.com/stascorp/rdpwrap/issues/1595

**Closed as completed by sebaxakerhtc** 2021-12-06 21:42 UTC
