### ISSUE TITLE
RDPWrap not working in Windows 10

### ISSUE THREAD

**Issue by v-mwalk** [stascorp/rdpwrap#678] opened 2019-02-21 06:33 UTC
Installed Windows 10 and Installed RDPWrap.

RDPConf confirms installed OK and is listening.  However, Remoting results in the 'Another user is connected......' warning etc.

RDPWrap has been working fine on previous installations of Win 10 and this is the first time I've seen it.  Is this a new known issue?  If not, I'll provide full debugging details (IE. Builds logs etc...)

**Comment by leaartibai** [comment] 2019-02-21 09:12
Hello,
I suffered these problems after windows updates... (windows 7)
Try to copy C:\Windows\System32\termsrv.dll from a computer with the wrapper and without problems.

**Comment by binarymaster** [comment] 2019-02-21 11:25
Duplicate of the one of existing issues.

https://github.com/stascorp/rdpwrap/issues?q=is%3Aissue+is%3Aopen+label%3A%22add+build%22

**Closed as completed by binarymaster** 2019-02-21 11:25 UTC
Labels: duplicate
