### ISSUE TITLE
Problem for RDP Wrap

### ISSUE THREAD

**Issue by csmaria** [stascorp/rdpwrap#105] opened 2016-04-06 07:54 UTC
I send the error message and file dll.

![install](https://cloud.githubusercontent.com/assets/18302167/14309460/e5ac5602-fbdc-11e5-9cf3-7e72546ff574.png)
![problem](https://cloud.githubusercontent.com/assets/18302167/14309461/e5ae6942-fbdc-11e5-8870-e7e837d16235.png)

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/205959/termsrv.zip)

Please help for me!
Thank you!

**Comment by binarymaster** [comment] 2016-04-06 10:00
Duplicate of https://github.com/stascorp/rdpwrap/issues/87

**Closed by binarymaster** 2016-04-06 10:00 UTC
Labels: duplicate
