### ISSUE TITLE
installer fails from inaccessible dependency and detects as virus in windows defender

### ISSUE THREAD

**Issue by Turphin** [stascorp/rdpwrap#1229] opened 2020-12-06 06:26 UTC
![image](https://user-images.githubusercontent.com/45678161/101272780-48959b00-3744-11eb-91ec-b35666395469.png)

**Comment by sashaqwert** [comment] 2020-12-06 10:27
Do not use MSI installer.
Use ZIP.
More info in Telegram chat: https://t.me/rdpwrap/23875
https://t.me/rdpwrap/21724

**Comment by beatinger** [comment] 2021-01-31 21:47
The ZIP file won't even download, for the same reason (virus detected).

**Comment by sebaxakerhtc** [comment] 2022-06-20 11:59
Duplicate of https://github.com/stascorp/rdpwrap/issues/277

**Closed as completed by sebaxakerhtc** 2022-06-20 11:59 UTC
