### ISSUE TITLE
10.0.17763.5328 not supported,thanks

### ISSUE THREAD

**Issue by shengyuli** [stascorp/rdpwrap#2475] opened 2024-01-29 07:07 UTC
Windows 10 LTSC 10.0.17763.5328

**Comment by shengyuli** [comment] 2024-01-29 07:11
![Capture2](https://github.com/stascorp/rdpwrap/assets/13676633/0e0d4e32-a05a-43bb-9e4e-ec6746e6ee18)

**Comment by sashaqwert** [comment] 2024-01-29 09:08
Duplicate of https://github.com/stascorp/rdpwrap/issues/2463

**Closed as not planned by sashaqwert** 2024-01-29 09:08 UTC
Labels: duplicate
