### ISSUE TITLE
not working with 16299.15

### ISSUE THREAD

**Issue by sigma2017** [stascorp/rdpwrap#318] opened 2017-10-05 06:51 UTC
Is not working with Pro x64  build 16299.15:
[*] Installing...
[*] Terminal Services version: 10.0.16299.15
[-] This version of Terminal Services is not supported.

The termsrv.dll file is untouched, the original one.
https://i.imgur.com/zyZsYVD.jpg
RDP server is working just fine but I can not enable multiple sessions in order to log in with a different user account.

**Comment by binarymaster** [comment] 2017-10-05 10:08
Duplicate of #316.

**Closed by binarymaster** 2017-10-05 10:08 UTC
Labels: duplicate
