### ISSUE TITLE
Windows 11 22621.2314 not supported

### ISSUE THREAD

**Issue by light689** [stascorp/rdpwrap#2308] opened 2023-08-11 08:46 UTC
![Snipaste_2023-08-11_16-46-12](https://github.com/stascorp/rdpwrap/assets/107845122/ee2b3f3d-e12d-4b84-a595-7cd0b05b453f)

**Comment by sashaqwert** [comment] 2023-08-11 10:13
Duplicate of https://github.com/stascorp/rdpwrap/issues/2290

**Closed as not planned by sashaqwert** 2023-08-11 10:13 UTC
Labels: duplicate
