### ISSUE TITLE
10.0.19041.4474 Not Supported 

### ISSUE THREAD

**Issue by Howie2024** [stascorp/rdpwrap#3368] opened 2024-11-25 04:58 UTC
10.0.19041.4474 Not Supported 
![image](https://github.com/user-attachments/assets/a007a10b-18a7-4356-a8b6-089c3247d7a3)

**Comment by binarymaster** [comment] 2024-11-25 14:56
Duplicate of https://github.com/stascorp/rdpwrap/issues/2840.

**Closed as not planned by binarymaster** 2024-11-25 14:56 UTC
Labels: duplicate
