### ISSUE TITLE
10.0.19044.1645 not supported

### ISSUE THREAD

**Issue by Saibot420** [stascorp/rdpwrap#1810] opened 2022-04-14 09:53 UTC
[Termsrv.dll](https://drive.google.com/file/d/1Y9Gt58uiyWP1aFuPYppSFT7ZOE4Rzuwv/view?usp=sharing)

**Comment by sashaqwert** [comment] 2022-04-14 12:39
Duplicate of https://github.com/stascorp/rdpwrap/issues/1808

**Comment by sebaxakerhtc** [comment] 2022-04-15 07:16
> Duplicate of #1808

**Closed as completed by sebaxakerhtc** 2022-04-15 07:16 UTC
