### ISSUE TITLE
Windows 11 Pro 22H2 (22621.1105) doesn't work

### ISSUE THREAD

**Issue by gerpaick** [stascorp/rdpwrap#2093] opened 2023-01-20 18:36 UTC
Hi,
my windows just got upgraded from 10 to 11. I uninstalled RDP Wrapper and reinstalled it.
I have info that my terminal services are not supported
![image](https://user-images.githubusercontent.com/1191005/213778728-6cbc0279-6e34-4664-b325-3c1b3bd3bbe0.png)

but then when I run RDP_CnC I get info that everything is fine.
![image](https://user-images.githubusercontent.com/1191005/213779186-be0ef615-a5a3-411d-a418-3d618d33b997.png)

However, I can only open one RDP session at the moment.

**Comment by sashaqwert** [comment] 2023-01-20 18:59
Try:
1. Download RDP Wrapper 1.6.2 and extract this to any directory.
2. Place `rdpwrap.ini` in the same directory.
3. Open CMD as administrator
4. Execute this commands
```
cd C:\path\to\directory\
rdpwinst -u -k
rdpwinst -i
```
5. Enjoy!

Original message: https://t.me/rdpwrap/49131

**Comment by sashaqwert** [comment] 2023-01-20 19:01
One termsrv.dll version = one opened issue.
This issue will closed as duplicate of first with this version.

**Comment by sashaqwert** [comment] 2023-01-20 19:01
Duplicate of https://github.com/stascorp/rdpwrap/issues/2006

**Closed as not planned by sashaqwert** 2023-01-20 19:01 UTC
Labels: duplicate
