### ISSUE TITLE
listener state not supported ver. 10.0.19041.1682

### ISSUE THREAD

**Issue by axiao907291973** [stascorp/rdpwrap#1863] opened 2022-05-20 09:53 UTC

**Comment by sebaxakerhtc** [comment] 2022-05-20 10:04
Duplicate of https://github.com/stascorp/rdpwrap/issues/1823

**Comment by axiao907291973** [comment] 2022-05-20 10:04
感谢您的来信，我会认真处理。谢谢！

**Closed as completed by sebaxakerhtc** 2022-05-20 10:04 UTC
