### ISSUE TITLE
Add support for build 10.0.17763.316

### ISSUE THREAD

**Issue by CONTIGIANLUCA** [stascorp/rdpwrap#662] opened 2019-02-13 11:08 UTC
Hi, with last update on Win10 (10.0.17763.316), RDP not work.
Somebody have the solution or new INI file ?
sorry for my language....

**Comment by binarymaster** [comment] 2019-02-13 11:37
RDPConf screenshot please.

**Comment by korolartemnexus** [comment] 2019-02-13 11:41
![default](https://user-images.githubusercontent.com/7373512/52709284-06123580-2f95-11e9-8933-ef77e7477c1e.png)

**Comment by vaa94** [comment] 2019-02-13 11:57
Same problem. 
Found the old one termserv.dll, correct rdpwrapper.ini and restart TermService.
[rdp.zip](https://github.com/stascorp/rdpwrap/files/2860210/rdp.zip)

**Comment by binarymaster** [comment] 2019-02-13 12:00
Duplicate of #645.

**Closed as completed by binarymaster** 2019-02-13 12:00 UTC
Labels: duplicate

**Comment by lampra1** [comment] 2019-02-15 23:36
In my case, I get error 1056 when restarting.
```
RDPWInst.exe -r
RDP Wrapper Library v1.6.2
Installer v2.5
Copyright (C) Stas'M Corp. 2017

[*] Restarting...
[+] TermService found (pid 8992).
[*] No shared services found.
[*] Terminating service...
[*] Starting TermService...
[-] StartService error (code 1056).
[+] Done.
````
I updated the .ini for 292 but Listener is not listening and seems unsupported.
Any chance to update?
![screenshot from 2019-02-16 01-20-32](https://user-images.githubusercontent.com/31213906/52890007-3a4f4700-318b-11e9-93ce-28831d7e385b.png)
![screenshot from 2019-02-16 01-21-41](https://user-images.githubusercontent.com/31213906/52890012-3fac9180-318b-11e9-8b1f-aba4a449cf89.png)

**Comment by Deba1981** [comment] 2019-02-23 14:07
Sorry can't find qay to solve the "not supportet" problem with the .316 Update in the posts above.

What can we do to supporter status?
Changing the  .ini from .182 (old) to .316 (new) doesn't work

**Comment by binarymaster** [comment] 2019-02-23 14:29
Use Telegram chat for user support, see README.

**Comment by Deba1981** [comment] 2019-02-23 14:31
Is there no solution to post?
Which Readme?
