### ISSUE TITLE
10.0.22621.2070 rdp wrapper not working

### ISSUE THREAD

**Issue by leb0wnski** [stascorp/rdpwrap#2293] opened 2023-07-27 10:12 UTC
![image](https://github.com/stascorp/rdpwrap/assets/140707879/66173869-0608-4d25-bb09-b7e5d0cf7bb5)

**Comment by binarymaster** [comment] 2023-07-27 12:08
Duplicate of #2290.

**Closed as not planned by binarymaster** 2023-07-27 12:08 UTC
Labels: duplicate
