### ISSUE TITLE
10.0.22000.856 [Not supported]

### ISSUE THREAD

**Issue by IsArsh** [stascorp/rdpwrap#1957] opened 2022-08-12 17:06 UTC

**Comment by sashaqwert** [comment] 2022-08-12 18:08
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by sebaxakerhtc** [comment] 2022-08-17 09:56
> RDPConf screenshot

termsrv.dll version 22000.708
Looks like a duplicate of https://github.com/stascorp/rdpwrap/issues/1868

**Comment by sashaqwert** [comment] 2022-08-17 10:57
> termsrv.dll version 22000.708
Looks like a duplicate of https://github.com/stascorp/rdpwrap/issues/1868

**Closed as not planned by sashaqwert** 2022-08-17 10:57 UTC
Labels: duplicate
