### ISSUE TITLE
need suport windows 11 22621.1485 

### ISSUE THREAD

**Issue by davidvieira13** [stascorp/rdpwrap#2209] opened 2023-05-20 03:04 UTC
I'm trying to install and the error appears - openkeyreadonly error (code 0)

I'm running as administrator

**Comment by sashaqwert** [comment] 2023-05-20 09:20
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by sashaqwert** [comment] 2023-05-21 18:12
Closed as no actibity

**Closed as not planned by sashaqwert** 2023-05-21 18:12 UTC

**Comment by davidvieira13** [comment] 2023-05-21 18:19
I will send, I'm not near the pc that is windows

**Comment by sashaqwert** [comment] 2023-05-22 05:28
> I will send, I'm not near the pc that is windows

OK. Without this information (version of `termsrv.dll`), the issue is invalid....
