### ISSUE TITLE
Windows 11 10.0.22621.2428 not Supported

### ISSUE THREAD

**Issue by citongshuo** [stascorp/rdpwrap#2366] opened 2023-10-12 06:39 UTC
![mmexport1697092562754.jpg](https://github.com/stascorp/rdpwrap/assets/119740445/7eee22bf-732d-4ad1-a73b-dfc75d84b320)

![mmexport1697092564186.jpg](https://github.com/stascorp/rdpwrap/assets/119740445/725d6d3d-e225-4ad9-9512-119f5c0b35c7)

**Comment by sashaqwert** [comment] 2023-10-12 08:34
Duplicate of https://github.com/stascorp/rdpwrap/issues/2345

**Closed as not planned by sashaqwert** 2023-10-12 08:34 UTC
Labels: duplicate
