### ISSUE TITLE
RDP Wrapper not working windows 11 

### ISSUE THREAD

**Issue by Trestin16** [stascorp/rdpwrap#2052] opened 2022-11-25 17:13 UTC
Hello all curently cant get the program rdp wrapper to work. I gotten everything to go green on check but it says access denied upon login. I have tried to make other guest accounts but it wont show. I need to edit the file with a hex editor but cant seem to find my version to change it.

**Comment by sashaqwert** [comment] 2022-11-26 06:33
> I need to edit the file with a hex editor but cant seem to find my version to change it.

`termsrv.dll` patching is not compatible with RDP Wrapper.

If you need support with RDP Wrapper:
Please, attach your RDPConf screenshot and `termsrv.dll`.

> but it says access denied

Please, add your RDP users to Administrators or «Remote Desktop users» group.

**Comment by Trestin16** [comment] 2022-11-26 06:56
![image_2022-11-26_015601406](https://user-images.githubusercontent.com/79481768/204076452-62e8b860-f56c-4ee4-a49c-ff8a1884b703.png)
im getting this error atm

**Comment by Trestin16** [comment] 2022-11-26 08:30
![image_2022-11-26_032953449](https://user-images.githubusercontent.com/79481768/204079812-7ff4079d-7756-4a4d-8181-9ea2fad56ac9.png)
This is all i see can see other users

**Comment by sashaqwert** [comment] 2022-11-26 09:55
> This is all i see can see other users

Try enter your RDP username and password, then press ENTER.

**Comment by Trestin16** [comment] 2022-11-26 09:59
![image_2022-11-26_045910100](https://user-images.githubusercontent.com/79481768/204083012-ce4974e5-08d4-4d81-8cb0-f15acabbbeac.png)

**Comment by Trestin16** [comment] 2022-11-26 10:01
![image_2022-11-26_050030619](https://user-images.githubusercontent.com/79481768/204083070-f16c4db9-3800-42fd-9ec1-a71c523214af.png)
![image_2022-11-26_050101126](https://user-images.githubusercontent.com/79481768/204083081-a53ee035-fa91-4937-91ae-7c7eaf952bd0.png)

**Comment by sashaqwert** [comment] 2022-11-26 10:06
You need to update the `rdpwrap.ini`.
More info in original issue (next comment)

**Comment by sashaqwert** [comment] 2022-11-26 10:06
Duplicate of https://github.com/stascorp/rdpwrap/issues/2006

**Closed as not planned by sashaqwert** 2022-11-26 10:06 UTC
Labels: duplicate
