### ISSUE TITLE
Win10 Compilation 101903 18362.418

### ISSUE THREAD

**Issue by jorgego19** [stascorp/rdpwrap#920] opened 2019-10-31 16:55 UTC
Good afternoon, someone has been able to use RDP.Wrapper.Library with this compilation of Windows 10 Pro. Thank you very much.

**Comment by SobieskiCodes** [comment] 2019-10-31 18:08
you mean like https://github.com/stascorp/rdpwrap/issues/906?

**Comment by lgzcoollg** [comment] 2019-11-05 02:34
Use the file below:

[https://github.com/stascorp/rdpwrap/issues/902#issuecomment-541559295](url)

**Comment by WVVxm** [comment] 2019-11-13 01:41
> Good afternoon, someone has been able to use RDP.Wrapper.Library with this compilation of Windows 10 Pro. Thank you very much.

Please check pull requests, there's some good guys updating rdpwrap.ini.

**Comment by sebaxakerhtc** [comment] 2022-06-20 10:16
Duplicate of https://github.com/stascorp/rdpwrap/issues/871

**Closed as completed by sebaxakerhtc** 2022-06-20 10:16 UTC
