### ISSUE TITLE
RDP 10.0.19041.4474 Windows 10 LTSC - "Not Supported" after updating the ini

### ISSUE THREAD

**Issue by ck0099** [stascorp/rdpwrap#3239] opened 2024-07-26 04:37 UTC
After executing the install.bad with Administration, and I have also updated the INI file according to this:

[Steps]
https://www.avica.link/blog/multiple-rdp-sessions-on-windows/#h3_3

[Ini]
https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini

I still cannot get it to work:

<img width="397" alt="Screen Shot 2024-07-26 at 12 35 53 PM" src="https://github.com/user-attachments/assets/856cabcc-0a6b-4186-8780-6f0273599f89">

**Comment by loyejaotdiqr47123** [comment] 2024-07-26 06:36
> After executing the install.bad with Administration, and I have also updated the INI file according to this:
> 
> [Steps] https://www.avica.link/blog/multiple-rdp-sessions-on-windows/#h3_3
> 
> [Ini] https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini
> 
> I still cannot get it to work:
> 
> <img alt="Screen Shot 2024-07-26 at 12 35 53 PM" width="397" src="https://private-user-images.githubusercontent.com/132270603/352367834-856cabcc-0a6b-4186-8780-6f0273599f89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NzYwNDgsIm5iZiI6MTcyMTk3NTc0OCwicGF0aCI6Ii8xMzIyNzA2MDMvMzUyMzY3ODM0LTg1NmNhYmNjLTBhNmItNDE4Ni04NzgwLTZmMDI3MzU5OWY4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQwNjM1NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTk4ZGYyMmY0ZjIzZDE5ZDExYWE1N2NiYjQwOGYyYjRhNjY0YjI3MzVlNjBiOTRkNjE2NDdiNTI4YTI5YmY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qWHoTWfgem6kvAxAtVjwcYo-M1M3Em0eEKlvorQ7Q5E">

Duplicate of #2840

**Comment by binarymaster** [comment] 2024-07-26 06:57
> I still cannot get it to work

Contact Telegram support group instead. Marked as duplicate.

**Closed as not planned by binarymaster** 2024-07-26 06:57 UTC
Labels: duplicate

**Comment by lbwanghr** [comment] 2024-11-12 01:38
Please visit this [page](https://github.com/stascorp/rdpwrap/issues/2840) for help.

Specifically, add the following text to the rdpwrap.ini
```
[10.0.19041.4474]
LocalOnlyPatch.x86=1
LocalOnlyOffset.x86=C4889
LocalOnlyCode.x86=jmpshort
SingleUserPatch.x86=1
SingleUserOffset.x86=45E85
SingleUserCode.x86=Zero
DefPolicyPatch.x86=1
DefPolicyOffset.x86=41E39
DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
SLInitHook.x86=1
SLInitOffset.x86=72C88
SLInitFunc.x86=New_CSLQuery_Initialize
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=93EB1
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=1846B
SingleUserCode.x64=mov_eax_1_nop_2
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1F455
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=2AE5C
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.19041.4474-SLInit]
bInitialized.x86= E5990
bServerSku.x86= E5994
lMaxUserSessions.x86= E5998
bAppServerAllowed.x86= E59A0
bRemoteConnAllowed.x86=E59A8
bMultimonAllowed.x86= E59AC
ulMaxDebugSessions.x86=E59B0
bFUSEnabled.x86= E59B4
bInitialized.x64= 1270A4
bServerSku.x64= 1270A8
lMaxUserSessions.x64= 1270AC
bAppServerAllowed.x64= 1270B4
bRemoteConnAllowed.x64=1270BC
bMultimonAllowed.x64= 1270C0
ulMaxDebugSessions.x64=1270C4
bFUSEnabled.x64= 1270C8
```

Then you should run uninstall.exe and install it again.

---
Now you could open RDPConf.exe and check the result.
