### ISSUE TITLE
Windows 11 PRO - Version 23H2 ( OS Build 22631.3085 ) not supported

### ISSUE THREAD

**Issue by dayspring-dev** [stascorp/rdpwrap#2470] opened 2024-01-24 19:53 UTC
![2024_01_24_13_49_42_About_Windows](https://github.com/stascorp/rdpwrap/assets/26641244/d5e853eb-e615-4086-b50b-de3b04a888fc)
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/14043004/termsrv.zip)

**Comment by sashaqwert** [comment] 2024-01-25 07:54
Please, rename your issue to `10.0.22621.3085`

<details>
<summary>From your termsrv.dll</summary>

![изображение](https://github.com/stascorp/rdpwrap/assets/24974508/10440285-0ecd-45c8-9822-961bae4fcfcd)

</details>

**Comment by sashaqwert** [comment] 2024-01-25 08:02
Duplicate of https://github.com/stascorp/rdpwrap/issues/2469

**Comment by sashaqwert** [comment] 2024-01-25 08:02
Because title is incorrect

**Closed as not planned by sashaqwert** 2024-01-25 08:02 UTC
