### ISSUE TITLE
Microsoft Windows [Version 10.0.19044.1415]

### ISSUE THREAD

**Issue by atenttai** [stascorp/rdpwrap#1672] opened 2021-12-22 20:00 UTC
Try for first time RDPwrap but seem is not working anymore. Is this project active or is been discontinued ?
Thanks

**Comment by sebaxakerhtc** [comment] 2021-12-23 08:35
Duplicate of https://github.com/stascorp/rdpwrap/issues/1630

**Closed as completed by sebaxakerhtc** 2021-12-23 08:35 UTC
