### ISSUE TITLE
Service not supported Win10 Ent

### ISSUE THREAD

**Issue by saesaeru** [stascorp/rdpwrap#518] opened 2018-07-02 10:58 UTC
![win10-bug](https://user-images.githubusercontent.com/7147646/42160466-fada3d9e-7dff-11e8-969e-dc5ebbeace23.jpg)

**Comment by binarymaster** [comment] 2018-07-02 11:00
Duplicate of #506.

**Closed by binarymaster** 2018-07-02 11:00 UTC
