### ISSUE TITLE
Listener: Not running : Windows 10 64-bit version 10.0.19041.1387

### ISSUE THREAD

**Issue by alexyuriev** [stascorp/rdpwrap#1666] opened 2021-12-18 16:55 UTC
This is a new one

Windows 10 has been updated to 1387
RDPWrap.ini has been updated to include 1387 config

Reboot.

Wrapper state: Installed
Service state: running
Listener state: not listening [fully supported]

Already tried re-installing. Same result.

Any thoughts/ideas?

**Comment by zekecarter** [comment] 2021-12-19 00:25
> This is a new one
> 
> Windows 10 has been updated to 1387 RDPWrap.ini has been updated to include 1387 config
> 
> Reboot.
> 
> Wrapper state: Installed Service state: running Listener state: not listening [fully supported]
> 
> Already tried re-installing. Same result.
> 
> Any thoughts/ideas?

Do not worry, there is already the solution to your problems, you just need to update your version of rdpwrapper for the version of sebaxakerhtc, and includes all updates from windows 7 to windows 11.

You can download the new version from this link:
[**RDPWrapper 1.8.6.1**](https://github.com/sebaxakerhtc/rdpwrap/releases/download/v1.8.6.1/RDPW_installer-Black.exe)

Let us know how it went with the new version greetings

**Comment by sashaqwert** [comment] 2021-12-19 08:27
Duplicate of https://github.com/stascorp/rdpwrap/issues/1630

1 termsrv version = 1 issue. This issue will closed in a few days...

**Closed as completed** 2021-12-19 11:39 UTC

**Comment by alexyuriev** [comment] 2021-12-19 15:13
Windows Defender identifies the new https://github.com/sebaxakerhtc/rdpwrap/releases/download/v1.8.6.1/RDPW_installer-Black.exe as a Trojan

**Comment by sebaxakerhtc** [comment] 2021-12-19 15:40
> Windows Defender identifies the new https://github.com/sebaxakerhtc/rdpwrap/releases/download/v1.8.6.1/RDPW_installer-Black.exe as a Trojan

Yes. It's normal behavior
When you don't trust - build it by yourself and you'll get your own Trojan 😉

**Comment by zekecarter** [comment] 2021-12-19 15:51
> Windows Defender identifies the new https://github.com/sebaxakerhtc/rdpwrap/releases/download/v1.8.6.1/RDPW_installer-Black.exe as a Trojan

Microsoft will go to great lengths to say that rdpwrapper is a virus because it affects their revenue monetarily, which is why they mark it as a virus but it is not.

Just temporarily disable the antivirus for installation and add it to the antivirus exceptions.

The rdpwrapper is the best program ever created greetings to the creators.
