### ISSUE TITLE
10.0.14393.4169 Not Supported

### ISSUE THREAD

**Issue by Th0rules** [stascorp/rdpwrap#1914] opened 2022-06-23 16:22 UTC
Its fine but no works ! ! 
![rdpwar](https://user-images.githubusercontent.com/38351478/175347566-71886aad-4470-4d25-b4d4-b012207e3100.png)
!

**Comment by sashaqwert** [comment] 2022-06-23 17:03
Duplicate of https://github.com/stascorp/rdpwrap/issues/1511

**Comment by sebaxakerhtc** [comment] 2022-06-23 17:09
Duplicate of https://github.com/stascorp/rdpwrap/issues/1511

**Closed as completed by sebaxakerhtc** 2022-06-23 17:09 UTC
