### ISSUE TITLE
Does not work on windows 10 pro

### ISSUE THREAD

**Issue by operations999** [stascorp/rdpwrap#1074] opened 2020-05-02 09:35 UTC
Hello,
I installed it on windows 10 pro but it does not work. 
Users are allowed RDP access but we are using custom RDP port.
Anyone can guide me how to fix?

**Comment by robbak** [comment] 2020-05-02 09:48
How did you install it, what rdpwrap.ini file are you using, where are you putting it, what error are you getting? "Does not work" is never a useful problem report.

All the version numbers and the status messages that are shown by RDPConf.exe would be useful. 

By 'custom RDP port' do you mean that you have used a tweak to change which UDP port RDP is using? I don't know whether that will be causing issues.

**Comment by operations999** [comment] 2020-05-02 09:53
I followed https://www.youtube.com/watch?v=fi87Xe78YNY
downloaded the zip.. and almost followed same and here is the output https://prnt.sc/s9lvs3

**Comment by robbak** [comment] 2020-05-02 09:56
OK. You haven't got an up-to-date .ini file. That version of termsrv.dll is well supported.

This one is the .ini file most of us are recommending - https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini

Stop the service, Replace the rdpwrap.ini file in Program Files/RDPWrapper with that one, and restart the service. It should then be working.

**Comment by operations999** [comment] 2020-05-02 11:02
OK i copied restarted services, even rebooted machine but when I try to login from second user to RDP it logs out first.

**Comment by robbak** [comment] 2020-05-02 11:04
What does rdpconf.exe tell you

**Comment by operations999** [comment] 2020-05-02 11:22
https://prnt.sc/s9mrxj
and rdpchecker gives this after I login as user 
https://prnt.sc/s9msbm

**Comment by robbak** [comment] 2020-05-02 11:35
'Not supported' means that you haven't got the rdpwrap.ini installed correctly - because that version is supported by the .ini file above.

Do open the rdpwrap.ini you have in notepad, and search for that version number (10.0.18362.657) to make sure you are using the right .ini file. 

Where are you putting your .ini files? Where are the rdpwrap binaries? Skimming through the transcript on that video you linked, there doesn't seem to be any instructions in there.

**Comment by operations999** [comment] 2020-05-02 11:53
Hello,
Downloaded latest version from https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini and stored inside the folder on desktop. when I opened the ini 10.0.18362.657 and i see there it is.
I tried to update/install still same issue.

**Comment by robbak** [comment] 2020-05-02 11:56
A folder on the desktop doesn't seem right. Have you copied all the downlaoded files to program files/RDPWrapper , including the updated .ini file, and run the install program from there? If not, do it again and post the output of the instal command here. Because the screenshot you posted tells us that rdpwrapper is still using an old .ini file.

**Comment by operations999** [comment] 2020-05-02 13:50
Thank you :) It worked :)
Once again thank you for your time and support.

**Comment by sebaxakerhtc** [comment] 2022-06-20 10:35
Duplicate of https://github.com/stascorp/rdpwrap/issues/983

**Closed as completed by sebaxakerhtc** 2022-06-20 10:35 UTC
