### ISSUE TITLE
rdp in windows 10 home is not enabled , why?

### ISSUE THREAD

**Issue by mohammed-sec2010** [stascorp/rdpwrap#1917] opened 2022-06-26 12:28 UTC
Hi 
I attached my termsrv 

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/8986582/termsrv.zip)

**Comment by sashaqwert** [comment] 2022-06-26 15:19
Duplicate of https://github.com/stascorp/rdpwrap/issues/1823

**Comment by sebaxakerhtc** [comment] 2022-06-27 07:07
Duplicate of https://github.com/stascorp/rdpwrap/issues/1823

**Closed as completed by sebaxakerhtc** 2022-06-27 07:07 UTC
