### ISSUE TITLE
Need RDPWrap ini configuration for Windows 10 ver 10.0.19041.3570

### ISSUE THREAD

**Issue by patelpulin** [stascorp/rdpwrap#2361] opened 2023-10-11 04:55 UTC
![image](https://github.com/stascorp/rdpwrap/assets/147581077/4f562d05-16d3-4e06-b357-350f20bbcd48)

**Comment by hnagasawa** [comment] 2023-10-11 05:59
I occure same issue after Windows update 11-Oct-2023(JST).

**Comment by Flomic24rus** [comment] 2023-10-11 06:12
https://github.com/stascorp/rdpwrap/issues/2362

**Comment by sashaqwert** [comment] 2023-10-11 06:15
Duplicate of https://github.com/stascorp/rdpwrap/issues/2359

**Closed as not planned by sashaqwert** 2023-10-11 06:15 UTC
Labels: duplicate

**Comment by Voltars** [comment] 2023-10-11 06:18
[10.0.19041.3570]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=92AF1
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=11E12
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=1F315
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=2866C
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.19041.3570-SLInit]
bInitialized.x64 =125074
bServerSku.x64 =125078
lMaxUserSessions.x64 =12507C
bAppServerAllowed.x64 =125084
bRemoteConnAllowed.x64=12508C
bMultimonAllowed.x64 =125090
ulMaxDebugSessions.x64=125094
bFUSEnabled.x64 =125 098

**Comment by alanscordoba** [comment] 2023-10-11 11:49
> [10.0.19041.3570] LocalOnlyPatch.x64=1 LocalOnlyOffset.x64=92AF1 LocalOnlyCode.x64=jmpshort SingleUserPatch.x64=1 SingleUserOffset.x64=11E12 SingleUserCode.x64=Zero DefPolicyPatch.x64=1 DefPolicyOffset.x64=1F315 DefPolicyCode.x64=CDefPolicy_Query_eax_rcx SLInitHook.x64=1 SLInitOffset.x64=2866C SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.19041.3570-SLInit] bInitialized.x64 =125074 bServerSku.x64 =125078 lMaxUserSessions.x64 =12507C bAppServerAllowed.x64 =125084 bRemoteConnAllowed.x64=12508C bMultimonAllowed.x64 =125090 ulMaxDebugSessions.x64=125094 bFUSEnabled.x64 =125 098

Perfect, it worked for me, thank you very much.

**Comment by Sianmung** [comment] 2023-10-12 04:55
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/12877224/rdpwrap.zip)

**Comment by Nuts-sugar** [comment] 2023-10-15 09:23
> [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/12877224/rdpwrap.zip)

it still not works for me [wuwuwu]

**Comment by Sianmung** [comment] 2023-10-16 16:24
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/12919287/rdpwrap.zip)
