### ISSUE TITLE
Workaround for #646 (Windows 7 build 6.1.7601.24326)

### ISSUE THREAD

**Issue by MartijnBraam** [stascorp/rdpwrap#670] opened 2019-02-15 10:08 UTC
Since #646 is locked

The workaround for making rdpwrap work is removing KB4486563

**Comment by s0nic9** [comment] 2019-02-15 11:14
Confirmed last official February 2019 cumulative patch for Windows 7 ( KB4486563 ) is not yet supported.

**Comment by m-hume** [comment] 2019-02-15 12:21
Think i've got the offsets for x64
Not really got a machine i can test on till the weekend thou
```
[6.1.7601.24326]
SingleUserPatch.x64=1
SingleUserOffset.x64=17F1E
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=17CEE
DefPolicyCode.x64=CDefPolicy_Query_eax_rdi
```
Disclaimer: I'm new to disassembly so don't hate to much if i've got this wrong ;)

**Comment by m-hume** [comment] 2019-02-15 12:28
Just noticed the link in this post https://github.com/stascorp/rdpwrap/issues/668#issue-410538268
@fre4kyC0de got the same offsets that i found so they should be good

**Comment by s0nic9** [comment] 2019-02-15 13:23
Works but no concurrent remote resktop allowed, tested on home premium and pro version, uninstalling udpdate, concurrent works again.

**Comment by m-hume** [comment] 2019-02-15 13:52
Strange it works on my local machine 
![image](https://user-images.githubusercontent.com/3430210/52860693-160e4e80-3128-11e9-8822-9eb77d2b7f72.png)

here's my ini file. I did need a reboot after editing for it to take hold thou
[rdpwrap.ini.txt](https://github.com/stascorp/rdpwrap/files/2869453/rdpwrap.ini.txt)

**Comment by ZeljkoManjkas** [comment] 2019-02-15 14:25
As s0nic9 say. On my test machine after change rdprwap.ini and restart terminal server on Win 7 6.1.7601.24356, RDP Wrapper conf. say full supported but no more than 2 users are allowed (console + one RDP user)





►    





  ►   

















  
s0nic9

**Comment by binarymaster** [comment] 2019-02-15 16:11
Duplicate of #646.

> Since #646 is locked

If some issue is locked I don't want to receive email notifications on the subject. Don't create duplicates of locked issues if you don't want to be banned.

**Closed as completed by binarymaster** 2019-02-15 16:11 UTC
Labels: duplicate

**Comment by MartijnBraam** [comment] 2019-02-15 19:50
I'm sorry for creating the duplicate, but that issue has been locked for two weeks while from the comment above it seems like there are people willing to work on fixing the issue.  So maybe it's better to unsubscribe for notifications on a thread if you don't want to get them instead of blocking communication for everyone.

(Also thanks for this project, saved me many times. I won't create a duplicate again)

**Comment by binarymaster** [comment] 2019-02-15 19:57
Ok, I temporary unlocked it.

**Comment by tanwars83** [comment] 2019-03-05 10:02
> Strange it works on my local machine
> ![image](https://user-images.githubusercontent.com/3430210/52860693-160e4e80-3128-11e9-8822-9eb77d2b7f72.png)
> 
> here's my ini file. I did need a reboot after editing for it to take hold thou
> [rdpwrap.ini.txt](https://github.com/stascorp/rdpwrap/files/2869453/rdpwrap.ini.txt)

Thank you!
