### ISSUE TITLE
Need support for version 10.0.17763.5830, please

### ISSUE THREAD

**Issue by kmelox** [stascorp/rdpwrap#3246] opened 2024-07-31 15:49 UTC
New update for win serv 19 was released that updated termsrv.dll
[termsrv.zip](https://github.com/user-attachments/files/16444276/termsrv.zip)

**Comment by binarymaster** [comment] 2024-07-31 17:39
Duplicate of https://github.com/stascorp/rdpwrap/issues/2622.

**Closed as not planned by binarymaster** 2024-07-31 17:39 UTC
Labels: duplicate
