### ISSUE TITLE
Version 19043.2006 fully suppote but not working

### ISSUE THREAD

**Issue by LucasFelipeMacedo** [stascorp/rdpwrap#1991] opened 2022-09-19 14:41 UTC
Hello!
After montly windows update, RDP wrapper stopped working (not supported message). As usualy, I updated ini file, after that - Fully supported, But multiply connetion does not works.

Follow the Ini file.

![image](https://user-images.githubusercontent.com/24925424/191042137-485d0991-5c87-4394-941b-d3a03c57f958.png)

![image](https://user-images.githubusercontent.com/24925424/191042076-5845d517-1117-4e1c-962f-2c8024b3be64.png)

![image](https://user-images.githubusercontent.com/24925424/191041848-87b1d9ed-98fd-4a4f-8b0a-d4f1c5281699.png)
[rdpwrap.txt](https://github.com/stascorp/rdpwrap/files/9599934/rdpwrap.txt)

**Comment by sashaqwert** [comment] 2022-09-19 16:32
Duplicate of https://github.com/stascorp/rdpwrap/issues/1968

**Closed as not planned by sashaqwert** 2022-09-19 16:32 UTC

**Comment by sashaqwert** [comment] 2022-09-19 16:33
Reason: one `termsrv.dll` version = one openned issue.

**Comment by sashaqwert** [comment] 2022-09-19 16:35
> Fully supported, But multiply connetion does not works.

Try restart service or reboot.

```
net stop termService
net start termService
```
