### ISSUE TITLE
RDP 10.0.22621.3958

### ISSUE THREAD

**Issue by bla1zy** [stascorp/rdpwrap#3244] opened 2024-07-30 18:17 UTC
help me please
![image](https://github.com/user-attachments/assets/08d4112c-cf40-4611-8709-17e223bddb8e)

**Comment by binarymaster** [comment] 2024-07-30 19:09
Duplicate of https://github.com/stascorp/rdpwrap/issues/3238.

You have "fully supported", contact Telegram chat for support instead.

**Closed as not planned by binarymaster** 2024-07-30 19:09 UTC
Labels: duplicate
