### ISSUE TITLE
[Supported Partially] in Windows 7

### ISSUE THREAD

**Issue by elpaco2000** [stascorp/rdpwrap#686] opened 2019-02-27 12:54 UTC
Hi
Install Rdp wrapper 1.6.2 in win 7 Professional
![image](https://user-images.githubusercontent.com/46573209/53490777-51d3dd00-3a73-11e9-966b-ea82057692ce.png)
 think the problem is in update security
if uninstall this updates work!
![image](https://user-images.githubusercontent.com/46573209/53490988-ec342080-3a73-11e9-9b8d-1a67a9b0051b.png)
it may work without uninstalling the update

**Comment by binarymaster** [comment] 2019-02-27 14:08
Duplicate of #646.

**Closed as completed by binarymaster** 2019-02-27 14:08 UTC
Labels: duplicate
