### ISSUE TITLE
Not supported on 10.0.19043.1586

### ISSUE THREAD

**Issue by Alien-ru323** [stascorp/rdpwrap#1767] opened 2022-03-12 12:32 UTC
On Windows 10 21H1 OS assembly 19043.1586

**Comment by sashaqwert** [comment] 2022-03-13 11:26
RDPConf screenshot, please!
You specified the Windows version instead of the version of `termsrv.dll`.  It can be found in RDPConf.

**Comment by Alien-ru323** [comment] 2022-03-13 13:57
![image](https://user-images.githubusercontent.com/101459854/158062960-71f2e003-b06f-48c7-a0d9-cbe4e40c3e9d.png)

**Comment by sashaqwert** [comment] 2022-03-13 17:17
Duplicate of https://github.com/stascorp/rdpwrap/issues/1725

**Closed as completed** 2022-03-14 08:09 UTC

**Comment by Alien-ru323** [comment] 2022-03-14 16:21
Thanks!
