### ISSUE TITLE
10.0.19041.3636 @ Win10 Home x86 22H2 19045.3803

### ISSUE THREAD

**Issue by Ayubahar1** [stascorp/rdpwrap#2462] opened 2024-01-07 17:59 UTC
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/13854416/termsrv.zip)

Listening state: Not listening

**Comment by sashaqwert** [comment] 2024-01-08 08:30
Duplicate of https://github.com/stascorp/rdpwrap/issues/2390

**Closed by sashaqwert** 2024-01-08 08:30 UTC
