### ISSUE TITLE
issues on Win 10 version 1909(OS Build 18363.778)

### ISSUE THREAD

**Issue by ankitT20** [stascorp/rdpwrap#1080] opened 2020-05-07 13:47 UTC
So, rdpwrap worked perfect until 3 days ago,until clean installed Windows 10 Pro,
I downloaded and installed latest version of Win10 on 3may.
![image](https://user-images.githubusercontent.com/58112602/81300460-55122200-9095-11ea-9d7e-00112b843647.png)
So , this error listener state: listening [not supported] , was also previous time
![image](https://user-images.githubusercontent.com/58112602/81300689-96a2cd00-9095-11ea-86c7-4c16d3e3b601.png)
I followed https://github.com/stascorp/rdpwrap/pull/1039/files
and the config changes to 
![image](https://user-images.githubusercontent.com/58112602/81301113-42e4b380-9096-11ea-8ca0-76f19800e64b.png)
I did remote desktop to 127.0.0.2
![image](https://user-images.githubusercontent.com/58112602/81301291-7de6e700-9096-11ea-9e82-82e2ababde8c.png)
I followed https://troubleshooter.xyz/wiki/fix-the-number-of-connections-to-this-computer-is-limited/
and my registry 
![image](https://user-images.githubusercontent.com/58112602/81301637-f057c700-9096-11ea-8aa7-9351694bef0e.png),restarted laptop
But the same error continues , i also read many posts before posting new one

**Comment by ankitT20** [comment] 2020-05-07 14:18
after reboot
![image](https://user-images.githubusercontent.com/58112602/81305027-78d86680-909b-11ea-9845-4f8e48691285.png)
I also found that TermService was missing 
![image](https://user-images.githubusercontent.com/58112602/81305196-ad4c2280-909b-11ea-97fc-74de331a8fdb.png)
But, 
![image](https://user-images.githubusercontent.com/58112602/81307532-66abf780-909e-11ea-9ad2-8ea320486332.png)

**Comment by sebaxakerhtc** [comment] 2022-04-27 16:11
Duplicate of https://github.com/stascorp/rdpwrap/issues/1059

**Closed as completed by sebaxakerhtc** 2022-04-27 16:11 UTC
