### ISSUE TITLE
10.0.19044.2006 [not supported]

### ISSUE THREAD

**Issue by lengyhua** [stascorp/rdpwrap#1982] opened 2022-09-15 02:55 UTC
版本	Windows 10 专业工作站版
版本号	21H2
安装日期	‎2022/‎6/‎25
操作系统内部版本	19044.2006
体验	Windows Feature Experience Pack 120.2212.4180.0

**Comment by vvwinnie** [comment] 2022-09-15 04:52
hi, 请问这个问题解决了嘛？我跟你是一样的版本o(╥﹏╥)o

**Comment by Shekhars** [comment] 2022-09-15 04:55
Same issue here. I am on the same version.

**Comment by menkemi** [comment] 2022-09-15 11:32
Yep, same issue!

**Comment by menkemi** [comment] 2022-09-15 11:55
With https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini i get "Fully supported"

<img width="1728" alt="Bildschirmfoto 2022-09-15 um 13 55 05" src="https://user-images.githubusercontent.com/100273580/190397263-2d618d3b-0600-4472-ae7c-961ac710351f.png">

But still cant connect multiple sessions, any ideas?

**Comment by sashaqwert** [comment] 2022-09-15 12:20
Duplicate of https://github.com/stascorp/rdpwrap/issues/1968

**Closed as not planned by sashaqwert** 2022-09-15 12:20 UTC
Labels: duplicate

**Comment by sashaqwert** [comment] 2022-09-15 12:24
@menkemi 
> But still cant connect multiple sessions, any ideas?

Try in CMD as Administrator:

```
net stop termService
net start termService
```
Or reboot.

**Comment by netoitape** [comment] 2022-09-15 14:01
Hello guys, I need help becase de new rdpwrap.ini not work for me. My windows version this is below, but I need change only rdpwrap.ini or the termsrv too? If the change the termsrv with how do I do that? Thanks for all helps 

Edição	Windows 10 Pro
Versão	21H2
Instalado em	‎17/‎07/‎2022
Compilação do SO	19044.2006
Experiência	Windows Feature Experience Pack 120.2212.4180.0

**Comment by adieux** [comment] 2022-09-16 00:07
Same issue here. My windows 10 just got updated to 10.0.19044.2006 and I could not do remote desktop now.

**Comment by vvwinnie** [comment] 2022-09-16 09:29
> Same issue here. My windows 10 just got updated to 10.0.19044.2006 and I could not do remote desktop now.
My computer is 64bit,
refer #1968 
1. uinstall.bat(Administrator)
2. backup C:\windows\System32\termsrv.dll(may need to change permission)
3. stop remote desktop servie(Try in CMD as Administrator):
    net stop termService

4. replace termsrv.dll and rdpwrap.ini 
 [https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini]
[https://github.com/stascorp/rdpwrap/files/9438208/termsrv--Win10--21H1--2022-08-28--10.0.19041.1949--64bit.zip](url)

5. then install.bat again(Administrator)

**Comment by menkemi** [comment] 2022-09-16 09:42
> @menkemi
> 
> > But still cant connect multiple sessions, any ideas?
> 
> Try in CMD as Administrator:
> 
> ```
> net stop termService
> net start termService
> ```
> 
> Or reboot.

Yep, worked after i locked myself out and had to drive to the physical location of the server :)

1) Used update script
2) updated the ini with [https://github.com/stascorp/rdpwrap/files/9438208/termsrv--Win10--21H1--2022-08-28--10.0.19041.1949--64bit.zip](https://github.com/stascorp/rdpwrap/issues/url)
3) Reboot

Now it works fine with 19044.2006

Thank you all :)

**Comment by timba64** [comment] 2022-09-28 12:21
I have Win 10.0.19044.2006 and the problem aren't decided because we don't have section 
[10.0.19044.2006] in rdpwrap.ini
PLEASE HELP US !!

**Comment by sashaqwert** [comment] 2022-09-28 14:04
@timba64

> 10.0.19044.2006

This is a Windows version.
The `rdpwrap.ini` contains only termsrv.dll versions.

Please, use a version from RDPConf. I guarantee that it will definitely be found in INI...

**Comment by timba64** [comment] 2022-09-28 14:52
Thank you for your efforts and o quick answer - my rdp works fine !!!!!
