### ISSUE TITLE
Need help with 10.0.22621.608

### ISSUE THREAD

**Issue by shuuuimu** [stascorp/rdpwrap#2112] opened 2023-02-13 14:02 UTC
the dll from [2006#](https://github.com/stascorp/rdpwrap/issues/2006) doesn't work
<img width="303" alt="image" src="https://user-images.githubusercontent.com/125280665/218477406-480078fe-6726-4397-a187-1b69fee268b6.png">
uninstall
<img width="734" alt="image" src="https://user-images.githubusercontent.com/125280665/218478016-9b0417f1-739c-45bc-b78f-2f3b671326d4.png">
install
<img width="666" alt="image" src="https://user-images.githubusercontent.com/125280665/218478181-46a1b5d9-7727-4efa-8bcd-96c320d7cbdc.png">

**Comment by shuuuimu** [comment] 2023-02-13 14:20
by the way, this is from my system information...
<img width="276" alt="image" src="https://user-images.githubusercontent.com/125280665/218483073-818e1940-2002-4ca3-9d73-81dcb3fd8b06.png">

**Comment by sashaqwert** [comment] 2023-02-13 17:44
Duplicate of https://github.com/stascorp/rdpwrap/issues/2006

**Closed as not planned by sashaqwert** 2023-02-13 17:44 UTC
Labels: duplicate
