### ISSUE TITLE
Limitation of number of connections under windows 2016

### ISSUE THREAD

**Issue by ometlaine** [stascorp/rdpwrap#531] opened 2018-07-29 16:18 UTC
Hello,
I allow myself to solicit you because we have a problem with Windows 2016.

We do not use Microsoft RDS services, but a third-party solution. With this solution, under Windows 2012 Standard, our users can open 5 to 30+ sessions and access the Desktop.

With this solution, under Windows 2016 Standard, it is not possible to open more than 16 sessions (15 remote sessions + Console). From session 17, black screen for 3 minutes and unstable session (the Start menu is not active for example).
The hardware resources are identical (2 cpu 3Ghz, 16 GB Ram).

We have installed an identical configuration with Windows 2016 Standard and we have installed RDPWrap. Our tests lead to the same conclusion: limitation of the system to 16 maximum RDP sessions.

Another test: 18 sessions. If we disconnect two sessions, then the last 2 sessions work;)

Do you have examples of Windows 2016 servers that accept more than 16 simultaneous sessions?

Thank you in advance for your answers. And sorry if my english is not very clean.

Regards

**Comment by FlashNetCloud** [comment] 2018-08-20 14:40
Have you tried adding more CPU to the 2016 server?

**Comment by binarymaster** [comment] 2018-08-24 12:14
Looks like duplicate of #512, let's continue discussion in that thread.

**Closed by binarymaster** 2018-08-24 12:14 UTC
