### ISSUE TITLE
19041.789 not supported

### ISSUE THREAD

**Issue by Asyw** [stascorp/rdpwrap#1388] opened 2021-04-30 05:06 UTC
I'm windows 10. The home system doesn't support remote desktop connection. Who has a good way?

**Comment by XingShuyu** [comment] 2021-04-30 13:45
oh，you can try rdpwarp project.
If you have some problems,and if you have encountered certain problems and have the energy and ability to solve them, you can refer to this article (this is a Chinese article because I am a Chinese)
https://blog.csdn.net/u010804317/article/details/104011926

**Comment by sydtc5545741** [comment] 2021-05-01 16:19
> 
> 
> I'm windows 10. The home system doesn't support remote desktop connection. Who has a good way?

windows version 19042.928 win10 20H2
RDPWARP Version 10.0.190401.789
now work！！！！！

try this link download rdpwarp.ini https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini

**Comment by engr-mazdaa-razavi** [comment] 2021-05-04 20:48
> > I'm windows 10. The home system doesn't support remote desktop connection. Who has a good way?
> 
> windows version 19042.928 win10 20H2
> RDPWARP Version 10.0.190401.789
> now work！！！！！
> 
> try this link download rdpwarp.ini https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini

Hi
the latest rdpwrap.ini (21332.1000-SLInit) do not worked on windows 10 20h2.
Please help me figure out how to fix this problem.
Thanks 


![RDPWrap-Configuration-1400-02-14](https://user-images.githubusercontent.com/83561176/117067828-bbc92a80-ad3f-11eb-99b2-207df1fd5db6.JPG)
![RDPWrap-Error-1400-02-14](https://user-images.githubusercontent.com/83561176/117067834-bd92ee00-ad3f-11eb-804e-8450d9d8edcf.JPG)

**Comment by FirstSpectr** [comment] 2021-05-09 16:49
same issue

**Comment by raycheung** [comment] 2021-05-10 01:34
> 
> 
> > I'm windows 10. The home system doesn't support remote desktop connection. Who has a good way?
> 
> windows version 19042.928 win10 20H2
> RDPWARP Version 10.0.190401.789
> now work！！！！！
> 
> try this link download rdpwarp.ini https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini

This works for me.

**Comment by FirstSpectr** [comment] 2021-05-10 09:18
Found a better solution: there is a file "autoupdate.bat" in the telegram channel https://t.me/rdpwrap. It downloads the latest ini file automatically. There is a complete instruction https://t.me/rdpwrap/29731

**Comment by sebaxakerhtc** [comment] 2022-06-20 13:19
Duplicate of https://github.com/stascorp/rdpwrap/issues/1317

**Closed as completed by sebaxakerhtc** 2022-06-20 13:19 UTC
