### ISSUE TITLE
Rdpwrap 19043.2130 not working

### ISSUE THREAD

**Issue by Barisha70** [stascorp/rdpwrap#2020] opened 2022-10-17 08:02 UTC
RdpWrap don't work on 19043.2130.
Please help me !
Thnx!

**Comment by sashaqwert** [comment] 2022-10-17 08:54
Please, attach your RDPConf screenshot and `termsrv.dll`

**Comment by Barisha70** [comment] 2022-10-17 08:59
I remove last installed updates from update history.
Now work under ver. 19043.1889





pon, 17. lis 2022. u 10:54 Aleksandr Chivarzin ***@***.***>
napisao je:

**Comment by Sharma73012** [comment] 2022-10-17 09:07
> 

![image](https://user-images.githubusercontent.com/115984143/196137245-cbbbcd31-69b3-4b93-a310-c7051855b260.png)

**Comment by Barisha70** [comment] 2022-10-17 09:12
After reinstall last updates now working on this version...


[image: image.png]






pon, 17. lis 2022. u 11:07 Sharma73012 ***@***.***> napisao
je:

**Comment by Sharma73012** [comment] 2022-10-17 09:17
> Please, attach your RDPConf screenshot and `termsrv.dll`
![image](https://user-images.githubusercontent.com/115984143/196139624-f2324512-f800-42d1-8515-d441149062f3.png)

**Comment by sashaqwert** [comment] 2022-10-17 10:27
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992

**Closed as not planned by sashaqwert** 2022-10-17 10:27 UTC
Labels: duplicate
