### ISSUE TITLE
Version not updating

### ISSUE THREAD

**Issue by fipekui** [stascorp/rdpwrap#1024] opened 2020-03-13 11:44 UTC
I added the 10.0.18362.657 lines in my rdpwrap.ini but the version shows 10.0.18362.53 in the wrapper configuration. Any ideas why the version wont update?

**Comment by affinityv** [comment] 2020-03-13 21:38
Have you got Windows updates to apply to get a later version.  The version that shows in rdpconf is the one of the termsrv.dll .... not what it finds in the INI file.

**Comment by sebaxakerhtc** [comment] 2022-04-27 15:57
Duplicate of https://github.com/stascorp/rdpwrap/issues/983

**Closed as completed by sebaxakerhtc** 2022-04-27 15:57 UTC
