### ISSUE TITLE
19041.804 can someone help me

### ISSUE THREAD

**Issue by jonytestXD** [stascorp/rdpwrap#1326] opened 2021-02-11 20:17 UTC
my updated yesterday to build 19041.804 and rdp wrapper isnt working, can some one helpme thanks by the way

**Comment by Jbarrioscuarenta** [comment] 2021-02-14 01:50
my build 19041.804 rdp wrapper isnt working, can some one helpme thanks

**Comment by XelaUA** [comment] 2021-02-14 10:49
some problem on build 19041.804, need working .ini

**Comment by Zykov-Alexey** [comment] 2021-02-15 08:58
It works for me

[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/5980461/rdpwrap.zip)

**Comment by master-yun-yun** [comment] 2021-02-15 14:48
> It works for me
> 
> [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/5980461/rdpwrap.zip)

can you upload your termsrv.dll  file？
thx

**Comment by XelaUA** [comment] 2021-02-16 09:01
> some problem on build 19041.804, need working .ini

all good, need to be copied with administrator rights

**Comment by BALAHLOP** [comment] 2021-02-16 13:58
Help me please, после обновление не работает, что сделать чтобы он опять работал???

**Comment by sashaqwert** [comment] 2021-02-18 17:29
> 
> 
> It works for me
> 
> [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/5980461/rdpwrap.zip)

This is 100% DO NOT work.
This INI is not contains 19041.804 (It's your version from RDPConf?)
termsrv.dll version != Windows version

**Comment by TheRainTime** [comment] 2021-02-19 17:24
> It works for me
> 
> [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/5980461/rdpwrap.zip)
It can't work on 19041.804 ,  but on 19042.804
19041.804   fully supported but NOT LISTENING

**Comment by TheRainTime** [comment] 2021-02-19 17:37
> It works for me
> 
> [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/5980461/rdpwrap.zip)

It cannot work on 19041.804 
Not listening but fully supported

**Comment by sk-lau** [comment] 2021-02-20 03:43
> > It works for me
> > [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/5980461/rdpwrap.zip)
> 
> It cannot work on 19041.804
> Not listening but fully supported

Please try the latest version from Amstron

You can run the update program under Administrator

**Comment by NegroCR** [comment] 2021-02-26 21:40
Sorry i was open another case (duplicated). I have the same problem. INI file didn´t works.

**Comment by NegroCR** [comment] 2021-02-26 21:55
Amstron INI  file don´t contains lines for 19041.804 version, only for 19041.84 version.

**Comment by Aidas777** [comment] 2021-03-02 22:44
That's true. Amstron INI file don´t contains lines for 19041.804 version. Only for .84

**Comment by chinamonkeyking** [comment] 2021-03-06 01:57
My "OS Build" shows "19041.804" but in "RDP Wrapper Configuration" it shows "10.0.19041.789". So I refer to https://github.com/stascorp/rdpwrap/issues/1317 and it works for me

**Comment by sebaxakerhtc** [comment] 2022-06-20 12:55
Duplicate of https://github.com/stascorp/rdpwrap/issues/1317

**Closed as completed by sebaxakerhtc** 2022-06-20 12:55 UTC
