### ISSUE TITLE
help me please,thank you.

### ISSUE THREAD

**Issue by github-world** [stascorp/rdpwrap#1481] opened 2021-07-26 06:38 UTC
![image](https://user-images.githubusercontent.com/24997143/126943888-74cc3ddf-3884-40ad-b817-d20feb3cab18.png)
![image](https://user-images.githubusercontent.com/24997143/126943954-ba368db3-d6f0-40e9-b83b-8d58d87a1652.png)

**Comment by thomtsib** [comment] 2021-07-26 12:26
You must add this text at rdpwrap.ini

[10.0.22000.1-SLInit]
; no x86 section

bServerSku.x64        =11FED0
bRemoteConnAllowed.x64=11FEE4
bFUSEnabled.x64       =11FEF4
bAppServerAllowed.x64 =11FEDC
bMultimonAllowed.x64  =11FEE8
lMaxUserSessions.x64  =11FED4
ulMaxDebugSessions.x64=11FEF0
bInitialized.x64      =11FECC

[10.0.22000.1]
; no x86 section

LocalOnlyPatch.x64    =1
LocalOnlyOffset.x64   =98C11
LocalOnlyCode.x64     =jmpshort
SingleUserPatch.x64   =1
SingleUserOffset.x64  =088C2
SingleUserCode.x64    =Zero
DefPolicyPatch.x64    =1
DefPolicyOffset.x64   =1BB75
DefPolicyCode.x64     =CDefPolicy_Query_eax_rcx
SLInitHook.x64        =1
SLInitOffset.x64      =26AD0
SLInitFunc.x64        =New_CSLQuery_Initialize

**Comment by sebaxakerhtc** [comment] 2021-10-25 16:10
duplicate of https://github.com/stascorp/rdpwrap/issues/1455

**Closed as completed by sebaxakerhtc** 2021-10-25 16:10 UTC
