### ISSUE TITLE
DANGER : this app is very dangerous ! Ransomware !

### ISSUE THREAD

**Issue by 1saeedir** [stascorp/rdpwrap#977] opened 2020-02-02 23:02 UTC
I downloaded this on my VPS while I faced by chrome and windows firewall warning but because server created for the test I run these files and It looks good in appearance ! after minutes I realized it had happened.
**it's a "Ransomware" !!**
ALL Files encrypted and created a text file that requests money for decryption files on long steps!

**Comment by affinityv** [comment] 2020-02-03 09:52
Is this just a Windows install with RDP open to the world and updates not applied?
Never leave RDP open to the world btw.

If this app is dangerous, then this is the first occurrence, ever, of such ransomware; IOW, it is not this app.

**Comment by BMRX** [comment] 2020-02-07 01:24
Can proof be provided?

**Comment by Theli93** [comment] 2020-02-07 17:30
As the saying goes... "Correlation does not imply causation."
Too many of us have been using the software on multiple computers for too long to give the illegitimate accusation any credence.

Lack of understanding, paranoia, and irresponsible computer security management is no excuse for libel.

**Comment by 1saeedir** [comment] 2020-02-07 18:00
Unfortunately, I deleted VPS fast, because my dedicated servers are on OVH Datacenter and it's very sensitive to these actions, The Abuse comes very quickly.
And I am correcting that this may be a conflict between other software.
It may not have much to do with this, although I got into trouble after installing this software, nothing can be said definitively.
But I am sure that when Download this file:  Windows, and chrome notified, blocked and serious warnings that this file is very dangerous! 
if I give Like and agreement on this comment, I will create a new Server and install this again to take screenshots proof from all steps and Events. and can open public access on this server that you can login and check to this server.

**Comment by papoluisjr** [comment] 2020-02-09 03:09
> I downloaded this on my VPS while I faced by chrome and windows firewall warning but because server created for the test I run these files and It looks good in appearance ! after minutes I realized it had happened.
> **it's a "Ransomware" !!**
> ALL Files encrypted and created a text file that requests money for decryption files on long steps!

Thank you, In fact it is very dangerous. I cheched the file before downloading it. Everytime you want to check a file before download it, go to virustotal and drag/drop the file or just put the url and it will tell you. This file has a trojan also. You can also download the zip, but do not open it. Just drag the file to the website virustotal and you will see how dangerous this is!

**Comment by papoluisjr** [comment] 2020-02-09 03:10
> Can proof be provided?

Download the file as a zip and do not open it. Go to virustotal and drop them there. You will see the proof there.

**Comment by BMRX** [comment] 2020-02-10 18:01
> > Can proof be provided?
> 
> Download the file as a zip and do not open it. Go to virustotal and drop them there. You will see the proof there.

This is not proof, I don't think you understand what you are doing. Sites like virustotal give false positives all the time.

This software is not harmful, however I reccommend you stay away from it if you have no idea what it does or what its purpose is.

**Comment by papoluisjr** [comment] 2020-02-10 19:15
I encourage you to freely go ahead and extract all the files in your computer, specifically this one: https://github.com/stascorp/rdpwrap/releases/download/v1.6.2/RDPWInst-v1.6.2.msi 
You are going to repent!

**Comment by papoluisjr** [comment] 2020-02-10 19:15
Need proof, go ahead and install it!

**Comment by sebaxakerhtc** [comment] 2022-04-27 15:41
Duplicate of https://github.com/stascorp/rdpwrap/issues/277

**Closed as completed by sebaxakerhtc** 2022-04-27 15:41 UTC
