### ISSUE TITLE
RDP Wrap Win10 Pro - Cannot acces more than one USER

### ISSUE THREAD

**Issue by melvin770** [stascorp/rdpwrap#482] opened 2018-05-14 18:25 UTC
Hello, 

Since i did last windows update, i cannot log in with more than one user

1) are you planing to launch a new version of RDP Wrap
2) i any body can help me solve this problem (i am ready to pay i cannot wait)

Thanks for help

**Comment by alcaraz73** [comment] 2018-05-15 01:45
Melvin, 

replace termsvr32.dll with an older one.

Take a look on this: https://github.com/stascorp/rdpwrap/issues/456

Regards.

**Comment by Bigben83** [comment] 2018-05-15 01:59
Attached is the latest termsrv.dll 10.0.17134.1
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/2003185/termsrv.zip)

**Comment by alcaraz73** [comment] 2018-05-15 02:30
Thanks, this version is patched?

**Comment by binarymaster** [comment] 2018-05-16 10:02
Duplicate of #456.

**Closed by binarymaster** 2018-05-16 10:02 UTC
