### ISSUE TITLE
Win10 1909 - 18363.1139 #1083

### ISSUE THREAD

**Issue by 7BigD** [stascorp/rdpwrap#1226] opened 2020-12-04 02:49 UTC
Hi, 

I am running the above build, and I've searched the issues to see if anyone has a solution, but I cannot find one.

![image](https://user-images.githubusercontent.com/56389190/101115153-daef4f00-361d-11eb-8d20-3dd300cd95b3.png)

I assume it's not listening and not supported because the versions do not match?
I also have a question :
1.  my os' version is 18363.1139 . it does not match with version 18362?
Can anyone help?

**Comment by karmon11** [comment] 2020-12-05 16:22
Try this https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini
For my 18363.1198 shows all in green.

**Comment by sebaxakerhtc** [comment] 2022-06-20 11:58
Duplicate of https://github.com/stascorp/rdpwrap/issues/1083

**Closed as completed by sebaxakerhtc** 2022-06-20 11:58 UTC
