### ISSUE TITLE
RDP Wrapper not working after update in Windows 10 10.0.19042 Build 19042

### ISSUE THREAD

**Issue by abhinavdangri** [stascorp/rdpwrap#1244] opened 2020-12-11 02:00 UTC
Hi Github Community.
Previously I was using RDP Wrapper and it was working correctly.
But after the update in windows 10 I am not able to use the RDP wrapper.
Listener state is listening but not supported.

Please Help me I need this solution ASAP.

**Comment by KrishnaST** [comment] 2020-12-11 07:35
RDP stopped working after morning update.
Windows 10 10.0.19042 Build 19042.685

**Comment by asmtron** [comment] 2020-12-11 07:47
please upload file "C:\Windows\System32\termsrv.dll" for Windows 10 10.0.19042 (x64 and x86)

**Comment by manishgour** [comment] 2020-12-11 09:29
[termsrv.pdf](https://github.com/stascorp/rdpwrap/files/5678279/termsrv.pdf)
rename pdf to dll

**Comment by mathewjpotter** [comment] 2020-12-11 15:53
go to windows update, and remove the recent windows security updates in the past two days. It will fix it.

**Comment by arnoldvdm** [comment] 2020-12-11 23:58
For me the same.
I think it's KB4592438 or the dot net framework: KB4586876

After removing and trying to reinstall:

> your device shall not be updated as long as updates are interrupted.
> updates will resume on: 19-12-2020

![image](https://user-images.githubusercontent.com/62776508/101965640-b561d700-3c15-11eb-965d-b8a22ef75019.png)

**Comment by AdrianQT** [comment] 2020-12-12 00:03
i need the ini file plz

**Comment by arnoldvdm** [comment] 2020-12-12 00:21
100% that it's KB4592438

**Comment by asmtron** [comment] 2020-12-12 09:09
We can **ONLY** help you and create the ini entries for 10.0.19042 when **YOU** upload the termsrv.dll for this Windows version!

### Upload the termsrv.dll (v.10.0.19042)

**Comment by watkmogi** [comment] 2020-12-12 12:33
Morning, mine not working too. Since yesterday. 

> termsrv.dll



[termsrv.zip](https://github.com/stascorp/rdpwrap/files/5683061/termsrv.zip)

**Comment by arnoldvdm** [comment] 2020-12-12 17:15
I have the same termsrv.dll size so I think it's the same file. (only a higher zip compression (7z))
> termsrv.dll 


[termsrv.zip](https://github.com/stascorp/rdpwrap/files/5683471/termsrv.zip)

**Comment by Huasah** [comment] 2020-12-12 20:04
Mine not working either. 
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/5683683/termsrv.zip)

**Comment by asmtron** [comment] 2020-12-13 19:07
@watkmogi
@arnoldvdm
@Huasah
thx for the upload; all the three termsrv.dll's have the version 10.0.19041.662; and this version is already supported on Win10 10.0.19041.662, 10.0.19041.685...

The autoupdate.bat batch file will automatically update the dpwrap.ini file to support the new  termsrv.dll 10.0.19041.662.

_Update: 12.12.2020: changing the restart method so we can copy and not stream the new downloaded ini; hope this fixes problems with loading of the new ini file on some systems..._

Download & install:
https://github.com/asmtron/rdpwrap/blob/master/binary-download.md

------------------------

```
or only the ini entries...

[10.0.19041.662]
LocalOnlyPatch.x86=1
LocalOnlyOffset.x86=B5F59
LocalOnlyCode.x86=jmpshort
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=88E81
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x86=1
SingleUserOffset.x86=3BC05
SingleUserCode.x86=nop
SingleUserPatch.x64=1
SingleUserOffset.x64=0CA0C
SingleUserCode.x64=Zero
DefPolicyPatch.x86=1
DefPolicyOffset.x86=3E779
DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
DefPolicyPatch.x64=1
DefPolicyOffset.x64=189D5
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x86=1
SLInitOffset.x86=68068
SLInitFunc.x86=New_CSLQuery_Initialize
SLInitHook.x64=1
SLInitOffset.x64=1D50C
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.19041.662-SLInit]
bInitialized.x86      =D1954
bServerSku.x86        =D1958
lMaxUserSessions.x86  =D195C
bAppServerAllowed.x86 =D1964
bRemoteConnAllowed.x86=D196C
bMultimonAllowed.x86  =D1970
ulMaxDebugSessions.x86=D1974
bFUSEnabled.x86       =D1978

bInitialized.x64      =106028
bServerSku.x64        =10602C
lMaxUserSessions.x64  =106030
bAppServerAllowed.x64 =106038
bRemoteConnAllowed.x64=106040
bMultimonAllowed.x64  =106044
ulMaxDebugSessions.x64=106048
bFUSEnabled.x64       =10604C
```

**Comment by aqasem81** [comment] 2020-12-13 20:34
Working as charm! Thank you.

**Comment by chuanh-ustc** [comment] 2020-12-14 09:57
> @watkmogi
> @arnoldvdm
> @Huasah
> thx for the upload; all the three termsrv.dll's have the version 10.0.19041.662; and this version is already supported on Win10 10.0.19041.662, 10.0.19041.685...
> 
> The autoupdate.bat batch file will automatically update the dpwrap.ini file to support the new termsrv.dll 10.0.19041.662.
> 
> _Update: 12.12.2020: changing the restart method so we can copy and not stream the new downloaded ini; hope this fixes problems with loading of the new ini file on some systems..._
> 
> Download & install:
> https://github.com/asmtron/rdpwrap/blob/master/binary-download.md
> 
> ```
> or only the ini entries...
> 
> [10.0.19041.662]
> LocalOnlyPatch.x86=1
> LocalOnlyOffset.x86=B5F59
> LocalOnlyCode.x86=jmpshort
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=88E81
> LocalOnlyCode.x64=jmpshort
> SingleUserPatch.x86=1
> SingleUserOffset.x86=3BC05
> SingleUserCode.x86=nop
> SingleUserPatch.x64=1
> SingleUserOffset.x64=0CA0C
> SingleUserCode.x64=Zero
> DefPolicyPatch.x86=1
> DefPolicyOffset.x86=3E779
> DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=189D5
> DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> SLInitHook.x86=1
> SLInitOffset.x86=68068
> SLInitFunc.x86=New_CSLQuery_Initialize
> SLInitHook.x64=1
> SLInitOffset.x64=1D50C
> SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.19041.662-SLInit]
> bInitialized.x86      =D1954
> bServerSku.x86        =D1958
> lMaxUserSessions.x86  =D195C
> bAppServerAllowed.x86 =D1964
> bRemoteConnAllowed.x86=D196C
> bMultimonAllowed.x86  =D1970
> ulMaxDebugSessions.x86=D1974
> bFUSEnabled.x86       =D1978
> 
> bInitialized.x64      =106028
> bServerSku.x64        =10602C
> lMaxUserSessions.x64  =106030
> bAppServerAllowed.x64 =106038
> bRemoteConnAllowed.x64=106040
> bMultimonAllowed.x64  =106044
> ulMaxDebugSessions.x64=106048
> bFUSEnabled.x64       =10604C
> ```

@asmtron
it`s still not working in my PC :(

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/5687954/termsrv.zip)

**Comment by DrMunni** [comment] 2020-12-14 19:00
> @asmtron
> it`s still not working in my PC :(

Leaving a blank line break at the end of the ini file fixed it for me

**Comment by andres-roman** [comment] 2020-12-21 17:23
> > @asmtron
> > it`s still not working in my PC :(
> 
> Leaving a blank line break at the end of the ini file fixed it for me

It is confirmed that adding a blank line works.

**Comment by IvanMurzak** [comment] 2020-12-22 21:19
Thanks, it works for me too. A blank line in the end added. But I'm not @MunniDerMeister by the way :)

**Comment by gesgood** [comment] 2021-01-14 01:47
> please upload file "C:\Windows\System32\termsrv.dll" for Windows 10 10.0.19042 (x64 and x86)

Hi @asmtron ,
  My OS version is  19042.746, and here is the termsrv.dll
  Looking forward your relpy, 
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/5811919/termsrv.zip)
Thanks.

**Comment by Melnick704** [comment] 2021-01-14 09:05
> > please upload file "C:\Windows\System32\termsrv.dll" for Windows 10 10.0.19042 (x64 and x86)
> 
> Hi @asmtron ,
> My OS version is 19042.746, and here is the termsrv.dll
> Looking forward your relpy,
> [termsrv.zip](https://github.com/stascorp/rdpwrap/files/5811919/termsrv.zip)
> Thanks.

Please, give your .ini file for 19042.746

**Comment by gesgood** [comment] 2021-01-15 01:58
> > > please upload file "C:\Windows\System32\termsrv.dll" for Windows 10 10.0.19042 (x64 and x86)
> > 
> > 
> > Hi @asmtron ,
> > My OS version is 19042.746, and here is the termsrv.dll
> > Looking forward your relpy,
> > [termsrv.zip](https://github.com/stascorp/rdpwrap/files/5811919/termsrv.zip)
> > Thanks.
> 
> Please, give your .ini file for 19042.746

My wrapper doesn't work on 19042.746 either, -_-!
And I'm looking for help from @asmtron

**Comment by Yen-Pang-Lai** [comment] 2021-01-19 22:52
Hi @asmtron ,

I also got the same problem with the OS version of 19042.746 and below is my termsrv file. 
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/5839037/termsrv.zip)
I appreciate for your help.

Thanks.

**Comment by thegadgetman-uk** [comment] 2021-01-22 11:05
Hi @asmtron, and to those having issues with OS 19042.746...

I recently found this project and encountered the issue about with the listener not being support on OS 19042.746 and I assumed an updated INI file would be needed as I couldn't find the OS version listed in the ini file from the install.

I was going to upload my termserv.dll when I noticed that the dll file version is 10.0.19041.746 - different from the OS version.

I then found the ini file that @affinityv has created at https://github.com/stascorp/rdpwrap/issues/999#issuecomment-668673903 which does contain the references for the dll version I have and I followed the instructions in that thread for replacing the ini file with the one affinityv has updated - PROBLEM SOLVED!

Hopefully this is helpful for others now knowing that the OS version and the termserv.dll version can differ (sorry if people already know this but I am new!).

Thanks again to everyone in this community and for the project which has solved a big problem for me.

**Comment by asmtron** [comment] 2021-01-24 13:09
Hi,

there a two possible entries for SingleUserOffset [10.0.19041.746]. 
ver1: SingleUserOffset.x64=0CA4C
ver2: SingleUserOffset.x64=0CB22

on my system Win10 64 Pro only the ver1 entry works. The ver2 entry gives me the [not supported]. Can you please check if ver1 or ver2 works on your win10 ?

To test:
1. open "cmd.exe" as admin and go to RDP Wrapper `cd C:\Program Files\RDP Wrapper`
2. uninstall  RDP Wrapper: `RDPWInst -u`
3. edit rdpwrap.ini: `notepad rdpwrap.ini` 
4. go to/search [10.0.19041.746] and change SingleUserOffset.x64 to 0CA4C (ver1) or 0CB22 (ver2)
```
[10.0.19041.746]
...
SingleUserOffset.x64=0CA4C
```
or
```
[10.0.19041.746]
...
SingleUserOffset.x64=0CB22
```
5. save and exit notepad
6. install RDP Wrapper: `RDPWInst -i`
7. run RDPConf to test: `RDPConf.exe`

**Comment by Yen-Pang-Lai** [comment] 2021-01-25 19:43
> Hi,
> 
> there a two possible entries for SingleUserOffset [10.0.19041.746].
> ver1: SingleUserOffset.x64=0CA4C
> ver2: SingleUserOffset.x64=0CB22
> 
> on my system Win10 64 Pro only the ver1 entry works. The ver2 entry gives me the [not supported]. Can you please check if ver1 or ver2 works on your win10 ?
> 
> To test:
> 
> 1. open "cmd.exe" as admin and go to RDP Wrapper `cd C:\Program Files\RDP Wrapper`
> 2. uninstall  RDP Wrapper: `RDPWInst -u`
> 3. edit rdpwrap.ini: `notepad rdpwrap.ini`
> 4. go to/search [10.0.19041.746] and change SingleUserOffset.x64 to 0CA4C (ver1) or 0CB22 (ver2)
> 
> ```
> [10.0.19041.746]
> ...
> SingleUserOffset.x64=0CA4C
> ```
> 
> or
> 
> ```
> [10.0.19041.746]
> ...
> SingleUserOffset.x64=0CB22
> ```
> 
> 1. save and exit notepad
> 2. install RDP Wrapper: `RDPWInst -i`
> 3. run RDPConf to test: `RDPConf.exe`

Hi Asmtron,

The version-1 works for me. 
Thank you very much.

**Comment by WITTORIO98** [comment] 2021-02-01 14:41
> Hi,
> 
> there a two possible entries for SingleUserOffset [10.0.19041.746].
> ver1: SingleUserOffset.x64=0CA4C
> ver2: SingleUserOffset.x64=0CB22
> 
> on my system Win10 64 Pro only the ver1 entry works. The ver2 entry gives me the [not supported]. Can you please check if ver1 or ver2 works on your win10 ?
> 
> To test:
> 
> 1. open "cmd.exe" as admin and go to RDP Wrapper `cd C:\Program Files\RDP Wrapper`
> 2. uninstall  RDP Wrapper: `RDPWInst -u`
> 3. edit rdpwrap.ini: `notepad rdpwrap.ini`
> 4. go to/search [10.0.19041.746] and change SingleUserOffset.x64 to 0CA4C (ver1) or 0CB22 (ver2)
> 
> ```
> [10.0.19041.746]
> ...
> SingleUserOffset.x64=0CA4C
> ```
> 
> or
> 
> ```
> [10.0.19041.746]
> ...
> SingleUserOffset.x64=0CB22
> ```
> 
> 1. save and exit notepad
> 2. install RDP Wrapper: `RDPWInst -i`
> 3. run RDPConf to test: `RDPConf.exe`

Hi asmtron,
in my .ini, I don't have the version you indicated!
  i only have up to version 10.0.17763.1;  and even trying "update.bat" doesn't change anything


edit: 
okok, i just "stolen" .ini file from your repo, and it works fine. (ty) 
but... can be true? the "official" support discontinued in 2018?🤔

**Comment by abhinavdangri** [comment] 2021-02-02 04:44
I got new update: 
![image](https://user-images.githubusercontent.com/44752159/106553333-3adf7480-653f-11eb-8bc4-50ffda8daf77.png)

now it is not working
previously we removed the 2438 security update and then it was working fine but now it is not working.

here are my new updates:
![image](https://user-images.githubusercontent.com/44752159/106553437-682c2280-653f-11eb-9bb2-ad8a215a8c36.png)


Please upload a new ini file or give some solid solution

**Comment by abhinavdangri** [comment] 2021-02-02 04:46
@mathewjpotter 
@arnoldvdm 
@KrishnaST 
@Retinoid

**Comment by abhinavdangri** [comment] 2021-02-04 06:59
Hi @asmtron 
Please give ini file for new version 
19042.746

**Comment by sandyrondonc** [comment] 2021-02-08 15:09
Hello, i install my PC recently, and i cant delete the updates, i have this version too
![image](https://user-images.githubusercontent.com/78744745/107238294-bc9c3a00-6a38-11eb-925b-8d534b474736.png)
@asmtron Please give ini file for new version 19042.746

**Comment by jamesngob** [comment] 2021-03-02 00:17
Please provide us the new ini file for the latest windows update 19042.844
This update is as of 24 Feb 2021/
The RDPWrapper stop working after this udpate

**Comment by ninjacarlo** [comment] 2021-03-06 14:14
> Please provide us the new ini file for the latest windows update 19042.844
> This update is as of 24 Feb 2021/
> The RDPWrapper stop working after this udpate

YES, please provide the lastest update for 19042.844


[termsrv.zip](https://github.com/stascorp/rdpwrap/files/6095450/termsrv.zip)

**Comment by khupzki** [comment] 2021-04-06 02:01
hi Guys,

Anyone has an updated INI entry for OS build 19041.867 ?

**Comment by westkil** [comment] 2021-04-13 16:47
> hi Guys,
> 
> Anyone has an updated INI entry for OS build 19041.867 ?

Affraid, nobody for now. Looking for it...

**Comment by affinityv** [comment] 2021-05-03 16:26
> Anyone has an updated INI entry for OS build 19041.867 ?

Okay, what version is the actual DLL as shown in `RDPConf.exe` ?

**Comment by lucindrea** [comment] 2021-05-17 16:54
Please update ini 

according to windows 
Version 20H2
OS  19042.985
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/6495518/termsrv.zip)


but rdpconf shows 10.0.1941.964 (with listener not working of course)

**Comment by gianmaxfactor** [comment] 2021-05-22 20:24
> Please update ini
> 
> according to windows
> Version 20H2
> OS 19042.985
> [termsrv.zip](https://github.com/stascorp/rdpwrap/files/6495518/termsrv.zip)
> 
> but rdpconf shows 10.0.1941.964 (with listener not working of course)

Same here, please help. Thanks.
PS.: could someone teach us how to do, so that more people can help updating the ini?

PS.: it seems to work with this ini
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/6527106/rdpwrap.zip)

**Comment by affinityv** [comment] 2021-06-08 16:58
Update your [INI](https://raw.githubusercontent.com/affinityv/INI-RDPWRAP/master/rdpwrap.ini) .

When it is in place, then do `RDPWInst -r` to activate it; DO NOT run install.bat again.

Make sure that Windows Defender has exceptions for the RDP product directory, ditto for any other AV.

**Comment by gnbcreations** [comment] 2021-06-29 04:19
rdp wrapper not supported windows 10 20h2 19042.1052

![image](https://user-images.githubusercontent.com/67085221/123736792-6b91c300-d8bf-11eb-9635-efff02139674.png)

**Comment by gnbcreations** [comment] 2021-06-29 04:43
rdp wrapper not supported windows 10 20h2 19042.1052

please upload ini file sir

**Comment by affinityv** [comment] 2021-07-01 13:08
What version does `RDPConf.exe` show?

**Comment by flybeye** [comment] 2021-07-08 01:10
Win 10 20H2 19042.1083
It worked for me.
I stopped Remote Desktop Service, copied the INI file from [here](https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini) to C:\Program Files\RDP Wrapper, then restarted Remote Desktop Service. 

![image](https://user-images.githubusercontent.com/22753145/124846832-41936d00-df5f-11eb-8b7e-0d0539632b2c.png)

**Comment by lucindrea** [comment] 2021-07-08 02:19
I got it working after trying different ini's and stumbled on a working one :)

**Comment by Ashwin-055** [comment] 2021-07-08 18:30
not working in windows 10 19041.1052
and my RDPConf.exe shows 19041.964

**Comment by keskinasil** [comment] 2021-08-03 18:37
Win 10 20H2 19042.1151

**Comment by orxortega** [comment] 2021-09-21 04:07
> Win 10 20H2 19042.1083
> It worked for me.
> I stopped Remote Desktop Service, copied the INI file from [here](https://github.com/sebaxakerhtc/rdpwrap.ini/blob/master/rdpwrap.ini) to C:\Program Files\RDP Wrapper, then restarted Remote Desktop Service.
> 
> ![image](https://user-images.githubusercontent.com/22753145/124846832-41936d00-df5f-11eb-8b7e-0d0539632b2c.png)

This ini file also works in 19042.1237

**Comment by affinityv** [comment] 2021-09-23 18:00
> This ini file also works in 19042.1237

Yes, but that's the Windows version, not the termsrv.dll version....

**Comment by sebaxakerhtc** [comment] 2022-06-20 12:06
Duplicate of https://github.com/stascorp/rdpwrap/issues/1220

**Closed as completed by sebaxakerhtc** 2022-06-20 12:06 UTC
