### ISSUE TITLE
not supported 10.0.19041.1387

### ISSUE THREAD

**Issue by MachoCR15** [stascorp/rdpwrap#1676] opened 2022-01-03 20:23 UTC
![image](https://user-images.githubusercontent.com/97060961/147976505-e1e1635c-1bb9-49c6-abb7-b6890ec5a72b.png)

someone have this error?

**Comment by sebaxakerhtc** [comment] 2022-01-04 10:16
Duplicate of https://github.com/stascorp/rdpwrap/issues/1630

**Closed as completed by sebaxakerhtc** 2022-01-04 10:16 UTC
