### ISSUE TITLE
10.0.22631.4037 not supported #3253

### ISSUE THREAD

**Issue by bellodku** [stascorp/rdpwrap#3267] opened 2024-09-08 11:25 UTC
Windows 11 22631.4037 show not support
it would be updated at 19 July 2024

please help

**Comment by bellodku** [comment] 2024-09-08 11:28
![image](https://github.com/user-attachments/assets/d01a1529-3ec3-4f18-95b0-381c328004b6)
[termsrv.zip](https://github.com/user-attachments/files/16921953/termsrv.zip)

**Comment by binarymaster** [comment] 2024-09-08 13:15
Duplicate of #3238.

**Closed as not planned by binarymaster** 2024-09-08 13:15 UTC
Labels: duplicate
