### ISSUE TITLE
10.0.22621.1928 not supported

### ISSUE THREAD

**Issue by faoggor** [stascorp/rdpwrap#2273] opened 2023-07-11 14:41 UTC
Hello

![image](https://github.com/stascorp/rdpwrap/assets/139246585/430c557a-f19d-4fde-9ee6-7c899eac0e07)

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/12015946/termsrv.zip)

**Comment by sashaqwert** [comment] 2023-07-11 17:57
Duplicate of https://github.com/stascorp/rdpwrap/issues/2258

**Closed as not planned by sashaqwert** 2023-07-11 17:57 UTC
Labels: duplicate
