### ISSUE TITLE
Not listening 6.3.9600.18928

### ISSUE THREAD

**Issue by stdfr33** [stascorp/rdpwrap#450] opened 2018-04-16 18:47 UTC
Listener State: Listening - Not Supported. Termsrv attached. Thanks!

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/1916768/termsrv.zip)

**Comment by binarymaster** [comment] 2018-04-16 18:49
Why don't you look at existing issues? Duplicate of #418.

**Closed by binarymaster** 2018-04-16 18:49 UTC

**Comment by stdfr33** [comment] 2018-04-16 18:52
Apologies. New to github.
