### ISSUE TITLE
Can Some One help Me

### ISSUE THREAD

**Issue by badr258** [stascorp/rdpwrap#3361] opened 2024-11-23 04:55 UTC
![Screenshot 2024-11-22 082939](https://github.com/user-attachments/assets/5368b48d-db8f-45f4-a978-0d34854a1167)

**Comment by binarymaster** [comment] 2024-11-23 10:05
Duplicate of https://github.com/stascorp/rdpwrap/issues/3285.

**Closed as not planned by binarymaster** 2024-11-23 10:05 UTC
Labels: invalid

**Comment by badr258** [comment] 2024-11-23 10:18
> Duplicate of #3285.

this not like my proplem bro

**Comment by binarymaster** [comment] 2024-11-23 10:36
In your case the RDP Wrapper is not even installed.

> Wrapper ver. N/A

Not a valid GitHub issue then.
