### ISSUE TITLE
Version 10.0.19041.789 Dont work - Unsuported

### ISSUE THREAD

**Issue by DavidFFerreira** [stascorp/rdpwrap#1342] opened 2021-03-06 15:32 UTC
Version 10.0.19041.789 Dont work - Unsuported

**Comment by Luuk34** [comment] 2021-03-06 17:24
see: https://github.com/stascorp/rdpwrap/issues/1314
![rdpwrap-10 0 19041 789](https://user-images.githubusercontent.com/7850737/110333385-d45be380-8021-11eb-8bf3-b1bdb42d4756.png)
[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/6101955/rdpwrap.zip)

In attached rdpwrap.zip you van find my rdpwrap.ini

**Comment by hereBo** [comment] 2021-03-07 10:31
still does not work

**Comment by NewyGuy** [comment] 2021-03-09 22:44
Add this to ini:

`
[10.0.19041.789]
LocalOnlyPatch.x86=1
LocalOnlyOffset.x86=B59D9
LocalOnlyCode.x86=jmpshort
SingleUserPatch.x86=1
SingleUserOffset.x86=3BC45
SingleUserCode.x86=nop
DefPolicyPatch.x86=1
DefPolicyOffset.x86=3E7C9
DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
SLInitHook.x86=1
SLInitOffset.x86=67BF8
SLInitFunc.x86=New_CSLQuery_Initialize

LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=88F41
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0CA4C
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=18A15
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=1D5BC
SLInitFunc.x64=New_CSLQuery_Initialize

[10.0.19041.789-SLInit]
bInitialized.x86=D0954
bServerSku.x86=D0958
lMaxUserSessions.x86=D095C
bAppServerAllowed.x86=D0964
bRemoteConnAllowed.x86=D096C
bMultimonAllowed.x86=D0970
ulMaxDebugSessions.x86=D0974
bFUSEnabled.x86=D0978

bInitialized.x64=106028
bServerSku.x64=10602C
lMaxUserSessions.x64=106030
bAppServerAllowed.x64=106038
bRemoteConnAllowed.x64=106040
bMultimonAllowed.x64=106044
ulMaxDebugSessions.x64=106048
bFUSEnabled.x64=10604C

`

**Comment by SHIINASAMA** [comment] 2021-03-11 05:49
> Add this to ini:
> 
> `
> [10.0.19041.789]
> LocalOnlyPatch.x86=1
> LocalOnlyOffset.x86=B59D9
> LocalOnlyCode.x86=jmpshort
> SingleUserPatch.x86=1
> SingleUserOffset.x86=3BC45
> SingleUserCode.x86=nop
> DefPolicyPatch.x86=1
> DefPolicyOffset.x86=3E7C9
> DefPolicyCode.x86=CDefPolicy_Query_eax_ecx
> SLInitHook.x86=1
> SLInitOffset.x86=67BF8
> SLInitFunc.x86=New_CSLQuery_Initialize
> 
> LocalOnlyPatch.x64=1
> LocalOnlyOffset.x64=88F41
> LocalOnlyCode.x64=jmpshort
> SingleUserPatch.x64=1
> SingleUserOffset.x64=0CA4C
> SingleUserCode.x64=Zero
> DefPolicyPatch.x64=1
> DefPolicyOffset.x64=18A15
> DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
> SLInitHook.x64=1
> SLInitOffset.x64=1D5BC
> SLInitFunc.x64=New_CSLQuery_Initialize
> 
> [10.0.19041.789-SLInit]
> bInitialized.x86=D0954
> bServerSku.x86=D0958
> lMaxUserSessions.x86=D095C
> bAppServerAllowed.x86=D0964
> bRemoteConnAllowed.x86=D096C
> bMultimonAllowed.x86=D0970
> ulMaxDebugSessions.x86=D0974
> bFUSEnabled.x86=D0978
> 
> bInitialized.x64=106028
> bServerSku.x64=10602C
> lMaxUserSessions.x64=106030
> bAppServerAllowed.x64=106038
> bRemoteConnAllowed.x64=106040
> bMultimonAllowed.x64=106044
> ulMaxDebugSessions.x64=106048
> bFUSEnabled.x64=10604C
> 
> `

it's worked for me,thank q!

**Comment by ricardobackk** [comment] 2021-03-15 14:02
I did it like the one above, adding this .ini, but after that the service doesn't start anymore ... what can I have done wrong?

**Comment by jnerim** [comment] 2021-03-19 03:16
Muchas Gracias, soy nuevo en esto, tendrás de casualidad por favor el ini ya agregado, para poder entender en que parte se agrega la configuración...
Saludos

**Comment by wtyytw0** [comment] 2021-03-19 10:41
Windows 10 version19042.867,  Remote desktop Version 10.0.19041.789
 I tried all these solutions, but still not supported

**Comment by andrej-annenski** [comment] 2021-03-21 06:30
> Windows 10 version19042.867, Remote desktop Version 10.0.19041.789
> I tried all these solutions, but still not supported

Check on which windows user the Remotedesktop Service is running. It can only be "Network Service", not LOCAL SERVICE.
https://i.stack.imgur.com/aPQka.png

**Comment by LiamKarlMitchell** [comment] 2021-03-22 02:57
It says "Network Service" for the user of the Remote Desktop service.
When RDPing I get this error.

Error code: 0x4 
Extended error code: 0x0 
Activity ID: {c52647d5-f685-4224-ae1f-e2adcdd30000}

This one fixed it for me.
https://github.com/stascorp/rdpwrap/issues/860

**Comment by wtyytw0** [comment] 2021-03-22 03:00
> > Windows 10 version19042.867, Remote desktop Version 10.0.19041.789
> > I tried all these solutions, but still not supported
> 
> Check on which windows user the Remotedesktop Service is running. It can only be "Network Service", not LOCAL SERVICE.
> https://i.stack.imgur.com/aPQka.png

thanks! we changed the .ini using cmd(under admin) and that worked.

**Comment by fermel01** [comment] 2021-05-03 21:35
> Muchas Gracias, soy nuevo en esto, tendrás de casualidad por favor el ini ya agregado, para poder entender en que parte se agrega la configuración ...
> Saludos

Does anyone have it complete, did I pass it on to us?

**Comment by sebaxakerhtc** [comment] 2022-03-30 13:09
Duplicate of https://github.com/stascorp/rdpwrap/issues/1317

**Closed as completed by sebaxakerhtc** 2022-03-30 13:09 UTC

**Comment by lenainjaune** [comment] 2022-12-01 16:17
@NewyGuy Great :) ! After installing the tool from install.bat (applications compressed zip version) with admin privileges, as RDPConf displayed "Listener state: Not listening [not supported]", [appending your configuration](https://github.com/stascorp/rdpwrap/issues/1342#issuecomment-794558507) in the end of **C:\Program Files\RDP Wrapper\rdpwrap.ini** (from notepad opened from an console with admin privileges) resolved the problem and worked perfectly for me on a fresh **Windows 10 Home 21H1 64-bit** system (Build version : **19043.928**).

Note : I am not a regular Windows user

[edit1] I stopped the **Terminal Server** service before and it restarted after [/edit1]

[edit2] In another not fresh installed system **Home 21H2 64-bits** (Build version : **19045.2251**), as the install failed with an "Access denied" error, I discovered that the problem came from the "Virus & threat protection" functionality which blocked all attempt to install ; after adding an exclusion for the uncompressed folder where the script install.bat is located (Virus & threat protection settings > Manage settings > Exclusions), as the service state uses the version **10.0.19044.2075** which was not supported, completing the INI file with the good configuration (see [here](https://github.com/stascorp/rdpwrap/issues/1992#issuecomment-1253357565)), now all work, I can access this Home system with RDP [/edit2]
