### ISSUE TITLE
Support for release 18362.418

### ISSUE THREAD

**Issue by JuezFenix** [stascorp/rdpwrap#941] opened 2019-12-12 20:03 UTC
Support for release 18362.418 please!!!

**Comment by Blame4** [comment] 2019-12-14 01:52
always provide termsrv.dll file for help

**Comment by QwertyTester** [comment] 2019-12-14 06:58
18363.535 is also not supported. I'm sorry.

**Comment by bojanhor** [comment] 2019-12-16 13:19
Hi,
 i am attaching file: termsrv.dll
i am attaching file: picture of gui

windows version info:
HAL Version= 10.0.18362.387

i hope this helps.

-----------------------------------------------------------------------------
more info from cmd:

C:\Program Files\RDP Wrapper>RDPWInst.exe -i -o
RDP Wrapper Library v1.6.2
Installer v2.5
Copyright (C) Stas'M Corp. 2017

[*] RDP Wrapper Library is already installed.

C:\Program Files\RDP Wrapper>RDPWInst.exe -w
RDP Wrapper Library v1.6.2
Installer v2.5
Copyright (C) Stas'M Corp. 2017

[*] Checking for updates...
[*] Current update date: 2018.10.10
[*] Latest update date:  2018.10.10
[*] Everything is up to date.

-----------------------------------------------------------------------

![Untitled](https://user-images.githubusercontent.com/58942593/70909896-caaa2280-200e-11ea-8686-c07d68a791f0.png)



[termsrv.zip](https://github.com/stascorp/rdpwrap/files/3968179/termsrv.zip)

**Comment by bojanhor** [comment] 2019-12-16 13:48
> Hi,
> i am attaching file: termsrv.dll
> i am attaching file: picture of gui
> 
> windows version info:
> HAL Version= 10.0.18362.387
> 
> i hope this helps.
> 
> more info from cmd:
> 
> C:\Program Files\RDP Wrapper>RDPWInst.exe -i -o
> RDP Wrapper Library v1.6.2
> Installer v2.5
> Copyright (C) Stas'M Corp. 2017
> 
> [*] RDP Wrapper Library is already installed.
> 
> C:\Program Files\RDP Wrapper>RDPWInst.exe -w
> RDP Wrapper Library v1.6.2
> Installer v2.5
> Copyright (C) Stas'M Corp. 2017
> 
> [_] Checking for updates... [_] Current update date: 2018.10.10
> [_] Latest update date: 2018.10.10 [_] Everything is up to date.
> 
> ![Untitled](https://user-images.githubusercontent.com/58942593/70909896-caaa2280-200e-11ea-8686-c07d68a791f0.png)
> 
> [termsrv.zip](https://github.com/stascorp/rdpwrap/files/3968179/termsrv.zip)


Hi, i just found ini file that is working (checked) with mentioned version:

[rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/3968273/rdpwrap.zip)

please folow instructions:



run uninstall.bat from previous version

stop the service running CMD as administrator: net stop termservice

unzip file: rdpwrap.zip and copy *.ini file to C:\Program Files\RDP Wrapper

start service running CMD as administrator: net start termservice

Reboot your PC!

when your pc rebooted, run RDPConf to check the states, make sure All states are green.
--

**Comment by dtsiapas** [comment] 2019-12-17 09:34
> > Hi,
> > i am attaching file: termsrv.dll
> > i am attaching file: picture of gui
> > windows version info:
> > HAL Version= 10.0.18362.387
> > i hope this helps.
> > more info from cmd:
> > C:\Program Files\RDP Wrapper>RDPWInst.exe -i -o
> > RDP Wrapper Library v1.6.2
> > Installer v2.5
> > Copyright (C) Stas'M Corp. 2017
> > [*] RDP Wrapper Library is already installed.
> > C:\Program Files\RDP Wrapper>RDPWInst.exe -w
> > RDP Wrapper Library v1.6.2
> > Installer v2.5
> > Copyright (C) Stas'M Corp. 2017
> > [_] Checking for updates... [_] Current update date: 2018.10.10
> > [_] Latest update date: 2018.10.10 [_] Everything is up to date.
> > ![Untitled](https://user-images.githubusercontent.com/58942593/70909896-caaa2280-200e-11ea-8686-c07d68a791f0.png)
> > [termsrv.zip](https://github.com/stascorp/rdpwrap/files/3968179/termsrv.zip)
> 
> Hi, i just found ini file that is working (checked) with mentioned version:
> 
> [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/3968273/rdpwrap.zip)
> 
> please folow instructions:
> 
> run uninstall.bat from previous version
> 
> stop the service running CMD as administrator: net stop termservice
> 
> unzip file: rdpwrap.zip and copy *.ini file to C:\Program Files\RDP Wrapper
> 
> start service running CMD as administrator: net start termservice
> 
> Reboot your PC!
> 
> ## when your pc rebooted, run RDPConf to check the states, make sure All states are green.

Thank you! I just tested it on 18363.535 and it works!

**Comment by oichan9821** [comment] 2019-12-19 14:42
Hello!
I also solved the problem thanks to rdpwrap.zip. 
Thank you very much.

**Comment by AlexMaxes** [comment] 2020-01-03 16:39
> > Hi,
> > i am attaching file: termsrv.dll
> > i am attaching file: picture of gui
> > windows version info:
> > HAL Version= 10.0.18362.387
> > i hope this helps.
> > more info from cmd:
> > C:\Program Files\RDP Wrapper>RDPWInst.exe -i -o
> > RDP Wrapper Library v1.6.2
> > Installer v2.5
> > Copyright (C) Stas'M Corp. 2017
> > [*] RDP Wrapper Library is already installed.
> > C:\Program Files\RDP Wrapper>RDPWInst.exe -w
> > RDP Wrapper Library v1.6.2
> > Installer v2.5
> > Copyright (C) Stas'M Corp. 2017
> > [_] Checking for updates... [_] Current update date: 2018.10.10
> > [_] Latest update date: 2018.10.10 [_] Everything is up to date.
> > ![Untitled](https://user-images.githubusercontent.com/58942593/70909896-caaa2280-200e-11ea-8686-c07d68a791f0.png)
> > [termsrv.zip](https://github.com/stascorp/rdpwrap/files/3968179/termsrv.zip)
> 
> Hi, i just found ini file that is working (checked) with mentioned version:
> 
> [rdpwrap.zip](https://github.com/stascorp/rdpwrap/files/3968273/rdpwrap.zip)
> 
> please folow instructions:
> 
> run uninstall.bat from previous version
> 
> stop the service running CMD as administrator: net stop termservice
> 
> unzip file: rdpwrap.zip and copy *.ini file to C:\Program Files\RDP Wrapper
> 
> start service running CMD as administrator: net start termservice
> 
> Reboot your PC!
> 
> ## when your pc rebooted, run RDPConf to check the states, make sure All states are green.

TX！it works on 10.0 18362

**Comment by sebaxakerhtc** [comment] 2022-06-20 10:18
Duplicate of https://github.com/stascorp/rdpwrap/issues/871

**Closed as completed by sebaxakerhtc** 2022-06-20 10:18 UTC
