### ISSUE TITLE
10.0.18362.836 not supported

### ISSUE THREAD

**Issue by Gans2308** [stascorp/rdpwrap#1966] opened 2022-08-23 00:34 UTC

**Comment by Gans2308** [comment] 2022-08-23 01:25
I writted file, I have support, but connection was failed. Continue only  1 user((

**Comment by sashaqwert** [comment] 2022-08-23 12:33
RDPConf screenshot, please!

Also this issue will closed tomorrow.

**Comment by sashaqwert** [comment] 2022-08-24 10:07
Duplicate of https://github.com/stascorp/rdpwrap/issues/1083

I know, thet original issue has incorrect title.

**Closed as not planned by sashaqwert** 2022-08-24 10:07 UTC
