### ISSUE TITLE
Windows 10 10.0.19044.2846 x86 (64 bits) need support

### ISSUE THREAD

**Issue by cyguard2** [stascorp/rdpwrap#2191] opened 2023-05-05 13:09 UTC
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/11406497/termsrv.zip)
Thank you!

**Comment by sebaxakerhtc** [comment] 2023-05-05 13:59
Duplicate of https://github.com/stascorp/rdpwrap/issues/2131
Always look at termsrv.dll version, not the Windows version

**Closed as completed by sebaxakerhtc** 2023-05-05 13:59 UTC
Labels: duplicate
