### ISSUE TITLE
How to solve this problem with WINDOWS 10.0.17763.253 ?

### ISSUE THREAD

**Issue by Ontariombd** [stascorp/rdpwrap#659] opened 2019-02-11 16:08 UTC
![__001](https://user-images.githubusercontent.com/47528149/52575965-79923680-2e1f-11e9-9494-4edbb371f7ec.jpg)

**Comment by binarymaster** [comment] 2019-02-11 16:41
Duplicate of #606.

**Closed as completed by binarymaster** 2019-02-11 16:41 UTC
Labels: duplicate
