### ISSUE TITLE
All green pass but cannot multiuser connection at one time

### ISSUE THREAD

**Issue by Cyanogen01** [stascorp/rdpwrap#2156] opened 2023-03-27 09:47 UTC
I have add all my RDP users to Remote Desktop users group manually as 

![useradded](https://user-images.githubusercontent.com/62990178/227904846-6d9dc20a-5b2a-4a45-804e-8b91dcf2a2d8.png)

and license seems not wrong

![nowrong](https://user-images.githubusercontent.com/62990178/227905052-a26af0c4-2ff8-4d83-bc3f-b53825ae270a.png)

But when another user attempts to connect, the using user will still be kicked off.

![cannot](https://user-images.githubusercontent.com/62990178/227906091-bc2ded82-d395-431d-9712-04b0b87cbcbd.png)

Could anyone help me to solve the problem?

**Comment by sashaqwert** [comment] 2023-03-28 06:48
Try restart service or reboot

or

Try:
1. Download RDP Wrapper 1.6.2 and extract this to any directory.
2. Place `rdpwrap.ini` in the same directory.
3. Open CMD as administrator
4. Execute this commands
```
cd C:\path\to\directory\
rdpwinst -u -k
rdpwinst -i
```
5. Enjoy!

Original message: https://t.me/rdpwrap/49131

**Comment by sashaqwert** [comment] 2023-03-28 06:49
One `termsrv.dll` version = ONE opened issue.

**Comment by sashaqwert** [comment] 2023-03-28 06:50
Duplicate of https://github.com/stascorp/rdpwrap/issues/2125

**Closed as not planned by sashaqwert** 2023-03-28 06:50 UTC
Labels: duplicate
