### ISSUE TITLE
rdp wrapper not supported

### ISSUE THREAD

**Issue by jaleedraja1** [stascorp/rdpwrap#1699] opened 2022-01-27 20:34 UTC
rdp wrapper is showing not supported
my windows os is 19043.1466

**Comment by sashaqwert** [comment] 2022-01-28 15:12
> my windows os is 19043.1466

This is not a ```termsrv.dll``` version.
RDPConf screenshot, please!

**Comment by sebaxakerhtc** [comment] 2022-01-29 09:39
Duplicate of https://github.com/stascorp/rdpwrap/issues/1630

**Closed as completed by sebaxakerhtc** 2022-01-29 09:39 UTC
