### ISSUE TITLE
10.0.17763.3469 Not working with updated ini

### ISSUE THREAD

**Issue by Killj0y1** [stascorp/rdpwrap#2017] opened 2022-10-13 21:36 UTC
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/9780895/termsrv.zip)
Got the new ini updated for this version and have several workstations no longer working. Am I missing something? I attached the termsrv.dll. RDPConf.exe comes back as everything looks good but testing with RDPCheck.exe and external devices all fail. I trieed the ini from #1994 which seems to be the same version.

![image](https://user-images.githubusercontent.com/106001343/195717729-f7ee3c47-fcb0-4911-b19a-a3237d050af7.png)

**Comment by P0limac** [comment] 2022-10-14 07:22
Hello, same problem here. I just reinstalled rdp wrapper and restarted pc. Now is fine again.

**Comment by Killj0y1** [comment] 2022-10-14 14:40
> Hello, same problem here. I just reinstalled rdp wrapper and restarted pc. Now is fine again.

Yea tried the same but still did not work sadly.

**Comment by tetas26** [comment] 2022-10-14 21:09
Are using 32 bit O/S

**Comment by Killj0y1** [comment] 2022-10-14 21:17
> Are using 32 bit O/S

No 64bit. I managed to get 1 test workstation working by uninstalling latest updates but that's a temporary fix. 

![image_2022-10-14_161737588](https://user-images.githubusercontent.com/106001343/195945544-023df431-e0c4-459d-ab1b-2d8b7adad63e.png)

**Comment by sashaqwert** [comment] 2022-10-15 10:46
One `termsrv.dll` version = ONE opened issue...

**Comment by sashaqwert** [comment] 2022-10-15 10:46
Duplicate of https://github.com/stascorp/rdpwrap/issues/1994

**Closed as not planned by sashaqwert** 2022-10-15 10:46 UTC
Labels: duplicate

**Comment by sashaqwert** [comment] 2022-10-15 10:48
> RDPConf.exe comes back as everything looks good but testing with RDPCheck.exe and external devices all fail.

Try:
1. Download RDP Wrapper 1.6.2 and extract this to any directory.
2. Place `rdpwrap.ini` in the same directory.
3. Open CMD as administrator
4. Execute this commands
```
cd C:\path\to\directory\
rdpwinst -u -k
rdpwinst -i
```
5. Enjoy!

Original message: https://t.me/rdpwrap/49131

**Comment by Killj0y1** [comment] 2022-10-24 18:52
> > RDPConf.exe comes back as everything looks good but testing with RDPCheck.exe and external devices all fail.
> 
> Try:
> 
> 1. Download RDP Wrapper 1.6.2 and extract this to any directory.
> 2. Place `rdpwrap.ini` in the same directory.
> 3. Open CMD as administrator
> 4. Execute this commands
> 
> ```
> cd C:\path\to\directory\
> rdpwinst -u -k
> rdpwinst -i
> ```
> 
> 5. Enjoy!
> 
> Original message: https://t.me/rdpwrap/49131

Ok this seems to have worked. Any insight as to why this method of installing works and not the default method? For future referance of course. I want to understand the why if possible.
