### ISSUE TITLE
10.0.22621.1702 need help！

### ISSUE THREAD

**Issue by qltre** [stascorp/rdpwrap#2205] opened 2023-05-18 07:54 UTC
Attached is the dll file，Please help to write an ini file，thanks!
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/11505665/termsrv.zip)

**Comment by sashaqwert** [comment] 2023-05-18 08:34
termsrv.dll version != Windows version.

Your version is `10.0.22621.608`

![изображение](https://github.com/stascorp/rdpwrap/assets/24974508/eb994366-0b91-4628-a2f5-12e8e7c247d3)

**Comment by sashaqwert** [comment] 2023-05-18 08:37
Also in your RDPConf Installed and N/A --> see https://github.com/stascorp/rdpwrap/issues/1883

<details>
<summary>RDPConf (from provided ZIP)</summary>

![изображение](https://github.com/stascorp/rdpwrap/assets/24974508/08767ef7-1f6d-4e4a-bdc9-39bfb5e1c82d)

</details>

**Comment by sashaqwert** [comment] 2023-05-18 08:40
> Your version is `10.0.22621.608`

Duplicate of https://github.com/stascorp/rdpwrap/issues/2006

**Closed as not planned by sashaqwert** 2023-05-18 08:40 UTC
Labels: duplicate

**Comment by qltre** [comment] 2023-05-18 08:43
Thank you for your help. My version of termsrv.dll is 10.0.22621.608, but I found the previous answer, using the ini file you provided before, the remote connection will be broken immediately. Do you know the problem?
![517b344567dad1f4bab276f4efb1557](https://github.com/stascorp/rdpwrap/assets/120163878/5a8abe63-7e8b-4bc9-8fa7-6c13bd59372c)

**Comment by sashaqwert** [comment] 2023-05-18 12:59
> Do you know the problem?

Most likely the problem is that RDPConf shows N/A instead of `termsrv.dll` version. I don't know the exact solution.
