### ISSUE TITLE
Windows 10 Pro 21H2 19044.1387 not working

### ISSUE THREAD

**Issue by keerthir99** [stascorp/rdpwrap#1650] opened 2021-12-07 05:19 UTC
![Screenshot (6)](https://user-images.githubusercontent.com/94477131/144971050-80fbd155-88ff-4237-99ed-a1f261c5d9e3.png)

**Comment by sebaxakerhtc** [comment] 2021-12-07 09:32
Duplicate of https://github.com/stascorp/rdpwrap/issues/1630

**Closed as completed by sebaxakerhtc** 2021-12-07 09:32 UTC
