### ISSUE TITLE
win 11   ver 22631.3447 

### ISSUE THREAD

**Issue by adslccn** [stascorp/rdpwrap#2583] opened 2024-04-19 16:01 UTC
Pls, help me ^_^

**Comment by loyejaotdiqr47123** [comment] 2024-04-21 08:29
Duplicate of #2549

**Comment by sashaqwert** [comment] 2024-04-22 13:33
Duplicate of https://github.com/stascorp/rdpwrap/issues/2549

**Closed as not planned by sashaqwert** 2024-04-22 13:33 UTC
Labels: duplicate
