### ISSUE TITLE
Win10  19042.964  support offered to include on ini.

### ISSUE THREAD

**Issue by trixocom** [stascorp/rdpwrap#1403] opened 2021-05-21 16:52 UTC
Please load 19042.964 info to the ini! I can collaborate with information is you need. thanks!

**Comment by binbard** [comment] 2021-05-23 07:42
#1397 tried this?

**Comment by trixocom** [comment] 2021-05-24 01:17
yes thanks!!

**Comment by sebaxakerhtc** [comment] 2022-06-20 13:23
Duplicate of https://github.com/stascorp/rdpwrap/issues/1384

**Closed as completed by sebaxakerhtc** 2022-06-20 13:23 UTC
