### ISSUE TITLE
Need help with windows build 19042.631   System32 DLL attached

### ISSUE THREAD

**Issue by damienwhite** [stascorp/rdpwrap#1336] opened 2021-02-28 13:21 UTC
Hi,

I have tried to attach as much information as possible. I could not find any solutions for my specific build of windows 10 so would greatly appreciate if someone could help me with the settings for my build version

Thanks very much in advance.

I have attached the termsrv file inside this zip. It is from windows/system32

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/6056835/termsrv.zip)

Here are the details of the windows version.

Here is a screen shot of the RDFConf output
![image](https://user-images.githubusercontent.com/6746900/109419815-6b71db80-7a23-11eb-9740-4a3ba989c8e1.png)

Here are the details of the windows installation

![image](https://user-images.githubusercontent.com/6746900/109419833-9bb97a00-7a23-11eb-93ab-4c037fd41e1b.png)

**Comment by sebaxakerhtc** [comment] 2022-06-20 12:59
Duplicate of https://github.com/stascorp/rdpwrap/issues/1004

**Closed as completed by sebaxakerhtc** 2022-06-20 12:59 UTC
