### ISSUE TITLE
Not working on 19044.1620 release, sombody has some solution for this?

### ISSUE THREAD

**Issue by airtonlj** [stascorp/rdpwrap#1790] opened 2022-03-26 02:30 UTC

**Comment by Raytow** [comment] 2022-03-26 10:51
The same to you, waiting for solution.

**Comment by sashaqwert** [comment] 2022-03-26 15:46
Duplicate of https://github.com/stascorp/rdpwrap/issues/1786

**Comment by sebaxakerhtc** [comment] 2022-03-26 16:58
> Duplicate of #1786

**Closed as completed by sebaxakerhtc** 2022-03-26 16:58 UTC
