### ISSUE TITLE
Not Supported 10.0.22000.527

### ISSUE THREAD

**Issue by batero2000** [stascorp/rdpwrap#1742] opened 2022-02-23 02:50 UTC
New Windows 11 update has no support for old ini file. Please update.

Thanks in advance!

**Comment by sebaxakerhtc** [comment] 2022-02-24 08:18
Duplicate of https://github.com/stascorp/rdpwrap/issues/1698

**Closed as completed by sebaxakerhtc** 2022-02-24 08:18 UTC

**Comment by batero2000** [comment] 2022-02-24 17:21
> Duplicate of #1698

No, it is not, that is version .469, I'm asking for .527

**Comment by sebaxakerhtc** [comment] 2022-02-24 17:23
> > Duplicate of #1698
> 
> No, it is not, that is version .469, I'm asking for .527

So... Double check termstv.dll version

**Comment by XilinWang0108** [comment] 2022-03-01 05:25
> version .469 is suitable for .527
![1](https://user-images.githubusercontent.com/76676235/156110189-10838366-389b-486b-9a02-3f0974e68cd5.jpg)
![2](https://user-images.githubusercontent.com/76676235/156110224-e0dc7d63-d633-4839-aa26-695b2c50cac8.jpg)

**Comment by XilinWang0108** [comment] 2022-03-01 05:27
> > Duplicate of #1698
> 
> No, it is not, that is version .469, I'm asking for .527

version .469 is suitable for .527
![2](https://user-images.githubusercontent.com/76676235/156110388-e7eaf378-a787-465b-8dfe-d028be570d2c.jpg)
![1](https://user-images.githubusercontent.com/76676235/156110392-3b50ec53-7b3d-4d81-a4ad-e02ed4852408.jpg)
