### ISSUE TITLE
termsrv.dll 10.0.19041.84

### ISSUE THREAD

**Issue by alturismo** [stascorp/rdpwrap#1055] opened 2020-04-18 19:08 UTC
Hi, attached the current termsrv.dll from the 05 2020 update which has been released in previews now

may someone can figure out how to get it working again ;)

[termsrv.zip](https://github.com/stascorp/rdpwrap/files/4497448/termsrv.zip)

**Comment by monta990** [comment] 2020-04-20 03:19
Same situation too.

**Comment by DrDrrae** [comment] 2020-04-20 23:56
Here's the additions to rdpwrap.ini for this version for 64bit only.
Make sure there's a blank link at the end of the file.

```
[10.0.19041.84]
LocalOnlyPatch.x64=1
LocalOnlyOffset.x64=87611
LocalOnlyCode.x64=jmpshort
SingleUserPatch.x64=1
SingleUserOffset.x64=0BF0C
SingleUserCode.x64=Zero
DefPolicyPatch.x64=1
DefPolicyOffset.x64=17ED5
DefPolicyCode.x64=CDefPolicy_Query_eax_rcx
SLInitHook.x64=1
SLInitOffset.x64=1BDFC
SLInitFunc.x64=New_CSLQuery_Initialize


[10.0.19041.84-SLInit]
bInitialized.x64      = 103FF8
bServerSku.x64        = 103FFC
lMaxUserSessions.x64  = 104000
bAppServerAllowed.x64 = 104008
bRemoteConnAllowed.x64= 104010
bMultimonAllowed.x64  = 104014
ulMaxDebugSessions.x64= 104018
bFUSEnabled.x64       = 10401C
```

Entire file
https://github.com/DrDrrae/rdpwrap/blob/72e6b9ec967d50c9e213fce65422099edceecc6e/res/rdpwrap.ini

**Comment by alturismo** [comment] 2020-04-21 04:29
@DrDrrae thank you very much

**Comment by affinityv** [comment] 2020-04-21 18:36
Okay RDPConf.exe was all that we needed.... your dll is covered [here](https://github.com/stascorp/rdpwrap/issues/1022#issuecomment-596437997).

**Comment by sebaxakerhtc** [comment] 2022-06-20 10:31
Duplicate of https://github.com/stascorp/rdpwrap/issues/1004

**Closed as completed by sebaxakerhtc** 2022-06-20 10:31 UTC
