### ISSUE TITLE
NlaSvc - StartService error (code 1056)

### ISSUE THREAD

**Issue by yo1995** [stascorp/rdpwrap#159] opened 2016-09-15 13:50 UTC
Log below: 
```console
RDP Wrapper Library v1.6
Installer v2.3
Copyright (C) Stas'M Corp. 2016

[*] Notice to user:
  - By using all or any portion of this software, you are agreeing
  to be bound by all the terms and conditions of the license agreement.
  - To read the license agreement, run the installer with -l parameter.
  - If you do not agree to any terms of the license agreement,
  do not use the software.
[*] Installing...
[*] Terminal Services version: 6.1.7601.18637
[+] This version of Terminal Services is fully supported.
[+] TermService found (pid 6764).
[*] Shared services found: CryptSvc, Dnscache, LanmanWorkstation, NlaSvc, TapiSr
v
[*] Extracting files...
[+] Folder created: C:\Program Files\RDP Wrapper\
[*] Downloading latest INI file...
[+] Latest INI file -> C:\Program Files\RDP Wrapper\rdpwrap.ini
[+] Extracted rdpw64 -> C:\Program Files\RDP Wrapper\rdpwrap.dll
[*] Configuring service library...
[*] Checking dependencies...
[*] Checking CertPropSvc...
[*] Checking SessionEnv...
[*] Terminating service...
[*] Starting CryptSvc...
[*] Starting Dnscache...
[*] Starting LanmanWorkstation...
[*] Starting NlaSvc...
[-] StartService error (code 1056).
[*] Starting TapiSrv...
[*] Starting TermService...
[*] Configuring registry...
[*] Configuring firewall...
确定。

[+] Successfully installed.
______________________________________________________________

You can check RDP functionality with RDPCheck program.
Also you can configure advanced settings with RDPConf program.
```

Apparently, the problem is about a service called "Network Localtion Awareness". 
The strange thing is that when I checked my services.msc list, the referred services is enabled.

![1](https://cloud.githubusercontent.com/assets/9660181/18551881/f13aad40-7b8c-11e6-9ecc-c825f1788942.PNG)
![2](https://cloud.githubusercontent.com/assets/9660181/18552156/dbe12dc4-7b8d-11e6-9b75-8604564b3cdd.PNG)

Another strange thing is that when I downloaded the 1.61 version and installed it with -o parameter, the conf.exe still yields a 1.5.0.0 version as the picture below. Even after updating it remains the same.
![3](https://cloud.githubusercontent.com/assets/9660181/18552157/dc0ee782-7b8d-11e6-91e1-99eb5ee3e9df.PNG)

Please give me some instruction about this issue. Thanks !
My dll version is 6.1.7601.18637.

**Comment by yo1995** [comment] 2016-09-15 13:54
After uninstall and reinstall, the error in the log disappear but the connection refused problem remains.

**Comment by binarymaster** [comment] 2016-09-19 13:01
According to https://msdn.microsoft.com/en-us/library/windows/desktop/ms681383(v=vs.85).aspx

```
ERROR_SERVICE_ALREADY_RUNNING

  1056 (0x420)
  An instance of the service is already running.
```

This is not an error, just ignore it. About the version, it's a duplicate of issue #100.

**Closed by binarymaster** 2016-09-19 13:01 UTC
Labels: wontfix
