### ISSUE TITLE
RDP users service not working error so

### ISSUE THREAD

**Issue by Gnanama** [stascorp/rdpwrap#1702] opened 2022-01-28 18:01 UTC
remote server error 1075 the dependency service does not exist or has been marked for deletion

**Comment by Gnanama** [comment] 2022-01-28 18:02
Windows server 2016

**Comment by sashaqwert** [comment] 2022-01-29 07:33
Please, restore backup of registry from clean system.

Backup from LTSC 2019 (I'm don't know this from client or server): 
[TerminalService_1809_LTSC.zip](https://github.com/stascorp/rdpwrap/files/7963181/TerminalService_1809_LTSC.zip)
Original: https://t.me/rdpwrap/41015

**Comment by sebaxakerhtc** [comment] 2022-01-29 09:19
Duplicate of https://github.com/stascorp/rdpwrap/issues/1701

**Closed as completed by sebaxakerhtc** 2022-01-29 09:19 UTC
