### ISSUE TITLE
new update windows 10 

### ISSUE THREAD

**Issue by turtle01** [stascorp/rdpwrap#2015] opened 2022-10-12 11:55 UTC
update windows 10 kb5018410
listener state not listening

**Comment by sashaqwert** [comment] 2022-10-12 14:11
Please, attach your RDPConf screenshot and `termsrv.dll`.

**Comment by kda406** [comment] 2022-10-12 15:46
Same issue for me.
![2075](https://user-images.githubusercontent.com/8987616/195388591-429d4230-21b3-4b13-a5f5-df71ec217c11.JPG)
[termsrv.zip](https://github.com/stascorp/rdpwrap/files/9766598/termsrv.zip)

**Comment by turtle01** [comment] 2022-10-12 15:55
Thank you, there is no way to make screenshots

**Comment by sashaqwert** [comment] 2022-10-12 16:30
Duplicate of https://github.com/stascorp/rdpwrap/issues/1992

**Closed as not planned by sashaqwert** 2022-10-12 16:30 UTC
Labels: duplicate
